### ISSUE TITLE
two variables has same name

### ISSUE THREAD

**Issue by MozhuCY** [frida/frida#1007]

**Comment by MozhuCY** [comment]
I have some problems
such as a class :
class A {
public int d;
public boolean d;
}
and a function  : public test(A a,String s){...}
I wanna get a.d(int),but the two variables has same name,how can i get their values?

**Comment by H0r53** [comment]
I'm not seeing how this is at all related to frida and therefore this is not an appropriate place for your issue. Regardless, it looks like you are writing code in C. Your compiler should complain about an ambiguity in the names of properties in class A. The code should not compile in the first place. Simple solution, change one of the variable names.

**Comment by MozhuCY** [comment]
I'm sorry, I didn't describe my problem clearly,The situation is that I am analyzing an apk file,but the JEB decomplier and Jadx give me the same Source code such as:

import com.xxx;
import com.xxx;

public class abcw {
    public String a;
    public int a;
    public long a;
    public boolean a;
    public long b;
    public String b;
    public int b;
    public boolean b;
    public boolean c;
    public int c;
    public long c;
    public int d;
    public boolean d;
    public int e;
    public boolean e;
    public boolean f;
    public boolean g;
    public boolean h;
    public boolean i;

    public abcw() {
        super();
        this.a = true;
        this.e = -1;
    }
}

and the next function argument is this strange class,such as:
    public void a(String arg11, abcw arg12, int arg13) {
        int v9 = 4;
        int v8 = 3;
        int v6 = 2;
        .......
    }

i wanna get the class abcw.d by frida,Frida can hook an overload function,but i have no idea how can i get it.
this is my code:
Java.perform(function(){
    adsh.a.overload("java.lang.String","abcw","int").implementation = function() {
        //console.log(arguments[1].d); i wanna get the values of public boolean d
        var ret = this.a.apply(this,arguments);
    }
})

**Comment by srcdes** [comment]
When a field and method having same name each other, you can access field by prefixing `_`. Read [this](https://www.frida.re/docs/examples/android/#example-tool-built-for-an-android-ctf) and [this](https://github.com/frida/frida/issues/833).

I don't know why decompiler converts other variables to have same name. Try this instead. For me it's working:

```bash
$ jadx --show-bad-code --output-dir ./decompiled --deobf ./base.apk
```

**Comment by 1356228082qqcom** [comment]
> 
how about using reflect?
