### ISSUE TITLE
Frida on_message bug when len(message['payload']) == 0

### ISSUE THREAD

**Issue by H0r53** [frida/frida#1008]
When using **script.on('message', on_message)** to send data from frida to a python driver, the following error is thrown from frida's _core.py_ if the length of a message payload is 0.

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 295, in _on_message
    elif mtype == 'send' and isinstance(payload, list) and payload[0] == 'frida:rpc':
IndexError: list index out of range
`

This results in annoying messages being printed to standard error. 
An example of how this would happen would be if a binary does not include imports, but a python script attempts to use frida to store import data. For example:

        module_name = 'some_process'
        imports = []

        def on_message(message, data):
            if len(message['payload']) == 0:
                pass
            for item in message['payload']:
                imports.append(item)

        source = 'send(Module.enumerateImports("%s"));' % module_name
        script = session.create_script(source)
        script.on('message', on_message)
        script.load()
        session.detach()

The most obvious fix would be to edit frida's core.py line to the following:

`elif mtype == 'send' and isinstance(payload, list) and len(payload) > 0 and payload[0] == 'frida:rpc':`

**Comment by oleavr** [comment]
Thanks, fixed!
