### ISSUE TITLE
System-installed autotools seems to get picked up instead of Frida's version

### ISSUE THREAD

**Issue by winsun** [frida/frida#102]
when i make python-mac PYTHON=/usr/bin/python, the follower compile's error will occur:

checking dynamic linker characteristics... darwin13.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking for unsigned long long int... yes
checking for long double... yes
checking for long long int... yes
checking elf.h usability... no
checking elf.h presence... no
checking for elf.h... no
checking sys/elf.h usability... no
checking sys/elf.h presence... no
checking for sys/elf.h... no
checking Apple OS type... Mac
checking for struct mallinfo.arena... no
../../../frida-gum/configure: line 17384: syntax error near unexpected token `GUM,'
../../../frida-gum/configure: line 17384:`PKG_CHECK_MODULES(GUM, $pkg_modules)'
make[1]: **\* [build/tmp-mac-x86_64/frida-gum/Makefile] Error 2
make: **\* [python-mac] Error 2

can help me what's wrong? how can i fix that?

**Comment by oleavr** [comment]
Hi,

Do you have any autoconf/automake/etc. on your PATH? E.g. as installed by Homebrew.

**Comment by winsun** [comment]
@oleavr,
in my mac osx 10.9, autoconf and automake are in /usr/local/bin directory, i can't understand what's your mean ?

**Comment by winsun** [comment]
when i brew install pkg-config, this error not occur. but  
checking pkg-config is at least version 0.9.0... ../../../frida-gum/configure: line 17531: /Users/winsunxu/GitHub/frida/build/toolchain-mac-x86_64/bin/pkg-config: No such file or directory
no
checking for GUM... no
configure: error: in `/Users/winsunxu/GitHub/frida/build/tmp-mac-x86_64/frida-gum':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables GUM_CFLAGS
and GUM_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
make[1]: *** [build/tmp-mac-x86_64/frida-gum/Makefile] Error 1
make: *** [python-mac] Error 2

**Comment by oleavr** [comment]
Please make sure you don't have autoconf/automake/pkg-config/etc. on your PATH, because Frida has its own toolchain with those things. The issue here seems to be that your system-installed binaries are getting picked up instead, which is a bug in our build system. (If you want to look into that that would be most appreciated!)
