### ISSUE TITLE
Failed to enumerate applications: unable to find process with name 'system_server'

### ISSUE THREAD

**Issue by kaleemshaik7867** [frida/frida#1025]
Hello Team,

I am using frida 12.7.4 on both MAC book and  android running root privileges with OS 6.0.1

I have started frida-server & on my android device with root privileges and it shows the process name. 

But when I run frida-ps -Uai I am getting the below error 
Failed to enumerate applications: unable to find process with name 'system_server'

Can you please help me to resolve the process 
![frida Mac](https://user-images.githubusercontent.com/7692857/65379835-46325700-dce0-11e9-8718-5c045b5b448d.png)
![frida server android](https://user-images.githubusercontent.com/7692857/65379838-46325700-dce0-11e9-8382-7928374cc3b0.png)

**Comment by kaleemshaik7867** [comment]
First need to run su and run frida-server

**Comment by JasmineScholz** [comment]
I'm still having an issue. My target application isn't showing frida-ps -U but is in frida-ps -Uai.
How can I made this run on frida-ps -U so I can open the application with frida and objection?

**Comment by decodewithdinesh-glitch** [comment]
Hii @EthanV181 

Did you get a solution bro. I am also facing the same
