### ISSUE TITLE
Hooking upon iOS app launching takes too long and killed by springboard

### ISSUE THREAD

**Issue by guitarfeng** [frida/frida#103]
Thank all the maintainers for this amazing project.

I have one issue about hooking upon iOS app launching (the target logic only triggers during app launching). I use the following command to do this:
 frida-trace -U -f  $BUNDLE_ID -m "-[xxx_class xxx_method]"
The app can be launched by frida and hangs in the first page during searching for the specific method.
Unfortunately, after a while, the app is killed by the Springboard due to the following error:
 "<Warning>: Forcing crash report of <FBApplicationProcess: 0x15ed82230; xxx; pid: xxx> (reason: 1, description: $BUNDLEID failed to launch in time)"

I think it's a common scenario using frida to hook app launching related logics. Is there any trick I can use to avoid this issue? Any response would be helpful. Thanks.

**Comment by oleavr** [comment]
Hi and thanks for reporting,

Which iOS version is this on? There is a known issue where we don't yet do anything about that built-in timeout, so if the instrumentation logic takes too long you will run into this issue. However, I have been wanting to optimize the Objective-C method resolving, as it would be nice to reduce that delay anyway, and it means we can figure out how to disable the timeout at a later point.

Cheers

**Comment by oleavr** [comment]
This issue should now be fixed in the latest [6.2.1](http://www.frida.re/news/2016/02/01/frida-6-2-released/) released today.
