### ISSUE TITLE
Hooking of variables and understanding Frida's $new

### ISSUE THREAD

**Issue by localacct** [frida/frida#1035]
Hi

# Question 1
I am trying to understand more about how frida works and I was trying to hook some variables. As an example

Snippet 1
````
public class AClass {
    public static boolean AClassVariable = false;

    public AMethod {
        int AnInteger = 0;
    }
}
````

I noticed that I can access the AClassVariable if I do the following

````
var fridaClass = Java.use("com.path.to.AClass");
console.log(fridaClass.AClassVariable);
````
However, I cannot access AnInteger even if I were to instantiate a new instance

````
var classInstance = fridaClass.$new();
console.log(classInstance.AMethod.AnInteger);
````

I realized that it does not work that way. So is there a way to access a function's local variables?

# Question 2

Snippet 2
````
public class theMainClass {
    boolean JustAName;
    
    public theMainClass (Context context) {
    // ....
    }
    
    public boolean JustAName() {
    // ....
    }
}
````

In this example, because a function and a variable has the same name, if I were to access JustAName, Frida will tell me its a function.

````
var second = Java.use("com.path.to.theMainClass");
console.log(second.JustAName);
````

Frida output
````
function a() { [ecmascript code] }
````

How can I get to choose which one I want to access?

Additionally, I would like to know if the below code is correct. Using Snippet 2 as the example

````
var myInstance = second.$new();
````
I will get an error saying
````
Error: <init>(): argument count of 0 does not match any of:
	.overload('android.content.Context')
````
So I modified the code
````
var myInstance = second.$new.overload('android.content.Context');
console.log(myInstance);
console.log(myInstance.methodName);
````

Frida output
````
function () { [ecmascript code] }
theMainClass
````

Frida will say that myInstance is a method and the name is the same as theMainClass, so I assume its the constructor? However, if I tried to call the function JustAName(), I get the following error
````
TypeError: undefined not callable (property 'JustAName' of [object Function])
````

So what did I do wrong? Any advice is appreciated.

**Comment by srcdes** [comment]
**For question 1:** Duplicates https://stackoverflow.com/a/58153506/9304999 .. You can't access local variable. You should access use site of the variable.

**For question 2:**
- For first part(accessing `JustAName`) of your question, you can't access field too. You can only hook or access a method. No field, No local variable.
- `second.$new.overload('android.content.Context');` is correct. When there are two or more methods having same signature, you should use `.overload()`.
- You can't access field `JustAName`. 

Before you write a question, it is good to search your question in google, first. :)

**Comment by localacct** [comment]
Hi @srcdes 

Thanks for the details, closing this issue.

**Comment by localacct** [comment]
Hi @srcdes 

Sorry, one more question. When I used

````
var myInstance = second.$new.overload('android.content.Context');
myInstance();
````

I will get an error
````
TypeError: cannot read property '$handle' of undefined
````

Am I using the overload correctly? It seems that myInstance is still undefined.

**Comment by srcdes** [comment]
If you want to create a new instance of your class, you should use `$new`, not `$init`. The `$init` is used for hooking a constructor call. Try this way:

```js
var the_context = /* you should get context instance through getActivity(), getApplicationContext() or, etc... */

var second = Java.use("com.path.to.theMainClass");
var myInstance = second.$new.overload('android.content.Context').call(the_context);
// myInstance is now just an instance of `theMainClass`. It is not a method reference. Do not call it, like `myInstance()`.
```

I think it is best to ask your question on **stackoverflow** instead of filing an issue.

**Comment by localacct** [comment]
Hi @srcdes 

Thanks for the guidance.

**Comment by effortlessdevsec** [comment]
**QUESTION -1**

`package com.example.demotest;


public  class xyz

{
    public static boolean AClassVariable = false;

    private void show()

    {

        System.out.println("Private class");

    }

}
`
Not able to access AClassVariable variable. showing [object object] . 
`Java.perform(() => {
  const abc = Java.use('com.example.demotest.xyz');
  console.log(abc.x)

});`
