### ISSUE TITLE
Failed to load script

### ISSUE THREAD

**Issue by Soutcast** [frida/frida#1038]
I am currently experiencing an issue when trying to connect frida to a decrypted ios app. This is the output from terminal:

`self._update_status("Failed to load script: {error}".format(error=e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 34: ordinal not in range(128)`

I installed frida through `sudo pip install frida-tools` and I am currently running it on macos mojave trying to connect to a jailbroken ipad running ios 9.3.5.

I was just wondering if anyone could shed some light on why this issue is caused and how to fix it. If any extra output is required please let me know so I can provide it.

**Comment by bannsec** [comment]
Would appear that Frida is attempting to decode something in memory as an ASCII string when it is not.

Guessing you'll need to provide more info, such as full backtrace, steps to reproduce, and example binary if possible.

**Comment by Soutcast** [comment]
The full error is:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/frida_tools/application.py", line 527, in _run
    work()
  File "/Library/Python/2.7/site-packages/frida_tools/application.py", line 301, in _try_start
    self._start()
  File "/Library/Python/2.7/site-packages/frida_tools/repl.py", line 151, in _start
    self._update_status("Failed to load script: {error}".format(error=e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 34: ordinal not in range(128)`

Steps to reproduce:

1. I manually decrypted the app (Medicare)
2. I patched fridagadget.dylib and fridagadget.config into the app binary directory
3.  I archived the app as ipa and installed it using cydia impactor
4. I started the app on the device and when I attempted to connect to it using frida, `frida -H 192.168.0.16:8080 -n Gadget`, I encountered this error

**Comment by Soutcast** [comment]
I worked around this issue by using objection to interact with the app
