### ISSUE TITLE
Failed enable_spawn_gating, crashed frida-helper-32

### ISSUE THREAD

**Issue by sc07kvm** [frida/frida#1048]
After frida_device.enable_spawn_gating() callback on_process_crashed call with info 
`pid 6733, process_name 'frida-helper-32', summary 'Bad access due to invalid address', report "*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***\nBuild fingerprint: 'google/marlin/marlin:8.1.0/OPM4.171019.021.P1/4820305:user/release-keys'\nRevision: '0'\nABI: 'arm'\npid: 6733, tid: 6733, name: frida-helper-32  >>> /data/local/tmp/re.frida.server/frida-helper-32 <<<\nsignal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0\nCause: null pointer dereference\n    r0 ff9c6498  r1 00000000  r2 6365765b  r3 73726f74\n    r4 00000000  r5 00000000  r6 ffffffff  r7 00000000\n    r8 ebfa0000  r9 00000063  sl 00000000  fp ef76c5e9\n    ip ff9c6490  sp ff9c6478  lr acf42aeb  pc ec4dbf98  cpsr a00b0030\n\nbacktrace:\n    #00 pc 00018f98  /system/lib/libc.so (strcmp+51)\n    #01 pc 000a9ae7  /data/local/tmp/re.frida.server/frida-helper-32\n", parameters {}`
and TransportError('the connection is closed',) is raised

Pixel XL, Android 8.1, Frida 12.7.10

**Comment by oleavr** [comment]
Thank you! Releasing Frida 12.7.11 right now with the fix.

**Comment by buwenqi** [comment]
I also occure similar problems with lastest Frida 12.11.14 on XiaoMi 6. It seems that the problem has not been solved。
