### ISSUE TITLE
Cannot hook application class. Always returns class not found exception

### ISSUE THREAD

**Issue by Anan5a** [frida/frida#1049]
I'm trying to bypass root check of an app.
The method ```java isDeviceRooted() ``` is in ```java com.appname.utils.Utils ```
But when I try this  code
```js
Java.perform(function(){
    var ut = Java.use("com.appname.utils.Utils"); //causes error!

ut.isDevice......
});
```

How to hook there in anyway? I need this before I can start dealing with SSL Pinning!

**Comment by febryanasaperdana** [comment]
seems you're doing this for sketchy purposes

**Comment by oleavr** [comment]
@Anan5a It means that the class wasn't loaded by the app's main class loader. You will have to use `Java.enumerateClassLoaders()` and `Java.ClassFactory.get()` passing it the `loader` on which you can `.use()` the given class.

**Comment by enriquejr99** [comment]
For future readers looking for a quick fix, this code finds and sets the appropriate class loader. Just change `CLASS.NAME.HERE` to your class.

```
const classLoaders = Java.enumerateClassLoadersSync();
for (const classLoader in classLoaders) {
    try {
        classLoader.findClass("CLASS.NAME.HERE");
        Java.classFactory.loader = classLoader;
        break;
    } catch {
        continue;
    }
}
```

**Comment by oleavr** [comment]
@enriquejr99 Thanks for providing the helpful example!  Worth noting that assigning to the `loader` property is deprecated, and one should use `Java.ClassFactory.get(loader)` instead of mutating the default class factory.

**Comment by HaoweiCh** [comment]
> For future readers looking for a quick fix, this code finds and sets the appropriate class loader. Just change `CLASS.NAME.HERE` to your class.
> 
> ```
> const classLoaders = Java.enumerateClassLoadersSync();
> for (const classLoader in classLoaders) {
>     try {
>         classLoader.findClass("CLASS.NAME.HERE");
>         Java.classFactory.loader = classLoader;
>         break;
>     } catch {
>         continue;
>     }
> }
> ```
nice

**Comment by us-maker** [comment]
What I used to enumerate methods: 

var classFactory;
const classLoaders = Java.enumerateClassLoadersSync(); 
for (const classLoader in classLoaders) {
    try {
		console.log( classLoaders[classLoader]);
        
       
        classLoaders[classLoader].findClass("my.class");
		  
		classFactory=Java.ClassFactory.get( classLoaders[classLoader]);
		 
		break;
		 
    } catch (e) {
		// console.log( e);
        continue;
    }
}
 
var clz= classFactory.use("my.class");
var methodArr = clz.class.getMethods();
for(var m in methodArr)
{
	console.log(methodArr[m]);
}

**Comment by Tr33NewBee** [comment]
> What I used to enumerate methods:
> 
> var classFactory; const classLoaders = Java.enumerateClassLoadersSync(); for (const classLoader in classLoaders) { try { console.log( classLoaders[classLoader]);
> 
> ```
>     classLoaders[classLoader].findClass("my.class");
> 	  
> 	classFactory=Java.ClassFactory.get( classLoaders[classLoader]);
> 	 
> 	break;
> 	 
> } catch (e) {
> 	// console.log( e);
>     continue;
> }
> ```
> 
> }
> 
> var clz= classFactory.use("my.class"); var methodArr = clz.class.getMethods(); for(var m in methodArr) { console.log(methodArr[m]); }

this works for me,thanks 👍

**Comment by crifan** [comment]
has write some util function:

```js
  static findClassLoader(className){
    var foundClassLoader = null

    const classLoaders = Java.enumerateClassLoadersSync()
    // console.log("classLoaders=" + classLoaders + ", type=" + (typeof classLoaders))

    for (const loaderIdx in classLoaders) {
      var curClassLoader = classLoaders[loaderIdx]
      // var loaderClsName = FridaAndroidUtil.getJavaClassName(curClassLoader)
      // console.log(`[${loaderIdx}] loaderClsName=${loaderClsName}, curClassLoader=${curClassLoader}`)

      try {
        if (curClassLoader.findClass(className)){
          // console.log(`Found ${className} in loader ${curClassLoader}`)
          // Found org.chromium.net.impl.CronetUrlRequest in loader dalvik.system.DelegateLastClassLoader[DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000013/CronetDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000013/CronetDynamite.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]
          foundClassLoader = curClassLoader
          break
        }
      } catch (err){
        // console.log(`${err}`)
      }
    }

    // console.log(`findClassLoader: className=${className} => foundClassLoader=${foundClassLoader}`)
    return foundClassLoader
  }

  static setClassLoder(newClassLoader){
    // var oldClassLoader = Java.classFactory.loader
    // console.log(`oldClassLoader=${oldClassLoader}`)
    Java.classFactory.loader = newClassLoader
    console.log(`Set ClassLoader to ${newClassLoader}`)
  }

  static updateClassLoader(className){
    var foundClassLoader = FridaAndroidUtil.findClassLoader(className)
    // console.log(`foundClassLoader=${foundClassLoader}`)
    if(foundClassLoader) {
      FridaAndroidUtil.setClassLoder(foundClassLoader)
    }
  }
```

detail pls refer:

https://github.com/crifan/JsFridaUtil/blob/main/frida/FridaAndroidUtil.js

call example:

```js
    var clsName_CronetUrlRequest = "org.chromium.net.impl.CronetUrlRequest"
    FridaAndroidUtil.updateClassLoader(clsName_CronetUrlRequest)
```
