### ISSUE TITLE
How to hook WebSettings.getSettings() method

### ISSUE THREAD

**Issue by bwinsight** [frida/frida#1055]
Dear all,

I would kindly ask your help about how could I hook the `getSettings()` method of the `android.webkit.WebSettings` class?

The code snippet I am trying to hook:
```java
WebView myWebView = (WebView) findViewById(C0000R.id.webView1);
myWebView.getSettings().setJavaScriptEnabled(true);
```

My Frida script is the following:
```javascript
var WebSettings = Java.use("android.webkit.WebSettings");
WebView.getSettings().setJavaScriptEnabled.overload('boolean').implementation = function(flag) {
console.log("[*] JavaScript support is enabled: " + flag);
this.getSettings().setJavaScriptEnabled.overload('boolean').call(this, flag);
};
```

Error message I am facing with:
```bash
Error: getSettings: cannot call instance method without an instance
    at n (frida/node_modules/frida-java/lib/class-factory.js:1317)
    at /repl12.js:27
    at frida/node_modules/frida-java/lib/vm.js:42
```

Could you help me with this?

Thank you in advance.

**Comment by secjey** [comment]
Hi @bwinsight 

You've probably found the answer by now as it should be an easy fix, but I'll still reply for future readers having issues working with `WebSettings`.

It looks like you created an instance of `android.webkit.WebSettings` but you are using `WebView` instead (instance which has not been created) to overload the `setJavaScriptEnabled` method. The latter is indeed a method of `WebSettings` ((https://developer.android.com/reference/android/webkit/WebSettings), so you should be able to just replace `WebView.getSettings()` by `WebSettings` in your code. To avoid confusion between variable names and class names, I would also recommend to not capitalize the first letter of your variables:

```JS
var webSettings = Java.use("android.webkit.WebSettings");
webSettings.setJavaScriptEnabled.overload('boolean').implementation = function(flag) {
    console.log("[*] JavaScript support is enabled: " + flag);
    this.setJavaScriptEnabled.overload('boolean').call(this, flag);
};
```

Note that `webView.getSettings()` would work if you were calling this in the same thread as the webview (by using a `Runnable`). In that case, you'd be able to change a value in an already-loaded webview as follows:

```JS
webView.getSettings().setJavaScriptEnabled(true);
```
