### ISSUE TITLE
Read floating points registers inside Arm64 callback

### ISSUE THREAD

**Issue by thebabush** [frida/frida#1059]
Hi,

Inside the `Interceptor.attach` callback, `this.context` only contains general purpose registers `X0...` (plus sp/pc/whatever) but not `D0...`/`S0...`.
Is there a way to read them?
I see that they are mentioned in the Arm64 enums.

Thanks!

**Comment by oleavr** [comment]
Hi,

They are not yet exposed. PRs welcome!

Cheers!

**Comment by depth42** [comment]
Any news on this feature? Would be really apreciated!

**Comment by depth42** [comment]
Any news on this feature? Would be really apreciated!

**Comment by shaohuawan** [comment]
Is it possible to access the floating point registers via Frida C API ?
