### ISSUE TITLE
Frida not support Stalker on arm? 

### ISSUE THREAD

**Issue by def0xff** [frida/frida#1060]
Frida not support Stalker on android arm? 
I have tried to use the Stalker.follow to trace a native call in so.  But got nothing output.
The device is arm. 
Is any idea for me?

`Process.enumerateThreads({
    onMatch: function (thread) 
    {
Stalker.follow(thread.id, { events: {call: true,ret: false,exec: true,block: true,compile: false}, onReceive: function (events) { send(Stalker.parse(events)); }})
    },
    onComplete: function () 
    {
    }
  });

`

**Comment by oleavr** [comment]
Only arm64 currently, in addition to 32- and 64-bit x86. PR welcome!
