### ISSUE TITLE
frida-server-12.7.16-android-arm64.xz can not download

### ISSUE THREAD

**Issue by ywx511613** [frida/frida#1066]
frida-server-12.7.16-android-arm64.xz can not download

**Comment by ywx511613** [comment]
help

**Comment by ywx511613** [comment]
anbody

**Comment by oleavr** [comment]
Sorry, the build machines unfortunately no longer have the 12.7.16 artifact that they failed to upload when that release was made.

Please download 12.7.20 instead.
