### ISSUE TITLE
How to support multiple android devices in python?

### ISSUE THREAD

**Issue by LMig2k** [frida/frida#1073]
Hi, 
The following code running correctly when there is a android device only. 

import frida

device_id = 'xx remote device id'

os.system('adb -s ' + device_id + ' forward tcp:27042 tcp:27042')
session = frida.get_remote_device().attach(package_name)
script = session.create_script(js_code)
script.on('message', on_message)
script.load()
sys.stdin.read()

When multiple remote devices exist, i think it should forward different local ports to the frida server port 27042 , such as: 
os.system('adb -s  device1_id  forward tcp:27042 tcp:27042')
#the local 27042 is used, use another local port
os.system('adb -s  device2_id  forward tcp:**port2** tcp:27042') 
os.system('adb -s  device3_id  forward tcp:port3 tcp:27042')

**device2** = frida.get_device(device2_id)

My question is how to let **device2** use the local **port2**?

Thanks!

**Comment by goddkiller** [comment]
you may use :
device = frida.get_device('device2_id')

**Comment by goddkiller** [comment]
device = frida.get_usb_device()

channel = device.open_channel("tcp:21")
print("Got channel:", channel)

welcome = channel.read(512)
print("Got welcome message:", welcome)

channel.write_all(b"CWD foo")
reply = channel.read(512)
print("Got reply:", reply)

channel.close()
print("Channel now:", channel)


the code is from example in 
https://github.com/frida/frida-python/blob/master/examples/channels.py

**Comment by oleavr** [comment]
@LMig2k Well could do it that way, but it's easier to use Frida's built-in adb integration. Just ensure adb is running before using Frida, and each connected Android device will be detected by Frida. You can then do e.g. `frida.get_usb_device()` to get one of them.
