### ISSUE TITLE
iOS UI does not update when objects are changed

### ISSUE THREAD

**Issue by andermoran** [frida/frida#1076]
In cycript, if you knew that the address of a UILabel was `0x100211610`, you could run
```
var a = new Instance(0x100211610)
a.text = @"Hello, world!"
```
and you would see the UILabel now display "Hello, world!" on your screen.

In Frida, if I do
```
var a = new ObjC.Object(ptr(0x100211610)) 
a["- setText:"]("Hello, world!")      
```
the value of the `text` property of the `UILabel` instance is "Hello, world!"; however, the change is not updated on the screen. This could maybe depend on if this code is running from the main thread or background thread. Could someone help me out? I'd like to see the change in realtime.

**Comment by oleavr** [comment]
You are most likely executing that code off the main thread (e.g. Frida's JS thread). Cycript runs everything on the main thread without you asking, but Frida leaves that decision to the user.

To get the same behavior, do it like this:

```js
ObjC.schedule(ObjC.mainQueue, function () {
  var a = new ObjC.Object(ptr('0x100211610'));
  a.setText_('Hello, world!');
});
```

Cheers!

**Comment by andermoran** [comment]
Thanks! Is there a way to make all Frida code run in the main thread? if not, it would be nice to have a flag like `frida [PID] --main-thread`. Would that be possible?
