### ISSUE TITLE
Failed to attach - iOS 12.4.1 Checkra1n jailbreak

### ISSUE THREAD

**Issue by izadgot** [frida/frida#1078]
Cannot attach to any application

**Device:**

- Jailbroken iOS 12.4.1 with Checkra1n jailbreak.
- CPU: A8
- OS Build: 16G102

**Versioning (iOS device and macOS):**

```
frida --version
12.7.20
```

**Doesn't work**

```
frida -U <app>
Failed to attach: unable to attach to the specified process 
```

**Works**

```
//Works just fine
frida-ps -U
```

**Comment by oleavr** [comment]
Fixed in Frida 12.7.21, just released.
