### ISSUE TITLE
Process terminated Error while using the Frida Server

### ISSUE THREAD

**Issue by rk8339811** [frida/frida#1085]
Hi,

I want to bypass the SSL pinning of an Android app using the Frida Server method. 

I have followed the whole process described in this tutorial.

Below are the steps which I have followed/performed:

0)  Installed the Frida library and Frida-tools
1) Rooted my Android Device
2) Installed the target app
3) Downloaded the Frida server for my Device architecture
4) Sent the Frida Server to its path in Device
5) Granted the Frida server the necessary permissions
6) Have started the Frida Server
7) Got the Java Script File ready
8) Now when I try to spawn an app it is raising the process is terminating as shown below:

![frida](https://user-images.githubusercontent.com/33418814/68917699-77d01780-0791-11ea-8c88-a8b57f77587f.png)

I am trying this from my Windows Laptop with a Real and rooted Android Device running Android lollipop 5.0.

I have tried it on other apps as well but it causes issues on them as well.

In my opinion, the issue is with the code within my JavaScript file.

If my Java Script file is empty it is causing no issue but whenever I add the below line in the file it is causing the process to be terminated.

This is the line that is causing the issue.

`Java.perform(function (){    });`

The app is the device is getting started and immediately the console is showing the process as terminated. I am using `frida-server-12.7.22-android-arm.xz` as the server. I am pretty sure that the setup is fully right but the only issue is occurring while adding the above code to the JavaScript file. 

Also.` Java.IsAvailable` returns false.

Thanks for the beautiful and highly useful library.

I hope I will be able to get this working.

Please let me know if any further info is required to debug this issue.

Thanks

**Comment by Eldario888** [comment]
Hi, I have the same problem, only I use it, if you found a solution, please share it, or maybe someone knows a solution to this problem? I tried different applications everywhere the same result.
![Screenshot_2](https://user-images.githubusercontent.com/30375206/69800353-462e6600-11ff-11ea-8800-30bf08a312bb.png)

**Comment by rk8339811** [comment]
Hi @RaaGod

I think Genymotion with Android 5.0 will work fine. I tried it, did not get this error. Since my system is not powerful enough to run an emulator smoothly hence I was not able to complete the test. But however, I tried it in an Android 9.0 64 bit Stock Android device and did not get this error. I think it should work for you if you use another configuration. Also, if possible try out the different architecture of the device that may be a 64 bit. If you succeed then if possible please update me. A pixel device emulator should be the best option.

**Comment by liukuo362573** [comment]
set timeout of setTimeout function to 1000 to solve my issue on Android 6.0.1

**Comment by khalilklf** [comment]
Solved for me
after one month of searching and debugging, this was my scenario
The App Lunch with root checking (Bypassed)
When I click on "Go To Login" Process Terminated.

the solution was too easy, just open your "apps" on android and grant the app the required and needed permissions.

Hope this will help you

**Comment by oleavr** [comment]
Lots of Android-specific issues have been fixed since this was opened, so let's assume this is fixed. Please open an issue if you encounter any bugs in 12.10.4. Cheers!

**Comment by D4r3-D3v1L** [comment]
> set timeout of setTimeout function to 1000 to solve my issue on Android 6.0.1

Could you please explain  @liukuo362573

**Comment by ahmetugur91** [comment]
@D4r3-D3v1L put the all your code to in

setTimeout(function(){ }, 1000);

this means that your code will perform after 1 second.

**Comment by Alonew0lfxx** [comment]
> @D4r3-D3v1L put the all your code to in
> 
> setTimeout(function(){ }, 1000);
> 
> this means that your code will perform after 1 second.

Thanks! That worked on Android 6 device too
