### ISSUE TITLE
Intercept of a NativeFunction call does not work on Android x64 (but does on Linux)

### ISSUE THREAD

**Issue by andreafioraldi** [frida/frida#1094]
Hi,
I'm debugging a strange behaviour that prevents me to run a simple experimetal fuzzer on Android.
https://github.com/andreafioraldi/experimental-frida-fuzz/blob/master/index.js#L180
The NativeFunction call (see the fuzzer_test_one_input function) executes without instrumentation because onEnter is never called (I putted a console.log and also the instrumentation output is empty so I'm pretty sure that onEnter is never called).
Is this a known problem? Is very strange cause on Linux x64 works like a charm.

**Comment by andreafioraldi** [comment]
Update: a restart of the frida server solve the issue with the interceptor but there is an issue with the stalker.
After translating the first block (a frida-agebt64 block, but I excluded it with Stalker.exclude), the execution of that block generates an illegal instruction. I used the Interceptor+Stalker trick to follow the current frida thread when calling a NativeFunction. @oleavr any ideas?

**Comment by oleavr** [comment]
@andreafioraldi I started implementing support for this use-case in the [feature/native-function-traps](https://github.com/frida/frida-gum/tree/feature/native-function-traps) branch. Almost got it working – works for the first call and crashes on the second. Once that's figured out it should be ready for merging.
