### ISSUE TITLE
Where is `frida-gum.h` header file?

### ISSUE THREAD

**Issue by Jack7ove** [frida/frida#1100]
Hi, I successfully build frida on win10 1903 with vs2017, I notice there are sample code in `frida/releng/devkit-assets/`, but when I try to compile it I notice I don't have `frida-gum.h` header file.
I also try to search it in the whole project, but I got nothing.

Could you plz tell me how can I get the header file?

**Comment by o0xmuhe** [comment]
https://github.com/frida/frida/releases 

you can find what you want :)
