### ISSUE TITLE
findExportByName(null,...) on Android does not always function as expected.

### ISSUE THREAD

**Issue by strazzere** [frida/frida#1110]
While targeting and Android device, I was attempting to hook some logging infrastructure. While doing this, I attempted to use;

```
Interceptor.attach(Module.findExportByName(null, '__android_log_write'), {
    onEnter: function(args) {
        var verbosity = args[0];
        var tag = Memory.readUtf8String(args[1]);
        var formattedString = Memory.readUtf8String(args[2]);
        console.log("__android_log_write -> " + verbosity + " : " + tag + " : " + formattedString);
     },
    onLeave: function(retval) {

    }
});
````

Which tends to work, however in this instance it was hooking the first instance of `__android_log_write` which was found, which happened to be an export symbol in 1 of ~10 libraries loaded. This meant any other library loaded and not using this function hooked symbol, would not be caught.

The "fix" I used was to explicitly hook this using `liblog.so` as a parameter vs `null`.

Edit: Remove code that isn't in snippet.

**Comment by eugenekolo** [comment]
I don't think this is an issue/bug. When you don't specify a library it picks a singular export, the first one. This is the price you pay for ease/laziness.

It you want an exact one, you have to specify the library.

**Comment by oleavr** [comment]
Well I wonder if we should make this behavior a bit more stable across apps. E.g. first try `RTLD_NEXT` pretending to be a high-level system library, and if that fails we try `RTLD_DEFAULT`. This way we'd have stable behavior across apps when looking up system exports the lazy way. OTOH we'd be making lazy app symbol lookups slower.

**Comment by strazzere** [comment]
@eugenekolo I've only reported it because I was asked too. I figured it out on my own - and it was based on my poor assumption. Honestly, I'm fine with it working the way it currently does, though the nitpick in me would love a slim line to the documentation about this.

**Comment by strazzere** [comment]
Huh - I dug into it a bit more and this explains what was happening;
```
 >> With lib : 0xe9dd5531
 >> Extra : 0xea5b7fb1 libcutils.so!__android_log_write
 >> Without lib : 0xea5b7fb1
 >> Extra : 0xe9dd5531 liblog.so!__android_log_write
```

From this snip;
```
console.log(" >> With lib : " + Module.findExportByName("liblog.so", '__android_log_write'));
console.log(" >> Extra : " + DebugSymbol.fromAddress(Module.findExportByName(null, '__android_log_write')));
console.log(" >> Without lib : " + Module.findExportByName(null, '__android_log_write'));
console.log(" >> Extra : " + DebugSymbol.fromAddress(Module.findExportByName("liblog.so", '__android_log_write')));
```

To be honest, it wasn't me trying to be easy/lazy in the beginning, I mostly didn't know /what/ library contained these functions. It also is very odd to me (but I guess understandable?) that this function is present in two separate libraries (and apparently never used from one of them).

Not sure if a change is /needed/, though it could be helpful for a comment or potentially noting that mutliple matching functions had been found. :man_shrugging:

**Comment by eugenekolo** [comment]
@strazzere Thanks for the report :), I'm just trying to triage. Looking at the documentation, I think stating that it returns "the first occurrence" would help a lot. 

@oleavr I'm a bit in disagreement there. It seems not a guaranteed stability and potentially a false guarantee. I think it's okay to just have people be aware, and instead make them write less lazy code when necessary.

**Comment by oleavr** [comment]
@eugenekolo You're right. When I made that comment I was still on the fence whether it's actually an API usability bug, and not just a documentation bug. But in light of @strazzere's discovery that his case involved two system libraries exporting the same name, I'd say his particular case is only the latter: something that should be clarified in the docs. And thinking more about it I don't think there's any point in trying to make our implementations (on each platform) more predictable for this use-case as even that is going to have edge-cases such as this one.

So let's close this and hope somebody opens a PR on frida-website (and DefinitelyTyped) to improve our docs. :-)
