### ISSUE TITLE
How to print an object parameter so that we can see clearly what's in this object

### ISSUE THREAD

**Issue by MY201314MY** [frida/frida#1114]
**Java.perform(function (){
    var chat = Java.use("com.chat.ChatManager")
    var message = Java.use("com.plugin.message.b.b.p")

    chat.a.overload('com.chat.g', 'com.chat.h').implementation = function(x, y){
        console.log("Argument X: " + x)
        console.log("Argument Y: " + y)
    }
})**

And it prints the following:

`Argument X: com.plugin.message.b.b.p@3b2800a

Argument Y: com.plugin.message.chat.presenter.l$1@dffb503`

Could you please tell me how to print it in detail, Thanks  a lot.

**Comment by tacesrever** [comment]
use `console.log(Object.getOwnPropertyNames(x).join(', '));` 
and `console.log(Object.getOwnPropertyNames(x.__proto__).join(', '));`
