### ISSUE TITLE
Error: invalid argument value

### ISSUE THREAD

**Issue by chris7coder7** [frida/frida#1126]
This is my snippet and its not working [Error: invalid argument value] , it seems to be correct , i am trying to create a uuid :

var JavaLong=Java.use('java.lang.Long');
var Java_UUID=Java.use('java.util.UUID');
var long1=JavaLong.$new(1);
var long2=JavaLong.$new(10);
var tuuid=Java_UUID.$new.overload('long','long').call(long1,long2);

**Comment by tacesrever** [comment]
you can directly use `Java_UUID.$new(1, 10);`.
