### ISSUE TITLE
loop executing js script will time out 

### ISSUE THREAD

**Issue by winsun** [frida/frida#113]
the issue:  
File "/Library/Python/2.7/site-packages/frida/core.py", line 441, in load
    self._impl.load()
frida.TransportError: timeout was reached

i write js script : 
for(var i = 0; i < 200 ; i++){
      crackuserinfo(uid);
      sleep(5000);
}

the above code will loop 5 times ,and throw exception.
how can i solve this problem?

**Comment by oleavr** [comment]
Hi,

This is to be expected. Long-running operations should not be blocking the loading of the script. So just wrap your for-loop in a setTimeout, i.e.:

```js
setTimeout(function () {
  /* your code here */
}, 0);
```

But if you want to run this operation every 5 seconds, it is better written like this:

```js
var remaining = 200;
function crackNext() {
  crackuserinfo(uid);
  if (--remaining > 0) {
    setTimeout(crackNext, 5000);
  }
}
setTimeout(crackNext, 0);
```

Cheers

**Comment by winsun** [comment]
tks oleavr

**Comment by hyrathon** [comment]
thanks, it helps

**Comment by srcdes** [comment]
Even though i wraps a `for` loop with `setTimeout()`, the `console.log()` after the loop isn't called. The loop iterates Java byte array `[B`(30mb). So the loop iterates 30000000 times. Is this loop too heavy? Are there any other effective ways to save a string to big-sized file?

```js
const fs = require("frida-fs");

Java.perform(function() {
    var theClass = Java.use("abc.def.TheClass");
    theClass.theMethod.implementation = function(str) {
        // `ret` is java byte array.
        var ret = this.theMethod.call(this, str);

        setTimeout(function() {
            Java.perform(function() {
                for (var i = 0; i < ret.length; i++) { // iterates over 30000000 times.
                    if (ret[i] >= 0)
                        data += (ret[i] + " ");
                    else
                        data += ((ret[i] & 0xff) + " ");
                    }
                }
                
                var file = new File("/data/data/abc.def.app/files/file_new.txt","w");
                file.write(data);
                file.close();
                console.log("written to file");
            });
        }, 0);
    
        return ret;
    };
});
```
