### ISSUE TITLE
Frida Gadget JS API - identifier 'Set' undefined

### ISSUE THREAD

**Issue by ddzobov** [frida/frida#1130]
Frida Gadget version 12.8.0
iOS 13.3

I'm trying to use Set:
```
const pendingBlocks = new Set();

console.log(pendingBlocks);
```

Result:
`{"type":"error","description":"ReferenceError: identifier 'Set' undefined","stack":"ReferenceError: identifier 'Set' undefined\n    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:81019)\n    at /script.js.js:1","fileName":"/script.js","lineNumber":1,"columnNumber":1}`

**Comment by tacesrever** [comment]
by https://frida.re/docs/gadget/,  
try config Gadget's runtime=jit to use v8.

**Comment by oleavr** [comment]
Or use frida-compile and enjoy TypeScript at the same time:
https://github.com/oleavr/frida-agent-example
