### ISSUE TITLE
Is it possible to run the frida in virutal space?And how?

### ISSUE THREAD

**Issue by m1chaeldg** [frida/frida#1135]
How will I run the frida-server in android inside of the virtual space like parallel, virtualxposed and vapp? The idea is I will spawn the apk in the virtual space and hook the native methods, shared objects, and the java classes.

Thanks

**Comment by cf** [comment]
I have the same question, has any one got this working before?

**Comment by oleavr** [comment]
Yes this is possible using [Gadget](https://frida.re/docs/gadget/).
