### ISSUE TITLE
frida-core.h: No such file or directory

### ISSUE THREAD

**Issue by awakened9879** [frida/frida#1138]
I am trying to execute a command `npm install` and get such errors
![image](https://user-images.githubusercontent.com/59332946/71556059-0bf9f380-2a4d-11ea-9da4-43f861cdaa30.png)

`gyp ERR! build error 
gyp ERR! stack Error: `D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gmka9\OneDrive\Desktop\frida-node-master
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@0.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

[2019-12-29T10_51_52_942Z-debug.log](https://github.com/frida/frida/files/4007976/2019-12-29T10_51_52_942Z-debug.log)

**Comment by oleavr** [comment]
When building from source you need to set the environment variable `FRIDA` to the absolute path to the root of the already built source tree. I.e. the `frida` repo that you git cloned with `--recurse-submodules` and built with VS2017.

**Comment by awakened9879** [comment]
> When building from source you need to set the environment variable `FRIDA` to the absolute path to the root of the already built source tree. I.e. the `frida` repo that you git cloned with `--recurse-submodules` and built with VS2017.

Can you explain more please

**Comment by oleavr** [comment]
Follow the build instructions:
https://frida.re/docs/building/#windows

Then, if the frida repo is at `C:\src\frida`, `set FRIDA=C:\src\frida` and `npm install`.

But there is no need to build Frida from source, we provide prebuilt binaries, e.g. `npm install frida@12.8.1`.

**Comment by awakened9879** [comment]
> Follow the build instructions:
> https://frida.re/docs/building/#windows
> 
> Then, if the frida repo is at `C:\src\frida`, `set FRIDA=C:\src\frida` and `npm install`.
> 
> But there is no need to build Frida from source, we provide prebuilt binaries, e.g. `npm install frida@12.8.1`.

i use npm install

**Comment by awakened9879** [comment]
npm install frida@12.8.1

![image](https://user-images.githubusercontent.com/59332946/71561750-f4922900-2a93-11ea-9449-d453f855531a.png)

**Comment by oleavr** [comment]
Read the error message. You're trying to install `frida` inside the `frida` module, which 
makes no sense.

**Comment by whobaca** [comment]
> Read the error message. You're trying to install `frida` inside the `frida` module, which
> makes no sense.

![03E1E6D0-936B-4B8F-A0A2-DB7B4321AAF7](https://user-images.githubusercontent.com/69328752/118317546-e31eb500-b500-11eb-9112-dffb968292c0.jpeg)


Any help, please, I did not know the reason please
