### ISSUE TITLE
Frida 12.8.2 Failed to attach: unable to inject library into process without libc

### ISSUE THREAD

**Issue by JoeyJiao** [frida/frida#1143]
Facing this error:
     ____
    / _  |   Frida 12.8.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
**Failed to attach: unable to inject library into process without lib**

# How to reproduce
wget https://github.com/andreafioraldi/frida-fuzzer/blob/master/tests/test.c
aarch64-linux-gnu-gcc -static test.c -o test_aarch64
adb push test_aarch64 /data/local/tmp/
adb shell /data/local/tmp/frida-server-12.8.2-android-arm64
frida-ps -U | grep test_aarch64 // pid like 8333

frida -U -p 8333 // Above error comes.

**Comment by oleavr** [comment]
Attaching to statically linked programs is not yet supported. Remove `-static`, or help us improve Frida's Linux injector to support this. Cheers!

**Comment by fabiomaia** [comment]
Has this been improved?

**Comment by kkkkkk011** [comment]
> Attaching to statically linked programs is not yet supported. Remove `-static`, or help us improve Frida's Linux injector to support this. Cheers!


Hope to support this function as soon as possible~~thinks

**Comment by kkkkkk011** [comment]
> Attaching to statically linked programs is not yet supported. Remove `-static`, or help us improve Frida's Linux injector to support this. Cheers!

I tried to make the static target dlopen ("libc") successful, but firda-inject still reported another error(frida.NotSupportedError: remote_exec PTRACE_CONT wait failed: 0)

**Comment by b1gcat** [comment]
+1
