### ISSUE TITLE
some issues about (Android ART Mode, GDBus Error)

### ISSUE THREAD

**Issue by NELpos** [frida/frida#115]
Hi

I really appreciate for support frida

but I have some issues about frida

I have two devices (one is Nexus 5, the other is Galaxy S4 mini)

First, Is Frida not working on ART Mode?
My Nexus Device version is lollipop(5.1.1)
It applys for ART Mode (set default)

Few days ago, I coded python, and tested in Nexus 5 about hooking method
but It didn't work, but another device(s4 mini, Dalvik mode) works very well despite of same code.
Please answer about this.

Second I saw an error message like this

Failed to enumerate processes: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 're.frida.HostSession7' on object at path /re/frida/HostSession7

0) I downloaded frida-server latest version(2/26)
1) I used frida very well with Nexus 5
2) One day, I tested some code on S4 mini.
3) I connect S4 mini and execute frida-server
4) On Desktop, performed adb port forward (according to manual)
5) I executed frida-ps -R
6) I saw this issues.

Please answer about this problem.

**Comment by oleavr** [comment]
Hi,

1. ART hooking is not yet working. Dalvik on Android 4.4 on 32-bit ARM is currently the best supported configuration.
2. This is because your host-side is Frida 7.x, but the `frida-server` running on your target is from a different major release, e.g. 6.x. See frida/frida-core/issues/72.

Cheers!

**Comment by ballballsun** [comment]
Hi, I have the problem similar to second one.
I am able to run ```frida-ps -Ua```, but When I run a my old script. 
I get 
```
Error: No such interface 're.frida.HostSession6' on object at path /re/frida/HostSession
    at Error (native)
```

I am using frida 7.0.5, by ```sudo pip install frida --upgrade```.
And the latest ```frida-server``` that get by
```
curl -O https://build.frida.re/frida/android/arm/bin/frida-server
$ adb push frida-server /data/local/tmp/
```

But still encounter the problem. Any idea?

**Comment by oleavr** [comment]
If you get that error it means that the Frida major version between host and device is not the same, e.g. 6.x on host and 7.x on device.

**Comment by TinyNiko** [comment]
so where can I get the 7.x frida-server
