### ISSUE TITLE
Frida 12.8.6 / iOS 12.4.1: frida doesn't recognize Developer Disk Image

### ISSUE THREAD

**Issue by pachoo** [frida/frida#1154]
This is similar to the previously reported https://github.com/frida/frida/issues/1065 however this is not working for me on iOS 12.4.1 and I verified that `frida` does work on Frida 12.4.8.

Device:
* iOS 12.4.1 (non-jailbroken)

Software:
* OSX 10.5.2
* Frida 12.8.6 (installed via pip)
* Python 3.7.4
* libimobiledevice (recent, not sure this matters terribly as Frida 12.4.8 works and this is on iOS 12.4.1 without the iOS 13 cleartext after handshake with debugserverd)

I've patched a simple test iOS app (FAT ARMv7, ARM64) with the Frida iOS universal gadget 12.8.6 dylib and noticed that when I try to connect to the gadget via the `frida` CLI tool I'm getting the "Failed to spawn: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually" message.

Repro:
1.  `$ idevicedebug run <bundle_id>`
2.  `$ frida -U -n Gadget`

Results in 
```
     ____
    / _  |   Frida 12.8.6 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to spawn: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually
```

I had an older version of Frida (12.4.8) installed in a separate virutalenv and with the same Gadget, it doesn't have an issue.
```
$ frida -U -n Gadget
     ____
    / _  |   Frida 12.4.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
                                                                                
[iPad 4::Gadget]-> Frida.version
"12.8.6"
```

I recall reading there were lockdownd integration changes recently introduced in Frida that might explain this.  I don't use `ios-deploy` but trying to `idevicepair unpair` between launching via `idevicedebug` and running `frida` didn't seem to work for me.

**Comment by pachoo** [comment]
Minor update:  

`frida -U -f re.frida.Gadget` is working on Frida 12.8.6 and iOS non jailbroken 12.4.1 to attach to the debugserver launched application (with embedded Gadget).

**Comment by oleavr** [comment]
There is no longer any need to patch the app to add Gadget to it. Here's a walkthrough of the modern way of doing things:
https://www.nowsecure.com/blog/2020/01/02/how-to-conduct-jailed-testing-with-frida/

Frida will now inject Gadget into memory dynamically. This has barely been tested on iOS < 13 though, so make sure you're running the latest iOS 13.3 if possible. (Or help us iron out any issues on older iOS versions.)

**Comment by oleavr** [comment]
(Would also recommend using Frida to launch the app for you, instead of relying on other tools for doing that.)
