### ISSUE TITLE
Failed to spawn: unable to launch iOS app: The operation couldn’t be completed. Application "app-identifier" is unknown to FrontBoard.

### ISSUE THREAD

**Issue by fiestyqier** [frida/frida#1168]
Hi, I am unable to spawn any apps on my iPhone iOS 11.3.1. I have verified that the version of Frida client and frida-server are currently 12.8.10. Any idea how to resolve/troubleshoot this? 

iphone:/usr/sbin root# `frida-server --version`
**12.8.10**

MacBook:~ xx$ `frida -U -f app-identifier`
     ____
    / _  |   **Frida 12.8.10** - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
**Failed to spawn: unable to launch iOS app: The operation couldn’t be completed. Application "app-identifier" is unknown to FrontBoard.**

**Comment by idb-** [comment]
Am having the same issue on iOS 13.4 jailbroken with checkra1n 0.10.1 using frida 12.8.20. Can attach to processes but not launch.

**Comment by poldenais** [comment]
I had the same issue now on iOS 13.2.2 device. Both Frida versions are synced up between MacBook and device. Any ideas how you solved this? thanks

**Comment by idb-** [comment]
I think i was actually just being an idiot and not using the package name
to try to spawn. I've been known to have my head up my ass sometimes.
