### ISSUE TITLE
Abort the execution for target process by specifying 'timeout' value

### ISSUE THREAD

**Issue by 73J45** [frida/frida#1174]
Hello @oleavr ,

I am working with child_gating.py script on Windows platform.
I am interested to know whether frida-python has any predefined way to specify timeout for  execution of target process, where we can just specify the timeout. Using it my frida app will start the target process, monitor it for the time interval specified by timeout and then terminate or abort the execution for target process and followed  by own termination.

**Comment by oleavr** [comment]
No, this is easy to implement in the application, so there is no need for Frida to provide this kind of functionality.

**Comment by 73J45** [comment]
I have implemented a logic in on_message to set the timeout. It works fine till the messages are pushed from targetprocess to frida app . But in case where the target process generates no events, the control does not return back to the on_message and the logic fails.
