### ISSUE TITLE
How to use rpc dispose?

### ISSUE THREAD

**Issue by datoboat** [frida/frida#1176]
I want to 'flush' our buffer of data on javascript side when process is terminated.
After looking https://frida.re/news/2018/04/28/frida-10-8-released/, I think dispose of rpc exports may be solution.
I tried to use that but not working.
How to use the rpc dispose?
Please help me.

**Comment by oleavr** [comment]
```js
rpc.exports.dispose = function () {
  // Do the work here.
};
```

**Comment by oleavr** [comment]
Note that this will only work if the app terminates one of the following ways and doesn't crash:
https://github.com/frida/frida-core/blob/f7c5d1d4b31becc9b99c75189bdc8df0d26c28c6/lib/payload/exit-monitor.vala#L39-L41
(PRs welcome to improve this!)

**Comment by datoboat** [comment]
`import frida
import sys

device = frida.get_local_device()
session = device.attach('simple')
script = session.create_script("""
    rpc.exports.dispose = function() {
        console.log('dispose');
    };
""")
script.load()
sys.stdin.read()`

I tried above code and terminated "simple" process by several ways (click Ctrl+C, run "kill -9 <pid>", run "kill <pid>")
But i couldn't get dispose working.
Can you please let me know what is wrong in my code?

**Comment by oleavr** [comment]
@datoboat Which OS are you trying this on?

**Comment by datoboat** [comment]
@oleavr  I am using Linux (Ubuntu 18.04).
