### ISSUE TITLE
python stdout redirect

### ISSUE THREAD

**Issue by bannsec** [frida/frida#1177]
It looks like there's a way to spawn through Frida in python and redirect stdio with `stdio='pipe'` option. From there, it seems you can do `device.input` to send to your process stdin. However, I can't find how to read from stdout programmatically.

**Comment by oleavr** [comment]
Connect to the `output` signal. It will give you the `pid`, `fd`, and `data` – in that order.

**Comment by 0x5e** [comment]
How to connect the output signal in JS API ? I didn't find it in the documentation either.

**Comment by NSEcho** [comment]
A bit late to the party, but you can take a look here: https://github.com/nsecho/fnoios

It is written using `frida-go` and is based around `output` signal.
