### ISSUE TITLE
Spawning process on android fails and crashes SystemUI

### ISSUE THREAD

**Issue by edermi** [frida/frida#118]
Hi,

when trying to spawn a process with frida-trace on Android, the process is not spawned but the Android UI crashes (looks like a soft reboot).

```
[meder@meder ~]$ frida-trace -U -i close -f com.google.chrome              
Failed to spawn: unable to find process with name 'com.android.systemui'
```

Trying again after the UI is up again leads to another error and a error message from frida-server:

```
[meder@meder ~]$ frida-trace -U -i close -f com.google.chrome
Failed to spawn: java API not available  
```

```
 {"type":"error","description":"Error: Java API not available","stack":"Error: Java API not available\n    at assertJavaApiIsAvailable (gumjs-java.js:138:23)\n    at Runtime.perform (gumjs-java.js:257:13)\n    at parasite-service.js:79:6","fileName":"gumjs-java.js","lineNumber":138,"columnNumber":23}
```

I'm using a Nexus 6 with rooted stock ROM (Android 6.0.1 Patch level February 2016) and Ubuntu 14.04. `frida --version` says 7.0.7

Attaching to an already running process works fine.

**Comment by oleavr** [comment]
Thanks for reporting. This is a known issue that I haven't had time to look at yet.

**Comment by ualwayswithme** [comment]
Hello, 
After ran the command "frida-trace -U -i open -f com.example.hellojni" , the application HelloJni would be set up normally. But after I executed the fellowing python script, i got a crash.

    ```
    device = frida.get_device_manager().enumerate_devices()[-1]
    session = device.attach(device.spawn(["com.example.hellojni"]))   
    ss = '''
           console.log("hello")
    '''    
    script = session.create_script(ss)
    script.load()
    session.detach()
```
The log "hello" showed in the console. But the app just crashed. And the logcat printed something like these:
04-17 06:14:58.279: E/WindowManager(570): Starting window AppWindowToken{41e429c0 token=Token{41f753c8 ActivityRecord{41ea5dc0 u0 com.example.hellojni/.view.MainActivity t39}}} timed out
04-17 06:14:58.279: W/ActivityManager(570): Process ProcessRecord{41dffd18 16943:com.example.hellojni/u0a203} failed to attach
04-17 06:14:58.289: I/ActivityManager(570): Killing 16943:com.example.hellojni/u0a203 (adj -100): start timeout

Was my script wrong? I'm using android4.4.4, dalvik mode, windows7, firda7.0.11..
Any help would be appreciated.

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
