### ISSUE TITLE
Frida unable to find exported function during early instrumentation

### ISSUE THREAD

**Issue by localacct** [frida/frida#1180]
Hi

In my test APK, I have this native library "libnative-lib.so" inside the lib/arm64-v8a folder and there is an exported function "Java_com_internal_native_hooknative_MainActivity_stringFromJNI" in the library.

I started the application using Frida

````
frida -U -f com_internal_native_hooknative -l frida_native.js --no-pause
````

However, when trying to intercept the exported function and trying to find the export by name, I encountered this

````
Error: libnative-lib.so: unable to find export 'Java_com_internal_native_hooknative_MainActivity_stringFromJNI'
````

However, if I now make some changes to the JavaScript code and save it again, the exported function can now be found (was able to print the address).

I am running Android 9 (rooted) on Google Pixel 3A XL.

I cannot attach Frida to the process after it has started as the function would have executed. I also tried using Frida-trace to start the application but it would show "Started tracing 0 functions", because I think Frida tried to hook very early and the library was not loaded yet. If I tried to use frida-trace to attach to the process only after it has started, then again it would be too late as the function would have executed.

Is there a way to write the Javascript code such that it will wait for the library to be loaded before hooking but is still part of early instrumentation?

**Comment by folkene** [comment]
Hello,

Can you confirm that the library has been loaded at the time of intercepting  Java_com_internal_native_hooknative_MainActivity_stringFromJNI? This can be easily check by tracing dlopen function calls.

If I'm right, just intercept the dlopen call corresponding to your library and add your interceptor at that time.

Folkene

**Comment by localacct** [comment]
Hi @folkene 

Thanks for the advice, I will try it

**Comment by localacct** [comment]
Hi @folkene 

Tried your suggestion, I did not see the library name being called by dlopen, then I tried hooking dlsym and added my interceptor there and it seems to work for my scenario.

Thanks for pointing me in the right direction about checking the library related functions.

**Comment by bartlomiejduda** [comment]
Here is my solution:
https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/Cocos2d/cocos2d_xxtea_script.js
