### ISSUE TITLE
(Documentation) $ pip install frida-tools returns error

### ISSUE THREAD

**Issue by foreza** [frida/frida#1186]
The website (https://frida.re/) and the README.me both indicate that you can use
`pip install frida-tools`

However, this gives me the following error (stack trace below) using MacOS 

Collecting frida-tools
  Using cached frida-tools-6.0.1.tar.gz (28 kB)
Collecting colorama<1.0.0,>=0.2.7
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting frida<13.0.0,>=12.8.5
  Using cached frida-12.8.11.tar.gz (6.9 kB)
ERROR: Could not find a version that satisfies the requirement prompt-toolkit<4.0.0,>=3.0.3 (from frida-tools) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.25, 0.26, 0.28, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.50, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.60, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10)
ERROR: No matching distribution found for prompt-toolkit<4.0.0,>=3.0.3 (from frida-tools)

It looks like the issue is due to me using pip / python 2.7
By using this instead:
`pip3 install frida-tools`

I was able to install frida.

**Comment by srcdes** [comment]
> Python – latest 3.x is highly recommended

https://frida.re/docs/installation/
