### ISSUE TITLE
Application crashes when hooking with frida

### ISSUE THREAD

**Issue by Quikko** [frida/frida#119]
Hello,

I am doing an internship for which i am using Frida to hook on functions from 'libcommonCrypto.dylib' on a jailbroken iPad. The problem which states itself is the following, when we execute our script, based on the screencast on youtube, the application spawns but after a few seconds crashes again. The application we're using at the moment is Twitter, although we've tried some others. The only application which has worked, is the App Store. "Error: The connection is closed"

'use strict';
const async = require('generator-async');
const frida = require('frida');

let session, script;
async.run(function *() {
        const device = yield frida.getUsbDevice();
        const pid = yield device.spawn(['com.atebits.Tweetie2']);
        session = yield device.attach(pid);
        script = yield session.createScript('(' + agent.toString() + ').call(this);');
        script.events.listen('message', message => {
        if(message.type === 'send' && message.payload.event === 'ready')
                device.resume(pid);
        else
        console.log(message);
        });
        yield script.load();
});

function agent(){
        'use strict';

```
    Module.enumerateExports('libcommonCrypto.dylib',{
            onMatch: e => {
                    if (e.type === 'function') {
                            try{
                                    Interceptor.attach(e.address, {
                                            onEnter: args => {
                                                    send({ event: 'call', name: e.name });
                                            }
                                    });
                            } catch (error) {
                                    console.log('Ignoring ' + e.name + ': ' + error.message);
                            }
                    }
            },
            onComplete: () => {
                    send({ event: 'ready' });
            }
    });
```

}

Kind regards,
Quikko

**Comment by oleavr** [comment]
Hi,

This looks correct. Are you running Frida 7.0.7 on both host and device?

Cheers!

**Comment by oleavr** [comment]
Fixed in latest Frida 9.x.
