### ISSUE TITLE
precision missed when hook "long" type on java layer, thx for any help

### ISSUE THREAD

**Issue by dengtongtongtong** [frida/frida#1190]
frida version: 12.8.11 run on android 9.0 with magisk rooted environment.

when I hook methods with 'long' type. I came across 'precision missed' situation, here is my code on android:
```
private void alterText(long num) {
    textView = (TextView) findViewById(R.id.textView2);
    textView.setText(String.valueOf(num));
}
```
and here is my frida js code
```
my_class.alterText.overload('long').implementation = function () {
        console.log("args:", arguments[0]);
        var ret_value = this.alterText(4791443766394045000);
        return ret_value;
}
```
I expect 4791443766394045000 showed on the textView. 
However I got 4791443766394045440, pls help

**Comment by dengtongtongtong** [comment]
additional, when I use alterText(4791443766394045000L) on android java code, it goes right. So why it goes wrong when set 'num' using frida-js

**Comment by oleavr** [comment]
> var ret_value = this.alterText(4791443766394045000);

JavaScript numbers are backed by `double`, so you need to do it like this:

`var ret_value = this.alterText(int64('4791443766394045000'));`
