### ISSUE TITLE
Failed to attach: unable to inject library into process without libc

### ISSUE THREAD

**Issue by PeterParker369** [frida/frida#1191]
Sorry for rising an old one problem, but it still doesn't works :(
I have read a lot of issues: tried to degrade frida version and so on.. but it didn't help.
Current versions I'm using: frida-server-12.8.11-android-arm.xz for Nox emulator and frida 12.8.11 ver.
I have root rights correctly switched on. When I'm doing `frida-ps -U` I get the list of the currents apps.
But when I want to load my JS script it tells:
Traceback (most recent call last):
  File "loader_s5.py", line 65, in <module>
    pid = device.spawn(["com.example.test"])
  File "C:\......\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\......\site-packages\frida\core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: unable to inject library into process without libc
Also when executing command: `frida-trace -U -i open com.example.test`
Failed to attach: unable to inject library into process without libc
Please help, am I doing everything correct or it's because I'm using Nox emulator?

**Comment by dausruddin** [comment]
I think it is because the emulator. I tried using Memu emulator and it gave the same error. Then I try it with my phone and it is working fine.

**Comment by oleavr** [comment]
Correct, such emulators are not yet supported. PRs welcome!

**Comment by PeterParker369** [comment]
Thx for response :(

**Comment by AndnixSH** [comment]
Such a sad moment. I need to hook ARM based app which does not have x86 libs and using fridax86 caused crash with the app

**Comment by TonicBoomerKewl** [comment]
> Such a sad moment. I need to hook ARM based app which does not have x86 libs and using fridax86 caused crash with the app

Same. Using frida x86, it cannot see the modules of arm64 app.

**Comment by oleavr** [comment]
@TonicBoomerKewl For arm64 you will need to use the x86_64 frida-server, not the x86 one.

**Comment by TonicBoomerKewl** [comment]
> @TonicBoomerKewl For arm64 you will need to use the x86_64 frida-server, not the x86 one.

Using x86_64 works, but because the app i'm trying to debug does not have x86 libraries, only arm64-v8a libraries, it cannot find the modules, even though I decompiled the app and the module is definitely there. I tried, bluestacks5, nox, memu, all failed.

**Comment by JasmineScholz** [comment]
Sorry ti bring up an old thread. Has a fix been found for this? I'm using an android studio emulator. Has anyone found a work around for the issue with libc?

**Comment by TonicBoomerKewl** [comment]
For me, the "fix" was to just use a real phone instead of using an android emulator.
