### ISSUE TITLE
Cannot catch exception inside Process.setExceptionHandler catch

### ISSUE THREAD

**Issue by bannsec** [frida/frida#1193]
There appears to be a nesting issue when attempting to use try/catch inside a handler registered as Process.setExceptionHandler. Example:

```
  8 Process.setExceptionHandler(
  9     function (details) {
 10         try {
 11             ptr("0x41414141").readPointer();
 12         } catch (e) { send(1); }
 13     }   
 14 )   
```

I wrote a program that will simply segfault. This will cause the exception handler to be called. However, unlike when I use try/catch normally, when used inside this exception handler call, i cannot catch exceptions, and instead the program crashes.

In the above example, i would hope to get "1" sent back to me. Instead, the program fully crashes.

**Comment by oleavr** [comment]
Hmm yes, that's definitely not handled yet.

Interested in taking a stab at fixing it? The best place to start is probably adding a test to the [test-suite](https://github.com/frida/frida-gum/blob/master/tests/gumjs/script.c) and explore things from there.

(Happy to walk you through it; hit me up on Telegram or Twitter DM if you're interested.)

**Comment by bannsec** [comment]
I can give it a shot. I tend to find myself getting lost in the heaps of code that is frida ;-)

**Comment by oleavr** [comment]
Awesome 👏

Yeah we definitely need better docs. 😊 You can find an overview here: https://frida.re/docs/hacking/
(Diagram has links to the different parts of the codebase.)

Here's the function that gets called when an exception occurs: https://github.com/frida/frida-gum/blob/916256984d34eaaf727ca5b5d184f4967c7ad403/gum/backend-posix/gumexceptor-posix.c#L335

**Comment by bannsec** [comment]
Closing since the PR was merged.
