### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by ghostfevil** [frida/frida#1197]
How to debug the code?
Specially vala code?

**Comment by oleavr** [comment]
The easiest is adding temporary logging:
https://gist.github.com/oleavr/00d71868d88d597ee322a5392db17af6

(But you can also put breakpoints in GDB/LLDB, as the Vala code is compiled to C code.)

**Comment by ghostfevil** [comment]
> The easiest is adding temporary logging:
> https://gist.github.com/oleavr/00d71868d88d597ee322a5392db17af6
> 
> (But you can also put breakpoints with GDB/LLDB, as the Vala code is compiled to C code.)

Ok thanks,I know your method,But i want to debug the vala code directlly.any mehod?

**Comment by oleavr** [comment]
@ghostfevil I don't know, haven't researched it.
