### ISSUE TITLE
Wait for user input

### ISSUE THREAD

**Issue by drZaius** [frida/frida#1203]
I currently use a Python wrapper to spawn and hook an Android app and to inject my frida script. I'm hooking a lot of methods and I'm sending the hooks back to the wrapper using frida's send() method. But there's still a lot of output on the terminal, since I hook many many methods, and it is quite messy. Therefore I tried to inform the user about a new hook and have him hit enter before the next hook is being displayed on the terminal (basically, every time on_message() is called, Python's input() is called and the user can choose to continue or wait). However, this does not work very well, because I have to hit enter three times (instead of one). I'm guessing the first two times the input is sent to different threads, not the one they should be sent to.
So my question: is there any way to fix this? Or is there a better way?

**Comment by oleavr** [comment]
Yes, you can use something like https://github.com/prompt-toolkit/python-prompt-toolkit for handling user input.

As a side-note, it's crucial that you never ever do anything blocking in callbacks from Frida. Instead, add work to a queue that another thread processes. E.g. if you're using a GUI toolkit, schedule work on its thread (or create a new background thread).

**Comment by markiyanch** [comment]
@drZaius Have you managed to solve this issue anyhow?
