### ISSUE TITLE
Method: absoluteString

### ISSUE THREAD

**Issue by Quikko** [frida/frida#121]
Hello,

I am trying to convert a NSURL to a NSSTRING. The methods tried are "absoluteString" and "path", which return no output, no errors either. I'm probably forgetting about some basic stuff but really can't find what.

try{
  var nsurl = ObjC.Object(args[0]);
  var abs = nsurl.absoluteString;
} catch (error){
  send({event: 'error', error: error.message});
}

Best regards,
Quinten

**Comment by oleavr** [comment]
Hi,

It seems you forgot to call the method:

```js
var url = new ObjC.Object(args[0]);
var str = url.absoluteString().toString();
```

Objective-C properties are actually just syntactic sugar for a call to a method with the same name. Once you have an `NSString` you can call `toString()` on it to convert it to a JavaScript string (or you can use the `+` operator with an existing JavaScript string to convert it automatically, e.g. `"foo: " + s`, in which case `s.toString()` will be called automatically).

Also `new` should be used when constructing an `ObjC.Object`.

Hope this helps.

Cheers!
