### ISSUE TITLE
iOS Frida dylib - OSStatus error -34018

### ISSUE THREAD

**Issue by vtky** [frida/frida#122]
I am getting the following error when using the Frida dylib on a non-jailbroken device.

`The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)`

The application that I am loading into is an existing binary which I do not have the source code to. I have codesigned with the proper entitlements.

When I load in my own compiled dylib I do not get that error.

Running iOS 9.2. Frida dylib downloaded 11th March 2016.

What other information do you need that I can provide?

**Comment by oleavr** [comment]
Did you resign the app with corresponding entitlements as the original one? Remember that these will vary between apps. With this particular app it sounds like you are missing `keychain-access-groups`. You should also add `get-task-allow` to the list so the app can be launched with lldb (which is required for FridaGadget to be able to run unsigned code).

**Comment by vtky** [comment]
Hey Oleavr,

I'm using the following entitlements.plist. (Strings removed for privacy)
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string></string>
	<key>com.apple.developer.team-identifier</key>
	<string></string>
	<key>get-task-allow</key>
	<true/>
	<key>keychain-access-groups</key>
	<array>
		<string></string>
	</array>
</dict>
</plist>
```
Application was started using ios-deploy.

The functions that I'm targeting are:
- SSLSetSessionOption

- SSLHandshake

- SSLCreateContext

Running frida-trace works fine, however intercepting and replacing the methods does not.

**Comment by vtky** [comment]
Oh and I have just double checked, hooking those functions with Substrate does not work as well. I'm thinking it has something to do with unsigned code. However I have codesigned everything.

This is a snippet of my shell script
```
	codesign -fs "$CODESIGN" --entitlements entitlements.plist $APP_FILE/$APP_NAME
	codesign -fs "$CODESIGN" --entitlements entitlements.plist $APP_FILE/embedded.mobileprovision
	codesign -fs "$CODESIGN" --entitlements entitlements.plist $APP_FILE/CydiaSubstrate
	codesign -fs "$CODESIGN" --entitlements entitlements.plist $APP_FILE/FridaGadget.dylib
	codesign -fs "$CODESIGN" --entitlements entitlements.plist $APP_FILE/$dyldme_NAME.dylib
	codesign -fs "$CODESIGN" --entitlements entitlements.plist $APP_FILE
```

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
