### ISSUE TITLE
frida-trace error - Failed to attach: unexpected error while preparing pipe endpoints

### ISSUE THREAD

**Issue by jgrover** [frida/frida#1223]
Both client and server are running frida 12.8.16.

**Command from Mac OS X machine connected to iPhone X running iOS 13.2.2**
frida-trace -U -p 5783

**Full error message:**
Failed to attach: unexpected error while preparing pipe endpoints for process with pid 5783 (mach_port_allocate remote_rx returned '(os/kern) invalid task')

The device was jailbroken using checkra1n.  The command frida-ps -U works great!

**Comment by jgrover** [comment]
Update: Got this to work by installing through cydia.  I had originally pulled the latest iOS binary from the github releases page. Not sure what the difference is.

**Comment by oleavr** [comment]
Probably put the binary in a sandboxed location such as `/var/root`. The Cydia package places it in `/usr/sbin`.

**Comment by oleavr** [comment]
(And also the .deb launches it through launchd, which is the recommended way to run it.)

**Comment by jgrover** [comment]
Gotcha.  Looking further, it appears the launchd method was the only difference. I had the original github release version in /usr/sbin as well but had been running in daemon mode (frida-server -D).

**Comment by oleavr** [comment]
Ah! I don't think daemon mode works on iOS due to sandbox-restrictions.
