### ISSUE TITLE
Express http on Android only

### ISSUE THREAD

**Issue by DeBerk** [frida/frida#1224]
Is it possible to have an express script to handle http requests on Android only without a Frida server? E.g.: 

```
const express = require('express');

const app = express();

app
  .get('/test', (req, res) => {
    console.log("test");
	res.status(200).json({message: "working"});
  });

app.listen(1337);
```
I tried frida-inject but it seems like it's not listening to requests. Also, is frida-inject availible only for rooted devices or can it also be used with Frida Gadget?

**Comment by oleavr** [comment]
Yes you can use `frida-compile`:
https://github.com/frida/frida-net/tree/master/examples/http-server

You can in theory use `frida-inject` to attach to PID 0 – the system session – which means it's running inside `frida-inject` itself. This shouldn't require root. You can also configure Gadget to run standalone. (See docs.)

**Comment by DeBerk** [comment]
Thanks for the fast response. I have to inject the script into a specific app so I can't inject in PID 0. I used Gadget and that worked fine but how can I make it standalone running on Android only?

**Comment by oleavr** [comment]
> how can I make it standalone running on Android only

It's described [here](https://frida.re/docs/gadget/).
