### ISSUE TITLE
Support for enumerating loaded classes on Android 5.1.1

### ISSUE THREAD

**Issue by dpnishant** [frida/frida#123]
Running the following on Android 5.1.1 on Nexus 5

`var classes = Java.enumerateLoadedClassesSync();`

throws the following error.

```
Error: Enumerating loaded classes is only supported on Dalvik for now
    at _enumerateLoadedClasses (gumjs-java.js:172:23)
```

**Comment by oleavr** [comment]
Please file Java issues in [frida-java](https://github.com/frida/frida-java). Cheers!
