### ISSUE TITLE
Jailbroken iOS Crash/Reboot with frida-ps

### ISSUE THREAD

**Issue by gitbugr** [frida/frida#1231]
Using `frida-ps -U` doesn't work, and instead reboots my device.

I see this, even when Xcode is running. Pretty sure it's unrelated. 
```
Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually
```

Using `frida-ps -H [local-ip]` doesn't reboot my device, but it doesn't work. I'm able to ssh into my device fine and the server _is_ running, but I can't seem to connect to it using frida
```
Failed to enumerate processes: unable to connect to remote frida-server
```

### Steps to reproduce:

* Install A12+ Frida server from build.frida.re repo
* Run `frida-ps -U` from terminal with device plugged in
* Device reboots

### Relevant Specs

**Operating System:** MacOS 10.15.3
**Frida Version:** 12.8.19

**iOS Version:** 12.1.2
**iOS Model:** (XS Max) MT502B/A
**Jailbroken using:** Chimera

**Comment by gitbugr** [comment]
Additionally, running `frida -U [random pid]` reboots my device too
```
➜ frida -U 123
     ____
    / _  |   Frida 12.8.19 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Waiting for USB device to appear...
Failed to attach: unable to connect (error code: 2)
```

**Comment by oleavr** [comment]
Only the unc0ver jailbreak is supported on A12. PRs welcome to improve this though – but I won't be able to do that as I cannot reproduce this. (My A12 devices can only be jailbroken using unc0ver.)

**Comment by gitbugr** [comment]
@oleavr just checked using unc0ver and it does work using that. Strange. 
Either way, I don't mind as long as it works (:

**Comment by aupsham** [comment]
Same thing happening with me , i am using Checkra1n jailbreak is there any solution or workaround ,
Frida version: 16.0.2 for both linux system and IOS device iphone 5s,

**Comment by tuhin1729** [comment]
I experienced the same issue. I am using Chimera jailbreak, tried downgrading the Frida version after seeing #2349 but it didn't work for me.

iPhone6, iOS 12.4.8

**Comment by tin-z** [comment]
Hi i had the same issue with an iphone 5s 12.5.5, this is how i solved:

- 1 - reboot the iphone and jailbreak it with unc0ver, the latest version is fine
   * 1.1 - Before opening the app, remove the passcode and put the iphone in airplane-mode
   * 1.2 - Open the app, be sure the flags "Block auto Updates" and "(Re)install OpenSSH" are on
   * 1.3 - Now before pressing the "Jailbreak" button wait 1 minute, then press it
   * 1.4 - if it doesn't work repeat from 1.1 point
 
 - 2 - install frida with cydia, then connect with ssh for checking the service is up

**Comment by 0x30c4** [comment]
Hey @tin-z , your method works iPad Air 12.5.8. thanks mate!
