### ISSUE TITLE
How to hook class-dump-z header file method

### ISSUE THREAD

**Issue by lu4kyd0y** [frida/frida#124]
I am very interested in this HOOK Frida framework also read the official document. But there is still some confusion, how  to hook class-dumpheader file method. like this, I want to hook onFirstUserLoginUserName this method
`@protocol WCAccountLoginFirstUserViewControllerDelegate <NSObject> 
@required
-(void)onFacebookConnect;
-(void)onFirstUserBack;
-(void)onLoginByPhoneFromQQ;
-(void)onFirstUserProblem:(id)arg1;
-(void)onFirstUserLoginUserName:(id)arg1 Pwd:(id)arg2;
@end`
what should i do in Python ,
Can you give me some examples for ios hook
Thanks!

**Comment by oleavr** [comment]
This is covered by the website (check out the “Examples” section).
