### ISSUE TITLE
Frida Build Error on ArchLinux

### ISSUE THREAD

**Issue by maiyao1988** [frida/frida#1240]
I'm trying to build frida tags/12.8.20.I clone the resp and type
`make python-linux-x86_64 PYTHON=/usr/bin/python`

but I get this error.

> build/frida-meson-env-linux-x86_64.rc && /home/my/src/frida/releng/ninja-linux-x86_64 -C build/tmp-linux-x86/frida-core src/frida-helper lib/agent/frida-agent.so
> ninja: Entering directory `build/tmp-linux-x86/frida-core'
> [1/1] Generating frida-agent with a custom command.
> FAILED: lib/agent/frida-agent.so 
> /home/my/src/frida/frida-core/tools/modulate.py lib/agent/_frida-agent.so --move constructor frida_init_memory first --move destructor frida_deinit_memory first --endian little --output lib/agent/frida-agent.so --nm /usr/bin/nm --objdump /usr/bin/objdump --otool otool --install-name-tool install_name_tool
> 'NoneType' object has no attribute 'groups'
> ninja: build stopped: subcommand failed.

my python version is Python 3.7.2
any idea?

**Comment by root-intruder** [comment]
same here!
