### ISSUE TITLE
Frida Cydia repository unavailable

### ISSUE THREAD

**Issue by BreakfastSerial** [frida/frida#1242]
I've added the Frida repository for Cydia on multiple devices, but it seems to be unavailable.
On `iOS 13.2.2` (iPhone SE) and on `iPadOS 13.3.1` (iPad 7) the repository shows no packages.

If I browse to the repository in Firefox I get the following:

```404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: index.html
    RequestId: <REQUEST-ID>
    HostId: <HOST-ID>
```

Is there an alternative to install Cydia on my devices? Something like a clone of the git repository and a local Cydia server?

**Comment by BreakfastSerial** [comment]
Nevermind. I am an idiot.

**Comment by mfeldheim** [comment]
What did you find out? Seems I am an idiot as well...

**Comment by oleavr** [comment]
Don't be confused by the lack of an index page in our S3 bucket – add `https://build.frida.re` as a source in Cydia.

**Comment by chensokolovsky** [comment]
Hi, it there a way to install frida-server on iOS via command line (ssh into JB device)?
Something like: apt install frida-server

**Comment by hugollsouza** [comment]
> I've added the Frida repository for Cydia on multiple devices, but it seems to be unavailable. On `iOS 13.2.2` (iPhone SE) and on `iPadOS 13.3.1` (iPad 7) the repository shows no packages.
> 
> If I browse to the repository in Firefox I get the following:
> 
> ```
> 
>     Code: NoSuchKey
>     Message: The specified key does not exist.
>     Key: index.html
>     RequestId: <REQUEST-ID>
>     HostId: <HOST-ID>
> ```
> 
> Is there an alternative to install Cydia on my devices? Something like a clone of the git repository and a local Cydia server?

You have tring this:
Download the frida version 16.0.7 into your iphone.
`wget https://github.com/frida/frida/releases/download/16.0.7/frida_16.0.7_iphoneos-arm.deb`

Then install by apt:
`apt install ./frida_16.0.7_iphoneos-arm.deb`
