### ISSUE TITLE
Can not install frida through npm on MacOS

### ISSUE THREAD

**Issue by pharazone** [frida/frida#1250]
Hello, I use MacOS 10.15, and frida can not be installed on my mac
![image](https://user-images.githubusercontent.com/11215634/79065556-d3bcaf00-7ce3-11ea-80ed-bb7811171b48.png)
and It stuck in "prebuild-install || node-gyp rebuild"

node version 8.16.1
macOS CATALINA 10.15

**Comment by pharazone** [comment]
xxx@MacBook-Air ~ % npm install frida

> frida@12.8.20 install /Users/xxx/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install unexpected end of file
gyp: binding.gyp not found (cwd: /Users/xxx/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/node_modules/frida
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/xxx/package.json'
npm WARN xxx No description
npm WARN xxx No repository field.
npm WARN xxx No README data
npm WARN xxx No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.8.20 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@12.8.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2020-04-13T01_30_36_620Z-debug.log

**Comment by oleavr** [comment]
You shouldn't install it like that. Instead do something like:

```sh
$ mkdir my-tool
$ cd my-tool
$ npm init
$ npm install frida
```

**Comment by oleavr** [comment]
For a complete example you can grab:
https://github.com/oleavr/frida-tool-example

**Comment by H0r53** [comment]
@oleavr I'm having the same issues. I even cloned the `frida-tool-eample` repo and followed the install steps there. Attempting to npm install frida on MacOS throws the following errors:

`
npm install
npm ERR! code 1
npm ERR! path /Users/horse/Repos/frida-tool-example/node_modules/frida
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=16.2.0 runtime=node arch=x64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.2.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.5 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! (node:12936) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/horse/Repos/frida-tool-example/node_modules/frida/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/horse/Library/Caches/node-gyp/16.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/horse/Library/Caches/node-gyp/16.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/horse/Library/Caches/node-gyp/16.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/horse/Repos/frida-tool-example/node_modules/frida',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: /Users/horse/Repos/frida-tool-example/node_modules/frida) while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/horse/Repos/frida-tool-example/node_modules/frida
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
`

I've been fighting with this for the past several hours and just want to use Frida via npm. What could be causing this issue? What is gyp doing, and why might binding.gyp not be found?

**Comment by H0r53** [comment]
Installing `nvm` and switching to node version 12.22.1 resolved the issue.

**Comment by Emi1305** [comment]
> Installing `nvm` and switching to node version 12.22.1 resolved the issue.

Wow, thanks. After an entire day lost trying to track this cryptic issue this worked. Anyway, it REALLY sucks to require an old version of node to be able to use this :S

**Comment by bensh** [comment]
Also tried this. Couldn't get frida to install on anything higher than 12.19.1 - npm 6.14.8

**Comment by alcastronic** [comment]
I also have this issue on MacOS Sonoma 14.0 

```
npm -v
10.2.0
```

```
node -v
v21.0.0
```

```
λ npm install -gi frida
npm ERR! code 1
npm ERR! path /Users/.../frida
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=21.0.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@21.0.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.11.5 found at "/Users/.../frida/venv/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v21.0.0/node-v21.0.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v21.0.0/node-v21.0.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v21.0.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v21.0.0/SHASUMS256.txt
npm ERR! gyp info spawn /Users/.../.../venv/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/.../.../node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/.../.../node_modules/frida/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/.../.../node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/.../Library/Caches/node-gyp/21.0.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/.../Library/Caches/node-gyp/21.0.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/.../.../node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/.../Library/Caches/node-gyp/21.0.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/.../.../node_modules/frida',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: /Users/.../.../node_modules/frida) while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/.../.../node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 23.0.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/21.0.0/bin/node" "/Users/.../.../node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/.../.../node_modules/frida
npm ERR! gyp ERR! node -v v21.0.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok
```
