### ISSUE TITLE
Frida Failed to spawn

### ISSUE THREAD

**Issue by spacex97** [frida/frida#1252]
Hello
I am getting following error. Can anyone help pls?

`Failed to spawn: unable to find a front-door activity`

**Comment by spacex97** [comment]
Issue has been fixed

**Comment by balook** [comment]
@spacex97 how you fixed it bro

**Comment by imatary** [comment]
> Hello
> I am getting following error. Can anyone help pls?
> 
> `Failed to spawn: unable to find a front-door activity`

How did you fixed it?? We Need Help
