### ISSUE TITLE
class's fields and methods not loaded in android 9

### ISSUE THREAD

**Issue by xuchongfeng** [frida/frida#1253]
I am hacking an app，hook the target method。in android 7，the target method exist， but in android 9， the target method is not。
i use the following function to print the fields and methods。
function describeJavaClass(className) {
    var jClass = Java.use(className);
    console.log(JSON.stringify({
      _name: className,
      _methods: Object.getOwnPropertyNames(jClass.__proto__).filter(function(m) {
        // return !m.startsWith('$') && m != 'class' && m != 'constructor' // optional
        return true;
      }), 
      _fields: jClass.class.getFields().map(function(f) {
        return f.toString()
      })
    }, null, 2));
}

the output in android 7:
"_methods": [
    "constructor",
    "$new",
    "$init",
    "$alloc",
    "$dispose",
    "$isSameObject",
    "class",
    "$className",
    "aS",
    "dSA",
    "dSB",
    "doScene",
    "getType",
    "onGYNetEnd",
    "callback",
    "gTO",
    "scene",
    "ziG",
    "zjc",
    "zoT",
    "zoU"
  ],
  "_fields": []
the output in android 9:
  "_methods": [
    "$n",
    "$C",
    "$w",
    "$_s",
    "$c",
    "$m",
    "$l",
    "$gch",
    "$f"
  ],
  "_fields": []

the methods in android9 is not complete.

**Comment by oleavr** [comment]
Is the device-side frida-server the latest version? We should be exposing all field and methods now.

**Comment by xuchongfeng** [comment]
> Is the device-side frida-server the latest version? We should be exposing all field and methods now.

Thank you for your reply!!
I update to the latest version 12.8.20, device-side and frida-server, the same result.
Actually I found the method can be hooked. but the function i use can print out the methods and fields in android7.1.2, but not in android 9.0.
the function i use:
`function describeJavaClass(className) {
var jClass = Java.use(className);
console.log(JSON.stringify({
_name: className,
_methods: Object.getOwnPropertyNames(jClass.proto).filter(function(m) {
// return !m.startsWith('$') && m != 'class' && m != 'constructor' // optional
return true;
}),
_fields: jClass.class.getFields().map(function(f) {
return f.toString()
})
}, null, 2));
}`
