### ISSUE TITLE
frida_gadget_detect_location: assertion failed: (our_range != null)

### ISSUE THREAD

**Issue by qq1091192337** [frida/frida#1254]
This problem occurred when I use frida-gadget.My steps are following:
1.Using apktool to decomplie the apkfile.
2.Change the Application entrypoint in order to injection(ps:many entrypoint that I have tried,but it doesn't work.So I don't think the problem is there)
3.copy the file gadget.so into the lib folder.
4.create the config file named **gadget.so.config into lib folder and writein config text.**
5.packing the apk file.
6.signing the apk file.
7.installing.
But it doesn't work.The error text is the **title.I** have searched many article but can't find a issue which similar with mine.

My OS is Win10 and Test OS is Android 7.1 simulator.
The gadget config type is script. **and I have pushed the js into the path.**

Does anyone have a good idea

**Comment by qq1091192337** [comment]
@oleavr Hi,do you have some solutions?

**Comment by oleavr** [comment]
Fixed in Frida 12.9.

**Comment by intelligentpotato** [comment]
Hi! I'm experiencing the same issue with 12.10.4. I injected the gadget using **lief**:
`libnative = lief.parse("lib/armeabi-v7a/libcocos2djs.so")
libnative.add_library("libfrida-gadget.so")
libnative.write("lib/armeabi-v7a/libcocos2djs.so")
`

The app instantly crashes and in logcat I'm getting:
`
07-19 04:19:15.897  9045  9045 F DEBUG   : Abort message: 'frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)'
07-19 04:19:15.897  9045  9045 F DEBUG   :     eax 00000000  ebx 00002310  ecx 00002310  edx 00000006
07-19 04:19:15.897  9045  9045 F DEBUG   :     esi a8e44584  edi a8e4452c
07-19 04:19:15.898  9045  9045 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000043  xss 0000007b
07-19 04:19:15.898  9045  9045 F DEBUG   :     eip a462bc56  ebp bfabc488  esp bfabc440  flags 00000202
07-19 04:19:15.898  9045  9045 F DEBUG   :
07-19 04:19:15.898  9045  9045 F DEBUG   : backtrace:
07-19 04:19:15.898  9045  9045 F DEBUG   :     #00 pc 00000c56  /system/lib/libc.so (offset 0x7d000)
`

**Comment by aoprea1982** [comment]
Same with frida 12.11.11 

```
: Abort message: 'frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)'
```

**Comment by intelligentpotato** [comment]
> Same with frida 12.11.11
> Using frida-gadget-12.11.11-android-arm.so.xz
> Emulator: NoxPlayer 7.0.0.5
> 
> ```
> : Abort message: 'frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)'
> ```

Emulators are using libhoudini to translate native ARM-library code to x86. Frida can't hook such libraries as I've read in other issues. The solution is to buy a real ARM-device.

**Comment by aoprea1982** [comment]
Thanks!
