### ISSUE TITLE
java enum class hook

### ISSUE THREAD

**Issue by Cydia5530** [frida/frida#1256]
i got a problem...
how can i hook a java enum class, or new a enum class?
anyone can tell me ....

**Comment by Watergun** [comment]
You can use simply reference the respective enum member.
For example, for the following enum:
```
public enum MyEnum {
     A, B, C, D
};
```
You at first need `var MyEnum = Java.use("....MyEnum")` to get a reference to the enum. Then you can do `MyEnum.A.value` in order to get the enum member value as a String.

**Comment by n0n0peration** [comment]
@Watergun @oleavr Can you elaborate on an example? Say you are attempting to use JS script like below with return or console.log:

```
Java.perform(() => {
var enumContent = Java.use('com.some.package.Enum');
return enumContent.values();
)};
```
or
```
Java.perform(() => {
var enumContent = Java.use('com.some.package.Enum');
console.log(enumContent.A.value);
)};
```

Assuming your Java code looks like this:

```
package com.some.package;

import kotlin.Metadata;

public enum Enum {
    A,
    B,
    C,
    D
}
```
