### ISSUE TITLE
Android SSL Re-pinning frida {Failed to load script: script(line 42): SyntaxError: unterminated statement}

### ISSUE THREAD

**Issue by UnknowUsername** [frida/frida#1258]
Hello, I'm too new with frida, getting different errors while trying bypass ssl pin
Tried different frida-server inside android
I got x86 by this command `adb shell getprop ro.product.cpu.abi` , if I call 
`frida -U -f com.app.pornhub -l C:\Users\xxx\fridascript.js --no-paus` getting this msg.
`Failed to load script: script(line 42): SyntaxError: unterminated statement`
But if I try different frida server on my x86 arch like simple arm, getting this
`"Failed to spawn: unable to inject library into process without libc"`
I`m using paid genymotion VM, any suggestion on which version I can run it?
Script I got from this [link](https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/)

**Comment by tjytjytj** [comment]
show the code of the file js

**Comment by UnknowUsername** [comment]
> 
> 
> show the code of the file js

I`m alredy provide script code https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/

**Comment by tjytjytj** [comment]
on x86 the error you are getting "libc.so" it is because frida ARM can run  in x86 emulator but it wont work , the other error i still cant know why , maybe you have modified the file so thats why i asked you to copy paste all the file C:\Users\xxx\fridascript.js , for first u need to put the certeficate file in /data/local/tmp/cert-der.crt or change the location in the js file

**Comment by UnknowUsername** [comment]
Thx for reply, I`m using this tutorial https://medium.com/@ved_wayal/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29
I did step by step.

**Comment by tjytjytj** [comment]
it does not matter the tutorial , what matters is what is inside the file , stick with frida x86 server it is the only version that will work for suck emulators , did you edit the file .js or you just made copy paste ?

**Comment by tjytjytj** [comment]
unterminated statement it means you did not copy everything , you are missing a `}` or `)` or `;`

**Comment by UnknowUsername** [comment]
> 
> 
> it does not matter the tutorial , what matters is what is inside the file , stick with frida x86 server it is the only version that will work for suck emulators , did you edit the file .js or you just made copy paste ?

Just copy/paste, with out editing

**Comment by UnknowUsername** [comment]
> 
> 
> unterminated statement it means you did not copy everything , you are missing a `}` or `)` or `;`

I think I know problem, will try

**Comment by UnknowUsername** [comment]
> 
> 
> unterminated statement it means you did not copy everything , you are missing a `}` or `)` or `;`

Thanks You, yes it was bad paste of script. Solved

**Comment by tjytjytj** [comment]
scroll all the way down you will find close issue button , just below where you type the comments
