### ISSUE TITLE
:frida_resolve_library_function: assertion failed: (remote_base != 0)

### ISSUE THREAD

**Issue by alexanderkjall** [frida/frida#126]
When trying to use frida against the attached file, the following output is produced:

$ frida ./toooooo-many-switches.0d37258813df342629a335a35f040be6 
     ____
    / _  |   Frida 7.0.9 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Spawning `./toooooo-many-switches.0d37258813df342629a335a35f040be6`...  
**
Failed to attach: the connection is closed                           :frida_resolve_library_function: assertion failed: (remote_base != 0)
usage: ./toooooo-many-switches.0d37258813df342629a335a35f040be6 <input>

[data.zip](https://github.com/frida/frida/files/180977/data.zip)

**Comment by oleavr** [comment]
Let's keep tracking this at frida/frida-core#101.
