### ISSUE TITLE
Exception not prapagating from Frida to process using CustomHook

### ISSUE THREAD

**Issue by himanshusharma2973** [frida/frida#1278]
I want to throw a "exception" in a process. I have created a custom hook method which throws exception. I am attaching that customhook function to my process to throw exception but the exception is not getting propagated to my process to handle it. And my process is getting crashed.

`**Process:**` 
#include "iostream"
#include "chrono"
#include "thread"
class A {
    public:void print() noexcept(false) {
        static int i=1;
        std::cout<<i++<<std::endl;
    }
};
int main(int argc, const char * argv[]) {
    // insert code here...
    std::cout << "Hello, World!\n";
    while(1) {
        A a;
        try {
            a.print();
        } catch(int i) {
            std::cout<<"exception caught int"<<std::endl;
        } catch(...) {
            std::cout<<"exception caught"<<std::endl;
        }
        std::this_thread::sleep_for(std::chrono::milliseconds(4000));
    }
    return 0;
}

`**Custom Hook Code**`
#include <stdio.h>
#include <iostream>
#include <exception>
extern "C"
{
    void beforeCreateSyncController(){
        throw "some exception";
    }
}

`**Frida script**`
function dlopen_(library) { 
  var _dlopen = new NativeFunction(Module.findExportByName(null, 'dlopen'), 'pointer', ['pointer', 'int']); 
  var RTLD_GLOBAL = 0x8; 
  var RTLD_LAZY = 0x1; 
  var path = Memory.allocUtf8String(library); 
  var handle = _dlopen(path, RTLD_GLOBAL | RTLD_LAZY); 
  if (handle.isNull()) 
  { 
    send('Failed to load ' + library) 
    throw new Error('Failed to load ' + library); 
   } 
  return handle; 
}              
dlopen_("/Users/CustomHook/libCSCustomHook.dylib")
functionPtr = DebugSymbol.findFunctionsMatching("*A*print*")[0];
throwCSFunction = Module.findExportByName('libCSCustomHook.dylib', 'beforeCreateSyncController');
Process.setExceptionHandler(function(exp) {
console.log("inside setExceptionHandler")
return false;
});
nativeThrowFunction = new NativeFunction(throwCSFunction, 'void', [] ,{exceptions:'propagate'});
Interceptor.replace(functionPtr, new NativeCallback(function(arg1) 
{ 
console.log("throwCSFunction() to be called") 
    nativeThrowFunction() 
    //return 0; 
    console.log("throwCSFunction() called") 
},'void', ['pointer']))

**Process Output**
`Hello, World!
1
2
3
4
5
6
7
8
libc++abi.dylib: terminating with uncaught exception of type std::logic_error
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]`

**Frida console output**
`[Local::Test]-> throwCSFunction() to be called
inside setExceptionHandler
Process terminated
[Local::Test]->                                                                 

Thank you for using Frida!`

Please help me with it. I am stuck. I basically want frida to throw exception from a process function.

**Comment by git-ashutoshverma** [comment]
Hi @oleavr , I am facing similar issue where I am not able to propagate the exception. Basically, I want debugee process to handle the raised exception.

**Comment by oleavr** [comment]
@git-ashutoshverma This is covered by the [NativeFunction documentation](https://frida.re/docs/javascript-api/#nativefunction). You want `exceptions: 'propagate'` instead of the default, which is `'steal'`.

**Comment by git-ashutoshverma** [comment]
We are using `exceptions: 'propagate' `, still fails to propagate the exception. The process is crashing as a result. Pasted the entire code above.

**Comment by git-ashutoshverma** [comment]
Hi @oleavr ,, I am facing the issue despite setting `exceptions: 'propagate' `.

**Comment by himanshusharma2973** [comment]
Hi @oleavr , if you check my above piece of code, I am using `exceptions : propagate` but still facing the issue.
