### ISSUE TITLE
frida.NotSupportedError: java API not available in get_frontmost_application

### ISSUE THREAD

**Issue by geeksec80** [frida/frida#128]
# get_front_app.py

import frida
rdev = frida.get_remote_device()
front_app = rdev.get_frontmost_application()
print front_app

When I run the above script, it shows the following errors.

E:\Security\android security\tool\hook\frida\scripts>python get_front_app.py
Traceback (most recent call last):
  File "get_front_app.py", line 3, in <module>
    front_app = rdev.get_frontmost_application()
  File "C:\Python27\lib\site-packages\frida-7.0.11-py2.7-win32.egg\frida\core.py", line 56
, in get_frontmost_application
frida.NotSupportedError: java API not available

My machine environment is the followings:
rooted Nexus 5 6.0.1 with Mar, 2016 patch, Windows 10

Would you help me check it? Thanks!

**Comment by small-evil-beast** [comment]
hi,i have the same problem,have you solved it?

**Comment by oleavr** [comment]
Not able to reproduce.
