### ISSUE TITLE
I cannot run my Frida Bypass SSL Pinning Script

### ISSUE THREAD

**Issue by Rezkmike** [frida/frida#1280]
![Screenshot from 2020-04-26 16-39-47](https://user-images.githubusercontent.com/48907062/80302472-da1b5280-87dc-11ea-9ee1-c84110d06c3c.png)

**Comment by Kroop-fr** [comment]
I think Frida is not installed

Do 
`pip install frida-tools `

**Comment by Rezkmike** [comment]
Now its already works. Need to restart my laptop and run the command. Thanks
