### ISSUE TITLE
Faster way to transfer byte[] between Java and JS engine

### ISSUE THREAD

**Issue by KB5201314** [frida/frida#1281]
I want to use Java functions to decrypt some byte arrays, but the transfer process of the array is very slow.

I have some code like this (`byteListInJs` is integer array in JS, and `byteListRtnInJava` is `byte[]` object in Java):
```js
function decrypt(byteListInJs) {
        Java.perform(function () {
            ...
            var byteListInJava = bytelist_js_to_java(byteListInJs)
            var byteListRtnInJava = javaObj.decrypt(byteListInJava)
            var byteListRtnInJS = bytelist_java_to_js(byteListRtnInJava)
            ...
        }
}
```

At the beginning my function was implemented like this:
```js
function bytelist_js_to_java(bytelist){
    return Java.array('byte', bytelist)
}

function bytelist_java_to_js(bytelist){
    var rtn = new Array(bytelist.length)
    for(var i = 0; i < bytelist.length; ++i) {
        rtn[i] = bytelist[i]
    }
    return rtn;
}

```

When processing 50KB of data, the `bytelist_js_to_java()` costs 2s and `bytelist_java_to_js()` costs 5s. Since I have a lot of data to process(about 10MB), this will be very slow.

Fortunately, I found it to be very fast when transferring strings, so I started trying to transfer the data as a string. For the second function, I found another faster implementation, by convert array to JSONArray in Java, and parse it in JS, which cost 0.2s only, ten times faster than `Java.array('byte', bytelist)`.

```js
function bytelist_java_to_js(bytelist){
    var jsonString = Java.use('org.json.JSONArray').$new(bytelist).toString();
    return JSON.parse(jsonString);
}
```

For the first function `bytelist_js_to_java()`, I can't find any existing method in Java that can be used directly to convert JSON to an byte array(`byte[]`), so cannot use json. 

Then I tried base64, by encode byte arrays to base64 string in js, then decode it to `byte[]` in Java by `android.util.Base64`. the `android.util.Base64.decode()` is fast enough, but the base64 encode in JS side is too slow (I used a self-implemented version of `Base64.encode()` because there is no base64 support provided by v8).
```js
function bytelist_js_to_java(bytelist){
    // return Java.array('byte', bytelist)
    var base64Str = base64Encode(bytelist)
    var androidBase64 = Java.use('android.util.Base64')
    var bytesInJava = androidBase64.decode(base64Str, 0)
    return bytesInJava;
}
```

Can someone suggest me a faster `bytelist_js_to_java()` function? Or can frida provide some conversion interface?

Thank you!

**Comment by adam-flynn** [comment]
If CModule is available, you can write your own native base64 encoding...
But this one achieves near-native performance (don't worry that the base64 encoding may be wrong for charcodes >=128; it's actually correct):
https://jsperf.com/tobase64-implementations/20

**Comment by adam-flynn** [comment]
If CModule is available, you can write your own native base64 encoding...
But this one achieves near-native performance (don't worry that the base64 encoding may be wrong for charcodes >=128; it's actually correct):
https://jsperf.com/tobase64-implementations/20

**Comment by adam-flynn** [comment]
If CModule is available, you can write your own native base64 encoding...

**Comment by KB5201314** [comment]
> If CModule is available, you can write your own native base64 encoding...

thank you

**Comment by crifanWeb3** [comment]
refer @imlk0  code, finally code:

```js
class FridaUtil {
  static JavaArray = null

  static {
    FridaUtil.JavaArray = Java.use('java.lang.reflect.Array')
    console.log("FridaUtil.JavaArray=" + FridaUtil.JavaArray)
  }

  constructor() {
    console.log("FridaUtil constructor")
  }

  // java byte array to js byte array
  static javaByteArrToJsByteArr(javaByteArr){
    // var javaByteArrLen = javaByteArr.length
    // console.log("javaByteArrLen=" + javaByteArrLen) // javaByteArrLen=undefined
    var javaByteArrGotLen = FridaUtil.JavaArray.getLength(javaByteArr)
    // console.log("javaByteArrGotLen=" + javaByteArrGotLen) // javaByteArrGotLen=8498
    var jsByteArr = new Array()
    // console.log("jsByteArr=" + jsByteArr)
    for(var i = 0; i < javaByteArrGotLen; ++i) {
      // jsByteArr[i] = javaByteArr[i]
      var curByte = FridaUtil.JavaArray.get(javaByteArr, i)
      // console.log("curByte=" + curByte)
      jsByteArr[i] = curByte
    }
    // console.log("jsByteArr=" + jsByteArr)
    return jsByteArr;
  }

}
```

call:

```js
            var jsByteArr = FridaUtil.javaByteArrToJsByteArr(javaByteArr)
            console.log("jsByteArr=" + jsByteArr)
```

output:

```bash
jsByteArr=8,-60,-112,-128,-126,4,16,2,24 ...
```
