### ISSUE TITLE
I need the latest stable version

### ISSUE THREAD

**Issue by ballen127** [frida/frida#1291]
Hi @oleavr 

I am trying to build frida v12.8.20 in Windows.
But I got errors because links of sdk and toolchains are not existing.
https://github.com/frida/frida/blob/12.8.20/releng/windows-sdk.txt
https://github.com/frida/frida/blob/12.8.20/releng/windows-toolchain.txt

I can see links of master branch are available.
So I modified releng/windows-sdk.txt and releng/windows-toolchain.txt with the links and tried to build but i got tons of errors such as v8/v8.h are not found.

Should I use current dev version instead of v12.8.20?

I need it urgently. Please help me.

Thank you!

**Comment by oleavr** [comment]
Hi,

It's unfortunately not possible as old SDKs/toolchains aren't kept around, although I'm hopeful this will improve in the future as we get more people involved who can help with devops and infrastructure. For now your best bet is to build master – it's release candidate quality and I plan on cutting a release soon-ish. (You could in theory build the old toolchain and SDK, but it would require fixing the build scripts to allow building anything other than `master` of the git repos with our dependencies.)

Cheers!
