### ISSUE TITLE
static method are not intercepted

### ISSUE THREAD

**Issue by salisbury-espinosa** [frida/frida#1298]
frida --version: 12.8.20
```js
Java.perform(() => {
  const TestClass = Java.use(
    'com.test.TestClass',
  );
  TestClass.testStaticMethod.overload('java.lang.String', 'java.util.Map').implementation = function (
    str,
    map,
  ) {
    console.log('intercept!');
    return this.b(str, map);
  };
  const testStr = Java.use('java.lang.String').$new('test');
  const testMap = Java.use('java.util.HashMap').$new();

  // test it!	
  TestClass.testStaticMethod(testStr, testMap);
});
```

it does NOT output 'intercept!'
the original method is called. what could be the reason?

**Comment by oleavr** [comment]
You may need to `Java.deoptimizeEverything()` as optimizations often mean that such hooks are bypassed.

**Comment by mrsonger** [comment]
I wonder did you resoved ? I have the same problem  @salisbury-espinosa

**Comment by ckcr4lyf** [comment]
@mrsonger  I just put `Java.deoptimizeEverything()` as @oleavr  suggested at the top. Worked like a charm
