### ISSUE TITLE
use upstream capstone

### ISSUE THREAD

**Issue by blshkv** [frida/frida#130]
it would be good if you could push your changes back to capstone if possible.
Capstone is calling itself a framework, that should probably mean flexibility.

I'm trying to compile frida under linux and the current system capstone is not compatible with your fork. The configure script does not allow me to specify a different location for capstone specifically which cases the mess.

**Comment by oleavr** [comment]
Hi,

The changes we depend on are still not merged (modrm offset) and have been sitting in the `encoding` branch upstream for a long time, so this is unfortunately out of our control.

Cheers!

**Comment by blshkv** [comment]
Let me try to include https://github.com/aquynh here

**Comment by aquynh** [comment]
i havent merged this because it would break all the existing bindings.
it is only a matter of time, however. my plan is to solve this issue sometime this month, or next month, because i also want to push out v4.0 soon.

thanks.

**Comment by blshkv** [comment]
I guess I can close that one since the changes has been attempted to push to upstream and work is in progress. Thank you all for the good work!
