### ISSUE TITLE
"can't decode byte 0xc0 in position", g_utf8_validate not support mutf-8

### ISSUE THREAD

**Issue by centy720** [frida/frida#1306]
if a utf8 string contains 0x00, for  modified utf-8,  it encodes to 0xC080, but g_utf8_validate can't process 0xC080

**Comment by oleavr** [comment]
Yes if you're dealing with strings where the encoding isn't well-defined, use `.readCString()` instead of `.readUtf8String()`.

**Comment by centy720** [comment]
but the default string 

> Yes if you're dealing with strings where the encoding isn't well-defined, use `.readCString()` instead of `.readUtf8String()`.

but the default process is readUft8String,  so if function param is not utf8 encoding,  function  hooking will failed, nothing user can do
