### ISSUE TITLE
How frida works? Does frida have any documents about it?

### ISSUE THREAD

**Issue by ghd8239820** [frida/frida#1309]

**Comment by oleavr** [comment]
There's an overview here:
https://frida.re/docs/hacking/
With links to the different parts of the code base.

Frida's Stalker is documented here:
https://frida.re/docs/stalker/

Some technical details are covered in these talks:
https://youtu.be/uc1mbN9EJKQ
https://youtu.be/y95St7wIUZU

**Comment by ghd8239820** [comment]
> There's an overview here:
> https://frida.re/docs/hacking/
> With links to the different parts of the code base.
> 
> Frida's Stalker is documented here:
> https://frida.re/docs/stalker/
> 
> Some technical details are covered in these talks:
> https://youtu.be/uc1mbN9EJKQ
> https://youtu.be/y95St7wIUZU

thanks 👍
