### ISSUE TITLE
early instrumentation in gadget (interaction type == listen)

### ISSUE THREAD

**Issue by salisbury-espinosa** [frida/frida#1312]
frida --version
12.8.20

configuration:
```json
{
  "interaction": {
    "type": "listen",
    "address": "127.0.0.1",
    "port": 27042,
    "on_load": "wait"
  }
}
```
script:

```js
rpc.exports = {
  init:  (stage, parameters) => {
    return new Promise((resolve) => setTimeout(resolve, 20000));
  },
  dispose: () => {
    console.log('[dispose]');
  },
};
```
run it:

```shell
frida -U Gadget -l test_compiled.js --runtime v8
```
I see **Attaching ...** for 20 seconds but the application starts immediately and I see all its activity during this time, but in documentation:

> Gadget calls your init() method and waits for it to return before letting the program execute its entrypoint. This means you can return a Promise if you need to do something asynchronous, e.g. Socket.connect(), and guarantees that you won’t miss any early calls.

the expected behavior (correct) is observed with this configuration
```json
{
  "interaction": {
    "type": "script",
    "path": "/data/local/tmp/test_compiled.js"
  }
}
```

**Comment by oleavr** [comment]
The issue is that you're asking Frida to attach, not spawn. What you want is:

```sh
$ frida -U -f re.frida.Gadget --no-pause -l test_compiled.js --runtime=v8
```

**Comment by oleavr** [comment]
(Please let me know if the `init()` guarantee is ignored even if you spawn though!)

**Comment by salisbury-espinosa** [comment]
@oleavr I saw that this has already been described by you
 https://github.com/frida/frida-core/pull/280#issuecomment-565207784
but I’m using gadget and the main reason is that there is no root access on the device, it is possible to patch the application (that is, in this task there is no frida server running).
so what you offer (use spawn instead of attaching) is incorrect for tasks requiring gadget, this is suitable for tasks that use frida-server...

```shell
frida -U -f test.test -l test_compiled.js --runtime=v8
Failed to spawn: unable to connect to remote frida-server: closed
```

**Comment by salisbury-espinosa** [comment]
@oleavr 
1. I launch the application with my hands (it is waiting)
2. frida -U -f re.frida.Gadget --no-pause -l test_compiled.js --runtime=v8

```shell
Failed to load script: the connection is closed 
```

**Comment by oleavr** [comment]
@salisbury-espinosa That means it's crashing. This is probably the constructor ordering bug that's already fixed in the latest Frida (12.9.4). Could you try updating?

**Comment by salisbury-espinosa** [comment]
upgrade helped! thank you!

**Comment by oleavr** [comment]
@salisbury-espinosa Glad to hear!
