### ISSUE TITLE
Failed to spawn process with iOS 13.5 and unc0ver 5.0.1

### ISSUE THREAD

**Issue by inode-** [frida/frida#1315]
Hello,

it's seems that there is some problem on spawning process on iOS 13.5 with unc0ver (frida 12.9.4) on iPhone 8 (with processor A11).

Attaching to a running PID is working correctly. It's the first time that I use the iPhone 8 with frida, so I didn't know if previous version of the OS can change the situation. Using frida 12.8.20 get the same problems.

```
# uname -a
Darwin pippo-iPhone 19.5.0 Darwin Kernel Version 19.5.0: Tue Apr 28 22:25:09 PDT 2020; root:xnu-6153.122.1~1/RELEASE_ARM64_T8015 iPhone10,1 arm64 D20AP Darwin
```

Error reported:

- Launching frida-server via console: "Failed to attach: expecting to read a single byte for receiving credentials but read zero bytes"
- Launching frida-server via console with -D option: "Failed to spawn: unexpected error while preparing pipe endpoints for process with pid 1 (mach_port_allocate remote_rx returned '(os/kern) invalid task')"

I think the problem is related to these previous issues, in particular to the first one:

- https://github.com/frida/frida/issues/931
- https://github.com/frida/frida/issues/792
- https://github.com/frida/frida/issues/885

Thank you

inode

**Comment by demhademha** [comment]
Is the iOS repo working now?

**Comment by inode-** [comment]
> 
> 
> Is the iOS repo working now?

I don't know, I use the frida-server directly

**Comment by alex1704** [comment]
Experience same issue with jb from unc0ver 5.0.1 on frida 12.9.4.
iPhone 7, iOS 13.5
# uname -a
Darwin iphone 19.5.0 Darwin Kernel Version 19.5.0: Tue Apr 28 22:25:26 PDT 2020; root:xnu-6153.122.1~1/RELEASE_ARM64_T8010 iPhone9,1 arm64 D10AP Darwin

**Comment by demhademha** [comment]
How are you running frida?

**Comment by hassankhan** [comment]
I get the same when running `objection explore`, googling the error led me to this issue.

**Comment by vocaeq** [comment]
It seems like only spawning process is broken. Attaching to running process works correctly. I've got the same issue with XR (A12) on 13.5 unc0ver both 5.0 and 5.0.1 - Frida 12.9.4 
19.5.0 Darwin Kernel Version 19.5.0: Tue Apr 28 22:24:50 PDT 2020; root:xnu-6153.122.1~1/RELEASE_ARM64_T8020 iPhone11,8 arm64 N841AP Darwin

**Comment by oleavr** [comment]
We are still working on this:
https://twitter.com/fridadotre/status/1264414407804825600

**Comment by oleavr** [comment]
This is now [fixed](https://github.com/frida/frida-core/commit/3a8e80c759c23c1729ee3e0401deef3a201b5cf3) in master. The crash reporter integration was also [ported](https://github.com/frida/frida-core/commit/36d64a94392408a80c914e9c1960c23dcbdd8bb8), but I haven't yet tested that on older versions of iOS so I will hold off on releasing until I've had a chance to test it there. In the meantime please do let me know of any additional issues.

**Comment by inode-** [comment]
The issue (https://github.com/frida/frida/issues/1319) reported for the frida-gadget can be related in some way to this problem?

**Comment by inode-** [comment]
From my tests everything is working fine on the latest release.
