### ISSUE TITLE
I am getting "Command errored out with exit status 1" error while installling

### ISSUE THREAD

**Issue by evilboyajay** [frida/frida#1320]
I tried many ways to install frida in my mac but could not succeed can you please help me. Here is the error screenshot

![](https://i.imgur.com/TyOGiU6.png)

**Comment by evilboyajay** [comment]
I have used this pip command to install

pip install frida-tools

**Comment by oleavr** [comment]
Your Python installation's certificate store is empty and needs to be populated. More details here:
https://stackoverflow.com/a/43855394/7981829
