### ISSUE TITLE
which version of python is needed for npm install frida?

### ISSUE THREAD

**Issue by darkgirl** [frida/frida#1329]
![捕获](https://user-images.githubusercontent.com/28688741/83592886-f48bdd00-a58d-11ea-94b6-8217dcb68f4f.PNG)

**Comment by oleavr** [comment]
Node.js's gyp [supports](https://github.com/nodejs/node-gyp/issues/1687#issuecomment-541471076) Python 3 these days, so this means your Node.js installation is too old.

However, compiling it yourself is not necessary as we provide prebuilds for Node.js 14, 12, and 10, so would recommend installing one of those versions.
