### ISSUE TITLE
frida-ps -U, frida-ps -Uai, frida-ps -R not working as expected

### ISSUE THREAD

**Issue by samitanwer** [frida/frida#133]
Hi,

I am able to run frida-server on my rooted android device (6.0.1, arm), however, when I try to run: "**frida-ps -U**", I get only one process listed, viz the frida-server process itself and when I run: "**frida-ps -R**", I get the message - "**unable to connect to remote frida-server**"

Also running "**frida-ps -Uai open com.android.chrome**" gives an error stating "**java API not available**"

Frida version on my host is 7.1.0 and frida-server version on my phone is 7.0.11

Any solution to this, yet?

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
