### ISSUE TITLE
how to stop hook in js code

### ISSUE THREAD

**Issue by forgottor** [frida/frida#1331]
wollo  ,how can i stop a hooked  java function , for example:

var f = Java.use('java.lang.Integer');
    f.parseInt.overload('java.lang.String').implementation = function(a ) {
          return this.parseInt(a);
		 
     }

can it be  f.pareInt. stopHook?

**Comment by oleavr** [comment]
Assign `null` to `implementation` to revert back to the original implementation. Recommend extracting the method to a variable, and using that both outside and inside. E.g.:

```js
var Integer = Java.use('java.lang.Integer');

var m = Integer.parseInt.overload('java.lang.String');
m.implementation = function (a) {
  return m.call(this, a);
};

/* then later: m.implementation = null */
```
