### ISSUE TITLE
New Version Clarification

### ISSUE THREAD

**Issue by sashakiwi** [frida/frida#1335]
Could you clarify what this means / what was the impact to the resulting binary/functionality ( if anything )for me if I built the 12.9.4 version?
     "Changes in 12.9.6
      No changes except for proper Windows binaries this time. The Windows CI worker did not 
      actually build anything last time around, and released stale binaries."

Also, can you tell me exactly which V8 and Node version is embedded/used if I build 12.9.4 vs 12.9.6 or newer?

Thanks!

**Comment by oleavr** [comment]
It means 12.9.6 is the same as 12.9.5 at the source code level, but some of the released 12.9.5 binaries were not actually 12.9.5, but 12.9.4.

Node.js is not embedded in Frida. As for V8, it depends on the version of our SDK (prebuilt deps) – `git grep 2020` will tell you where the version references are. Look at build/sdk-*/lib/pkgconfig/v8*.pc to determine the version. If you want to look at the source code and our patches, there's a v8 repo under our GH organization. (Typing on my phone so I'll let you look up the exact URLs – figured a cryptic but quick reply is better than a precise but late one.)
