### ISSUE TITLE
How to properly use onReceive callback with CModule/Native code?

### ISSUE THREAD

**Issue by sherrellbc** [frida/frida#1339]
I have a CModule defined with a transform function and a onReceive callback function:

```
void transform(GumStalkerIterator *iterator,
               GumStalkerOutput *output,
               gpointer user_data)
{
    cs_insn *insn;

    while(gum_stalker_iterator_next(iterator, &insn)){
        gum_stalker_iterator_keep(iterator);
    }
}

void stalker_on_receive(void *data)
{
}
```

After attaching to a particular function:

```
const cm  = new CModule(c_src);

Interceptor.attach(ptr(0xXXXXXXXX), {
    onEnter     : onEnterHook,
    onLeave     : onLeaveHook,
    transform   : cm.transform
});
```

I want to start Stalking at the callback event:

```
function onReceiveEvent(events)
{
    console.log(Stalker.parse(events, {
        annotate    : true,
        stringify   : true
    }));
}

function onEnterHook(args)
{
    Stalker.follow({
        events : {
            block   : true
        },

        onReceive   : onReceiveEvent,
        transform   : cm.transform
    });
}

function onLeaveHook(retval)
{
    Stalker.flush();
    Stalker.unfollow();
}
```

This works well. And the use of `transform : cm.transform` causes no issues. However, if I want to use any CModule function for `onReceive` I can't get it to work. If I use the function name directly:

`onReceive : cm.stalker_on_receive
`

An error is reported stating that a function is expected:
```
        Error: expected a function
        Error: expected a function
    at Object.value [as follow] (frida/runtime/core.js:456:15)
    at InvocationContext.onEnterHook (/inject.js:206:13)
```

So if we make it into a function:
`onReceive : new NativeFunction(cm.stalker_on_receive, 'void', ['pointer'])`

We still get an error. But this time it appears to be from the call to `Stalker.flush()` in the `onLeave` callback:
```
        Error: expected a NativePointer object
        Error: expected a NativePointer object
    at NativeFunction.<anonymous> (<anonymous>)
    at InvocationContext.onLeaveHook (/inject.js:222:13)
```

It seems that when attempting to call the native function perhaps the `events` object is not being converted to a NativePointer. Given the backtrace provided it looks as if it at least attempted to call the NativeFunction.

What is the proper way to handle onReceive in native code? The documentation alludes to this working with the following statement:

> However when hooking hot functions you may use Interceptor in conjunction with CModule to implement the callbacks in C.

However it is unclear if it meant only onEnter and onLeave. Perhaps the argument list of the function needs to more fitting for the data structure passed to it by Stalker, but it is unclear what that might be. 

Is there a support method for handling these event callbacks in native code? In particular, a supported way to parsing the received data without Stalker.parse from Javascript? It appears to be so according the Stalker documentation

> onReceive: Called with `events` containing a binary blob
>   //            comprised of one or more GumEvent structs.
>   //            See `gumevent.h` for details about the
>   //            format. Use `Stalker.parse()` to examine the
>   //            data.

And just attempting to call into the native function by passing `events` directly or `ptr(events)` always just gives
```
        Error: expected a NativePointer object
        Error: expected a NativePointer object
    at value (frida/runtime/core.js:94:14)
    at trace_onReceive (/inject.js:202:12)
    at InvocationContext.onLeaveHook (/inject.js:231:13)
```

**Comment by sherrellbc** [comment]
I thought I had tried this, but apparently the override in the `events` object for printing it just shows a hexdump:

```
           0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
00000000  08 00 00 00 00 00 00 00 a4 7a 89 a0 77 00 00 00  .........z..w...
00000010  a8 7a 89 a0 77 00 00 00 01 00 00 00 00 00 00 00  .z..w...........
00000020  08 00 00 00 78 00 00 00 c0 7a 89 a0 77 00 00 00  ....x....z..w...
00000030  cc 7a 89 a0 77 00 00 00 84 72 fb 9c 75 00 00 00  .z..w....r..u...
00000040  01 00 00 00 78 00 00 00 d0 7a 89 a0 77 00 00 00  ....x....z..w...
00000050  b4 77 72 a0 77 00 00 00 00 00 00 00 75 00 00 00  .wr.w.......u...
00000060  08 00 00 00 78 00 00 00 d4 7a 89 a0 77 00 00 00  ....x....z..w...
...
```

How can I get the address of this memory so I could pass it to native code?

**Comment by oleavr** [comment]
Yeah for now the `onReceive` value has to be a JS function. Happy to accept a PR improving this in case you're interested 🙂

**Comment by thouger** [comment]
Very helpful issue，I tried it one night, but it didn't work....
