### ISSUE TITLE
Error in android emulator (Android Q x86_64) when use Java.perform

### ISSUE THREAD

**Issue by liuyufei** [frida/frida#1341]
{"type":"error","description":"Error: access violation accessing 0x53","stack":"Error: access violation accessing 0x53\n    at NativePointer.readPointer (frida/runtime/core.js:144:17)\n    at frida/node_modules/frida-java-bridge/lib/android.js:331:1\n    at o.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at Re (frida/node_modules/frida-java-bridge/lib/android.js:323:1)\n    at Object.getArtMethodSpec (frida/node_modules/frida-java-bridge/lib/android.js:1328:1)\n    at i (frida/node_modules/frida-java-bridge/lib/class-model.js:36:1)\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:109:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:56:1)\n    at frida/node_modules/frida-java-bridge/index.js:177:1","fileName":"frida/runtime/core.js","lineNumber":144,"columnNumber":17}

Android emulator environment : https://github.com/google/android-emulator-container-scripts
Emulator config : Android Q x86_64
Frida 12.9.7

**Comment by tomergi** [comment]
Did you find a solution? I'm having the same error.

**Comment by liuyufei** [comment]
@tomergi you should try latest android image of Q, I got an answer from @oleavr that "Frida don't support previews before DP4"

**Comment by EngleVV** [comment]
The same problem, using phone of Android P version solves it.
