### ISSUE TITLE
Android spawn usage will cause application crash

### ISSUE THREAD

**Issue by inode-** [frida/frida#135]
Using spawn on Android is causing me some problems that will cause the application crash. The problem seems to be caused my a sort of timing issue. An example code that cause the crash can be viewed here: [example.txt](https://github.com/frida/frida/files/206212/example.txt)

Same code with enabled this part will work:

```
for module in session.enumerate_modules():
    print module.name
```

Same problem will occur if I add a lot of hooked functions with the print modules "workaround".

Currently testing on Android 4.4.2 with Cyanogenmod 11 on Samsung Galaxy S3.

Here the crash log: [frida_crash.txt](https://github.com/frida/frida/files/206197/frida_crash.txt)

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
