### ISSUE TITLE
Android: support of spawning apps on different users

### ISSUE THREAD

**Issue by inode-** [frida/frida#1353]
Frida is currently not able to spawn an application on a specific Android user. All spawned application are launched with the default user.

```
1|ASUS_Z017D_1:/sdcard # pm list users
Users:
        UserInfo{0:Owner:13} running
        UserInfo{10:Work profile:30} running
ASUS_Z017D_1:/sdcard #
```

Same application on different user can have different data and can be managed in different ways, an option allowing the selection of the user used during the spawn process in android should resolve this problem.

Native "am start" command has an option to select the user to start the application.

inode

**Comment by sowdust** [comment]
A very rough way to overcome the lack of a user specific option is to manually modify frida-server.js and recompile with the user value hardcode. Specifically, modify lines 124-126 with the folliwing code for user with id 10:

```
var userSpecific = true;
if (!userSpecific) {
 performLaunchOperation(pkg, function () {
  context.startActivity(intent);
 });
}else{
performLaunchOperation(pkg, function () {
  var userid = 10;
  var ContextWrapper = Java.use('android.content.ContextWrapper');
  var UserHandle = Java.use('android.os.UserHandle');
  var userHandle = UserHandle.of(userid);
  context = ContextWrapper.$new(context);
  context.startActivityAsUser(intent,userHandle);
});
}
```

**Comment by oleavr** [comment]
We could easily add a spawn option for this – we already have platform-specific spawn options such as ["activity"](https://github.com/frida/frida-core/blob/7988a362c15ec4e3284c480ee72ee6eae6d9cb26/src/linux/linux-host-session.vala#L1185). PR welcome!

**Comment by inode-** [comment]
PR done.

[https://github.com/frida/frida-core/pull/327/commits/4c006d7cbba739312574ef7c3b80c496c2740d4c](https://github.com/frida/frida-core/pull/327/commits/4c006d7cbba739312574ef7c3b80c496c2740d4c)
[https://github.com/frida/frida-tools/pull/36](https://github.com/frida/frida-tools/pull/36)

**Comment by andreashappe** [comment]
i just downloaded the latest Android frida-server version and thought that I might configure the user-id through an startup-option. Alas I didn't find a fitting one.. is this currently possible with frida-server 15.1.14 or am I missing something? Thanks andreas

**Comment by oleavr** [comment]
@andreashappe You need to pass `--aux=...` to the CLI tools (or corresponding keyword arguments if you're using the Python API). Here's the `--help` description:

```
  --aux=option          set aux option when spawning, such as “uid=(int)42”
                        (supported types are: string, bool, int)
```

The available options depends on the platform, and the source code is the only documentation right now. The relevant code for our Android `uid` aux option is [here](https://github.com/frida/frida-core/blob/06349fd8020c19655278b27a4259b628ef8b20c9/src/linux/linux-host-session.vala#L1514-L1519).

So to pass it you should do `--aux='uid=(int)1234`. To specify the `activity` you'd do: `--aux='activity=(string)com.some.activity`, and same for `receiver`.
