### ISSUE TITLE
frida-ps: command not found

### ISSUE THREAD

**Issue by asad0x01** [frida/frida#1355]
I'm getting this error despite I've installed frida using pip install frida-tools .

Tested in MacOS Catalina and Ubuntu 18.04

**Comment by swarupsro** [comment]
try with `pip3 install frida-tools|

**Comment by swarupsro** [comment]
try this command `pip3 install frida-tools`

**Comment by asad0x01** [comment]
Same issue.Tried npm and still the same.

**Comment by pierreyves-lebrun** [comment]
> EDIT:The problem was within Python path.It was not set.Had to manually set the path and it's now working perfectly :)

How did you do it?

**Comment by Mirhatyasar** [comment]
It occurs because it cannot set the path correctly due to privileges

to fix this issue:
Uninstall the frida - pip uninstall frida-tools
then install it with sudo - sudo pip install frida-tools

It should be fixed now.

**Comment by prasanthbodepu** [comment]
I used pip install frida-tools and got the below error: 
<img width="1445" alt="pip install frida-tools" src="https://user-images.githubusercontent.com/82134963/176409804-ae17e016-90ca-4a0f-a27e-14b4dc96d9bf.png">

Then used "python3 setup.py install" and received the below output:
<img width="848" alt="python3 setup py install" src="https://user-images.githubusercontent.com/82134963/176409995-60785d1c-e642-429a-b4c6-845f4c1efa1c.png">

But when I use "frida --version" receiving the below output:
command not found

Please help me resolve the issue.
Thank you in advance

**Comment by jitsingh007** [comment]
Hi @prasanthbodepu, I got the same error; follow this https://github.com/frida/frida (problem: trusted code signing). Mine got resolved :)

**Comment by prasanthbodepu** [comment]
Hey @kamleshbiloniya ,
Thanks for responding, Yeah I did the similar method and It actually worked for me.
thank you : )

**Comment by IkerSolozabal** [comment]
It was a syntax error, was writting `frida-ps` instead of `Frida-ps`

Was changing letter `F` to uppercase and it worl for me

**Comment by mriamnobody** [comment]
> It occurs because it cannot set the path correctly due to privileges
> 
> to fix this issue: Uninstall the frida - pip uninstall frida-tools then install it with sudo - sudo pip install frida-tools
> 
> It should be fixed now.

Thanks @mirhatx  it works as expected now.

**Comment by ItsCEED** [comment]
Installing frida with admin run terminal did the job for me.

**Comment by BiteFoo** [comment]
> It occurs because it cannot set the path correctly due to privileges
> 
> to fix this issue: Uninstall the frida - pip uninstall frida-tools then install it with sudo - sudo pip install frida-tools
> 
> It should be fixed now.

it works for me 👍

**Comment by xbr01** [comment]
if you can't figure out the python directory or if none of the above methods work consider adding this to your path 

`export PATH="~/.local/bin:$PATH"`

**Comment by krishan-fernando** [comment]
> Uninstall Frida -> `pip3 uninstall frida-tools` install frida -> `pip3 install frida-tools` if you get following warning ` WARNING: The scripts frida, frida-apk, frida-compile, frida-create, frida-discover, frida-join, frida-kill, frida-ls, frida-ls-devices, frida-ps, frida-pull, frida-push, frida-rm and frida-trace are installed in '/Users/userame/Library/Python/3.9/bin' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.` then execute export PATH=/Users/userame/Library/Python/3.9/bin:$PATH
> 
> This worked for me.

for windows ?

**Comment by xbr01** [comment]
> > Uninstall Frida -> `pip3 uninstall frida-tools` install frida -> `pip3 install frida-tools` if you get following warning ` WARNING: The scripts frida, frida-apk, frida-compile, frida-create, frida-discover, frida-join, frida-kill, frida-ls, frida-ls-devices, frida-ps, frida-pull, frida-push, frida-rm and frida-trace are installed in '/Users/userame/Library/Python/3.9/bin' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.` then execute export PATH=/Users/userame/Library/Python/3.9/bin:$PATH
> > This worked for me.
> 
> for windows ?

for setting path in windows follow these steps

    Right-click on the Start Button
    Select “System” from the context menu.
    Click “Advanced system settings”
    Go to the “Advanced” tab
    Click “Environment Variables…”
    Click variable called “Path” and click “Edit…”
    Click “New”
    Enter the path to the folder containing the binary you want on your PATH. For example, to add MATLAB R2016b, add: C:\Program Files\MATLAB\R2016b\bin
  
  cc: [link](https://in.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows)
    
in our case add the directory in which the python binaries exist
