### ISSUE TITLE
frida_temporary_file_destroy: assertion 'self != NULL' failed

### ISSUE THREAD

**Issue by AloneMonkey** [frida/frida#136]
how to solve it？

Apr 10 15:54:12 iPad frida-server[1033] <Critical>: Frida: frida_temporary_file_destroy: assertion 'self != NULL' failed
Apr 10 15:54:12 iPad com.apple.xpc.launchd[1] (re.frida.server[1033]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
Apr 10 15:54:12 iPad com.apple.xpc.launchd[1] (re.frida.server) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 5 seconds.

**Comment by mrmacete** [comment]
for me is the same, it all started suddenly 15 minutes ago: it kicked me out while i had a REPL session running and the phone went standby, then it started refusing connection, on the phone now the persistent failure is:

```bash
Cane:~ root# frida-server 
2016-04-25 17:22:46.361 frida-server[853:4849] Frida: frida_temporary_file_destroy: assertion 'self != NULL' failed
Trace/BPT trap: 5
Cane:~ root# 
```
even rebooting doesn't help :(

both server and client are version 7.1.4

**Comment by mrmacete** [comment]
maybe "solved": apparently there were too much frida-* things inside /Library/Caches, just nuked them all and frida-server started again, is it correct?

**Comment by oleavr** [comment]
Yep if you wipe all frida-* directories in /Library/Caches, and upgrade to 7.1.9 (currently being released), frida-server will now [re-use the same temporary directory on every run](https://github.com/frida/frida-core/commit/263429685789ee0e134affe2199196858959cd1f), to prevent this kind of issues.
