### ISSUE TITLE
Frida crash

### ISSUE THREAD

**Issue by MlsDmitry** [frida/frida#1361]
Emulator details:
NoxAppPlayer
CPU: x86 armeabi-v7a
Android version: 7.1.2

Taget android application is: com.mojang.minecraftpe (Minecraft Bedrock Edition 1.11.4.2)
app has 2 native libs:

- unzipped_minecraft/lib/armeabi-v7a/libfmod.so: ELF 32-bit LSB shared object ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/, stripped

- unzipped_minecraft/lib/armeabi-v7a/libminecraftpe.so: ELF 32-bit LSB shared object ARM, EABI5 version 1 (SYSV), dynamically linked, stripped

**And frida-gadget** 

- unzipped_minecraft/lib/armeabi-v7a/libgadget.so: ELF 32-bit LSB shared object ARM, EABI5 version 1 (SYSV), dynamically linked, stripped

I'm trying to load frida-gadget 

**Log from logcat ->**
`07-01 17:58:43.113  2250  3762 I ActivityManager: Start proc 6425:com.mojang.minecraftpe/u0a61 for activity com.mojang.minecraftpe/.MainActivity
07-01 17:58:43.827  6425  6425 F Frida   : frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)
07-01 17:58:43.827  6425  6425 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 6425 (ang.minecraftpe)
07-01 17:58:43.828  1719  1719 W         : debuggerd: handling request: pid=6425 uid=10061 gid=10061 tid=6425
07-01 17:58:43.894  6446  6446 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-01 17:58:43.894  6446  6446 F DEBUG   : Build fingerprint: 'samsung/dream2qltezh/dream2qltechn:7.1/N2G48H/G9550ZHU1AQEE:user/release-keys'
07-01 17:58:43.894  6446  6446 F DEBUG   : Revision: '12'
07-01 17:58:43.894  6446  6446 F DEBUG   : ABI: 'x86'
07-01 17:58:43.894  6446  6446 F DEBUG   : pid: 6425, tid: 6425, name: ang.minecraftpe  >>> com.mojang.minecraftpe <<<
07-01 17:58:43.894  6446  6446 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-01 17:58:43.896  6446  6446 F DEBUG   : Abort message: 'frida-core/lib/gadget/gadget.vala:679:frida_gadget_detect_location: assertion failed: (our_range != null)'
07-01 17:58:43.898  6446  6446 F DEBUG   :     eax 00000000  ebx 00001919  ecx 00001919  edx 00000006
07-01 17:58:43.898  6446  6446 F DEBUG   :     esi b7743584  edi b774352c
07-01 17:58:43.898  6446  6446 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
07-01 17:58:43.898  6446  6446 F DEBUG   :     eip b769dcc0  ebp bfe09f58  esp bfe09efc  flags 00000292
07-01 17:58:43.899  6446  6446 F DEBUG   :
07-01 17:58:43.899  6446  6446 F DEBUG   : backtrace:
07-01 17:58:43.900  6446  6446 F DEBUG   :     #00 pc 00000cc0  [vdso:b769d000] (__kernel_vsyscall+16)
07-01 17:58:43.900  6446  6446 F DEBUG   :     #01 pc 0007bfcc  /system/lib/libc.so (tgkill+28)
07-01 17:58:43.900  6446  6446 F DEBUG   :     #02 pc 000777a5  /system/lib/libc.so (pthread_kill+85)
07-01 17:58:43.900  6446  6446 F DEBUG   :     #03 pc 0002821a  /system/lib/libc.so (raise+42)
07-01 17:58:43.900  6446  6446 F DEBUG   :     #04 pc 0001eed6  /system/lib/libc.so (abort+86)
07-01 17:58:43.900  6446  6446 F DEBUG   :     #05 pc 00222c1c  /system/lib/libhoudini.so
07-01 17:58:44.043  2250  6451 W ActivityManager:   Force finishing activity com.mojang.minecraftpe/.MainActivity`

Any ideas?

**Comment by oleavr** [comment]
You're loading an arm gadget using Houdini, right? If so, the issue is probably that we look at the loaded libraries and try to find ourselves in that list – but we are looking at the *native* list instead of the *emulated* list.

**Comment by MlsDmitry** [comment]
I just patched MainActivity to load my library.

**Comment by MlsDmitry** [comment]
solved
