### ISSUE TITLE
PIP install Frida - cant see after installation

### ISSUE THREAD

**Issue by animal463** [frida/frida#1362]
I have installed Frida using command "pip install frida" as mentioned in this website https://www.notsosecure.com/pentesting-android-apps-using-frida/ but later when I run this command

frida --version

it is saying command not found on windows. the installation was successfull, when i tried to install again it is saying as "requirement already satisifed" can someone help me how to overcome this issue?

**Comment by kirand777** [comment]
You should install it by this command
pip install frida-tools
(see https://frida.re/docs/installation/)
