### ISSUE TITLE
hook java.lang.equals   error

### ISSUE THREAD

**Issue by forgottor** [frida/frida#1376]
hellow, when i  hook java.lang.equals,  has error

        var a = Java.use('java.lang.String');
	a.equals.overload('java.lang.Object').implementation = function(i) { 
			var ret = this.equals(i);  
                        return ret;              
        } 

error:
{'type': 'error', 'description': 'Error: access violation accessing 0x0', 'stack
': 'Error: access violation accessing 0x0\n    at frida/runtime/core.js:144\n
 at gt (frida/node_modules/frida-java-bridge/lib/android.js:593)\n    at frida/n
ode_modules/frida-java-bridge/lib/android.js:572', 'fileName': 'frida/runtime/co
re.js', 'lineNumber': 144, 'columnNumber': 1}

**Comment by jinghaifeng1** [comment]
How did you solve it
