### ISSUE TITLE
iPhone SE2: Calling NativeFunction crashes with access violation prepended with 0x2000000

### ISSUE THREAD

**Issue by jiska2342** [frida/frida#1381]
Hi,

I'm using an extension of [frizzer](https://github.com/demantz/frizzer) to fuzz `bluetoothd`. It's using the stalker to get coverage while calling target functions within `bluetoothd`. It's been working well throughout the last months on a couple of *iPhone 7* with various Frida versions and on iOS 13.3-13.5. Currently having iOS 13.3.1, Frida 12.10.4, checkra1n and it's going well :) We're going to release that fuzzer soon ;)

However, when I use the fuzzer on an *iPhone SE2, unc0ver 5.0.1, iOS 13.5* it doesn't work. The error message I get is:

```
frida.core.RPCException: Error: access violation accessing 0x200000010276babc
    at NativeFunction.<anonymous> (<anonymous>)
    at functionCalledForFuzzing (bluetoothd.js:94:18)
    at Object.setupSomethingForFuzzing (bluetoothd.js:236:18)
    at SomeFuzzer.prePrepare (../projects/fuzzcase/fuzzthis.js:21:34)
    at SomeFuzzer.prepare (fuzzer.js:66:14)
    at Object.prepare (fuzzer.js:121:39)
    at frida/runtime/message-dispatcher.js:13:1
    at c (frida/runtime/message-dispatcher.js:23:1)
```

The code executed looks like this:
```
var base = Module.getBaseAddress("bluetoothd");
// ...

function functionCalledForFuzzing(arg1, arg2) {
    var fn_addr = base.add(0x123abc);
    var _functionCalledForFuzzing = new NativeFunction(fn_addr, "pointer", ["pointer", "char"]);
    _functionCalledForFuzzing(arg1, arg2);
    //...
};
```

The `abc` part in the address is similar, the remaining difference should be a result of ASLR. Not sure about the leading `0x2000000` in the error message, though? When I print the base address (`bluetoothd` restarted, other address than previous example) I get `0x102274000`, which looks all right, but the access violation still is prepended with the `0x2000000`.

```frida-trace``` works well nonetheless:

```
# frida-trace -U -i "objc_msgSend" bluetoothd
Instrumenting...   
Started tracing 1 function. Press Ctrl+C to stop.                       
           /* TID 0x13a9f */
   111 ms  objc_msgSend()
   111 ms  objc_msgSend()
   111 ms     | objc_msgSend()
   111 ms     |    | objc_msgSend()
   112 ms  objc_msgSend()
   112 ms     | objc_msgSend()
   112 ms     | objc_msgSend()
   112 ms  objc_msgSend()
```

Any idea where the crash comes from?
I also tried calling other functions and always get an access violation but only on the iPhone SE2 (with adapted symbols within `bluetoothd`), the iPhone 7 works fine.

Best,
Jiska

**Comment by oleavr** [comment]
Hey,

Cool! The issue is that you need to pass a signed pointer to `NativeFunction`. It should only be a matter of changing:

```js
    var _functionCalledForFuzzing = new NativeFunction(fn_addr, "pointer", ["pointer", "char"]);
```

to:

```js
    var _functionCalledForFuzzing = new NativeFunction(fn_addr.sign(), "pointer", ["pointer", "char"]);
```

Cheers!

**Comment by oleavr** [comment]
(This will be a noop on non-arm64e architectures and processes.)

**Comment by jiska2342** [comment]
Thanks for the fast response :)
It's working now on the iPhone SE2 :unicorn:

**Comment by stokatyan** [comment]
I've got a similar issue, but `.sign()` doesn't appear to be the solution for me.  Any idea why I get this error:
```
Running Chess Loop ...

Byte Array at ptr:
           0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
00000000  ff 83 03 d1                                      ....

Calling NativeFunction at ptr ...
Error: access violation accessing 0x3
    at <eval> (/ChessLoop.js:40)
```

With this code:
```javascript
console.log("Running Chess Loop ...");

let baseAddress = Module.getBaseAddress("Chess"); // Base Address, used to calculate ASLR Slide
let rootAddress = "0x100000000" // Address that the Base Address is relative to
let aslrSlide = subtractHex(baseAddress, rootAddress);

var functionAddress = '0x1002548a4'; // Address before ASLR Slide
functionAddress = addHex(functionAddress, aslrSlide); // Address after ASLR Slide
var functionPtr = ptr(functionAddress);

console.log('\nByte Array at ptr:');
console.log(functionPtr.readByteArray(4)); // Confirms that the binary at the address is correct

// -[CHRatedPuzzleViewController exitButtonTapped]:
var _function = new NativeFunction(functionPtr.sign(), 'void', []);
console.log('\nCalling NativeFunction at functionPtr.sign() ...')

_function(); // Error: access violation accessing 0x3
```

**Comment by jiska2342** [comment]
On an iPhone 7, there's no PAC, so you're likely having the issue due to something else.

**Comment by stokatyan** [comment]
I see, so your issue was only on the SE — is that correct?

In any case,  it seems like we have similar scripts.  Any thoughts why I’m running into this error?  Also, what is PAC?

**Comment by ChiChou** [comment]
@stokatyan 

Your question is totally not related to this thread.

iPhone 7 has no PAC, so you don't need to call `.sign`. Anyway, calling `.sign` on an unsupported device will do nothing.

The reason your code crashed is null pointer dereference. It could be various reasons, but the most obvious one is that there is no SELF pointer applied.

First, don't call ObjC methods like this. Otherwise you will need to manually apply both SELF pointer and selector pointer.

You need to first get the instance of `CHRatedPuzzleViewController` (for example, `ObjC.chooseSync(CHRatedPuzzleViewController)` to enumerate all existing instances)

Then, use the frida way to invoke the ObjC methods.

From the name of the method I guess it's part of UI logic. All UI operations are supposed to be executed by the main thread, so you need to call the method in `ObjC.mainQueue`.

Example code like this, I can't guarantee if it's working

```js
ObjC.schedule(() => {
    controller = ObjC.chooseSync(ObjC.classes.CHRatedPuzzleViewController).pop(); // search all instances and get the first
    controller.exitButtonTapped(); // trigger method
)
```

**Comment by stokatyan** [comment]
@ChiChou Thank you for helping with this.  I learned a lot from your reply.
