### ISSUE TITLE
PID or name must be specified

### ISSUE THREAD

**Issue by yunhaipiaodi** [frida/frida#1382]
when i run frida-server notice "PID or name must be specified",what wrong happend?

**Comment by 0xXA** [comment]
> when i run frida-server notice "PID or name must be specified",what wrong happend?
maybe if u can tell me where u ran it so i can help u with dat
frida-server by default opens port 27042 and listens on current device for all the communications and it should have no problem even when u don't specify a PID
post logcat

**Comment by oleavr** [comment]
@yunhaipiaodi That means you've deployed the `frida-inject` binary instead of `frida-server`.

**Comment by rootsparrow** [comment]
> @yunhaipiaodi That means you've deployed the `frida-inject` binary instead of `frida-server`. (It's easy to get them mixed up!)

exactly,,, !
 thank for that!

**Comment by sappi13** [comment]
> @yunhaipiaodi That means you've deployed the `frida-inject` binary instead of `frida-server`. (It's easy to get them mixed up!)

I was also doing the same mistake.
