### ISSUE TITLE
Error 404 when installing (12.10.4) from cydia

### ISSUE THREAD

**Issue by kshipeng** [frida/frida#1388]
Error 404 when installing (12.10.4) from cydia.
This is still the case after refreshing the software source

**Comment by sritarun3** [comment]
even i had the same issue

**Comment by d1pakda5** [comment]
same here

**Comment by d1pakda5** [comment]
@oleavr kindly look into this

**Comment by eaneatfruit** [comment]
Same here, experiencing the same issues even after refreshing software source, re jailbreak, and restarting springboard.

**Comment by oleavr** [comment]
Sorry about this, I tightened up the permissions of the S3 bucket but forgot to update the release script, which resulted in the 12.11.0 release automation nuking the existing version and failing to upload the new one. Fixed the script and completed the deployment earlier today. Cheers!
