### ISSUE TITLE
Trying to read libil2cpp method from Unity Game, getting weird parameter results

### ISSUE THREAD

**Issue by Syrou** [frida/frida#1392]
I'm currently trying to read the contents of 3 parameters in a method which dnSpy has reformatted to look like this:
`public int PrintBuffer(string tag, byte[] buffer, int size) { return default(int); }`

Example setup:
```
var libil2cpp = Module.findBaseAddress("libil2cpp.so");
var printTextLocation= libil2cpp.add(0xABABAD);
Interceptor.attach(printTextLocation, {
    onEnter: function(args) {},
    onLeave: function(args) {}
});
```
My Frida code runs onEnter and onLeave just fine. But when I'm trying to read the contents of args things become weird.
```
onEnter: function(args) {
        console.log(getCurrentDateString() + "\n");
        var tag= args[0];
        var buf = args[1];
        var length = args[2];
        
        console.log("TAG: ", tag.readUtf8String(-1)); <- Gives me garbage
        console.log("buf: ", hexdump(buf)); <- Is plausibe, but has weird start of bytes
        console.log("TAG: ", length toInt32()); <- Gives me a waaay to high number for the incoming buffer
}
```
I'm certain the memory location is correct, because by printing the instructions, it matches what shows up in IDA.
I'm guessing the reason why I'm having issues, is because of dnSpy giving me the C# version of the code.
So what I'm actually reading here is C#.Net classes or some Il2CPP wrappers rather than C/C++. Has anyone any any idea on how to work around it?

**Comment by glootjofo** [comment]
For now this is partly resolved. Solution might be published later.

**Comment by Syrou** [comment]
For now, this is partly resolved. Solution pending to be released. Safe to say, yes, everything needs to be parsed/wrapped with il2cpp

**Comment by shellcong** [comment]
Would you share your solution here? I have a similar problem.

**Comment by Syrou** [comment]
When I made this there was no public solutions. There are several now, amongst others the very popular: https://github.com/vfsfitvnm/frida-il2cpp-bridge
