### ISSUE TITLE
.apply on Java .overload does not work

### ISSUE THREAD

**Issue by adam-flynn** [frida/frida#1399]
I wrote a more generic Java function hooking which takes an array of types as a parameter. It uses something similar to the following:

    Java.perform ( function() { var jclass = Java.use("my.class"); var jfunc = jclass.abc; var jimpl = jfunc.overload.apply(jfunc.overload, types_array); } );

In more recent versions of Frida, this piece of code does not work anymore:

    TypeError: cannot read property 'length' of undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:59225)
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:907
    at [anon] (input:1)
    at frida/node_modules/frida-java-bridge/lib/vm.js:11
    at frida/node_modules/frida-java-bridge/index.js:358
    at eval (input:1)
    at eval (native)
    at /repl.js:9
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)

I think it is this commit: https://github.com/frida/frida-java-bridge/commit/116df10f308d01a0d009730592c716b2ac074b7d

I currently work around it by using ``eval()``, but it is really ugly.

**Comment by oleavr** [comment]
This only worked by luck in the past. When you do:

```
jfunc.overload(x, y, z)
```

Then `this` will be bound to `jfunc`.

So when you do:

```js
var jimpl = jfunc.overload.apply(jfunc.overload, types_array); } );
```

You're actually binding it to `jfunc.overload` instead of `jfunc`.

So instead you want to do:

```js
var jimpl = jfunc.overload.apply(jfunc, types_array); } );
```

**Comment by adam-flynn** [comment]
Oh, I'm so sorry for my stupidity. I thought I tried it with jfunc as well, but I just tried it and it works.
