### ISSUE TITLE
Android L

### ISSUE THREAD

**Issue by mszawlow** [frida/frida#14]
Frida usage on Nexus 5 with android 5.0.1 fails with:
error: only position independent executables (PIE) are supported.

while spinning up frida server

**Comment by oleavr** [comment]
Thanks! This sounds like a build issue, hopefully only a matter of adding `-pie` to the Android `LDFLAGS`in `releng/setup-env.sh`. Let me know if you need any help building Frida yourself to try this out. (If not I'll leave this issue open and I can have a closer look at this before the next release.)

**Comment by mszawlow** [comment]
It certainly is a build issue - I'm not sure if LD_FLAGS fixed it because I added it also to CFLAGS ;)

I have another issue now: frida-trace is now stuck on Failed to attach: Timeout was reached .
I've used strace on frida-server and the last part seems like this:

```
ptrace(PTRACE_ATTACH, 2915, 0, 0)       = 0
wait4(2915, [{WIFSTOPPED(s) && WSTOPSIG(s) == SIGSTOP}], 0, NULL) = 2915
openat(AT_FDCWD, "/proc/2915/maps", O_RDONLY) = 11
fstat64(11, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mprotect(0xb6471000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0xb6471000, 4096, PROT_READ)   = 0
read(11, "b6b00000-b6d00000 rw-p 00000000 "..., 1024) = 1024
futex(0xbea5ca24, FUTEX_WAIT_PRIVATE, 2, NULL
```

I'm trying to figure out why the server hangs - I could send a patch if I find the bug but I'd need some directions...

**Comment by oleavr** [comment]
Ah cool :)

Hmm.. you did `adb forward` all necessary ports on the host, right? (27042 for communicating with frida-server, 27042+n for each session – but beware there's not yet any recycling of ports so n will increase for each attempt)

Another potential issue to look out for is knox:
Perhaps you're running into the knox issue:

```irc
20:31 <acicula> im toying with frida on an S4 with 4.4.2, but it crashes the app everytime i attached to it. I am just following the introductionary tutorial .
20:32 <acicula> i am running into some trouble with knox it seems
20:32 <acicula> E/knox    (19018): type=1400 msg=audit(1421843126.899:531): avc:  denied  { write } for  pid=29995 comm=".an
20:32 <acicula> droid.chrome" name="linjector-29081" dev="mmcblk0p29" ino=259800 scontext=u:r:untrusted_app:s0 tcontext=u:ob
20:32 <acicula> ject_r:shell_data_file:s0 tclass=fifo_file VE=SEPF_GT-I9515_4.4.2_0011
20:32 <acicula> and that kills the process dead
20:54 <acicula> fixed it :)
20:54 <acicula> setenforce 0 and now its is set to permissive
```

**Comment by mszawlow** [comment]
Well I thought about SELinux but it doesn't solve the problem. I'll play with it some more - maybe some printf debugging will help ;)

It just seems like the server is freezing for some reason and the client is getting timeout after a while

**Comment by oleavr** [comment]
Good plan :) Spraying `frida-core/src/linux/linjector-glue.c` with `printf` calls and `frida-core/src/linux/linux-host-session.vala` with `stderr.printf ("Foo %d", bar);` style calls should make things a bit clearer. Note that once `frida-server` has injected the `.so` into the target process it will communicate the port number back to the host, which will then TCP connect directly to this port number on the device, where the `frida-agent.so` is listening inside the target process. (`frida-server` is not a middle-man in the host<->target process communications.)

**Comment by oleavr** [comment]
Any luck?

**Comment by mszawlow** [comment]
no free time yet :( I will try to find some this week

2015-01-31 13:14 GMT+01:00 Ole André Vadla Ravnås <notifications@github.com>
:

**Comment by mszawlow** [comment]
Ok I've found the issue: it hangs on sscanf while trying to parse /proc/<pid>/maps.
This is probably caused by: http://stackoverflow.com/questions/27847322/hang-in-sscanf-with-app-stl-c-shared-when-running-on-android-5-0-lollipop. I'll try to fix it somehow

**Comment by oleavr** [comment]
Great catch! The reason is lack of time. In theory it's just a matter of rebuilding Frida's SDK with the latest NDK. (Frida's SDK contains prebuilt dependencies, and unfortunately the latest NDK isn't ABI compatible with r9d.)

**Comment by mszawlow** [comment]
You can either rebuild the Frida SDK with newer ndk (I'd do that but I'm pretty lost in the build system...) or apply patch to ndk-r9d like suggested on https://android.googlesource.com/platform/ndk.git/+/47e68e84ee043436387a053c1cd47b97cabbb8ca

to rebuild libc++  you have to use in ndk root:
build/tools/build-cxx-stl.sh --stl=libc++ --verbose

Unfortunately for me it failed because it couldn't find some directory ... linux-x86/ ...
I have x86_64 so I had to fix one file to make it work: build/tools/prebuild-common.sh lines ~1133,
change RET=linux-x86 to RET=linux-x86_64

        linux-x86_64)
            if [ "$TRY64" = "no" ]; then
 1133:               RET=linux-x86_64
            fi


then rebuild frida and it seems to be working now without any hangs :)

**Comment by oleavr** [comment]
Aha, very interesting! Awesome work, thanks for digging :) I'll have a look at upgrading the SDK; hopefully the `Makefile.sdk.mk` steps should work with the latest SDK – fingers crossed :)

**Comment by ignoramous** [comment]
Is the fix available in the latest release/source code?

**Comment by oleavr** [comment]
@ignoramous It's fixed in latest git. We will release 1.6.9 containing this fix later this weekend if all goes to plan.
