### ISSUE TITLE
Android frida-trace -i "*function*" does not generate correct handler names any longer

### ISSUE THREAD

**Issue by adam-flynn** [frida/frida#1413]
I'm having a curious problem with frida-trace (version 12.10.4) where say I run:

    frida-trace -U -i "Java_*" <some_application>

It generates single letter handler names, e.g.

    a: Auto-generated handler at "/home/<user>/__handlers__/libopenjdk.so/J.js"

And indeed the trace has only single letter handler outputs:

            /* TID 0x334f */
    954 ms  J()
    959 ms  J()
    960 ms  J()

Any idea why this is happening?

**Comment by adam-flynn** [comment]
I just verified that an old version 12.8.6 works and the latest version 12.11.6 does not work. So quite likely a regression, and a major one to me.

**Comment by oleavr** [comment]
Yep turns out we broke Python 2 support, and it went unnoticed because pretty much all testing happens on 3 😅 Fix coming.

**Comment by oleavr** [comment]
Fixed in latest frida-tools (8.1.3). Thanks for reporting!
