### ISSUE TITLE
Simple use case.

### ISSUE THREAD

**Issue by MariasStory** [frida/frida#142]
Hi,

I am trying to use frida for malware analyze.
1) Can I get a complete traceback of a file with functions called, hopefully parameters recognized (strings, not just pointers)?
2) Than I would like to limit the functions to the interesting ones.
3) After this I would like to modify behavior (parameters) of some functions.

Can someone give me step by step instructions to get such use case working?

PS: Off course, it would be nice to have such solution for multiple platforms.

Greetings,
Tolik

**Comment by oleavr** [comment]
Hi,

All of this is possible, but Frida just gives you the building blocks. Check the web-site to learn how to use the APIs, and from there you can build all of that very easily.

Cheers!
