### ISSUE TITLE
Issue with variable

### ISSUE THREAD

**Issue by chrrox** [frida/frida#1420]
How would i over write this boolean.
<img src="https://i.snipboard.io/xcM8KQ.jpg"/>

I get this error

Error: c(): has more than one overload, use .overload(<signature>) to choose from:
        .overload()
        .overload('android.content.Context')
    at ge (frida/node_modules/frida-java-bridge/lib/class-factory.js:584)
    at me (frida/node_modules/frida-java-bridge/lib/class-factory.js:573)
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:953
    at [anon] (input:8)
    at frida/node_modules/frida-java-bridge/lib/vm.js:11
    at frida/node_modules/frida-java-bridge/index.js:446
    at frida/node_modules/frida-java-bridge/index.js:429
    at je (frida/node_modules/frida-java-bridge/lib/class-factory.js:633)
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:616

**Comment by kevinspider** [comment]
var className = Java.use("xxx.xxx");
className.c.overload().implementation = function (){}
className.c.overload('android.content.Context').implementation = function (){}
