### ISSUE TITLE
Is it possible to have syntax highlight for frida variables like "Java.use(...)"

### ISSUE THREAD

**Issue by bigdogs** [frida/frida#1427]
My ide (VSCode/Webstorm) does not recognize frida vairables (like, "Java.use") , so the code completion is not work when I'm writing frida js code on Mac.
It there a possible to make it work?

**Comment by oleavr** [comment]
https://github.com/oleavr/frida-agent-example

Here's what it looks like:
https://www.youtube.com/watch?v=9cr4gOPFN4o
