### ISSUE TITLE
Cyanogenmod: Java API not available

### ISSUE THREAD

**Issue by vakexuta** [frida/frida#144]
I am running frida server (7.1.4) in a Xperia Z3C with CM 12.1 (Android 5.1.1), and when trying to hook Dalvik functions, it shows this error:

`Error: Java API not available
    at assertJavaApiIsAvailable (gumjs-java.js:138:23)
    at Runtime.perform (gumjs-java.js:257:13)
    at script1.js:6:8
`

The same code works for standard Android devices.
The rest is okay, it is capable of hooking native functions.

Do not know if it is an issue for you or if I shall make some changes from my side for this getting working.

**Comment by jamesst20** [comment]
Issue confirmed with my OnePlus X running CM13 Marshmallow.

```
frida-ps -Uai open com.android.chrome
Waiting for USB device to appear...
Failed to enumerate applications: java API not available
```

**Comment by mirkobrandner** [comment]
I am running latest Frida and Android 6.0.1. Intention is to hook Java functions. No matter what I try (node.js or python) I get Java API not available errors. I have installed the Xposed framework on the Nexus 7 2013 device and wonder if this makes a difference for Frida. Maybe this is a hint.

**Comment by oleavr** [comment]
Frida is not currently compatible with Xposed. Please keep an eye on [frida-java](https://github.com/frida/frida-java) to know when this improves.

**Comment by jamesst20** [comment]
@oleavr

I dont think this issue has anything to do with Xposed. Must be confirmed.

**Comment by vakexuta** [comment]
@oleavr nothing about Xposed as @jamesst20 states. This issue started with Cyanogenmod only. Can you confirm?

**Comment by oleavr** [comment]
@jamesst20 Oops, sorry, you are absolutely right. We should hopefully be compatible with Cyanogenmod now though. (Please open an issue in frida-java if not.)
