### ISSUE TITLE
Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually

### ISSUE THREAD

**Issue by akashkatare** [frida/frida#1447]
I am using  Iphone 6 with iOS 12.4.8 , Frida version ==  latest 12.11.14
Install frida in linux working properly 

when i run frida-ps -U  get below error
Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually

Tried all present ways like frida-server -l "deviceip":9999
Tried to start server manually then i got error like 
My device is jailbroken using Checkra1n

Please help out thanx in advance

**Comment by thevillagehacker** [comment]
# Frida Solution
you can use **`Frida for Pre-A12`** package to resolve this issue

Thanks 
Naveen

**Comment by spookey0188** [comment]
> # Frida Solution
> you can use **`Frida for Pre-A12`** package to resolve this issue
> 
> Thanks
> Naveen

Doesn't exist anymore

**Comment by oleavr** [comment]
@spookey0188
> Doesn't exist anymore

We've finally unified them – the package is now named just “Frida”.
