### ISSUE TITLE
unable to intercept function on iPhone5, iOS8.2

### ISSUE THREAD

**Issue by nevermoe** [frida/frida#145]
Hi, I tried to hook a function but frida gives me this information. I am sure that there is a function at address 0x11fdbc using dynamic debugging.

{u'columnNumber': 25, u'description': u'Error: unable to intercept function at 0x11fdbc; please file a bug', u'fileName': u'gumjs-core.js', u'lineNumber': 535, u'type': u'error', u'stack': u'Error: unable to intercept function at 0x11fdbc; please file a bug\n    at Object.defineProperty.value [as replace] (gumjs-core.js:535:25)\n    at script1.js:20:13'}

The following is part of my code:

var baseAddr = Module.findBaseAddress('MyApp_inhouse') - 0x4000;
var origFuncOffset = 0x42DBC;
var origFuncRVA = baseAddr + origFuncOffset;
 

var origFuncPtr = ptr(hexString(origFuncRVA));
var origFunc = new NativeFunction(origFuncPtr, 'pointer', ['pointer', 'pointer'])
 
Interceptor.replace(origFuncPtr, new NativeCallback(function (pBuf, pKey){
    //....

I tried this code on a iPhone6s, iOS 9.0.2 and it works fine (of course the calculation of base address and function address is modified for 64 bit address, the other code remains the same).

Maybe it is a bug? Because if I mistake the funciton return type or parameters type, the application will just crash or shows some other information.

**Comment by oleavr** [comment]
Hi,

> var baseAddr = Module.findBaseAddress('MyApp_inhouse') - 0x4000;

This is not a good idea, you should use `.sub(0x4000)` to stay in the NativePointer domain to avoid losing bits. (JavaScript Number values cannot represent all 64-bit pointers.)

> var origFuncRVA = baseAddr + origFuncOffset;

Same here. Use `baseAddr.add(origFuncOffset)`.

Btw, if the function is Thumb then you need to make sure that the LSB is set, e.g. `.or(1)`. Could this be the issue?

**Comment by nevermoe** [comment]
Sorry, it doesn't work. I noticed that the function I'd like to hook might be an operator overload. In dynamic debugging, there is comment like 

`LineRangers_inhouse`Json::Value::operator[]:
    0xbadbc <+0>:  push   {r7, lr}
    0xbadbe <+2>:  mov    r7, sp
`

Can operator overload been hooked?

**Comment by oleavr** [comment]
Yes that definitely can be hooked. I noticed that it's Thumb, so you'll have to set the lower bit when passing the address to Interceptor, i.e. 0xbadbd – `ptr('0xbadbc').or(1)`.

**Comment by nevermoe** [comment]
Perfectly solved my problem. Thank you!

**Comment by oleavr** [comment]
Glad to hear!
