### ISSUE TITLE
Unable to find base address or exported function of dynamically loaded library

### ISSUE THREAD

**Issue by Caydenz** [frida/frida#1454]
I'm able to detect when the library is loaded using System.loadLibrary, but Module.findBaseAddress returns null and Module.enumerateExports doesn't return anything.

Here's my code:

    function processJniOnLoad(libraryName) {
        const funcSym = "giface";
    	const funcPtr = Module.findExportByName(libraryName, funcSym);
    
        const membase = Module.findBaseAddress(libraryName);
    	console.log("Address name is " + membase);
    	
        console.log("[+] Hooking " + funcSym + "() @ " + funcPtr + "...");
    
        Module.enumerateExports(libraryName, { onMatch: function(e) { console.log("type " + e.type + " name of function = " + e.name + " " + e.address); }, onComplete: function() { } });
    }
    
    function waitForLibLoading(libraryName) {
        var isLibLoaded = false;
    
        Interceptor.attach(Module.findExportByName(null, "android_dlopen_ext"), {
            onEnter: function (args) {
                var libraryPath = Memory.readCString(args[0]);
                if (libraryPath.includes(libraryName)) {
                    console.log("[+] Loading library " + libraryPath + "...");
                    isLibLoaded = true;
                }
            },
            onLeave: function (args) {
                if (isLibLoaded) {
                    processJniOnLoad(libraryName);
                    isLibLoaded = false;
                }
            }
        });
    }
    
    waitForLibLoading("orastream.so");

Output example:

    C:\just_a_path>python peton3.py
    [+] Loading library /data/app/com.app_name.app-<random string>==/base.apk!/lib/arm64-v8a/library_name.so...
    Base address is null
    [+] Hooking JNI_OnLoad() @ null...

Looking at the Exports tab in IDA, I can see that JNI_OnLoad is exported. Is this a bug or I'm doing something wrong?

**Comment by baseoursteps** [comment]
Can confirm the same behavior on rooted Android 6.0 using frida-server 12.11.16 when I try to hook native methods from stripped libraries both by symbol and by address.

**Comment by oleavr** [comment]
Would suggest taking a look at [frida-onload](https://github.com/iGio90/frida-onload).

On a more general note:

> var isLibLoaded = false;

This is a really bad idea as multiple threads may be calling `android_dlopen_ext()` in the same time window. Instead, use `this.isLibLoaded = true;` and in `onLeave` access `this.isLibLoaded`.

> Module.enumerateExports(libraryName, { onMatch:

This is deprecated API. Use `Module.enumerateExports(libraryName)`, which returns an array of exports. (Which you can iterate using e.g. `.forEach()`.)
