### ISSUE TITLE
Problem server on android 4.2

### ISSUE THREAD

**Issue by maxben14** [frida/frida#1458]
root@android:/sdcard/Download # ./frida-server-12.11.12
soinfo_relocate(linker.cpp:980): cannot locate symbol "getauxval" referenced by "./frida-server-12.11.12"...CANNOT LINK
EXECUTABLE

I use genimotion android 4.2 and have problem with server frida. How on 4.2 frida use ?

**Comment by oleavr** [comment]
We only support Android 4.3 and newer, though 8+ is highly recommended these days.

**Comment by maxben14** [comment]
Are there any alternative solutions for 4.2 debugging using function hooks?

**Comment by maxben14** [comment]
Also i have problem with frida on 4.4. Option -f don't work and i can't start my app with frida script. I use frida 12.11.12.

**Comment by oleavr** [comment]
> Are there any alternative solutions for 4.2 debugging using function hooks?

You can build Frida yourself, including the SDK, lowering the API level used. But I wouldn't recommend this.

> Also i have problem with frida on 4.4. Option -f don't work and i can't start my app with frida script. 

Upgrade to ART. Early instrumentation (`spawn()`) isn't supported on Dalvik systems for now, only ART.

**Comment by maxben14** [comment]
> You can build Frida yourself, including the SDK, lowering the API level used.

Interesting idea. Can you tell in which file me need to fix the api before assembly? I want to build a frida server for android-x86 on Linux, I understand correctly that this is the easiest way just do make in linux ?

I am researching an application that developers were making for 4.4 android, I lowered to 4.2. The app starts and runs on 4.2, but not quite as it does on 4.4. Identifying bugs in the application. I wanted to use frida to get a log of calls of methods important for me on both machines and compare them. Find where the error is. Therefore, I want to frida use at 4.2. Debugging in ida pro is very long, frida is more convenient and faster for work.
