### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by pitust** [frida/frida#1464]
10-03 12:15:22.275  4441  4441 F DEBUG   : Abort message: 'Error: Java API only partially available; please file a bug. Missing: _ZN3art3Dbg9StartJdwpEv, _ZN3art3Dbg8GoActiveEv, _ZN3art3Dbg21RequestDeoptimizationERKNS_21DeoptimizationRequestE, _ZN3art3Dbg20ManageDeoptimizationEv, _ZN3art3Dbg9gRegistryE'
Is this just old frida issue? I don't really know.

**Comment by oleavr** [comment]
Yes, fixed in the latest.
