### ISSUE TITLE
Frida can't find exported native function

### ISSUE THREAD

**Issue by Fi5t** [frida/frida#1465]
Hello folks! I'm trying to hook a native function in my android app with the Frida, but I can't. Frida shows me this error:
```
Error: libnative-lib.so: unable to find export 'Java_com_example_fridabug_MainActivity_stringFromJNI'
    at frida/runtime/core.js:232
    at /hook.js:1
```

I use this command to run Frida:
```
frida -U -l hooks/hook.js -f com.example.fridabug --no-pause
```

My `hook.js`
```javascript
Interceptor.attach(Module.getExportByName("libnative-lib.so", "Java_com_example_fridabug_MainActivity_stringFromJNI"), {
    onEnter: function () {
        console.log("onEnter ")
    },
    onLeave: function (retval) {
        console.log("onLeave");
    }
});

```

Here is a project to reproduce this bug(?): https://github.com/Fi5t/frida-native-hook-bug

**Frida version:** 12.11.17
**Android version:** 6.0.1

**Comment by oleavr** [comment]
What happens is that your code runs early in the process lifetime, before the library has been loaded. See [frida-onload](https://github.com/iGio90/frida-onload) for one possible solution.

**Comment by bartlomiejduda** [comment]
Here is my solution:
https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/Cocos2d/cocos2d_xxtea_script.js

**Comment by milahu** [comment]
see also [frida hook native non exported functions](https://stackoverflow.com/questions/68332781/frida-hook-native-non-exported-functions)

> I assume you are using frida's method `Module.findExportByName`. This way only works for exported functions. The method visible in the Ghidra screen-shot you have posted however seems to be an internal function that do not even have a name.

<blockquote>

You should be able to hook an unnamed function directly by using it's address and the base address of the module it is implemented in.

You just have to insert the correct `moduleName` in the following code:

```js
const ghidraImageBase = 0x00040000; // example value get the real value in Ghidra from Window -> Memory map -> Set Image Base
const moduleName = "insert module name here";
const moduleBaseAddress = Module.findBaseAddress(moduleName);
const functionRealAddress = moduleBaseAddress.add(0x002d5044 - ghidraImageBase);
Interceptor.attach(functionRealAddress, {
                   onEnter: function(args) {
                       ...
                   }
});
```

</blockquote>

**Comment by bartlomiejduda** [comment]
> You should be able to hook an unnamed function directly by using it's address and the base address of the module it is implemented in.

@milahu I did that in another script
https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/ObsCure%202/frida_hook/obscure2_frida_hook.js
Probably forgot to post it here or I didn't see the point, because first one already answered question.

**Comment by milahu** [comment]
aah. i failed to see that i can pass the executable name as `module_name`

```js
var module_name = 'Obscure2.exe';
//var base_address = Module.findBaseAddress(module_name);
var base_address = Module.getBaseAddress(module_name); // throws on error
const hash_function_address = base_address.add(0x194510);
```

in theory, the base address should also be in [Process.mainModule.base](https://frida.re/docs/javascript-api/#process)
but in my case, `Process.mainModule == undefined`
