### ISSUE TITLE
Question regarding Java.use("java.util.TreeMap").$new();

### ISSUE THREAD

**Issue by B4RD4k** [frida/frida#1466]
Hi,

I have a  question regarding Java.use("java.util.TreeMap").$new();, i want to pass it "CASE_INSENSITIVE_ORDER" as part of the initiation.

How should I pass it? I tried a lot of things.

10x

**Comment by oleavr** [comment]
Something like this:

```js
var String = Java.use('java.lang.String');
var TreeMap = Java.use('java.util.TreeMap');

var map = TreeMap.$new(String.CASE_INSENSITIVE_ORDER.value);
```
