### ISSUE TITLE
Building CLI executables from source on Windows

### ISSUE THREAD

**Issue by jamesggre** [frida/frida#1468]
I've followed the build guides and built frida's CLI tools (frida, frida-trace, etc) on linux.

With some modifications (python include and lib paths) I've also followed the Windows build guide at https://frida.re/docs/building/ and built frida.sln on Windows - all projects get built successfully.

But the standalone CLI tools (frida.exe, frida-trace.exe, etc) don't seem to get built. What am I missing here? Are there additional steps to take after builing all the projects in frida.sln ?

**Comment by oleavr** [comment]
These are generated by pip at package installation time. You should be able to get it to generate them for you by running `setup.py` and asking it to install the package.

**Comment by jamesggre** [comment]
Thanks, worked for me!

In case anyone finds this useful: you seem to need to 'setup.py install' frida-python first, then do 'npm install' in frida-tools/agents/tracer, then 'setup.py install' in python-tools. This will create the executables in your python Scripts folder.

Would be nice to have a way to create standalone versions of them (as they seem to work on linux, alhtough I may be wrong, and there are still some dependencies to the python installation under linux too), these only work as part of the python installation, you can't move them. But this is enough for me, for now.
