### ISSUE TITLE
Frida causing crash when native hooking

### ISSUE THREAD

**Issue by natashenka** [frida/frida#1469]
The following script, hooking Facebook Messenger is causing the application to crash:

```
import frida
import sys

def on_message(message, data):
	print message

package_name = "com.facebook.orca"

jscode = """

var json = Module.findExportByName ( "librtcR20.so", "_ZN5folly9parseJsonENS_5RangeIPKcEE");
console.log(json);

Interceptor.attach (json, {

	onEnter : function(args){
		
		console.log("here");
		
	
	}
	
});

"""
devices = frida.enumerate_devices()
device = 0

if len(sys.argv) < 2:
	for item in devices:
		print(item.name)
	exit()	

for item in devices:
	print(item.name)
	if sys.argv[1] == item.name:
		device = item

process = device.attach(package_name)
script = process.create_script(jscode)
script.on('message', on_message)
print('[*] Running CTF')
script.load()
sys.stdin.read()
```

The crash is:

10-09 17:34:00.243  8404 11119 E AndroidRuntime: FATAL EXCEPTION: rtc_platform
10-09 17:34:00.243  8404 11119 E AndroidRuntime: Process: com.facebook.orca, PID: 8404
10-09 17:34:00.243  8404 11119 E AndroidRuntime: java.lang.RuntimeException: json parse error on line 0: expected json value
10-09 17:34:00.243  8404 11119 E AndroidRuntime: 	at com.facebook.jni.ThreadScopeSupport.runStdFunctionImpl(Native Method)
10-09 17:34:00.243  8404 11119 E AndroidRuntime: 	at com.facebook.jni.ThreadScopeSupport.runStdFunction(:0)

I think what's happening here is that the hook is setting args[0] to 0 somehow, but I don't see how this script could be doing that. Thanks!

**Comment by oleavr** [comment]
This probably means that Interceptor fails to [relocate](https://github.com/frida/frida-gum/blob/702723e6ad5f8cc6ca5c4c3f3b58255604a06def/gum/backend-arm64/guminterceptor-arm64.c#L232) the start of the function to the trampoline that it generates. The Arm64Relocator that it uses might be missing handling of some position-dependent instruction – it currently handles [these](https://github.com/frida/frida-gum/blob/702723e6ad5f8cc6ca5c4c3f3b58255604a06def/gum/arch-arm64/gumarm64relocator.c#L277-L301). (Or its existing handling has a flaw.) Another theory is that the function has a branch back to the beginning, and we overwrite past that point. We have some [logic](https://github.com/frida/frida-gum/blob/702723e6ad5f8cc6ca5c4c3f3b58255604a06def/gum/arch-arm64/gumarm64relocator.c#L411-L512) to detect such scenarios, but it's far from perfect.

Could you disassemble the start of the function before hooking it and post an excerpt here?

Cheers!

**Comment by natashenka** [comment]
The assembly is:

.plt:00000000002E53E0                 ADRP            X16, #off_2FF580@PAGE
.plt:00000000002E53E4                 LDR             X17, [X16,#off_2FF580@PAGEOFF]
.plt:00000000002E53E8                 ADD             X16, X16, #off_2FF580@PAGEOFF
.plt:00000000002E53EC                 BR              X17

**Comment by oleavr** [comment]
@natashenka I'll take a quick stab at the last idea, seems like a relatively simple fix that could impact a lot of apps.

**Comment by oleavr** [comment]
@natashenka Hmm, seems I'm seeing a different function:

```
0x71d98cc4a8	sub sp, sp, #0xb0
0x71d98cc4ac	stp x20, x19, [sp, #0x90]
0x71d98cc4b0	stp x29, x30, [sp, #0xa0]
0x71d98cc4b4	add x29, sp, #0xa0
```

Was able to reproduce the same crash though!

Looking at that code, the issue here is that this code looks at `LR`:

    stp x29, x30, [sp, #0xa0]

So it's looking at where it's being called from and making decisions based on it. However, `Interceptor.attach()` replaces `LR` in order to trap the return, which means this function is seeing a caller that it's not expecting. That is if you do:

```
Interceptor.attach(impl, {
  onEnter: function () {
    console.log('here');
  }
});
```

However, if you use an instruction-level probe, it will not modify `LR`:

```
Interceptor.attach(impl, function (args) {
  console.log('here');
});
```

This works for me.

(Such probes can also be put (almost) anywhere in a given function – useful if you need to capture the return value or look at registers at arbitrary points.)

Cheers!

**Comment by natashenka** [comment]
That works for me too. Thanks so much!!
