### ISSUE TITLE
How do i change NSString argument  when hooking obj-c method?

### ISSUE THREAD

**Issue by claudiocellec** [frida/frida#147]
Hello,

I'm trying to alter an obj-c method.
I can successfully hook the method and read the variables but when i try to change the value of one of the NSString arguments the application crashes.

the way i tried is:
args[3] = new ObjC.Object(ptr("0x1234"));

Thanks,
Claudio.

**Comment by oleavr** [comment]
Hi,

That would only work if you know there's an Objective-C string at 0x1234 in memory. Instead you might want something like:
`args[3] = ObjC.classes.NSString.stringWithString_('Hello');`

Cheers!

**Comment by claudiocellec** [comment]
Hi,

Thanks for the quick help!
it did worked. but now when i try to change more than one argument, like this:
args[2] = ObjC.classes.NSString.stringWithString_('a');
args[3] = ObjC.classes.NSString.stringWithString_('b');
args[4] = ObjC.classes.NSString.stringWithString_('c')

It does work only when the function is first called, after that, only the first argument (args[2]) is being changed. I have no clue why that happens.
Is there a solution for this problem?

Thanks again,
Claudio.

**Comment by oleavr** [comment]
Should work properly in latest Frida 9.x.
