### ISSUE TITLE
how to hook a android c program

### ISSUE THREAD

**Issue by forgottor** [frida/frida#1474]
android app use shell，e.g.
 su -c /data/user/0/muo.cpjndnu.xnzlfka/files/tel.so 111111111111111111111111 d1d13897975c4e6

how,can i to hook this c program, i can not get tel.so address

**Comment by ii64** [comment]
You can try to disassemble/debug it with Ghidra, or if you're using frida server on rooted device, you can use the process id

**Comment by forgottor** [comment]
i use inject to hook,like this:

/data/local/tmp/frida-inject1401  -f  /data/user/0/dxh.zgsrvhc.kkuutak/files/test.so  -s /data/local/tmp/test.js
