### ISSUE TITLE
how to replace value of input of MessageBoxW of user32.dll

### ISSUE THREAD

**Issue by punishell** [frida/frida#1475]
Hello i saw some examples for C functions with ptr() but how i could replace a value of arg[1] of MessageBoxW? 
`
int MessageBoxW(
  HWND    hWnd,
  LPCWSTR lpText,
  LPCWSTR lpCaption,
  UINT    uType
);
`
`"""
    var baseAddr = Module.findExportByName('user32.dll','MessageBoxW');
    console.log('user32.dll baseAddr: ' + baseAddr);

   

    Interceptor.attach(baseAdd), {

        
        onEnter: function (args) {
    
            console.log('lpText',Memory.readUtf16String(args[1])); // Arg to replace
     
        },

        // When function is finished
        onLeave: function (retval) {
            console.log('retval'+retval);
        }
    });

"""`

Ps. Probbably i need to overload implementation of whole function but i dont cant find eny resources.

**Comment by punishell** [comment]
```"""



    var baseAddr = Module.findExportByName('user32.dll','MessageBoxW'); 

    Interceptor.attach(baseAddr, { 

        onEnter: function (args) {
            Memory.writeUtf16String(args[1], 'test');
            console.log(Memory.readUtf16String(args[1]));
           
        },


        onLeave: function (retval) {
           
            console.log('[+] Returned from baseAddr: ' + retval);
        }
    });
""")```

**Comment by oleavr** [comment]
@punishell Would recommend doing it like [this](https://frida.re/docs/best-practices/) instead.
