### ISSUE TITLE
Unexpected ES6 syntax error

### ISSUE THREAD

**Issue by CaledoniaProject** [frida/frida#1479]
I'm trying to use the `() => {}` syntax, it's valid everywhere but frida:

```
Java.perform(() => {
	var main = Java.use('sg.vantagepoint.uncrackable1.MainActivity')
	main.a.implementation = function(arg1) {
		return
	}
})
```

It complains:

```
Failed to load script: script(line 1): SyntaxError: empty expression not allowed
```

**Comment by oleavr** [comment]
The default runtime uses Duktape which only supports ES5, but we will soon replace it with QuickJS, which supports ES2020.

In the meantime you can either [use frida-compile](https://github.com/oleavr/frida-agent-example) or switch to our V8-based runtime – i.e. `session.create_script(…, runtime='v8')` / `--runtime=v8`.
