### ISSUE TITLE
[Feature request] insert a debug break here

### ISSUE THREAD

**Issue by 0xABD** [frida/frida#148]
It would be nice to have a shorthand function in Frida native Interceptor API to insert a debug break at a specific address (preserving the original code at that address, preferably restoring it afterwards).
https://github.com/scottt/debugbreak has a nice collection of instructions for different architectures.

**Comment by oleavr** [comment]
This is now possible with the new API: `Memory.patchCode(ptr('0x1234'), 1, function (ptr) { Memory.writeU8(ptr, 0xCC); })`
