### ISSUE TITLE
Connecting new iPad Device is giving problems

### ISSUE THREAD

**Issue by poldenais** [frida/frida#1484]
HI all,
    I can connect to an older iPad device no problem and run Frida commands from my MacBook but for some reason with a new iPad device Im getting the strange error below when I attempt to run Frida commands.

Anyone any ideas please? 
Thanks

Device:
iPad 7th Generation
Software 13.2.2

frida --version
12.11.9

```
MacBook-Pro` ~ % frida-ps -Uai

(frida:2715): Frida-CRITICAL **: 13:00:08.760: file ../../../frida-core/lib/interfaces/session.vala: line 167: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?re.frida.HostSession12? on object at path /re/frida/HostSession (g-dbus-error-quark, 19)
zsh: segmentation fault  frida-ps -Uai
```

**Comment by poldenais** [comment]
Sorry updated my Frida version on MacBook. frida-ps -Uai

**Comment by atlantavip** [comment]
for me the problem was not solved:
frida --version
 14.0.5

**Comment by MantisSTS** [comment]
I got the same issue at the moment

**Comment by oleavr** [comment]
This always means you have a Frida component of a different major version. For jailed iOS make sure you also check the Gadget in your home directory, e.g. `~/.cache/frida`.

**Comment by DuffyAPP-IT** [comment]
Cheers Ole! That worked a treat 🥳
