### ISSUE TITLE
Instanciate a class which implements an interface

### ISSUE THREAD

**Issue by alexduros** [frida/frida#1493]
A bit similar to https://github.com/frida/frida/issues/863, but when I'm trying to instanciate an `com.android.okhttp.okio.Buffer` with a `var BufferObj = Buffer.$new()`, I'm always reaching a `no supported overloads`.

Looking at `com.android.okhttp.okio.Buffer` implementation, it seems that it is a class which implements a `BufferedSink` which is an interface.

I'm a quite new to Frida so I don't really where to start to investigate furthermore. 

Thanks for your help.

**Comment by alexduros** [comment]
While trying workaround, I came up with a different solution and different issue which, however seems to be link. 

Here my snippet to create an okhttp3 `Buffer` in another way : 

```
var out = ByteArrayOutputStream.$new();
var BufferObj = Okio.buffer(Okio.sink(out));
```

My buffer is properly instanciated when I log it to the console

```
<instance: com.android.okhttp.okio.BufferedSink, $className: com.android.okhttp.okio.RealBufferedSink>"
```

But when used with a method which requires a `BufferedSink`, like `requestBody.writeTo` from the ok 

```
error 2: Error: writeTo(): argument types do not match any of:
	.overload('okio.BufferedSink')
```

I guess, there is an issue while checking the types of the arguments.

**Comment by alex88510** [comment]
Hi, I think I ran into the same issue as yours. 
The following code works for me:
`var buffer = Java.use('okio.Buffer');
var bufferInstance = buffer.$new();
requestBody.writeTo(bufferInstance);
console.log(bufferInstance.readUtf8());`

**Comment by alexduros** [comment]
Oh! Perfect, yes working for me as well. Thank you very much ! (Event if I think the above should work as well but I may miss something)

**Comment by rfleuryleveso** [comment]
I'm having the same issue as @alexduros 

```js

var out = ByteArrayOutputStream.$new();
var BufferObj = Okio.buffer(Okio.sink(out));
requestBody.writeTo(BufferObj);
```

ClassName is RealBufferedSink, but writeTo expects a BufferSink.

```js
Error: writeTo(): argument types do not match any of:
        .overload('j.g')
```

Using Alex's method throws a *no supported overloads* error.

Frida last version.
