### ISSUE TITLE
How to escape a "." in the name of an ObjC class in an iOS app

### ISSUE THREAD

**Issue by micahhu** [frida/frida#1496]
Hello, 

I'm trying to instantiate an Objective-C class in an iOS app that has a "." in its name and I'm trying to figure out a way to escape it.

Here's the initial Frida script:

```
// Let's call the wanted class "old.myClass"
var classTarget = ObjC.classes.old.myClass;

// the init method doesn't take any argument
var instance = classTarget.alloc().init()

```

The error message I get is:

`TypeError: cannot read property 'myClass' of undefined
`
It ignored the first part of the class name ("old") which suggests to me that the "." in the class name "old.myClass" needs to be escaped.

My first attempt was to use a backslash, like the following (line 2):

```
// Let's call the wanted class "old.myClass"
var classTarget = ObjC.classes.old\.myClass;

// the init method doesn't take any argument
var instance = classTarget.alloc().init()

```
I got the error message:
```

SyntaxError: invalid escape (line 2)
    at [anon] (input:2)

```

Then, I tried unicode:

```
// Let's call the wanted class "old.myClass"
var classTarget = ObjC.classes.old\u002e.myClass;

// the init method doesn't take any argument
var instance = classTarget.alloc().init()
```

And i get the same error message:

```
SyntaxError: invalid escape (line 2)
    at [anon] (input:2)
```

Could you please help me figure out how to encode the "."?

Thank you very much.

**Comment by oleavr** [comment]
Hey,

Go for:
`ObjC.classes['old.myClass']`

This is also what you'd do if the name was variable.

Cheers!
