### ISSUE TITLE
Frida broken when using other tools e.g Passionfruit

### ISSUE THREAD

**Issue by bensh** [frida/frida#1498]
I am trying to use Passionfruit which leverages frida but everytime I launch it hits me with this error:

`(frida:42655): Frida-CRITICAL **: 12:04:13.775: file ../../../frida-core/lib/interfaces/session.vala: line 167: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “re.frida.HostSession12” on object at path /re/frida/HostSession (g-dbus-error-quark, 19)`

I have Frida 14.0.5 both on the mac and on iOS and the usual Frida commands work ok

```
frida-ps -Uai
  PID  Name                  Identifier                             
-----  --------------------  ---------------------------------------
11374  App Store             com.apple.AppStore                     
11396  Camera                com.apple.camera     
```

Any ideas? Do I need to clear the session file or something?

**Comment by oleavr** [comment]
See chaitin/passionfruit#79.

**Comment by grit96** [comment]
Why was this closed?

**Comment by bensh** [comment]
> 
> 
> Why was this closed?

Seems like its a Passionfruit issue not working with latest update of Frida - 14.0
That said, Passionfruit is archived, so not sure it'll be fixed.

**Comment by grit96** [comment]
Is there any way to use passionfruit currently with this incompatibility?

**Comment by oleavr** [comment]
@grit96 A workaround is to downgrade the iOS-side Frida to 12.x.x, but it's better to upgrade the specific tool to Frida 14. For a tool built on Frida's Node.js bindings, such as Passionfruit, it goes something like this:
1. Run `npm ls frida` and `npm ls frida-compile` in each directory containing a `package.json` to reveal where the outdated packages are.
2. Bump them to the latest according to [npm](https://www.npmjs.com) – running `npm outdated` after `npm install` will also tell you.
3. Delete any `package-lock.json` files – they will be re-generated by the next `npm install`.
4. Make sure that no `createScript()` calls specify `V8`, just replace those with `QJS` instead.
Then once you get it working open a pull-request.

**Comment by ChiChou** [comment]
@oleavr how do I enable module support for the latest frida-compile?

> SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by bensh** [comment]
@oleavr is it possible to downgrade frida at all? having problems with frida 14 on a lot of tools.

I've tried to install a release of v12 from the releases page using dpkg -i but trying to start it on the device gives me bad CPU type in example. if i were to install this from cydia, then it works fine.

**Comment by oleavr** [comment]
@ChiChou 

Sorry for the delay, my GH notifications are a mess :-(

> how do I enable module support for the latest frida-compile?

It was the only thing still pulling in Babel, so I dropped it. Would it be an option to do a soft-migration to TypeScript? (Just rename .js -> .ts, and configure the compiler to be really forgiving about implicit any etc.?)

Down the road I'm hoping to rewrite frida-compile so it uses the TypeScript compiler for all of the bundling and transforms, so the scanning and parsing only needs to happen once. Would like to make Node.js optional so we can run the compiler on Frida's runtime (in the system session, i.e. PID 0) and just make the tool part of frida-tools.

**Comment by oleavr** [comment]
@bensh It sounds like you grabbed the wrong one -- the one suffixed with 64 is for arm64e, and the one without a suffix is for pre-A12 devices. (It's not intuitive at all, just didn't want to introduce a new package name for pre-A12.)

**Comment by ChiChou** [comment]
@oleavr I decide to not upgrade `frida-compile`. Now the problem is at initialization. Even if I've done `Module.ensureInitialization('CoreFoundation')`, accessing `ObjC.classes.*` at the global scope hangs the whole agent.
