### ISSUE TITLE
Memory allocUtf8String problem

### ISSUE THREAD

**Issue by Chensem** [frida/frida#1499]
Memory.allocUtf8String("hello123") 
var str = Memory.allocUtf8String("hello123")

![image](https://user-images.githubusercontent.com/27469499/97995324-542e3300-1e21-11eb-85ed-a2be089f3bea.png)

**Comment by oleavr** [comment]
This is working as intended: In the first call nothing is keeping the return value alive, so it gets deallocated as soon as it's garbage-collected – and that happens very predictably with the new QuickJS runtime.
