### ISSUE TITLE
Cannot hook classes after dynamic code loading

### ISSUE THREAD

**Issue by enovella** [frida/frida#150]
Hi, I am struggling with an Android packer that makes use of dynamic code loading (class encryption). Resulting in  deobfuscated classes in an (o)DEX file in the filesystem when loading them. I have dumped this specific file that seems to have plaintext strings and reflection undone. What I want is to tell Frida that load these deobfuscated classes instead the obfuscated ones in the static APK which are obfuscated and use reflection. These classes are located in the following path and the line code for loading it is:

```
Java.openClassFile("/data/app/deobf.odex").load();
Java.openClassFile("/data/app/deobf.zip").load();
```

Apparently, Frida does not complain about loading but does not intercept any call. I am confident that these calls are made and Frida could intercept them. I have also tried to locate the DEX/ZIP within the default paths used by Frida.

 Any suggestion?

Frida version: 7.1.4 & 7.2.0 tested
Platform : Debian8   x64
Dalvik Executable at /data/app with permissions and ZIP (classes.dex) and odex format

**Comment by 0xABD** [comment]
As per discussion here:
https://twitter.com/oleavr/status/762616376490065926
https://twitter.com/oleavr/status/762621137385840640
> That's definitely possible. You need to hook the class loader API so you can install your hook once it's loaded.
> Frida only uses the app's class loader, so if the class isn't visible to it in this case then we'll need to extend

**Comment by pharazone** [comment]
The same problem……how to reload the classes and the methods that dymanic loaded by the Packer.

**Comment by nshuba** [comment]
@dspiir thanks for the snippet! After getting the correct loader I am finally able to call ```Java.use(`<class name>`)```, however the returned object's methods are undefined... So I cannot hook them.

Could anyone please post a more complete example? This is a similar [issue](https://github.com/frida/frida-java/issues/65), but there is no full sample there either.
