### ISSUE TITLE
Frida 14.0.6 - Failed to spawn: unexpectedly timed out while waiting for app to launch.

### ISSUE THREAD

**Issue by g7maxwell** [frida/frida#1500]
Hi!

Android v10
In Frida 14.0.6 (same 14.05) i have some problem - Failed to spawn: unexpectedly timed out while waiting for app to launch.

```
____
  / _  |   Frida 14.0.5 - A world-class dynamic instrumentation toolkit
 | (_| |
  > _  |   Commands:
 /_/ |_|       help      -> Displays the help system
 . . . .       object?   -> Display information about 'object'
 . . . .       exit/quit -> Exit
 . . . .
 . . . .   More info at https://www.frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch 
```

For example, other commands work normaly:

```
frida-ps -U
frida-trace -U -i open
```

Help me please solve this task.

Thanks!

**Comment by g7maxwell** [comment]
Frida 14.0.7 has same problem (see above). What could cause this problem?

Thanks.

**Comment by vfsfitvnm** [comment]
@g7maxwell Does the app spawn?

**Comment by g7maxwell** [comment]
@vfsfitvnm Yes, App spawn correct and Frida waits, after some time i get` Failed to spawn: unexpectedly timed out while waiting for app to launch `

**Comment by oleavr** [comment]
Perhaps you have Unspecialized App Process Pool (USAP) enabled? Frida isn't compatible with it yet.

Workaround is to disable it. Something like:

```sh
$ setprop persist.device_config.runtime_native.usap_pool_enabled false
```

And then rebooting.

**Comment by g7maxwell** [comment]
@oleavr Great thaks, it's works. I will close the ticket.
