### ISSUE TITLE
Does firda support native jvm?

### ISSUE THREAD

**Issue by lemisky** [frida/frida#1505]
# example - windows10

```java
package Foyou;

public class Main {
    public static void main(String[] args) throws Exception {
        int i = 0;
        while (true) {
            fun("Frida Hook Native Java Function " + i++);
            Thread.sleep(1000);
        }
    }

    static void fun(String s) {
        System.out.println(s);
    }
}
```

I want to hook **fun** method, I don't know if frida supports it (I know it supports Android).
I use **javac** & **java**, and then use **frida -l xx.js -p 7452**

**xx.js**

```javascript
Java.perform(function () {
    var use = Java.use("Foyou.Main");
    use.fun.implementation = function (args) {
        console.log("hook success~");
    }
});
```

**But i get an error**

```
Error: Java API only partially available; please file a bug. Missing: _ZN6Method4sizeEb, _ZN6Method19set_nati
ve_functionEPhb, _ZN6Method21clear_native_functionEv, _ZN6Method24restore_unshareable_infoEP6Thread, _ZN6Method10jmethod_idEv, _ZN
20ClassLoaderDataGraph10classes_doEP12KlassClosure, _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_, _ZN8VMThread7executeEP
12VM_Operation, _ZN11OopMapCache22flush_obsolete_entriesEv, _ZN14NMethodSweeper16sweep_code_cacheEv, _ZTV18VM_RedefineClasses, _ZN
18VM_RedefineClasses4doitEv, _ZN18VM_RedefineClasses13doit_prologueEv, _ZN18VM_RedefineClasses13doit_epilogueEv, _ZNK18VM_Redefine
Classes26allow_nested_vm_operationsEv, _ZN19Abstract_VM_Version19jre_release_versionEv, _ZN14NMethodSweeper11_traversalsE, _ZN14NM
ethodSweeper13_should_sweepE
    at K (frida/node_modules/frida-java-bridge/lib/jvm.js:267)
    at O (frida/node_modules/frida-java-bridge/lib/jvm.js:34)
    at frida/node_modules/frida-java-bridge/index.js:53
    at e (frida/node_modules/frida-java-bridge/index.js:36)
    at frida/node_modules/frida-java-bridge/index.js:564
    at o (frida/node_modules/browser-pack/_prelude.js:1)
    at frida/runtime/java.js:1
    at o (/_java.js:1)
    at r (/_java.js:1)
Error: Java API only partially available; please file a bug. Missing: _ZN6Method4sizeEb, _ZN6Method19set_native_functionEPhb, _ZN6
Method21clear_native_functionEv, _ZN6Method24restore_unshareable_infoEP6Thread, _ZN6Method10jmethod_idEv, _ZN20ClassLoaderDataGrap
h10classes_doEP12KlassClosure, _ZN10JavaThread27thread_from_jni_environmentEP7JNIEnv_, _ZN8VMThread7executeEP12VM_Operation, _ZN11
OopMapCache22flush_obsolete_entriesEv, _ZN14NMethodSweeper16sweep_code_cacheEv, _ZTV18VM_RedefineClasses, _ZN18VM_RedefineClasses4
doitEv, _ZN18VM_RedefineClasses13doit_prologueEv, _ZN18VM_RedefineClasses13doit_epilogueEv, _ZNK18VM_RedefineClasses26allow_nested
_vm_operationsEv, _ZN19Abstract_VM_Version19jre_release_versionEv, _ZN14NMethodSweeper11_traversalsE, _ZN14NMethodSweeper13_should
_sweepE
    at K (frida/node_modules/frida-java-bridge/lib/jvm.js:267)
    at O (frida/node_modules/frida-java-bridge/lib/jvm.js:34)
    at frida/node_modules/frida-java-bridge/index.js:53
    at e (frida/node_modules/frida-java-bridge/index.js:36)
    at frida/node_modules/frida-java-bridge/index.js:564
    at o (frida/node_modules/browser-pack/_prelude.js:1)
    at frida/runtime/java.js:1
    at o (/_java.js:1)
    at r (/_java.js:1)

```

## Please help me, thank you very much 😘

@oleavr @oleavr @oleavr ~thank you very much 😘 & Waiting for you

**Comment by lemisky** [comment]
@oleavr 
作者你好,
能帮忙解答一下嘛~
就说支不支持 hook windows jvm java 就可以了.
支持吗? 
非常感谢🌹🌹🌹

**Comment by lemisky** [comment]
期待 @oleavr

**Comment by lemisky** [comment]
@oleavr

**Comment by oleavr** [comment]
It's supported but only if your JVM has symbols available. That means that the `DebugSymbol` API is able to locate the symbols used by `frida-java-bridge`. Cheers!

**Comment by lemisky** [comment]
> It's supported but only if your JVM has symbols available. That means that the `DebugSymbol` API is able to locate the symbols used by `frida-java-bridge`. Cheers!

Okay, thank you very much for your reply, I see. Thanks again. Send you a little red flower 🌹

**Comment by sailor-fly** [comment]
请问是怎么解决的，我现在也出现了这个错误

**Comment by sailor-fly** [comment]
> > It's supported but only if your JVM has symbols available. That means that the `DebugSymbol` API is able to locate the symbols used by `frida-java-bridge`. Cheers!
> 
> Okay, thank you very much for your reply, I see. Thanks again. Send you a little red flower 🌹

请问是怎么解决的，我用了OpenJDk里面的JDK，还是一样出现这个错误，头疼

**Comment by sailor-fly** [comment]
> > It's supported but only if your JVM has symbols available. That means that the `DebugSymbol` API is able to locate the symbols used by `frida-java-bridge`. Cheers!
> 
> Okay, thank you very much for your reply, I see. Thanks again. Send you a little red flower 🌹

**Comment by lemisky** [comment]
> 请问是怎么解决的，我现在也出现了这个错误

当时我也是突发奇想, 但是后来没有解决, 就去忙别的事去了. 不过知道可以实现就足够, 剩下就使劲干吧.  因为我暂时没有这个刚需.

**Comment by sailor-fly** [comment]
> > 请问是怎么解决的，我现在也出现了这个错误
> 
> 当时我也是突发奇想, 但是后来没有解决, 就去忙别的事去了. 不过知道可以实现就足够, 剩下就使劲干吧. 因为我暂时没有这个刚需.

我试了作者说的有符号的JDK，AdoptOpenJDK 里面的都试过了，还是不行，网上查资料也没有，真滴难受

**Comment by lemisky** [comment]
哈哈, 那就只有研究 frida 实现原理了.
我当时也是网上搜不到, 没办法才来这里问一问的.

**Comment by lemisky** [comment]
@sailor-fly 来来来, 加个wx: lemisky, 有机会交流一下😁

**Comment by sailor-fly** [comment]
> It's supported but only if your JVM has symbols available. That means that the `DebugSymbol` API is able to locate the symbols used by `frida-java-bridge`. Cheers!

Hi, I'm on Windows 10 x64, and I have tested  OpenJDK  8 - 16, but I also got the error "Error: Java API only partially available" , none of those are compiled with symbols?  Can you give me some help ?

**Comment by lemisky** [comment]
Maybe you need @ Author

**Comment by sailor-fly** [comment]
@oleavr Please help me
