### ISSUE TITLE
Cannot list devices in frida 14.0.8

### ISSUE THREAD

**Issue by raulmozosuarez** [frida/frida#1508]
Hi 😄,

Since the last update to 14.0.8 using Frida for pre-A12 devices, I have been having issues with listing the devices connected to the computer and listing the processes running in a device.

As you can see in the image below I cannot see the device connected with `frida-ls-devices`.
Also, when running `frida-ps -Uai` I have to wait about 10-15 seconds for the output.
![imagen](https://user-images.githubusercontent.com/69641954/98821783-4899c800-2430-11eb-9c13-8d13cf767e15.png)

Due to the impossibility to list the devices when running a hook frida outputs a timeout error. 
![imagen](https://user-images.githubusercontent.com/69641954/98822260-e8575600-2430-11eb-8cdf-21e2d43c0073.png)

Thanks for your help.

OS: Windows 10
Devices: iPhone SE, Iphone X, Ipad mini 2

**Comment by CarlesLlobet** [comment]
I have the same issue here! 

Everything was working fine with 14.0.5, just updating frida-server pre-a12 in cydia to the 14.0.8 and now I can not see any of my devices, and they do not list processes.

Here you can see how I was able to list all the applications successfully, I updated the server to frida 14.0.8 from cydia, and gave me an "unable to connect" error:
![image](https://user-images.githubusercontent.com/6575422/98834227-3e32fa80-243f-11eb-814f-2ce4bdd913a1.png)

OS: Windows 10
Devices: iPhone Xs, iPad mini 2

PS: Eventhough the error wasn't a mismatch between frida-server and client, I have updated frida-tools python package, but still the same error

**Comment by mrmacete** [comment]
Hello, here are a few questions:

- what happens if you downgrade to Frida 14.0.5 (both host and device, or only on the host) ? does it go back to a working state?
- does it work with linux / macOS host (if you have a chance to try) ?
- what iOS version are you using?
- is the device jailbroken and using what jailbreak?

**Comment by raulmozosuarez** [comment]
Hi @mrmacete,

- I have not found a way to downgrade Frida on the device because is managed with Cydia.
When downgrading the host to Frida 14.0.5 does not go to a working state as you can see below.
![imagen](https://user-images.githubusercontent.com/69641954/98912585-995c0000-24c6-11eb-9233-afe73a3fc70f.png)

- I am not able to verify if it works with a Linux / macOS host sorry
- iOS versions I am using are:
    - iPhone X (A1901) - 12.1.2
    - iPad mini 2 (A1489) - 12.4.8
    - iPhone SE (MP852Y/A) - 13.3.1
- The device is jailbroken using checkra1n

**Comment by mrmacete** [comment]
ok, i'm going to try and reproduce this later (on a vm, as i don't have access to an actual windows machine).

This looks like a windows-specific issue related to the 3rd-party component which exposes apple devices connect to usb and possibly how Frida "talks" to it.

some more questions:

- did you get iTunes from apple or from the windows store? 
- is it possible that you also updated that stuff along with Frida?
- are other apps accessing apple devices still working fine?

**Comment by CarlesLlobet** [comment]
Hi @mrmacete,

As you can see yesterday it suddenly started failing (thanks god I took that evidence), but today without doing anything (updating or re-installing anything) it works again as always: 
- frida-ls-devices works fine
- frida-ps -Uai works fast
- My [TCPRelay](https://github.com/CarlesLlobet/TCPRelay) implementation works again fine

I don't know what happened. Maybe I had to give some time to frida-server after the update to give time to the deamon to properly start again the new frida-server (14.0.8) and stop the former one (14.0.5).

Good Luck to @raulmozosuarez in getting his problem fixed also.

**Comment by raulmozosuarez** [comment]
Hi @mrmacete,

I have uninstalled iTunes and installed it from the Windows Store and now everything works fine now.

I am sorry I cannot be of more help to identify the problem.
Thanks for your help.
