### ISSUE TITLE
Spawn, apply instrumentation then detach without losing the instrumentation

### ISSUE THREAD

**Issue by ali-alidoust** [frida/frida#151]
Is there a way of doing frida instrumentation like this:
1. Spawn the target process
2. Create a script and apply instrumentation
3. Resume the target process
4. Detach from the target process **without** losing the instrumentation

I'm currently trying this in frida-python but whenever the python process closes, all instrumentation is reverted on the target process.

**Comment by oleavr** [comment]
This is not currently supported but is something we should consider adding API for, as it would be very easy to implement.

**Comment by oleavr** [comment]
Let's revisit this later.
