### ISSUE TITLE
Error: No such interface “re.frida.HostSession14” on object at path /re/frida/HostSession (g-dbus-error-quark, 19)

### ISSUE THREAD

**Issue by briglewis** [frida/frida#1510]
I've had this issue with frida version 14.07 and frida version 14.08.

Device: Android Nexus 5
Android Version: 6.0.1
frida-server: frida-server-14.0.8-android-arm
frida version on Android device: 14.0.8
Host OS: Mac OSX 10.15.5 Catalina

![frida-error2](https://user-images.githubusercontent.com/19641210/99021296-7ad43280-25b4-11eb-867e-70ef32630e79.png)

Previously Frida was working without any issues.

Appreciate your help!

**Comment by bensh** [comment]
There is currently a lot of this going around due to lots of backend changes. 
I have had this constantly for days whether I'm on v14 on device and host, or v12 on device and v14 on host.

Sessions getting confused or something.

**Comment by briglewis** [comment]
Without any intervention on my side Frida is magically working again 🥳
