### ISSUE TITLE
Frida-14.0.8.: Unable to locate the libc; please file a bug

### ISSUE THREAD

**Issue by lidongbo** [frida/frida#1516]
11-17 14:33:15.381 8580-8595/com.myapp I/art: Background sticky concurrent mark sweep GC freed 114298(5MB) AllocSpace objects, 2(32KB) LOS objects, 6% free, 65MB/70MB, paused 7.125ms total 181.801ms
11-17 14:33:16.262 8580-8595/com.myapp I/art: Background sticky concurrent mark sweep GC freed 72611(5MB) AllocSpace objects, 7(153KB) LOS objects, 6% free, 65MB/70MB, paused 5.219ms total 105.685ms
11-17 14:33:17.307 8580-9064/com.myapp W/linker: frida-agent-32.so: unused DT entry: type 0x6ffffef5 arg 0x1f0c
11-17 14:33:17.446 8580-9064/com.myapp A/Frida: Unable to locate the libc; please file a bug
11-17 14:33:17.475 8580-9064/com.myapp D/Snare-JNI: handle signal start
11-17 14:33:17.477 8580-9064/com.myapp D/Snare-JNI: ready to unwind
    
    --------- beginning of crash
11-17 14:33:17.502 8580-9064/com.myapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdead0000 in tid 9064 (n.myapp)
11-17 14:33:17.604 1518-1518/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-17 14:33:17.604 1518-1518/? I/DEBUG: Build fingerprint: 'Android/aosp_shamu/shamu:5.1.1/LYZ28N/0.0.1:user/release-keys'
11-17 14:33:17.604 1518-1518/? I/DEBUG: Revision: '0'
11-17 14:33:17.604 1518-1518/? I/DEBUG: ABI: 'x86'
11-17 14:33:17.605 1518-1518/? I/DEBUG: pid: 8580, tid: 9064, name: n.myapp  >>> com.myapp <<<
11-17 14:33:17.605 1518-1518/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdead0000
11-17 14:33:17.691 1518-1518/? I/DEBUG: Abort message: 'Unable to locate the libc; please file a bug'
11-17 14:33:17.692 1518-1518/? I/DEBUG:     eax 00000000  ebx a4233ff4  ecx b7717990  edx b7717990
11-17 14:33:17.692 1518-1518/? I/DEBUG:     esi 00000008  edi 00000001
11-17 14:33:17.692 1518-1518/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
11-17 14:33:17.692 1518-1518/? I/DEBUG:     eip a409f0ee  ebp 8ebff6c8  esp 8ebff5d0  flags 00010246
11-17 14:33:17.692 1518-1518/? I/DEBUG: backtrace:
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #00 pc 001950ee  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #01 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #02 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #03 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #04 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #05 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #06 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #07 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #08 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #09 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #10 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #11 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #12 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #13 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #14 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #15 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #16 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #17 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #18 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #19 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #20 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #21 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #22 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #23 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.692 1518-1518/? I/DEBUG:     #24 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #25 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #26 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #27 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #28 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #29 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #30 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #31 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #32 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #33 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #34 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #35 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #36 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #37 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #38 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #39 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #40 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #41 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #42 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #43 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #44 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #45 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #46 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #47 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #48 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #49 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #50 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #51 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #52 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #53 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #54 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #55 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #56 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #57 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.693 1518-1518/? I/DEBUG:     #58 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.694 1518-1518/? I/DEBUG:     #59 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.694 1518-1518/? I/DEBUG:     #60 pc 001950ed  /system/lib/libhoudini.so
11-17 14:33:17.694 1518-1518/? I/DEBUG:     #61 pc 001976c0  /system/lib/libhoudini.so
11-17 14:33:17.694 1518-1518/? I/DEBUG:     #62 pc 000133ef  /system/lib/libc.so
11-17 14:33:17.694 1518-1518/? I/DEBUG:     #63 pc 001950ed  /system/lib/libhoudini.so

**Comment by pussinboots1992** [comment]
Are you using an emulator and arm translator ? Seems to be the case because I can see libhoudini.so in your debug output...I think it isn't supported yet. Are you using a gadget in the apk or running Frida-Server as root on the android system ?

**Comment by lidongbo** [comment]
1, yes, emulator and use arm translator to call so-lib.
2, no use Frida-gadget.
3, running Frida-Server with no root.

**Comment by pussinboots1992** [comment]
I think you are probably having an issue similar to me:

https://stackoverflow.com/questions/64891548/having-issues-with-a-frida-gadget-on-an-emulated-android-device

I saw a comment suggesting to use a Frida gadget instead but event that appears to fail.

**Comment by Mimi8298** [comment]
same problem on x86 emulator since version 14.x

**Comment by kattakkat** [comment]
Non-similar, but on real device fails to start frida-server 14.0.8 arm64 with "No such file or directory"
