### ISSUE TITLE
frida-trace -U -f "<app identifier>" causes frida.InvalidOperationError: process is not suspended 

### ISSUE THREAD

**Issue by ferrell-code** [frida/frida#1532]
When I try to launch apps on ios with frida it throws the above error. The app does launch on the iphone but frida doesn't hook in. 

 Frida works fine when I hook into an app that is already running but fails when I want to do anything using the -f flag, any help would be much appreciated :)

Enviroment:
Iphone 6 running ios 13.6.1 with checkra1n jailbreak
Computer-OS: Linux Fedora 32 x86_64

**Comment by ferrell-code** [comment]
It works now I  rebooted and re jailbroke the phone and it work not sure what the error was caused by

**Comment by zaq962** [comment]
the same problem

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/3.8/site-packages/frida_tools/application.py", line 635, in _run
    work()
  File "/Library/Python/3.8/site-packages/frida_tools/tracer.py", line 280, in <lambda>
    self._reactor.schedule(lambda: self._on_message(message, data, ui))
  File "/Library/Python/3.8/site-packages/frida_tools/tracer.py", line 321, in _on_message
    handled = self._try_handle_message(*params)
  File "/Library/Python/3.8/site-packages/frida_tools/tracer.py", line 357, in _try_handle_message
    ui.on_trace_progress('initialized')
  File "/Library/Python/3.8/site-packages/frida_tools/tracer.py", line 132, in on_trace_progress
    self._resume()
  File "/Library/Python/3.8/site-packages/frida_tools/application.py", line 251, in _resume
    self._device.resume(self._spawned_pid)
  File "/Library/Python/3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/frida/core.py", line 148, in resume
    self._impl.resume(self._pid_of(target))
frida.InvalidOperationError: process is not suspended





Enviroment：
Iphone 7 running ios 14.2 with checkra1n jailbreak

how can i resove it？

**Comment by flo-tuv** [comment]
I have the same Issue:

iPhone: SE (A1723 ) (jailbroken with unc0ver  )
iOS: 13.5.1
OS: Kali Linux
Frida: 14.0.8

The tested app is on Cordova app, the app is starting but producing the below error message, frida-trace e.g. crashes the app.
(name of the name changed)

Output: 

root@kali:/opt# frida -U -f at.appname
     ____
    / _  |   Frida 14.0.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Spawned `at.appname`. Use %resume to let the main thread start executing!
[iOS Device::at.appname]-> %resume
[iOS Device::at.appname]-> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/frida_tools/application.py", line 635, in _run
    work()
  File "/usr/local/lib/python3.7/dist-packages/frida_tools/repl.py", line 455, in <lambda>
    self._reactor.schedule(lambda: self._resume())
  File "/usr/local/lib/python3.7/dist-packages/frida_tools/application.py", line 251, in _resume
    self._device.resume(self._spawned_pid)
  File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 148, in resume
    self._impl.resume(self._pid_of(target))
frida.InvalidOperationError: process is not suspended

**Comment by idb-** [comment]
I'm also having this issue. What's strange though is my hooks are operating. I hit an exception on device.resume and if I click continue then the session ends in vscode. If I don't click continue everything seems to be running as expected. This only started occurring when updating to the latest frida version a day or 2 ago.

**Comment by idb-** [comment]
I'm also having this issue but am running agent from vscode, not using frida-trace (haven't tried frida-trace but assume same issue). What's strange though is my hooks are operating. I hit an exception on device.resume and if I click continue then the session ends in vscode. If I don't click continue everything seems to be running as expected. This only started occurring when updating to the latest frida version a day or 2 ago.

**Comment by idb-** [comment]
> I have the same Issue:
> 
> iPhone: SE (A1723 ) (jailbroken with unc0ver )
> iOS: 13.5.1
> OS: Kali Linux
> Frida: 14.0.8
> 
> The tested app is on Cordova app, the app is starting but producing the below error message, frida-trace e.g. crashes the app.
> (name of the name changed)
> 
> Output:
> 
> root@kali:/opt# frida -U -f at.appname
> ____
> / _ | Frida 14.0.8 - A world-class dynamic instrumentation toolkit
> | (_| | > _ | Commands: /_/ |_| help -> Displays the help system
> . . . . object? -> Display information about 'object'
> . . . . exit/quit -> Exit
> . . . .
> . . . . More info at https://www.frida.re/docs/home/
> Spawned `at.appname`. Use %resume to let the main thread start executing!
> [iOS Device::at.appname]-> %resume
> [iOS Device::at.appname]-> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
> self.run()
> File "/usr/lib/python3.7/threading.py", line 870, in run
> self._target(*self._args, **self._kwargs)
> File "/usr/local/lib/python3.7/dist-packages/frida_tools/application.py", line 635, in _run
> work()
> File "/usr/local/lib/python3.7/dist-packages/frida_tools/repl.py", line 455, in
> self._reactor.schedule(lambda: self._resume())
> File "/usr/local/lib/python3.7/dist-packages/frida_tools/application.py", line 251, in _resume
> self._device.resume(self._spawned_pid)
> File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 26, in wrapper
> return f(*args, **kwargs)
> File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 148, in resume
> self._impl.resume(self._pid_of(target))
> frida.InvalidOperationError: process is not suspended

I was having a similar issue after updating to the newest version of cydia substrate. Try downgrading to version 0.9.7111 and see if that fixes the issue for you.

**Comment by idb-** [comment]
> This seems to happen with the latest version of "Substitue" installed (2.1.0) as well and running on Cydia Substrate version 0.9.7111 does not fix it for me.
> 
> Might this be some issue if the app is some Cordova App ?

I also have Substitute 2.1.0 installed and the previous fix I mentioned works fine for me. What jailbreak are you using?

**Comment by flo-tuv** [comment]
unc0ver 6.1.1

**Comment by eitguide** [comment]
I got the same issue

**Comment by kevinspider** [comment]
I encountered the same issue and resolved it by downgrading the version of Cydia Substrate. The current available environment is: iOS 12.5.7, iPhone 6, checkra1n, Cydia Substrate 0.9.7111, frida 14.2.18.

**Comment by kotori2** [comment]
I have the same issue on iOS 16.4.1 & rootless Palera1n. Solved by manually installing latest Frida server (16.1.6) on iPhone first.
