### ISSUE TITLE
Failed to enumerate processes: unexpected response: PasswordProtected

### ISSUE THREAD

**Issue by sashs** [frida/frida#1547]
Hi, 

I get the error "Failed to enumerate processes: unexpected response: PasswordProtected" since today. However, I do not know what the problem is. I am using the current frida version on Android 7.

**Comment by sashs** [comment]
I see, that is a problem of my system. Weird.

**Comment by CLtheorem** [comment]
how do you solve this problem? :)

**Comment by zhugongzi** [comment]
@CLtheorem Did you connect another device through USB, not your usual test device?
