### ISSUE TITLE
Failed to start tracing: the connection is closed

### ISSUE THREAD

**Issue by NelsonGaleano** [frida/frida#1552]
frida-ps  works correctly, but it don't when i use frida-tracing.
Help plis
From Paraguay

**Comment by zhiguangqiao** [comment]
+1, i meet the same problem 
Failed to start tracing: the connection is closed

**Comment by oleavr** [comment]
Update your frida-tools to the latest version. This issue is covered in the [14.1 release notes](https://frida.re/news/2020/12/01/frida-14-1-released/).
