### ISSUE TITLE
arg[1] and args[2] crashes onEnter

### ISSUE THREAD

**Issue by prolitornandbasturtrumerthydempe** [frida/frida#1553]
`onEnter` crashes the application if I use `args[1]` or `args[2]`
`onLeave` works perfectly fine (`args[0]` is also fine).

**Here's my code:**

```
var game = ObjC.classes.CHGame["- sanMoves:"];

Interceptor.attach(game.implementation, {
    onEnter: function(args) {
    // args[0] is self
    // args[1] is selector
    // args[2] holds the first function argument
    var moves = ObjC.Object(args[1]);
    // console.log("In: " + moves.toString());
    },

    onLeave: function(retval) {
    var moves = ObjC.Object(retval);
    console.log("\nOut:\n" + moves.toString());
    }
});
```

**And here's the method declaration (from disassembler) of `-[CHGame sanMoves:]`:**

`id __cdecl -[CHGame sanMoves:](CHGame *self, SEL, bool)`

It simply takes a `bool` and returns an `id`.

Do you know why I can't access` args[1]` and `args[2]` here?

**Comment by oleavr** [comment]
`args[1]` is not an Objective-C object, it's a selector. Likewise, for this particular method, `args[2]` is a `bool` which is also not an Objective-C object.
