### ISSUE TITLE
iOS Choose() error

### ISSUE THREAD

**Issue by huobb0** [frida/frida#1559]
Using Frida 14.1.2 with iOS Frida server 14.1.2 and I'm trying to dump instance variables. As far as I remember, this is the way to achieve this. (iOS 13.4.1 if that matters - )

Any hints on whether this is a bug or am I missing something here? 

Thanks,
zs

 $ frida -U "Blackjack"
     ____
    / _  |   Frida 14.1.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/

[iPad 4::Blackjack]-> ObjC.choose(ObjC.classes.NSString)
Error: linking failed: tcc: error: undefined symbol '_class_getInstanceSize'
tcc: error: undefined symbol '_malloc_get_all_zones'
tcc: error: undefined symbol '_class_getSuperclass'
tcc: error: undefined symbol '_malloc_get_all_zones'
tcc: error: undefined symbol '_class_getSuperclass'
    at _ (frida/node_modules/frida-objc-bridge/lib/fastpaths.js:11)
    at get (/_objc.js)
    at choose (frida/node_modules/frida-objc-bridge/index.js:1022)
[iPad 4::Blackjack]->

**Comment by chensokolovsky** [comment]
Same for me (14.1.2, iOS 13.4.1)

**Comment by lauritzh** [comment]
Same for me. Did anyone find a workaround, yet?

**Comment by epsleq0** [comment]
Same here. Unfortunately the official repo (https://build.frida.re) currently only has the latest version (14.1.2). So a comfortable downgrade with Cydia is not possible. As a workaround I recommend a manual downgrade to version 14.0.8.

Please make sure to remove the Frida package with Cydia first. Then, select the appropriate binary from https://github.com/frida/frida/releases/tag/14.0.8 (for me frida-server-14.0.8-ios-arm64.xz worked for me - iOS 13.6.1, A10 device, 64 bit). Decompress and manually put the binary on the iOS device under `/usr/sbin/frida-server`, e.g. with `scp`. Make the file executable (`chmod +x /usr/sbin/frida-server`) and start the Frida server: `/usr/sbin/frida-server -D`.

I also tried this with 14.1.1 but it still failed, maybe 14.1.0 won't.

**Comment by oleavr** [comment]
@huobb0 Thanks for reporting, great catch! I made a mistake while rebasing our patches as part of the TinyCC upgrade, and apparently we have a blind spot in our CI, so this one slipped through undetected. Sorry about that! Bug-fix release will be coming soon, hopefully tomorrow.

**Comment by oleavr** [comment]
Fixed in 14.1.3.
