### ISSUE TITLE
build python-macos on Apple M1 failed

### ISSUE THREAD

**Issue by hans2003** [frida/frida#1565]
macOS Big Sur
version 11.0.1
Chip   Apple M1

frida-trace --version
14.1.3

1、frida-trace some process failed, error msg is:
Failed to attach: process is dead.

but, actually the process is alive.

2、I try to compile frida-python，but failed
make python-macos PYTHON=/Users/ripple/miniforge3/bin/python3.9

> Run-time dependency glib-2.0 found: NO (tried pkgconfig and framework)
> 
> frida-gum/meson.build:185:0: ERROR: Dependency "glib-2.0" not found, tried pkgconfig and framework

but, I install glib with homebrew; like this:
(base) ripple@Mac-mini frida %arch -x86_64 brew list
gdb		glibmm		pcre		sqlite
gdbm		libffi		pkg-config	xz
gettext		libsigc++@2	python@3.9
glib		openssl@1.1	readline

full error log:
[meson-log.txt](https://github.com/frida/frida/files/5671064/meson-log.txt)

**Comment by oleavr** [comment]
Make sure you're building in an arm64 terminal. If you use iTerm built for x86_64, or your Python is built for x86_64, that might result in our build system being confused. (This is the kind of edge-cases we should improve support for though – PRs welcome.)

As a side-note, there's no need to install GLib from Homebrew – we use (and require) our own GLib, and our build system should download a prebuilt version of that. (Hopefully it has been downloaded to `build/sdk-*`.)

**Comment by oleavr** [comment]
> Make sure you're building in an arm64 terminal.

Oops, I forgot that I fixed this in `releng/detect-arch.sh`, so this is likely not the issue here.

Thinking more about it:

> 1、frida-trace some process failed, error msg is:
> Failed to attach: process is dead.

This is likely because the Python interpreter that you installed Frida for is x86_64, and that won't work. Also note that attaching to system processes/Apple-signed binaries typically requires SIP to be disabled.

> 2、I try to compile frida-python，but failed

This issue is most likely caused by `releng/setup-env.sh` failing to download the SDK – with prebuilt static libraries of our dependencies – to `build/sdk-*`. The recent changes there may have broken error-handling in case the download fails midway through, so to be sure wipe `build/` and try again.

**Comment by hans2003** [comment]
Thanks for your reply。

> > Make sure you're building in an arm64 terminal.
> 
> Oops, I forgot that I fixed this in `releng/detect-arch.sh`, so this is likely not the issue here.
> 
> Thinking more about it:
> 
> > 1、frida-trace some process failed, error msg is:
> > Failed to attach: process is dead.
> 
> This is likely because the Python interpreter that you installed Frida for is x86_64, and that won't work. Also note that attaching to system processes/Apple-signed binaries typically requires SIP to be disabled.
> 

The python environment is miniforge。 
![image](https://user-images.githubusercontent.com/40558512/101880097-537d7f00-3bcd-11eb-9e10-ba75841ecb96.png)

(base) ripple@ripples-Mac-mini ~ % python
Python 3.9.1rc1 | packaged by conda-forge | (default, Nov 28 2020, 22:21:58)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.


When I frida-trace ‘Chome’ process and ‘QQlive’ process， the error msg is 'Failed to attach: process is dead'.

When trace ‘cat’ ， 'QuickTime Player' , ’safari‘ process, the error msg is 'Failed to attach: unexpected error while starting thread (set_thread_state returned '(os/kern) protection failure')'

The SIP is disabled, like this:
(base) ripple@ripples-Mac-mini ~ % csrutil status
System Integrity Protection status: disabled.

I replace the _frida.so that pip installed with my own compiled _frida.so。 but，the error is same。



> > 2、I try to compile frida-python，but failed
> 
> This issue is most likely caused by `releng/setup-env.sh` failing to download the SDK – with prebuilt static libraries of our dependencies – to `build/sdk-*`. The recent changes there may have broken error-handling in case the download fails midway through, so to be sure wipe `build/` and try again.

I remove 'build/', then compile success！！ Thank you
