### ISSUE TITLE
can i call a function with java.util.Map type argument 

### ISSUE THREAD

**Issue by stayliv3** [frida/frida#158]
i could call a static function use the js:

Java.perform(function () {
    // console.log(Java.enumerateLoadedClassesSync());
    var d = Java.use("com.jerome.jni.JNIProcess");
    console.log(d.getPart1('aaaaaaaa'));
    console.log(d.getPart2('bbbbbbbb'));
});

the argument type is strings .but now i have a function the argument type is java.util.Map

just like 

`private static String a(Map arg5, Map arg6) {
`

does frida support it to make a map type argument and pass it to the function ?

thanks.

I have read the doc and could not find a solution.

I got the way to hook the funtions with map arguments.but don't know how to call it.

**Comment by oleavr** [comment]
Hi,

[java.util.Map](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html) is just an interface, so you'd want to instantiate one of its implementations, like [HashMap](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html). For example:

```js
Java.perform(() =>
  const HashMap = Java.use('java.util.HashMap');

  const initialCapacity = 2;
  const map = HashMap.$new(initialCapacity);
  map.put('name', 'Joe');
  map.put('description', 'Engineer');

  /* now you can use `map` */
});

**Comment by stayliv3** [comment]
really thanks for u. I'll try it.

**Comment by stayliv3** [comment]
@oleavr i test on the android 4.4.4 and frida 7.2.13  but still get the error message
```
Error: put: argument types do not match any overload
    at HashMap.f (repl1.js:1089:27)
    at repl1.js:3278:9
    at VM.perform (repl1.js:2124:17)
    at repl1.js:284:24
    at Array.forEach (native)
    at performPending (repl1.js:282:21)
    at repl1.js:264:29
    at VM.perform (repl1.js:2124:17)
    at Runtime.perform (repl1.js:259:24)
    at repl1.js:3274:9
```

the javascript i used

```
Java.perform(() =>{
    const HashMap = Java.use('java.util.HashMap');
  	const initialCapacity = 2;
  	const map = HashMap.$new(initialCapacity);
  	map.put('name', 'Joe');
  	map.put('description', 'Engineer');
  	});

```

**Comment by 0xABD** [comment]
I wonder if we may need to instantiate the HashMap with the exact key and value types specified in the signature?
Something like, ```"Ljava/util/HashMap<Ljava/lang/String;Ljava/lang/String;>;"```

**Comment by stayliv3** [comment]
@0xABD thanks for your advice. can u show me the javascript we should try.

**Comment by c00lyu** [comment]
@stayliv3 you can just try

```
var HashMap = Java.use("java.util.HashMap");
var Map = Java.use("java.util.Map");

hashmap = HashMap.$new()
var map = Java.cast(hashmap, Map);
map.put("a", "1");
map.put("b", "2");
```

**Comment by geeeez** [comment]
> @stayliv3 you can just try
> 
> ```
> var HashMap = Java.use("java.util.HashMap");
> var Map = Java.use("java.util.Map");
> 
> hashmap = HashMap.$new()
> var map = Java.cast(hashmap, Map);
> map.put("a", "1");
> map.put("b", "2");
> ```

if i have a json string.And I want to convert it to a variable of type map.It like this problem,but i don't want to map.put().i want convert a json string to a variable of type map. How can I achieve it。
