### ISSUE TITLE
Bug: Java byte[] 

### ISSUE THREAD

**Issue by polarbear88** [frida/frida#1587]
![image](https://user-images.githubusercontent.com/38294644/103235988-70ac9e80-497e-11eb-95b8-8565a42b8a87.png)

**Comment by polarbear88** [comment]
meta
![image](https://user-images.githubusercontent.com/38294644/103236152-06482e00-497f-11eb-8530-6add209697cc.png)

**Comment by polarbear88** [comment]
Urgent! I need help

**Comment by Miscf** [comment]
I was trapped the same question with you!
