### ISSUE TITLE
/system/bin/sh: ./frida-server-14.0.7-linux-x86: No such file or directory

### ISSUE THREAD

**Issue by sunny250** [frida/frida#1608]
Hi,
When I try to open this  file on netease-mumu ,that show ：
file ./frida-server-14.0.7-linux-x86                                           <
./frida-server-14.0.7-linux-x86: ELF executable, 32-bit LSB 386, dynamic (/lib/ld-linux.so.2 loads 1 lib)
/frida-server-14.0.7-linux-x86                                                <
/system/bin/sh: ./frida-server-14.0.7-linux-x86: No such file or directory

**Comment by sunny250** [comment]
Not match platfrom;
use the frida-server-14.0.7-android-x86

**Comment by PinkDraconian** [comment]
Thank you for making this issue. I also got stuck on this incredibly silly thing.

To people reading this 👇
Ensure you are using the right platform:
frida-server-14.0.7-**android**-x86 != frida-server-14.0.7-**linux**-x86
