### ISSUE TITLE
Feature: Wait for process to be launched

### ISSUE THREAD

**Issue by vdun** [frida/frida#161]
When `frida-trace` does not find the target process, it can wait for it. Once launched, attach to it.
Example:
- In terminal1 : `frida-trace cat`, frida will wait for `cat`
- In terminal2 : `cat`, now it is attached

**Comment by oleavr** [comment]
That would indeed be useful. Please open a PR against frida-python if you're interested in making this happen.

**Comment by juergenhoetzel** [comment]
> [oleavr](/oleavr) closed this [on 19 Jan 2017](#event-928377993)

Is this feature implemented meanwhile?

**Comment by jontelang** [comment]
Was this ever implemented? I am not sure if I've missed something but to solve this now I use 2 terminal windows. One spawns + resumes the app. The other attaches the tracking.

T1: frida -U -f com.the.app
T2: frida-trace --usb -m "*[UIViewController *]" -n "APPNAME"
T1: %resume

Works but non optimal.
