### ISSUE TITLE
Android early instrumentation doesn't attach to application

### ISSUE THREAD

**Issue by ph0t0shop** [frida/frida#1613]
I'm trying to achieve early instrumentation in Frida. Below is a log from my command-line:
```
> frida -U -f com.discord
     ____
    / _  |   Frida 14.2.6 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch

>
```

Now the interesting part: The app _does_  in fact launch, Frida just doesn't attach.
I'm on a OnePlus 6T A6013, Android 10/LineageOS 17.1-20210114-nightly-fajita. I do have Magisk installed. It didn't work with MagiskHide active (as expected) so I disabled it and rebooted before this. 

Side thought: Could the `ro.debuggable` system prop have anything to do with this at all?

EDIT: I should say that this happens with any app that I have tested

**Comment by oleavr** [comment]
Is USAP enabled? (Fast app launching feature in modern Android versions.) If so you must disable it as Frida doesn't support it.

**Comment by ph0t0shop** [comment]
I just read your comment on an older issue mentioning exactly that! I thought it was off by default, but apparently it's not. That fixes the issue, thanks!

**Comment by ViRb3** [comment]
This should be pinned or added to the docs. Just saved me a huge headache, thanks!
