### ISSUE TITLE
Frida-server 14.2.8 - Error binding to address 127.0.0.1:27042: Address already in use

### ISSUE THREAD

**Issue by Czar-IV** [frida/frida#1619]
I updated my frida to version 14.2.8 and can't start frida. I already updated the version on my android to 14.2.8 and applied  chmod 755 but still got this error of address already in use. 

On linux
![image](https://user-images.githubusercontent.com/78155967/106148494-dcd61a00-6157-11eb-8892-17f05bb9bdef.png)

![image](https://user-images.githubusercontent.com/78155967/106148712-245ca600-6158-11eb-9580-55c81854c454.png)

On android
![image](https://user-images.githubusercontent.com/78155967/106148586-fa0ae880-6157-11eb-9216-cb48b815fca9.png)

![image](https://user-images.githubusercontent.com/78155967/106148803-435b3800-6158-11eb-8671-920a0007c9fc.png)

![image](https://user-images.githubusercontent.com/78155967/106149052-93d29580-6158-11eb-9947-4ccf495128b6.png)

**Comment by Nightshades1** [comment]
This can happen if somehow you have a zombie process running, restart your device and try again, assuming no other app use that port

**Comment by Czar-IV** [comment]
> This can happen if somehow you have a zombie process running, restart your device and try again, assuming no other app use that port

I already did it and still the same error. I also updated my magisk, could it be some incompatibility?

![image](https://user-images.githubusercontent.com/78155967/106152997-d72f0300-615c-11eb-8bdd-72d8ba1cf8a8.png)

**Comment by Nightshades1** [comment]
Hmm can you try this:
./frida-server -l 127.0.0.1:PORT       <-----change PORT

Remember to use the same port if you use frida.exe or w/e you do ^^

**Comment by Czar-IV** [comment]
I figured out, there was a plugin "MagiskFrida" installed and another one I can't remeber, so I deleted all of them and reboot my android and then started working

on android, no plug-in.
![image](https://user-images.githubusercontent.com/78155967/106157820-de0c4480-6161-11eb-96a2-692d7801c49b.png)

![image](https://user-images.githubusercontent.com/78155967/106157911-f1b7ab00-6161-11eb-956c-ba1f0b4867c2.png)

> I hope your issue is resolved though 😬 you can also get your architecture on android with "adb shell getprop ro.product.cpu.abi"

and thanks about that! 😄
