### ISSUE TITLE
404 Not Found for Frida 32 bit repository 

### ISSUE THREAD

**Issue by sc4pp1n1** [frida/frida#1625]
Hello,
The cydia repository "https://build.frida.re/pool/main/r/re.frida.server32/re.frida.server32_12.8.6_iphoneos-arm.deb" is not available, the error is as follows:
404 not found
Code: NoSuchKey
Message: the specified key does not exist.
Key: pool / main / r / re.frida.server32 / re.frida.server32_12.8.6_iphoneos-arm.deb
[...]

are there any plans to make the repository available again?

Thank you.

**Comment by oleavr** [comment]
We've stopped publishing 32-bit binaries for macOS and iOS as we're no longer testing on such targets – you will have to build it yourself if you need it. We can bring back support if anybody's willing to maintain it.

**Comment by kwstasna** [comment]
@oleavr how can I install Frida-server to my 32-bit iOS device tho?
