### ISSUE TITLE
Building android x86 error

### ISSUE THREAD

**Issue by HyEvil** [frida/frida#163]
Hi.
I build android-x86 using `make -f Makefile.sdk.mk FRIDA_HOST=android-i386`

Got following error:
`
. build/fs-env-android-i386.rc \
        && cd build/fs-tmp-android-i386/v8 \
        && PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH" \
                CXX_host="$CXX" CXX_target="$CXX" LINK="$CXX" \
                make -j 8 android_ia32.release GYPFLAGS="-D host_os=linux -D werror='' -D v8_use_external_startup_data=0 -D v8_enable_gdbjit=0 -D v8_enable_i18n_support=0 -f make-android -D android_ndk_root=/root/android-ndk-r12b -D android_sysroot=/root/android-ndk-r12b -D android_target_platform=14 -D clang=1  "
make[1]: Entering directory '/root/frida/build/fs-tmp-android-i386/v8'
make[2]: Entering directory '/root/frida/build/fs-tmp-android-i386/v8'
GYP_GENERATORS=make-android \
GYP_DEFINES="target_arch=ia32 v8_target_arch=ia32 OS=android" \
PYTHONPATH="/root/frida/build/fs-tmp-android-i386/v8/tools/generate_shim_headers:/root/frida/build/fs-tmp-android-i386/v8/gypfiles:" \
tools/gyp/gyp --generator-output="out" gypfiles/all.gyp \
              -Igypfiles/standalone.gypi --depth=. \
              -S.android_ia32.release -D host_os=linux -D werror='' -D v8_use_external_startup_data=0 -D v8_enable_gdbjit=0 -D v8_enable_i18n_support=0 -f make-android -D android_ndk_root=/root/android-ndk-r12b -D android_sysroot=/root/android-ndk-r12b -D android_target_platform=14 -D clang=1
gyp: Dependency 'src/v8.gyp:mkpeephole#target' not found while trying to load target src/v8.gyp:v8_base#target
Makefile.android:67: recipe for target 'out/Makefile.android_ia32.release' failed
make[2]: *** [out/Makefile.android_ia32.release] Error 1
make[2]: Leaving directory '/root/frida/build/fs-tmp-android-i386/v8'
Makefile:320: recipe for target 'android_ia32.release' failed
make[1]: *** [android_ia32.release] Error 2
make[1]: Leaving directory '/root/frida/build/fs-tmp-android-i386/v8'
Makefile.sdk.mk:435: recipe for target 'build/fs-tmp-android-i386/.v8-build-stamp' failed
make: *** [build/fs-tmp-android-i386/.v8-build-stamp] Error 2

Please help me.
`

**Comment by oleavr** [comment]
Fixed. Please do a fresh git clone and try again.

**Comment by HyEvil** [comment]
It is worked.
But got new errors..
```
/root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/type_traits:298:49: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
template <>          struct __is_nullptr_t_impl<nullptr_t> : public true_type {};
                                                ^
/root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/type_traits:298:49: error: template argument for template type parameter must be a type
template <>          struct __is_nullptr_t_impl<nullptr_t> : public true_type {};
                                                ^~~~~~~~~
/root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/type_traits:297:17: note: template parameter is declared here
template <class _Tp> struct __is_nullptr_t_impl       : public false_type {};
                ^
/root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/type_traits:530:52: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
template <> struct _LIBCPP_TYPE_VIS_ONLY is_scalar<nullptr_t> : public true_type {};
                                                   ^
/root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/type_traits:530:52: error: template argument for template type parameter must be a type
template <> struct _LIBCPP_TYPE_VIS_ONLY is_scalar<nullptr_t> : public true_type {};
                                                   ^~~~~~~~~
/root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/type_traits:523:17: note: template parameter is declared here
template <class _Tp> struct _LIBCPP_TYPE_VIS_ONLY is_scalar
                ^
In file included from ../src/base/file-utils.cc:10:
In file included from .././src/base/platform/platform.h:25:
In file included from /root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/list:174:
In file included from /root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/memory:597:
/root/android-ndk-r12b//sources/cxx-stl/llvm-libc++/libcxx/include/type_traits:298:49: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
template <>          struct __is_nullptr_t_impl<nullptr_t> : public true_type {};
                                                ^
```

**Comment by oleavr** [comment]
Please try wiping your frida repo and building Frida as normally. (The new SDKs have been prebuilt for most of the platforms and architectures now.)
