### ISSUE TITLE
retval not correct on indirect return value function

### ISSUE THREAD

**Issue by inode-** [frida/frida#1639]
Hello,

working on iOS on ARM64 I found a problem on the return value of the function when the return is not an object but it's a structure. The problem is that frida use "retval" always on direct return, but in some cases it can also be used an indirect return value (x8).

For example [https://developer.apple.com/documentation/foundation/nsprocessinfo/1410906-operatingsystemversion](https://developer.apple.com/documentation/foundation/nsprocessinfo/1410906-operatingsystemversion)

Obj-C code:

```
NSOperatingSystemVersion version = [[NSProcessInfo processInfo] operatingSystemVersion];
NSString* string = [NSString stringWithFormat:@"%ld.%ld", version.majorVersion,version.minorVersion];
```

Frida code:
```
    var os_version = ObjC.classes.NSProcessInfo["- operatingSystemVersion"];

    Interceptor.attach(os_version.implementation, {
        onEnter: function(args) {
            console.log('---------------- > operatingSystemVersion > ----------------');
            this.pippo = this.context.x8;

        },
        onLeave: function (retval) {
            console.log('---------------- < operatingSystemVersion < ----------------');

            console.log("wrong return value: " + retval);
            console.log("right return value: " + this.pippo);

        }
    });
```

**Comment by oleavr** [comment]
Thanks for reporting! This is "unfortunately" [by design](https://github.com/frida/frida-gum/issues/439#issuecomment-632388934) – use `Interceptor.replace()` if you want `NativeCallback` to deal with the ABI for you, or access registers/memory directly.
