### ISSUE TITLE
How to hook a fucntion which return a float number,and get the return value

### ISSUE THREAD

**Issue by karma-sun** [frida/frida#1640]
hook functions like below:
float fun1(float a,float b){
return a+b;
}

**Comment by Ynkcc** [comment]
I also encountered a similar problem, did you solve it?

**Comment by Ynkcc** [comment]
![Screenshot_2022-07-01-22-45-57-685_com android chrome](https://user-images.githubusercontent.com/55530775/176917210-ebd2a70b-4bbb-4497-9613-a40e91f72812.png)
I found it.  This is an old question.
