### ISSUE TITLE
Can I run frida-server on a low version glibc devices or compile frida-server as a staticlly linked elf?

### ISSUE THREAD

**Issue by hear7v** [frida/frida#1645]
I need to run frida-server on a linux arm64 IOT Device.The IOT Device libc version is 2.23,when I run frida-server ,which download from github release,it did't work,and report error "./frida-server-14.2.13-linux-arm64: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./frida-server-14.2.13-linux-arm64)".
So,I try to compile frida-server as a staticlly linked elf file.I modify  frida/frida-core/server/meson.build to follow code:
```
if host_os == 'macos'
  server_plist = 'frida-server.plist'
  extra_link_args += ['-Wl,-sectcreate,__TEXT,__info_plist,' + join_paths(meson.current_source_dir(), server_plist)]
  extra_link_depends += [server_plist]
endif
extra_link_args += ['-static','-pthread','-v']
executable('frida-server', server_sources,
  vala_args: ['--pkg=posix'],
  link_args: extra_link_args,
  link_depends: extra_link_depends,
  dependencies: [core_dep],
  c_args: ['-static','-pthread','-v'],
  install: true,
)
```
But I still can't make a staticlly linked file.

Then I extract files from libc6_2.28-10_arm64.deb,and set *LD_LIBRARY_PATH* to  lib path

```

patchelf --set-rpath /tmp/lib/aarch64-linux-gnu frida-server
 patchelf  --set-interpreter /tmp/lib/ld-linux-aarch64.so.1 frida-server
 LD_LIBRARY_PATH=/tmp/lib ./frida-server

```
After that ,I can run frida-server,but I can't hook successfully.
```
ubuntu@ubuntu-LENOVO-IDEAPAD-Y400:~$ frida-ps -U
  PID  Name
-----  -----------------
  237  6620_launcher
  386  adbd
  238  voip
  184  dbus-daemon
ubuntu@ubuntu-LENOVO-IDEAPAD-Y400:~$ frida-trace voip -U
Failed to attach: unable to inject library into process without libc
```

**Comment by fabiomaia** [comment]
I have the exact same problem

**Comment by alexanderkent** [comment]
Anyone figure out a solution to this?

**Comment by aadog** [comment]
Yes I did, you need to re-edit Frida

**Comment by alexanderkent** [comment]
@aadog interesting, can you share ?

**Comment by ShaliDaliHaliDa** [comment]
how?

**Comment by oleavr** [comment]
Latest Frida binaries for Linux/arm64 are now built against glibc 2.17, so this issue can now be closed.
