### ISSUE TITLE
early instrumentation ok with 7.0.8 but fails with 7.3.2

### ISSUE THREAD

**Issue by flop01** [frida/frida#165]
Hello,

I wrote this little early instrumentation frida script that is supposed to spawn a process, then attach and create a simple script that lists all loaded modules, then wait for the user to press a key before resuming the process.

``` python
import frida
import sys, time

pid = frida.spawn(["/bin/ls", "-l"])
print("attach to pid " + str(pid))
session = frida.attach(pid)

script = session.create_script("""
var mod = Process.enumerateModulesSync();
var modLen = mod.length;
for (var i = 0; i < modLen; i++) {
    send("[+] module: " + mod[i]['name']);
}
""")

def on_message(message, data):
    if message['type'] == 'send':
        print(message['payload'])

script.on('message', on_message)
script.load()

sys.stdin.read(1)
frida.resume(pid)
```

On Linux 64 bits and Windows XP 32 bits, this works perfectly fine with frida 7.0.2 (from pip), which is an older version I happened to have.
However, with frida updated to latest 7.3.2 (from pip as well), it does not work:
- On windows XP, the instrumented process crashes before I even get the list of modules. I'm left with the "program.exe has encountered a problem and needs to close" window
- On Linux, I get the list of modules but the process seems to crash afterwards as I never get the `ls -l`output

This is the Windows output with 7.3.2 (+ process encountered problem window):

```
C:\Documents and Settings\Demo>python dga-instru.py
attach to pid 3788
Traceback (most recent call last):
  File "dga-instru.py", line 16, in <module>
    """)
  File "C:\Python27\lib\site-packages\frida\core.py", line 175, in create_script

    return Script(self._impl.create_script(*args, **kwargs))
frida.TransportError: the connection is closed
```

This is the Windows output with 7.0.8:

```
C:\Documents and Settings\Demo>python dga-instru.py
attach to pid 3240
[+] module: testdga.exe
[+] module: ntdll.dll
[+] module: kernel32.dll
[+] module: ADVAPI32.DLL
[+] module: RPCRT4.dll
[+] module: Secur32.dll
[+] module: msvcrt.dll
[+] module: frida-agent-32.dll
[+] module: DNSAPI.dll
[+] module: WS2_32.dll
[+] module: WS2HELP.dll
[+] module: ole32.dll
[+] module: GDI32.dll
[+] module: USER32.dll
[+] module: WINMM.dll
[+] module: SHELL32.dll
[+] module: SHLWAPI.dll
[+] module: PSAPI.DLL
[+] module: IMM32.DLL
[+] module: comctl32.dll
[+] module: comctl32.dll

[...cut: expected output from instrumented program...]
```

What could explain the difference of behaviour ?
Thanks

**Comment by oleavr** [comment]
Hey,

Thanks for reporting. This is definitely a regression. Would you mind trying different releases to try to narrow this down? Very curious to know if the last version before 7.3.0 works, or the regression happened earlier.

Cheers!

**Comment by flop01** [comment]
Thanks for your prompt answer !
Sure, on both WinXP and Ubuntu 14.04 it's working upto Frida 7.0.11 and starts to fail from frida 7.1.0.

So problem looks to have happened on 7.1.0.

Regards

**Comment by oleavr** [comment]
Fixed in latest Frida 9.x.
