### ISSUE TITLE
求帮忙看看AttributeError: module 'frida' has no attribute 'Cancellable'

### ISSUE THREAD

**Issue by gtict112** [frida/frida#1652]
AttributeError: module 'frida' has no attribute 'Cancellable'     ##frida 112.6.9   frida-server-12.6.9-android-arm  这是什么原因

   self._reactor = Reactor(run_until_return, on_stop)
  File "/Users/kwing/Library/Python/3.7/lib/python/site-packages/frida_tools/application.py", line 559, in __init__
    self.io_cancellable = frida.Cancellable()
AttributeError: module 'frida' has no attribute 'Cancellable'
Exception ignored in: <function Reactor.__del__ at 0x108db5d90>
Traceback (most recent call last):
  File "/Users/kwing/Library/Python/3.7/lib/python/site-packages/frida_tools/application.py", line 565, in __del__
    self._ui_cancellable_fd.release()
AttributeError: 'Reactor' object has no attribute '_ui_cancellable_fd'
t88888:FridaContainer kwing$ frida --v
12.6.9

**Comment by oleavr** [comment]
This means you have leftovers from an old version of Frida. Carefully review each directory on your Python's `sys.path` to find the file(s) to delete.
