### ISSUE TITLE
Frida on Windows 10 can't see a process

### ISSUE THREAD

**Issue by endrin** [frida/frida#1656]
I'm trying to run a simple script on Windows against a certain process, the script looks like this:
```py
import frida

try:
    session = frida.attach(<either process name or id>)
    session.detach()
    print("Attached and detached!")
except Exception as err:
    print(f"failed even to attach: {err}")
```

However, when I'm trying to pass process name to `attach` call, I'm getting an "unable to find process with name '..." error. When I'm trying to pass pid to it (copied from Task Manager), I'm getting a "unable to access process with pid ... from the current user account".

So I'd like to ask, how it's even possible? Is there a way for an app to actively hide itself from Frida and how it can be bypassed? Or am I just making a mistake somewhere?

frida-ps is not showing this process as well. Looks like Task Manager is the only one knowing about it.

**Comment by Manouchehri** [comment]
@endrin Do you mind sharing what the solution was?

**Comment by endrin** [comment]
@Manouchehri in my case, the target application used [PPL](https://www.crowdstrike.com/blog/evolution-protected-processes-part-1-pass-hash-mitigations-windows-81/) to hide itself from debuggers. So it wasn't Frida's fault.

**Comment by Kasi** [comment]
On windows11, try to run frida with administrator privileges. For example, run cmd with administrator privileges, and then use frida in cmd.
