### ISSUE TITLE
Java.choose throws invalid instruction

### ISSUE THREAD

**Issue by Iorpim** [frida/frida#1672]
Whenever I use _Java.choose_ I get an Invalid Instruction exception.

Android version: 5.1.1
Frida version: 14.2.13

Simple hook:
```java
Java.perform(function() {
    console.log("[ * ] Starting implementation override...")
    Java.choose("com.example.Class" , {
        onMatch : function(instance){
          console.log("Found instance: "+instance);
        },
        onComplete:function(){}
    });
}
```

![image](https://user-images.githubusercontent.com/22481687/112396574-23bb3880-8cdf-11eb-9514-4bcb71e380d6.png)

Should I be doing something different?

**Comment by samye465072111** [comment]
I have the same problem~

**Comment by samye465072111** [comment]
i use the version of 12.8.10 can  solve this problem

**Comment by Iorpim** [comment]
Tried to downgrade, unfortunately it did not fix the issue for me.
