### ISSUE TITLE
Unable to frida-trace on jailbroken device

### ISSUE THREAD

**Issue by une-petite-laitue** [frida/frida#1673]
Hi there,

I'm running frida-trace version **14.2.13** against an **A13** device running **iOS 14.3**, jailbroken using **unc0ver 6.1.1**. I have a developer disk image mounted on the device, so `frida-ps -U` is working as expected.

However, when I try `frida-trace -U <app-name>`, I get the following error:

`Failed to attach: need Gadget to attach on jailed iOS; its default location is: <path>`

My understanding is that Gadget is only required when running Frida against a jailed device; this device is not jailed, so Frida should be able to inject without issue.

Is there any way I can help guide Frida to acknowledge the fact that the device is jailbroken, and that it ought to proceed accordingly?

**Comment by oleavr** [comment]
Hey,

This typically means the frida-server is unable to run on the iOS side, so Frida on the host side assumes the device isn't jailbroken. Please upgrade to 14.2.14 on both sides, which should resolve this issue.

Cheers!
