### ISSUE TITLE
Unable to install 7.3.5 on IOS

### ISSUE THREAD

**Issue by vmsv** [frida/frida#168]
I'm trying to install version 7.3.5 on IOS and Cydia is report errors after the "Preparing frida"
The errors are:
failed in buffer_write(fd)(8 ret=-1)
Sub-process /usr/libexec/cydia/cydo returned an error code (1)

I'm running iOS 9.3.3 jailbroken with Pangu.

**Comment by piaoapiao** [comment]
you can delete some file,especailly "/" directory.

**Comment by rustymagnet3000** [comment]
I had the same issue.  I solved it by moving the entire Linguistics Data folder from System/Library to Var/Mobile.

**Comment by rustymagnet3000** [comment]
Upgrade to the new Frida client on your device and machine (version 8+).

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
