### ISSUE TITLE
Where do I get the latest executable.

### ISSUE THREAD

**Issue by MariasStory** [frida/frida#169]
Hi.

I really like the tool. I would like to do some debugging on windows, but I could not find the latest "frida-trace.exe". In the compiled folders, that you refer, I find "frida-server.exe".

1) Should I use frida-server? After few fast attempts I could not figure how to use it.
2) Where are the latest compilations of the frda tools?

**Comment by MariasStory** [comment]
Ping.

**Comment by oleavr** [comment]
Hi,

The recommended way is to install the latest version through pip or easy_install, e.g.:

`pip install frida`

You can also find other binaries at https://github.com/frida/frida/releases.

**Comment by oleavr** [comment]
Sorry for the delay btw. Feel free to drop by #Frida on FreeNode.

**Comment by thebigsmileXD** [comment]
Sorry for bumping this old issue, but i have no internet connection at home, is there a way to download the application via mobile? Which files would be needed?
