### ISSUE TITLE
Failed injecting frida gadget on non rooted android 10

### ISSUE THREAD

**Issue by nourmehdi** [frida/frida#1697]
I'm trying to inject frida gadget by system.Loadlibrary("frida-gadget"), to an application , on my galaxy s9+ android 10 non rooted phone .
Injection made into the public constructor of the MainActivity of the App , rebuild of the smali code successfull , signed by uber apksign , without errors . 

On application launch , adb  logcat shows   "  6831  6831 D ApkSoSource: not allowing consideration of lib/arm64-v8a/libfrida-gadget.so: deferring to libdir" .
 
Tried frida gadget android version 14.2.4 , 14.2.3 , 12.8.6 , arm64-v8a without success . Any idea about this ?

**Comment by oleavr** [comment]
There is no longer any need to repackage the app – latest Frida is able to inject frida-gadget dynamically through JDWP.

**Comment by navaneeth-dev** [comment]
Can you elaborate? How to do this? @oleavr
