### ISSUE TITLE
classnotfound when spawn

### ISSUE THREAD

**Issue by Gunkkk** [frida/frida#1699]
I have no idea why when i spawn some app, some class or methods can not be found, but totally different when i start the app and then attach it.
Thanks!

`Error: java.lang.ClassNotFoundException: Didn't find class "com.tencent.smtt.sdk.WebView" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /product/lib64, /system/lib64, /vendor/lib64, /product/lib64]]

**Comment by owen800q** [comment]
If the app is multi process, when you enumerated classes and methods,
You need to change class loader
I believe this is the root cause

**Comment by Gunkkk** [comment]
> If the app is multi process, when you enumerated classes and methods,
> You need to change class loader
> I believe this is the root cause

 WOW, it helps me a lot  as im a fresh man. However, it occurs that i cannot spawn the app with script like that,
and do u have som ideas?
Thanks! 
```Java.perform(function () {
    Java.enumerateClassLoaders({
    "onMatch": function(loader) {
        console.log(loader+'\n');
        Java.classFactory.loader = loader;
        loadclasses()
    },
    "onComplete": function() {
        console.log("success");
    }
});
});
```
summary="java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.LoadedApk.getHwReceiverResource()' on a null object reference"

**Comment by Gunkkk** [comment]
> > If the app is multi process, when you enumerated classes and methods,
> > You need to change class loader
> > I believe this is the root cause
> 
> WOW, it helps me a lot as im a fresh man. However, it occurs that i cannot spawn the app with script like that,
> and do u have som ideas?
> Thanks!
> 
> ```
>     Java.enumerateClassLoaders({
>     "onMatch": function(loader) {
>         console.log(loader+'\n');
>         Java.classFactory.loader = loader;
>         loadclasses()
>     },
>     "onComplete": function() {
>         console.log("success");
>     }
> });
> });
> ```
> 
> summary="java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.LoadedApk.getHwReceiverResource()' on a null object reference"

It goes ok when i resume before load script, It seems that the app cannot be hook before it has totally started,right? But it do be conflict with the spawn function, or just i use it wrong ,such as i cant use the enumerateClassLoaders before resume?
Anyway, thanku!
