### ISSUE TITLE
Unable to connect on Android: Error sending data: Broken pipe

### ISSUE THREAD

**Issue by mhelwig** [frida/frida#170]
I'm having issues connecting my rooted android phone (Nexus 4, version 5.1.1) to frida.

Starting frida-server on the rooted devices I get:

```
root@mako:/data/local/tmp # ./frida-server                                     
WARNING: linker: ./frida-server: unused DT entry: type 0x6ffffffe arg 0x44098
WARNING: linker: ./frida-server: unused DT entry: type 0x6fffffff arg 0x2
```

Running `frida-ps -U` results in:

```
root@sixtyseven:~# frida-ps -U
Failed to enumerate processes: unable to connect to remote frida-server: Error sending data: Broken pipe
```

and also stops the server process on the device:

```
root@mako:/data/local/tmp # ps ax
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME
[1] + Stopped (signal)     ./frida-server 
```

Any ideas on how to get this running? Server version is 7.3.1 and frida latest from pip (7.3.6 for frida-ps)

Thanks for input!

EDIT: I noticed that I do get a connection to frida-server when I do not run frida-server on the device as root but as shell. However, in this case frida-ps only lists frida-server as process (and there is an error about SELinux policy), so its not really useful.

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
