### ISSUE TITLE
NativeFunction Crashes on iOS

### ISSUE THREAD

**Issue by natashenka** [frida/frida#1715]
I'm trying to call a function in WhatsApp on iOS, but it crashes with: "access violation accessing 0x22d60". Most functions I try to call in the same binary have the same problem. I can hook them using Interceptor.attach, so they get hooked correctly and I can verify the parameters, but calling the same functions causes a crash.

A sample function that causes this problem is:

```
_text:0000000100AC90EC sub_100AC90EC                           ; CODE XREF: sub_100A7C604:loc_100A7C6F8↑p
__text:0000000100AC90EC                                         ; sub_100A7C604+194↑p
__text:0000000100AC90EC
__text:0000000100AC90EC arg_0           =  0
__text:0000000100AC90EC arg_12          =  0x12
__text:0000000100AC90EC arg_50          =  0x50
__text:0000000100AC90EC arg_60          =  0x60
__text:0000000100AC90EC arg_70          =  0x70
__text:0000000100AC90EC arg_80          =  0x80
__text:0000000100AC90EC
__text:0000000100AC90EC ; FUNCTION CHUNK AT __text:0000000100A7CFB4 SIZE 00000148 BYTES
__text:0000000100AC90EC ; FUNCTION CHUNK AT __text:0000000100AA50E0 SIZE 00000008 BYTES
__text:0000000100AC90EC
__text:0000000100AC90EC                 MOV             X0, X19
__text:0000000100AC90F0                 MOV             X1, X22
__text:0000000100AC90F4                 B               loc_100A7CFB4



text:0000000100A7CFB4 loc_100A7CFB4                           ; CODE XREF: sub_100AC90EC+8↓j
__text:0000000100A7CFB4                 MOV             X2, X30
__text:0000000100A7CFB8                 BL              sub_100AA663C
__text:0000000100A7CFBC                 MOV             X30, X2
__text:0000000100A7CFC0                 STP             X29, X30, [SP,#arg_80]
__text:0000000100A7CFC4                 ADD             X29, SP, #arg_80
__text:0000000100A7CFC8                 ADRP            X8, #___stack_chk_guard_ptr@PAGE
__text:0000000100A7CFCC                 LDR             X8, [X8,#___stack_chk_guard_ptr@PAGEOFF]
__text:0000000100A7CFD0                 LDR             X8, [X8]
__text:0000000100A7CFD4                 STUR            X8, [X29,#-0x38]
__text:0000000100A7CFD8                 BL              sub_100AB4070
```

I'm using an iPhone SE.

I'm creating the NativeFunction using:

var change_relay = new NativeFunction(w.base.add(0xAC90EC), 'void', ['pointer', 'pointer', 'pointer'];

The crash appears to occur before the parameters are used, and if I try changing all parameters to 0x77777777, the address of the crash does not change.

**Comment by NewDwarf** [comment]
Maybe WhatsApp has integrity protection checks?
The "Interceptor" API causes image modification of the loaded module in RAM. This can be detected by the integrity checks.
As an option, you can try to attach the debugserver to the app (if a device is jailbroken), connect to the debugserver by lldb, and set the software breakpoint (also modifies the runtime image in RAM) at the same location (with the 0xAC90EC offset). If this will cause the similar crash, more likely, it is because of the integrity checks.

**Comment by natashenka** [comment]
No, I'm able to set a breakpoint at this location in lldb.

**Comment by natashenka** [comment]
Sorry, this project is long finished and binary is long gone, so closing
