### ISSUE TITLE
Incompatible gadget version

### ISSUE THREAD

**Issue by 0x00-0xFF** [frida/frida#172]
After upgrading to frida 7.3.6 I cannot use the FridaGadget.dylib in ios apps:
Failed to enumerate processes: unable to communicate with remote frida-server; pease ensure that major versions match and that the remote Frida has the feature you are trying to use

**Comment by v4if** [comment]
have you solved?

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
