### ISSUE TITLE
failed to spawn a app on macOS

### ISSUE THREAD

**Issue by xietao1233** [frida/frida#1732]
frida version: 14.2.18

--------------------------------------
let num = await device.spawn('/Applications/Safari.app');

Error: Unable to spawn executable at '/Applications/Safari.app': No such file or directory

**Comment by xietao1233** [comment]
device.spawn('/Applications/Safari.app/Contents/MacOS//Safari');

**Comment by xietao1233** [comment]
device.spawn('/Applications/Safari.app/Contents/MacOS//Safari');

**Comment by eric-gitta-moore** [comment]
I think I still have a problem here

```
Error: Unable to spawn executable at '/Applications/Safari.app/Contents/MacOS/Safari': Undefined error: 0
```
