### ISSUE TITLE
Failed to spawn: unexpectedly timed out while waiting for app to launch on Android 11 Device

### ISSUE THREAD

**Issue by goldjpg** [frida/frida#1737]
On my redmi note 8 pro with dot os android 11 get get the following error with latest frida:

E:\> frida -U -f com.whatsapp --no-pause -l .\agent.js
     ____
    / _  |   Frida 14.2.18 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch

The app on the phone starts but the command line shows timeout a timeout error.

**Comment by zero-829** [comment]
i have same problem with android 10

**Comment by goldjpg** [comment]
I fixed it by lowering selinux to permissive. After that Frida is running perfectly.

**Comment by forgottor** [comment]
> I fixed it by lowering selinux to permissive. After that Frida is running perfectly.

hello how to lowering selinux to permissive， i set  “setenforce 0”，but it not work

**Comment by goldjpg** [comment]
> > I fixed it by lowering selinux to permissive. After that Frida is running perfectly.
> 
> hello how to lowering selinux to permissive， i set “setenforce 0”，but it not work

I am not an expert but you could try to inject the script with frida-inject on android. If there is any error you should see it in console.
