### ISSUE TITLE
Not allowed outside Java.perform() callback?

### ISSUE THREAD

**Issue by c4242** [frida/frida#174]
The following has been suggested to me by someone else should work.

```
import frida
import sys

def print_message(a, b):
    print str(a)
    print str(b)

proc = sys.argv[1]
script_d = open(sys.argv[2], "r").read()
pid = frida.get_usb_device().spawn([proc])
session = frida.get_usb_device().attach(pid)
script = session.create_script(script_d)
script.on("message", print_message)
script.load()
```

The script is just empty (but I've also tried a non-empty script that should work):

```
Java.perform(function () {
    console.log("Test");
});
```

I get the following error (e.g. when trying to start org.mozilla.firefox):

```
{u'columnNumber': 23, u'description': u'Error: Not allowed outside Java.perform() callback', u'fileName': u'gumjs-java.js', u'lineNumber': 133, u'type': u'error', u'stack': u'Error: Not allowed outside Java.perform() callback\n    at assertCalledInJavaPerformCallback (gumjs-java.js:133:23)\n    at Runtime.get [as androidVersion] (gumjs-java.js:118:21)\n    at getArtMethodSpec (gumjs-java.js:3117:78)\n    at Function.replaceArtImplementation [as implementation] (gumjs-java.js:1297:43)\n    at Function.set [as implementation] (gumjs-java.js:1128:55)\n    at vm.perform (gumjs-java.js:267:46)\n    at VM.perform (gumjs-java.js:2110:17)\n    at Runtime.perform (gumjs-java.js:259:24)\n    at script1.js:1:6'}
None
```

Is this an issue with Frida or just a user mistake? Sorry if the latter case is true. I don't see what the problem is.

**Comment by enovella** [comment]
Hi all,

I just updated Frida from 7.1.3 to 8.0.3 and I am experimenting the same issue today. What it is weird is that the hooks I am working with were working smoothly in Frida 7.x.x (Android 4.4.4 Dalvik VM)

The error is when I do some casting (getIV function) outside of Java.perform():
`[!] Received: [Cipher.init(mode,key,parametersSpec): ]
[!] Received: [Mode:]
[!] Received: [ENCRYPT_MODE(1)]
[!] Received: [Key:]
[!] Received: [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
[!] Received: [AlgorithmParameterSpec:  (IV)]
[!] Received: [{u'columnNumber': 23, u'description': u'Error: Not allowed outside Java.perform() callback', u'fileName': u'gumjs-java.js', u'lineNumber': 133, u'type': u'error', u'stack': u'Error: Not allowed outside Java.perform() callback\n    at assertCalledInJavaPerformCallback (gumjs-java.js:133:23)\n    at Runtime.use (gumjs-java.js:314:13)\n    at getIV (script1.js:50:58)\n    at Cipher.cipher.init.overload.implementation (script1.js:229:27)\n    at init (eval at implement (gumjs-java.js:1556:13), <anonymous>:1:260)'}]`

I will check it out along today to see what is happening. 

Cheers

**Comment by enovella** [comment]
Hi again,

I have downgraded Frida from 8.1.0 to 7.1.4 and my old hooks are working fine:

```
[!] Received: [Cipher.init(mode, key, parametersSpec): ]
[!] Received: [Mode:]
[!] Received: [DECRYPT_MODE(2)]
[!] Received: [Key:]
[!] Received: [E64389C45A5CC10157EBE11052562C23]
[!] Received: [AlgorithmParameterSpec:  (IV)]
[!] Received: [1755EDC583F5F87770D2265343A3A13F]
```

Let us see what it is going on.  I would like to use the latest Frida version :)

Cheers,
   Edu

**Comment by c4242** [comment]
Thanks for the replies, I was worried it was some silly user mistake. What commit did you use to get to 7.1.3? I cannot find any pre-built older binaries available.

**Comment by enovella** [comment]
Try using pip:
`sudo pip install frida==7.1.4`

**Comment by c4242** [comment]
I tried that before posting but I'm assuming the server side Frida version must match the client side version. If I'm using 8.1.1 on the server and 7.1.4 on the client I get this error:

```
  File "/usr/lib64/python2.7/site-packages/frida/core.py", line 84, in spawn
    return self._impl.spawn(argv)
frida.TransportError: no such interface 're.frida.HostSession7' on object at path /re/frida/HostSession

```

**Comment by enovella** [comment]
Yeah. Both binaries must have the same version. I think I am using `frida` 7.1.4 and `frida-server` 7.1.3 if I recall correctly.

**Comment by c4242** [comment]
But did you compile it from the git repo or did you get a binary from somewhere? If from the repo, then what commit did you build, if the latter, could you share where you got it?

**Comment by enovella** [comment]
Hi,

I have been storing on my HDD several versions of `frida-server arm32` for a while. You never know :) I will upload it to somewhere tomorrow.

Cheers

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
