### ISSUE TITLE
frida is not running on my phone

### ISSUE THREAD

**Issue by xcapri** [frida/frida#1745]
Hello, sir,

https://infosecwriteups.com/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29

i'm trying this, while running command
D:\APK\platform-tools>adb shell getprop ro.product.cpu.abi

arm64-v8a ( i got this response )
so can you tell me which firda server is suitable for my cellphone?

Previously I compared the Frida version as in the tutorial, but I got an error like : 

D:\APK\platform-tools>adb shell /data/local/tmp/frida-server &
/system/bin/sh: /data/local/tmp/frida-server: not executable: 32-bit ELF file

i use Redmi Note 5A

Thanks.

**Comment by xiaokanghub** [comment]
please download the version of ARM64 for frida server on Android platform  
https://github.com/frida/frida/releases/download/14.2.18/frida-server-14.2.18-android-arm64.xz

**Comment by securi3ytalent** [comment]
please download the version of ARM64 for frida server on Android platform
https://github.com/frida/frida/releases/download/14.2.18/frida-server-14.2.18-android-arm64.xz

not working

**Comment by securi3ytalent** [comment]
its work me

https://github.com/frida/frida/releases/download/16.2.1/frida-server-16.2.1-android-x86.xz
