### ISSUE TITLE
Android 11，frida-server can`t run

### ISSUE THREAD

**Issue by forgottor** [frida/frida#1757]
mars:/data/local/tmp # ./frida-server-12.9.8-android-arm64
libsepol.policydb_read: policydb version 31 does not match my version range 15-30
Unable to load SELinux policy from the kernel: unsupported policy database format

mars:/data/local/tmp # ./frida-server-14.2.17-android-arm64
{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:170:1)\n    at Jt (frida/node_modules/frida-java-bridge/lib/android.js:945:1)\n    at zt.activate (frida/node_modules/frida-java-bridge/lib/android.js:998:1)\n

**Comment by toraidl** [comment]
I have encountered the same issue.
Is there any method to sovle this?

**Comment by pavlukivan** [comment]
same here
