### ISSUE TITLE
Loading library and calling android native method - Error: access violation accessing 0xXXXXXXXXXXXXXX

### ISSUE THREAD

**Issue by Progress1** [frida/frida#1764]
I try load native dll and call some function from it.

```
function LoadLib(){
    var mod = Module.load("/data/app/com.app/lib/arm64/libnative-lib.so");
    console.log("Module info: \n" + JSON.stringify(mod));
    var modBase = mod.base;
    console.log("lib base address: " + modBase);
    var expAddr = Module.findExportByName("libnative-lib.so", "My_Fun")
    console.log("Export address: " + expAddr);
    var myFun = new NativeFunction(expAddr, "pointer", ["pointer"])
    var buf = Memory.allocUtf8String("abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd")
    var ret = myFun(buf);    <<<<<< here we crash
    console.log("Ret:", ret); 
}
```
Output:

```
Module info:
{"name":"libnative-lib.so","base":"0x7e7eaa2000","size":2977792,"path":"/data/app/com.app/lib/arm64/libnative-lib.so"}
lib base address: 0x7e7eaa2000
Export address: 0x7e7eb708e4
Error: access violation accessing 0x636261646367b9
    at LoadLib (/LoadLibrary.js:30)

```

Called from APK (smali):
`invoke-virtual      Info->MyFun([B)String, v0, p1
`

Definition in APK (smali)
```
.method public final native MyFun([B)Ljava/lang/String;
.end method
```

I think the problem is maybe in wrong parameter definition. From APK we sending **byte[]**,  in Frida i define **pointer** where i send **allocUtf8String** variable ... Return value is **String**. Maybe i should define byte array with other way?

I try also send ByteArray, but the error was the same.
```
var b = Memory.alloc(3);
b.writeByteArray([0x02, 0x89, 0x7F]);

```
Any clues? Thank you.

Tested on latest versions, Windows 10 x64, Android 10 arm64,

**Comment by 0xXA** [comment]
> Any clues? Thank you.
show me the definition of that native routine
if the parameter is of type **char *** then specifying 'pointer' as argument type is correct way to do it and as you have mentioned that this routine returns a String ( a pointer to first element in it ) so return type is also correct.

**Comment by Progress1** [comment]
At the end i solve it with different way (live hooking, no load). Thank you for you reply.
