### ISSUE TITLE
hexdump stuck

### ISSUE THREAD

**Issue by joshuachenn** [frida/frida#1765]
When using console log hexdump data, seems like when data is too large and some downloader can't hold it, frida becoming stuck and not log anything and then frida-server died, need disconnect device and restart frida-server.

**Comment by H0r53** [comment]
Can you give an example of how you are doing a hexdump? Clearly dumping too much data can cause access errors and seg faults, so you should minimally be certain that the data you are dumping is within a single memory segment.

**Comment by joshuachenn** [comment]
I'm using hexdump to dump received data from `recv` function, data pointer takes from `recv`'s parameter, and data length is the `recv`'s return value. But frida get stuck just last few hours, and then everything was getting well...so weired.
Here is my code:
```c
    Interceptor.attach(recv_addr, {
        onEnter: function (args) {
            this.pdata = parseInt(args[1])
            this.socket = args[0]
        }, onLeave: function (retVal) {
            if (parseInt(retVal) != 0xffffffff && parseInt(retVal) > 0) {
                console.log('[+] ---------------------RECV BEGIN--------------------- [+]')
                console.log('[+] socket:0x' + parseInt(this.socket).toString(16) + ' len:' + retVal)
                console.log(hexdump(ptr(this.pdata), {length:parseInt(retVal), ansi:false}))
                console.log('[+] ---------------------RECV END--------------------- [+]')
            }
        }
    })
