### ISSUE TITLE
How to build old version like 12.11.8

### ISSUE THREAD

**Issue by q447552640** [frida/frida#1766]
Since version 14 is released ,there is a lote of things can't find in build.frida.re.

Because of I'm using a ject iphone se with ios 10.13,the new version will cause ios reboot .

So I had to use a old verion deb which is 12.11.8

And I'm not able to fix the 14 verions crashed bug.

I want to build a the old version tools and deb ,so that the iphone can client to my python script server port.

but when I download the Old 12.11.8 tag,the releng porject point to two sdk is 404.

https://build.frida.re/toolchain-20200518-windows-x86.exe

https://build.frida.re/sdk-20200518-windows-any.exe

How to continue?

**Comment by oleavr** [comment]
I'm afraid that isn't easy, and would require a lot of software archeology to figure out exactly which versions were used to build those old dependencies. We do have a better system in place now, though, so in the future it will be possible to build old versions – but those releases are from before I fixed that system. Sorry!

**Comment by q447552640** [comment]
> I'm afraid that isn't easy, and would require a lot of software archeology to figure out exactly which versions were used to build those old dependencies. We do have a better system in place now, though, so in the future it will be possible to build old versions – but those releases are from before I fixed that system. Sorry!

Thanks bro.I update my device. And New Version is Wondfull!!
