### ISSUE TITLE
getting error while ruuning frida command

### ISSUE THREAD

**Issue by stish834** [frida/frida#1769]
getting 
![Screenshot 2021-07-09 00:41:24](https://user-images.githubusercontent.com/31948359/124977981-d032e780-e04e-11eb-8d5c-fb99fce915e4.png)
 error while running this code

frida -U -f com.* -l fridaroot.js --no-pause

error

failed to spawn: command failed: 99

Thanks fix this soon

**Comment by Xeon8297** [comment]
for me its "Failed to spawn: unable to start helper"

**Comment by vipertje** [comment]
> 
> 
> for me its "Failed to spawn: unable to start helper"

Upgraded from v14.2.18 to v15.0.2 and getting the same message. Objection downloaded new gadget and I also upgraded frida to match the version

**Comment by oleavr** [comment]
Sorry, these error-message are quite misleading – what's actually wrong here is that the local and remote Frida versions don't match. So if e.g. Objection uses the Frida v14 Python bindings, but the remote frida-server/frida-gadget is v15 (or vice versa), then they won't be able to communicate.
