### ISSUE TITLE
Failed to spawn: command failed: 99

### ISSUE THREAD

**Issue by royz** [frida/frida#1771]
I am trying to bypass SSL pinning for an android app. I am running `frida -U -l unpin.js -f com.example.app`. The app is launched on the Genymotion Virtual machine but then I get the following error:

``` 
     ____
    / _  |   Frida 15.0.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to spawn: command failed: 99
```

**Comment by zarkin404** [comment]
i got the same issue after i update to 15.x, the command i run is `frida -H ip:port -l script.js --no-pause -f com.example.app`

```
     ____
    / _  |   Frida 15.0.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to spawn: connection closed
```

**Comment by zarkin404** [comment]
> i got the same issue after i update to 15.x, the command i run is `frida -H ip:port -l script.js --no-pause -f com.example.app`
> 
> ```
>      ____
>     / _  |   Frida 15.0.2 - A world-class dynamic instrumentation toolkit
>    | (_| |
>     > _  |   Commands:
>    /_/ |_|       help      -> Displays the help system
>    . . . .       object?   -> Display information about 'object'
>    . . . .       exit/quit -> Exit
>    . . . .
>    . . . .   More info at https://frida.re/docs/home/
> Failed to spawn: connection closed
> ```

i found that i run the frida-server with wrong architecture which should be arm64 while i run an android-x86_64 version. 😂

after i replaced the proper version everything works fine.

**Comment by oleavr** [comment]
This error message is confusing (and we should improve that) – but what's happening here is that it's failing to connect to a remote frida-server, so it tries the experimental "non-rooted" code-path, which isn't yet compatible with a very broad range of devices, and fails in ways such as this one. (`command failed: 99`)
