### ISSUE TITLE
inject frida-gadget into android apk,unable to connect to remote frida-server

### ISSUE THREAD

**Issue by xyxdaily** [frida/frida#1775]
when I rebuild frida-gadget.so whos default port is 27043,"frida -U -n Gadget" or "frida -U -p pid" and others do not work on me. How can I connect ?

**Comment by oleavr** [comment]
Make sure the remote frida-server is 15.x as well – both ends need to have the same major version. (Ideally they should both be the same latest version.)

**Comment by 0x1shyboy1** [comment]
yeah, I have the same problem in 15.0.8. If I switch back to the 14.2.18 version, everything will be normal

**Comment by layerlre** [comment]
I have the same problem in frida-server/frida-gadget 15.0.8
