### ISSUE TITLE
inlinehook for arm64

### ISSUE THREAD

**Issue by flycrane** [frida/frida#178]
Hi,

I was wondering where the inlinehook code for arm64 is? grepped the whole tree but no luck. 
Appreciate for any hint pls.

Thank you.

**Comment by oleavr** [comment]
Hi,

You can find it [here](https://github.com/frida/frida-gum/blob/5c234b790177ed3a6c542f9bf5b42605ead258e9/gum/backend-arm64/guminterceptor-arm64.c#L249-L299).

Cheers!
