### ISSUE TITLE
Frida doesn't hook on rooted android anymore

### ISSUE THREAD

**Issue by bkerler** [frida/frida#1790]
OS: Android 6
Root-Type : non-magisk (root via system command)

Expected behaviour: Spawn an android app and hook a java function. 

Issue: 
On frida 15.0.x:
"need Gadget to attach on jailed Android; its default location is: /home/bjk/.cache/frida/gadget-android-arm64.so"

On frida <15.0.x, hooking works fine.

Is there a way to enforce the old behaviour, as it seems to have incorrectly detected a "jailed" Android ? Btw. the term for android is "rooted", not "jailbroken" as for iOS devices.

**Comment by bkerler** [comment]
Additional comment: Yes, the frida-server is being run as root, selinux is permissive. And no, there are no kernel modules like rkp.

**Comment by bkerler** [comment]
"chown root:root frida-server" fixed it.

**Comment by melon-masou** [comment]
I got similar results and I found that it is because I upgraded the frida-core, but forgot upgrading the frida-server to corresponding version.
