### ISSUE TITLE
How to Parse win type object when intercept

### ISSUE THREAD

**Issue by scruel** [frida/frida#1804]
According to the [MSDN website](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses), AdapterAddresses function has a parameter called AdapterAddresses, and its type is PIP_ADAPTER_ADDRESSES, so How can I parse it with Frida? How to modify the attributes of the object?

js code:
```
var _GetAdaptersAddresses = Module.findExportByName("Iphlpapi.dll", "GetAdaptersAddresses");
Interceptor.attach(_GetAdaptersAddresses, {
    onEnter: function(args) {
        console.log('_GetAdaptersAddresses');
        this.Family = args[0];
        this.Flags = args[1];
        this.Reserved = args[2];
        this.AdapterAddresses = args[3];
        // for (let i = 0; i < 2; i++) {
        //    this.AdapterAddresses.PhysicalAddress[i] += 0x10;
        //    console.log(args => PhysicalAddress[i]);
        // }
        this.SizePointer = args[4]
        console.log(Memory.readInt(args[4]));
    },
    onLeave: function(args) {
        console.log('AdapterAddresses : ' + this.AdapterAddresses);
        console.log(Memory.readInt(this.SizePointer));
        console.log('SizePointer : ' + this.SizePointer);
    }
})
```

**Comment by NewbieGoose** [comment]
As far as I know there is no interface for this currently (see https://github.com/frida/frida/issues/1099).
You might have to do this yourself for each struct. For example, if you would like to access and modify the value of `PhysicalAddressLength`.

```js
....
                this.AdapterAddresses = args[3];
	        console.log(`AdapterAddresses: ${this.AdapterAddresses}`)
	        console.log(`&(AdapterAddresses->PhysicalAddressLength): ${this.AdapterAddresses.add(0x58)}`)
	        var PhysicalAddressLength = this.AdapterAddresses.add(0x58).readU32();
	        console.log(`PhysicalAddressLength: ${PhysicalAddressLength}`)
                this.AdapterAddresses.add(0x58).writeU32(0x7);

....
```
I grabbed the offset `0x58` from a disassembler or you could calculate it yourself given the wanted [struct definition](https://docs.microsoft.com/en-us/windows/win32/api/iptypes/ns-iptypes-ip_adapter_addresses_lh) (which is harder and error prone IMO).

**Comment by scruel** [comment]
> 
> 
> As far as I know there is no interface for this currently (see #1099).
> You might have to do this yourself for each struct. For example, if you would like to access and modify the value of `PhysicalAddressLength`.
> 
> ```js
> ....
>                 this.AdapterAddresses = args[3];
> 	        console.log(`AdapterAddresses: ${this.AdapterAddresses}`)
> 	        console.log(`&(AdapterAddresses->PhysicalAddressLength): ${this.AdapterAddresses.add(0x58)}`)
> 	        var PhysicalAddressLength = this.AdapterAddresses.add(0x58).readU32();
> 	        console.log(`PhysicalAddressLength: ${PhysicalAddressLength}`)
>                 this.AdapterAddresses.add(0x58).writeU32(0x7);
> 
> ....
> ```
> 
> I grabbed the offset `0x58` from a disassembler or you could calculate it yourself given the wanted [struct definition](https://docs.microsoft.com/en-us/windows/win32/api/iptypes/ns-iptypes-ip_adapter_addresses_lh) (which is harder and error prone IMO).

Great work, I've done the same thing!
