### ISSUE TITLE
Error: access violation accessing 0xffffffffb4e49110

### ISSUE THREAD

**Issue by scruel** [frida/frida#1807]
Pointer.toInt32() function is not enough.

```
...
console.log(Pointer);
console.log(Pointer.toInt32());
console.log(Memory.readU32(ptr(Pointer.toInt32())));
...
```

Result:
```
0x2a9b4e49110
-1260089072
[{'type': 'error', 'description': 'Error: access violation accessing 0xffffffffb4e49110', 'stack': 'Error: access violation accessing 0xffffffffb4e49110\n    at <anonymous> (/script1.js:122)', 'fileName': '/script1.js', 'lineNumber': 122, 'columnNumber': 1}] => None
```

**Comment by xiaokanghub** [comment]
This is not a read-write address :)

**Comment by scruel** [comment]
> 
> 
> This is not a read-write address :)

Yep, cause the result of `toInt32()` function is negative.

**Comment by oleavr** [comment]
This isn't going to work, as it will clip the upper bits: `ptr(Pointer.toInt32())`. You should avoid turning the `NativePointer` into a JS number, as JS number is backed by `double`, which cannot represent all 64-bit pointer values. Instead, use the NativePointer methods such as `add()`, `sub()`, etc. If you need to get the value out to pass it to e.g. `BigInt` (JavaScript's built-in support for large integers), then you should use `toString()`.
