### ISSUE TITLE
Error: Unable to attach to debuggable app

### ISSUE THREAD

**Issue by test436** [frida/frida#1808]
Problem:
Frida is unable to attach to a debuggable iOS app on a **jailed** device

Setup:
Device: iPhone XR iOS 14.7
Frida 15.0.13 on macOS

Steps to reproduce:
- Create an empty iOS app with Xcode
- Launch it in debug mode on the device
- try to attach to it with` frida -U -n fooapp`

Result:
`Failed to attach: unable to attach to the specified process`

Next steps in case lldb of Xcode attached to the process was the problem
- stop the app 
- disconnect the usb cable 
- reconnect it
- open the app(it should still be debuggable)
- try  to attach to it with` frida -U -n fooapp`

Result:
`Failed to attach: connection closed`

**Comment by oleavr** [comment]
Is your Gadget up-to-date? E.g., on macOS, it's at: `~/.cache/frida/gadget-ios.dylib` – It's vital that it's of the same major version as your local version of Frida.

**Comment by test436** [comment]
yes it was that the problem, thank you!
