### ISSUE TITLE
Can't get className

### ISSUE THREAD

**Issue by Kaspek2480** [frida/frida#1811]
**Frida 15.0.13**

Hello, i'm trying to use 
`crypto.d.implementation = function (str, str2) {
      console.log("[*] Crypto ")

      console.log("[*] str: " + str)
      console.log("[*] str2: " + str2)
      var result = this.d(str, str2)
      console.log("[*] Result: " + result + " | " + result.$className)
      return result
  }`

But it not works, i'm getting `[*] Result: c9a4dd487ecc0c17f669230814544722ffde3916 | undefined`

What can be a issue?

**Comment by abevol** [comment]
try `result.getClass().getName()`
