### ISSUE TITLE
Hexdump Printing 256 Bytes Regardless Of Length Field

### ISSUE THREAD

**Issue by H0r53** [frida/frida#1818]
Within an attached Interceptor's `onEnter` and `onLeave` routines I am printing a hexdump of the arguments/return value. In the example below, args[0] is a pointer.

```
console.log(hexdump(args[0]), {
    offset: 0,
    length: 16,
    header: true,
    ansi: true
});
```

Regardless of what I set the `length` field to, 256 bytes are printed by Frida. This is quite annoying as it clutters my console with irrelevant data, making the analysis difficult. I am currently using Frida version 15.0.8. I'll see if updating to the latest version fixes the issue and update this issue afterwards.  
Please advise, thank you.

**Comment by H0r53** [comment]
I updated to the latest Frida version (15.0.15) and the issue remains. I've also verified it occurs outside of a Interceptor hook. If I simply hexdump an address in memory I consistently receive a 256 byte hexdump. Additional context: frida-server is running on Android arm64 and I'm instrumenting a process associated with an APK. In particular, I'm attempting to dump data from a shared object used by the APK via JNI. If I hexdump using the simple Frida examples (`hello` for instance) hexdump respects the `length` argument. However, regardless of the `length` argument given to the hexdump via frida-server, I always receive 256 bytes.

**Comment by H0r53** [comment]
Further insights: It isn't just the `length` field that isn't being recognized, but all of the hexdump options in my case (offset, length, header, ansi). Regardless of how I call the hexdump I receive a 256 byte dump with headers, ansi data, and offset 0.

**Comment by oleavr** [comment]
You're passing the options to `console.log()` instead of `hexdump()`.

Would recommend switching to TypeScript – it would have caught this error. Here's a teaser of the development experience: https://www.youtube.com/watch?v=9cr4gOPFN4o

Cheers!

**Comment by H0r53** [comment]
*facepalm* - Thank you Oleavr for catching this simple syntax issue.
