### ISSUE TITLE
Can not intercept the DLL function

### ISSUE THREAD

**Issue by zswaaa** [frida/frida#1819]
When i use frida to hook a function in 64-bits DLL on windows, I find that Frida can not intercept function at 00007FFF66A61010 in DLL.

I use the findExportByName to get the function address and send it to console, But when i attach it in script, I get  the error result .Here is my script.
![image](https://user-images.githubusercontent.com/25542253/130174071-6a62ee1c-30a4-4c9e-aaa4-29dbe5f69666.png)

I think maybe i get wrong address ,But when i print the address in inside of the exe, I get the same address as findExportByName analysing.
![image](https://user-images.githubusercontent.com/25542253/130174631-885b8a4a-dd65-43df-a51c-d3d629f0bce7.png)

![image](https://user-images.githubusercontent.com/25542253/130174875-3bfbda84-f55b-45d3-bfa4-8cf7e4119a2c.png)

So i was so confused with the error of the second pic, Why unable to intercept function at 00007FFF66A61010, I can not find the reason,  My exe application and DLL are all 64 bits.

And i find this in my add function.
![image](https://user-images.githubusercontent.com/25542253/130187067-f795fea7-9478-4a1c-8a52-a0eaeecf80f7.png)

Please help me or give me some advise, Thank u very much.

**Comment by zswaaa** [comment]
DLL compiling setting problem.

**Comment by commonuserlol** [comment]
@zswaaa i have a similar problem, could you share your solution?
