### ISSUE TITLE
Unable to Attach with frida 8.1.7 on Jailbroken iOS (9.3.3)

### ISSUE THREAD

**Issue by TheBananaStand** [frida/frida#182]
Confirmed that both frida-server and frida on my workstation are the same version (8.1.7) and working/running properly. Also confirmed that `frida-ps -U` worked correctly, and the appropriate PID was being pulled for the targeted package/application. However, whenever I attempt to attach, I get the following error.

`Traceback (most recent call last):`
`File "test.py", line 25, in <module>`
`session = frida.get_usb_device().attach(proc)`
`File "/usr/local/lib/python2.7/site-packages/frida/core.py", line 96, in attach`
`return Session(self._impl.attach(self._pid_of(target)))`
`frida.TransportError: the connection is closed`

**Comment by oleavr** [comment]
Any chance you could try older releases from http://build.frida.re/debs/ and narrow it down to one specific release where this broke? I no longer have a jailbroken 9.x device for testing, and this works fine on 8.x, so I'm unable to look into this for now.

**Comment by oleavr** [comment]
(But if you can help me narrow it down to one release it should be easy to fix.)

**Comment by TheBananaStand** [comment]
I've tried using versions 8.1.6 and 7.3.6 (both frida client on OSX and frida-server on iOS matching). Unfortunately, I received the same error message.

**Comment by oleavr** [comment]
Would you mind building Frida yourself, modifying config.mk to set `FRIDA_STRIP` to `no`? Having lldb attached when the crash happens should be helpful. I'm wondering if it is the target app that crashes, `frida-helper`, or `frida-server`.

**Comment by TheBananaStand** [comment]
Although this isn't a detailed bug report (apologies for that), I was able to resolve the issue. For some reason, the default deployment of frida-server from the Cydia repository isn't properly configured to interact with the frida client (at least out of the box). Additionally, I was unable to successfully kill frida-server from a shell on the device, as it would automatically restart. Once I removed the binary (and the repo), I pushed the frida-server binary from [here](https://github.com/frida/frida/releases/download/8.1.7/frida-server-8.1.7-ios-universal.xz) to the device and started manually using the `frida-server -l [listening interface IP]` command. Afterward, I was able to attach to any target process without any errors.

**Comment by oleavr** [comment]
@TheBananaStand That's strange. It should be listening on localhost:27042, which the host-side [Fruity](https://github.com/frida/frida-core/blob/master/src/fruity/fruity-host-session.vala) backend should be able to reach (it talks to usbmuxd). Which OS are you running on your host?

**Comment by oleavr** [comment]
@TheBananaStand Note that launching apps will not work if you run frida-server standalone. You need to run it through launchd with the proper configuration for that to work. (So I would recommend installing the .deb from Cydia and rather just tweak the .plist to add the `-l` switch if you need it to listen on other interfaces.

**Comment by TheBananaStand** [comment]
@oleavr Thanks for the direction, much appreciated. I was running the client on OS X (El Capitan) and tried running the standalone binary with the `-l` switch and without (defaulting to localhost:27042). I was able to connect from the client in both situations, but confirmed that the version installed from Cydia (.deb package) was unsuccessful.

**Comment by strano666** [comment]
Try to update to the 8.1.14
Now works with me!

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
