### ISSUE TITLE
Why you make frida-ps -U return all the process even if the frida-server is not running on the device ?

### ISSUE THREAD

**Issue by dummys** [frida/frida#1836]
Hi,

Can you remove this feature ? It's a bit problematic because a lot of tutorial on the internet state that to test if frida is working, just run `frida-ps -U` and in fact since frida 14.2.8 it works without any frida-server running on the device.
Thanks

**Comment by oleavr** [comment]
We support jailed/non-rooted instrumentation of debuggable apps. I agree it's bad usability though, but that's a bug in frida-tools in case you're interested in helping improve that. (There's now `device.query_system_parameters()` which has `access: 'jailed'` in such cases.)

**Comment by dummys** [comment]
thanks for your explanation. If I have time I will improve it for sure.
