### ISSUE TITLE
Frida-server fails to run successfully on physical device running Android 11

### ISSUE THREAD

**Issue by mrh1234** [frida/frida#1837]
This issue is probably related to #1788 and #1820.

### Frida-server
When running frida-server (version 15.0.19-arm64) on my rooted s21 ultra (Android 11 & fully updated), I get the following error message, without that the frida-server terminates. Also I get this error message for older frida version (e.g. 15.0.18 or 14.2.18):

`{"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:170:1)\n    at zt (frida/node_modules/frida-java-bridge/lib/android.js:945:1)\n    at Ut.activate (frida/node_modules/frida-java-bridge/lib/android.js:998:1)\n    at Gt.replace (frida/node_modules/frida-java-bridge/lib/android.js:1045:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1010:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:925:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at g._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)","fileName":"frida/runtime/core.js","lineNumber":170,"columnNumber":1}`

I tested the same frida-server binary also on a rooted galaxy s8 (Android 9) and there is no error message shown and everything works flawless, which I tested with simple hook scripts, that I also tried to run on the s21 ultra. So maybe this issue is caused by the Android version.

### Frida client

Now when I try to run a simple script, like the disableRoot script [(see here)](https://joshspicer.com/android-frida-1) for the UnCrackable Level1 challenge, I get this error message on the client side, which is probably the result of the failure of the frida-server:
`Error: VM::AttachCurrentThread failed: -1
    at o (frida/node_modules/frida-java-bridge/lib/result.js:4)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:25)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:14)
    at Xe (frida/node_modules/frida-java-bridge/lib/android.js:499)
    at Ie (frida/node_modules/frida-java-bridge/lib/android.js:195)
    at Ce (frida/node_modules/frida-java-bridge/lib/android.js:16)
    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:17)
    at g (frida/node_modules/frida-java-bridge/index.js:9)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:317)
    at call (native)
    at o (/_java.js)
    at <anonymous> (/_java.js)
    at <anonymous> (frida/runtime/java.js:1)
    at call (native)
    at o (/_java.js)
    at r (/_java.js)
    at <eval> (frida/runtime/java.js:3)
    at _loadJava (native)
    at get (frida/runtime/core.js:114)
    at <eval> (/disableRoot.js:1)
`

### Success for library function tracing and hooking
However, running frida-trace seems to work fine and hooking library functions works as well. Running this simple script works for example:
`Interceptor.attach(Module.getExportByName('libc.so', 'open'), { 
	onEnter(args) { 
		console.log('open entered successfully');
	}
});`

### Device and frida infos

-Rooted Samsung Galaxy S21 Ultra Exynos version (SM-G998B/DS)
-Android 11 
-Magisk Version 23 installed
-Tested frida-server versions: 15.0.19, 15.0.18, 14.2.18
-frida client versions were the same as the frida-server versions at the time of each test

**Comment by markslin** [comment]
I also encountered this problem, I tried version 14.2.13, it work.

**Comment by RealIndica** [comment]
Exact same thing. Hopefully theres a fix soon.

**Comment by mrh1234** [comment]
Everything works with Frida Server Version 15.1.1. (Frida client is version 15.1.1. as well). The error message is still thrown and displayed, however I can hook native and Java functions without problems. I did not test the newer versions.

**Comment by RealIndica** [comment]
> Everything works with Frida Server Version 15.1.1. (Frida client is version 15.1.1. as well). The error message is still thrown and displayed, however I can hook native and Java functions without problems. I did not test the newer versions.

Is your selinux set to permissive or enforced? Trying hard to get this to work on my S21 exynos but all the solutions are telling me to set selinux to permissive and i just keep running into to trouble when trying to build a custom kernel.
