### ISSUE TITLE
How to resume a Gadget connected to Portal

### ISSUE THREAD

**Issue by b1ueb1ues** [frida/frida#1839]
I find portal a great tool to use when I have to connect to multiple Gadget.

Portal_Client.py from example or frida-trace works very fine with Portal. 

But when I'm using Portal_Server.py with enable_spawn_gating. Either Portal_Client.py or frida-trace won't resume correctly. 

Was I miss something?
```
n_node_connected() 1 ('127.0.0.1', 56843)
on_node_joined() 1 Application(identifier="/system/bin/app_process64", name="app_process64", pid=13767, parameters={'system': {'arch': 'arm64', 'os': {'version': '9', 'id': 'android', 'name': 'Android'}, 'platform': 'linux', 'api-level': 28, 'access': 'full'}})
on_controller_connected() 2 ('127.0.0.1', 39948)
on_node_left() 1 Application(identifier="/system/bin/app_process64", name="app_process64", pid=13767, parameters={'system': {'arch': 'arm64', 'os': {'version': '9', 'id': 'android', 'name': 'Android'}, 'platform': 'linux', 'api-level': 28, 'access': 'full'}})
on_node_disconnected() 1 ('127.0.0.1', 56843)
on_controller_disconnected() 2 ('127.0.0.1', 39948)
```
I tried session.resume(), device.resume(pid),  both won't work.

**Comment by oleavr** [comment]
The issue is that every client that does `enable_spawn_gating()` must `resume()` each process for it to be allowed to continue. The `portal_server.py` example does not do this automatically.
