### ISSUE TITLE
Linker Warning

### ISSUE THREAD

**Issue by rotlogix** [frida/frida#185]
```WARNING: linker: ./frida-server: unused DT entry: type 0x6ffffffe arg 0x441dc```

Ultimately this prevents me from pulling the running processes from the device, and I am sure many other things.  This occurred on an Alcatel OneTouch running Android 5.1.1.

**Comment by oleavr** [comment]
@rotlogix Thanks for reporting! Fix should be coming soon.

**Comment by z6101681** [comment]
![default](https://cloud.githubusercontent.com/assets/15312660/20953610/e7eb002c-bc6f-11e6-9e6a-84648f153329.png)

Running on android 5.1.Can't not start the server.

**Comment by oleavr** [comment]
Linked warning turned out to be harmless. We'll ignore it for now.
