### ISSUE TITLE
Cannot call function on Android Gadget

### ISSUE THREAD

**Issue by RealIndica** [frida/frida#1860]
The entire gadget script :
```
var func_ptr = Module.findBaseAddress('libil2cpp.so').add('0xE28D8C')
var func = new NativeFunction(func_ptr, 'void', [])
func()
```

I feel this should definitely work. But instead it gives me this :
```
[SM G991B::gadget]-> Error: access violation accessing 0x0
    at <eval> (/a.js:3)
```

Any ideas what I could be doing wrong?

The function looks like this in DnSpy (il2cpp dumper dummy dll)
```
	[Token(Token = "0x60014BC")]
	[Address(RVA = "0xE28D8C", Offset = "0xE28D8C", VA = "0xE28D8C")]
	[Attribute(Name = "InjectAttribute", RVA = "0xC48C4C", Offset = "0xC48C4C")]
	public void Setup()
	{
	}
```

Thank you

(I am also very new to Frida, so I apologise if its something stupid)

**Comment by oleavr** [comment]
It looks like you're trying to call an instance method without passing the instance to call it on. You're also calling it from Frida's JavaScript thread instead of an application thread, which it may not be prepared for.

Cheers!

**Comment by jinghaifeng1** [comment]
How did you solve it?

**Comment by jinghaifeng1** [comment]
> It looks like you're trying to call an instance method without passing the instance to call it on. You're also calling it from Frida's JavaScript thread instead of an application thread, which it may not be prepared for.
> 
> Cheers!

oleavr，I can't find how to specify a thread to execute a NativeFunction from the documentation, can you teach me

**Comment by jinghaifeng1** [comment]
@oleavr
