### ISSUE TITLE
[Question] How to hook java static field and static filed's method?

### ISSUE THREAD

**Issue by lwintermelon** [frida/frida#1896]
Hello, thanks for this great tools. I hava some questions with hooking java, how to hook java field and filed's method?
see below code.

```java
// java code to be hooked
public class Build {
    private int uniqueId = 1; // how to hook field access and modify it.
    private static final String TAG = "Build";
    public static final Creator CREATOR; // how to hook static filed's method like Build.Creator.createFromParcel()
}
```

Though *static final* fields (constants) might be optimized 'away' at compile time, so we can only modify it when an application starts. (like TAG above).
[ADDED]: The following frida code describes what I want.

```js
// frida js code to hook above
const Build = Java.use('xx.Build');

// every time Build.uniqueId is accessed, the hook is called.
// you can even return different uniqueId for every access.
Build.uniqueId.hook = function(originalValue){
    return yourId;
}

// Creator is a static field of a class, to hook its method
Build.Creator.createFromParcel.implementation = function () {

}
```

By the way, where can we chat about frida except telegram, i join the irc but it seems that it's bridged from telegram and u guys can't see my messages.

**Comment by xiaokanghub** [comment]
```
var build = Java.use('xx.Build');
console.log(build.TAG.value);
```

**Comment by lwintermelon** [comment]
> ```
> var build = Java.use('xx.Build');
> console.log(build.TAG.value);
> ```

Of course I know how to use static field and set its value, it's well documented. I mean hook.
When original app access a static field, we intercept it, we can get the original value, modify it, or provide a new value based on context.

**Comment by cxapython** [comment]
Java.choose("'xx.Build'", {
            onMatch: function (x) {
                console.log("find instance :" + x);
                console.log("result of secret func:" + x.TAG.value);
            },
            onComplete: function () {
                console.log("end");
            }
        });

**Comment by lwintermelon** [comment]
> ```
> Java.choose("'xx.Build'", {
>             onMatch: function (x) {
>                 console.log("find instance :" + x);
>                 x.TAG.value ="verynb";  //you can change tag value
>                 console.log(x.TAG.value);
>             },
>             onComplete: function () {
>                 console.log("end");
>             }
>         });
> ```

Your code is almost same as xiaokanghub's, just get value of a static field or modify it. I mean hook.

let's make it clear. The following code describes what I want to do.

```js
const build = Java.use('xx.Build');

// every time build.TAG is accessed, the hook is called.
// you can even return different TAG for every access.
build.TAG.hook = function(originalValue){
    return yourTag;
}

// Creator is a static field of a class, to hook its method
build.Creator.createFromParcel.implementation = function () {

}

```
