### ISSUE TITLE
为什么frida-Stalker不能打印浮点寄存器的数据?

### ISSUE THREAD

**Issue by eachlove** [frida/frida#1897]
Why can't Frida stallker print data from floating-point registers?

**Comment by b1ueb1ues** [comment]
frida can't support these registers now.  
I use 
`let s0 = ptr(this.context.sp-0x90).readFloat();`
A trick to read register from unwind

**Comment by XUCharles** [comment]
> frida can't support these registers now. I use `let s0 = ptr(this.context.sp-0x90).readFloat();` A trick to read/write register

why is the sp register minus 0x90 offset the s0 register??

**Comment by b1ueb1ues** [comment]
> > frida can't support these registers now. I use `let s0 = ptr(this.context.sp-0x90).readFloat();` A trick to read/write register
> 
> why is the sp register minus 0x90 offset the s0 register??

frida need to save register on stack before do anything else, and restore them after. So we show/edit register data frida stored on stack.

**Comment by XUCharles** [comment]
> 
So the offset is not a fixed 0x90, it's contextual and only specific to your case?

**Comment by XUCharles** [comment]
> > > frida can't support these registers now. I use `let s0 = ptr(this.context.sp-0x90).readFloat();` A trick to read/write register
> > 
> > 
> > why is the sp register minus 0x90 offset the s0 register??
> 
> frida need to save register on stack before do anything else, and restore them after. So we show/edit register data frida stored on stack.

So the offset is not a fixed 0x90, it's contextual and only specific to your case?

**Comment by b1ueb1ues** [comment]
> > > > frida can't support these registers now. I use `let s0 = ptr(this.context.sp-0x90).readFloat();` A trick to read/write register
> > > 
> > > 
> > > why is the sp register minus 0x90 offset the s0 register??
> > 
> > 
> > frida need to save register on stack before do anything else, and restore them after. So we show/edit register data frida stored on stack.
> 
> So the offset is not a fixed 0x90, it's contextual and only specific to your case?

I'm not sure. Afaik it depend on libunwind that frida use, maybe fixed.

**Comment by shatyuka** [comment]
Close this issue?
https://frida.re/news/2022/06/18/frida-15-1-25-released/
https://github.com/frida/frida-gum/pull/658
