### ISSUE TITLE
Access the value of static field from type byte array utilizing reflection in Android

### ISSUE THREAD

**Issue by monkeywave** [frida/frida#191]
Hi,

in Android 4.4 I'm trying to print the value of a static field utilizing reflection. Right now it seems like I'm getting only the address of this field, but not the value. This is the code I'm using:

```
Java.perform(function()
            {       
		var myClass = Java.use("example.com.MyClass").$new();
		var fieldArray = myClass.class.getDeclaredFields();
		send("Name of field 0:"+ fieldArray[0].getName());
		send("Type of field 0:"+ fieldArray[0].geType());
		send("Reference of field 0:"+ fieldArray[0].get(myClass));
		send("Value of field 0:"+ fieldArray[0].get(myClass).value);
	    });

```

and this is the output:
```
{u'type': u'send', u'payload': u'Name of field 0: A'}
{u'type': u'send', u'payload': u'Type of field 0: class [B'}
{u'type': u'send', u'payload': u'Reference of field 0: [B@08147d8'}
{u'type': u'send', u'payload': u'Value of field 0: undefined'}
```
I can access the name and type of this static field (byte array), but can't get it's value. 

I guess I'm doing something wrong here, but can't see what it is...thanks for your help :)

**Comment by oleavr** [comment]
Please file Java issues in [frida-java](https://github.com/frida/frida-java). Cheers!
