### ISSUE TITLE
Some problem when attach to application/

### ISSUE THREAD

**Issue by baimurzin** [frida/frida#192]
When I try something like that:

`frida-trace -U -i open com.facebook.katana`

or using script python:

`frida.get_usb_device().attach("com.facebook.katana")`

I got in my adb shell: 

```
root@Z00A_1:/data/local/tmp # **
Frida:ERROR:../../../../frida-core/src/linux/frida-helper-glue.c:1911:frida_resolve_library_function: assertion failed (local_library_path == remote_library_path): ("/system/lib/arm/libc.so" == "/system/lib/arm/nb/libc.so")
Aborted 
```

And as a result of script or command execution:

`Traceback (most recent call last):File "ssl_all45_new_2.py", line 13, in session = frida.get_usb_device().attach(process_name)File "/usr/local/lib/python3.5/dist-packages/frida/core.py", line 96, in attachreturn Session(self._impl.attach(self._pid_of))frida.TransportError: the connection is closed
`
`Failed to attach: the connection is closed    `

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.

**Comment by razaina** [comment]
Hi,

getting almost the same error, frida-server built against android-6.0.1_r1


```
Traceback (most recent call last):
  File "hook.py", line 23, in <module>
    process = frida.get_usb_device().attach('com.google.android.gms')
  File "/home/r/Tools/frida/venv/lib/python3.6/site-packages/frida/core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: the connection is closed
```


`Frida:ERROR:../../../../frida-core/src/linux/frida-helper-glue.c:2059:frida_resolve_library_function: assertion failed (local_library_path == remote_library_path): ("/system/lib/libc.so" == "/lib/libc.so")`

**Comment by razaina** [comment]
Any idea please regarding why local and remote library paths are different?
