### ISSUE TITLE
Windows: Failed to enumerate processes: unable to connect to remote frida-server: closed

### ISSUE THREAD

**Issue by daoduythuan** [frida/frida#195]
I'm using Windows 10 and my emulator is BlueStack rooted.
I installed frida-server by issuing the following command.
`pip install frida`
`adb push frida-server /data/local/tmp/`
`adb shell "chmod 755 /data/local/tmp/frida-server"`
`adb shell "su -c '/data/local/tmp/frida-server'"`
Finally I run command: `frida-ps -U`
And I got an error: `Failed to enumerate processes: unable to connect to remote frida-server: closed`
How to fix it?

**Comment by enovella** [comment]
Did you forward the TCP port for `frida-server`?

**Comment by daoduythuan** [comment]
Yes @enovella !
I forward-ed the TCP port before.

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.

**Comment by oleavr** [comment]
@alliejk Make sure iTunes is installed.
