### ISSUE TITLE
Hook c++ function inside apple mylib.framework (IOS)

### ISSUE THREAD

**Issue by alyfreym** [frida/frida#1971]
Hi. I have one question. I have function in c++ MyEngine::Core::GenerateUniqueKey(). this function inside my MyEngine.framework (IOS).
How I can hook this function using Frida?

**Comment by stokatyan** [comment]
Tried any methods?  I don't know how frida works with a c++ function on iOS, but frida-trace might be a good place to start: https://github.com/frida/frida/issues/1974#issuecomment-1012533145

**Comment by c0618** [comment]
> Hi. I have one question. I have function in c++ MyEngine::Core::GenerateUniqueKey(). this function inside my MyEngine.framework (IOS). How I can hook this function using Frida?

example:
// func_offset is ida Pro & Hopper static analyze get
var func_offset = '0x';
Interceptor.attach(Process.getModuleByName("MyEngine.framework").base.add(func_offset), {
    onEnter: function (args) {},
    onLeave: function (retVal) {}
});
