### ISSUE TITLE
Intercepting arguments exchanged (iOS / Objective-C)

### ISSUE THREAD

**Issue by encodeShoe** [frida/frida#1989]
Hi!

Just getting started learning reverse engineering and Frida

Poking around with AirDrop (sharingd daemon)

I have managed to find out from hooking onto the sharingd daemon, that the class SDAirDropController is "in charge" of the AirDrop settings, eg. when you turn "No One" to "Everyone" or "Contacts Only" in the AirDrop menu, SDAirDropController's methods get invoked

(I also manage to backtrace that SDNetworkOperation setProperty, SharingDaemon handleOperationMessage, SharingDaemon handleNewConnection etc calls/invoke SDAirDropController's setProperty method)

Question:
**How do I hook and intercept the methods being called or invokve to view the variable/arguments exchanged?**

I manage to hook the SDAirDropController class with the following Frida script, and throwing the class and method to see if I can intercept:
```
function show_modify_function_return_value(className_arg, funcName_arg) {
    var className = className_arg;
    var funcName = funcName_arg;
    var hook = eval('ObjC.classes.' + className + '["' + funcName + '"]');
    Interceptor.attach(hook.implementation, {
        onLeave: function(retval) {
            console.log("\n[*] Class Name: " + className);
            console.log("[*] Method Name: " + funcName);
            console.log("\t[-] Type of return value: " + typeof retval);
            console.log("\t[-] Return Value: " + retval);
            console.log("\t[-] True Value: " + retval.value);
        }
    });
}
```

CHANGES AIRDROP SETTINGS TO "EVERYONE"
```
[*] Class Name: SDAirDropController
[*] Method Name: - configureSettingsForAirDrop
	[-] Type of return value: object
	[-] Return Value: 0x125f5a480
	[-] True Value: undefined

[*] Class Name: SDAirDropController
[*] Method Name: - setStatusAndNotify
	[-] Type of return value: object
	[-] Return Value: 0x1ce5e9f40
	[-] True Value: undefined

[*] Class Name: SDAirDropController
[*] Method Name: - somethingChanged:
	[-] Type of return value: object
	[-] Return Value: 0x1ce5e9f40
	[-] True Value: undefined

[*] Class Name: SDAirDropController
[*] Method Name: - setProperty:forKey:
	[-] Type of return value: object
	[-] Return Value: 0x125db7100
	[-] True Value: undefined
```
I see the return values are pointers, is there a way I can get them to print out arguments/variables exchanged instead?

Thanks in advance!

**Comment by encodeShoe** [comment]
Yes thanks! I managed to get some readable strings from SDAirDropController's configureSettingsForAirDrop method
```
[*] Class Name: SDAirDropController
[*] Method Name: - configureSettingsForAirDrop
	[-] Type of return value: object
	[-] Return Value: 0x125f5a480
retval: -- SDHotspotAgent --
Companion Link:         NULL
Family Count:           0
Legacy Browser:         no
Legacy Client Count:    0
Legacy Host Count:      0
PH Supported:           no
PH Device Count:        0
PH Client Count:        0
PH Host Count:          0

Charge Level:           100%
Family HS Enabled:      no
Network Type:           0
Signal Strength:        0
P2P Allowed:            no
```

Just another question, do you think this script I used earlier is doing what I intend to do?
Like am I understanding the script correctly?
```
function show_modify_function_return_value(className_arg, funcName_arg) {
    var className = className_arg;
    var funcName = funcName_arg;
    var hook = eval('ObjC.classes.' + className + '["' + funcName + '"]');
    Interceptor.attach(hook.implementation, {
        onLeave: function(retval) {
            console.log("\n[*] Class Name: " + className);
            console.log("[*] Method Name: " + funcName);
            console.log("\t[-] Type of return value: " + typeof retval);
            console.log("\t[-] Return Value: " + retval);
        }
    });
}
```
First I use Frida Interceptor to attach (hook onto the class and the class' methods), then I'm actually intercepting the return value (retval) of the method when it's called **or** the return value of what the method is calling?


Thanks in advance

**Comment by stokatyan** [comment]
> Just another question, do you think this script I used earlier is doing what I intend to do?
> Like am I understanding the script correctly?
Yes, it seems like the code is doing what you intend to do.  You're attaching to a function that gets called when you change your airdrop settings, and you're trying to learn more about the return value.

>  or the return value of what the method is calling?
I don't understand this question, but onLeave's `retVal` is the value being returned by the function
