### ISSUE TITLE
Link to download pre-build binaries not working 

### ISSUE THREAD

**Issue by mkmcsa** [frida/frida#201]
Hi, 
Following links are not working, is there an alternate location to download the pre-built binaries.

http://build.frida.re/frida/ios/
http://build.frida.re/frida/mac/

**Comment by oleavr** [comment]
Hi,

These should be fixed now. I will leave this issue open and close it once the continuous integration has been fixed so it won't happen again in the future.

Cheers!

**Comment by mkmcsa** [comment]
Hi Ole,
 Thanks for the quick response, Deep links are still not working, couldn't download libs from these links.
http://build.frida.re/frida/ios/bin/frida-server
http://build.frida.re/frida/ios/lib/FridaGadget.dylib

BTW , would these lib work on iOS 10.2 device? 

Thanks,
Karthik

**Comment by riverar** [comment]
Links look live here, can you verify? Will defer iOS question to @oleavr/

**Comment by oleavr** [comment]
Please grab binaries from: https://github.com/frida/frida/releases
