### ISSUE TITLE
Frida issus : Failed to spawn: command failed: 99

### ISSUE THREAD

**Issue by xSaleh** [frida/frida#2019]
Hello

First : 
after run frida-server i try to injection simple code .js to called app

```
D:\Program Files\Microvirt\MEmu>frida -U -l unssl.js -f mozat.rings.loops
     ____
    / _  |   Frida 15.1.17 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to G011A (id=127.0.0.1:21503)
Failed to spawn: need Gadget to attach on jailed Android; its default location is: C:\Users\metas\AppData\Local\Microsoft\Windows\INetCache\frida\gadget-android-arm64.so
```

i alrady download gadget-android-arm64.so from github and add to my path C:\Users\metas\AppData\Local\Microsoft\Windows\INetCache\frida\ << i create folder frida and past file .so

**my problem is :**
after using this command:
frida -U -l unssl.js -f mozat.rings.loops

i have error message:
Failed to spawn: command failed: 99
and crash the app in android

my system: windows 10
my emulator: MEmu Android 7.1.2 { enable root }
frida version : 15.1.17
python version: 3.7.0
pip already install: frida , frida-tools , frida-gadget

any ideas ? 

![image](https://user-images.githubusercontent.com/29132154/155379167-9c641177-df82-4a57-82ac-7e7255142b9e.png)

**Comment by piereligio** [comment]
You are having same issue that I am. Actually, I'm pretty sure we shouldn't put that gadget file manually, and that the issue is on ARM 32 bits architectures. On a x86_64 emulator I had no issues, while I do on my Android 7.1.2 ARM 32 bits phones

**Comment by b1gcat** [comment]
@xSaleh have you solved it , i have the same problem :)

**Comment by xkawjd121000** [comment]
how to solved that? @b1gcat

**Comment by nanshihui** [comment]
same as me
