### ISSUE TITLE
Question about using 8.x

### ISSUE THREAD

**Issue by ping** [frida/frida#202]
I have an old install (v7.1) which I use with a Nexus 4 image running Android 4.4.2 (ARM) in the simulator. This setup has been working fine.

Recently, I upgraded frida to the most recent version 8.2.3 and things have stopped working.

If I remember correctly, ``frida-server`` was downloaded from https://build.frida.re/frida/android/arm/bin/frida-server, now the docs asks us to download it from https://github.com/frida/frida/releases. 

There are 2 possible candidates in the release page which I should use:
https://github.com/frida/frida/releases/download/8.2.3/frida-server-8.2.3-android-arm64.xz
https://github.com/frida/frida/releases/download/8.2.3/frida-server-8.2.3-android-arm.xz

I've tried with both, uncompressed and renamed to ``frida-server`` but neither seemingly works.

``frida-ps -U`` works but when I try to inject a simple script I get ``frida.ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use``.

I'd appreciate any help with this, and I apologise in advance for the noobness.

**Comment by oleavr** [comment]
Hi,

Did you also upgrade the host side to 8.x? It's important that both client and server are on the same major version (ideally they should both be running the same and latest version).

Cheers!

**Comment by ping** [comment]
@oleavr I'm sorry when you refer to the host side, do you mean the ``frida-server`` binary?

**Comment by ping** [comment]
@oleavr I think I found my problem. It was a conflict with the remnants of the old install in site-packages/. I switched to using virtualenv and that fixed the ProtocolError problem for me.
