### ISSUE TITLE
App crashes with frida-discover on Android x86 and Bliss OS

### ISSUE THREAD

**Issue by Yp3rion** [frida/frida#2023]
Hello and first of all thank you for developing this awesome tool which `frida` is.
I wish to report an issue I have encountered when attempting to invoke `frida-discover` on KVM-powered VMs with either the 9.0-r2 release of **Android x86** (both 32 and 64 bits) or **Bliss OS 11.13** installed: no matter how the command is invoked, either the traced application crashes as soon as spawned/attached or it crashes as soon as the user tries to interact with it. This is an example showing the error returned when executing the command `frida-discover -U -f com.aurora.store` with `frida-tools` 10.5.4 and `frida-server` 15.1.9:
```
Tracing 8 threads. Press ENTER to stop.                                 
Process crashed: Bad access due to invalid address

***
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Bliss Version: '11.13'
Build fingerprint: 'Android-x86/android_x86_64/x86_64:9/PQ2A.190405.003/electrikjesus11131524:userdebug/test-keys'
Revision: '0'
ABI: 'x86_64'
pid: 18409, tid: 18409, name: om.aurora.store  >>> com.aurora.store <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    rax 1a0bf6dbe8a0402a  rbx 00007fff9e5c40b0  rcx 000079fbeb0ae07b  rdx 000079fbff187000
    r8  000079fca65cb54f  r9  0000000000000000  r10 0000000000004000  r11 0000000000000246
    r12 0000000000000001  r13 0000000000000000  r14 00007fff9e5c42c0  r15 000000000000001d
    rdi 00007fff9e5c42c0  rsi 0000000000000000
    rbp 0000000000000000  rsp 000079fbf80514d8  rip 0000000000000000

backtrace:
    #00 pc 0000000000000000  <unknown>
    #01 pc 000000000009405b  /system/lib64/libc.so (offset 0x80000) (__pthread_start(void*)+27)
    #02 pc 00000000007fb2bf  [stack:00007fff9ddc9000]
***
Stopping...
```
Notice that I already tried using several versions of `frida-server` including the latest (15.1.17), but I could not identify a single version where `frida-discover` did not crash the target application. I am currently settled on 15.1.9 because it appears that with version 15.1.10 and above injecting custom scripts also ends up crashing the target application.

If you can assist me with debugging I would be glad to try and fix this; I really think that `frida` is awesome and it would be a shame not to be able to fully draw its potential.

**Comment by oleavr** [comment]
Thanks for reporting! Just committed a [fix](https://github.com/frida/frida-gum/commit/86c37554c9ddc30f0b75bcb9d04042baae1d9ee0), which will make it into the next release. Cheers!
