### ISSUE TITLE
Port 27042 not opening

### ISSUE THREAD

**Issue by Wullschi** [frida/frida#203]
Hi!

I'd like to work with Frida on my iOS device and exactly followed the instructions for iOS Instrumentation without jailbreak. I tested with a new and empty Xcode project and added de dylib as described in https://www.frida.re/docs/ios/#without-jailbreak.

Sadly, I don't get the expected output "Frida: Listening on TCP port 27042", neither on Device, nor in the simulator. Waiting for some minutes doesn't help either, the port does not open. Did I overlook something important here?

Thanks!
Wullschi

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
