### ISSUE TITLE
Jailbroken iPhone 7 (iOS 12.1.2) reboots

### ISSUE THREAD

**Issue by jundawiz** [frida/frida#2036]
I use an M1 Mac(Monterey 12.2.1)

Every time I try _python3 dump.py -l_ on terminal
_Failed to enumerate applications: the connection is closed_ comes up
and my iPhone reboots itself

any suggestions?

**Comment by HGStyle** [comment]
I have this exact problem on my jailbroken iPhone with Frida installed via Sileo. Did you get it to work and how ? (please, say yes)
