### ISSUE TITLE
Frida error with iOS 12.5.5

### ISSUE THREAD

**Issue by lorenzoferron98** [frida/frida#2047]
Hi,

I have got an [iPad Mini 2](https://ipsw.me/iPad4,4/info) with iOS 12.5.5 and Sileo installed with [Chimera](https://chimera.coolstar.org/) 1.6.4. I installed `frida-server` from [official repo](https://build.frida.re/Packages) (Package: re.frida.server). Unfortunately if I run `frida-ps -U` (installed with `pip install frida-tools`) or `frida-ps -R` from Manjaro with Python 3.10.2, I receive `Failed to enumerate processes: the connection is closed` and then iPad reboots.

Do you know about this issue? Can you help me?

Thanks in advance.
Kind regards, Lorenzo.

**Comment by lorenzoferron98** [comment]
It works with unc0ver.

**Comment by yimiaodaren** [comment]
iPad Mini 2 with iOS 12.5.5
unc0ver 8.0.2 
can't jailbreak
what can i do?

**Comment by MichaelGDev48** [comment]
> > iPad Mini 2 with iOS 12.5.5
> > unc0ver 8.0.2
> > can't jailbreak
> > what can i do?
> 
> I had some problems with unc0ver: re-jailbreak more times because procedure fails or clear Safary history, etc... then I passed to Odysseyra1n. I used [this guide](https://ios.cfw.guide/installing-odysseyra1n/) and it works. There is one disadvantage this is a semi-tethered jailbreak but IT WORKS!

yeah that doesnt seem to work for me i keep getting error code 31 on apple silicon mac

**Comment by miticollo** [comment]
> > > iPad Mini 2 with iOS 12.5.5
> 
> > > unc0ver 8.0.2
> 
> > > can't jailbreak
> 
> > > what can i do?
> 
> > 
> 
> > I had some problems with unc0ver: re-jailbreak more times because procedure fails or clear Safary history, etc... then I passed to Odysseyra1n. I used [this guide](https://ios.cfw.guide/installing-odysseyra1n/) and it works. There is one disadvantage this is a semi-tethered jailbreak but IT WORKS!
> 
> 
> 
> yeah that doesnt seem to work for me i keep getting error code 31 on apple silicon mac

Do you mean that checkra1n fails?
