### ISSUE TITLE
Cannot connect to frida-server-8.2.3-android-arm server 

### ISSUE THREAD

**Issue by tommy-dong** [frida/frida#205]
Hi, 
I updated the code to 8.2.3 and found below issue when connecting to the frida server.
[Device(id="local", name="Local System", type='local'), Device(id="tcp", name="Local TCP", type='remote'), Device(id="emulator-5554", name="Android Emulator 5554", type='tether')]
Traceback (most recent call last):
  File "/root/workspaceg/frida_test/fulltest.py", line 11, in <module>
    pid = device.spawn([app])
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 84, in spawn
    return self._impl.spawn(argv)
frida.TransportError: the connection is closed

BTW: 8.2.2 works fine.

**Comment by oleavr** [comment]
Thanks for reporting! Please reopen if this is not fixed in 8.2.5.

**Comment by tommy-dong** [comment]
thanks oleavr
