### ISSUE TITLE
DebugSymbol.fromAddress / .fromName returning wrong names?

### ISSUE THREAD

**Issue by doegox** [frida/frida#206]
Hi

Playing around with symbols in a linux libc...

```
let a=DebugSymbol.findFunctionsMatching("_I?_do_write")[0];
DebugSymbol.fromAddress(a);
```
=> `{'moduleName': 'libc.so.6', 'name': '_IO_do_write', ...}`
=> ok

```
let a=DebugSymbol.findFunctionsMatching("_I?_fwrite")[0];
DebugSymbol.fromAddress(a);
```
=> `{'moduleName': 'libc.so.6', 'name': 'fwrite', ...}`
=> 'fwrite' <> '_IO_fwrite' ??

`DebugSymbol.fromName("fwrite"))`
=> empty data

`DebugSymbol.fromName("_IO_fwrite"))`
=> `{'moduleName': 'libc.so.6', 'name': 'fwrite', ...}`
=> 'fwrite' <> '_IO_fwrite' ??

**Comment by doegox** [comment]
And on Android I get always empty names:

```
let a=DebugSymbol.findFunctionsMatching("fwrite")[0];
DebugSymbol.fromAddress(a);
```
`{'address_hex': '0x4003db0c', 'name': '', 'fileName': '', 'moduleName': 'libc.so', 'lineNumber': 0, 'address': 1073994508}`

**Comment by oleavr** [comment]
Thanks for reporting! Let's keep tracking this at frida/frida-gum#186.
