### ISSUE TITLE
Typo in API doc

### ISSUE THREAD

**Issue by doegox** [frida/frida#207]
Hi

At https://www.frida.re/docs/javascript-api/#debugsymbol

`DebugSymbol.fromAddress(address), DebugSymbol.fromAddress(name)`
should be
`DebugSymbol.fromAddress(address), DebugSymbol.fromName(name)`

**Comment by riverar** [comment]
Fixed, good catch! https://github.com/frida/frida-website/commit/8c555ba28c213cb24a8f7d3898b8ceb54caf6372
