### ISSUE TITLE
Failed to spawn: unexpectedly timed out while waiting for app to launch

### ISSUE THREAD

**Issue by miller93** [frida/frida#211]
whenever I try to spawn any app with frida in jailbroken IOS 7.1.2 using `frida-trace -U -f com.facebook.Facebook` the app opens in the device however, I still get  `Failed to spawn: unexpectedly timed out while waiting for app to launch` not sure why... everything else works just fine.

**Comment by oleavr** [comment]
Is this still an issue in Frida 9.0.8?

**Comment by oleavr** [comment]
Please reopen in [frida-core](https://github.com/frida/frida-core) if this is still an issue in the latest Frida 9.x.

**Comment by oleavr** [comment]
Note that a bug with this exact symptom has just been fixed in 306e288 -- currently being released in Frida 12.0.8.
