### ISSUE TITLE
Android weird native hook behaviour [no idea] 

### ISSUE THREAD

**Issue by AndyXan** [frida/frida#214]
Hello. I'm relatively new to Frida and i'm having some sort of weird troubles i can't find a solution to. First of all: Frida setup works as intended. And for further testing i reused a Substrate Application which has to native methods in it, both exported:

```
int getAge(void)
{
    LOGI("[i] Verbose - getAge located at %p\n", &getAge);
    return 21;
}
jstring
Java_io_koz_targetApp1_targetApp1_doThings( JNIEnv* env,
                                                  jobject thiz )
{
    int r = arc4random() % 10000;
    LOGI("[+] John Smith is %d years old.\n", getAge());
    LOGI("[+] The totally reliable random seed is: %d\n\n", r);
    return 0;
}
```

(Complete app can be found at https://github.com/ikoz/AndroidSubstrate_hookingC_examples/tree/master/targetApp1) and the apk is included in this issue.

The first test was to hook the JNI call Java_io_... which works perfectly fine. The second test is, and here it gets somewhat strange, is to hook getAge which is an exported symbol. Here the callback does not occur whatsoever. The function has not been inlined or anything. The hook code:

```
def hookGetAge2():
    get_age_hook_code = """
       Interceptor.attach(Module.findExportByName ("libtargetLib.so","getAge"), {
            onEnter: function (args) {
                send("[*] Instrumentando...");
                }
    });
    """
    return get_age_hook_code
```

Works. The symbol getAge is found. But the callback does not trigger. Also when using ptr(correct address here) does not work.

 However, the callback works perfectly fine for:

```
def hookGetAge():
    get_age_hook_code = """
       Interceptor.attach(Module.findExportByName ("libtargetLib.so","Java_io_koz_targetApp1_targetApp1_doThings"), {
            onEnter: function (args) {
                send("[*] Instrumentando...");
                }
    });
    """
    return get_age_hook_code
```

Works. Callback gets triggered. So since i am completely new to Frida, maybe there is something wrong with my approach in general.

Setup: Ubuntu 13.01, Device: Rooted Tablet Nexus, Android 6.0. SuperSu and so on installed - but i doubt that this is a device problem since Frida and Hooking in general works.

Hope somebody can help me here!
Greetings

[targetApp1-debug.apk.zip](https://github.com/frida/frida/files/714005/targetApp1-debug.apk.zip)

**Comment by oleavr** [comment]
Hi,

Are you sure the function call(s) don't happen exclusively early in the app launch process? (So your instrumentation is added too late.)

Cheers!

**Comment by oleavr** [comment]
Please reopen in [frida-gum](https://github.com/frida/frida-gum) if this is still an issue in latest Frida 9.x.
