### ISSUE TITLE
 frida-inject-15.1.27-arm64 Process not found

### ISSUE THREAD

**Issue by xiaobaiyey** [frida/frida#2148]
frida-inject-version: frida-inject-15.1.27-android-arm64
android : android 10 arm64

check process is running
```shell
marlin:/data/local/tmp # ps -A | grep xue
u0_a673      30999 19043 1913164 101472 SyS_epoll_wait f2eb1ccc S com.xuetian.jiaoyu
```
run frida-inject 
``` shell
marlin:/data/local/tmp #  ./frida-inject-15.1.27 -e -n com.xuetian.jiaoyu -s inject.js
Process not found
```
 got Process not found error

**Comment by xiaobaiyey** [comment]
arg of **-n** should be app name not package name ,

**Comment by denglaxiong** [comment]
Yes, that's true



***@***.***
 
From: xiaobaiyey
Date: 2022-06-24 10:09
To: frida/frida
CC: Subscribed
Subject: Re: [frida/frida] frida-inject-15.1.27-arm64 Process not found (Issue #2148)
arg of -n should be app name not package name ,
