### ISSUE TITLE
Hooking Callback not Executed (Reopen)

### ISSUE THREAD

**Issue by AndyXan** [frida/frida#215]
I'm reopening the Issue as stated. I retested the example with the newest Frida version. The first test was on a Nexus Tablet running 6.0.1. I Retested the same with an ARM-32 Emulator, Running 4.4.2 resulting in the exact same behaviour. Still i'm new to Frida - might be some stupid mistake of mine. 

Native Code from SubstrateTestApp: [targetApp1-debug.apk.zip](https://github.com/frida/frida/files/714005/targetApp1-debug.apk.zip)

```
int getAge(void)
{
    LOGI("[i] Verbose - getAge located at %p\n", &getAge);
    return 21;
}

jstring
Java_io_koz_targetApp1_targetApp1_doThings( JNIEnv* env,
                                                  jobject thiz )
{
    int r = arc4random() % 10000;
    LOGI("[+] John Smith is %d years old.\n", getAge());
    LOGI("[+] The totally reliable random seed is: %d\n\n", r);
    return 0;
}
```

Hooking the JNI Call works perfectly fine. The Message appear in the console.

```
package_name = "io.koz.targetApp1"
...  
def hookGetAge():
    get_age_hook_code = """
       Interceptor.attach(Module.findExportByName ("libtargetLib.so","getAge"), {
            onEnter: function (args) {
                send("[*] Instrumentando...");
                }
    });
    """
    return get_age_hook_code
...
script = session.create_script(hookGetAge())
script.on('message', on_message)
script.load()
sys.stdin.read()
```

However, trying to hook the second native function GetAge() which gets executed according to logcat does not trigger the callback at all. The Symbol getAge gets found by findExportByName and can be resolved (changign getAge to getAgeeeee leads to exception). So it is not a problem with the symbol. Inserting a correct runtime address (ptr(..)) also does not work. 

```
def hookGetAge():
    get_age_hook_code = """
       Interceptor.attach(Module.findExportByName ("libtargetLib.so","getAge"), {
            onEnter: function (args) {
                send("[*] Instrumentando...");
                }
    });
    """
    return get_age_hook_code
```

Environment Ubuntu 13.01, Device: Rooted Tablet Nexus, Android 6.0 including SuperSu and so on. Rechecked with Emulator Running 4.4.2. 

Hope somebody can help me here!
Greetings

**Comment by oleavr** [comment]
Thanks! Let's keep tracking this at frida/frida-gum#187.
