### ISSUE TITLE
If the android cpu is 8gen1, frida cannot be used, which will cause the device to restart

### ISSUE THREAD

**Issue by etjson** [frida/frida#2167]
If the android cpu is 8gen1, frida cannot be used, which will cause the device to restart

This problem has existed for a long time, and my newly purchased Xiaomi Mi 12pro has been unable to use frida, I hope it can be compatible.

@oleavr

**Comment by deyloTT** [comment]
> If the android cpu is 8gen1, frida cannot be used, which will cause the device to restart
> 
> This problem has existed for a long time, and my newly purchased Xiaomi Mi 12pro has been unable to use frida, I hope it can be compatible.
> 
> @oleavr

yes, same problem with me on my redmi note 10 5g. Ive tried multiple things to no avail

**Comment by deyloTT** [comment]
I see you closed it...have you been able to solve it?

**Comment by deyloTT** [comment]
> If the android cpu is 8gen1, frida cannot be used, which will cause the device to restart
> 
> This problem has existed for a long time, and my newly purchased Xiaomi Mi 12pro has been unable to use frida, I hope it can be compatible.
> 
> @oleavr 

have you solved this? I see you closed it

**Comment by deyloTT** [comment]
> > > If the android cpu is 8gen1, frida cannot be used, which will cause the device to restart
> > > This problem has existed for a long time, and my newly purchased Xiaomi Mi 12pro has been unable to use frida, I hope it can be compatible.
> > > @oleavr
> > 
> > have you solved this? I see you closed it
> 
> Dynamic delay injection with gumjs, temporary solution.

ok if possible can you explain or direct me to a link how it can be done? I usually use frida for certificate unpinning with a script...
