### ISSUE TITLE
Java interface not working

### ISSUE THREAD

**Issue by hedger** [frida/frida#220]
I'm running Frida 9.1 with target device Wileyfox Swift (arch=a64) running Android 6.0.1 (CM13.1.5). It's on stock ROM with Xposed v87.

I can't make anything Java-related work.
```
[USB::Wileyfox Wileyfox Swift::com.android.phone]-> Java.available
false
```

I tried debugging what's happening on [Java interface initialization](https://github.com/frida/frida-java/blob/master/lib/android.js#L32), and found out that 
`_ZN3art6mirror6Object5CloneEPNS_6ThreadE` (`art::mirror::Object::Clone(art::Thread*)`)
is missing from `libart.so`, but instead there's a function called `_ZN3art6mirror6Object5CloneEPNS_6ThreadEm`, which demangles to `art::mirror::Object::Clone(art::Thread*, unsigned long)`. 
File containing initialization code is built into frida-server binary, so I can't easily debug and test it further.

**Comment by oleavr** [comment]
Known issue, we're not yet compatible with Xposed. Let's keep tracking this in frida/frida-java#10.
