### ISSUE TITLE
Does each 'attach' create a file contains a helper.exe?

### ISSUE THREAD

**Issue by TO-OTR** [frida/frida#2200]
10GB files. Is this beacause I didn't use detach? 
Thanks for your answer! I appreciate that!
![image](https://user-images.githubusercontent.com/44498296/184572493-050f775f-dcc6-4147-b6bd-721dc26557c2.png)
![image](https://user-images.githubusercontent.com/44498296/184572801-db374def-c763-454d-944d-815ec699f450.png)

**Comment by oleavr** [comment]
It means you didn't tear things down before exiting. If you're using the Python bindings, call `frida.shutdown()` before exiting to make sure things get cleaned up.
