### ISSUE TITLE
iOS 15.6.1 breaks patchCode functionality

### ISSUE THREAD

**Issue by ddzobov** [frida/frida#2205]
Device: iPhone 13 Pro Max
iOS: iOS 15.6.1
Frida-Gadget: 15.2.2

```
Memory.patchCode(address, size, code => {
    this.log('Writing byte array');
    code.writeByteArray(bytes);
});
```

causes this error on iOS 15.6.1, frida-gadget 15.2.2, but on iOS 15.6 all worked perfectly:

```
Aug 21 11:50:50 iPhone-13-Pro-Max App(FridaGadget.dylib)[2110] <Notice>: TWEAK LOG: Writing byte array
Aug 21 11:50:50 iPhone-13-Pro-Max kernel(AppleMobileFileIntegrity)[0] <Notice>: AMFI: '/private/var/mobile/Containers/Data/Application/CFDEEDED-D557-47A1-AC92-094256EC84CB/tmp/frida-0NE7Q1.dylib' has no CMS blob?
Aug 21 11:50:50 iPhone-13-Pro-Max kernel(AppleMobileFileIntegrity)[0] <Notice>: AMFI: '/private/var/mobile/Containers/Data/Application/CFDEEDED-D557-47A1-AC92-094256EC84CB/tmp/frida-0NE7Q1.dylib': Unrecoverable CT signature issue, bailing out.
Aug 21 11:50:50 iPhone-13-Pro-Max kernel(AppleMobileFileIntegrity)[0] <Notice>: AMFI: code signature validation failed.
Aug 21 11:50:50 iPhone-13-Pro-Max kernel(Sandbox)[0] <Error>: Sandbox: App(2110) deny(1) mach-lookup cy:com.saurik.substrated
```

This code works on iOS 15.6.1:
```
Memory.protect(address, size, 'rw-'); // added this
Memory.patchCode(address, size, code => {
    this.log('Writing byte array');
    code.writeByteArray(bytes);
});
```

**Comment by jpstotz** [comment]
Seems that not only `Memory.patchCode` is affected by the changes of iOS 15.6.1:

I also noticed that with iOS15.6.1 it is no longer possible to hook ObjC methods using `Interceptor.attach` or `Interceptor.replace` that are implemented in a framework library that is shipped with the app (or potentially the app binary itself). 

Hooking a function in a system library (that is shipped with iOS) works without problems but if you try to hook e.g. a method of AFNetworking frida just stalls without any error.  

Calling `Memory.protect(address, size, 'rw-');` on the method implementation address and a size of e.g. 16 makes hooking possible again.

**Comment by jpstotz** [comment]
@oleavr Do you see a chance to include automatic memory unprotection into Frida or is it from your point of view responsibility of the Frida script developer to unprotect memory region before executing `Memory.patchCode` or `Interceptor.replace`? If you see responsibility on developer side what would be the  correct size value to unprotect memory for hooking? In my example I used 16 bytes and it seem to work but that was just a guess.

**Comment by oleavr** [comment]
@jpstotz This one is a bug. It's fixed in latest git (as of earlier today) — just make sure the frida-gum submodule is at the latest main if you want to try it. Cheers!

**Comment by ddzobov** [comment]
What about tag frida to 15.2.3 with this fix?

**Comment by oleavr** [comment]
Thanks for confirming, @jpstotz! Let's close this issue :tada:
