### ISSUE TITLE
How to send and recv within JavaScript

### ISSUE THREAD

**Issue by H0r53** [frida/frida#2207]
Frida docs give the following example for sending and receiving data using Python
```py
from __future__ import print_function
import frida
import sys

session = frida.attach("hello")
script = session.create_script("""
    recv('poke', function onMessage(pokeMessage) { send('pokeBack'); });
""")
def on_message(message, data):
    print(message)
script.on('message', on_message)
script.load()
script.post({"type": "poke"})
sys.stdin.read()
```
This seems to work well. However, I'm using strictly JavaScript for frida and I would like to accomplish the same goal: Prompt a remote user/process for input and block within frida until a message is received.

The `send` and `recv` methods exist within JavaScript. It just isn't clear how to use them together. I have been launching frida using this method `frida -U "MyApp" -l myScript.js`. Within `myScript.js` I've tried writing code that does the following:
```js
recv('poke', function onMessage(pokeMessage) {
    send('pokeBack'); 
});
```
My assumption is I need to spawn a new process with `frida -U "MyApp"` (for example) and then send a message using something like this
```js
send("poke")
```
However, when I do this, nothing happens. Additionally, `recv` does not appear to be blocking within the frida script that is loaded into the app. The app continues executing as if `recv` was never encountered, something I can tell by using `console.log('test')` after the `recv` call.

How can you accomplish a blocking send / recv within a JavaScript only frida solution? Thank you!

**Comment by H0r53** [comment]
I believe the "non blocking" concept is ultimately related to the asynchronous nature of the execution. For example, `recv` doesn't block, it just "calls" the callback after it is reached. That is fine and I can write my code accordingly. I am still wondering how to successfully invoke the `recv` callback from another frida process using `send`.

**Comment by H0r53** [comment]
The frida NodeJS bindings are required to reproduce the Python example for messaging.

https://github.com/frida/frida-node

Within the NodeJS bindings exists a Script type with a method for `.post()`.

**Comment by tsxx880** [comment]
frida-core.h Can a local path installation scheme be added to the package?
