### ISSUE TITLE
frida and frida-tools pip errors

### ISSUE THREAD

**Issue by cfossace** [frida/frida#2208]
I suddenly can't install frida / frida-tools anymore with pip! I am not sure why 

> error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> frida
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.
>

**Comment by ahmedmani** [comment]
this is not a problem with frida your traffic is routed through a mitm proxy disable that and it should install fine

**Comment by cfossace** [comment]
No I am not using a proxy. All other pip packages seem to install fine. I think the error is something to do with "legacy-install-failure" in the error code perhaps?

**Comment by cfossace** [comment]
I completely uninstalled and reinstalled python. This fixed the error: 
https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
