### ISSUE TITLE
[ASK FOR TIPS] How can i find native function source?

### ISSUE THREAD

**Issue by tahafatih** [frida/frida#2219]
Hi all,

There ise a native function but i dont know which library has it. How can i find?

` public static native Object m45a(int r0, int r1, long j, String str, Object obj);`

**Comment by kiven7299** [comment]
There are 2 possible ways to achieve that.

**Method 1**: You could find whether there is `System.loadLibrary(<modname>)` or `System.load(<modname>)` in the same class where the native function declared, then the library should be `lib<modname>.so`. As example bellow, the library contains `stringFromJNI()` is `libtestnativelibrary.so`
![image](https://user-images.githubusercontent.com/60765640/190298159-2b19328e-1d02-4c38-ae48-17c39ec344bb.png)

**Method 2**: Using [APIResolver](https://frida.re/docs/javascript-api/#apiresolver) from frida.<br/>
```
var resolver = new ApiResolver('module');
resolver.enumerateMatches('exports:{module name wildcard}!{exported function name wildcard}');
```
Example:
![image](https://user-images.githubusercontent.com/60765640/190299502-382b80e1-2c76-48a4-9cad-ba205a2b8058.png)
