### ISSUE TITLE
Starting suspended gui process (notepad.exe) in windows File->Open results in Not enough memory

### ISSUE THREAD

**Issue by rlaemmert** [frida/frida#222]
Host System: Gentoo 64Bit
Guest System: Windows 7 32Bit inside VirtualBox

frida-server started in Administrator cmd with 
`frida-server.exe -l 0.0.0.0:27042`

on the host i used 
`frida -R -f C:\\Windows\\notepad.exe`
After resume the application successfully shows up but File->Open creates
'Not enough memory' Failure. Other applications for example goldeneye ransomware immediately crash.
Is this suppose to work?

**Comment by oleavr** [comment]
Yes this is supposed to work, but this is a known issue. Unfortunately I don't think I'll get around to investigating this anytime soon, so if you're interested in digging into it I'd be happy to assist. /cc @riverar

**Comment by oleavr** [comment]
Let's keep tracking this at frida/frida-core#107.
