### ISSUE TITLE
Calling Native Function does not change the R4 register 

### ISSUE THREAD

**Issue by gool123456** [frida/frida#2222]
```
var fn_decrpyt_cv0 = new NativeFunction(ptr(Module.findBaseAddress("libXX.so").add(0x00426E84)).or(1),  'int', ['pointer','uint32', 'pointer', 'pointer', 'uint32']);
            if(fn_decrpyt_cv0){
                console.log('fn_decrpyt_cv0:', fn_decrpyt_cv0)
                strvout = Memory.alloc(0x38)
                console.log('strvout:', strvout)
                var In2 = Module.findBaseAddress("libXX.so").add(0x0067F93C).readU32()
                console.log('In2:', In2.toString(16))
                console.log('start call...')
                fn_decrpyt_cv0(strvout, In2, inpath, cbinv, 0xFFFFFFFF)  //<-
            }
```
My Break log :

![image](https://user-images.githubusercontent.com/62092037/188542652-4ea0e846-3767-4c94-ba6a-acb723cb6610.png)

The R4 register is 0, and the parameter I entered is 0xFFFFFFFF . Is Bug ? :)

**Comment by gool123456** [comment]
Paramter log:

inpath: 0x87b5d5d0   
cbinv: 0x87b5de58
strvout: 0x87b5df88
In2: 844e8c98

**Comment by oleavr** [comment]
That is now how AAPCS specifies arguments should be passed. The first four typically go in registers R0-R3, the next go on the stack. If you need something different, you can generate your own adapter trampoline that you call using NativeFunction.

**Comment by gool123456** [comment]
@oleavr thanks, It was indeed my negligence !
