### ISSUE TITLE
frida-gum/meson.build:506:4: ERROR: Dependency 'quickjs' is required but not found.

### ISSUE THREAD

**Issue by lgq2015** [frida/frida#2232]
Dependency liblzma found: YES 5.2.5 (overridden)
Checking for function "pthread_attr_getstack" with dependency threads: YES 
Run-time dependency gioopenssl found: NO (tried pkgconfig, framework and cmake)
Run-time dependency quickjs found: NO (tried pkgconfig, framework and cmake)
Looking for a fallback subproject for the dependency quickjs
Cloning into 'quickjs'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 69 (delta 6), reused 34 (delta 4), pack-reused 0
Receiving objects: 100% (69/69), 607.10 KiB | 1.34 MiB/s, done.
Resolving deltas: 100% (6/6), done.

Executing subproject quickjs 

quickjs| Project name: quickjs
quickjs| Project version: 2021-03-27-frida
quickjs| C compiler for the host machine: /Users/mac/Desktop/frida_build/build/frida-ios-x86_64-clang -include /Users/mac/Desktop/frida_build/build/frida-version.h (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.3)")
quickjs| C linker for the host machine: /Users/mac/Desktop/frida_build/build/frida-ios-x86_64-clang -include /Users/mac/Desktop/frida_build/build/frida-version.h ld64 711
quickjs| C compiler for the build machine: /Users/mac/Desktop/frida_build/build/frida-macos-x86_64-clang -include /Users/mac/Desktop/frida_build/build/frida-version.h (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.3)")
quickjs| C linker for the build machine: /Users/mac/Desktop/frida_build/build/frida-macos-x86_64-clang -include /Users/mac/Desktop/frida_build/build/frida-version.h ld64 711
quickjs| Fetching value of define "EMSCRIPTEN" :
quickjs| Dependency threads found: YES unknown (cached)
quickjs| Library dl found: YES
quickjs| Library m found: YES
quickjs| Has header "unistd.h" : YES (cached)
quickjs| Checking for function "malloc_usable_size" : NO
quickjs| Configuring config.h using configuration
quickjs| Build targets in project: 35
quickjs| Subproject quickjs finished.

Dependency quickjs found: YES 2021-03-27-frida (overridden)
WARNING: Subproject 'quickjs' did not override 'quickjs' dependency and no variable name specified
Dependency quickjs from subproject subprojects/quickjs found: NO

frida-gum/meson.build:506:4: ERROR: Dependency 'quickjs' is required but not found.

A full log can be found at /Users/mac/Desktop/frida_build/build/tmp-ios-x86_64/frida-gum/meson-logs/meson-log.txt
make[1]: *** [build/frida-ios-x86_64/usr/lib/pkgconfig/frida-gum-1.0.pc] Error 1
make: *** [gadget-ios] Error 2

**Comment by lgq2015** [comment]
frida-gum/meson.build:506:4: ERROR: Dependency 'quickjs' is required but not found.
???

**Comment by lgq2015** [comment]
@keesj @raymontag @ralphtheninja @riverar @

**Comment by jeanbmar** [comment]
Build with https://github.com/frida/docker-images, no more issues

**Comment by oleavr** [comment]
This was a bug in the build system where we accidentally used the wrong GCC on x86_64. Fixed in the latest Linux toolchain and SDK.

**Comment by milahu** [comment]
same here

```
Run-time dependency quickjs found: NO (tried pkgconfig and cmake)
```

problem is, my quickjs has no pkgconfig or cmake files

```
$ find /nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27 -type f
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/include/quickjs/quickjs.h
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/include/quickjs/quickjs-libc.h
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/share/doc/jsbignum.info
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/share/doc/jsbignum.texi
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/share/doc/spec.info
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/share/doc/quickjs.texi
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/lib/quickjs/libquickjs.a
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/lib/quickjs/libquickjs.lto.a
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/bin/qjs
/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27/bin/qjsc
```

fix: add pkgconfig file to quickjs

```pkgconfig
prefix=/nix/store/ikpxfq7md3pnc9r716gz8fywmzdf4na6-quickjs-2021-03-27
exec_prefix=${prefix}
libdir=${prefix}/lib
pkglibdir=${prefix}/lib/quickjs
includedir=${prefix}/include
pkgincludedir=${prefix}/include/quickjs

Name: quickjs
Description: A small and embeddable Javascript engine
Version: 2021-03-27
Requires.private:
Libs: -L${pkglibdir} -lquickjs
Libs.private:
Cflags: -I${pkgincludedir}
```

success!

```
Dependency quickjs found: YES 2021-03-27 (cached)
```
