### ISSUE TITLE
BUG !!

### ISSUE THREAD

**Issue by m2k2v** [frida/frida#2246]
Error: Java API only partially available; please file a bug. Missing: JNI_GetCreatedJavaVMs, _ZN3art17ReaderWriterMutex13ExclusiveLockEPNS_6ThreadE, _ZN3art17ReaderWriterMutex15ExclusiveUnlockEPNS_6ThreadE, _ZNK3art6Thread13DecodeJObjectEP8_jobject, _ZN3art10ThreadList9ResumeAllEv, _ZN3art6Thread14CurrentFromGdbEv, _ZN3art3Dbg14SetJdwpAllowedEb
    at ze (frida/node_modules/frida-java-bridge/lib/android.js:181)
    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16)
    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29)
    at _ (frida/node_modules/frida-java-bridge/index.js:21)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:332)
    at call (native)
    at o (/_java.js)
    at <anonymous> (/_java.js)
    at <anonymous> (frida/runtime/java.js:1)
    at call (native)
    at o (/_java.js)
    at r (/_java.js)
    at <eval> (frida/runtime/java.js:3)
    at _loadJava (native)
    at get (frida/runtime/core.js:130)
    at <anonymous> (/frida/repl-2.js:33)

this is My code : 
```
function awaitForCondition(callback) {
    var i = setInterval(function () {
      var addr = Module.findBaseAddress('libil2cpp.so');
        console.log("Address found:", addr);
        if (addr) {
            clearInterval(i);
            callback(+addr);
        }
    }, 0);
}

var il2cpp = null;

Java.perform(function () {
    awaitForCondition(function (base) {
        il2cpp = ptr(base);
        f1();
        console.log("Working...");
    })
})

function f1()
{
    Interceptor.attach(il2cpp.add(0x8471A8),{
        onEnter: function (args) {
            console.log("f1 Called !!!");
            
        },
        onLeave: function (ret_val) {
            console.log("Leave Method !!");
        }
    })
}
```

**Comment by pratheeshrussell** [comment]
I guess you are running in an emulator with --realm=emulated flag?   

I am facing the issue too. If I don't set realm as emulated then  Module.findBaseAddress('libil2cpp.so') returns null always. If I set it to emulated then I get Java error. Any solutions?

**Comment by Chensem** [comment]
> I guess you are running in an emulator with --realm=emulated flag?
> 
> I am facing the issue too. If I don't set realm as emulated then Module.findBaseAddress('libil2cpp.so') returns null always. If I set it to emulated then I get Java error. Any solutions?

Hey , i am faing this issue too , any solutions ?

**Comment by hieudaicano1** [comment]
I am facing the issue too in Emulator , any solutions ?

**Comment by mesidex** [comment]
I'm also having this issue

**Comment by m2k2v** [comment]
Well guys, as far as I have investigated, you cannot use Frida to modify values in memory such as libil2cpp or lib-native using an emulator. This is precisely because of the architecture of emulators, which process binary files in their own way. To solve this problem, you need to use Frida gadgets and take advantage of them on your actual device. The good thing about this tool is that it is fully compatible with Frida and does not require rooting. I hope you succeed ❤✌.
