### ISSUE TITLE
system restrictions error

### ISSUE THREAD

**Issue by eyahoww** [frida/frida#226]
i used frida 9.x and test device is rooted
but failed to attach process
this is my error message.

------------error message---------------
Traceback (most recent call last):
  File "./start.py", line 29, in <module>
    session = frida.get_usb_device().attach('com.elbis.process')
  File "C:\Python27\lib\site-packages\frida\core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.PermissionDeniedError: unable to access process with pid 16933 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root
-------------------------------------------

and this is my python code

------------python code---------------
import frida,sys

def on_message(message, data):
    if message['type'] == 'send':
        print("[*] {0}".format(message['payload']))
    else:
        print(message)

jscode = """
console.log("================ Start ================");
"""

session = frida.get_usb_device().attach('com.elbis.process')
print session
script = session.create_script(jscode)
script.on('message', on_message)
print('[*] Running frida start_py')
script.load()
-------------------------------------------

thankyou for your comment ;-;

**Comment by oleavr** [comment]
Hi,

Is frida-server running as root? And what kind of Android system is it running on?

Cheers!

**Comment by eyahoww** [comment]
yes frida-server running as root.
my android system is 4.4.2.
i think target application is protected from anti debugging.
because my code execute very well for other application.

**Comment by oleavr** [comment]
Ahh right. I bet the target application `ptrace()`s itself so a debugger can't. You'll have to `spawn()` it with Frida and hook `ptrace()` to ignore the application's attempts to do so. (You will have to reverse-engineer some of the app to figure out exactly what this entails.)
