### ISSUE TITLE
Can't Enumerate All Loaded Modules

### ISSUE THREAD

**Issue by jujuo0o** [frida/frida#2265]
Frida doesn't enumerate `libapp.so` and `libflutter.so` on almost all emulators including genymotion, avd. Yet the same applications modules can be enumerated on Windows Subsystem For Android(WSA).

While frida detects the module being loaded, when we hook `dlopen`, but its not available in `Process.enumerateModules` and other respective functions.

Tested on Frida: `15.2.2`

**Comment by baikaishiuc** [comment]
https://github.com/frida/frida/issues/434

it seems therer are bugs in hook dlopen, suggest a new approach in the above post.

`Java.perform(function() {
    const System = Java.use('java.lang.System');
    const Runtime = Java.use('java.lang.Runtime');
    const SystemLoad_2 = System.loadLibrary.overload('java.lang.String');
    const VMStack = Java.use('dalvik.system.VMStack');

    SystemLoad_2.implementation = function(library) {
        console.log("Loading dynamic library => " + library);
        try {
            const loaded = Runtime.getRuntime().loadLibrary0(VMStack.getCallingClassLoader(), library);
            if(library.includes("yourlibraryhere")) {
                // do stuff
            }
            return loaded;
        } catch(ex) {
            console.log(ex);
        }
    };
});`

**Comment by doviettung96** [comment]
Even after applying the above code, I tried to enumerate the modules by Process.enumerateModules but couldn't find the library
