### ISSUE TITLE
Swift class with two words separated by "." breaks Frida logic

### ISSUE THREAD

**Issue by hduarte** [frida/frida#228]
The app is developed in swift. When I try to obtain the methods of the classes, frida breaks when the class is composed by 2 names separated by a "." For example:

...
[+] Class: App1.TransactionListPickerViewController
TypeError: cannot read property 'TransactionListPickerViewControl...' of undefined

Any ideias of how to show frida that the classname is "App1.TransactionListPickerViewController" and not just "App1" ?

**Comment by oleavr** [comment]
Let's track this at frida/frida-objc#1.
