### ISSUE TITLE
compile with -g 

### ISSUE THREAD

**Issue by lx866** [frida/frida#2284]
hi, all when i rebuild frida with -g , which file should i modify, thanks

**Comment by oleavr** [comment]
Hey,

We're using Meson, which uses the an option named `debug` to control this. We leave this on for everything [except V8](https://github.com/frida/frida/blob/f6f2a3d88bd2276063a3fdd1ae066dfbb58bcd75/releng/deps.mk#L502). But, we do pass `--strip` to Meson by default, so you can remove this by editing `config.mk`.

Cheers!
