### ISSUE TITLE
Issues with Frida (16.0.1) recognizing device. Fix is to downgrade version (15.2.2) manually on iOS device.

### ISSUE THREAD

**Issue by SwftAIO** [frida/frida#2286]
Device : iPhone 11 Pro
iOS Version : 14.4.2
Jailbroken method : Unc0ver + Fugu14

Issue:

Installing Frida via sources of https://build.frida.re latest version 16.0.1 causes device to be unrecognized. I have validated both MacOS and iOS Frida version are 16.0.1 during this issue.

Only fix that works currently is to downgrade Frida manually to version 15.2.2

**Comment by shadow-boy** [comment]
same issue and may i request your way to  downgrade frida

**Comment by SwftAIO** [comment]
> same issue and may i request your way to downgrade frida

Sure, to downgrade I used wget, so make sure thats installed. SSH into your iPhone and then the following:

`wget https://github.com/frida/frida/releases/download/15.2.2/frida_15.2.2_iphoneos-arm.deb
dpkg -i frida_15.2.2_iphoneos-arm.deb
killall -HUP SpringBoard`

Please note you will also have to downgrade frida-tools/frida on your Mac/other device.

**Comment by shadow-boy** [comment]
> 

Thank you sincerely

**Comment by RajaUzairAbdullah** [comment]
> > same issue and may i request your way to downgrade frida
> 
> Sure, to downgrade I used wget, so make sure thats installed. Next uninstall Frida in cydia or how you installed it previously. SSH into your iPhone and then the following:
> 
> ```
> wget https://github.com/frida/frida/releases/download/15.2.2/frida_15.2.2_iphoneos-arm.deb
> 
> dpkg -i frida_15.2.2_iphoneos-arm.deb
> 
> killall -HUP SpringBoard
> ```
> 
> Please note you will also have to downgrade frida-tools/frida on your Mac/other device.

Thanks That worked like a charm.
