### ISSUE TITLE
How Can I Install It from Sileo

### ISSUE THREAD

**Issue by senolatac** [frida/frida#2292]
I tried it with `https://build.frida.re` but couldn’t find it.

**Comment by dennyishere** [comment]
Add repo sileo://source/https://build.frida.re/ and search for frida one more time

**Comment by senolatac** [comment]
this doesn’t work on rootless mode.

**Comment by sergeykomlev** [comment]
On `palera1n 1.1 (47affd5)` using `Sileo` I’m able to successfully install `Frida (16.1.0)` from `https://build.frida.re/` repository.

**Comment by vidasamadian** [comment]
how did you do that @sergeykomlev

**Comment by tallot13** [comment]
On palera1n 1.1 (47affd5) using Sileo, when adding repo i have errors - didn't find architectures, could not find release file

**Comment by tallot13** [comment]
problem was in rootless mode

**Comment by SuFu123** [comment]
what is rootless mode btw

**Comment by shoaloak** [comment]
@SuFu123 palera1n is able to jailbreak in fakefs-rootful mode (/ is writeable) and rootless mode (default, / is not writable).
Do note that rootful mode is [deprecated](https://ios.cfw.guide/archived-palera1n-rootful/).
Frida should migrate tweak support to rootless.

Luckily, Miticolo has made a [repo](https://github.com/miticollo/miticollo.github.io/blob/main/repos/my/) you can add to, e.g., Sileo for a rootless Frida

**Comment by SuFu123** [comment]
> @SuFu123 palera1n is able to jailbreak in fakefs-rootful mode (/ is writeable) and rootless mode (default, / is not writable). Do note that rootful mode is [deprecated](https://ios.cfw.guide/archived-palera1n-rootful/). Frida should migrate tweak support to rootless.
> 
> Luckily, Miticolo has made a [repo](https://github.com/miticollo/miticollo.github.io/blob/main/repos/my/) you can add to, e.g., Sileo for a rootless Frida

this repo doesn't work for me,same error didn't find architectures, could not find release file

**Comment by rharnt** [comment]
@SuFu123 , try adding https://miticollo.github.io/repos/my
https://www.linkedin.com/pulse/using-frida-server-rootless-jailbreak-ios-15-césar-calderón
Worked on rootless IOS 16.6
