### ISSUE TITLE
Is there an example of how connect is used in Frida Gadget?

### ISSUE THREAD

**Issue by editso** [frida/frida#2298]
![image](https://user-images.githubusercontent.com/37452715/198830065-849f378d-60f4-422e-b42e-79719e012c01.png)
I did the above and connected successfully, but I didn't know how to load the script

**Comment by dan4ik94** [comment]
Scroll down to the Script section. I personally connect from Windows to my emulator like this:

`adb connect 127.0.0.1:5555&&frida -U -n Gadget -l _agent.js`

**Comment by editso** [comment]
> Scroll down to the **Script** section. I personally connect from Windows to my emulator like this:
> 
> `adb connect 127.0.0.1:5555&&frida -U -n Gadget -l _agent.js`
Thanks, it's my own problem
