### ISSUE TITLE
Hook Java constructor

### ISSUE THREAD

**Issue by daMatz** [frida/frida#2302]
How can we manipulate an object which is created by a Java constructor with frida?

I created new Android Studio Project with a basic Activity and a basic class with constructor.
Here is the working example with `$init`:

![image](https://user-images.githubusercontent.com/9104870/199670659-a94ba295-29a1-4c32-a437-1c51215bf17f.png)

Here is the failing example with `$new`:

![image](https://user-images.githubusercontent.com/9104870/199670881-aed9c90c-e283-4264-a0a3-40f760741ba4.png)

It seems like both of the approaches are not optimal.

What would I have to do if I want to change the `str` of `MyClass` to "Bye!"?

`ret.str.value = "Bye!"` doesn't work for the `$init` approach, as nothing is returned from the `$init` call and also not for the `$new` approach, as we can't return anything from the hooked method.

**Comment by xxr0ss** [comment]
It' is a misunderstanding that `$init` is used to _create_ an instance. Actually the instance is already created before entering `$init`, the instance is `this`.

So your code should be:

```javascript
MyClass.$init.overload().implementation = function() {
    console.log(`before $init: ${this}`)
    this.$init()
    console.log(`after $init: ${this}`)     // <-- same value before $init()
    this.str.value = "Bye!"

    // also you should not return any value here
}
```

**Comment by daMatz** [comment]
Thank you very much for clarifying @xxr0ss, I'll close the issue 👍 

This works well for me:

![image](https://user-images.githubusercontent.com/9104870/199942532-3b884909-46b0-4c33-b25f-62faac51852c.png)

I think this really helps to clear up some confusion about this topic.
