### ISSUE TITLE
Failed to load the Frida native extension: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by egilas** [frida/frida#232]
Hi,

I am trying out Frida 9. I'm getting this error:

-----------------------------------------
C:\python353_x86>.\python.exe
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 15:51:26) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import frida

Failed to load the Frida native extension: DLL load failed: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python353_x86\lib\site-packages\frida\__init__.py", line 26, in <module>
    raise ex
  File "C:\python353_x86\lib\site-packages\frida\__init__.py", line 6, in <module>
    import _frida
ImportError: DLL load failed: The specified module could not be found.

-----------------------------------------

I have tried Frida 8 before on this machine. 
I have tried both the x86 and x64 version of python 3.5.3. 
Frida installed via pip. 
Procmon shows that the C:\python353_x86\Lib\site-packages\_frida.cp35-win32.pyd is being loaded by python.exe.

Got any pointers?

**Comment by egilas** [comment]
Resolved it. Seems there is hardcoded a reference to python36.dll somewhere in the .\_frida.cp35-win32.pyd - saw this popping up on procmon, and confirm via:

PS C:\python353_x86\lib\site-packages> strings .\_frida.cp35-win32.pyd | sls python36.dll

python36.dll

Downloaded and installed python 3.6 and installed via pip there solved it...

**Comment by verylove** [comment]
not resolved at all

**Comment by EionRobb** [comment]
@verylove frida 12 links against python37.dll 
As a hacky workaround you can edit the _frida.cp35-*.pyd file in a hexeditor and rename python37.dll to whatever version of python you have (in my case, I renamed it to python35.dll)

**Comment by DanIntruder** [comment]
@EionRobb's suggestion works for the latest python release, changing the value to python38.dll
