### ISSUE TITLE
Frida Version 16.0.5 "Error Failed to spawn: spawn already in progress for the specified identifier"

### ISSUE THREAD

**Issue by kaleb-g** [frida/frida#2338]
Good Day, I was trying to run an app using frida but there's an error stating

"Failed to spawn: spawn already in progress for the specified identifier"

Device:
iPhone 12 14.5.1 unc0ver jailbreak
Frida Version 16.0.5

Also I was unable to downgrade my frida in Cydia.

**Comment by PerverthsO** [comment]
I have the same error with the version of frida 16.0.5 in iOS 14.3 :(

**Comment by kaleb-g** [comment]
> I have the same error with the version of frida 16.0.5 in iOS 14.3 :(

Hi, I found a work around on this one,  Please refer to this link 

https://github.com/frida/frida/issues/2286#issuecomment-1288319360

Hopefully they will fix this one.

**Comment by oleavr** [comment]
This should be fixed in 16.0.6, just released. Please let me know whether it works for you now.

**Comment by kaleb-g** [comment]
> This should be fixed in 16.0.6, just released. Please let me know whether it works for you now.

Hi @oleavr , It works now. Thank you for the fast fix! great tool as always!
