### ISSUE TITLE
Can`t install frida-server on Android 5.1.1

### ISSUE THREAD

**Issue by kammaks** [frida/frida#235]
Hello,

Please help me with my issue.
Try install frida-server (frida-server-9.1.6-android-arm) on Android 5.1.1, rooted device, use Win 7 x64, installing by Cygwin.
This is that I do and error:

```
$ adb shell
shell@mako:/ $ su
su
root@mako:/ # /data/local/tmp/frida-server &
/data/local/tmp/frida-server &
[1] 8548
root@mako:/ # WARNING: linker: /data/local/tmp/frida-server: unused DT entry: type 0x6ffffffe arg 0x55350
WARNING: linker: /data/local/tmp/frida-server: unused DT entry: type 0x6fffffff arg 0x2
Unable to start server: Error binding to address: Address already in use
```

In this post https://github.com/frida/frida-core/issues/98  you are wrote that fixed in Frida 9.x. but I have it issue...

Thank you in advance.

**Comment by oleavr** [comment]
Looks like you have an existing zombie frida-server already running. Kill it and retry, hopefully that'll do it. (Those linker warnings can be ignored.)
