### ISSUE TITLE
VM::GetEnv failed (ART on Android)

### ISSUE THREAD

**Issue by QKaiser** [frida/frida#237]
I used to rely on this code to list loaded classes on Android:

```javascript
Java.enumerateLoadedClasses({
        onMatch: function(className) {
            send(className);
        },
        onComplete: function() {
            send("done");
        }
});
```

Given the announced improved support for ART in frida 9.1.8, I gave it a try and got an error (stack trace below).

> Error: VM::GetEnv failed: -2
> at e (frida/node_modules/frida-java/lib/result.js:7)
> at frida/node_modules/frida-java/lib/vm.js:53
> at h (frida/node_modules/frida-java/index.js:165)
> at frida/node_modules/frida-java/index.js:106
> at script1.js:18

My understanding is that GetEnv() returns NULL when called from a thread that is not attached to the VM object so I came up with the following fix:

```javascript
if(Java.available){
    Java.vm.attachCurrentThread();
    Java.enumerateLoadedClasses({
        onMatch: function(className) {
            send(className);
        },
        onComplete: function() {
            send("done");
        }
    });
```

I don't know if this should be fixed in frida or if this "trick" should be included in Android documentation so I'll let you look into it :)

**Comment by oleavr** [comment]
Thanks for testing! `Java.enumerateLoadedClasses()` is supposed to throw an error if it's called outside `Java.perform()` -- so I'd definitely recommend changing your code to do that instead. (Your example works but isn't how the API should be used.)

Cheers!

**Comment by QKaiser** [comment]
Aaah, that makes more sense !

Thanks for the super fast reply :)
