### ISSUE TITLE
Cant start frida server on iOS 16

### ISSUE THREAD

**Issue by fredrikhaggbom** [frida/frida#2375]
When installing Frida on jailbroken iOS 16.2 device, I get the following log:
```
iPhone:~ root# apt-get install re.frida.server
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  re.frida.server
0 upgraded, 1 newly installed, 0 to remove and 36 not upgraded.
Need to get 18.7 MB of archives.
After this operation, 59.8 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  re.frida.server
Install these packages without verification? [y/N] y
Get:1 https://build.frida.re ./ re.frida.server 16.0.8 [18.7 MB]
Fetched 18.7 MB in 2s (8775 kB/s)          
Selecting previously unselected package re.frida.server.
(Reading database ... 4426 files and directories currently installed.)
Preparing to unpack .../re.frida.server_16.0.8_iphoneos-arm.deb ...
Unpacking re.frida.server (16.0.8) ...
/Library/LaunchDaemons/re.frida.server.plist: Service cannot load in requested session
Setting up re.frida.server (16.0.8) ...
```

It seems to me that the installation is successful, however when trying to launch frida-server, there's an error (`/Library/LaunchDaemons/re.frida.server.plist: Service cannot load in requested session`)

I get the same error message when trying to start the server with command `launchctl load /Library/LaunchDaemons/re.frida.server.plist`.

Any ideas of how to solve this?

**Comment by YungRaj** [comment]
Experiencing this issue too. Has anyone found a way to get it to work?

**Comment by YungRaj** [comment]
Looks like using Frida 16.0.2 works

**Comment by 0xallie** [comment]
You need to edit the plist and remove
```plist
<key>LimitLoadToSessionType</key>
<string>System</string>
```
and then it should work.

This change should probably be integrated into Frida itself as it is required due to iOS 16 launchctl changes.

**Comment by oleavr** [comment]
Fixed in Frida 16.0.9, currently being released.

**Comment by DnPUBG1** [comment]
i also have the same problem is there any way to solve it?

**Comment by fredrikhaggbom** [comment]
> i also have the same problem is there any way to solve it?

As @oleavr mentioned, it was fixed in version 16.0.9. Both 16.0.9 and 16.0.10 works fine for me in iOS 16.

**Comment by u36318** [comment]
Maybe go to ssh and run `frida-server` manually.

**Comment by und3fined** [comment]
In 16.0.11, Need manual run frida-server on Jb device (iOS 16)

**Comment by DnPUBG1** [comment]
> manual run frida-server

how can i run frida-sever manually

**Comment by und3fined** [comment]
ssh to your device and  run command 
`frida-server -D`

**Comment by Chensem** [comment]
> 

+1

**Comment by HMaker** [comment]
> Fixed in Frida 16.0.9, currently being released.

I got same error with frida 16.0.9 on IOS 16.4.1.

**Comment by jpstotz** [comment]
Does somebody know what effect the setting `LimitLoadToSessionType=System` in the launch daemon plist file has?

If fixing the underlaying problem is not that easy and for most users running frida-server without that option is sufficient my suggestion would be to change the build scripts that create the packages for the Frida Cydia repo to provide two packages: 
One with the launch daemon plist that contains the `LimitLoadToSessionType=System` entry and one without. 

The users could select the package that works in their environment. Does anybody know in which repository the scripts are located that build the frida-server iOS Cydia packages/repository on `https://build.frida.re`?

**Comment by und3fined** [comment]
Anyone can try here: https://miticollo.github.io/repos/

**Comment by 0xklaue** [comment]
The problem still persists.
iOS version: 16.4.1
Frida version: 16.0.19
iOS device: iPhone X (A11)

Workaround mentioned by @0xallie works

**Comment by nullonsesec** [comment]
> You need to edit the plist and remove
> 
> ```
> <key>LimitLoadToSessionType</key>
> <string>System</string>
> ```
> 
> and then it should work.

Either you can do this or for the time being open Filza file manager and search Frida, you will find the executable file click on it and you are good to go.

**Comment by onelive7** [comment]
run  frida-server -D    is ok.

**Comment by Raj789-sec** [comment]
can anyone help me ? ios 16.7.4 iphone8 rootful - frida 16.1.10 and objection unable to use 
➜  ~ objection -g com.apple.VoiceMemos explore                              
/Users/raj/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Checking for a newer version of objection...
Using USB device `iPhone`
Unable to connect to the frida server: failed to get the task for process 12050
