### ISSUE TITLE
How can I pass parameters with dash to Frida

### ISSUE THREAD

**Issue by zyfeng-go** [frida/frida#2384]
I'm trying to execute the command `frida -l xxx.js -f /bin/ls -a` and I unsurprisingly got the error `(frida: error: unrecognized arguments: -a)`.

I've tried multiple ways to pass the `-a` option as well as used the -P option provided by Frida itself. None of them worked. 

**Any help is appreciated!!**

**Comment by oleavr** [comment]
Use `--`, e.g.:

```
frida -f /bin/ls … -- -l /etc
```
