### ISSUE TITLE
frida-agent-32 / 64 for windows link errors

### ISSUE THREAD

**Issue by brudemlaz** [frida/frida#2386]
Hi,

When I'm trying to compile frida-agent-32 / 64 for windows I have some link errors that I didn't get before. These errors are as follows:
I am using the instructions listed on https://frida.re/docs/building/

 Creating library C:\Users\testuser\frida\build\tmp-windows\x64-Debug\frida-agent-64\frida-agent-64.lib and object C:\Users\testuser\frida\build\tmp-windows\x64-Debug\frida-agent-64\frida-agent-64.exp
libv8-10.0.a(parsing_literal-buffer.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(compiler_backend_mid-tier-register-allocator.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(compiler_backend_register-allocator.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(compiler_js-call-reducer.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(compiler_js-create-lowering.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(regexp_regexp.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(wasm_module-compiler.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(wasm_module-instantiate.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(compiler_backend_x64_instruction-selector-x64.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(objects_ordered-hash-table.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(json_json-parser.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(objects_elements.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(objects_literal-objects.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(objects_objects.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(objects_js-objects.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(objects_map.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(heap_factory.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_4
libv8-10.0.a(heap_heap.cc.obj) : error LNK2019: unresolved external symbol __std_min_element_8 referenced in function "unsigned __int64 const * __cdecl __std_min_element<unsigned __int64 const >(unsigned __int64 const *,unsigned __int64 const *)" (??$__std_min_element@$$CB_K@@YAPEB_KPEB_K0@Z)
libv8-10.0.a(heap_slot-set.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_8
libv8-10.0.a(parsing_scanner-character-streams.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_8
libv8-10.0.a(heap_heap-controller.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_8
libv8-10.0.a(heap_heap.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_8
libv8-10.0.a(zone_zone.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_8
libv8-10.0.a(heap_concurrent-marking.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_8
libv8-10.0.a(heap_incremental-marking.cc.obj) : error LNK2001: unresolved external symbol __std_max_element_8
libv8-10.0.a(compiler_wasm-compiler.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(regexp_regexp-compiler-tonode.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(numbers_bignum.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(compiler_memory-lowering.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(heap_object-stats.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(heap_scavenger.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(runtime_runtime-test.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(baseline_baseline-compiler.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(heap_factory.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(handles_global-handles.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(codegen_interface-descriptors.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
libv8-10.0.a(objects_transitions.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_4
C:\Users\testuser\frida\build\tmp-windows\x64-Debug\frida-agent-64\frida-agent-64.dll : fatal error LNK1120: 4 unresolved externals

**Comment by hostar** [comment]
I had the same problem. I think there is something on my machine, which is incorrectly being included to the build process. 
The solution I used was absolute overkill - creating a Windows 10 virtual machine in VirtualBox with only the minimum requirements installed (node and git I think).

**Comment by brudemlaz** [comment]
Hello @hostar thanks for the reply. I found that by updating VS 2022 from 17.4.1 to 17.4.4 the compilation issue went away.

**Comment by unholytony** [comment]
A possible useful piece of information for anyone else straying across this issue.
I had exactly the same issue and it boiled down to tooset versions.
the <algorithm> header in the 14.34 toolset declares and uses a set of c functions __std_min_element_2, __std_min_element_4, etc.
However if the final link occurs with an earlier toolset ( such as 14.29 in my case ) you will see these as unresolved externals.
It is documented somewhere that you cannot consume libraries that are built with newer toolsets and when compiling vcpkg packages it will by default use the most up to date installed tools and sdk's.

I had recently installed Visual Studio 2022 (v143), even though the majority of the project i build have to be Visual Studio 2019 (v142). 

The fix for me was to create an overlay-triplet from the vcpkg created triplet adding:

set(VCPKG_PLATFORM_TOOLSET_VERSION 14.29.30133)

then rebuild the vcpkg's I needed. with the '--overlay-triplets=%MY_OVERLAY_PATH%' on the command line.

I hope this might be of some help to someone else googling this issue.
