### ISSUE TITLE
frida-trace objc_msgSend - any way to get the arg[0] SELF type?

### ISSUE THREAD

**Issue by huobb0** [frida/frida#2392]
Trying to bypass a jailbreak detection framework, which, when kicking in, terminates the app so quickly (<100ms) that I am unable to instrument ObjC calls and I have issues even with identifying exactly _how_ the app is terminated.

As an alternate solution, I use` frida-trace -U -W app.name -i objc_msgSend` with the following handler, giving me results.

```
{
  onEnter(log, args, state) {
    //log(`objc_msgSend(), args[0]:` + args[0] + ', args[1]:' + args[1] + ', args[2]:' + args[2]);
    var selector = args[1].readCString();
    log(selector);
},
```

This part is easy, as the objc_msgSend invocation has the selector as a string in args[1]. However, the first argument is a pointer to the target object. I can use the NativePointer API to read memory and stuff, but is there a way to get type information on the NativePointer arg[0]?

**Comment by oleavr** [comment]
You can do:

```
const self = new ObjC.Object(args[0]);
log(self.$className);
```

(Implemented [here](https://github.com/frida/frida-objc-bridge/blob/main/index.js).)

**Comment by huobb0** [comment]
Awesome, thanks! Greatly appreciated.
