### ISSUE TITLE
Memory.readAnsiString no longer exists?

### ISSUE THREAD

**Issue by jgeralnik** [frida/frida#24]
I tried using Memory.readAnsiString and received an error that the function is undefined.

Sure enough, returning Object.getOwnPropertyNames(Memory) yields: 

    [u'alloc', u'copy', u'protect', u'readPointer', u'writePointer', u'readS8', u'writeS8', u'readU8', u'writeU8', u'readS16', u'writeS16', u'readU16', u'writeU16', u'readS32', u'writeS32', u'readU32', u'writeU32', u'readS64', u'writeS64', u'readU64', u'writeU64', u'readByteArray', u'writeByteArray', u'readUtf8String', u'writeUtf8String', u'readUtf16String', u'writeUtf16String', u'allocUtf8String', u'allocUtf16String', u'scan', u'dup']

which does not include either readAnsi or writeAnsi.

Were these functions intentionally deleted? Is there a different way of reading a generic null-terminated string?

**Comment by oleavr** [comment]
Those are only available on Windows, as they rely on the notion of a current ANSI code-page. Were you trying this on Windows or another OS?

The recommended way of reading a generic null-terminated string is `Memory.readUtf8String()`, although we might want to add a `Memory.readCString()` / `Memory.readAsciiString()` or something like that.

**Comment by jgeralnik** [comment]
Thanks, I was trying on Linux. As you said, I was looking for a readCString or some equivalent - my data may include binary data, but is not utf-8.

**Comment by oleavr** [comment]
Ah right. That's definitely a use-case we should support. I'll add this to the TODO for the upcoming release due later today if all goes to plan.

**Comment by jgeralnik** [comment]
You also may want to update the api docs to make it clear that ansi is windows-only.

**Comment by oleavr** [comment]
Great idea. Thanks!

**Comment by oleavr** [comment]
Fixed in latest git (to be released soon as part of the upcoming 4.0.0).
