### ISSUE TITLE
prompt -sh: /usr/sbin/frida-server: Bad CPU type in executable

### ISSUE THREAD

**Issue by dleyanlin** [frida/frida#240]
Hi,

when run frida-server on terminal after ssh to ios device show below error:
  -sh: /usr/sbin/frida-server: Bad CPU type in executable

device information:
   iPad 2 and OS version is 8.1.3

thanks

**Comment by oleavr** [comment]
Hi, did you install the “Frida for 32-bit devices” package?

**Comment by dleyanlin** [comment]
sorry, i check on the cydia not be installed default. but when select package to install prompt 404 error.

**Comment by max01203** [comment]
It seems this issue can be closed nop?

**Comment by oleavr** [comment]
Yep, thanks @max01203!
