### ISSUE TITLE
error TS2345: Argument of type 'NativePointer | null' is not assignable to parameter of type 'NativePointerValue'.

### ISSUE THREAD

**Issue by barluc** [frida/frida#2407]
#no error
E:\test>frida -f test.exe -l index.js

#error (how to fix it??)
E:\test>frida -f test.exe -l index.ts

#index.js
```
var  pMessageBoxA = Module.findExportByName("user32.dll", 'MessageBoxA')
Interceptor.attach(pMessageBoxA,
 {
    onEnter: function (args, state) 
    {

    },  
    onLeave: function (retval, state) {

    
    }

});
```

log:
```
E:\test>frida -f test.exe -l index.js
     ____
    / _  |   Frida 16.0.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
Spawned `test.exe`. Resuming main thread!
test1:0xf13b30,RVA:0x3b30
[Local::test.exe ]-> Process terminated
[Local::test.exe ]->

Thank you for using Frida!
```

```
E:\test>frida -f test.exe -l index.ts
     ____
    / _  |   Frida 16.0.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
Spawned `test.exe`. Resuming main thread!
E:/test/index.ts:2:20 - error TS2345: Argument of type 'NativePointer | null' is not assignable to parameter of type 'NativePointerValue'.
  Type 'null' is not assignable to type 'NativePointerValue'.
E:/test/index.ts:4:24 - error TS7006: Parameter 'args' implicitly has an 'any' type.
E:/test/index.ts:4:30 - error TS7006: Parameter 'state' implicitly has an 'any' type.
E:/test/index.ts:8:24 - error TS7006: Parameter 'retval' implicitly has an 'any' type.
E:/test/index.ts:8:32 - error TS7006: Parameter 'state' implicitly has an 'any' type.
test1:0xf13b30,RVA:0x3b30
Process terminated
[Local::test.exe ]->

Thank you for using Frida!
```

**Comment by barluc** [comment]
while i excecute " npm run watch" command ,it show error:
if i replace name from /agent/index.ts to /agent/index.js,npm run watch exec OK


E:\test\frida\frida-agent-example>npm run watch

> frida-agent-example@1.0.0 watch
> frida-compile agent/index.ts -o _agent.js -w

Compilation failed: TypeScript error: E:/test/frida/frida-agent-example/agent/index.ts(2,20): Error TS2345: Argument of type 'NativePointer | null' is not assignable to parameter of type 'NativePointerValue'.
  Type 'null' is not assignable to type 'NativePointerValue'.
Notifications are disabled
Reason: DisabledForUser Please make sure that the app id is set correctly.
Command Line: E:\test\frida\frida-agent-example\node_modules\node-notifier\vendor\snoreToast\snoretoast-x64.exe -pipeName \\.\pipe\notifierPipe-4622fd7a-31d6-4c69-8f8a-9d53f6162be5 -m "TypeScript error: E:/test/frida/frida-agent-example/agent/index.ts(2,20): Error TS2345: Argument of type 'NativePointer | null' is not assignable to parameter of type 'NativePointerValue'.
  Type 'null' is not assignable to type 'NativePointerValue'." -t "Compilation failed"

**Comment by barluc** [comment]
ts syntax error

**Comment by oleavr** [comment]
The TypeScript compilers is reporting actual bugs in your code:

1. `Module.findExportByName()` may return `null` if the export cannot be found, and your code is not checking for it and passing the value to `Interceptor.attach()`, which does not accept `null`. The fix, unless you intend to support the particular export being missing for some reason, is to use `Module.getExportByName()`.
2. You're declaring an extra parameter in `onEnter` and `onLeave` -- only frida-trace' handlers has the additional arguments.
3. Side-note: use modern syntax (never use `var`, always `const` or `let`, and instead of `onEnter: function (args) {` do `onEnter(args) {`. Same for `onLeave`.
