### ISSUE TITLE
it seems frida-python did not process non ascii process name

### ISSUE THREAD

**Issue by fr0zenrain** [frida/frida#241]
core.py get_process will raise a exception,i use appmon cause this issue

**Comment by max01203** [comment]
Hi,
Can you provide more detail about the error please?

Thanks,

**Comment by fr0zenrain** [comment]
today when i test it's ok,so strange!
python appmon.py -p ios -a 邮件 -s scripts/iOS/SQLite3/sqlite3_open.js
maybe i fixed,i just modify process name encode utf-8, i'm sorry, please close this issue,thanks!

**Comment by oleavr** [comment]
@fr0zenrain No worries. Thanks for confirming!
