### ISSUE TITLE
frida-server 16 hanging on OnePlus 6

### ISSUE THREAD

**Issue by tacertain** [frida/frida#2423]
I have a rooted OnePlus 6. I am attempting to use frida-server for SSL cert unpinning. I am using the same setup that is successfully working on a Moto G5 Plus (though obviously with the 64-bit version instead of 32-bit). Everything works as expected on the Moto; however, on the OP, as soon as I try to connect to the server, my controlling application hangs. I've tried 16.0.9 and 16.0.10.

If I start the server and then do something simple such as frida-ps -U, that command hangs as well (it runs if the server is not running on the phone - I haven't looked at the code, but I assume it just uses remote commands if the server isn't running). I can't kill the server with Ctrl-C - I have to send it a kill -9 (not sure if that is expected).

I'm looking into installing strace to see if I can get any clue there. I also tried a 15.X release, but it won't work with my frida-tools, and I'm not super keen on downgrading those since it's working for the Moto.

If anybody has any advice, I would appreciate it.

**Comment by tacertain** [comment]
Also, if there are dumb things I could have gotten wrong, love to hear those!

**Comment by thinhbuzz** [comment]
@tacertain try this https://github.com/frida/frida/issues/1788#issuecomment-932833126

**Comment by tacertain** [comment]
Alas, same result.

**Comment by tacertain** [comment]
Here's an strace of running the server. It got to line 22626 before I tried to attach to it (e.g. that thread timed out and exited before I started my frida program). I will try tomorrow to get a similar trace from my Moto where it is working.

[strace.out.txt](https://github.com/frida/frida/files/10781473/strace.out.txt)

**Comment by fwb7014** [comment]
I have the same issue,I try low version it works,the current version may be need a few tricks.

**Comment by fwb7014** [comment]
current version works fun on iPhone, but not Android

**Comment by tacertain** [comment]
15.1.17 worked. I'm not going to pursue further.

**Comment by Montg0mery** [comment]
@tacertain The symptoms sound similar to what a few people (myself included) have seen in #2360 and similar issues.

If you can try the frida-server 16.0.3 binary and it works but the frida-server 16.0.4 binary fails, then I would guess it's the same issue.

**Comment by mriamnobody** [comment]
@tacertain  You should try this I had the same issue and it worked for me https://github.com/frida/frida/issues/2360#issuecomment-1410882971

**Comment by tacertain** [comment]
Closing this - the work arounds are fine for me.
