### ISSUE TITLE
SIGSEGV on 64-bit Linux with 32-bit binary

### ISSUE THREAD

**Issue by frozen-void** [frida/frida#243]
System: Xubuntu 64-bit 16.04
Steps to reproduce the problem:

1. Get hello.c from [frida](https://www.frida.re/docs/functions/)
2. Change sleep(1) to usleep(1000000)
3. Compile with `gcc -m32 hello.c -o hello`
3. Use `python hook.py 0x804843b`
4. Output:

```
f() is at 0x804843b
Number: 0
Number: 1
Number: 2
Number: 3
Number: 1911
Number: 1911
Number: 1911
Segmentation fault (core dumped)
```

**Comment by oleavr** [comment]
Thanks! Which version of Frida is this?

**Comment by frozen-void** [comment]
frida --version says: 9.1.15

**Comment by frozen-void** [comment]
Is there any progress on this issue? It's still relevant in version 10.0.5 and prevents me from using frida at all.

**Comment by oleavr** [comment]
@frozen-void I haven't been able to reproduce this on my Linux systems. Haven't found the time to try other systems in a VM, but I hope to get to it someday. Help appreciated.
