### ISSUE TITLE
Crashed when hooking too many functions

### ISSUE THREAD

**Issue by nevermoe** [frida/frida#244]
Hi, I am trying to hook all functions in an iOS binary to trace the functions calls. However, the app crashed after tens functions being hooked. 

There are about 80 thousands of functions to be hooked. The reason for why I am doing this is that  frida does not support Stalker on iOS / android yet (Sorry, I made a mistake. Seems Stalker is supported for arm64). So I used this work around. Is this kind of hooking massive functions not practical?

The below is part of my code:
```
def get_script():
    hook = """
'use strict';

send("Script Initialized");

var baseAddr = Module.findBaseAddress('inhouse');
baseAddr = parseInt(baseAddr)
send("baseAddr is " + baseAddr.toString(16))

var subs = %subs_list%;
var len = %len%;
for (var i = 0 ; i < len ; i++) {
    var sub_addr = subs[i] + baseAddr;

    send("hooking " + (subs[i] + 0x100000000).toString(16))
    Interceptor.attach(ptr(sub_addr), {
        onEnter:function(args){
            send("hooking sub");
        },
        onLeave:function(retVal){
        }
    });
}

"""
    return hook


if __name__ == "__main__":
    try:
        f = open('./subs.txt', 'r')
        subs_list = []
        for line in f:
            subs_list.append(str(line).strip('\r\n'))
        f.close()

        subs_list[:] = [int(x,16) - 0x100000000 for x in subs_list]
        subs_len = len(subs_list)
        subs_list = json.dumps(subs_list)
        inject_script = get_script()
        inject_script = inject_script.replace('%subs_list%', subs_list).replace('%len%', str(subs_len))


        session = frida.get_usb_device().attach(process)
        script = session.create_script(inject_script)
        script.on('message', on_message)
        script.load()
        sys.stdin.read()
    except KeyboardInterrupt as e:
        sys.exit(0)
```

Furthermore, I tried to test stalker on mac, but it also crashes. Below is my stalker code:
```
def on_message(message, data):
    print message


def get_script():
    hook = """
'use strict';

send("Script Initialized");

const WAITING = 0;
const STALKING = 1;
const DONE = 1;
var state = WAITING;

Interceptor.attach(Module.findExportByName("libc++.1.dylib", "send"), {
    onEnter: function (args) {
        send("enter");
        if (state == STALKING) {
            state == DONE;
            Stalker.unfollow();
        }
    },
    onLeave: function (retval) {
        send("leave");
        if (state == WAITING) {
            state = STALKING;
            Stalker.follow(Process.getCurrentThreadId(), {
                events: {
                    call: true, // CALL instructions: yes please
                    ret: false, // RET instructions: no thanks
                    exec: false // all instructions: no thanks
                },
                onReceive: function (events) {
                    //send("begin stalking");
                },
                onCallSummary: function (summary) {
                    //send("begin stalking");
                }
            });
        }
    }
});

"""
    return hook


if __name__ == "__main__":
    try:
        inject_script = get_script()

        #session = frida.get_usb_device().attach(process)
        session = frida.attach('firefox')
        script = session.create_script(inject_script)
        script.on('message', on_message)
        script.load()
        sys.stdin.read()
    except KeyboardInterrupt as e:
        sys.exit(0)
```

**Comment by oleavr** [comment]
Hi,

> Is this kind of hooking massive functions not practical?

Not for now, unless you would like to hack on Frida and help us optimize this kind of scenarios. We currently have transactions under the hood, so all `Interceptor.attach()` calls within a single stretch of JavaScript are automatically wrapped in a transaction. This makes it possible to do clever things. For now we only batch memory allocations and page updates, but the sky's the limit there.

While Stalker has been ported to arm64, it's only been tested on Android for now, and would need some work to support iOS. Mainly because it relies on RWX pages, which aren't as easily available on iOS.

By the way, this kind of pointer arithmetic is [dangerous](http://stackoverflow.com/questions/9643626/javascript-cant-handle-64-bit-integers-can-it) in 64-bit processes:
`var sub_addr = subs[i] + baseAddr;`
Instead use:
`var sub_addr = baseAddr.add(subs[i]);`
(Always keep pointers as `NativePointer` values.)

Cheers!

**Comment by nevermoe** [comment]
Thank you Oleavr!

There remains a question that when I use Stalker on mac it also crashes. I tried to attach to a simple helloworld program and the stalker ran fine. But when I tried to stalk firefox, or calculator, it just crashed.
