### ISSUE TITLE
frida cannot attach "zygote" process on Android

### ISSUE THREAD

**Issue by lichao890427** [frida/frida#246]
frida cannot attach "zygote" process on Android
test on Android Emulator 4.4
because frida-server inject /data/local/tmp/re.frida.server/frida-agent-32.so  into "zygote"
For common app process , it works,  while "zygote" need injected so file to be resides in system directory like /system/lib/frida-agent-32.so
Can you fix this?

**Comment by fr0zenrain** [comment]
i think you can copy to system directory by manual

**Comment by oleavr** [comment]
Moved to frida/frida-core#114.
