### ISSUE TITLE
how to print stacktrace on windows

### ISSUE THREAD

**Issue by barluc** [frida/frida#2462]
I try to build FridaDbg.dll and export patch_print_stack_trace() function to print stacktrace.
when i hook CreateFileW function,it can print stacktrace, but the number of captured frames too small(CaptureStackBackTrace returns 16)
![image](https://user-images.githubusercontent.com/23028682/228177407-5895e62f-e707-4e73-b349-92588c29dbee.png)

Is there any other solution in frida that can print stack information?

**Comment by barluc** [comment]
vs can print all stacktrace info,
![image](https://user-images.githubusercontent.com/23028682/228180603-44ffa8d9-64a2-4892-8c18-b77af10de7c3.png)

**Comment by barluc** [comment]
Thread.backtrace

**Comment by zodiac-zodiac** [comment]
I think Thread.backtrace will only give you the functions ... if you need more info from the stack like pushed args, local variables ... you can build a simple unwind function like i did, it should be easy for 32bit but for 64 (especially windows) it is nearly impossible given the fact that BP might no be in use and DAWRF info are hard to extract ...
