### ISSUE TITLE
Frida server can't be started because Houdini Failed?

### ISSUE THREAD

**Issue by AlterCreator** [frida/frida#2465]
I can't use frida server because it can't be started by exucute on adb ./frida-server ( i use Nox Emulator and LdPlayer both have same issue with Houdini )

I got text 

[4132] Initialize Houdini (version: 9.0.5c_z.51331 RELEASE)... Failed.

How to fix it? (I use correct version of frida-server with my android emulator version).

Android version i use Android 9 Arm64,64x,

**Comment by AlterCreator** [comment]
Ohh, i found the solution.

**Comment by R4YVEN** [comment]
> Ohh, i found the solution.

People like you are the reason humanity hasn't gone interplanetary yet

**Comment by Okasile** [comment]
I also encountered this issue. The problem is that the target machine and the installed version are different. I downloaded the arm64 version, while the target machine is x86_64. The issue was resolved by downloading the x86_64 version again.

**Comment by hassangawish** [comment]
> 

what is the solution bro ?

**Comment by raze2012** [comment]
In an attempt to quell the victims of [DenverCoder9](https://xkcd.com/979/), I'll also mention that I ran into a similar issue and found the solution. 

I was using the wrong Frida server. be very careful which release you download. A native device will need ARM (or possible ARM-64) and an emulator (which the issue creator mentions) needs an android-x86 release (or perhaps android-x86-64, especially if on Windows 11 with most 32-bit support rendered null). 

Best of luck!
