### ISSUE TITLE
Interceptor.attach() does not work in Android 7.1.1 arm64

### ISSUE THREAD

**Issue by 0xABD** [frida/frida#247]
Interceptor.attach() does not work in Android 7.1.1 arm64 (no effect on the target function, memory unchanged).
Tested with latest Frida 9.1.18 (latest arm64 server binary) on Nexus5X stock N4F26O + TWRP + chainfire SuperSU.

1. Compile and run [hello-jniCallback from Google NDK samples](https://github.com/googlesamples/android-ndk/tree/master/hello-jniCallback)
2. Try to attach Interceptor e.g. to `void sendJavaMsg()` in `libhello-jnicallback.so`
3. Apparently the hook is not being placed in memory.

Attached is the agent.js with Interceptor invocation and the python client. 
[interceptor_testcase.zip](https://github.com/frida/frida/files/851456/interceptor_testcase.zip)

Code:
```
	var ptr_target_func = Module.findExportByName("libhello-jnicallback.so","sendJavaMsg");
	send("sendJavaMsg = " + ptr_target_func);
	send("Memory at target before hook = " + stringToHex(Memory.readCString(ptr_target_func, 16)));

        Interceptor.attach(ptr_target_func, {
            onEnter(args) {
		send("sendJavaMsg - ENTER:");
		//env
		this.var_0 = args[0];
		//instance
		this.var_1 = args[1];
		//func
		this.var_2 = args[2];
		//msg
		this.var_3 = args[3];
		send(stringToHex(Memory.readCString(this.var_3, 64)));
		send("sendJavaMsg - ENTER.");
            } , 
            onLeave(retval) {
		send("sendJavaMsg - LEAVE:");
		send(stringToHex(Memory.readCString(this.var_3, 64)));
		send("sendJavaMsg - LEAVE.");
            }

	});

	send("Memory at target after hook  = " + stringToHex(Memory.readCString(ptr_target_func, 16)));
```

**Comment by oleavr** [comment]
Thanks! Could you try with 9.1.16? I think we have a regression (to be fixed in 9.1.19, hopefully coming later today).

**Comment by 0xABD** [comment]
Tested in 9.1 and 9.1.16, same results.
Surprisingly, `frida-trace` works on that function. So the issue must be with the way I am using Interceptor. 
Calling `Interceptor.flush()` does not help, but I can now see that the hook is placed in memory. The original target function is definitely being called by Java code (verified by adding logcat print in the source code), but the hook handler is either not being called, or is unable to communicate.

**Comment by 0xABD** [comment]
The minimum test case is: 
Python code:
```# -*- coding: utf-8 -*-
import frida, sys, re
import codecs, time
 
def on_message(message, data):
    print message
  
with codecs.open("agent.js", 'r', encoding='utf8') as f:
    jscode = f.read()
    session = frida.get_usb_device(timeout=30).attach("com.example.hellojnicallback")
    session.enable_jit()
    script = session.create_script(jscode)
    script.on('message', on_message) 
    print "[*] Intercepting ..."
    script.load()
    sys.stdin.read()
```
and `agent.js` code
```
send("Starting hooks...");
	var ptr_target_func = Module.findExportByName("libhello-jnicallback.so","sendJavaMsg");
        Interceptor.attach(ptr_target_func, {
            onEnter: function (args) {
		console.log("ENTER");
            } , 
            onLeave: function (retval) {
		console.log("LEAVE");
            }
	});
	Interceptor.flush();
send("Hooks installed.");
```

**Comment by ocecaco** [comment]
I had an issue very similar to this, where my own hooks would not get called, but frida-trace did work. In my case it turned out that the module I was trying to hook was loaded twice into memory at different base addresses. Then findExportByName would only find one of them and hook the wrong one. Frida-trace uses ApiResolver.enumerateMatchesSync so it does not have the same issue. So if you still have this issue, compare the addresses returned by those APIs or see if the module is loaded twice.

**Comment by oleavr** [comment]
Does not seem like a bug.
