### ISSUE TITLE
Optimizing Frida size, guessing which features are relevant

### ISSUE THREAD

**Issue by rmartinsanta** [frida/frida#2475]
I would like to use Frida to instrument an ARM binary in an embedded device. Using frida-server as released crashes due to lack of RAM. Following the instructions in https://frida.re/docs/footprint/, it is clear that I can build it disabling several components. However, I am not sure which components may be disabled, because I am not sure when they are necessary. Current guess:

- FRIDA_V8: Don't know if it is necessary to interpret the JS instrument script, or if this is done by gumjs. When is it really used?
- FRIDA_CONNECTIVITY: can be disabled if SSL is not used, eliminates OpenSSL. Don't know if it can be disabled when using frida-server as: `frida-server -l 0.0.0.0`.
- FRIDA_DATABASE: can be disabled if https://frida.re/docs/javascript-api/#sqlitestatement is not used.
- FRIDA_JAVA_BRIDGE: can be disabled if the instrumented app does not use the Java Virtual Machine.
- FRIDA_OBJC_BRIDGE: can be disabled if the instrumented app is not written in Objective C.
- FRIDA_SWIFT_BRIDGE: can be disabled if the instrumented app is not written in Swift.

Is this correct? If you want, I can open a PR modifying the corresponding webpage, detailing this a bit more.

**Comment by oleavr** [comment]
Thanks, that would be great! :raised_hands:

Some clarifications:

> FRIDA_V8: Don't know if it is necessary to interpret the JS instrument script, or if this is done by gumjs. When is it really used?

Only used when you do `create_script(..., runtime='v8')` (API) / `--runtime=v8` (CLI), as the default runtime is QuickJS-based.

> FRIDA_CONNECTIVITY: can be disabled if SSL is not used, eliminates OpenSSL. Don't know if it can be disabled when using frida-server as: frida-server -l 0.0.0.0.

It can. Only needed if you use `--certificate=CERTIFICATE` to enable TLS, or use `setup_peer_connection()` (API) / `--p2p` (CLI).

> FRIDA_DATABASE: can be disabled if https://frida.re/docs/javascript-api/#sqlitestatement is not used.

Yes, the `SqliteDatabase` class and related APIs.

> FRIDA_JAVA_BRIDGE: can be disabled if the instrumented app does not use the Java Virtual Machine.
> FRIDA_OBJC_BRIDGE: can be disabled if the instrumented app is not written in Objective C.
> FRIDA_SWIFT_BRIDGE: can be disabled if the instrumented app is not written in Swift.

It's kind of misleading to say "the instrumented app", as it could be a system daemon. And it's not only about whether the program itself uses these things -- a system API could be using Objective-C behind the scenes for example.

**Comment by rmartinsanta** [comment]
PR opened in https://github.com/frida/frida-website/pull/255, closing this issue. Thanks for the clarifications!

**Comment by thinhbuzz** [comment]
> Thanks, that would be great! 🙌
> 
> Some clarifications:
> 
> > FRIDA_V8: Don't know if it is necessary to interpret the JS instrument script, or if this is done by gumjs. When is it really used?
> 
> Only used when you do `create_script(..., runtime='v8')` (API) / `--runtime=v8` (CLI), as the default runtime is QuickJS-based.
> 
> > FRIDA_CONNECTIVITY: can be disabled if SSL is not used, eliminates OpenSSL. Don't know if it can be disabled when using frida-server as: frida-server -l 0.0.0.0.
> 
> It can. Only needed if you use `--certificate=CERTIFICATE` to enable TLS, or use `setup_peer_connection()` (API) / `--p2p` (CLI).
> 
> > FRIDA_DATABASE: can be disabled if https://frida.re/docs/javascript-api/#sqlitestatement is not used.
> 
> Yes, the `SqliteDatabase` class and related APIs.
> 
> > FRIDA_JAVA_BRIDGE: can be disabled if the instrumented app does not use the Java Virtual Machine.
> > FRIDA_OBJC_BRIDGE: can be disabled if the instrumented app is not written in Objective C.
> > FRIDA_SWIFT_BRIDGE: can be disabled if the instrumented app is not written in Swift.
> 
> It's kind of misleading to say "the instrumented app", as it could be a system daemon. And it's not only about whether the program itself uses these things -- a system API could be using Objective-C behind the scenes for example.

@oleavr How can I configure this on the latest code?

**Comment by redin0s** [comment]
@thinhbuzz You can specify the options of each subproject during the configure step, for example:

```sh
./configure --host=arm-linux-gnueabihf -- \
    -Dfrida-core:connectivity=disabled \
    -Dfrida-gum:database=disabled \
    -Dfrida-gum:frida_objc_bridge=disabled \
    -Dfrida-gum:frida_java_bridge=disabled
```

You can see each option in the `meson.options` file of each subproject
