### ISSUE TITLE
Latest Frida not working

### ISSUE THREAD

**Issue by Abhishek94-cs** [frida/frida#2477]
Frida version frida-server-16.0.12-android-x86

Failed to enumerate processes: bootstrapper failed due to 'libc-unsupported'; please file a bug

![image](https://user-images.githubusercontent.com/130787361/232118402-88a09c86-b24c-44f2-bc3b-5a0487c41417.png)

**Comment by oleavr** [comment]
Thanks for reporting. What kind of device/emulator is this with?

**Comment by oleavr** [comment]
Fixed in 16.0.13, currently being released.

**Comment by Abhishek94-cs** [comment]
> Thanks for reporting. What kind of device/emulator is this with?

I am using Pixel XL emulater
![image](https://user-images.githubusercontent.com/130787361/232205040-f3866a67-379c-4a0c-9741-7a74718a778a.png)

**Comment by Abhishek94-cs** [comment]
> Fixed in 16.0.13, currently being released.

let me try this one
