### ISSUE TITLE
does frida support hook a function by module + offset

### ISSUE THREAD

**Issue by fr0zenrain** [frida/frida#249]
such as android JNI function, and  some functions  not export.

**Comment by oleavr** [comment]
Yes, you can do: `Interceptor.attach(Module.findBaseAddress('libfoo.so').add(0x1234), ...`

Just keep in mind that the address needs to have its least significant bit set to 1 for Thumb functions.

**Comment by fr0zenrain** [comment]
thanks,,i will test,awesome!

**Comment by 0xABD** [comment]
Also, `frida-trace` supports `-a` (`--add=`) option to quickly hook a function by its raw offset from the base address of the module, like:
```frida-trace -U com.foobar.helloworld -a libfoo.so!0x1234```

**Comment by w0x12e** [comment]
thanks a lot

**Comment by H0r53** [comment]
I'm dealing with a stripped ELF shared object that came from an APK. Functions I'm interested in are not exported. I know the offsets of functions that I want to hook, and I've verified I'm hooking the correct addresses with hexdumps. However, Frida's interceptor never seems to trigger :( I'm pretty positive that the hooked functions are being called from the app through JNI native code. Any idea why the interceptor hooks don't seem to trigger, or how to see what thread is interacting with a module and possibly get a stacktrace of what is being called? At first I was thinking perhaps Frida does not hook routines that are not exported, but this thread seems to indicate that it should.

**Comment by Drygord** [comment]
> the functions of interest were never directly called, but rather they were "returned to" by some funky code modifying the return address

Did you ever find a dynamic way to resolve this? I recall learning about this nasty trick, or a similar variant of it, in one of Casey Muratori's videos about the C compiler and virtual functions of all places.
