### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by QPLAYid** [frida/frida#2539]
Failed to attach: unexpected crash while trying to allocate memory 
I use frida server android arm64

**Comment by 111304037** [comment]
show the logcat or tombstones

**Comment by QPLAYid** [comment]
> show the logcat or tombstones

Where i get that ?

**Comment by QPLAYid** [comment]
> show the logcat or tombstones

I use in termux

**Comment by QPLAYid** [comment]
![Screenshot_2023-06-07-19-27-39-598_com termux](https://github.com/frida/frida/assets/102419809/50daaf22-d37b-4471-a835-ac282472a88e)

**Comment by 15691756737** [comment]
我用的是frida16.1.4  再对soul进行调试的时候也报这个错
![image](https://github.com/frida/frida/assets/68184366/72c9fd02-7189-4856-994f-234efe80b2a9)

**Comment by AndnixSH** [comment]
Getting same issue

**Comment by dyglcc** [comment]
@QPLAYid 解决了吗？怎么解决的呢？

**Comment by FrankHuy** [comment]
same issue

**Comment by aidoTank** [comment]
restart spwan mode, frida -U -f package_name

**Comment by tabs** [comment]
同样的问题，怎么解决的啊
