### ISSUE TITLE
Android: Process not Found / PID not Found

### ISSUE THREAD

**Issue by AndyXan** [frida/frida#254]
Hello, 

have some issue with an app i wanted to test. When launching my python script, frida tells me that the process name or when giving the pid, it can not be found.

However, `frida-ps -Ua` gives me the name and the pid and it has to be found:

```
frida-ps -Ua
15377  EventChallenge                          challenge.teamsik.eventchallenge                       
```  

Python Startup Code:

```
package_name = 'challenge.teamsik.eventchallenge'
13 session = frida.attach(package_name)
14 #session = frida.attach(15377)
```

On the same frida version and installation, i've hooked other functions in other binaries. The only difference so far that I see is that other apps where frida is finding the process have been compiled with ndk-build and the apps i'm currently testing on are compiled with android-studio and gradle stuff.

Greetings, 
Appended App:

[app-debug.apk.zip](https://github.com/frida/frida/files/867324/app-debug.apk.zip)

**Comment by oleavr** [comment]
Hi,

This will attach() on the local system:
```python
session = frida.attach(package_name)
```

instead do:
```python
device = frida.get_usb_device()
session = device.attach(package_name)
```

Cheers!

**Comment by keyurvala** [comment]
> Hi,
> 
> This will `attach()` on the local system:
> 
> ```python
> session = frida.attach(package_name)
> ```
> 
> instead do:
> 
> ```python
> device = frida.get_usb_device()
> session = device.attach(package_name)
> ```
> 
> Cheers!

Not working this for me
