### ISSUE TITLE
Latest Frida Gum Devkit for arm64 iOS (`frida-gum-devkit-16.0.19-ios-arm64.tar.xz`) is compiled incorrectly.

### ISSUE THREAD

**Issue by mineo333** [frida/frida#2554]
There is an issue with the latest frida gum devkit where the Stalker does not function correctly. Specifically, in the function `gum_arm64_relocator_read_one`, the function will not set the correct variables when disassembling branch/return instructions.

For example, when disassembling a `ret` instruction, the function will not set `self->eob` and `self->eoi`. Instead it will go to the default case. This results in very odd output code where it won't virtualize any branch/ret instructions resulting in the code leaving Stalker early. This can be fixed by downgrading to an old frida gum devkit. 

I suspect this is because an incorrect capstone header was used.

**Comment by oleavr** [comment]
Thanks for reporting! Is this using our Rust bindings by any chance? If so this is caused by the wrong Capstone being pulled in and used instead of Frida's.

**Comment by mineo333** [comment]
It actually is the rust bindings. I didn't think that could be an issue because of the frida-gum-sys auto-download. Is the frida-gum-devkit not pre-compiled with capstone?
