### ISSUE TITLE
Failed to spawn: unexpectedly timed out while waiting for signal from process with PID [zygote64.pid]

### ISSUE THREAD

**Issue by fuqiuluo** [frida/frida#2559]
![image](https://github.com/frida/frida/assets/61898844/9134b7b6-f506-4898-80c9-c4fcba56b2dd)

![Screenshot_2023-06-25-05-55-44-102_com android se](https://github.com/frida/frida/assets/61898844/6bd418e0-b024-4fb8-88a1-aa883589ab74)

**Comment by mriamnobody** [comment]
Have you found a solution to this issue?

**Comment by aabbccgg** [comment]
Hello, have you found a solution to this issue? @fuqiuluo

**Comment by aabbccgg** [comment]
> Have you found a solution to this issue? @fuqiuluo

You can try this:
In aosp call it persist.device_config.runtime_native.usap_pool_enabled, but oems change its name
1. getprop|grep usap
2. If getprop xxx.usap returns true
3. setprop xxxx.usap false
4. And then getprop xxxx.usap will return false
5. Use spawn by your own way

**Comment by jang1998** [comment]
do you solove this question? i count it too.
