### ISSUE TITLE
Java.perform doesn't work

### ISSUE THREAD

**Issue by mutepigz** [frida/frida#256]
I can use frida working for Android-native, when I try to use it for `Java.perform()` but i failed.
here is my code:
```
setImmediate(function(){
        console.log("[*] test1");
        Java.perform(function () {
            console.log("[*] test2");
        });
    })
```
when i run this,but only get "test1" and then it waiting for my operation....
<img width="530" alt="default" src="https://cloud.githubusercontent.com/assets/16552633/24432336/032d61ae-1454-11e7-9625-ec50ae850bc7.png">
i want to know how to make it work...

**Comment by enovella** [comment]
Hi @mutepigz ,

After Frida version 9.x new Android features were added in the framework. Are you trying to hook ART or Dalvik?.  

Cheers

**Comment by mutepigz** [comment]
Thanks very much .. My frida-server's version is 8.1.12 
but i download it with 
```
http://build.frida.re/frida/android/arm/bin/frida-server
```
where can i download 9.x frida-server?

**Comment by mutepigz** [comment]
Thanks for your solution .. My frida's version is 8.1.12 @enovella

**Comment by razaina** [comment]
@mutepigz 

`git clone --recursive https://github.com/frida/frida
`
Download android-ndk-r13b

`export ANDROID_NDK_ROOT=/opt/android-ndk-r13b
`
`cd frida
`
`make server-android
`

**Comment by mutepigz** [comment]
thanks ..
but it seems doesn't work ....
<img width="559" alt="default" src="https://cloud.githubusercontent.com/assets/16552633/24446254/659a775a-149f-11e7-9961-8383263ec48c.png">

**Comment by max01203** [comment]
Hi, I think your main issue come from the delay that is to present to attach to a device. (I don't know if the modification was made in the frida command). Try to create a basic launcher in python and set a delay before attaching to USB device and load your JavaScript hooking script. 
If you need more help check this : https://www.mavensecurity.com/blog/getting-started-with-frida-on-android/ I think it can help you :) If needed just ask ;) 

Thanks,
