### ISSUE TITLE
Failed to enumerate applications: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually

### ISSUE THREAD

**Issue by poldenais** [frida/frida#2579]
**iPad 7th Gen.

iOS 16.5.1

palera1n Rootful (iOS16), Sileo 2.5 (rootful).

Frida 16.1.3**

Hi Im getting the Failed to enumerate applications message for the the latest jailbreak. I was having problems getting this device Jailbroken so was delighted when it was done using palera1n and that I got Frida installed. 

Any suggestions please?

**Comment by poldenais** [comment]
closed. opened Xcode. I modified the app in Sileo and it seems to work now.

**Comment by MorielHarush** [comment]
> closed. opened Xcode. I modified the app in Sileo and it seems to work now.

what did you modified ? can you write your solution ?
