### ISSUE TITLE
Is it possible reload a native Library using Frida?

### ISSUE THREAD

**Issue by asafe199** [frida/frida#2599]
I'm looking for a little bit of help with frida on android.

I am trying to reload a native library that is loaded in at runtime in the application. The library grabs various device IDs on first run, I am able to spoof these IDs on first run, however due to the nature of the application, the IDs can only be used once. In order to automate a process within the app, i need to change this ID for each request, therefore needing to reload the library. 

That being said, i know i could reload the entire application, but i feel that this will hinder performance, and loading the native library directly could be a much faster alternative. 

Does anyone know if this is possible, or could anyone point me in the right direction?

I don't want to hook the current library that is already loaded; i'd like to load a new instance of the library

**Comment by sunsjgit** [comment]
我遇到了同样的问题
