### ISSUE TITLE
Failed to enumerate processes?

### ISSUE THREAD

**Issue by BiteFoo** [frida/frida#264]
I had downloaded the android server from "http://build.frida.re/frida/android/arm/bin/",and my phone is neuxs5.  I pushed the server to the /data/local/tmp ,and chmod 755 frida-server, then ,run command ./frida-server , frida-ps -R (on the new terminal ),but I got an error 
 "Failed to enumerate processes: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
" ,what should I do?

**Comment by dzonerzy** [comment]
Frida server version and client version maybe are different , please make sure to use the same version on both sides.

**Comment by amahmoodi181188** [comment]
change your version of frida on both android device and PC

**Comment by DavidRodriguezTorrado** [comment]
I've faced this issue recently. In my case it happened because frida-tools had conflict with the frida version installed. Frida version 14.2.18 and frida-tools version 9.2.5 worked correctly.
