### ISSUE TITLE
NativePointer writeCString() ?

### ISSUE THREAD

**Issue by indexofrefraction** [frida/frida#2649]
NativePointer  readUtf8String(), readUtf16String(), readAnsiString(), readCString()
NativePointer writeUtf8String(), writeUtf16String(), writeAnsiString() **but NO writeCString(**) ...  ??

**Comment by oleavr** [comment]
Use `writeUtf8String()` -- `readCString()` is the same as `readUtf8String()` when the string is properly encoded UTF-8, but adds fault-tolerance in cases when it isn't.

**Comment by indexofrefraction** [comment]
tx oleavr !
