### ISSUE TITLE
ERROR frida 9.1.27 frida_injec t_instance_new: assertion failed (ret == 0): (-1 == 0)

### ISSUE THREAD

**Issue by midnightstarr** [frida/frida#265]
I am running frida server(x86 android) on nox android emulator. Whenever I try to attach to process/invoke get_usb_device I get this error:

First error:
`Frida:ERROR:../../../../frida-core/src/linux/frida-helper-glue.c:2059:frida_reso
lve_library_function: assertion failed (local_library_path == remote_library_pat
h): ("/system/lib/libc.so" == "/system/lib/arm/libc.so")
**`

Next errors:
`
**
Frida:ERROR:../../../../frida-core/src/linux/frida-helper-glue.c:429:frida_injec
t_instance_new: assertion failed (ret == 0): (-1 == 0)
**
`

And python script:
`frida.TransportError: the connection is closed`

Looks like local and remote library paths are different. There is arm in path, however I use x86. That is weird.

**Comment by oleavr** [comment]
Thanks for reporting. This is unfortunately an unsupported configuration (for now).
