### ISSUE TITLE
frida script  how to get  xmm0 value in windows x64?

### ISSUE THREAD

**Issue by zengfr** [frida/frida#2675]
frida script how to get xmm0 value in windows x64? in this. context not xmm0

movups  xmm0, [rsp+8F8h+var_8A8]       
movups  xmmword ptr [rsp+8F8h+usedClient.ExpireDate], xmm0  
 jz          short loc_ECB8F4             
xor        eax, eax

**Comment by j4k0xb** [comment]
seems like the only way is by writing it to memory via asm:

- https://github.com/frida/frida-presentations/blob/37f4de0234de2bd6106af800c49c817f531e0e84/R2Con2017/02-transforms/03-divsd-tamper.js

**Comment by zengfr** [comment]
> seems like the only way is by writing it to memory via asm: https://github.com/frida/frida-presentations/blob/37f4de0234de2bd6106af800c49c817f531e0e84/R2Con2017/02-transforms/03-divsd-tamper.js related: #2558

thank you
