### ISSUE TITLE
An error of "frida.TransportError: gDBus.Error:re.frida.Error.InvalidArgument"

### ISSUE THREAD

**Issue by Jessie9122** [frida/frida#268]
Hello,
I installed a frida on android arm-64 device and the client is install by easy_install on Linux x86_64, version is 9.1.27
`from future import print_function
import frida
import sys

session=frida.get_usb_device().attach("com.abc")
hookcode="""
Interceptor.attach(Module.findExportByName(null,"getDeviceId",{
onEnter:function() {
send("Injecting IMEI");
}
});
"""

script=session.create_script(hookcode)

def on_message(message,data):
print(message)
script.on('message',on_message)
script.load()
sys.stdin.read()`

after excute the python script , we get an error information:
user@ubuntu:~/frida/script$ python imei.py Traceback (most recent call last): File "imei.py", line 14, in <module> script=session.create_script(hookcode) File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 182, in create_script return Script(self._impl.create_script(*args, **kwargs)) frida.TransportError: gDBus.Error:re.frida.Error.InvalidArgument: Script(line 6): SyntaxError: parse error

I want to know if my argument is correct or if it is the bug of the tool

**Comment by oleavr** [comment]
` Script(line 6): SyntaxError: parse error`

Would recommend putting your JavaScript code in a separate file and using an editor with code completion, e.g. vscode.
