### ISSUE TITLE
Frida-gadget does not read the contents of the lib<name>.config.so file

### ISSUE THREAD

**Issue by AmokDev** [frida/frida#2682]
# About the problem
Recently I encountered a problem: frida-gadget does not read the contents of the libname.config.so file.

When I try
```bash
frida -U Gadget -l index.js
```
everything works, but when I try to load the script from the config, nothing works.

# Config script
```json
{
  "interaction": {
    "type": "listen",
    "address": "127.0.0.1",
    "port": 1337,
    "on_port_conflict": "pick-next",
    "on_load": "wait"
  }
}
```

# The screenshots show the file structure, if needed.
![image](https://github.com/frida/frida/assets/114482884/e7fda890-96f1-4d76-8ec5-79f08a56a6d3)
Thanks in advance! 

+ p.s. In theory, the application should wait until it receives the script from the server, but it starts immediately without a script

+ p.s.s. Frida under no circumstances sees the contents of the libpizzakebab.config.so file, lol

**Comment by Gabriel55ita** [comment]
what a familiar looking folder we have here lol

**Comment by AmokDev** [comment]
> what a familiar looking folder we have here lol

it's cool that you recognized the folder, I hope you know how to solve my problem))
