### ISSUE TITLE
How to Create a instance for android?

### ISSUE THREAD

**Issue by mutepigz** [frida/frida#272]
I face a problem that I want to call a function but it belongs to a class
I tried code like 
```
var Class = Java.use("com.test.Main");                                                                                                                      
Class.function("123");
```
but it error  
```
cannot call instance method without an instance
```
so how to create a instance for android?

**Comment by Oreaz** [comment]
https://www.frida.re/docs/javascript-api/#java

> Java.use(className): dynamically get a JavaScript wrapper for className that you can instantiate objects from by calling $new() on it to invoke a constructor.

Another example
`Java.perform(function () {
	var stringClass = Java.use("java.lang.String");
	var stringInstance = stringClass.$new("Hello World");
	send(stringInstance.toString());
});`

**Comment by royhershkovitz** [comment]
checkout this
https://android.jlelse.eu/hacking-android-app-with-frida-a85516f4f8b7
