### ISSUE TITLE
Frida calling wrong overloaded method , Android app

### ISSUE THREAD

**Issue by 11x256** [frida/frida#274]
Hello,
```
Java.perform(function x(){
    var my_class = Java.use("javax.crypto.Cipher");
    my_class.init.overload('int', 'java.security.Key', 'java.security.spec.AlgorithmParameterSpec').implementation  = function(x,y,z){
        this.init(x,y,z);
    }
    });
```

this script crashes the hooked application on android 6.0  x86 emulator , and this is the error message from logcat 

> E/art: JNI ERROR (app bug): attempt to pass an instance of javax.crypto.spec.IvParameterSpec as argument 3 to void javax.crypto.Cipher.init(int, java.security.Key, java.security.AlgorithmParameters)

> A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: bad arguments passed to void javax.crypto.Cipher.init(int, java.security.Key, java.security.AlgorithmParameters) (see above for details)

> A/art: art/runtime/java_vm_ext.cc:410]     from void javax.crypto.Cipher.init!(int, java.security.Key, java.security.spec.AlgorithmParameterSpec)

I am using frida version 10.0.3

Java code calling init function 
```       
SecretKey key = KeyGenerator.getInstance("AES").generateKey();
Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
cipher.init(Cipher.ENCRYPT_MODE, key , new IvParameterSpec("aaaaaaaaaaaabbbb".getBytes()) );
```

**Comment by dzonerzy** [comment]
Try replace
```
this.init(x,y,z);
```
with

```
my_class.init.overload('int', 'java.security.Key', 'java.security.spec.AlgorithmParameterSpec').init.call(this, x,y,z);
```

**Comment by williamfreeman667** [comment]
Was there an actual resolution to this? I am getting the same error with frida 10.3.14 when trying to instrument and subsequently call the Cipher.init method from within the instrumentation code. I tried @dzonerzy's solution without any luck.

**Comment by ultrafunkamsterdam** [comment]
I do not have that much java knowledge but The error seems to tell exactly what is wrong. Method asks for :
"""
java.security.AlgorithmParameters 
"""

And you are sending it a:
""
java.security.spec.AlgorithmParameterSpec
"""

**Comment by ultrafunkamsterdam** [comment]
I do not have that much java knowledge but The error seems to tell exactly what is wrong. Method asks for :
```
java.security.AlgorithmParameters 
```

And you are sending it a:
```
java.security.spec.AlgorithmParameterSpec
```
