### ISSUE TITLE
frida.NotSupportedError: bootstrapper failed due to 'auxv-not-found' - read-only file system

### ISSUE THREAD

**Issue by yooo1999** [frida/frida#2768]
While I tried to attach to Linux ARM64 process I got :

`frida.NotSupportedError: bootstrapper failed due to 'auxv-not-found'`

frida --version
16.1.4

**That happened when the binary located at read-only file system** If I move the binary to writeable file system that works fine!

**Comment by gallexme** [comment]
Same issue here, any other pointers but cause of read only systems ?
It worked half a year ago, same process does not work anymore today and I'm not sure if it's cause kernel updates or something else, anyone got some ideas ?

**Comment by yooo1999** [comment]
Same in frida-server-16.3.3-linux-arm64
