### ISSUE TITLE
How to install frida manually

### ISSUE THREAD

**Issue by aphage** [frida/frida#2789]
Is there any manual installation documentation ?

**Comment by Zepp7289** [comment]
Download whl file from https://pypi.org/project/frida/ then install with 
```
pip install frida-16.0.1.dev7-cp34-abi3-win_amd64.whl
```

**Comment by aphage** [comment]
> Download whl file from https://pypi.org/project/frida/ then install with
> 
> ```
> pip install frida-16.0.1.dev7-cp34-abi3-win_amd64.whl
> ```

Can it only be installed using pip?
