### ISSUE TITLE
Is there any way to call NSLog  for IOS

### ISSUE THREAD

**Issue by dreamhaha** [frida/frida#279]
Is there any way to call NSLog in script,
the code below does not work.

var logptr = Module.findExportByName('Foundation','NSLog');
var nslog = new NativeFunction(ptr(logptr),'void',['pointer']);
var text = ObjC.classes.NSString.stringWithString_("Hello World");
nslog(text);

Thanks!

**Comment by oleavr** [comment]
Here's a working implementation:

```js
var NSAutoreleasePool = ObjC.classes.NSAutoreleasePool;
var NSString = ObjC.classes.NSString;

var pool = NSAutoreleasePool.alloc().init();
try {
  var text = ObjC.classes.NSString.stringWithString_("Hello World");
  var NSLog = new NativeFunction(Module.findExportByName('Foundation', 'NSLog'), 'void', ['pointer', '...']);
  NSLog(NSString.stringWithString_('Hello World'));
} finally {
  pool.release();
}
```

Some notes on your code:
- No need to call `ptr()`, `Module.findExportByName()` returns a `NativePointer` (or `null` if not found).
- Never interact with Objective-C APIs without an autorelease-pool. You can either `ObjC.schedule(ObjC.mainQueue, function () { ... })` to get this for free, or you'll have to do it like in my example.
- `NSLog()` is varargs, so you need to tell `NativeFunction` that it is a varargs function by having a `'...'` marker. If you actually need to pass it more than one argument you will have to create multiple `NativeFunction` objects for each signature. E.g. `new NativeFunction(Module.findExportByName('Foundation', 'NSLog'), 'void', ['pointer', '...', 'int', 'pointer'])` if your format string contains a `%d` followed by a `%s`.
