### ISSUE TITLE
"no response from the script" frida fails to hook with frida-multiple-unpinning.js

### ISSUE THREAD

**Issue by m7zr** [frida/frida#2804]
C:\Program Files\Microvirt\MEmu>frida -U -f com.zhiliaoapp.musically -l "C:\Users\9 9 9\Desktop\frida-multiple-unpinning.js"
     ____
    / _  |   Frida 16.2.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to SM N975F (id=127.0.0.1:21503)
Spawning `com.zhiliaoapp.musically`...

**Comment by kingingo** [comment]
Same issue also with objection

C:\Users\###>objection --gadget tech.httptoolkit.pinning_demo explore
Using USB device `SM G960F`

**Comment by kingingo** [comment]
Update: I could now inject a script via frida-inject 
Example:
ps -A | grep "tech.httptoolkit.pinning_demo"       # Get PID_RUNNING_APP 
su ./frida -p PID_RUNNING_APP -s frida_multiple_unpinning.js
