### ISSUE TITLE
Unable to access class property inside class method hook

### ISSUE THREAD

**Issue by dzonerzy** [frida/frida#281]
As title said i'm unable to access class properties inside class method hook. I have a class defined like this:

```
public class Compute
{
  byte[] array = new byte[16];

 public static void compute(byte[] paramArrayOfByte)
  {
   ..... do something
  }
}
```

Inside compute hook i'm not able to access this.array.

This is my hook:

```
var class4 = Java.use('Package.Compute');
var class4_method1 = class4.compute.overload('[B');

class4_method1.implementation = function(param1){
send(this.array);
var ret = class4_method1.call(this,param1);
return ret;
}
```

this.array always return undefined

**Comment by oleavr** [comment]
You need to use the class, not the instance, as this is a static field. I.e. `class4.array.value`
