### ISSUE TITLE
aux option doesn't work with specify uid / uname in android

### ISSUE THREAD

**Issue by fdciabdul** [frida/frida#2816]
```
127|dandelion:/ $ pm list users
Users:
        UserInfo{0:Owner:13} running
        UserInfo{999:XSpace:800010} running
dandelion:/ $
```

spawn with this argument

`frida -U -f com.android.apps -l script.js --aux='uid=(int)999`

it's stil running on default user,`0:Owner:13`

i follow step in this https://github.com/frida/frida/issues/1353#issuecomment-990424623

am i missing something? or the `aux` argument need to pass in frida-server?

**Comment by chen-zc** [comment]
Use 

--aux="uid=(int)999"

this works for me.

**Comment by fdciabdul** [comment]
> n

omg, i just missing quote
