### ISSUE TITLE
Pass and read parameters for frida script

### ISSUE THREAD

**Issue by Dayslar** [frida/frida#2818]
Good afternoon, can you tell me if I can send some additional parameters when running the script via frida-inject and how can I then read the values ​​of these parameters in the script?

I found the -P property

so I run the script like this on the device

./frida-inject -p 1111 -s agent.js -P {json with args} &

but I still don't know how to read the parameters passed to -P

**Comment by Dayslar** [comment]
If this is still useful to someone, then the command and script look like this

**Comment by Dayslar** [comment]
If this is still useful to someone, then the command and script look like this

./frida-inject -p 1111 -s agent.js -P "'{\"param1Key\":paramOne\"\",\"param2Key\":\"param2\"}'" &

`
function mainFunction(params: any) {
}

rpc.exports = {
    init(stage, parameters) {
        mainFunction(
            JSON.parse(
                JSON.stringify(parameters)
            )
        );
    },
    dispose() {
        log('[dispose]');
    }
};
`

**Comment by rustymagnet3000** [comment]
related:  https://github.com/frida/frida/issues/2384

I could only get this to work with a `--`
