### ISSUE TITLE
Failed to attach: timed out while waiting for session to establish 

### ISSUE THREAD

**Issue by liumengdeqq** [frida/frida#284]
Failed to attach: timed out while waiting for session to establish

**Comment by dzonerzy** [comment]
Please provide more details, are you trying to hook Android , Linux, Windows?
Are you using frida-* prebuilt tools or Frida APIs?

**Comment by Alexeyan** [comment]
You might want to replace the get_usb_device() call with get_usb_device(1) to give it a higher timeout. 
This was necessary for me to get it working on macOS.

**Comment by RoyalFlushever** [comment]
Downgrade your frida-server version on your android devices.
For example, if you have frida-version 10.6.32 on your PC, you can install frida-server 10.0.X.
Note: only master version should match between frida-server and frida.
