### ISSUE TITLE
onEnter and onLeave hook for user defined method inside a class.

### ISSUE THREAD

**Issue by code-error** [frida/frida#285]
I want to hook a user defined function inside a .class file. There are examples using Interceptor to perform onEnter and onLeave, on native methods. I want to do the same for a user defined method inside a .class file without changing the actual implementation of that method. Is it possible ??

**Comment by oleavr** [comment]
No, but you can emulate that behavior yourself:
https://gist.github.com/oleavr/8cc48967a1c836d4026cceef3949ef27
