### ISSUE TITLE
Bug in Frida version 16.2.2 for iOS, failed to spawn: module not found

### ISSUE THREAD

**Issue by andyacer** [frida/frida#2856]
Using Frida-server version 16.2.2, when trying to spawn or attach to an app on an iOS device, frida-server responds with the error below:
`Failed to spawn: module not found at "/usr/local/lib/frida/frida-agent.dylib"`

Error image:
<img width="714" alt="image" src="https://github.com/frida/frida/assets/25163515/62ba76dd-8d38-4772-b0bd-dce0297d0c7c">

This seems to be a new issue introduced since 16.2.1.  Version 16.2.1 works without issue as shown in the below image:
<img width="716" alt="image" src="https://github.com/frida/frida/assets/25163515/4250ec10-0a3b-4df5-be4a-f61169c56062">

Setup details - tested on:
* Rootless jailbroken iPad
* Rootless jailbroken iPhone 7
* Problematic build: frida_16.2.2_iphoneos-arm64.deb
* Working build: frida_16.2.1_iphoneos-arm64.deb

I haven't tested this on a device using a rootful jailbreak or a jailed device.

This was also discussed in this closed issue:
https://github.com/frida/frida/issues/2288

**Comment by deezph** [comment]
same 
Excpetion: Error: Module not found at "/usr/local/lib/frida/frida-agent.dylib"

**Comment by oleavr** [comment]
Thanks a lot for reporting! 🙌 Just [fixed](https://github.com/frida/frida-core/commit/5e149a3f2df5cb4ea8fe46e805c39e5967957d0a) this and cut 16.2.3 -- should be out in 30-60 minutes if the CI is in a good mood 😊

**Comment by andyacer** [comment]
Confirmed fixed in 16.2.3.  Thanks @oleavr  🙂 👍 

<img width="741" alt="image" src="https://github.com/frida/frida/assets/25163515/799c216b-24ea-48d1-babf-125dbb30bcd0">
