### ISSUE TITLE
Trace JNI Callbacks

### ISSUE THREAD

**Issue by AISEC17** [frida/frida#286]
Is it possible to trace JNI Callbacks like CallVoidMethod?
I'm trying to list all CallVoidMethod calls and show the parameters, but I can't find it using the Module.enumerateExports. I'm using following Code, which lists all functions off all modules:
```python
for mods in modules:
    script = session.create_script("""
    "use strict";
    Module.enumerateExports(%s,{
        onMatch function(exp) {
		if (exp.type === 'function') {
			send(%s + ',' + exp.name)
		}},
	onComplete: function () {}
});
""" %(mods, mods))
script.on('message',on_message)
script.load()
```

**Comment by oleavr** [comment]
Hi,

Have a look at [frida-java](https://github.com/frida/frida-java); you'll have to do something similar where you get hold of the `env` pointer and read its vtable. From there you can just `Interceptor.attach()` as you please.

Cheers!
