### ISSUE TITLE
Getting "unknown symbol: banana_main" error for renamed self compiled frida-server

### ISSUE THREAD

**Issue by iamatulsingh** [frida/frida#2886]
Hi,

I have compiled frida-server with different name for arm64 using patch provided by one dev here https://github.com/AsenOsen/frida-stealth?tab=readme-ov-file. I take care about the changed project structure and applied the patch successfully and build was success too. I started the self compiled frida server and then tried to connect using USB but it was timed out. I then tried using ip:port to connect and that failed with error "unknown symbol: banana_main". I think may be I'm idiot because I'm using python lib provided officially and frida-server is self compiled but I can't figured it out. 

Can somebody please tell me what is the exact issue with the steps I followed?

Also, if I'm correct about the error, how can i change or modify the frida-tool to connect to my custom named frida server?

Thank you very much!

**Comment by iamatulsingh** [comment]
I'm simply using hex editor to do changes instead compiling

**Comment by Mutahar789** [comment]
@iamatulsingh did you find a solution? I am facing the same issue. Would appreciate any help. Thanks!
