### ISSUE TITLE
Frida 16.4.0 can't connect to remote server

### ISSUE THREAD

**Issue by seagate00** [frida/frida#2905]
Hello! I'm trying to connect Frida to a remote server, but the connection is not happening - it just freezes frida/frida-ps. I looked at the logs on Wireshark, the connection is not even trying to be established. I installed the previous version of the application (16.3.3) - everything worked.

Please ignore the host - `1.1.1.1`, I specified it for debugging purposes
`frida -H 1.1.1.1 Consolas`

![Screenshot 2024-07-06 011309](https://github.com/frida/frida/assets/34270211/c6c685da-1698-4e99-abdb-936ca3be0e92)

**Comment by oleavr** [comment]
Thanks for reporting! Does it work if you specify an IPv6 address? (Not suggesting this as a workaround, just trying to triage where the regression is.)

**Comment by oleavr** [comment]
Fixed in 16.4.1, currently being released 🎉
