### ISSUE TITLE
frida.NotSupportedError: java API only partially available;

### ISSUE THREAD

**Issue by GHXST01** [frida/frida#291]
FULL ERROR: 
`frida.NotSupportedError: java API only partially available; please file a bug. Missing: _Z20dvmDecodeIndirectRefP6ThreadP8_jobject, _Z15dvmUseJNIBridgeP6MethodPv, _Z20dvmHeapSourceGetBasev, _Z21dvmHeapSourceGetLimitv, _Z16dvmIsValidObjectPK6Object, JNI_GetCreatedJavaVMs, gDvmJni, gDvm`

ANDROID:
`4.4.2 on NOX emulator`

BINARIES:
`frida-server-10.0.15-android-x86`

CODE:
```
Java.perform( function () {

    var MyClass = Java.use('com.myyearbook.m.MYBApplication');

    MyClass.updatePrivateKey.overload('java.lang.String').implementation = function (arg4) {

        send('Outputting function args of `com.myyearbook.m.MYBApplication.updatePrivateKey` ...');

        send(arg4);

        return this.updatePrivateKey(arg4);

    };
});
```
__
NOX emulator can be found [**here**](https://www.bignox.com/l).
I have not tried Genymotion or other emulators.

**Comment by max01203** [comment]
Hi, 
can you try with the latest version that is 10.2.3 at the time of my comment please?

Can you also try on another emulator to check?

Thanks,

**Comment by thatname** [comment]
I've encountered this problem on NOX EMULATOR too, with the latest github version 10.3.1

host OS: windows 7 
frida-server-10.3.1-android-x86

called 
frida_device_get_frontmost_application_sync()
got :
**Java API only partially available; please file a bug. Missing: _Z20dvmDecodeIndirectRefP6ThreadP8_jobject, _Z15dvmUseJNIBridgeP6MethodPv, _Z20dvmHeapSourceGetBasev, _Z21dvmHeapSourceGetLimitv, _Z16dvmIsValidObjectPK6Object, JNI_GetCreatedJavaVMs, gDvmJni, gDvm**

called  
frida_device_attach_sync()
got: 
The connection is closed.

**Comment by oleavr** [comment]
I'm afraid NOX is unsupported. Please use a plain emulator, or help us fix this. It's not a priority for me personally so unless somebody helps out, NOX support will not happen. :-/

**Comment by abdawoud** [comment]
I have the same error with stock Android, the master branch, and I would love to investigate the problem more and try fixing it. Is there any starting point you can suggest?
