### ISSUE TITLE
frida-core 16.4.4 compile error on macos

### ISSUE THREAD

**Issue by PterX** [frida/frida#2910]
/opt/homebrew/Cellar/go/1.22.5/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
ld: Undefined symbols:
  _SecTaskCopyValueForEntitlement, referenced from:
      _darwin_detach_kernel_driver in libfrida-core.a[474](libusb_os_darwin_usb.c.o)
  _SecTaskCreateFromSelf, referenced from:
      _darwin_detach_kernel_driver in libfrida-core.a[474](libusb_os_darwin_usb.c.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by oleavr** [comment]
The new devkits require linking with Security.framework. The clang command-line example in the example.c inside the devkit should have what you need. (It's auto-generated based on the system libraries that we link with.)
