### ISSUE TITLE
Frida Server keeps showing 'Process terminated' after spawning the application

### ISSUE THREAD

**Issue by imacrosid** [frida/frida#2920]
Hi,

I want to bypass the SSL pinning of an Android app using the Frida Server method.
Below are the steps which I have followed/performed:

1. Installed the Frida library and Frida-tools
2. Rooted my Android Device
3. Installed the target app
4. Downloaded the Frida server for my Device architecture
5. Sent the Frida Server to its path in Device
6. Granted the Frida server the necessary permissions
7. Have started the Frida Server
8. Got the Java Script File ready

Now when I try to spawn an app it is raising the process is terminating as shown below:
![Screenshot_32](https://github.com/user-attachments/assets/5d7c780f-01ea-4324-92c3-e2985c719535)
But app still opened.

I’ve tried the advice to add some delay before executing code, but it still doesn’t work. Reference: https://github.com/frida/frida/issues/1085#issuecomment-778541090

**Comment by NgoHuy** [comment]
it's not frida's issue, it's rasp, please don't open new request for those issues!
