### ISSUE TITLE
How can I create byte array in js?

### ISSUE THREAD

**Issue by idoiwill** [frida/frida#293]
I use frida to hook java application and I want to overload the following code of Java:
void java_func(HttpURLConnection httpconne){
    InputStream input = httpconne.getInputStream();
    ByteArrayOutputStream baos = new byteArrayOutputStream();
    byte[]  buffer = new byte[1024];
    int len;
    while (( len = input.read(buffer)) > -1) {
        baos.write(buffer,0,len);
    }
   baos.flush();
}

When I implement this function as js code, I don't know how to create a byte array.
The function read of InputStream need byte array as first arg. How can I create a byte array and transfer to this function??

**Comment by max01203** [comment]
Hello,
I think the thing that you need is to learn smali or bytecode :) because in this particular think byte array is noted like this : [B.
So if I'm not wrong you will have to create a variable like this:
`var byteArr = Java.use("[B"); // to declare the var in javascript
byteArr.$new() // to instantiate the object`

See more detail here : https://github.com/frida/frida-java

I'm not 100% sure about what you need but at least I hope it will help ;)

Thanks,

**Comment by gitQqqHs** [comment]
good

**Comment by awakened1712** [comment]
any update on this please?

**Comment by oleavr** [comment]
```js
var buffer = Java.array('byte', [ 13, 37, 42 ]);
```

**Comment by zxhubo** [comment]
@oleavr I really want to know how to resolve this issue：
https://github.com/frida/frida-java/issues/78

**Comment by srcdes** [comment]
@oleavr Doesn't support declaring java array with size, not elements?

**Comment by srcdes** [comment]
If anyone want to create Java byte array of a certain size, use this code snippet:

```js
const array = new Array(1024);
array.fill(0);
const buffer = Java.array('byte', array); // size of 1024 
```

**Comment by forensicmike** [comment]
> 
> 
> If anyone want to create Java byte array of a certain size, use this code snippet:
> 
> ```js
> const buffer = Java.array('byte', new Array(1024).fill(0)); // size of 1024 
> ```

Array.fill doesn't seem to be implemented for me, otherwise this would be awesome :\ .

**Comment by srcdes** [comment]
> > If anyone want to create Java byte array of a certain size, use this code snippet:
> > ```js
> > const buffer = Java.array('byte', new Array(1024).fill(0)); // size of 1024 
> > ```
> 
> Array.fill doesn't seem to be implemented for me, otherwise this would be awesome :\ .

You can use `--runtime` option setting to `v8` not `duk`.

**Comment by 5andr0** [comment]
If you only want to use the byte array as buffer for reading in java, it makes no sense to have all the overhead of creating and filling a byte array in js and transferring it to java. You can use reflections to create the byte array directly in java.

```
    const byteClass = Java.use('java.lang.Byte').TYPE.value;
    //const byteClass = Java.use("java.lang.Class").getPrimitiveClass('byte');
    //const byteClass = Java.use("java.lang.VMClassLoader").getPrimitiveClass('B');
    const Array = Java.use('java.lang.reflect.Array');
    
    const byteArray = Array.newInstance(byteClass, 1024);
```

If you want to access the `byteArray` in js, just wrap it with `Java.array('byte', byteArray);`

**Comment by anenasa** [comment]
Java.array is slow for me, this is what I use:

```
const env = Java.vm.getEnv();
const JavaObject = Java.use('java.lang.Object');
const buffer = Java.cast(env.newByteArray(1024), JavaObject);
```
And when you want to use buffer as argument, you need to use overload (not tested, not sure if this will work):
`input.read.overload('[B').call(input, buffer)`
