### ISSUE TITLE
How to log NSError in onLeave

### ISSUE THREAD

**Issue by markszabo** [frida/frida#294]
I'm trying to check whether the function [`removeItemAtURL:error:`](https://developer.apple.com/documentation/foundation/nsfilemanager/1413590-removeitematurl) succeeded or not. In `onEnter` I store the error parameter in a local variable, and then I can access it in `onLeave`. However I have two problems: 

If there is no error, then the error object will be `nil`. How can I check for this? (`error == null` is always false and `error == nil` gives `ReferenceError: identifier 'nil' undefined
`).

If there is an error, how can I access the information? I have tried `console.log(error.localizedDescription.toString())`, `console.log(error.code)` and `console.log(error.code.toString())` but it all crashes the application.

My test code is:
```
'use strict';
var resolver = new ApiResolver('objc');
var NSFileManager_removeItemAtURL_error = {};
var NSFileManager_blacklist = [
  'UIKit', 'libobjc.A.dylib',
  'WebKitLegacy', 'libdispatch.dylib',
  'CoreFoundation', 'Foundation',
  'libsystem_pthread.dylib', 'UIFoundation'
];
var array_search = function(str, arr) {
  for (var i = 0; i < arr.length; i++) {
    if (arr[i] === str) return true;
  }
  return false;
}
resolver.enumerateMatches('-[NSFileManager removeItemAtURL:error:]', {
  onMatch: function(match) {
    NSFileManager_removeItemAtURL_error.name = match.name;
    NSFileManager_removeItemAtURL_error.address = match.address;
  },
  onComplete: function() {}
});

var error_to_inspect;

if (NSFileManager_removeItemAtURL_error.address) {
  Interceptor.attach(NSFileManager_removeItemAtURL_error.address, {
    onEnter: function(args) {
        var backtrace = Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress);
        if (!array_search(backtrace[0].toString().split(' ')[1].toString().split('!')[0].toString(), NSFileManager_blacklist)) {

          error_to_inspect = args[3];

        }
      }
      ,onLeave: function (retval) {

        var errorobj = new ObjC.Object(error_to_inspect);
        //console.log(errorobj.code);

      }
  });
}
```

I'm using a jailbroken 4th generation iPad with iOS 8.1.2.

**Comment by oleavr** [comment]
Hi,

This is not a good idea:
```js
error_to_inspect = args[3];
```
Because another thread might call the same function concurrently and overwrite the value. Instead, assign it to a property on `this`, which is a per-thread and per-invocation object, so it even works for recursive functions.

Now, in your `onLeave` you actually want to de-reference the pointer, so do:

```
var errorHandle = Memory.readPointer(this.error);
if (!errorHandle.isNull()) {
  var error = new ObjC.Object(errorHandle);
  console.log('error: ' + error);
}
```

Cheers!

**Comment by markszabo** [comment]
Thank you very much, it works! 👍
