### ISSUE TITLE
Interceptor attach to arbitrary instruction

### ISSUE THREAD

**Issue by river-li** [frida/frida#2944]
Hi, I was trying to hook at an non-function-start instruction and If I directly use the `Interceptor.attach`, the program stack got screwed up after this address. 

As discussed in this issue https://github.com/frida/frida-gum/issues/445, seems like I should pass a null pointer for `onLeave` in low-level. Is it possible to do that in Javascript?

Also, I found the following descriptions in the documentation but didn't find any examples.

> You may also intercept arbitrary instructions by passing a function instead of the callbacks object. This function has the same signature as onEnter, but the args argument passed to it will only give you sensible values if the intercepted instruction is at the beginning of a function or at a point where registers/stack have not yet deviated from that point.

**Comment by j4k0xb** [comment]
```js
Interceptor.attach(instruction, function(args) {
  console.log(this.context);
});
```

**Comment by river-li** [comment]
Thanks!
