### ISSUE TITLE
lineagenos android14 error frida-server-16.4.10-android-arm64

### ISSUE THREAD

**Issue by Lingchen218** [frida/frida#2946]
{"type":"error","description":"Error: libart.so: unable to find export '_ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE'","stack":"Error: libart.so: unable to find export '_ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE'\n    at Function.value [as getExportByName] (frida/runtime/core.js:250:1)\n    at Ft (frida/node_modules/frida-java-bridge/lib/android.js:837:1)\n    at Tt (frida/node_modules/frida-java-bridge/lib/android.js:762:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1331:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1189:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1103:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":250,"columnNumber":1}

frida-server-16.4.10-android-arm64

**Comment by devnoname120** [comment]
Duplicate of: #2851

**Comment by Lingchen218** [comment]
Thanks, it's been solved
