### ISSUE TITLE
Issues attaching to application

### ISSUE THREAD

**Issue by PencilBow** [frida/frida#295]
Hi.

Having some problems attaching to an applications. I'm a complete noob in frida but I've tried just about everything so I feel like it might not be on me.

Running:
- Windows 10 host (anaconda 4.3.1, python 3.6.0)
- frida 10.1.0 (pip install frida)
- android 4.4.2 x86 (through bluestacks)
- Running 'frida-server-10.1.0-android-x86' from the releases page. I'm running the server exactly as described in the android tutorial (data/local/temp, with permissions, sudo, in background).

 I can attach to 'com.google.chrome' perfectly (`frida-trace -U -i "open" com.android.chrome`). When doing the same with other apps (including my target app), it doesn't work. When I run com.facebook.katana for example, I get the following error.

```
Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:2059:frida_resolve_library_function: assertion failed (local_library_path == remote_library_path): ("/system/lib/libc.so" == "/system/lib/arm/libc.so")
**
Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:429:frida_inject_instance_new: assertion failed (ret == 0): (-1 == 0)
```

The error message I receive is the exact same as mentioned in #192 on the bottom.

**Comment by oleavr** [comment]
Hi,

Emulators that run JNI components with qemu-user are not supported. (Contributions welcome, but this is a low-priority issue for me personally so I doubt it will happen anytime soon.)

Cheers!
