### ISSUE TITLE
Unable to perform state trasition

### ISSUE THREAD

**Issue by TensorFu** [frida/frida#2954]
I encountered an error when I ran frida-server, the error is as follows:

```json
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}
```

At first glance, this error seems to be due to an incompatibility between my Frida-server version and my device. However, logically speaking, that’s not the case because my device is the one I’ve always used, and the version of Frida-server hasn’t changed. Everything was working fine in my previous usage, and this error only appeared recently. Even after I changed the Frida-server version and restarted my phone, the error still persists.

**background**
device: pixel 6 pro
frida-server version: 16
Android version: Android 13

**Comment by llmarchitect** [comment]
Same error here:

`{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`

Background:
Device: Pixel 5
Frida-server: 16.5.1
Android Version: 14

**Comment by TensorFu** [comment]
> Same error here:
> 
> `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`
> 
> Background: Device: Pixel 5 Frida-server: 16.5.1 Android Version: 14

It worked -> 

Enter "pm uninstall com.google.android.art"
Reboot your device

**Comment by italodeveloper** [comment]
frida-gadget crash same error, uninstall solution is fixed it

**Comment by antoinechauvn** [comment]
Same here, pm uninstall do nothing

**Comment by root-intruder** [comment]
+1

**Comment by Cookgo** [comment]
+1

**Comment by breaking153** [comment]
+1

**Comment by harsh-im** [comment]
factory resetting the device might help

**Comment by zboralski** [comment]
> factory resetting the device might help

No it won't. You'll just waste time and have the same issue again.

**Comment by user154lt** [comment]
> > factory resetting the device might help
> 
> No it won't. You'll just waste time and have the same issue again.

It depends on what play system update your firmware has. If it is before Aug 2024 it will work as long as you do not perform the play system update. Otherwise like you say it will be a waste of time.

**Comment by Satar07** [comment]
> > > factory resetting the device might help
> >
> >
> > No it won't. You'll just waste time and have the same issue again.
>
> It depends on what play system update your firmware has. If it is before Aug 2024 it will work as long as you do not perform the play system update. Otherwise like you say it will be a waste of time.

I’m using the default Android 15 ARM-v8a system image on the Apple ARM emulator, but the server doesn’t run properly. When I switch to the Android 14 ARM-v8a system image, everything works fine. Looks like the system update is messing things up—dropping back to a version below 14 seems to fix it.

**Comment by zax2002** [comment]
> > Same error here:
> > `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`
> > Background: Device: Pixel 5 Frida-server: 16.5.1 Android Version: 14
> 
> It worked ->
> 
> Enter "pm uninstall com.google.android.art" Reboot your device

Thanks, this worked for me. (Oneplus 8 Pro, Android 13)

**Comment by peiga** [comment]
> > Same error here:
> > `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`
> > Background: Device: Pixel 5 Frida-server: 16.5.1 Android Version: 14
> 
> It worked ->
> 
> Enter "pm uninstall com.google.android.art" Reboot your device

can someone elaborate why this app cause issues? I've seen the advice to uninstall art app a few times now.

**Comment by goodza** [comment]
Using the same version of frida and frida-gadge.so helped me.

**Comment by isfahany** [comment]
> > Same error here:
> > `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`
> > Background: Device: Pixel 5 Frida-server: 16.5.1 Android Version: 14
> 
> It worked ->
> 
> Enter "pm uninstall com.google.android.art" Reboot your device

worked for me. make sure that after:
Enter "pm uninstall com.google.android.art"
reboot adb shell itself "reboot"

**Comment by isfahany** [comment]
> > > Same error here:
> > > `{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n at frida/node_modules/frida-java-bridge/index.js:224:1\n at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}`
> > > Background: Device: Pixel 5 Frida-server: 16.5.1 Android Version: 14
> > 
> > 
> > It worked ->
> > Enter "pm uninstall com.google.android.art" Reboot your device
> 
> can someone elaborate why this app cause issues? I've seen the advice to uninstall art app a few times now.

simply because playstore has a new art. the new art then affect the offset of class linker. then, frida cannot locate it and things got an error.

detailed information:
https://github.com/frida/frida/issues/2254#issuecomment-1514494478

**Comment by EliotCodes** [comment]
I tried running the "pm uninstall com.google.android.art", but I'm getting a [DELETE_FAILED_INTERNAL_ERROR] as response.

I'm on Infinix smart 8 android 13 go.

**Comment by C00kiie** [comment]
same issue, "[DELETE_FAILED_INTERNAL_ERROR] "
