### ISSUE TITLE
Error: Unable to perform state transition

### ISSUE THREAD

**Issue by EbananLinfal** [frida/frida#2984]
Hello, I encountered a error when trying to start `frida-server` (version 16.5.2; android-arm64)

Raw error: 
```
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}
```

I ran `frida-server` on rooted Redmi 10 2022 (Android 13; MIUI Global 14.0.2; 21121119SG)

I don't know what to do anymore, I hope for any help
P.S. English isnt my native language

**Comment by ExternalAddress4401** [comment]
https://github.com/frida/frida/issues/2958

The only solution is deleting com.google.android.art as detailed in one of the replies. Be warned, it's not easy to get back once it's deleted.

**Comment by EbananLinfal** [comment]
> #2958
> 
> The only solution is deleting com.google.android.art as detailed in one of the replies. Be warned, it's not easy to get back once it's deleted.

Just great, thanks

**Comment by wen-zheng** [comment]
android 15 prompt those error messages on adb root shell :
```
pm uninstall com.google.android.art
Failure [DELETE_FAILED_ABORTED: Failed to uninstall apex com.google.android.art]
```

**Comment by wen-zheng** [comment]
> android 15 prompt those error messages on adb root shell :
> 
> ```
> pm uninstall com.google.android.art
> Failure [DELETE_FAILED_ABORTED: Failed to uninstall apex com.google.android.art]
> ```

someone can help

**Comment by lephuhung** [comment]
> android 15 prompt those error messages on adb root shell :
> 
> ```
> pm uninstall com.google.android.art
> Failure [DELETE_FAILED_ABORTED: Failed to uninstall apex com.google.android.art]
> ```

same
