### ISSUE TITLE
Palera1n wont install Sileo Fatal error

### ISSUE THREAD

**Issue by kayaalpbilal** [frida/frida#2986]
After successfully installing palera1n on my computer, I jailbroke my iPhone 8 with palera1n -l. Unfortunately, the installation of Sileo does not work. After attempting, I receive the error message: '[fatal] No matching bootstrap found. File: Download#Install.swift:38 Func: downloadFiles(file:basePath:)'. I even tried it in rootful mode but have a different kind of error message.

**Comment by pig837** [comment]
You've come to the wrong place.

https://github.com/palera1n/palera1n

**Comment by kayaalpbilal** [comment]
Sorry didnt notice!

**Comment by Michael-Howard209z** [comment]
have you found a solution yet if so please show me i am having the same problem on iphone se 1st ios 15.4.8 contact me via email: nguyenkimhehe2009@gmail.com because i often don't pay much attention to github
