### ISSUE TITLE
Frida unable to run

### ISSUE THREAD

**Issue by pentagramz** [frida/frida#299]
Im trying in mac el capitan 10.11.6 and iphone ios 10.2

Im not able to run frida..
![screen shot 2017-07-17 at 10 49 20 pm](https://user-images.githubusercontent.com/7072014/28280806-971e31f0-6b42-11e7-9033-b05d04f959fa.png)

**Comment by oleavr** [comment]
This means your phone or desktop are running different major releases of Frida. (One of them is outdated.)

**Comment by pentagramz** [comment]
desktop i just downloaded 

sudo easy_install frida.

so i believe its latest one

**Comment by oleavr** [comment]
Try: `sudo easy_install -U frida`

**Comment by pentagramz** [comment]
ok im installing in progress best match shows 10.2.3

**Comment by pentagramz** [comment]
![screen shot 2017-07-17 at 11 04 04 pm](https://user-images.githubusercontent.com/7072014/28281302-406a0238-6b44-11e7-8b86-4a541e154870.png)

**Comment by pentagramz** [comment]
Im getting this error now

**Comment by pentagramz** [comment]
i have 10.0.15 frida in iphone device

**Comment by pentagramz** [comment]
Any workaround?

**Comment by oleavr** [comment]
Upgrade to the latest on your phone as well.

**Comment by pentagramz** [comment]
can u tell please the latest on phone

**Comment by pentagramz** [comment]
thanks finally frida running fine...:)
