### ISSUE TITLE
Problem during build

### ISSUE THREAD

**Issue by umpacu** [frida/frida#30]
Hi, I'm trying to build frida in Archlinux, following this documentation: http://www.frida.re/docs/building/

The make goes fine, but then I run "make -f Makefile.linux.mk python-64 PYTHON=/usr/bin/python2.7", and this happens:

>FRIDA_HOST=linux-x86_64 ./releng/setup-env.sh
>Downloading and deploying toolchain...
>
>bzip2: Compressed file ends unexpectedly;
>perhaps it is corrupted?  *Possible* reason follows.
>bzip2: Inappropriate ioctl for device
>Input file = (stdin), output file = (stdout)
>
>It is possible that the compressed file(s) have become corrupted.
>You can use the -tvv option to test integrity of such files.
>
>You can use the `bzip2recover' program to attempt to recover
>data from undamaged sections of corrupted files.
>
>tar: Child returned status 2
>tar: Error is not recoverable: exiting now
>releng/common.mk:34: recipe for target 'build/frida-env-linux-x86_64.rc' failed
>make: *** [build/frida-env-linux-x86_64.rc] Error 1

I guess it's because when the script tries to donwload "https://build.frida.re/toolchain-20150401-linux-x86_64.tar.bz2" the server responds with a 500 code.

By the way, I'm trying to build frida because the version installed by easy_install gives me this error when I try to run frida-ps -R:
>Failed to load the Frida native extension: /home/umpacu/.python-eggs/frida-3.0.1-py2.7-linux-x86_64.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
>Please ensure that the extension was compiled for Python 2.7.

From what I read it seems that my python version uses a 4-byte representation for Unicode characters. Is that a known issue? Or do you want me to create a new issue for that?

Thank you very much!

**Comment by oleavr** [comment]
This is unfortunately due to major changes going on in Frida right now; I'm currently in the process of upgrading the third-party dependencies like GLib, V8, capstone, etc. I'm hoping to get most of the remaining changes landed tonight. This is the only big thing left on my backlog for the next release (coming soon), where the Python binaries will be fixed as well.

Sorry for the inconvenience! I'll keep you posted.

**Comment by umpacu** [comment]
No problem! Thank you very much for the quick response!

I'll be waiting to test it.

**Comment by oleavr** [comment]
Feel free to give it a try now (from a fresh `git clone`). Tests are passing again on Windows, Mac and iOS, and I'm currently testing Android, so feedback on Linux would be great!

Cheers!

**Comment by umpacu** [comment]
Sure, I'll try!

Firs of all, I'm usgin Archlinux 64 bits and I would like to build frida with python 2.7. If I have the standard gcc package, the build fails with:
>configure: error: in `/home/umpacu/tmp/frida/build/tmp-linux-i386/frida-gum':
>configure: error: C compiler cannot create executables
>See `config.log' for more details
>Makefile.linux.mk:111: recipe for target 'build/tmp-linux-i386/frida-gum/Makefile' failed
>make: *** [build/tmp-linux-i386/frida-gum/Makefile] Error 77

I guess that's because it needs to compile something for x86, so if I install gcc-multilibs, then the build process goes further, but it still gives me an error, which is this (just the last few lines because the output is huge; if you need more, just tell me):

/home/umpacu/tmp/frida/build/sdk-linux-i386/lib/libv8_base.a(string-builder.o): In function 
`v8::internal::IncrementalStringBuilder::IncrementalStringBuilder(v8::internal::Isolate*)':
string-builder.cc:(.text._ZN2v88internal24IncrementalStringBuilderC2EPNS0_7IsolateE+0xc0): 
undefined reference to `V8_Fatal'
/home/umpacu/tmp/frida/build/sdk-linux-i386/lib/libv8_base.a(string-builder.o): In function 
`v8::internal::IncrementalStringBuilder::Extend()':
string-builder.cc:(.text._ZN2v88internal24IncrementalStringBuilder6ExtendEv+0xc2): undefined 
reference to `V8_Fatal'
/home/umpacu/tmp/frida/build/sdk-linux-i386/lib/libv8_base.a(string-builder.o): In function 
`v8::internal::IncrementalStringBuilder::Finish()':
string-builder.cc:(.text._ZN2v88internal24IncrementalStringBuilder6FinishEv+0x108): 
undefined reference to `V8_Fatal'
/home/umpacu/tmp/frida/build/sdk-linux-i386/lib/libv8_base.a(string-builder.o): In function 
`v8::internal::IncrementalStringBuilder::AppendString(v8::internal::Handle<v8::internal::String>)':
string-builder.cc:(.text._ZN2v88internal24IncrementalStringBuilder12AppendStringENS0_6HandleINS0_6StringEEE+0x110): 
undefined reference to `V8_Fatal'
/home/umpacu/tmp/frida/build/sdk-linux-i386/lib/libv8_base.a(string-builder.o):string-builder.cc:(.text._ZN2v88internal24IncrementalStringBuilder12AppendStringENS0_6HandleINS0_6StringEEE+0x170): 
more undefined references to `V8_Fatal' follow
collect2: error: ld returned 1 exit status
Makefile:481: recipe for target 'libfrida-gumpp-1.0.la' failed
make[3]: *** [libfrida-gumpp-1.0.la] Error 1
make[3]: Leaving directory 
'/home/umpacu/tmp/frida/build/tmp-linux-i386/frida-gum/bindings/gumpp'
Makefile:374: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/umpacu/tmp/frida/build/tmp-linux-i386/frida-gum/bindings'
Makefile:503: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/umpacu/tmp/frida/build/tmp-linux-i386/frida-gum'
Makefile.linux.mk:115: recipe for target 
'build/frida-linux-i386/lib/pkgconfig/frida-gum-1.0.pc' failed
make: *** [build/frida-linux-i386/lib/pkgconfig/frida-gum-1.0.pc] Error 2

Any idea?

**Comment by oleavr** [comment]
Thanks! Turns out this was an issue with the prebuilt dependencies where libraries were passed to the linker in the wrong order. I also discovered some other issues that have now been fixed. I'm doing a full rebuild across all platforms now, and I'll let you know as soon as it's been uploaded.

**Comment by umpacu** [comment]
Great. I'll be waiting to test it.

Cheers!

**Comment by oleavr** [comment]
It should now be ready for testing; just give it a spin on a fresh git clone.

Thanks for your patience!

**Comment by umpacu** [comment]
I've created a virtualenv setup to use python2.7 because in Arch the default version is python3, and it was giving me an error during the compilation.

But other than that, it works great!

The build is complete, so now I'll try to use frida, but that's another thing. I can close this issue.

Thank you so much!

**Comment by oleavr** [comment]
Yay, glad to hear! The python3 issue might be a missing development package (check `config.log`).

Cheers!

**Comment by piopro** [comment]
Hi, I have got the error trying to install Frida for Windows: Failed to load the Frida native extension: DLL load failed: ..... Please ensure that the extension was compiled for Python 3.x.

The install procedure was:
1) Downloaded https://www.python.org/ftp/python/3.6.0/python-3.6.0a3-amd64.exe
2) Executed python-3.6.0a3-amd64.exe
3) Downloaded https://bootstrap.pypa.io/ez_setup.py
4) Executed python ez_setup.py --insecure 
5) Executed pip install Frida

What should I do to correct?

**Comment by piopro** [comment]
Solved this problem replacing Python distribution by this: https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe
