### ISSUE TITLE
new Promise is giving SyntaxError

### ISSUE THREAD

**Issue by Hams1** [frida/frida#306]
Trying the RPC example in frida documents is giving me:
```
 File "remote.py", line 19, in <module>
    script = session.create_script(fd.read())
  File "D:\Programs\Python36-32\lib\site-packages\frida\core.py", line 182, in c
reate_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.InvalidArgumentError: gDBus.Error:re.frida.Error.InvalidArgument: Script(l
ine 34): SyntaxError: parse error
```

Specifically this line `return new Promise(resolve => {`
apparently, the `new Promise` syntax is not accepted by frida

**Comment by snooze6** [comment]
Try it without using lambdas, like this:

```javascript
   sub: function (a, b) {
        return new Promise(function (resolve, reject) {
            setTimeout(function () {
                resolve(a - b);
            }, 100);
        });
    }
```

Although I like lambdas too they seem to be unsupported on Frida agents at this moment.

**Comment by oleavr** [comment]
You can also switch to the V8 runtime by passing `--enable-jit` (or calling `session.enable_jit()`), which supports the latest and greatest syntax. For non-trivial agents I would recommend using [frida-compile](https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3) as it will allow you to use the latest syntax, and also make it possible to compose your agent from multiple files through `require()`, and give you access to thousands of existing modules from npm. (Including the ones that are Frida-specific.)

**Comment by jkwolf** [comment]
Traceback (most recent call last):
  File "midu.py", line 30, in <module>
    script = session.create_script(src)
  File "C:\Python27\lib\site-packages\frida\core.py", line 148, in create_script

    return Script(self._impl.create_script(*args, **kwargs))
frida.InvalidArgumentError: gDBus.Error:re.frida.Error.InvalidArgument: Script(l
ine 5): SyntaxError: invalid token

what happend?  bro
