### ISSUE TITLE
https://build.frida.re/sdk-20170727-linux-arm.tar.bz2 404 not found while make server-arm

### ISSUE THREAD

**Issue by coderiderlin** [frida/frida#309]
e@ubuntu32:~/projects/frida$ make -f Makefile.sdk.mk

Success! Here's your SDK: build/sdk-linux-x86.tar.bz2

It will be picked up automatically if you now proceed to build Frida.

e@ubuntu32:~/projects/frida$ make server-arm
make[1]: Entering directory '/home/e/projects/frida'
FRIDA_HOST=linux-x86 \
	FRIDA_OPTIMIZATION_FLAGS="-Os" \
	FRIDA_DEBUG_FLAGS="-g3" \
	FRIDA_ASAN=no \
	./releng/setup-env.sh
Environment created. To enter:
# source /home/e/projects/frida/build/frida-env-linux-x86.rc
. build/frida-env-linux-x86.rc && cd frida-gum/bindings/gumjs && npm install
/bin/sh: 1: /npm: not found
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
FRIDA_HOST=linux-arm \
	FRIDA_OPTIMIZATION_FLAGS="-Os" \
	FRIDA_DEBUG_FLAGS="-g3" \
	FRIDA_ASAN=no \
	./releng/setup-env.sh
**Downloading and deploying SDK for linux-arm...
command is: [curl -sS https://build.frida.re/sdk-20170727-linux-arm.tar.bz2**

Bummer. It seems we don't have a prebuilt SDK for your system.

Please go ahead and build it yourself:
$ make -f Makefile.sdk.mk

Afterwards just retry and the SDK will get picked up automatically.

releng/common.mk:46: recipe for target 'build/frida-env-linux-arm.rc' failed
make[1]: *** [build/frida-env-linux-arm.rc] Error 1
make[1]: Leaving directory '/home/e/projects/frida'
Makefile:2: recipe for target 'server-arm' failed
make: *** [server-arm] Error 2

**Comment by oleavr** [comment]
You need to specify which OS/arch to build for:
`make -f Makefile.sdk.mk FRIDA_HOST=linux-arm`
(It defaults to your local system otherwise.)

Also, you need Node.js (recent version like 8.x) installed – make sure `node` and `npm` are on your `PATH`.

**Comment by coderiderlin** [comment]
thanks,i 've built the linux-arm sdk and it works.by the way,i don't know why the scripts use /npm not /usr/bin/npm,fixed this by ln -s /usr/bin/npm /npm.

**Comment by oleavr** [comment]
Glad to hear! The `npm` issue is because our [auto-detection](https://github.com/frida/frida/blob/50f7f12caeae2d761087c0247efb45764c0f19dc/config.mk#L19-L21) fails. Sounds like `which node` doesn't result in a match on your system. Are you running the latest Node.js 8.x?

**Comment by coderiderlin** [comment]
yeah the node has been installed right now
e@ubuntu32:~/projects/frida$ dirname `which node`
/usr/bin
maybe i did install it after that.

by the way ,how can i see the real gcc command while compile and link the frida-server?i 've compile frida-server for armhf but the glibc library version is newer than the system one,and i add the -rpath option

> LDFLAGS="$host_arch_flags -Wl,--gc-sections -Wl,-rpath,/boxer/lib -Wl,--dynamic-linker,/boxer/lib/ld-linux-armhf.so.3"

 to **LDFLAGS in /releng/setup.env (line 234)** to  relocate the search library path but it doesn't work.
Here is the **LD_TRACE_LOADED_OBJECTS=1** option result,seem like the same as above

```
root@cubieboard2:/boxer# LD_TRACE_LOADED_OBJECTS=1 /boxer/frida-server
/boxer/frida-server: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.17' not found (required by /boxer/frida-server)
        libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xb6f10000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6f05000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6eea000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6e06000)
        /boxer/lib/ld-linux-armhf.so.3 (0xb6f28000)
root@cubieboard2:/boxer#
```

What i think is if the rpath option must be in the frist of gcc option?

**Comment by coderiderlin** [comment]
well,i've tried LD_LIBRARY_PATH and it work,i mean the frida-server was up,but attach faild cause:

>`# LD_LIBRARY_PATH='/boxer/lib' ./frida-server --version
> 10.3.8

> `# LD_LIBRARY_PATH='/boxer/lib' ./frida-server -l 0.0.0.0
> Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:2059:frida_resolve_library_function: assertion failed (local_library_path == remote_library_path): ("/boxer/lib/libc-2.23.so" == "/lib/arm-linux-gnueabihf/libc-2.15.so")

i'm going to downgrade the compiler..

**Comment by oleavr** [comment]
@coderiderlin Android systems with qemu-user (e.g. native x86 emulating arm code) are not currently supported. Supporting them is not something I need personally or at work, so I'm hoping that someone will eventually step up and contribute support for it.

**Comment by coderiderlin** [comment]
what i trying to work with is lubuntu system in armhf arch,not android.unfortunately i don't have the corresponds libc6-dev-armhf-cros version 2.17 (cuz the system's libc.so.6 is GLIBC_ 2.17) to build.

for now i'm using [this server_armhf](https://build.frida.re/frida/linux/armhf/bin/frida-server) with frida8.0.0 (pip install frida==8.0.0) and it works fine.

however ,i want to know how can i  build one with an old gcc version with the corresponds glibc?
and as i know,the elf linked as static can run on that system,can frida link with static?what should i do if it can? thanks.
