### ISSUE TITLE
Create instance of abstract java class and override function

### ISSUE THREAD

**Issue by 5andr0** [frida/frida#3096]
Is it possible to create an instance of an abstract class and override functions just for the instance?

    public abstract class AbstractClass {
        public void OverrideCallback() {
        }
    }
    
I would like to simulate this:

    new AbstractClass() { 
                @Override
                public final OverrideCallback() {
                    // ...
                }
            };

I tried the following, but as I expected it overrides the AbstractClass function for all instances.

    const ac =  Java.use('AbstractClass');
    const acInstance = ac.$new();
    acInstance.OverrideCallback.implementation = function () {
        console.log('intercepted');
    }
    acInstance.OverrideCallback(); // prints intercepted
    const acAnotherInstance = ac.$new();
    acAnotherInstance.OverrideCallback(); // also prints intercepted

If this is not possible, please regard this as a feature request!

**Comment by commonuserlol** [comment]
You have to use `Java.registerClass` with `implements: [Java.use("AbstractClass")]`

**Comment by 5andr0** [comment]
> Java.registerClass

Thanks for the hint to Java.registerClass! To derive from an abstract class it would be `superClass` instead of `implements`.
However I'm running into some issues there:
In the docs https://frida.re/docs/javascript-api/#java 
```
checkClientTrusted(chain, authType) {
      console.log('checkClientTrusted');
    },
```
this function is declared without the object defining argumentTypes. Frida doesn't recognize the amount of parameters and thinks it has no arguments:
```
Error: checkClientTrusted(): argument types do not match any of:
        .overload()
    at X (frida/node_modules/frida-java-bridge/lib/class-factory.js:626)
    at value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1145)
    at e (frida/node_modules/frida-java-bridge/lib/class-factory.js:610)
```
I have to explicitly use the {returnType, argumentTypes, implementation} syntax.
As soon as I use superClass I'm getting this error:
```
cannot read property 'replace' of undefined
    at S (frida/node_modules/frida-java-bridge/lib/types.js:369)
    at registerClass (frida/node_modules/frida-java-bridge/lib/class-factory.js:206)
    at registerClass (frida/node_modules/frida-java-bridge/index.js:283)
```

I'll do some more debugging why this is happening, but maybe someone knows whats up
