### ISSUE TITLE
Spawn time out

### ISSUE THREAD

**Issue by MuhammadMusayiab** [frida/frida#3246]
I am using latest release of frida server android arm_64 architecture and its giving me spawn time out error

**Comment by xitake** [comment]
I'm having the same problem. Release 16.5.2.
Using gadget on a jailed device, it remains in "Spawning `package name`..."
In the device, the app restarts and open up with "Waiting for Debugger" message.
After some minutes, it times out.

**Comment by MuhammadMusayiab** [comment]
I just solved the issue by my self

Check device architecture
` adb shell getprop ro.product.cpu.abi `

Install the latest frida server version and frida tool

su
setprop persist.device_config.runtime_native.usap_pool_enabled false
getprop | grep usap // check this is set to false or not

run frida server 

adb push {server's path} /data/local/tmp
adb shell
su
cd /data/local/tmp
chmod+x ./{frida-server}
./{frida-server}

run the following command

frida -f binary name -U -l script-path -t 60
