### ISSUE TITLE
frida-server  runs in ios jb device reports: dyld: incompatible cpu-subtype: 0x80000002 in /usr/sbin/frida-server

### ISSUE THREAD

**Issue by johnwas** [frida/frida#3249]
Install frida pkg (version 16.5.4) in a ios jb device iphone 11 ( IOS 13.6.1, Jb by :  unc0ver).   I can't start frida-server:

#dpkg -i frida_16.5.4_iphoneos-arm.deb
Selecting previously unselected package re.frida.server.
(Reading database ... 8315 files and directories currently installed.)
Preparing to unpack frida_16.5.4_iphoneos-arm.deb ...
Unpacking re.frida.server (16.5.4) ...
Setting up re.frida.server (16.5.4) ...
 
#/usr/sbin/frida-server 
dyld: incompatible cpu-subtype: 0x80000002 in /usr/sbin/frida-server
Abort trap: 6

**Comment by pig837** [comment]
I haven't checked it myself, but I suspect it's an ABI issue.

It is said that you need to build and use it in Xcode 11 when running iOS 13 or lower.

https://x.com/fridadotre/status/1366669060432355328?lang=en

**Comment by miticollo** [comment]
@johnwas Thank you for having used my script! You was right, there was an error with the order of the args passed to `releng/mkfatmacho.py`. I [fixed it](https://gist.github.com/miticollo/12e3fff5ba8fab7dd707c874105a508f#file-build_frida-sh-L177-L181)! Furthermore, to explain this issue deeper: starting to Frida 16.4.0 your iOS version is no more supported. In particular the support for old ABI is (temporarily) suspended. Look the body of [this commit](https://github.com/frida/frida/commit/fe5017001b1d568ff0ac7ec5f0fc2d95a2980aaf) to see the reason! Finally, if you are interested [here](https://twitter.com/elihweilrahc13/status/1344126498777812992) you can find what old ABI means.
