### ISSUE TITLE
Windows build errors

### ISSUE THREAD

**Issue by christiancoleman** [frida/frida#327]
Hi there,

I'm using the documentation found at https://www.frida.re/docs/building/#windows and I'm getting the following errors while building. I've tried to pull down the repository a couple times and ensuring nothing was corrupted in the process. I'm sure I've been following the steps to the letter so I'm hoping by bringing this up I can either help with documentation or find out what I'm doing incorrectly. I've started to look at a few of the errors. One in particular is found in the output section that shows an issue with generate-bindings.py. It appears to be trying to interpret the type 'GumAddress from,' so for some reason the parsing of that type is failing and I'm wondering if it might be due to an unsual character in one of my PATH variables or something. Hope to hear from someone. 

Thanks.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"cmd.exe" exited with code 1.	gumjs-32	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171	
Error (active)	E1696	cannot open source file "frida-core.h"	frida-core	c:\workspace_git\frida\frida-core\src\frida-glue.c	1	
Error (active)	E0020	identifier "frida_on_pending_garbage" is undefined	frida-core	c:\workspace_git\frida\frida-core\src\frida-glue.c	18	
Error	MSB6006	"cmd.exe" exited with code 1.	gumjs-64	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171	
Error	LNK1104	cannot open file 'C:\workspace_git\frida\build\tmp-windows\Win32-Debug\gumjs-32\gumjs-32.lib'	frida-agent-32	C:\workspace_git\frida\frida-core\lib\agent\LINK	1	
Error	LNK1104	cannot open file 'C:\workspace_git\frida\build\tmp-windows\x64-Debug\gumjs-64\gumjs-64.lib'	frida-agent-64	C:\workspace_git\frida\frida-core\lib\agent\LINK	1	
Error	LNK1104	cannot open file 'gumjs-32.lib'	gum-tests	C:\workspace_git\frida\frida-gum\tests\LINK	1	
Error	MSB6006	"cmd.exe" exited with code 1.	frida-core	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171	
Error		Package 'frida-core' not found in specified Vala API directories or GObject-Introspection GIR directories	frida-server	C:\workspace_git\frida\frida-core\CUSTOMBUILD	1	
Error		Package 'frida-core' not found in specified Vala API directories or GObject-Introspection GIR directories	frida-tests	C:\workspace_git\frida\frida-core\tests\CUSTOMBUILD	1	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-python27	C:\workspace_git\frida\frida-python\src\_frida.c	7	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-python36	C:\workspace_git\frida\frida-python\src\_frida.c	7	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-clr	C:\workspace_git\frida\frida-clr\src\Runtime.cpp	3	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-clr	c:\workspace_git\frida\frida-clr\src\Device.hpp	6	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-clr	c:\workspace_git\frida\frida-clr\src\Marshal.hpp	6	
Error		Package 'frida-core' not found in specified Vala API directories or GObject-Introspection GIR directories	frida-gadget	C:\workspace_git\frida\frida-core\CUSTOMBUILD	1	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-clr	c:\workspace_git\frida\frida-clr\src\DeviceManager.hpp	5	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-clr	c:\workspace_git\frida\frida-clr\src\Process.hpp	6	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-clr	c:\workspace_git\frida\frida-clr\src\Script.hpp	5	
Error	C1083	Cannot open include file: 'frida-core.h': No such file or directory	frida-clr	c:\workspace_git\frida\frida-clr\src\Session.hpp	5	
`

The associated output is:

`1>------ Build started: Project: frida-resource-compiler, Configuration: Debug Win32 ------
1>Compiling vala code
1>resource-compiler.c
1>frida-resource-compiler.vcxproj -> C:\workspace_git\frida\build\tmp-windows\Win32-Debug\frida-resource-compiler\frida-resource-compiler.exe
1>frida-resource-compiler.vcxproj -> C:\workspace_git\frida\build\tmp-windows\Win32-Debug\frida-resource-compiler\frida-resource-compiler.pdb (Full PDB)
2>------ Build started: Project: frida-pipe-32, Configuration: Debug Win32 ------
2>Compiling vala code
2>pipe-sddl.c
2>pipe-windows.c
2>pipe.c
2>Generating Code...
2>frida-pipe-32.vcxproj -> C:\workspace_git\frida\build\tmp-windows\Win32-Debug\frida-pipe-32\frida-pipe-32.lib
3>------ Build started: Project: frida-pipe-64, Configuration: Debug x64 ------
3>Compiling vala code
3>pipe-sddl.c
3>pipe-windows.c
3>pipe.c
3>Generating Code...
3>frida-pipe-64.vcxproj -> C:\workspace_git\frida\build\tmp-windows\x64-Debug\frida-pipe-64\frida-pipe-64.lib
4>------ Build started: Project: gum-32, Configuration: Debug Win32 ------
4>gumspinlock-ia32-msc.c
4>gumwallclocksampler.c
4>gumsampler.c
4>gumprofilereport.c
4>gumprofiler.c
4>gummalloccountsampler.c
4>gumcyclesampler-x86.c
4>gumcallcountsampler.c
4>gumbusycyclesampler-windows.c
4>gumsanitychecker.c
4>gumpagepool.c
4>guminstancetracker.c
4>gumheapapi.c
4>gumcobjecttracker.c
4>gumcobject.c
4>gumboundschecker.c
4>gumallocatorprobe.c
4>gumallocationtracker.c
4>gumallocationgroup.c
4>gumallocationblock.c
4>Generating Code...
4>Compiling...
4>gumsymbolutil-dbghelp.c
4>gumdbghelpbacktracer.c
4>gumdbghelp.c
4>gummemoryaccessmonitor-windows.c
4>gumexceptor-windows.c
4>gumprocess-windows.c
4>gummemory-windows.c
4>gumtls-windows.c
4>gumstalker-x86.c
4>guminterceptor-x86.c
4>gumcpucontext-x86.c
4>gumarm64relocator.c
4>gumarm64writer.c
4>gumarmreg.c
4>gumthumbrelocator.c
4>gumthumbwriter.c
4>gumarmrelocator.c
4>gumarmwriter.c
4>gumx86writer.c
4>gumx86relocator.c
4>Generating Code...
4>Compiling...
4>gumx86reader.c
4>gumx86backtracer.c
4>gumstalker.c
4>gumreturnaddress.c
4>gumprocess.c
4>gumprintf.c
4>gummodulemap.c
4>gummoduleapiresolver.c
4>gummetalhash.c
4>gummetalarray.c
4>gummemorymap.c
4>gummemory.c
4>gumlibc.c
4>gumkernel.c
4>guminvocationlistener.c
4>guminvocationcontext.c
4>guminterceptor.c
4>gumeventsink.c
4>gumexceptor.c
4>gumcodesegment.c
4>Generating Code...
4>Compiling...
4>gumcodeallocator.c
4>gumcloak.c
4>gumbacktracer.c
4>gumapiresolver.c
4>gum.c
4>Generating Code...
4>gum-32.vcxproj -> C:\workspace_git\frida\build\tmp-windows\Win32-Debug\gum-32\gum-32.lib
5>------ Build started: Project: gum-64, Configuration: Debug x64 ------
5>gumspinlock-amd64-msc.c
5>gumwallclocksampler.c
5>gumsampler.c
5>gumprofilereport.c
5>gumprofiler.c
5>gummalloccountsampler.c
5>gumcyclesampler-x86.c
5>gumcallcountsampler.c
5>gumbusycyclesampler-windows.c
5>gumsanitychecker.c
5>gumpagepool.c
5>guminstancetracker.c
5>gumheapapi.c
5>gumcobjecttracker.c
5>gumcobject.c
5>gumboundschecker.c
5>gumallocatorprobe.c
5>gumallocationtracker.c
5>gumallocationgroup.c
5>gumallocationblock.c
5>Generating Code...
5>Compiling...
5>gumsymbolutil-dbghelp.c
5>gumdbghelpbacktracer.c
5>gumdbghelp.c
5>gummemoryaccessmonitor-windows.c
5>gumexceptor-windows.c
5>gumprocess-windows.c
5>gummemory-windows.c
5>gumtls-windows.c
5>gumstalker-x86.c
5>guminterceptor-x86.c
5>gumcpucontext-x86.c
5>gumarm64relocator.c
5>gumarm64writer.c
5>gumarmreg.c
5>gumthumbrelocator.c
5>gumthumbwriter.c
5>gumarmrelocator.c
5>gumarmwriter.c
5>gumx86writer.c
5>gumx86relocator.c
5>Generating Code...
5>Compiling...
5>gumx86reader.c
5>gumx86backtracer.c
5>gumstalker.c
5>gumreturnaddress.c
5>gumprocess.c
5>gumprintf.c
5>gummodulemap.c
5>gummoduleapiresolver.c
5>gummetalhash.c
5>gummetalarray.c
5>gummemorymap.c
5>gummemory.c
5>gumlibc.c
5>gumkernel.c
5>guminvocationlistener.c
5>guminvocationcontext.c
5>guminterceptor.c
5>gumeventsink.c
5>gumexceptor.c
5>gumcodesegment.c
5>Generating Code...
5>Compiling...
5>gumcodeallocator.c
5>gumcloak.c
5>gumbacktracer.c
5>gumapiresolver.c
5>gum.c
5>Generating Code...
5>gum-64.vcxproj -> C:\workspace_git\frida\build\tmp-windows\x64-Debug\gum-64\gum-64.lib
6>------ Build started: Project: gumjs-32, Configuration: Debug Win32 ------
6>Generating bindings
6>Traceback (most recent call last):
6>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2620, in <module>
6>    generate_and_write_bindings(source_dir, output_dir)
6>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 38, in generate_and_write_bindings
6>    bindings = generate_bindings(name, arch, flavor, api_header, options)
6>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 132, in generate_bindings
6>    api = parse_api(name, flavor, api_header, options)
6>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2582, in parse_api
6>    args = [parse_arg(raw_arg) for raw_arg in raw_args]
6>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2600, in parse_arg
6>    return MethodArgument(raw_type, name)
6>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2527, in __init__
6>    raise ValueError("Unhandled type: {0}".format(type))
6>ValueError: Unhandled type: GumAddress from,
6>     GumAddress
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
6>Done building project "gumjs-32.vcxproj" -- FAILED.
7>------ Build started: Project: winjector-helper-32, Configuration: Debug Win32 ------
7>Compiling vala code
7>session.c
7>winjector-types.c
7>winjector-helper.c
7>Generating Code...
7>winjector-wait-handle-source.c
7>winjector-helper-services.c
7>winjector-helper-core.c
7>Generating Code...
7>winjector-helper-32.vcxproj -> C:\workspace_git\frida\build\tmp-windows\Win32-Debug\winjector-helper-32\winjector-helper-32.exe
7>winjector-helper-32.vcxproj -> C:\workspace_git\frida\build\tmp-windows\Win32-Debug\winjector-helper-32\winjector-helper-32.pdb (Full PDB)
8>------ Build started: Project: frida-agent-32, Configuration: Debug Win32 ------
8>Compiling vala code
8>session.c
8>script-engine.c
8>agent.c
8>Generating Code...
8>agent-glue.c
8>LINK : fatal error LNK1104: cannot open file 'C:\workspace_git\frida\build\tmp-windows\Win32-Debug\gumjs-32\gumjs-32.lib'
8>Done building project "frida-agent-32.vcxproj" -- FAILED.
9>------ Build started: Project: gumjs-64, Configuration: Debug x64 ------
9>Generating bindings
9>Traceback (most recent call last):
9>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2620, in <module>
9>    generate_and_write_bindings(source_dir, output_dir)
9>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 38, in generate_and_write_bindings
9>    bindings = generate_bindings(name, arch, flavor, api_header, options)
9>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 132, in generate_bindings
9>    api = parse_api(name, flavor, api_header, options)
9>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2582, in parse_api
9>    args = [parse_arg(raw_arg) for raw_arg in raw_args]
9>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2600, in parse_arg
9>    return MethodArgument(raw_type, name)
9>  File "C:\workspace_git\frida\frida-gum\bindings\gumjs\generate-bindings.py", line 2527, in __init__
9>    raise ValueError("Unhandled type: {0}".format(type))
9>ValueError: Unhandled type: GumAddress from,
9>     GumAddress
9>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
9>Done building project "gumjs-64.vcxproj" -- FAILED.
10>------ Build started: Project: winjector-helper-64, Configuration: Debug x64 ------
10>Compiling vala code
10>session.c
10>winjector-types.c
10>winjector-helper.c
10>Generating Code...
10>winjector-wait-handle-source.c
10>winjector-helper-services.c
10>winjector-helper-core.c
10>Generating Code...
10>winjector-helper-64.vcxproj -> C:\workspace_git\frida\build\tmp-windows\x64-Debug\winjector-helper-64\winjector-helper-64.exe
10>winjector-helper-64.vcxproj -> C:\workspace_git\frida\build\tmp-windows\x64-Debug\winjector-helper-64\winjector-helper-64.pdb (Full PDB)
11>------ Build started: Project: gumpp, Configuration: Debug Win32 ------
11>symbolutil.cpp
11>sanitychecker.cpp
11>sampler.cpp
11>runtime.cpp
11>returnaddress.cpp
11>profiler.cpp
11>invocationlistener.cpp
11>interceptor.cpp
11>backtracer.cpp
11>Generating Code...
11>   Creating library C:\workspace_git\frida\build\frida-windows\Win32-Debug\bin\gumpp.lib and object C:\workspace_git\frida\build\frida-windows\Win32-Debug\bin\gumpp.exp
11>gumpp.vcxproj -> C:\workspace_git\frida\build\frida-windows\Win32-Debug\bin\gumpp.dll
11>gumpp.vcxproj -> C:\workspace_git\frida\build\frida-windows\Win32-Debug\bin\gumpp.pdb (Partial PDB)
12>------ Build started: Project: gumpp-static, Configuration: Debug Win32 ------
12>symbolutil.cpp
12>sanitychecker.cpp
12>sampler.cpp
12>runtime.cpp
12>returnaddress.cpp
12>profiler.cpp
12>invocationlistener.cpp
12>interceptor.cpp
12>backtracer.cpp
12>Generating Code...
12>gumpp-static.vcxproj -> C:\workspace_git\frida\build\frida-windows\Win32-Debug\bin\gumpp-static.lib
13>------ Build started: Project: frida-agent-64, Configuration: Debug x64 ------
13>Compiling vala code
13>session.c
13>script-engine.c
13>agent.c
13>Generating Code...
13>agent-glue.c
13>LINK : fatal error LNK1104: cannot open file 'C:\workspace_git\frida\build\tmp-windows\x64-Debug\gumjs-64\gumjs-64.lib'
13>Done building project "frida-agent-64.vcxproj" -- FAILED.
14>------ Build started: Project: gum-tests, Configuration: Debug Win32 ------
14>testutil.c
14>fakeeventsink.c
14>fakebacktracer.c
14>dummyclasses.c
14>sampler.c
14>profiler.c
14>fakesampler.c
14>gumtest.c
14>symbolutil.c
14>process.c
14>stalker-x86.c
14>interceptor.c
14>lowlevel-helpers.c
14>sanitychecker.c
14>pagepool.c
14>instancetracker.c
14>cobjecttracker.c
14>boundschecker.c
14>allocatorprobe.c
14>allocationtracker.c
14>Generating Code...
14>Compiling...
14>kscript.c
14>script.c
14>memoryaccessmonitor.c
14>memory.c
14>cloak.c
14>tls.c
14>backtracer.c
14>apiresolver.c
14>relocator.c
14>codewriter.c
14>thumbwriter.c
14>thumbrelocator.c
14>armwriter.c
14>armrelocator.c
14>arm64writer.c
14>arm64relocator.c
14>Generating Code...
14>backtracer.cxx
14>allocatorprobex.cxx
14>LINK : fatal error LNK1104: cannot open file 'gumjs-32.lib'
14>Done building project "gum-tests.vcxproj" -- FAILED.
15>------ Build started: Project: frida-core, Configuration: Debug Win32 ------
15>Serializing Agent resources
15>Error opening file C:\workspace_git\frida\build\tmp-windows\Win32-Debug\frida-agent-32\frida-agent-32.dll: No such file or directory
15>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
15>Done building project "frida-core.vcxproj" -- FAILED.
16>------ Build started: Project: frida-tests, Configuration: Debug Win32 ------
16>Compiling vala code
16>CUSTOMBUILD : error : Package 'frida-core' not found in specified Vala API directories or GObject-Introspection GIR directories
16>Compilation failed: 1 error(s), 0 warning(s)
16>Done building project "frida-tests.vcxproj" -- FAILED.
17>------ Build started: Project: frida-server, Configuration: Debug Win32 ------
17>Compiling vala code
17>CUSTOMBUILD : error : Package 'frida-core' not found in specified Vala API directories or GObject-Introspection GIR directories
17>Compilation failed: 1 error(s), 0 warning(s)
17>Done building project "frida-server.vcxproj" -- FAILED.
18>------ Build started: Project: frida-clr, Configuration: Debug Win32 ------
18>Runtime.cpp
18>src\Runtime.cpp(3): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
18>Device.cpp
18>c:\workspace_git\frida\frida-clr\src\Device.hpp(6): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
18>Marshal.cpp
18>c:\workspace_git\frida\frida-clr\src\Marshal.hpp(6): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
18>DeviceManager.cpp
18>c:\workspace_git\frida\frida-clr\src\DeviceManager.hpp(5): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
18>Process.cpp
18>c:\workspace_git\frida\frida-clr\src\Process.hpp(6): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
18>Script.cpp
18>c:\workspace_git\frida\frida-clr\src\Script.hpp(5): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
18>Session.cpp
18>c:\workspace_git\frida\frida-clr\src\Session.hpp(5): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
18>Generating Code...
18>Done building project "frida-clr.vcxproj" -- FAILED.
19>------ Build started: Project: frida-python27, Configuration: Debug Win32 ------
19>Installing frida package
19>C:\workspace_git\frida\frida-python\src\frida\application.py
19>C:\workspace_git\frida\frida-python\src\frida\core.py
19>C:\workspace_git\frida\frida-python\src\frida\discoverer.py
19>C:\workspace_git\frida\frida-python\src\frida\kill.py
19>C:\workspace_git\frida\frida-python\src\frida\lsd.py
19>C:\workspace_git\frida\frida-python\src\frida\ps.py
19>C:\workspace_git\frida\frida-python\src\frida\repl.py
19>C:\workspace_git\frida\frida-python\src\frida\tracer.py
19>C:\workspace_git\frida\frida-python\src\frida\__init__.py
19>        9 file(s) copied.
19>_frida.c
19>src\_frida.c(7): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
19>Done building project "frida-python27.vcxproj" -- FAILED.
20>------ Build started: Project: frida-python36, Configuration: Debug Win32 ------
20>Installing frida package
20>C:\workspace_git\frida\frida-python\src\frida\application.py
20>C:\workspace_git\frida\frida-python\src\frida\core.py
20>C:\workspace_git\frida\frida-python\src\frida\discoverer.py
20>C:\workspace_git\frida\frida-python\src\frida\kill.py
20>C:\workspace_git\frida\frida-python\src\frida\lsd.py
20>C:\workspace_git\frida\frida-python\src\frida\ps.py
20>C:\workspace_git\frida\frida-python\src\frida\repl.py
20>C:\workspace_git\frida\frida-python\src\frida\tracer.py
20>C:\workspace_git\frida\frida-python\src\frida\__init__.py
20>        9 file(s) copied.
20>_frida.c
20>src\_frida.c(7): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory
20>Done building project "frida-python36.vcxproj" -- FAILED.
21>------ Build started: Project: frida-gadget, Configuration: Debug Win32 ------
21>Compiling vala code
21>Compilation failed: 1 error(s), 0 warning(s)
21>CUSTOMBUILD : error : Package 'frida-core' not found in specified Vala API directories or GObject-Introspection GIR directories
21>Done building project "frida-gadget.vcxproj" -- FAILED.
========== Build: 9 succeeded, 12 failed, 3 up-to-date, 0 skipped ==========
`

**Comment by christiancoleman** [comment]
Whoops forgot to mention the versions of the programs I'm using:

Windows 10 Pro 64-bit version 1703
Visual Studio 2017 version 15.3.1
Node v6.11.2
git version 2.13.3.windows.1
Python 2.7 and Python 3.6 both downloaded separately before this endeavor. I made sure that 2.7 was listed first in my PATH via python --version. I notice that one of the build processes downloads both 2.7 and 3.6 at one point so I'm not sure how much this matters anymore.

**Comment by o0xmuhe** [comment]
@christiancoleman  do you fix it? It seems I got the same error as you..

**Comment by lchnider** [comment]
same here :(

**Comment by christiancoleman** [comment]
@lchnider it's been awhile, but the discussion in https://github.com/frida/frida-gum/pull/242 cleared up why this happens. I had performed this command because typically it is what I want:

`git config --global core.autocrlf true`

But you can - for this repo - run this:

`git config core.autocrlf false`

and it should get rid of some of these errors.

**Comment by christiancoleman** [comment]
@lchnider it's been awhile, but the discussion in https://github.com/frida/frida-gum/pull/242 cleared up why this happens. I had performed this command because typically it is what I want:

`git config --global core.autocrlf true`

But you can - for this repo - run this:

`git config core.autocrlf false`

and it should get rid of some of these errors.
