### ISSUE TITLE
Failed to enumerate processes: failed to open USB device: Operation not supported or unimplemented on this platform

### ISSUE THREAD

**Issue by datph4mmm** [frida/frida#3287]
![image](https://github.com/user-attachments/assets/1dd05aad-e644-4580-8e4c-d221f8a06039)

is there any way to solve this? IOS 15.8.2 device

**Comment by datph4mmm** [comment]
done

**Comment by Jane151013** [comment]
Hi,I've met the same error.Can you tell me how to solve this?TKS

**Comment by Jane151013** [comment]
degrade the frida version to 16.5.2 or lower,then solved
