### ISSUE TITLE
can't execute frida-ps

### ISSUE THREAD

**Issue by flycrane** [frida/frida#33]
Hi guys,

I got following error when I using frida-ps after I installed it with "sudo easy_install frida" as the doc suggested, any idea why and can I fixed please? thank you

$ sudo frida-ps -R
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/txia/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)

***
Failed to load the Frida native extension: /home/txia/.python-eggs/frida-3.0.1-py2.7-linux-i686.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
Please ensure that the extension was compiled for Python 2.7.
***

Traceback (most recent call last):
  File "/usr/local/bin/frida-ps", line 9, in <module>
    load_entry_point('frida==3.0.1', 'console_scripts', 'frida-ps')()
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-i686.egg/frida/ps.py", line 58, in main
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-i686.egg/frida/application.py", line 81, in run
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-i686.egg/frida/__init__.py", line 84, in get_device_manager
ImportError: /home/txia/.python-eggs/frida-3.0.1-py2.7-linux-i686.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String

**Comment by oleavr** [comment]
Hi,

Thanks for reporting! This is a known issue with the current Linux binaries that will be fixed in the upcoming release (which sadly is way behind scheduled). For now I'm afraid you'll have to build Frida yourself if you want to play with it on Linux. Sorry for the inconvenience!

Cheers

**Comment by flycrane** [comment]
Hi oleavr,

Thanks for the response, yes I was  trying building frida myself but met problem as well, haven't figured out why after a long time searching, any advice please?

/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(hydrogen.o): In function `v8::internal::HGraph::SourcePositionToScriptPosition(v8::internal::SourcePosition)':
hydrogen.cc:(.text._ZN2v88internal6HGraph30SourcePositionToScriptPositionENS0_14SourcePositionE+0x63): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(type-feedback-vector.o): In function `v8::internal::Handle<v8::internal::TypeFeedbackVector> v8::internal::TypeFeedbackVector::Allocate<v8::internal::ZoneFeedbackVectorSpec>(v8::internal::Isolate*, v8::internal::ZoneFeedbackVectorSpec const*)':
type-feedback-vector.cc:(.text._ZN2v88internal18TypeFeedbackVector8AllocateINS0_22ZoneFeedbackVectorSpecEEENS0_6HandleIS1_EEPNS0_7IsolateEPKT_[_ZN2v88internal18TypeFeedbackVector8AllocateINS0_22ZoneFeedbackVectorSpecEEENS0_6HandleIS1_EEPNS0_7IsolateEPKT_]+0x27f): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o): In function `v8::internal::compiler::RegisterAllocator::ComputeLiveOut(v8::internal::compiler::InstructionBlock const*)':
register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator14ComputeLiveOutEPKNS1_16InstructionBlockE+0x182): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o): In function `v8::internal::compiler::RegisterAllocator::ResolveControlFlow()':
register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator18ResolveControlFlowEv+0x2d1): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o):register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator22FindOptimalSpillingPosEPNS1_9LiveRangeENS1_16LifetimePositionE+0x1d8): more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
collect2: error: ld returned 1 exit status
make[3]: *** [gum-tests] Error 1
make[3]: Leaving directory `/home/txia/frida/build/tmp-linux-i386/frida-gum/tests'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/txia/frida/build/tmp-linux-i386/frida-gum/tests'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/txia/frida/build/tmp-linux-i386/frida-gum'
make: *** [build/frida-linux-i386/lib/pkgconfig/frida-gum-1.0.pc] Error 2

**Comment by oleavr** [comment]
This looks like an incompatibility between the libstdc++ that I have on the Linux build machine, which was used to build the Frida SDK (prebuilt dependencies). It is GCC 4.9.1 IIRC. I'm afraid you'll have to build the SDK yourself. With a clean git clone, do:
```sh
$ make -f Makefile.sdk.mk FRIDA_HOST=linux-x86_64
```
Then once it's built it should be automatically picked up when you then proceed to build Frida.

**Comment by flycrane** [comment]
thanks, will try that

**Comment by flycrane** [comment]
oleavr,
so I checked out the frida-ci project, and run create-toolchain-and-sdk.sh as the doc suggested, however, got error "Missing required script ../frida-ci/create-toolchain-and-sdk.sh/build-deps.sh". I found no build-deps.sh out there, just build-deps-windows.sh which seems for windows.

**Comment by oleavr** [comment]
Sorry, that script is obsolete. Didn't the Makefile.sdk.mk in the `frida` repo work?

**Comment by flycrane** [comment]
no, Makefile.sdk.mk didn't work, anything missing?

txia@baidu:~/frida$ make -f Makefile.sdk.mk  FRIDA_HOST=linux-x86_64
FRIDA_ENV_NAME=fs FRIDA_ENV_SDK=none FRIDA_HOST=linux-x86_64 ./releng/setup-env.sh
Downloading and deploying toolchain...
Environment created. To enter:
# source /home/txia/frida/build/fs-env-linux-x86_64.rc
rm -f -r zlib
mkdir zlib
wget -O - -q http://zlib.net/zlib-1.2.8.tar.gz | tar -C zlib -xz --strip-components 1
rm -f -r build/fs-tmp-linux-x86_64/zlib
mkdir -p build/fs-tmp-linux-x86_64
cp -a zlib build/fs-tmp-linux-x86_64/zlib
. build/fs-env-linux-x86_64.rc \
		&& export PACKAGE_TARNAME=zlib \
		&& . $CONFIG_SITE \
		&& export CFLAGS CXXFLAGS OBJCFLAGS \
		&& case "linux-x86_64" in \
			android-i386) \
				export PATH="$(dirname $NM):$PATH"; \
				export CHOST="i686-linux-android"; \
				;; \
			android-arm) \
				export PATH="$(dirname $NM):$PATH"; \
				export CHOST="arm-linux-androideabi"; \
				;; \
			qnx-i386) \
				export PATH="$(dirname $NM):$PATH"; \
				export CHOST="i486-pc-nto-qnx6.6.0"; \
				;; \
			qnx-arm) \
				export PATH="$(dirname $NM):$PATH"; \
				export CHOST="arm-unknown-nto-qnx6.6.0eabi"; \
				;; \
		esac \
		&& cd build/fs-tmp-linux-x86_64/zlib \
		&& ./configure \
			--prefix=$frida_prefix \
			--static
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
make: *** [build/fs-tmp-linux-x86_64/zlib/Makefile] Error 1
txia@baidu:~/frida$

**Comment by flycrane** [comment]
also saw this:
txia@baidu:~/frida/build/fs-tmp-linux-x86_64/zlib$ cat configure.log 
--------------------
./configure --prefix=/home/txia/frida/build/fs-linux-x86_64 --static
Mon Apr 20 16:52:16 CST 2015
=== ztest25685.c ===
extern int getchar();
int hello() {return getchar();}
===
/usr/bin/gcc -static-libgcc -static-libstdc++ -c ztest25685.c
... using gcc

Checking for obsessive-compulsive compiler options...
=== ztest25685.c ===
int foo() { return 0; }
===
/usr/bin/gcc -static-libgcc -static-libstdc++ -c -include /home/txia/frida/build/frida-version.h -fPIC -m64 -ffunction-sections -fdata-sections -Wall -Os -pipe -gdwarf-2 -g3 ztest25685.c
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:59:1: fatal error: /home/txia/frida/build/frida-version.h: No such file or directory
 #endif
 ^
compilation terminated.
(exit code 1)
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
--------------------

**Comment by oleavr** [comment]
Oops, realized there was a regression. Should be fixed now. Sorry about that! Could you give it another spin now? (From a fresh git clone.)

**Comment by flycrane** [comment]
oleavr,

it works when building sdk, but still got following error when building frida with "make -f Makefile.linux.mk python-64 PYTHON=/usr/lib/python2.7", seems 

make[3]: Entering directory `/home/txia/frida/build/tmp-linux-i386/frida-gum/tests'
  CXXLD    gum-tests
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(compiler.o): In function `v8::internal::CompilationInfo::LogDeoptCallPosition(int, int)':
compiler.cc:(.text._ZN2v88internal15CompilationInfo20LogDeoptCallPositionEii+0x8c): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(hydrogen.o): In function `v8::internal::HGraph::SourcePositionToScriptPosition(v8::internal::SourcePosition)':
hydrogen.cc:(.text._ZN2v88internal6HGraph30SourcePositionToScriptPositionENS0_14SourcePositionE+0x63): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(type-feedback-vector.o): In function `v8::internal::Handle<v8::internal::TypeFeedbackVector> v8::internal::TypeFeedbackVector::Allocate<v8::internal::ZoneFeedbackVectorSpec>(v8::internal::Isolate*, v8::internal::ZoneFeedbackVectorSpec const*)':
type-feedback-vector.cc:(.text._ZN2v88internal18TypeFeedbackVector8AllocateINS0_22ZoneFeedbackVectorSpecEEENS0_6HandleIS1_EEPNS0_7IsolateEPKT_[_ZN2v88internal18TypeFeedbackVector8AllocateINS0_22ZoneFeedbackVectorSpecEEENS0_6HandleIS1_EEPNS0_7IsolateEPKT_]+0x27f): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o): In function `v8::internal::compiler::RegisterAllocator::ComputeLiveOut(v8::internal::compiler::InstructionBlock const*)':
register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator14ComputeLiveOutEPKNS1_16InstructionBlockE+0x182): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o): In function `v8::internal::compiler::RegisterAllocator::ResolveControlFlow()':
register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator18ResolveControlFlowEv+0x2d1): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/txia/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o):register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator22FindOptimalSpillingPosEPNS1_9LiveRangeENS1_16LifetimePositionE+0x1d8): more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
collect2: error: ld returned 1 exit status
make[3]: *** [gum-tests] Error 1
make[3]: Leaving directory `/home/txia/frida/build/tmp-linux-i386/frida-gum/tests'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/txia/frida/build/tmp-linux-i386/frida-gum/tests'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/txia/frida/build/tmp-linux-i386/frida-gum'
make: *** [build/frida-linux-i386/lib/pkgconfig/frida-gum-1.0.pc] Error 2

**Comment by flycrane** [comment]
oleavr,
here is what I did with a fresh clone:

$make -f Makefile.sdk.mk FRIDA_HOST=linux-x86_64
$make -f Makefile.toolchain.mk FRIDA_HOST=linux-x86_64
$make -f Makefile.linux.mk python-64  PYTHON=/usr/bin/python2.7

I am suprised that it is building with i386

**Comment by oleavr** [comment]
Sorry about the late follow-up here!

It looks like you forgot to build the i386 part:
$ make -f Makefile.sdk.mk FRIDA_HOST=linux-i386

Don't build the toolchain btw, that's not necessary.

**Comment by flycrane** [comment]
i am using the lastest 4.0, everything is fine, thanks

**Comment by Rezkmike** [comment]
Hi,
I cannot run my frida tool

Here is the error popup
![Screenshot from 2020-04-26 16-39-47](https://user-images.githubusercontent.com/48907062/80302451-b1935880-87dc-11ea-8642-fa991ebc7916.png)
