### ISSUE TITLE
[Novice confusion]How to get at least a microsecond time？

### ISSUE THREAD

**Issue by xmu1218** [frida/frida#330]
Hi Everyone
     How can I get microsecond timestamp use of frida? #Data.now( )、#performance.now( ) only get millisecond timestamps.
      I found the source of frida called #gettimeofday( ),It can take the time to microseconds.But the timestamp of the frida output is still millisecond.

   Thanks

**Comment by xmu1218** [comment]
resolved

**Comment by simpzan** [comment]
@xmu1218 hi, how did you solve this problem? I have the same need.
