### ISSUE TITLE
Frida-server not working in pixel 8 and android 14

### ISSUE THREAD

**Issue by gaganshetty645hk** [frida/frida#3307]
almost tried all the versions from latest till this version, all had thrown the same error
/frida-server-16.3.1-android-arm64                                            <
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":577,"columnNumber":1}

**Comment by pig837** [comment]
https://github.com/frida/frida/issues/2958

**Comment by gaganshetty645hk** [comment]
Thanks it really solved my issue :)

**Comment by gaganshetty645hk** [comment]
Thanks
