### ISSUE TITLE
ObjC.classes 

### ISSUE THREAD

**Issue by sebastian312** [frida/frida#336]
My script look like this:

```js
for(var className in ObjC.classes){
    if(ObjC.classes.hasOwnProperty(classname)){
        console.log(className);
    }
}
```

This displays all used classes of my apllication.

After running this script I try to detect all the methods of a class with another script:  
```js
var className = MyApp.JailbreakViewController;
var methods = eval('ObjC.classes.' + className + '.$methods');
for (var i = 0; i < methods.length; i++){
                console.log(methods[i]);
            }
}
```

The problem is now when using a classname with a dot in the middle like MyApp.JailbreakViewController there is an error shown that this property is undefined. When using another class that doesn't has a dot in its name like NSFileManager then the script displays me all the methods of the class.

I think this is a parsing problem because the interpreter isn't able to differentiate the classname containing a dot from a function call of ObjC class.

Is there a solution to solve this issue?

Thanks in advance!

**Comment by oleavr** [comment]
Use this syntax: `ObjC.classes['MyApp.JailbreakViewController']`. Also, to list classes it is easier to do `Object.keys(ObjC.classes).forEach(function (className) { ... });`.
