### ISSUE TITLE
Cydia repository is broken.

### ISSUE THREAD

**Issue by TheKalin** [frida/frida#337]
Hello I just wanted to install the new 10.5 version of frida on my iPhone 5s but the repository returns 404 error inside cydia package installer.  The latest file version of https://build.frida.re/frida/ios/bin/frida-server is from **16-May-2017 22:20.** And it  contains 10.0.6 version. 

![img_0023](https://user-images.githubusercontent.com/8446513/30211894-fc3609f8-94a2-11e7-9018-614d936fa8c2.PNG)

**Comment by oleavr** [comment]
Hi,

This must have been a build machine hiccup. Should be resolved now.

Thanks for reporting!

**Comment by ranbochen** [comment]
@oleavr 
It's broken again!
