### ISSUE TITLE
Error while listing processes @ Android

### ISSUE THREAD

**Issue by vikohone** [frida/frida#34]
Hi!

I was following the Android tutorial on http://www.frida.re/docs/android/ and the following error occurred:

$ frida-ps -R
Failed to enumerate processes: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.boblycat.frida.HostSession' on object at path /org/boblycat/frida/HostSession

---
OS X Yosemite 10.10.2
Python 2.7
Cyanogen OS 11.0-XNPH05Q
Android 4.4.4

**Comment by oleavr** [comment]
Hi,

It appears your local version of Frida is quite old – did you install it recently?

Cheers!

**Comment by vikohone** [comment]
Thank you!

You were right, I was using an old version of Frida.

I did install the newest one yesterday, but I must've failed somehow.

Moving the old Frida away from /usr/local/bin/frida-ps and then sudoing the make command helped me.

Now the Frida is at /usr/bin/frida-ps.

Cheers!

**Comment by oleavr** [comment]
Glad to hear! Thanks for using Frida! :+1:
