### ISSUE TITLE
UnboundLocalError: local variable 'os_version' referenced before assignment     

### ISSUE THREAD

**Issue by akbulut** [frida/frida#340]
Hello,
i try setup  frida on FreeBSD 10.1-RELEASE.
this is error message i see;

    UnboundLocalError: local variable 'os_version' referenced before assignment
    
    ----------------------------------------
Command "/usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r1ZAFh/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yz4qUZ-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-r1ZAFh/frida/

**Comment by oleavr** [comment]
FreeBSD is not (yet) supported. Help appreciated!
