### ISSUE TITLE
Javascript cannot access ObjC method begin with underscore(But REPL can!)

### ISSUE THREAD

**Issue by ranbochen** [frida/frida#341]
cli version 10.5.15
frida server version: from cydia 10.5.15

js file:
```
'use strict';
const print = console.log.bind(console)
const UIApplication = ObjC.classes.UIApplication
const app = UIApplication.sharedApplication()
print('injected:', app, typeof(app._workspace))
// injected: <UIApplication: 0x156d3a540> undefined
```

REPL:
UIApplication = ObjC.classes.UIApplication
app = UIApplication.sharedApplication()
app._workspace
---> Function

**Comment by oleavr** [comment]
Use this syntax when the name contains underscores: `app['- _workspace']`
