### ISSUE TITLE
VM:GetEnv failed: -2

### ISSUE THREAD

**Issue by rotlogix** [frida/frida#349]
When attempting to use Frida's Java API(s) I continue to get an error when Frida attempts to retrieve 
the virtual machine environment.

I've tried this on all 10.6.* versions, with duplicate results.  My device is a Nexus 5 running Android 5.1.1

```bash
Error: VM::GetEnv failed: -2
    at e (frida/node_modules/frida-java/lib/result.js:7)
    at frida/node_modules/frida-java/lib/vm.js:72
    at p (frida/node_modules/frida-java/index.js:166)
    at frida/node_modules/frida-java/index.js:105
    at frida/node_modules/frida-java/index.js:126
    at repl1.js:1
```

**Comment by oleavr** [comment]
Did you wrap your Java API calls in a `Java.perform()`? Seem to recall forgetting it results in symptoms like what you’re seeing.

**Comment by rotlogix** [comment]
Yes, and the error does not always through.  One thing is for certain, none of method implementations I am choosing to hook are working.  Even generic Activities.

**Comment by rotlogix** [comment]
I'll probably just (re)flash and (re)root this phone to see if it has anything to do with the device, then go from there.

**Comment by rotlogix** [comment]
So I do get results if I hook a specific Activity instead of `android.app.Activity` ...
