### ISSUE TITLE
Libraries not matching in Frida 10.6

### ISSUE THREAD

**Issue by Alph0r** [frida/frida#350]
When I try to attach to an app I get the following error:
Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:2059:frida
_resolve_library_function: assertion failed (local_library_path == remote_librar
y_path): ("/system/lib/arm/libc.so" == "/system/lib/arm/nb/libc.so")

I even tried to change that part of the Frida code, but I was not able to succesfully compile the Frida Server for ARM so far.
I know, that there was the same issue in the past, the reply was that it's fixed, but seems it's not.

I am using Genymotion with ARM translation.

**Comment by K-S-V** [comment]
I am also facing somewhat similar issue. My target device is not an emulator. It's physical Android x86 device (ASUS_T00J) running Android version 4.4.2. I haven't used Frida on this device before so I am not sure if it's a bug in new version of Frida or this configuration is not supported altogether. I am running latest frida and frida-server version (10.6.4).

```
**
Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:2059:frida_resolve_library_function: assertion failed (local_library_path == remote_library_path): ("/system/lib/libc.so" == "/system/lib/arm/libc.so")
Aborted
```

There is only one **libc.so** loaded in the target process.

```
cat /proc/3579/maps | grep libc.so
```

```
4005a000-4011c000 r-xp 00000000 b3:09 53196      /system/lib/libc.so
4011c000-4011d000 r--p 000c1000 b3:09 53196      /system/lib/libc.so
4011d000-40120000 rw-p 000c2000 b3:09 53196      /system/lib/libc.so
```

**Comment by oleavr** [comment]
Systems like Genymotion, that emulate ARM binaries through qemu-user, are not supported. (PRs welcome though!)

**Comment by K-S-V** [comment]
> Systems like Genymotion, that emulate ARM binaries through qemu-user, are not supported. (PRs welcome though!)

But I am not using an emulator. I am using a physical device. I can open a separate issue if you want.

**Comment by oleavr** [comment]
I know, that's why I said "Systems **like** Genymotion". It should work on apps with x86 native libraries though, so it appears we pick the wrong libc in those – separate issue for that in frida-core would be great. Thanks!

**Comment by NamPNQ** [comment]
@oleavr Can you tell more about how to fix it?

**Comment by enovella** [comment]
Would it be possible to upgrade Frida?
