### ISSUE TITLE
Build on mac error with new version 10.6.4

### ISSUE THREAD

**Issue by neoz** [frida/frida#351]
$ make server-android
. build/frida-meson-env-macos-x86_64.rc; \
	builddir=build/tmp-android-x86/frida-gum; \
	if [ ! -f $builddir/build.ninja ]; then \
		mkdir -p $builddir; \
		python3 /Users/xxXXxx/dev/frida/releng/meson/meson.py \
			--prefix /Users/xxXXxx/dev/frida/build/frida-android-x86 \
			--cross-file build/frida-android-x86.txt \
			--default-library static --buildtype minsize --strip -Denable_diet=auto \
			frida-gum $builddir || exit 1; \
	fi; \
	/Users/xxXXxx/dev/frida/releng/ninja-macos-x86_64 -C $builddir install || exit 1
ninja: Entering directory `build/tmp-android-x86/frida-gum'
[0/1] Regenerating build files.
The Meson build system
Version: 0.41.0.dev1
Source dir: /Users/xxXXxx/dev/frida/frida-gum
Build dir: /Users/xxXXxx/dev/frida/build/tmp-android-x86/frida-gum
Build type: cross build
Project name: frida-gum
Native c compiler: /Library/Developer/CommandLineTools/usr/bin/clang (clang 8.1.0)
Cross c compiler: /Users/xxXXxx/dev/frida/build/frida-android-x86-clang (clang 5.0.300080)
Native cpp compiler: /Library/Developer/CommandLineTools/usr/bin/clang++ (clang 8.1.0)
Cross cpp compiler: /Users/xxXXxx/dev/frida/build/frida-android-x86-clang++ (clang 5.0.300080)
Host machine cpu family: x86
Host machine cpu: x86
Target machine cpu family: x86
Target machine cpu: x86
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking if "compiling for macOS" compiles: NO
Checking if "compiling for iOS" compiles: NO
Has header "android/api-level.h": YES
Has header "elf.h": YES
Has header "stdint.h": YES
Has header "sys/elf.h": NO
Has header "sys/user.h": YES
Checking for type "long double": YES
Checking for type "long long int": YES
Checking for type "unsigned long long int": YES
Checking if "compiling for glibc" compiles: NO
Checking for function "log2": YES
Checking whether type "struct mallinfo" has member "arena": YES
Checking if "compiling with ASan" compiles: NO
Cross dependency liblzma found: YES 5.3.0alpha
Has header "bfd.h": NO

Meson encountered an error in file meson.build, line 161, column 2:
Error encountered: libbfd is required
FAILED: build.ninja
'/usr/local/opt/python3/bin/python3.6' '/Users/xxXXxx/dev/frida/releng/meson/meson.py' --internal regenerate '/Users/xxXXxx/dev/frida/frida-gum' '/Users/xxXXxx/dev/frida/build/tmp-android-x86/frida-gum' --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
make[1]: * [build/frida-android-x86/lib/pkgconfig/frida-gum-1.0.pc] Error 1
make: * [server-android] Error 2

**Comment by oleavr** [comment]
Your submodules are out of date. Run `git submodule update`, or, if you're hacking on Frida it's better to do: `git submodule foreach 'git checkout master && git pull'`

**Comment by neoz** [comment]
thanks oleavr
