### ISSUE TITLE
frida-server-10.6.4-ios-arm64 won't run

### ISSUE THREAD

**Issue by brian-leidos** [frida/frida#353]
Trying to run frida-server-10.6.4-ios-arm64 on iPhone 6 running iOS 10.2 will not run (exits with "Killed: 9"). frida-server-10.5.15-ios-arm64 runs fine on this device.

**Comment by brian-leidos** [comment]
I was able to run frida-server-10.6.3-ios-arm64 on this same device

**Comment by brian-leidos** [comment]
Closing this. Apparently this is user error involving manually updating frida-server. Documenting it here for others who run into it.

If you have a version of frida-server running and want to put a different version on your device:
1. kill -9 <pid> of frida-server
2. shut down all apps running on the device
3. copy the newer version of frida-server to /usr/sbin/frida-server
3. try to run /usr/sbin/frida-server&
4. if that fails: 
     a. start the app you had previously attached frida to (e.g., AngryBirds)
     b. try to run /usr/sbin/frida-server&
     c. if that fails, shutdown the app you ran (AngryBirds), then run /usr/sbin/frida-server& 
It should start now.

**Comment by oleavr** [comment]
Ah, I think the issue here is that the kernel caches the code-signing state based on the inode, so if you overwrite the file with a new one it will no longer match and result in the error you were seeing. The solution is to rm (unlink) the old one before copying the new one in.
