### ISSUE TITLE
/system/bin/sh: ./frida-server: not executable: 32-bit ELF file

### ISSUE THREAD

**Issue by quanjin9099** [frida/frida#364]
I run frida-server on Mumu (android4.4.4)
I run 3 versions:
Frida-server-10.6.15-android-arm
Frida-server-9.1.25-android-arm64
Frida-server-9.1.25-android-arm
But none of them can run

chmod 777 frida-server 
/system/bin/sh: ./firda-server: not executable: 64-bit ELF file
/system/bin/sh: ./frida-server: not executable: 32-bit ELF file

What should I do?

**Comment by ChD1** [comment]
Maybe wrong arch? Try x86 and other archs. I Think this will help.

**Comment by enovella** [comment]
Please run on your box:

`$ file frida-server-10.6.15-android-arm`

Did you uncompress the server?
