### ISSUE TITLE
How to listen CCHmacInit like CommonCrypto functions?

### ISSUE THREAD

**Issue by ibrahimyilmaz** [frida/frida#365]
Hi there,
Is it possible to listen  CCHmacInit , CCHmacUpdate and CCHmacFinal functions and get their input and output parameteres in CommonCrypto?

Any idea or help will be appreciated so much.
Ibrahim

**Comment by oleavr** [comment]
See the `Interceptor.attach()` [docs](https://www.frida.re/docs/javascript-api/#interceptor) – basically in `onEnter`:
```js
this.data = args[1];
this.dataLength = args[2];
```

Then in `onLeave`:
```js
var data = Memory.readByteArray(this.data, this.dataLength);
send({ type: 'data-for-you' }, data);
```

Though if you're writing a non-trivial agent you should be using [frida-compile](https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3), in which case you might want to check out [frida-trace](https://github.com/nowsecure/frida-trace) for a more declarative approach.

Cheers!

**Comment by ibrahimyilmaz** [comment]
Hi there,
I tried  in that way and I get that error.
I just didn't understand how can I call it...
Error: expected an integer
    at input:7

```
Interceptor.attach(Module.findExportByName("libcommonCrypto.dylib", "CCHmacInit"), {
    onEnter: function (args) {
	this.data = args[1];
	this.dataLength = args[2];
    },
    onLeave: function (retval) {
	var data = Memory.readByteArray(this.data, this.dataLength);
	send({ type: 'data-for-you' }, data);
    }
});
```

**Comment by oleavr** [comment]
Oops, I didn't actually test that code. Here's my mistake:

`this.dataLength = args[2];`

should have been:

`this.dataLength = args[2].toInt32();`

As the second argument to `Memory.readByteArray()` should be a number, and not a `NativePointer`.

**Comment by idb-** [comment]
When dealing with OnLeave of CCHmacFinal how can we read the final digest value from void *macOut?

**Comment by oleavr** [comment]
@idb- Something like this:

```
Interceptor.attach(Module.findExportByName('libcommonCrypto.dylib', 'CCHmacFinal'), {
  onEnter: function (args) {
    this.macOut = args[1];
  },
  onLeave: function (retval) {
    var mac = this.macOut.readByteArray(this.data, 20);
    console.log('*** CCHmacFinal:\n' + hexdump(mac, { ansi: true }));
  }
});
```

However you will also need to hook `CCHmacInit()` so your `CCHmacFinal()` knows which algorithm is used for the given `CCHmacContext()`. You can use an object in the outer scope to keep a mapping from context pointer to algorithm, and remove the mapping in your `CCHmacFinal()` hook.
