### ISSUE TITLE
[Android ARM] Failed to spawn: the connection is closed

### ISSUE THREAD

**Issue by kpowojski** [frida/frida#366]
I've just struggling with spawning the process on Android device (Google Pixel, Android 7.1). I'm running frida-server version 10.6.18 on mobile device and frida version 10.6.18 on my Mac. 
While doing `frida-ps -U` it returns me list of active processes correctly, but while trying to `frida -U --no-pause -f com.android.chrome` I get 'Failed to spawn: the connection is closed'. On mobile device there is an error message:
`Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:429:frida_inject_instance_new: assertion failed (ret == 0): (-1 == 0)`

**Comment by shanliangxiaomifeng** [comment]
How to get an error message on mobile device? I had the same trouble.

**Comment by oleavr** [comment]
This should be fixed as of 10.6.40. Cheers!
