### ISSUE TITLE
.frida-server: syntax error: ')' unexpected

### ISSUE THREAD

**Issue by stathisb** [frida/frida#367]
I am working on a rooted Nexus 5X device (64-bit ARM). I have the latest Frida version (10.6.18) installed on my desktop and i have already downloaded the latest frida-server (frida-server-10.6.18-android-arm64.xz). I have also pushed the frida server on my android device following the documentation but when i run the frida-server (./frida-server, as root) i am getting the following error:

./frida-server[9]: syntax error: ')' unexpected

Can someone help me?  Why this happens?

Thank you!

**Comment by enovella** [comment]
Some questions:
1. how do you run the frida-server? 
2. how do you launch Frida? bindings? REPL?
3. could you run `$ file frida-server` on your box?
4. did you chmod the binary on your nexus 5X?

**Comment by stathisb** [comment]
@enovella First of all thank you for your answer.

1) I run the frida-server following the official documentation [https://www.frida.re/docs/android/](url)
2) Just check if i can see the running processes on my mobile device using the following command on my local machine: frida-ps -U
3) The file command is not available on my device. So no, i cannot
4) Yes i have changed the permissions of the file to 755

**Comment by enovella** [comment]
3. Please do $ file frida-server on your machine before pushing it into your Nexus5X. Did you uncompress the server?

**Comment by stathisb** [comment]
@enovella  The problem solved. The problem was with the decompression of the .xz server file. I finally decompressed the file using the WinZip (as i am working on Windows) and now all seems to work fine. So lets close that issue.

Thank you very much :)

**Comment by manish199014** [comment]
I am trying to install  Frida 11.0.12 version server on Genymotion Android Emulator. I have successfully pushed the file but unable to start the server. I am getting following error. 
./frida-server-11.0.12-android-x86.xz[1]: syntax error: ')' unexpected

To set up this I m using a Macbook and I have also tried the same on Ubuntu 18.04 VM machine but the error was same. Can anyone help me in a right direction?

**Comment by rasoulmiri** [comment]
maybe you are use XXX.xz, You need to us XXX

**Comment by rainb3rry** [comment]
It's effective for that server file on me,
```
xshine@xshine-MacBook-Pro platform-tools % file /Applications/MAMP/htdocs/frida-server
/Applications/MAMP/htdocs/frida-server: Mach-O 64-bit executable x86_64
```
What I did:
```
xshine@xshine-MacBook-Pro platform-tools % ./adb root
adbd is already running as root
xshine@xshine-MacBook-Pro platform-tools % ./adb push ~/Downloads/frida-server /data/local/tmp/
/Users/xshine/Downloads/frida-server: 1 file pushed, 0 skipped. 24.5 MB/s (14404320 bytes in 0.561s)
xshine@xshine-MacBook-Pro platform-tools % ./adb shell "chmod 755 /data/local/tmp/frida-server"
xshine@xshine-MacBook-Pro platform-tools % ./adb shell "/data/local/tmp/frida-server &"        
/data/local/tmp/frida-server[2]: syntax error: ')' unexpected
xshine@xshine-MacBook-Pro platform-tools % frida-ps -U                                                       
Failed to enumerate processes: unable to connect to remote frida-server: closed
```
Any recommendations, @enovella, @rasoulmiri, @iambooker thanks.
