### ISSUE TITLE
Hooked method contents ignored

### ISSUE THREAD

**Issue by doridori** [frida/frida#371]
Help!

I am trying to hook a basic java method on Android and am failing. 

I have been using the code sample from the Frida site, as well as trying https://11x256.github.io/Frida-hooking-android-part-1/.

I have tried this from a rooted N5 running 6.0. X86 emulators running 4.4 (Dalvik) / 5 / 6 and an ARM emulator running 6. I have also used python 2.7 on OSX and 3.? on Fedora.

The closest I can get to it working is it hooks the method, but it will always just return a default value for the return type. It seems to remove the original methods implementation and replace with an empty method. For example;

Original Code:

```
public boolean hookme() {
   return true;
}
```

Hooking with JS:

```
setImmediate(function() { //prevent timeout
    console.log("[*] Starting script");

    Java.perform(function() {
      bClass = Java.use("com.example.fridatest.MainActivity");
      bClass.hookme.implementation = function() {
         console.log("[*] hooked");
         return true;
      };
      console.log("[*] hookme modified");

    });
});
```

will _always_ cause the hookme call to return `false` and nothing written to log. I have tried this with `10.1` and latest frida servers with the same behaviour. 

What am I be doing wrong? Going nuts over here! Thanks

EDIT: the `py` loading

```
#python code
import frida
import time
device = frida.get_usb_device()
pid = device.spawn(["com.example.fridatest"])
device.resume(pid)
time.sleep(1) #Without it Java.perform silently fails
session = device.attach(pid)
script = session.create_script(open("test.js").read())
script.load()

#prevent the python script from terminating
raw_input()
```

**Comment by oleavr** [comment]
Should be working in 10.6.40. Known to work well on Nexus 5X running 8.1.0. Cheers!

**Comment by nanoymaster** [comment]
I am having the same issue:

Java.choose("uk.rossmarks.fridalab.MainActivity", {
            onMatch: function (instance) {
                rtn = instance.chall03();
                console.log(rtn); // rerturn's false
                console.log("[3][+] Hooking chall03()");
                instance.chall03.implementation = function() {
                    console.log("[3][+] hooked");
                    return true;
                }
                rtn = instance.chall03();
                console.log(rtn); // return's false
            },
            onComplete: function () { }
        });

trying to make the following  in MainAtivity return true:

    private boolean chall03() {
        return false;
    }

Using frida version 12.2.18
