### ISSUE TITLE
Confused about how to run frida at nox player emulator android on windows

### ISSUE THREAD

**Issue by rafaelwedbiz** [frida/frida#372]
Hi, im trying to make this tutorial:

https://techblog.mediaservice.net/2017/07/universal-android-ssl-pinning-bypass-with-frida/

but it is getting hard cuz i doesn't work,

Well i have some questions::
frida server can be installed on nox player?
this part **$ frida -U -f it.app.mobile -l frida-android-repinning.js --no-pause** should be done at device shell or in mine cmd desktop windows?

I tried also to follow this tutorial https://www.frida.re/docs/android/ but commands like **frida-ps -U** doesn't work at windows, very confused.

could u help me please?

Thanks in advanced.

**Comment by Zymlex** [comment]
-U - use USB connection, but Nox use Wi-Fi.

Example for MEmu (on cmd):
adb shell "getprop dhcp.eth0.ipaddress"
adb shell "/data/local/tmp/frida-server -l 10.0.2.15:21502"
frida-ps -H 127.0.0.1:21502
frida -H 127.0.0.1:21502 -f com.android.aospbrowser -l "D:\frida-android-repinning_sa-1.js" --no-pause

The port must be forwarded and not busy.

**Comment by oleavr** [comment]
Not App Player and other mixed-mode emulators that only support ARM native code are not supported.

**Comment by lalokupfer** [comment]
Hi,
The above post was 2 years ago, Can Frida sever now be installed in nox?
If so any tutorial?

**Comment by seltix5** [comment]
I was looking for alternatives too, my old android device just died.... thanks!
