### ISSUE TITLE
frida cannot spawn with -f

### ISSUE THREAD

**Issue by Wingless-Archangel** [frida/frida#375]
I'm not sure that it's related to #245 or not but the issue is quite similar.

This issue occurs whenever I tried to put `-f` into Frida, I got the error below

```shell
$ frida -U --no-pause -f com.android.chrome
     ____
    / _  |   Frida 10.6.21 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to spawn: unable to handle 64-bit processes due to build configuration
```

but when I put only -U, it's working properly

```shell
$ frida -U --no-pause com.android.chrome
     ____
    / _  |   Frida 10.6.21 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/

[Android Emulator 5554::com.android.chrome]-> quit
```
frida version: 10.6.21 both client and server
android studio: 3.0

**Comment by oleavr** [comment]
This is because the wrong frida-server was deployed to the device. Make sure you're deploying the `arm64` version (or `x86_64`, depending on the architecture) if the device is a 64-bit device.

**Comment by Josue198s** [comment]
> This is because the wrong frida-server was deployed to the device. Make sure you're deploying the `arm64` version (or `x86_64`, depending on the architecture) if the device is a 64-bit device.

Hello Oleavr, 

I have installed the right server but I still get this problem on two phones. 

sh-3.2# frida-trace -U -i open wit.sire.mSeller
Instrumenting functions...                                              
open: Loaded handler at "/Users/drfs_gs/Desktop/Crack_me_Challenges/__handlers__/libbase.so/open.js"
Started tracing 1 function. Press Ctrl+C to stop.                       
^Csh-3.2# frida -l rootbypass.js -f wit.sire.mSeller
sh: fridada: command not found
sh-3.2# frida -l rootbypass.js -f wit.sire.mSeller
     ____
    / _  |   Frida 12.8.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to spawn: unable to find executable at 'wit.sire.mSeller'        
sh-3.2#

**Comment by oleavr** [comment]
@Josue198s Looks like you forgot to specify the device to use in your `-f` command line, so `frida-trace` is trying to spawn a program on the local system.

**Comment by imatary** [comment]
> This is because the wrong frida-server was deployed to the device. Make sure you're deploying the `arm64` version (or `x86_64`, depending on the architecture) if the device is a 64-bit device.

I deployed arm64 version and it give me following error
(/system/bin/sh: ./FS64: No such file or directory)
