### ISSUE TITLE
frida -f for 32-bit devices crashes device

### ISSUE THREAD

**Issue by Nightbringer21** [frida/frida#376]
Spawning an application using **`frida -f`** or **`frida-trace -f`** on a 32-bit device leads to a device crash and restart (using "Frida for 32-bit devices" v. 10.6.21). This is on an iPad mini device running iOS 9.3.5, using the Ph0enix JB.

Running the exact same command on a device running iOS 10.2 (Yalu JB), works as normal.

Example command:

>`frida -U -f <Package name>`

**Comment by Nightbringer21** [comment]
Could be directly related to #373.

**Comment by nssecur1ty** [comment]
if youre looking for a workaround, try http://sultan.readthedocs.io/en/latest/ + https://github.com/bored-engineer/iOS-sbutils (sblaunch)

**Comment by Wingless-Archangel** [comment]
I have this similar issue but occur on the android emulator both 32-bit and 64-bit.

**Comment by oleavr** [comment]
Please try with 10.6.40 – should work much better on both iOS and Android.

**Comment by Wingless-Archangel** [comment]
Let me try it as soon as I can. Thanks for the heads up!

**Comment by Wingless-Archangel** [comment]
Let me try it as soon as I can. Thanks for the heads up! Just one quick question, Does the test including the emulator?

**Comment by oleavr** [comment]
Yes if it's a plain emulator and not an x86 emulator with ARM emulation inside – so stay away from Nox App Player and emulators like that. (Plain x86 works.)
