### ISSUE TITLE
How to hook a string in onCreate()?

### ISSUE THREAD

**Issue by GeekTan** [frida/frida#377]
I want to hook tmp, how to hook?
public class MainActivity extends AppCompatActivity {

    // Used to load the 'native-lib' library on application startup.
    static {
        System.loadLibrary("native-lib");
    }
    private String tmp;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Example of a call to a native method
        TextView tv = (TextView) findViewById(R.id.sample_text);
        tmp=stringFromJNI();
        tv.setText(tmp);
    }

    /**
     * A native method that is implemented by the 'native-lib' native library,
     * which is packaged with this application.
     */
    public native String stringFromJNI();
}
I try this, but can't work.
Java.perform(function () {

	var mainactivity = Java.use("com.geektan.myapplication1.MainActivity");
	mainactivity.onStart.overload().implementation = function (){

        send(this);
	    this.tmp="hello";

	    var ret = this.onStart.overload().call(this);

	}

	send("Hooks installed.");
});

**Comment by enovella** [comment]
What if you hook the methods `stringFromJNI` or `setText`?

**Comment by GeekTan** [comment]
I try hook stringFromJNI and setText,but I want to try hook onCreate(), onCreate()   can't hook?

**Comment by GeekTan** [comment]
I try hook stringFromJNI and setText is sucessed,but I want to try hook onCreate(), onCreate() can't hook?

**Comment by enovella** [comment]
In your code snippet you were hooking `onStart` but you are interested in `onCreate`. Mismatch?

Btw, there was an issue (https://github.com/frida/frida-java/issues/29) with this topic. Did you take a peek at it?

BR,

**Comment by GeekTan** [comment]
How to hook a native method return value?Give me a sample?Thanks.
