### ISSUE TITLE
Java.enumerateLoadedClasses returns different mangling depending on Android version

### ISSUE THREAD

**Issue by doegox** [frida/frida#379]
On Android 4.4, Frida server 10.6.21

Java.enumerateLoadedClasses |grep java.lang.String
'[[Ljava/lang/String;'
'[Ljava/lang/String;'
'Ljava/lang/String;'

On Android 5.0.2, Frida server 10.6.21

Java.enumerateLoadedClasses |grep java.lang.String
'[[Ljava.lang.String;'
'[Ljava.lang.String;'
'java.lang.String'

Note the change of the separator "/" -> "." and the stripping of "L...;" on base classes.

Could the behavior be unified and return the lists with the same mangling in both cases?

**Comment by oleavr** [comment]
Good catch! Moving this to [frida-java](https://github.com/frida/frida-java).
