### ISSUE TITLE
Could Java.perform return the result of the called function?

### ISSUE THREAD

**Issue by doegox** [frida/frida#380]
Currently the return value of a function is lost when wrapped with Java.perform.
E.g. one can't do

        return Java.perform(function () {
            return Java.enumerateLoadedClassesSync().sort();
        });

but has to do e.g.

        var result;
        Java.perform(function () {
            result=Java.enumerateLoadedClassesSync().sort();
        });
        return result;

I guess it's just a matter of changing
https://github.com/frida/frida-java/blob/master/lib/vm.js#L39
by capturing the return value of fn() and returning it in the "finally".
It would be nice :)

**Comment by oleavr** [comment]
`Java.perform()` is potentially asynchronous, i.e. early in the process lifetime when the app's class loader isn't yet available. However, if you need to return a result for example through `rpc`, you can do:

```js
rpc.exports.foo = function () {
  return new Promise(function (resolve, reject) {
    Java.perform(function () {
      try {
        var result = ...
        resolve(result);
      } catch (e) {
        reject(e);
      }
    });
  });
};
```

**Comment by doegox** [comment]
thanks!
