### ISSUE TITLE
No support template string?

### ISSUE THREAD

**Issue by Daemonceltics** [frida/frida#381]
[Motorola AOSP on Shamu::PID::3317]-> var firstName = 'Jake';
undefined
[Motorola AOSP on Shamu::PID::3317]-> console.log(`My name is ${firstName}`);
SyntaxError: invalid token (line 1)

**Comment by oleavr** [comment]
Use `frida-compile`, or switch to V8 through `—enable-jit`

**Comment by srcdes** [comment]
You can use `frida` command's `--runtime` option setting to `v8` which supports template string. Default value is `duk` which doesn't support it.

**Comment by oleavr** [comment]
Here's how to do it on Duktape:
https://github.com/oleavr/frida-agent-example
