### ISSUE TITLE
Frida gadget

### ISSUE THREAD

**Issue by fridaExplorer** [frida/frida#382]
When using frida gadget (v10.6.21) in android using "script" interaction types, where does the console.log() display the text?

I have tried to use new File(filePath, mode) in the js but there is file permission error. Read in another posting that this api is limited.

In that case, when using frida gadget in android using "script" interaction types, how can i perform the logging?

Thanks

**Comment by ChD1** [comment]
I use logcat. This is some example:
`
var Log = Java.use("android.util.Log");
var TAG_L = "[FRIDA_SCRIPT]";
Log.v(TAG_L, "[*] This string will be printed in to logcat!");
`

**Comment by fridaExplorer** [comment]
Thanks for the information!

Unfortunately, the script that i use it on the apk does not execute the Java.perform, hence I cannot use Java.use to print the string to logcat.

**Comment by ChD1** [comment]
You can save you log to file [Frida Javascript Api: File](https://www.frida.re/docs/javascript-api/#file)

**Comment by oleavr** [comment]
You can also call `__android_log_write()` through `NativeFunction`.

**Comment by exikyut** [comment]
(Which is extremely easy:

```
const android_log_write = new NativeFunction(Module.getExportByName(null, '__android_log_write'), 'int', ['int', 'pointer', 'pointer']);

const tag = Memory.allocUtf8String("tag");
const str = Memory.allocUtf8String("str");

android_log_write(3, tag, str);
```

See https://developer.android.com/ndk/reference/group/logging for the possible values for `prio` (`3` here is `DEBUG`, a probably-sane default.)
