### ISSUE TITLE
frida-dicover failed!

### ISSUE THREAD

**Issue by paulnaoki** [frida/frida#386]
Hi,

im using Frida 10.6.21 to play with my emulator which runs andriod 4.2.2.  tried hard to connect my PC to the device.
when i tried frida-discover, this throw error got thrown... what should i do?

Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:2059:frida_resolve_library_function: assertion failed (local_library_path == remote_library_path): ("/system/lib/libc.so" == "/system/lib/arm/libc.so")

Please Help!!!

**Comment by oleavr** [comment]
Mixed-architecture emulators are not supported. Please use a plain emulator or a real device. (Or contribute support for this.)
