### ISSUE TITLE
Frida Backtrace

### ISSUE THREAD

**Issue by fridaExplorer** [frida/frida#387]
I have managed to use Thread.backtrace together with interceptor to track the caller on a method.

1. Instead of getting the address, is it possible to get the function name?

2. Is it possible to backtrace a few level at one time?

**Comment by enovella** [comment]
Please try to share code snippets, and it will be way easier to give you ideas or advises.

**Comment by fridaExplorer** [comment]
Interceptor,attach(Module.findExportByName("libc.so","open"), {
   OnEnter: function(args) {
       console.log("Open called from:\n" +
            Thread.backtrace(this.context, Backtracer.ACCURATE)
            .map(DebugSymbol.fromAddress).join("\n") + "\n");
   }
});

This will print the address of the caller where open is invoked.

**Comment by oleavr** [comment]
Seems like you answered your own question – case closed. :)

**Comment by YuyeQingshan** [comment]
@oleavr do I need to decrypt the app first?
