### ISSUE TITLE
App crashes on hooking java.lang.ClassLoader.loadClass

### ISSUE THREAD

**Issue by lupodellemontagne** [frida/frida#388]
I am trying to instrument an Android malware. To instrument early calls to internal classes I am hooking java.lang.ClassLoader.loadClass.
The js snippet is the following:

```
Java.performNow(
function () {      
        x=Java.use("java.lang.ClassLoader");
        console.log(""+x);
        console.log(""+x.loadClass.overloads);
        x.loadClass.overloads[0].implementation=function(v){
            send("0"+v);
            var ret=x.loadClass.overloads[0].apply(this, arguments);
            send(ret)
            return ret;
        };
         x.loadClass.overloads[1].implementation=function(v){
            send("1"+v);
            var ret=x.loadClass.overloads[1].apply(this, arguments);
            send(ret)
            return ret;
        };
        
         console.log("hook installed");
        
}
);

```
I am using python and the code that I use to install the script is the following:

```
device = frida.get_usb_device(10)
pid = device.spawn(["com.opera.installer"])

session = device.attach(pid)
script = session.create_script(jscode)
script.on("message",on_message)
script.load()
device.resume(pid)
print('Riesumiamo'+str(pid))
sys.stdin.read()

```

Quite strangely the App starts normally and I am able to see the loaded class. However, if I interact in any way with the app it immediately crashes after loading a class. Using logcat I see that the error is

```
W/dalvikvm( 7715): JNI WARNING: method declared to return 'Ljava/lang/Class;' returned 'Ljava/lang/String;'
W/dalvikvm( 7715):              failed in Ljava/lang/ClassLoader;.loadClass
I/dalvikvm( 7715): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm( 7715):   | group="main" sCount=0 dsCount=0 obj=0x9dae5ca8 self=0xb8670380
I/dalvikvm( 7715):   | sysTid=7715 nice=0 sched=0/0 cgrp=apps handle=-1224933036
I/dalvikvm( 7715):   | state=R schedstat=( 2170000000 3150000000 2082 ) utm=133 stm=84 core=0
I/dalvikvm( 7715):   at java.lang.ClassLoader.loadClass(Native Method)
I/dalvikvm( 7715):   at com.opera.installer.f.onClick((null):-1)

```

It seems that after the instrumentation loadClass is returing a String instead of a Class. However in the js snippet I do not touch the return tipe. I do not have this problem if I run the same code on "com.android.calendar".

I am using frida 10.2.3 and emulated Android 4.4. arm. I was not able to use newer version of frida on the emulator, hooks were not working or they were crashing the app.

**Comment by oleavr** [comment]
Please try with 10.6.40. Known to work well on Nexus 5X running 8.1.0. Cheers!
