### ISSUE TITLE
I can't make Makefile.sdk.mk on ubuntu 16.04

### ISSUE THREAD

**Issue by nueah** [frida/frida#389]
I was trying to make 
make -f Makefile.sdk.mk FRIDA_HOST=android-arm

but I got this error
my ndk version is r15c 
and it says there is no cstring ...
I don't know why...

and I already build linux-x86-64 

if test -f /usr/bin/python2.7; then \
	ln -sf /usr/bin/python2.7 build/fs-tmp-android-arm64/python; \
else \
	ln -sf /usr/bin/python2.6 build/fs-tmp-android-arm64/python; \
fi
. build/fs-env-android-arm64.rc \
	&& cd build/fs-tmp-android-arm64/v8 \
	&& PATH="/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64:/usr/bin:/bin:/usr/sbin:/sbin:$PATH" \
		CXX_host="$CXX" CXX_target="$CXX" LINK="$CXX" \
		make -j 8 android_arm64.release GYPFLAGS="-D host_os=linux -D werror='' -D v8_use_external_startup_data=0 -D v8_enable_gdbjit=0 -D v8_enable_i18n_support=0 -D v8_enable_inspector=1 -f make-android -D android_ndk_root=/home/nueah/Android/Sdk/ndk-bundle_r15c -D android_sysroot=/home/nueah/Android/Sdk/ndk-bundle_r15c -D android_target_platform=21 -D clang=1  "
make[1]: Entering directory '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8'
make[2]: Entering directory '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8'
make[3]: Entering directory '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out'
src/inspector/inspector_debugger_script.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/debugger-script.h'
src/inspector/inspector_debugger_script.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/debugger-script.h'
src/inspector/inspector_injected_script.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/injected-script-source.h'
src/inspector/inspector_injected_script.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/injected-script-source.h'
src/inspector/protocol_compatibility.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/js_protocol.stamp'
src/inspector/protocol_compatibility.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/js_protocol.stamp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Forward.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Forward.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Protocol.cpp'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Protocol.cpp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Protocol.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Protocol.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Console.cpp'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Console.cpp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Console.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Console.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Debugger.cpp'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Debugger.cpp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Debugger.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Debugger.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/HeapProfiler.cpp'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/HeapProfiler.cpp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/HeapProfiler.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/HeapProfiler.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Profiler.cpp'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Profiler.cpp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Profiler.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Profiler.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Runtime.cpp'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Runtime.cpp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Runtime.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Runtime.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Schema.cpp'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Schema.cpp'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Schema.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/src/inspector/protocol/Schema.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/include/inspector/Debugger.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/include/inspector/Debugger.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/include/inspector/Runtime.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/include/inspector/Runtime.h'
src/inspector/protocol_generated_sources.target.android_arm64.release.mk:13: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/include/inspector/Schema.h'
src/inspector/protocol_generated_sources.host.android_arm64.release.mk:13: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj/gen/include/inspector/Schema.h'
src/v8_base.target.android_arm64.release.mk:744: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_base.a'
src/v8_base.host.android_arm64.release.mk:682: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_base.a'
src/v8_libbase.target.android_arm64.release.mk:286: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_libbase.a'
src/v8_libbase.host.android_arm64.release.mk:220: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_libbase.a'
src/v8_libplatform.target.android_arm64.release.mk:272: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_libplatform.a'
src/v8_libplatform.host.android_arm64.release.mk:210: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_libplatform.a'
src/v8_libsampler.target.android_arm64.release.mk:265: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_libsampler.a'
src/v8_libsampler.host.android_arm64.release.mk:203: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_libsampler.a'
src/v8_nosnapshot.target.android_arm64.release.mk:264: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_nosnapshot.a'
src/v8_nosnapshot.host.android_arm64.release.mk:206: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_nosnapshot.a'
src/v8_snapshot.target.android_arm64.release.mk:292: warning: overriding recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_snapshot.a'
src/v8_snapshot.host.android_arm64.release.mk:226: warning: ignoring old recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/libv8_snapshot.a'
  TOUCH /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.host/src/inspector/protocol_compatibility.stamp
  TOUCH /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/src/inspector/protocol_compatibility.stamp
  TOUCH bdc92efe44eca1954fdff70fd086c7e138d0fbb1.intermediate
  TOUCH b469d38bd3ab89ecee5588da1e88c67d8e6ccfbe.intermediate
  TOUCH /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/src/inspector/inspector_injected_script.stamp
  TOUCH /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/src/inspector/inspector_debugger_script.stamp
  ACTION Generating inspector protocol sources from protocol json bdc92efe44eca1954fdff70fd086c7e138d0fbb1.intermediate
  CXX(host) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.host/v8_builtins_setup/src/setup-isolate-full.o
  ACTION Generating inspector protocol sources from protocol json b469d38bd3ab89ecee5588da1e88c67d8e6ccfbe.intermediate
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/file-utils.o
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/functional.o
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/ieee754.o
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/logging.o
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/once.o
In file included from ../src/setup-isolate-full.cc:7:
.././src/base/logging.h:8:10: fatal error: 'cstring' file not found
#include <cstring>
         ^
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/platform/memory-backend.o
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/platform/threading-backend.o
  CXX(target) /home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.target/v8_libbase/src/base/platform/time.o
1 error generated.
src/v8_builtins_setup.host.android_arm64.release.mk:152: recipe for target '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.host/v8_builtins_setup/src/setup-isolate-full.o' failed
make[3]: *** [/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out/android_arm64.release/obj.host/v8_builtins_setup/src/setup-isolate-full.o] Error 1
make[3]: *** Waiting for unfinished jobs....
rm bdc92efe44eca1954fdff70fd086c7e138d0fbb1.intermediate b469d38bd3ab89ecee5588da1e88c67d8e6ccfbe.intermediate
make[3]: Leaving directory '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8/out'
Makefile.android:59: recipe for target 'android_arm64.release' failed
make[2]: *** [android_arm64.release] Error 2
make[2]: Leaving directory '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8'
Makefile:330: recipe for target 'android_arm64.release' failed
make[1]: *** [android_arm64.release] Error 2
make[1]: Leaving directory '/home/nueah/Documents/FRIDA/android-64-arm/build/fs-tmp-android-arm64/v8'
Makefile.sdk.mk:478: recipe for target 'build/fs-tmp-android-arm64/.v8-build-stamp' failed
make: *** [build/fs-tmp-android-arm64/.v8-build-stamp] Error 2

**Comment by oleavr** [comment]
Assuming this is fixed in latest git. (Recently rebuilt the SDKs just fine.)
