### ISSUE TITLE
interacting with a method that has an underscore in its name

### ISSUE THREAD

**Issue by miller93** [frida/frida#390]
so i understand how to interact with objects using the example in documentation

`[NSString stringWithString:@"Hello World"] ` becomes `var NSString = ObjC.classes.NSString; NSString.stringWithString_("Hello World");`

however, what if the object has an underscore in the method name for example

`[Manage _userString:data:]`

what am i suppose to do with the underscore frida recognizes it as a colon

**Comment by oleavr** [comment]
`Manage['- _userString:data:'].call(Manage, userString, data)`
