### ISSUE TITLE
Failed to enumerate applications: unable to connect to remote frida-server: Unable to connect (connection refused)

### ISSUE THREAD

**Issue by alliejk** [frida/frida#391]
Does "frida-ps -Ua" works in Windows10? I have a following problem using frida-ps on my laptop, but it perfectly works on Windows 7...

> frida-ps -Ua
> Failed to enumerate applications: unable to connect to remote frida-server: Unable to connect (connection refused)

**Comment by oleavr** [comment]
It should work if iTunes is installed. Otherwise you won't have usbmuxd running.
