### ISSUE TITLE
How to modify android return value (Object type)

### ISSUE THREAD

**Issue by cgbcsh** [frida/frida#395]
Hi, 
First of all, I really use frida very well. frida is awesome.

I want to know how to modify return value. (Android object type)
please see, below.

```
a[1] = Java.use("android.net.ConnectivityManager");
a[1].getNetworkInfo.overload("int").implementation = function(s1) {
 var ret = this.getNetworkInfo(s1)
 console.log("getNetworkInfo [*] ret: " + ret) 
 return ret
};
```
frida attach (in python) / android version : 6.0.1 / frida version : 10.6.26
and original return value is 
```
getNetworkInfo [*] ret: [type: MOBILE[], state: DISCONNECTED/DISCONNECTED, reason: (unspecified), 
extra: (none), roaming: false, failover: false, isAvailable: true]
```
I want to change like below.
state: DISCONNECTED/DISCONNECTED  -> state: CONNECTED/CONNECTED

Finally, return value is 
```
getNetworkInfo [*] ret: [type: MOBILE[], state: CONNECTED/CONNECTED, reason: (unspecified), 
extra: (none), roaming: false, failover: false, isAvailable: true]
```

Thanks, have a nice day!

**Comment by enovella** [comment]
Hi,

have you tried `Java.cast()` ?

https://www.frida.re/docs/javascript-api/

**Comment by cgbcsh** [comment]
Hi, thanks for your response.
If there is an example, can I see it...?

**Comment by ChD1** [comment]
Maybe better intercept getState() like this:
```
var states = Java.use("android.net.NetworkInfo.State");
a[1] = Java.use("android.net.NetworkInfo");
a[1].getState.implementation = function(){
	var ret = states.valueOf("CONNECTED");
	return ret;
};
```
PS: I write code without checking.

**Comment by cgbcsh** [comment]
Thanks for your response.
I need to study more about Java.cast()


and It works
```
a[3100] = Java.use("android.net.NetworkInfo");
a[3100].getState.implementation = function() {
 var ret = this.getExtraInfo()
 console.log(ret) 
 return ret
};
```

Thank you all.

**Comment by henrytom1703** [comment]
How to modify android return int value? 
I'm seeing return a wrong format type:  
Ex:
console return 200.0 instead of 200
var clzString = Java.use("java.lang.String");
clzString.valueOf.overload('int').implementation = function (value) {
console.log(this.valueOf(value));
if (value == 200) {
return this.valueOf(parseInt("100"));
}
return this.valueOf(value);
};
output console:
200.0 --> this is wrong format

**Comment by 1471880107** [comment]
.
