### ISSUE TITLE
frida hook `ios objective-c class method` seems not correctly

### ISSUE THREAD

**Issue by 3xp10it** [frida/frida#399]
I try to hook a objective-c method(`setIntegratedSteps`) in a class(`PARSPedometerInfo`) in an ios app,the method `setIntegratedSteps` in `ida pro` has below content:

```
void __cdecl -[PARSPedometerInfo setIntegratedSteps:](PARSPedometerInfo *self, SEL a2, signed __int64 a3)
{
  self->_integratedSteps = a3;
}
```

That's to say, the method `setIntegratedSteps` has one parameter,and the parameter type is int64,and the method `setIntegratedSteps`'s return value type is `void`,I try to hook this method with frida in below code:

```
import frida
import sys

session = frida.get_usb_device().attach(720)
script_string = """
if (ObjC.available)
{
    try
    {
        var className = "PARSPedometerInfo";
        var funcName = "- setIntegratedSteps:";
        var hook = eval('ObjC.classes.' + className + '["' + funcName + '"]');
        Interceptor.attach(hook.implementation, {
          onEnter: function(args) {
            console.log("param:"+args[0]+" type:"+typeof args[0]);
            send(args[0]);
          },
          onLeave: function(retval) {
            console.log("[*] Class Name: " + className);
            console.log("[*] Method Name: " + funcName);
            console.log("\t[-] Type of return value: " + typeof retval);
            console.log("\t[-] Return Value: " + retval);
            send(retval)
          }
        });
    }
    catch(err)
    {
        console.log("[!] Exception2: " + err.message);
    }
}
else
{
    console.log("Objective-C Runtime is not available!");
}
"""


script = session.create_script(script_string)


def on_message(message, data):
    if message['type'] == 'error':
        print("[!] " + message['stack'])
    elif message['type'] == 'send':
        print("[i] " + message['payload'])
        addr = int(message['payload'], 16)
        print("try to read addr content...")
        addr_content = session.read_bytes(addr, 4)
        print("addr content:" + addr_content)
    else:
        print(message)


script.on('message', on_message)
script.load()
sys.stdin.read()
```

The output is:

```
param:0x1279cfa20 type:object
[i] 0x1279cfa20
try to read addr content...
[*] Class Name: PARSPedometerInfo
[*] Method Name: - setIntegratedSteps:
        [-] Type of return value: object
        [-] Return Value: 0x1279cfa20
[i] 0x1279cfa20
try to read addr content...
```

The output shows that the param value is `0x1279cfa20`,however,I am sure it is not `0x1279cfa20`,the real value of the method `setIntegratedSteps` is a int64 value,and the true parameter value is `0x49a`,but frida shows the param value is `0x1279cfa20`,I cann't understand it,so I think maybe frida wants to tell me the true value `0x49a` is stored at `0x1279cfa20`,then I try to read_bytes at `0x1279cfa20`,but upon output cann't print anything else after print `try to read addr content...`,that's to say,`0x1279cfa20` can not be read.

Besides,the return value of method `setIntegratedSteps` shoud be `void`,but frida shows me the method return value is the same as the method's parameter `0x1279cfa20`,I can't understand it.

This makes me confused,when I try to hook an ios objective-c class method which has no parameter,frida works well on showing the return value,and then I try to check the official site's hook function example [here][1],and it works well on print the parameter value too.But it seems frida works not correctly on hooking ios objective-c classes functions which have parameters.

Can you help me?

[1]: https://www.frida.re/docs/functions/#hooking-functions

**Comment by oleavr** [comment]
The issue is that the actual arguments start at index 2.

**Comment by oleavr** [comment]
(Index 0 is `self` and index 1 is `sel`, so the actual arguments start at index 2.)
