### ISSUE TITLE
Build error vs2013 generate-version-header.py

### ISSUE THREAD

**Issue by techbliss** [frida/frida#40]
There seem to be missing some value when generating frida-version.h
here is the error log. 

Generating frida-version.h
1>  fatal: Not a git repository (or any of the parent directories): .git
1>  Traceback (most recent call last):
1>    File "D:\frida-master\releng\generate-version-header.py", line 45, in <module>
1>      generate_version_header()
1>    File "D:\frida-master\releng\generate-version-header.py", line 11, in generate_version_header
1>      (major, minor, micro, nano, commit) = version.split(".")
1>  ValueError: need more than 1 value to unpack

**Comment by oleavr** [comment]
This is because we currently assume that git is in your PATH. We should probably improve the script to auto-detect its path on Windows.
