### ISSUE TITLE
Is there any way to find an object in the memory by the object's classname  with frida

### ISSUE THREAD

**Issue by 3xp10it** [frida/frida#400]
After jailbreak in ios,we can find an specific object address in ios objective-c app with `cycript` tool by `choose(className)`,eg:
`choose(PARSPedometerInfo)` will find an object of `PARSPedometerInfo` class,can frida find an specific object by className?

**Comment by oleavr** [comment]
Use `ObjC.choose()`, see docs [here](https://www.frida.re/docs/javascript-api/#objc).
