### ISSUE TITLE
iOS, Interceptor.attach works/.replace crashes 

### ISSUE THREAD

**Issue by brian-leidos** [frida/frida#402]
I have this JS code (I'm using against SpringBoard):
var hook = eval('ObjC.classes.SBAlertItemsController["- activateAlertItem:"]');

If I:
Interceptor.attach(hook.implementation...   <-- works, I can console.log to my heart's content

but:
Interceptor.replace(hook.implementation, new NativeCallback(function(sbai) {
   // do nothing
   return;
}, 'void', ['SBAlertItem']));

.replace crashes SpringBoard

**Comment by oleavr** [comment]
Use `'pointer'` instead of `'SBAlertItem'`. If it crashes it means your replacement either has the wrong signature or doesn't behave as the caller expects, e.g. forgets to return a value.

**Comment by brian-leidos** [comment]
Ah! Thanks @oleavr
