### ISSUE TITLE
Frida & Nox

### ISSUE THREAD

**Issue by cpilka** [frida/frida#403]
Hi,

I want to inspect an Android app in Nox App Player. So what I did is:

    adb connect 127.0.0.1:62001

    adb devices -l <-- shows me Nox App Player

    adb shell /data/local/tmp/frida-server -l 0.0.0.0:27042 &

    adb forward tcp:27042 tcp:27042

    frida-ps -R <-- shows me the target app in process list

    frida -R --no-pause -p 2137

returns:

      ____
     / _  |   Frida 10.6.29 - A world-class dynamic instrumentation framework
    | (_| |
     > _  |   Commands:
    /_/ |_|       help      -> Displays the help system
    . . . .       object?   -> Display information about 'object'
    . . . .       exit/quit -> Exit
    . . . .
    . . . .   More info at http://www.frida.re/docs/home/
    Attaching...                                                            
    **
    Frida:ERROR:../../../frida-core/src/linux/frida-helper-service-glue.c:429:frida_inject_instance_new: assertion failed (ret == 0): (-Failed to attach: the connection is closed

Am I missing a step or is that a known issue?

Best regards,
Christoph

**Comment by cpilka** [comment]
Related to https://github.com/frida/frida/issues/295 ?

**Comment by oleavr** [comment]
Nox App Player is not supported. It expects native code to be ARM code, which means frida-java's method hooking isn't compatible with it.

**Comment by nanshihui** [comment]
now  is  there any solution？  i got the same  problem
