### ISSUE TITLE
How to record function return value and modify function return value when the return value is String type

### ISSUE THREAD

**Issue by 3xp10it** [frida/frida#406]
I want to hook an Objective-c funcion `[PARSSignInfo uId]`,I use `cycript` with below cmd to check the type of the return value:
```
cy# choose(PARSSignInfo)
[#"<PARSSignInfo: 0x14e839a30>"]
cy# [#0x14e839a30 uId]
@"849910421621100544"
```
That's to say,uId returns String type value `849910421621100544`,and I want to hook `uId` function's returen value to `849910421621100545`(former 849910421621100544+1) with below code:
```
if (ObjC.available)
{
    try
    {
        var className = "PARSSignInfo";
        var funcName = "- uId";
        var hook = eval('ObjC.classes.' + className + '["' + funcName + '"]');
        Interceptor.attach(hook.implementation, {
          onEnter: function(args) {
          },
          onLeave: function(retval) {
            console.log("Original retval-> type:"+typeof retval+" value:"+retval)
            newretval="849910421621100545";
            retval.replace(newretval)
            console.log("New retval-> type:"+typeof newretval+" value:"+newretval)
          }
        });
    }
    catch(err)
    {
        console.log("[!] Exception2: " + err.message);
    }
}
else
{
    console.log("Objective-C Runtime is not available!");
}

```

Then I get the below outpu:
```
Original retval-> type:object value:0x134ff8cb0
New retval-> type:string value:849910421621100545
```

I have two questions here:

1.I can't understand why the retval is not `849910421621100544`,but `0x134ff8cb0`,can you tell me why,should I change my js code?

2.Should I change my js code like below to replace the return value to `849910421621100545`?

```
change from 
`newretval="849910421621100545" ` 
to
`newretval=ObjC.classes.NSString.stringWithString_("849910421621100545")`
```

**Comment by oleavr** [comment]
Interceptor doesn't know anything about Objective-C, so you will have to do `new ObjC.Object(retval)` to access the return value as an Objective-C object. Likewise when replacing it you have to assign an Objective-C object there (same way).

**Comment by OwnerCM** [comment]
> I can't understand why the retval is not `849910421621100544`,but `0x134ff8cb0`,can you tell me why,should I change my js code?

I also encountered the same problem, how did you solve it? @3xp10it
