### ISSUE TITLE
Is it possible to hook a process that is being debugged with r2?

### ISSUE THREAD

**Issue by securisec** [frida/frida#408]
I keep getting a permission error which does not exist if hooking the app without debugging with r2. Running with sudo doesnt seem to do the trick.

**Comment by oleavr** [comment]
You can use frida-gadget, or contribute an optional kernel driver for Linux that allows us to inject frida-agent without relying on ptrace. (We currently have such a driver for macOS, and long-term I hope others will contribute similar drivers for other OSes.)
