### ISSUE TITLE
Frida can't hook java.lang.Runtime in Application

### ISSUE THREAD

**Issue by Roselia** [frida/frida#410]
# Environment
device:nexus5 4.4.4
frida version:10.6.32
# Frida Code
import frida, sys

jscode = """
Java.perform(function () {
	send("Running Script");

    var mRuntime=Java.use("java.lang.Runtime");
 mRuntime.loadLibrary.overload("java.lang.String","java.lang.ClassLoader").implementation=function(){
       send("frida--->loadLibrary");
    }

});

"""

process = frida.get_usb_device().attach('com.test.jnidemo')
script = process.create_script(jscode)
def on_message(message, data): 
    print(message)
script.on('message', on_message)
script.load()
sys.stdin.read()

# Android Code
# application can't print frida--->loadLibrary
public class MyApplication extends Application {
    static {
        System.loadLibrary("native-lib");
    }

    @Override
    public void onCreate() {
        super.onCreate();
        Log.e("result----->",stringFromJNI());
    }
    public native String stringFromJNI();
}
# Activity can print frida--->loadLibrary
public class MainActivity extends Activity {
    static {
        System.loadLibrary("native-lib");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Example of a call to a native method
        TextView mTest1 = findViewById(R.id.mTest1);
        mTest1.setText(stringFromJNI());
    }
    public native String stringFromJNI();
}

**Comment by oleavr** [comment]
Please file an issue in [frida-java](https://github.com/frida/frida-java) if this is also reproducible on Android 8.1. (I do most of my testing these days on a Nexus 5X running 8.1.0.)

**Comment by jeanbmar** [comment]
It seems that Runtime.loadLibrary doesn't cover all the situations for some reason.
I have the same issue on Android 7, but I'm able to hook some calls using:
```
const RuntimeDef = Java.use('java.lang.Runtime');
const RuntimeLoad_3 = RuntimeDef.loadLibrary0.overload('java.lang.ClassLoader', 'java.lang.String');
RuntimeLoad_3.implementation = function(classLoader, library) {
    send("Loading dynamic library (RuntimeLoad_3) => " + library);
    RuntimeLoad_3.call(this, classLoader, library);
    send("Loading dynamic library (RuntimeLoad_3) SUCCESS => " + library);
    return;
}

**Comment by jeanbmar** [comment]
https://github.com/frida/frida-java/issues/63#issuecomment-384629231

**Comment by jeanbmar** [comment]
https://github.com/frida/frida-java/issues/63#issuecomment-384629231

**Comment by henrytom1703** [comment]
Hello @oleavr  and @jeanbmar 
I have a same issue. I cannot hook  java.lang.Runtime class.
And I have a question . how to inject native shared libs into app
Thanks

**Comment by jeanbmar** [comment]
See my response here https://github.com/frida/frida-java/issues/63#issuecomment-384629231 to hook loadLibrary

**Comment by henrytom1703** [comment]
Hello @jeanbmar 
I tried it and not working. and I have a other question. I want inject native shared libs into  any app. 
Do you know how to do it?.  Can make inject native shared libs with xposed or firda, ...?
Thanks
