### ISSUE TITLE
How to write js when I need both hook function and support a rpc interface

### ISSUE THREAD

**Issue by 3xp10it** [frida/frida#411]
When I try to hook function and support a rpc interface, I find I must wait around 2 minutes for my rpc function to be called,it seems frida will spend 2 minutes or more to find the rpc function's entrance.Below is my js coce:
```
'use strict';

rpc.exports = {
    encrypt: function (plain) {
        console.log(3434343434)
        var result=ObjC.classes.PARSCryptDataUtils.encryptWithServerTimestamp_(plain)
        console.log("rpc !!!!!!!!!!!!!!!!!!!!!! been called")
        return result.toString()
    },
    add: function (a) {
        console.log("add func called!!!!!!!!!!!!")
        return 4444444444;
        }
};



if (ObjC.available)
{
    try
    {
        var className = "PARSCryptDataUtils";
        var funcName = "+ encryptWithServerTimestamp:";
        var hook = eval('ObjC.classes.' + className + '["' + funcName + '"]');
        Interceptor.attach(hook.implementation, {
          onEnter: function(args) {
            var string_to_send=ObjC.classes.NSString.stringWithString_(args[2]).toString()
            send(string_to_send)
          },
        });
    }
    catch(err)
    {
        console.log("[!] Exception2: " + err.message);
    }
}
else
{
    console.log("Objective-C Runtime is not available!");
}
```

When I use below python code to call the `add` rpc function from frida,I must wait 2 or more minutes.(This happens only the first time I call any rpc function in the js,after I have called any rpc function successfully,I can call any rpc function in around 1 second),I can't understand why the first time I call any rpc function should speed too much time,should I modify my js code to make it faster?

Here is my python code 
```
            add_function = getattr(script.exports, 'add')
            #I have to wait 2 or more minutes before below add_function return a value
            data = add_function(data)

```

**Comment by oleavr** [comment]
Cannot reproduce this. Please reopen if you are able to provide a simple way to reproduce it. Cheers!
