### ISSUE TITLE
Android platform "failed to fork" error

### ISSUE THREAD

**Issue by Daemonceltics** [frida/frida#412]
I am run frida-server as root, but frida -U  -p any process result like this
  ____
    / _  |   Frida 10.6.28 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to attach: failed to fork (Connection refused)

**Comment by oleavr** [comment]
If this is still reproducible in 10.6.40 this must be a ROM-specific issue. One such known issue is on Samsung kernels where processes in `/data/local/tmp` (and maybe other locations) aren't able to spawn child processes. This is why we have a client that talks to SuperSU to ask it to spawn `frida-helper-{32,64}`, but obviously this won't work on devices with Magisk or another kind of rooting solution. PRs welcome!

**Comment by Daemonceltics** [comment]
My very very stupid mistake , frida run in my custom ROM that I change fork logic , sorry for waste your time.
