### ISSUE TITLE
compile frida-gum error

### ISSUE THREAD

**Issue by mwpcheung** [frida/frida#413]
error while compile frida macos python

Cross cpp compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ (clang 9.0.0)
Host machine cpu family: x86
Host machine cpu: x86
Target machine cpu family: x86
Target machine cpu: x86
Build machine cpu family: x86_64
Build machine cpu: x86_64
/Users/~/frida/build/tmp-macos-x86/frida-gum/meson-private/sanitycheckobjc.m:1:8: fatal error: 'stdio.h' file not found
#import<stdio.h>
       ^~~~~~~~~
1 error generated.

Meson encountered an error in file meson.build, line 15, column 2:

**Comment by oleavr** [comment]
Xcode issue, try `xcode-select --install`.
