### ISSUE TITLE
Question: How to read a JSON file in Javascript code on Android

### ISSUE THREAD

**Issue by waqarrashid33** [frida/frida#414]
Hello everyone,

I want to load the methods that need to be hooked from a JSON file stored on android device. How do I do that?
I tried using the `new File(filePath, mode)` in the but it says that it can't find the file or directory. I can't make a file either, it gives the error of `Read only file system`. 

The device is rooted and the file path is /data/local/tmp/file.json.

I also tried sending the file using script.post() but I get only half file, may be because of some size limit. 
I will appreciate any help. Let me know if you need more info, as I am new to frida and probably missed some needed info.

Cheers.
Waqar

**Comment by oleavr** [comment]
Hi,

If you want a persistent on-device solution take a look at Gadget's [script mode](https://www.frida.re/docs/gadget/#script).

The `File` API doesn't support reading just yet (PR welcome), but for non-trivial agents it's a better idea to use frida-compile anyway and use the [frida-fs](https://github.com/nowsecure/frida-fs) module.

Cheers!

**Comment by waqarrashid33** [comment]
Thanks @oleavr . Another question:
But how do I execute the compiled binary? Do I launch it from python bindings just like the JavaScript or some other way?

Waqar

**Comment by waqarrashid33** [comment]
For those of you who are visiting this issue for similar reason as mine, here is an example script to open a text file on android and send it to host.

```JavaScript
'use strict';

const fs = require("frida-fs");

Java.perform(function () {
    var readStream = fs.createReadStream("/path/to/file.txt");
    var text = "";
    readStream
        .on('readable', function () {
            var chunk;
            while (null !== (chunk = readStream.read())) {
                text = text.concat(chunk);
            }
        })
        .on('end', function () {
            send(text);
        });
});
```

Make sure you have "frida-fs" installed using "npm".

To compile this code, first install "frida-compile". Thats how I did it:
`sudo npm install frida-compile -g`

And then create a NodeJS project with `npm init` in the directory you want your project to be. Then install frida-fs using `npm install frida-fs`. Then make the app.js( or whatever file you want to use as main script) and paste the above code into it.

Compile this script using `frida-compile app.js -o payload.js`.
Then change in your binding code, use payload.js as your JavaScript file. e.g in mine it looks like this:
`script = process.create_script(open("path/to/payload.js").read())`

I hope its helpful.

Waqar
