### ISSUE TITLE
Bug in Overload()

### ISSUE THREAD

**Issue by dmchell** [frida/frida#417]
If you have a number of overloads, and one of them takes no arguments, when you try get the overload it fails with error:

TypeError: cannot read property 'overload' of undefined

It appears to be trying to retrieve "overload" as a property rather than invoke as a method.

**Comment by oleavr** [comment]
The issue must be elsewhere, as [this test](https://github.com/frida/frida-java/commit/84782b079b034d8551bad950d75fb7b042b724d5) passes with the current code.
