### ISSUE TITLE
How can i get functions list in Android?

### ISSUE THREAD

**Issue by jdragonbae** [frida/frida#418]
<pre><code>
var component = "com.example.pacakge.MainActivity";

var targetClass = Java.use(component);

//object

console.log(typeof(targetClass));

//function

console.log(typeof(targetClass.f1));
</code></pre>

I want to get function list in class.

How can i do? Please, explain.

Thank you.

**Comment by madushan1000** [comment]
You can use something like `Java.enumerateLoadedClasses(callbacks)` I think. But the last time I tried this on chrome, the script timed out. Your best bet is to use some apk decompiler like dex2jar with JD-GUI to get the java source code and find the function/class names from that.

**Comment by enovella** [comment]
IMHO, [Jadx](https://github.com/skylot/jadx) is more updated and reliable than dex2jar.
