### ISSUE TITLE
issue with call android app function

### ISSUE THREAD

**Issue by vah13** [frida/frida#42]
Hi
I have next situation. Now I analyse android application with frida, application have obfuscated strings for example 
final String string4 = query.getString(query.getColumnIndex(h.a("\u4347\uf662\u2b58\uf5f5")));
![git1](https://cloud.githubusercontent.com/assets/7976421/7636836/5fd7b1b4-fa72-11e4-8d87-7f3602fef0b2.png)

decryption class h decryption function 

static final String a(final String p0) {...}
![git2](https://cloud.githubusercontent.com/assets/7976421/7636844/643ee858-fa72-11e4-92e4-e21991613bea.png)

I use next code but don't can call "h.a" function, 

import frida,sys
 def print_result(message):
            print "[*] Testing PIN %s" %(message)
 def on_message(message, data):
            print_result(message['payload'])
 jscode = """
 Dalvik.perform(function () {
       var h = Dalvik.use("com.adobe.cfg.h");
    var ret = h.a('\ufad6!\ubb89\u2731\u11c5');
    send(ret);
});
"""
session = frida.get_remote_device().attach("com.adobe.jaguar:jaguar_bf")
print session.enumerate_modules()
script = session.create_script(jscode)
script.on('message', on_message)
script.load()
sys.stdin.read()

![git3](https://cloud.githubusercontent.com/assets/7976421/7636875/84305f16-fa72-11e4-863c-c8ac4f2ce274.png)

What I do wrong ?

**Comment by oleavr** [comment]
This looks correct at first glance. What happens?

**Comment by vah13** [comment]
python process does not end for a long time

**Comment by vah13** [comment]
maybe inject code is not true?

**Comment by oleavr** [comment]
Hmm, you're sure there's no escaping issue with the backslashes inside that python multiline string? I would recommend reading the .js from a file while prototyping. You can do:

```bash
$ frida -R com.adobe.jaguar:jaguar_bf -l decode.js
```

Then in `decode.js` put your code. You can enter `%reload` in the REPL to make it reload the .js file.

**Comment by vah13** [comment]
Usage: frida-ps-script.py [options]

frida-ps-script.py: error: no such option: -l

**Comment by oleavr** [comment]
Did you run the `frida` tool? (I'm assuming you're running the latest 4.0.x version)

**Comment by oleavr** [comment]
Considering this issue fixed.
