### ISSUE TITLE
frida-ps -U doesn't recognise iPad

### ISSUE THREAD

**Issue by TomHubGit** [frida/frida#421]
Hello everyone,

I am quite new to frida and I discover some issues as frida doesnt recognise my iPad. However it is recognised by the underlaying Linux OS.

Setup:
```
iPad mini - iOS 9.3.3 - jailbroken
Linux - Ubuntu based Kali
frida client tools - installed according to documentation
frida server - installed through Cydia on iPad
```

Starting frida -U with a connected iPad hangs here:
```
~ # frida-ps -U                                                             
Waiting for USB device to appear...
```

However it is seen by the OS:
```
~ # lsusb                                                             root@kali
Bus 001 Device 003: ID 05ac:12ab Apple, Inc. iPad 4/Mini1
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Killing the frida-server on the iPad over SSH doesnt help. 

Anyone any idea what this might be? Every input is appreciated.

Thank you!
Tom

**Comment by oleavr** [comment]
Hi,

You're probably missing the package containing usbmuxd. If you're able to successfully run `ideviceinfo` then Frida should also work.

Cheers!

**Comment by TomHubGit** [comment]
Thanks for the hint, but the package is installed:
```

libusbmuxd4/kali-rolling,now 1.1.0~git20171206.c724e70f-0.1 amd64 [installed,automatic]
  USB multiplexor daemon for iPhone and iPod Touch devices - library

usbmuxd/kali-rolling,now 1.1.0-2+b2 amd64 [installed,automatic]
  USB multiplexor daemon for iPhone and iPod Touch devices
```
However the linux has no ideviceinfo command. Any other idea?

**Comment by konsumer** [comment]
Same prob, with `libimobiledevice-utils` package (which also pulls in `libusbmuxd6` and `libimobiledevice6`.

I'm on aarch64 ubuntu 20.04 on a pi3b

**Comment by konsumer** [comment]
I spoke too soon. need to trust computer. After installing `libimobiledevice-utils` and trusting, it started working. Thanks!
