### ISSUE TITLE
[Frida x85 on Android]

### ISSUE THREAD

**Issue by ccasadob** [frida/frida#428]
Hey There!

I'm new using Frida and I have a problem. When I'm trying to spawn a process with the command:
frida -U --no-pause -f jakhar.aseem.diva
I'm getting this error:
Failed to spawn: timed out while waiting for session to establish
I'm using Frida 10.6.27 on my laptop, and Frida server 10.6.32  on a android emulator device. I'm trying with the same version of Frida on both sides (client and server using 10.6.27 version) then I got this error:
Failed to spawn: the connection is closed

Maby is a problem with the versions compatibility?
 I installed Frida with pip command, then I assume that my Frida's version is the latest. I repeat, I'm new learning this and using Frida, maby my question is a little bit basic and I don't know how to solve this problem, sorry about that.
Any help will be of much help.
Thanks in advance!
Best Regards!

**Comment by oleavr** [comment]
Hey,

Please reopen if this is also an issue on Frida 10.6.52 (10.6.27 and 10.6.32 are quite outdated).

Cheers!

**Comment by ccasadob** [comment]
Sorry about my ignorance. how can I upgrade my Frida 10.6.27 to the last version (10.6.27)?

**Comment by oleavr** [comment]
`pip install -U frida` or `easy_install -U frida` depending on how you installed it. For the Android side grab the latest frida-server from our [releases](https://github.com/frida/frida/releases).

**Comment by ccasadob** [comment]
Thanks you so much! It works very well when I upgrade both Frida, client an server!
