### ISSUE TITLE
Failed to Spawn: failed to execute child process

### ISSUE THREAD

**Issue by 0xTHEgod** [frida/frida#431]
I am currently pentesting android apps using tools ADB and Frida. Every step pertaining to installing and configuring went smooth and well. I am currently at the point now of pentesting the actual android package using the syntax; **frida -U -f com.android.package -l frida-android-repinning_sa-1.js --no-pause**

However, I continually get this error message; **Failed to Spawn: failed to execute child process "/data/local/tmp/re.frida.server/frida-helper-32" (Permission Denied)**

Thanks in advance for any help.

**Comment by enovella** [comment]
Hi @0xTHEgod,

which permissions did you gave to frida-server? which ROM are you using?  More details are always needed to try to spot the problem.

Cheers

**Comment by 0xTHEgod** [comment]
Thank you for the reply, but I will be closing the issue. With some trial and error (using a Samsung Galaxy 3) I just moved the frida-server to /system/priv-app and it suddenly worked.
