### ISSUE TITLE
Frida crashing when not in console

### ISSUE THREAD

**Issue by hemo91** [frida/frida#433]
## When does it happen 
This happens only when a `js` file is loaded but doesn't happen if the same `js` is pasted on **frida console**.

However, I made a `js` file with the following code ---
```
Java.perform(function () {
    var Activity = Java.use("android.app.Activity");
    Activity.onResume.implementation = function () {
        console.log("[*] onResume() got called!");
        this.onResume();
    };
});

```
and it worked fine but if I used `enumerateLoadedClasses` it gives an error  :disappointed: 

I am getting this error when trying to **print all classes** or for that matter any **js** I'm trying to load. 

The script is taken from [here](https://github.com/antojoseph/frida-android-hooks), it has quite some useful hooks.

The js part is --

    setTimeout(function() {
        Java.enumerateLoadedClasses({
            onMatch: function(className) {
                send(className);
            },
            onComplete: function() {
                send("done");
            }
        });
    }, 0);

I'm very new to frida.

 
    Error: VM::GetEnv failed: -2
        at e (frida/node_modules/frida-java/lib/result.js:6)
        at frida/node_modules/frida-java/lib/vm.js:71
        at p (frida/node_modules/frida-java/index.js:171)
        at frida/node_modules/frida-java/index.js:112
        at repl1.js:15

Frida version -- **frida-server-10.6.54-android-arm64**  the latest version

### When injecting a `js` file
![image](https://user-images.githubusercontent.com/35294510/36473362-5de01352-171a-11e8-83c6-0e830c2fbfda.png)

### Direct `js` on console, works fine
![image](https://user-images.githubusercontent.com/35294510/36473536-c6257d1c-171a-11e8-8a7f-e903fa695c6a.png)

It's the same on any app.

**Comment by oleavr** [comment]
You forgot to run `Java.enumerateLoadedClasses()` inside a `Java.perform()` callback. This is required for all Java API calls – and even if it appears to work without, it may result in undefined behavior and weird crashes.

**Comment by hemo91** [comment]
Thanks a lot @oleavr  :slightly_smiling_face:
