### ISSUE TITLE
(Android) Anyway to call a function?

### ISSUE THREAD

**Issue by NGTmeaty** [frida/frida#436]
I want to call a function and pass args using Frida, anyway to do so?

**Comment by FrankSpierings** [comment]
If you want to call a Java function, something like this:

```java
function myfunction() {
    // Check if frida has located the JNI
    if (Java.available) {

        // Switch to the Java context
        Java.perform(function() {
            // https://www.frida.re/docs/javascript-api/#java 
            // Dynamically get a JavaScript wrapper for className that you can instantiate objects from by calling $new() on it to invoke a constructor.
            const JavaString = Java.use('java.lang.String');
            // Create an instance of java.lang.String and assign it to a variable 
            var exampleString1 = JavaString.$new('Hello World, this is an example string in Java.');
            console.log('[+] exampleString1: ' + exampleString1);
            console.log('[+] exampleString1.length(): ' + exampleString1.length());
        }
    )}
}
// Call the function
myfunction()
```

**Comment by NGTmeaty** [comment]
@FrankSpierings well, if there is a function already initialized in the code, and I want to call it, is there any way to do so with variables? I see how you can initialize the variables, but not how to pass them into an already existing function.

**Comment by FrankSpierings** [comment]
I use x86 android api level 24 without playstore with a emulated nexus 5

**Comment by henrymark92** [comment]
@oleavr . Can you make frida support this emulator ?
http://www.mediafire.com/file/chzx2cymbvyj5l6/BlueStacks+App+Player+0.9.24.5311+Superuser+BSEasy+-+bo+2.msi
Thanks

**Comment by oleavr** [comment]
@henrymark92 Not a priority for me personally. PRs welcome though!
