### ISSUE TITLE
Use frida-gadget 10.6.55 on Android device Shamu failed

### ISSUE THREAD

**Issue by SheilaLundin** [frida/frida#437]
"adb forward tcp:27042 tcp:27042" has been runned, and libfrida-gadget.so has been loaded. But "frida-ps -U" returns "Failed to enumerate processes: unable to connect to remote frida-server: closed".

**Comment by oleavr** [comment]
The `adb forward` should not be done for `-U` — if adb can see the device and `frida-ls-devices` does too, you only need `-U`.
