### ISSUE TITLE
Cannot download FridaGadget.dylib

### ISSUE THREAD

**Issue by tepmnthar** [frida/frida#438]
[https://build.frida.re/frida/ios/](https://build.frida.re/frida/ios/)
[https://build.frida.re/frida/macos/](https://build.frida.re/frida/macos/)
Those two folders show 403 forbidden to me. 
Is there any other mirror site or how can I compile **FridaGadget.dylib** by myself?

**Another issue:**
My current dylib (downloaded at last august) seems always cause a crash when it has intercepted a method.
```
tepmnthardeMBP:WTSSDKBundlePack TEP$ frida-trace -U -f re.frida.Gadget -m "+[WTSSDK *]"
Instrumenting functions...
+[WTSSDK forwardingTargetForSelector:]: Auto-generated handler at "/Users/TEP/Documents/wuta/WTSSDKBundlePack/__handlers__/__WTSSDK_forwardingTargetForSelector__.js"
```
Then crashed.

**Comment by oleavr** [comment]
Gadget should always be downloaded from: https://github.com/frida/frida/releases

As for the crash, please file a separate issue after narrowing it down to a single function and providing disassembly of its instructions. Otherwise there's no way I can reproduce it.

**Comment by tepmnthar** [comment]
@oleavr Thank you for your reply. I've posted a new issue [here](https://github.com/frida/frida/issues/439).

**Comment by tepmnthar** [comment]
[Doc](https://www.frida.re/docs/ios/#without-jailbreak) seems a bit outdated. I feel confused when I found an invalid download link.

**Comment by oleavr** [comment]
Ah, oops! Care to open a PR against frida-website fixing this?
