### ISSUE TITLE
How to hook android.content.pm.ComponentInfo  constructed function?

### ISSUE THREAD

**Issue by GeekTan** [frida/frida#442]
'use strict';
Java.perform(function(){
    var ComponentInfo = Java.use("android.content.pm.ComponentInfo");
    ComponentInfo.overload("android.content.pm.ComponentInfo").implementation = function(orig){
        send(this.applicationInfo);
       return this.overload("android.content.pm.ComponentInfo").apply(this,arguments);
    }

});

{u'columnNumber': 1, u'description': u"TypeError: undefined not callable (property 'overload' of [object Object])", u'fileName': u'script1.js', u'lineNumber': 3, u'type': u'error', u'stack': u"TypeError: undefined not callable (property 'overload' of [object Object])\n    at [anon] (duk_js_call.c:2847)\n    at script1.js:3\n    at frida/node_modules/frida-java/lib/vm.js:39\n    at y (frida/node_modules/frida-java/index.js:331)\n    at frida/node_modules/frida-java/index.js:302\n    at frida/node_modules/frida-java/lib/vm.js:39\n    at java.js:2368\n    at script1.js:11"}

**Comment by ChD1** [comment]
Try this:
```
...
ComponentInfo.$new.overload("android.content.pm.ComponentInfo").implementation = function(orig){
...
}

});
```

**Comment by Obaied** [comment]
@GeekTan did this solve your issue?
