### ISSUE TITLE
Installation problems on both Windows and Linux

### ISSUE THREAD

**Issue by luh2** [frida/frida#443]
Host: Windows 10, Rhel 7
Python: 3.6.4 / 3.4
There is an outgoing proxy at `http://proxy.host.com:3128`. Somehow it keeps failing. Tried new fresh install of python, but it doesn't change a thing :/ 

Not sure if it's a PEBKAC or frida problem. Could it be that the proxy settings are ignored in a later part?Here the full output.

> pip.exe --proxy=http://proxy.host.com:3128 install frida
Collecting frida
  Using cached frida-10.6.58.tar.gz
Collecting colorama>=0.2.7 (from frida)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting prompt-toolkit>=0.57 (from frida)
  Using cached prompt_toolkit-1.0.15-py3-none-any.whl
Collecting pygments>=2.0.2 (from frida)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit>=0.57->frida)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting six>=1.9.0 (from prompt-toolkit>=0.57->frida)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: colorama, wcwidth, six, prompt-toolkit, pygments, frida
  Running setup.py install for frida ... error
    Complete output from command "c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\luh2\\AppData\\Local\\Temp\\pip-build-zzxtk2xm\\frida\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\luh2\AppData\Local\Temp\pip-m1ci8z0_-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\frida
    copying frida\application.py -> build\lib.win-amd64-3.6\frida
    copying frida\core.py -> build\lib.win-amd64-3.6\frida
    copying frida\discoverer.py -> build\lib.win-amd64-3.6\frida
    copying frida\kill.py -> build\lib.win-amd64-3.6\frida
    copying frida\lsd.py -> build\lib.win-amd64-3.6\frida
    copying frida\ps.py -> build\lib.win-amd64-3.6\frida
    copying frida\repl.py -> build\lib.win-amd64-3.6\frida
    copying frida\tracer.py -> build\lib.win-amd64-3.6\frida
    copying frida\__init__.py -> build\lib.win-amd64-3.6\frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. C:\Users\luh2/frida-10.6.58-py3.6-win-amd64.egg
    no prebuilt extension found in home directory
    error: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
>
>    ----------------------------------------
> Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\luh2\\AppData\\Local\\Temp\\pip-build-zzxtk2xm\\frida\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\luh2\AppData\Local\Temp\pip-m1ci8z0_-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\luh2\AppData\Local\Temp\pip-build-zzxtk2xm\frida\

**Comment by luh2** [comment]
Ok, under Linux it works, if I execute `pip install frida` as regular user or as root, but not as `sudo pip install frida`.

**Comment by tepmnthar** [comment]
Maybe you should use `pip3 install --user frida`. It works for me.

**Comment by luh2** [comment]
No, that didn't change anything. But it was as I suspected, it seems like the installation routine uses two different sources for the proxy information. One, the passed argument in the proxy parameter, second, the environment variable `https_proxy`. I had to set that manually in Windows. Once it was set, installation passed smoothly. I guess in Linux, when using sudo, the env variables are not quite the same as when actually logged in.

**Comment by tepmnthar** [comment]
If I'm not misunderstanding your question. You want to use proxy when installing frida, but you don't know which environment variable it will use?

I write a bash script in `/usr/local/bin/proxy`.
```
#!/bin/bash
http_proxy=http://127.0.0.1:8118 https_proxy=http://127.0.0.1:8118 $*
```

If I want to use proxy in bash. I just put **proxy** before other commands. Just like this: `$ proxy pip install xxx`. I think it will override any other **https_proxy** settings in your system.

Don't know how to do it in Windows. Maybe you can download **Proxifier**.

**Comment by luh2** [comment]
There is no question, just the observation that doing `pip3 install --proxy=PROXY frida` will successfully get the packages from pypi, but in the installation routine it will fail. But if the proxy is additionally set as environment variables `http(s)_proxy` it does work. That leads to the idea, that different parts of the installation routine read the settings from different places.
