### ISSUE TITLE
findExportByName causes a second instance of module to get loaded into memory

### ISSUE THREAD

**Issue by ocecaco** [frida/frida#445]
Tested on Android 7.1.2 ARM. This issue might be the cause of #247.

When the same module is loaded twice or more into a process (i.e. at different base addresses), findExportByName and findBaseAddress can return information from different instances of the module. Also enumerateMatchesSync behaves strangely.

To clarify a bit:

Suppose libfoo.so is loaded once at base address A and another time at base address B. When I call findBaseAddress with the module name, it returns B (So far so good). Yet when I call findExportByName it returns an address inside module A. I would expect both functions to refer to module A or module B consistently, and not have one of them refer to another module.

Furthermore, when I call enumerateMatchesSync with a pattern that matches the same function I called findExportByName with, it ONLY returns the address inside module instance B. I would expect it to return both matches from A and B. Right now it does not find the export of A that is found by findExportByName.

* Edit
EDIT: It turns out that findExportByName is causing my module to get loaded into the process a second time. Before calling it the module was loaded only once. The other export related functions don’t cause the module to get loaded another time.

**Comment by oleavr** [comment]
It is not well-defined which of the two `libfoo.so` you get in case of duplicates – the proper way to deal with this is to use the full module path everywhere. So instead of `foo.so`, use `/path/to/foo.so`. You could detect this by using `Process.enumerateModulesSync()` to pick the one you want, and assign that to a variable that you use when referencing it.

**Comment by ocecaco** [comment]
In my case both modules have the same path, so this does not work to disambiguate between them. I am not exactly sure how two copies of it are getting loaded, but it only occurs if I call getExportByName.

**Comment by oleavr** [comment]
Ah, that is the issue then – the platform-specific backend in frida-gum should never report duplicates. If you're interested in digging deeper that would be great.

**Comment by mhsjlw** [comment]
After reading 247, and then looking at this issue, I am experiencing the same issue. I will use `findExportByName` and it will print the function pointer, yet Interceptor will never be called. Yet, when using `frida-trace`, it is able to properly hook the function and I have just been using those handlers. I am running Android 7, arm64, like ocecaco and have experienced the issue with multiple Android apps (using Interceptor). I will try using `enumerateModulesSync`.

**Comment by nevermoe** [comment]
@oleavr hi, I'm on Android and I am experiencing the same issue. It seems that first libfoo.so is loaded by the app itself and the second libfoo.so is loaded by frida. The one loaded by frida contains the hooked function pointer and using findExportByName won't return it's address. It will return the un-modified function address from the first libfoo.so and causing my hook not working. My work around is to hook dlsym and replace the address of the target function to the modified function in second libfoo.so. Anyway, I still want to figure out why this happens. It does not happen when I hook libc.so, but it happens when I hook a unity game's so file. Any suggestion?

**Comment by kholia** [comment]
I believe that I ran into this issue today on Android 7.1.1 32-bit.

What works -> `frida-trace -U -i '_ZN14SkMemoryStreamC2EPKvjb' <app>`

The following doesn't work,

```
script = session.create_script("""
var a = Module.findExportByName("libskia.so", "_ZN14SkMemoryStreamC2EPKvjb");
console.log(a);
Interceptor.attach(a, {
    onEnter: function(args) {
    console.log("hello");
    }
});
""")
```

The `console.log` line never executes.

Frida version,

```
$ frida-trace --version
12.0.6
```

**Comment by M47H3W** [comment]
Has anybody found a way around this issue? I seem to be experiencing the same issue and suspect that my code isn't hooking properly.

**Comment by ocecaco** [comment]
I think I worked around the issue by using Module.enumerateExportsSync to obtain a mapping from function names to addresses. Then once you have the address of the function you want you can just hook it normally. As long as you don't ever call findExportByName, everything should work.

**Comment by srcdes** [comment]
`Process.findModuleByName("libmodule.so");` returns `null`.

**Comment by yinjimmy** [comment]
@M47H3W 

I tested your code like bellow:

```js
setImmediate(function () {
    Java.perform(function () {
        var sofile = 'libc.so'
        var module = Process.findModuleByName(sofile)
        module.enumerateExportsSync(module.name).forEach(function (exp) {
            console.log("Hook: " + exp.name + " in: " + module.name + " at: " + ptr(exp.address));
        })
    })
})
```

output:
```
message: {u'columnNumber': 1, u'description': u"TypeError: undefined not callable (property 'enumerateExportsSync' of [object Object])", u'fileName': u'/script1.js', u'lineNumber': 365, u'type': u'error', u'stack': u"TypeError: undefined not callable (property 'enumerateExportsSync' of [object Object])\n    at [anon] (duk_js_call.c:2870)\n    at /script1.js:365"}
```

Whats your frida-server and frida-tools version ?
