### ISSUE TITLE
Is it possible to return/recv a synchronous message?

### ISSUE THREAD

**Issue by H4oK3** [frida/frida#446]
Hey, I am currently working on a tool idea; I would like to achieve sth like this:

when a function get called; it calls send() back to my application and wait for user input before returns or executed; after it gets users' inputs; then the actual function got executed. However, I think right now Frida send/recv function only support asynchronous mode, which is to say there is no way I can make the frida script pause the function execution and wait for my input. I guess one hacky way might be I can call native libc socket function instead of using send/recv so everything can work synchronously, but I would like to ask if you think there is a better way of doing this.

Thanks for the amazing work!

**Comment by oleavr** [comment]
Hey,

Happy to report that this is already supported! Have a look at the last section of this tutorial:
https://www.frida.re/docs/messages/

Cheers!

**Comment by H4oK3** [comment]
Awesome, thanks!
