### ISSUE TITLE
How to modify return  String value when hook native in Android

### ISSUE THREAD

**Issue by YaphetsH** [frida/frida#449]
when jni method return string value,and I use frida to hook native code.
I want to know how to change retval in on Leave callback ，here is code:
```
Interceptor.attach (Module.findExportByName 
( "libnative-lib.so", "Java_com_targetdemo_MainActivity_stringFromJNI"), {
onEnter: function(args) {
        //do something },
 onLeave: function (retval) {
retval.replace(ptr("1234"));				
 }
```
but this doesn't work ,so how to get and modify retval object?

**Comment by lqxn1015** [comment]
I have the same problem. How can solve it?

**Comment by myzhan** [comment]
I have the same problem. I tried this and it didn't work.

var stringClass = Java.use("java.lang.String");
	var stringInstance = stringClass.$new("1234");

    Interceptor.attach(funcAddr, {
        onEnter: function (args) {
            return 0;
        },
        onLeave: function (retval) {
            console.log(stringInstance);
            retval.replace(stringInstance);
        },
    });

**Comment by myzhan** [comment]
OK, this will work.

```java
Interceptor.attach(funcAddr, {
        onEnter: function (args) {
            return 0;
        },
        onLeave: function (retval) {
            const dstAddr = Java.vm.getEnv().newStringUtf("1234");
            retval.replace(dstAddr);
        },
    });
```

**Comment by oleavr** [comment]
@myzhan That works... but it might be easier to hook it by replacing the method through the `Java` API.

**Comment by YaphetsH** [comment]
@myzhan  it works , very thanks

**Comment by henrytom1703** [comment]
Hello @myzhan 
Could you help me resolve this issues: 
https://github.com/frida/frida/issues/655
Thanks

**Comment by iloststars** [comment]
@myzhan 
 thanks very much,it works.But how do you know that it should use newStringUtf() rather than NewStringUTF(),the later is offical API.I would appreciate it if I get your reply.

**Comment by myzhan** [comment]
@iloststars I found the method in the source code of java bridge.

https://github.com/frida/frida-java-bridge/blob/master/lib/env.js

**Comment by iloststars** [comment]
Thanks for your help~

**Comment by Oh-Py-God** [comment]
I am still unable to do this. 

Running `Module.findExportByName("lib<LIBRARY>.so", "Java_<FULLMETHOD>")` returns `null`.
Then, `Interceptor.attach` would throw an error as the funcAddr is `null`.

@myzhan did you something extra that returned non-null value for funcAddr?

Any help would be appreciated. Thanks.

**Comment by YaphetsH** [comment]
> I am still unable to do this.
> 
> Running `Module.findExportByName("lib<LIBRARY>.so", "Java_<FULLMETHOD>")` returns `null`.
> Then, `Interceptor.attach` would throw an error as the funcAddr is `null`.
> 
> @myzhan did you something extra that returned non-null value for funcAddr?
> 
> Any help would be appreciated. Thanks.

Maybe the timing you find module is earlier,try to Interceptor the System.LoadLibrary fun,and get the fix timing when load the target library

**Comment by Oh-Py-God** [comment]
**Update:** I'm able to do this on one device `Xiaomi Mi A1` running on Android 8.1.0.

But still cannot do this for the same application on `Oneplus 2` running on Android 6.0.1. I'm getting the following error:
`Error: libonetest.so: unable to find export 'Java_com_example_nativeone_MainActivity_stringFromJNI'`

Any hints on how to debug this?

**Comment by effortlessdevsec** [comment]
@Oh-Py-God   Use this to enumerate all jni functions

`var process = Process.enumerateModules()
//console.log(process.length)
var i =0;

for(i=0;i<process.length;i++){



if(process[i].path.indexOf('libnative-lib')!=-1)
{
	
	//console.log(JSON.stringify(process[i])+"\n")
    var exports = process[i].enumerateExports()
    for(var j =0;j<exports.length;j++){
    //console.log(JSON.stringify(exports[j]))



if(exports[j].name.indexOf('Java_')!=-1)
{
    console.log(JSON.stringify(exports[j])+"\n")
}


}
}
}`
