### ISSUE TITLE
Detect frida-winjector-helper-32.exe as malware

### ISSUE THREAD

**Issue by dodaeche** [frida/frida#454]
I'm playing with frida for hooking malloc function on Windows. On frida 10.6.61 it works well with no issue. I've just updated frida to version 10.7.6 and run hooking script with frida. Got error message below.

Failed to attach: unable to spawn helper executable at 'C:\Users\world\AppData\Local\Temp\frida-f4e0b5cf03b2f2eab54994597772c743\frida-winjector-helper-32.exe': 0x000000e1

Windows Defener catch frida-winjector-helper-32.exe as malware 'Trojan:Win32/Fuery.A!cl'

**Comment by oleavr** [comment]
Thanks for reporting!

Unfortunately I am not able to reproduce this issue. Either it got infected on your system, or this is a false positive. Defender does not detect it as such on my end, though.

Please reopen if you find any evidence to the contrary.

**Comment by david-wm-sanders** [comment]
![frida_detected_as_trojan](https://user-images.githubusercontent.com/673925/84339506-77b4c080-ab96-11ea-9420-822ce48f81a2.PNG)

Windows Defender flags `frida-winjector-helper-32.exe` as a trojan when I try to use `frida-discover` :/

**Comment by david-wm-sanders** [comment]
As an additional note:
https://www.virustotal.com/gui/file/12cdbd8a583cf4b48dbcb571c2a73478931a19c58e22cffe1e8c25515ed6a976/detection

**Comment by oleavr** [comment]
Thanks for reporting.

This will probably be a never-ending issue as we do inject code into running processes in ways that also malware does. We could digitally sign our binaries, but that would only help until a malware author chooses to build malware on top of Frida, and we'd be back to square one.

Perhaps the best short-term solution, which might buy us some times, is to also link in the winjector-helper code into frida-core and try that first – and only spawn the helper when elevation is needed. A PR adding this would be awesome in case you're interested :-)
