### ISSUE TITLE
[Android] read binary file from sdcard

### ISSUE THREAD

**Issue by kne-eraj** [frida/frida#457]
Trying to read a stored file in sdcard earlier using this piece of code 
![screenshot from 2018-03-25 15-00-48](https://user-images.githubusercontent.com/13537818/37873590-61407a6e-303d-11e8-931c-aef6bdc41430.png)
Couldn't find specific functions to **read** as Javascript API only seemed to highlight **write** functions.
This is the method I am trying to hook to:
`android.security.net.config.RootTrustManager`
What I am trying to achieve is write `List<X509Certificate>` to a file in binary mode to sdcard and reload back from the file,
to bypass SSL Pinning.If any other methods to do the same, please suggest. Thanks.

**Comment by TheDauntless** [comment]
Take a look at the objection framework, which is built on Frida. It provides code for downloading files, and also for ssl pinning bypasses. 

https://github.com/sensepost/objection

Vote to close, as not a frida issue.
