### ISSUE TITLE
Toolchain and SDK

### ISSUE THREAD

**Issue by 0xh0b0** [frida/frida#464]
When a new version of SDK and toolchain released the old versions removed from build.frida.re.
Can you keep the old SDKs and toolchains to allow the building of old Frida versions?

**Comment by oleavr** [comment]
I agree we need a better solution to this... ideally all repos should be tagged with the toolchain/SDK version, and the build system should be able to build the appropriate toolchain/SDK if a prebuilt tarball isn't available. I'm unfortunately spread way too thin to spend time on this, and the risk of using the wrong version (plus the ever-growing disk footprint) lead me to drop obsolete versions. Help appreciated!
