### ISSUE TITLE
Android: Error binding to address: Address already in use

### ISSUE THREAD

**Issue by henrymark92** [frida/frida#471]
How to kill process it without reboot android?
Thanks

**Comment by shivang1989** [comment]
using ps command only fetches 2 PIDs with name "sh" and "ps". 
Can't find frida-server in ps. 
How to solve this ? 

Restarting android device solves the problem but don't want to do that every time.  
Please help.

**Comment by RussiaVk** [comment]
> Maybe you should use **ps** command in shell to find frida-server and use **kill** command to kill it.

no any result
