### ISSUE TITLE
macOS installation 

### ISSUE THREAD

**Issue by klmitchell2** [frida/frida#478]
I have installed frida via npm: `npm install frida`

I am receiving this error on macOS after following the first step in [this tutorial](https://www.frida.re/docs/ios/#with-jailbreak): `-bash: frida-ps: command not found`

I have installed Frida via Cydia as well. 

What part of the tutorial am I following incorrectly? Something seems non-obvious to me.

**Comment by SajjadPourali** [comment]
I think this link could help you.
https://www.frida.re/docs/installation/#install-with-pip

**Comment by minhtt159** [comment]
I'm using frida with pip2 which comes with python2. Hope it might help
```
brew install python2
pip2 install frida
```

**Comment by alyfreym** [comment]
> I'm using frida with pip2 which comes with python2. Hope it might help
> 
> ```
> brew install python2
> pip2 install frida
> ```

python3 recommended instead pthon2.7

**Comment by minhtt159** [comment]
> > I'm using frida with pip2 which comes with python2. Hope it might help
> > ```
> > brew install python2
> > pip2 install frida
> > ```
> 
> python3 recommended instead pthon2.7

It has been too long. I supposed that frida now fully support python3
