### ISSUE TITLE
Add global config options (config.mk)

### ISSUE THREAD

**Issue by radare** [frida/frida#48]
* [ ] enable/disable MAPPER for gum
* [ ] strip final builds
* [ ] which arch to include in the universal bin? (avoid building everything twice for iOS)
* [ ] optimization/debug CFLAGS
* [ ] ...

**Comment by oleavr** [comment]
Oh yes, completely agree. Would also be neat to be able to disable or reduce optimizations and build with ASAN.

**Comment by radare** [comment]
Final builds are stripped by default, the way to disable `strip` is by editing all build/*.rc and change the  `STRIP=` line to be `STRIP=echo`
