### ISSUE TITLE
Handling multithreads

### ISSUE THREAD

**Issue by HarDToBelieve** [frida/frida#482]
Hi,

I'm trying to build an instrument tool which produces the coverage of an application. However, I cannot handle threading stuffs when the app calls `pthread_create` or some functions like that.

I tried to hook those functions, but after that, I didn't know what threadID numbers they would create. I also took the first argument of `pthread_create` then printed out. However, it was totally different from the number when I hooked into a specific function and ran `console.log('ThreadID: ' + this.threadId)`

Is there anyway I can solve this? I searched on google for some scripts but none of them could follow the new threads.

**Comment by HarDToBelieve** [comment]
It seems that the `thread_id` given by agent is under scope of the instrument tool, not target process. So I choose to run `Process.enumerateThreads` each time `pthread_create` is called. As I see it is not stable ( for race-condition reason, maybe ). Any suggestions?

**Comment by oleavr** [comment]
Reverse-engineer the platform's pthread library and find an internal function to hook. Ideally publish a module to npm that abstracts this, and use [frida-compile](https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3) to consume that.

**Comment by vadimszzz** [comment]
> Reverse-engineer the platform's pthread library and find an internal function to hook. Ideally publish a module to npm that abstracts this, and use [frida-compile](https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3) to consume that.

It sounds like frida is not your tool.

**Comment by oleavr** [comment]
@vadimszzz It's been almost four years since that comment. I think it makes sense to have a cross-platform implementation of this in Gum, exposed to GumJS. PR welcome!
