### ISSUE TITLE
Error occurs when injecting code to android app to fetch signatures

### ISSUE THREAD

**Issue by s0be1t** [frida/frida#49]
Hi

Recently i encounter a error when trying to inject code to android app to fetch signatures, here is the js code executing:

Dalvik.perform(function () {
  var application = Dalvik.use("com.test.test").currentApplication();
  var context = application.getApplicationContext();
  var package_name = context.getPakcageName();
  var package_info = context.getPackageManager().getPakcageInfo(package_info, 64);
  send(package_info);
  send(context):
  send(package_name):
  var sign = package_info.signatures[0];
  send(signs);
});

The exception occurs when executing package_info.signatures[0]. It's known to us that it's the way to get signature in java, but i just can't do it in frida:

			PackageInfo packageInfo = context.getPackageManager().getPackageInfo(pkgName, PackageManager.GET_SIGNATURES);
			Signature[] signs = packageInfo.signatures;
			Signature sign = signs[0];
                        getMD5(sign.toByteArray());

The class "PackageInfo" and "Signature" are all class that implement interface "Percelable", the difference is "PackageInfo" implements "toString" while "Signature" only implements "toCharsString", i don't know if it matters. Is there anything i missed?

**Comment by s0be1t** [comment]
btw, the error message description i get is
"TypeError: cannont read property '0' of undefined", meanwhile, signs is not an array? But even i send package_info.signatures directly, there is no neither payload or error field in message, i get a pure message like this:

{u'type': u'send'}

Any thought?

**Comment by oleavr** [comment]
Hi,

The Dalvik integration doesn't yet support fields, only methods. I think @marc1006 started on a patch adding support for this, so hopefully this might happen in the near future.

Cheers!

**Comment by s0be1t** [comment]
Thx! I'll wait for the new version.

**Comment by marc1006** [comment]
@s0be1t it should work fine now
```javascript
Dalvik.perform(function () {
   ...
   const sign = package_info.signatures.value[0];
   ...
});
```

**Comment by oleavr** [comment]
Considering this one fixed.
