### ISSUE TITLE
Any supported Emulator?

### ISSUE THREAD

**Issue by HamidZaeri** [frida/frida#492]
What emulators work with frida-server?
I tried nox with frida x86 but nothing happen after starting server!

**Comment by oleavr** [comment]
Stay away from memu, nox, etc., that is, emulators with an old VM, i.e. Dalvik, and emulators that are x86 but pretend to be arm, so they emulate any JNI libraries. Use stock emulator images from Google, ideally something on Android 8.x, or an image from Genymotion. As for physical devices I'd recommend getting a Nexus 5X – my primary test-device these days is a 5X running 8.1.0.

**Comment by hagolo** [comment]
> Stay away from memu, nox, etc., that is, emulators with an old VM, i.e. Dalvik, and emulators that are x86 but pretend to be arm, so they emulate any JNI libraries. Use stock emulator images from Google, ideally something on Android 8.x, or an image from Genymotion. As for physical devices I'd recommend getting a Nexus 5X – my primary test-device these days is a 5X running 8.1.0.

Thanks )

**Comment by srcdes** [comment]
@oleabr Nexus 5X LG-H791 right?
