### ISSUE TITLE
how to replace value of input argument array when hook native .so

### ISSUE THREAD

**Issue by henrytom1703** [frida/frida#493]
Ex:
int _put_data(const char *name, char *value)
 input:  name = "age", value = "40"

 
```
  Interceptor.attach (Module.findExportByName ( "libbcc.so", "_put_data"), {
        onEnter: function (args) {
                    this.key = Memory.readUtf8String(args[0]);
                    console.log(this.key);
                    this.value = Memory.readUtf8String(args[1]);
                    console.log(this.value);
                 
        },
        onLeave: function (retval) {
        
         }
    });
```

I want to replace input argument (ex: replace input value "40" -> "18" ). How ?
And how to convert a String value to pointer(Ex: "40" -> pointer)
Thanks

**Comment by huhuang03** [comment]
Same question!

**Comment by duolaaa** [comment]
@henrytom1703 @bxl0608 @huhuang03  can you solved this problem?

**Comment by huhuang03** [comment]
May be you can try https://www.frida.re/docs/javascript-api/#nativepointer, such as new NativePointer("the value you want replace"). The doc says the value is a address, but may be can use the original int value. Maybe, I can't remember clearly.

**Comment by huhuang03** [comment]
In tutorial https://www.frida.re/docs/functions/. There's a demo use `args[0] = ptr("1337");`. May be this is you want.

**Comment by duolaaa** [comment]
@henrytom1703,  thank you, I want to console log input argument ,ex:

```
Interceptor.attach(Check,{
            onEnter: function(args){
                send(typeof(Memory.readCString(args[2])));
                send(Memory.readCString(args[2]).toString());
                send(Memory.readCString(args[2]));
                }
        });
```

but the result is:
![image](https://user-images.githubusercontent.com/15665926/55201053-312aae80-51fc-11e9-8a95-283a7d6fca21.png)

**Comment by huhuang03** [comment]
May be you can try Memory.readUtf8String

**Comment by oleavr** [comment]
Try: `args[2].readUtf8String()` (The old `Memory.read/write*()` API is deprecated.)

**Comment by duolaaa** [comment]
@oleavr  thank you ,and it retured:

```
TypeError: undefined not callable (property 'readUtf8String' of [object Object])
    at [anon] (duk_js_call.c:2870)
    at /repl26.js:22
```

@huhuang03 , i used Memory.readUtf8String, it failed: 

```
Error: can't decode byte 0xe0 in position 0
    at /repl28.js:21
```

i want hook a native (android app so file ) method's argments , 
use the command : 
`frida -U -l hook_native.js -f com.company.android
`


my js file is:
```
setImmediate(function(){
    console.log("Running Script");
    Java.perform(function(){
        var securityCheck = undefined;
        exports = Module.enumerateExportsSync("libcrackme.so");
        for(i=0; i<exports.length; i++){
            if(exports[i].name == "Java_com_company_android_MainActivity_securityCheck"){
                securityCheck = exports[i].address;
                send("Pointer is at " + securityCheck);
                break;
            }
        }

        Interceptor.attach(securityCheck,{
            onEnter: function(args){
                send(typeof(Memory.readCString(args[2])));
                send(Memory.readCString(args[2]).toString());
                send(Memory.readCString(args[2]));
                send("================");
                send(Memory.readUtf8String(args[2]));

                send(args[2].readUtf8String());
                send(Memory.readByteArray(securityCheck,65534));
              }
        });
    });
});
```

**Comment by duolaaa** [comment]
use Java.cast can solve this , thank you all very much .

```
var String_java = Java.use('java.lang.String');
var args_2 = Java.cast(args[2], String_java);
send("get args[2] value: " + args_2);
```

**Comment by oleavr** [comment]
@duolaaa That means you're running an old version of Frida. Please ensure you're running the latest before reporting bugs.
