### ISSUE TITLE
Frida Server 11.0.0 Android crashing with gum_thumb_writer_put_argument_list_setup_va: code should not be reached

### ISSUE THREAD

**Issue by clviper** [frida/frida#495]
Hello,

I'm running frida-server 11.0.0 arm64 on Nexus 5x with Android 6.0.1

When I try to spawn a new app with "frida -U -l script.js -f  process" the device soft reboots.

The errors recorded in the logs are:

"05-07 11:10:05.247 11648 16923 F Frida   : frida-gum/gum/arch-arm/gumthumbwriter.c:360:gum_thumb_writer_put_argument_list_setup_va: code should not be reached
05-07 11:10:05.248 11648 16923 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 16923 (main)"

**Comment by clviper** [comment]
Have the same behavior in version 10.8.2. In 10.7.7 is working correctly.

**Comment by mhsjlw** [comment]
Experiencing the same crash (on 11.0.0) with `process = frida.get_usb_device().spawn("com.example.app")`, Android 7.

**Comment by oleavr** [comment]
Thanks for reporting! Fixed in 11.0.1, currently being released.

**Comment by clviper** [comment]
Awesome @oleavr . Thnks for the quick fix.

**Comment by clviper** [comment]
Just tested and it's working. Thanks @oleavr!

**Comment by mhsjlw** [comment]
I just tested again using the exact same code I posted above using version 11.0.1 on both my Android phone and device and my phone just soft rebooted like it did before the patch. How can I provide information to help debug this?

**Comment by mhsjlw** [comment]
I have also tested using `frida-trace`, and it has successfully spawned the app and did not crash my phone.
