### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by handjoywqh** [frida/frida#497]
Installing collected packages: colorama, six, wcwidth, prompt-toolkit, pygments, frida
  Running setup.py install for frida ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-IeglSl/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-QmFdvF/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    creating build/lib.macosx-10.12-intel-2.7/frida
    copying frida/__init__.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/application.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/core.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/discoverer.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/kill.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/lsd.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/ps.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/repl.py -> build/lib.macosx-10.12-intel-2.7/frida
    copying frida/tracer.py -> build/lib.macosx-10.12-intel-2.7/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/wangqinghui/frida-11.0.1-py2.7-macosx-10.11-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-IeglSl/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-QmFdvF/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-IeglSl/frida/

- macOS 10.12.6
- Python 2.7.10
- Pip 10.0.1

**Comment by oleavr** [comment]
Updating your macOS system to the latest, currently `10.13.4`, should solve this issue. Your system's OpenSSL is too old.

**Comment by 19oos** [comment]
> Updating your macOS system to the latest, currently `10.13.4`, should solve this issue. Your system's OpenSSL is too old.

@oleavr hi, I got the same issue.  
macOS 10.14.2
python  2.7.13
pip 18.1

Here is the Errinfo:
py2android ❯ pip install frida-tools
Collecting frida-tools
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /Users/user/py2virtualenv/py2android/lib/python2.7/site-packages (from frida-tools) (0.4.1)
Collecting frida<13.0.0,>=12.1.0 (from frida-tools)
  Using cached https://files.pythonhosted.org/packages/28/57/dfd4b2965cb5a9d13e998aba038eb0d8150f1570e0c12a78158278a7403f/frida-12.2.27.tar.gz
Collecting pygments<3.0.0,>=2.0.2 (from frida-tools)
  Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=0.57 (from frida-tools)
  Using cached https://files.pythonhosted.org/packages/d1/b0/1a6c262da35c779dd79550137aa7c298a424987240a28792ec5ccf48f848/prompt_toolkit-1.0.15-py2-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=0.57->frida-tools)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /Users/user/py2virtualenv/py2android/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=0.57->frida-tools) (1.12.0)
Building wheels for collected packages: frida
  Running setup.py bdist_wheel for frida ... error
  Complete output from command /Users/user/py2virtualenv/py2android/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0f/v781tmf53yb24d4mmf0rwh4w0000gp/T/pip-install-C_ne2l/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/0f/v781tmf53yb24d4mmf0rwh4w0000gp/T/pip-wheel-LUOvVB --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-2.7
  creating build/lib.macosx-10.6-intel-2.7/frida
  copying frida/__init__.py -> build/lib.macosx-10.6-intel-2.7/frida
  copying frida/core.py -> build/lib.macosx-10.6-intel-2.7/frida
  running build_ext
  querying pypi for available prebuilds
  network query failed
  looking for prebuilt extension in home directory, i.e. /Users/user/frida-12.2.27-py2.7-macosx-10.9-intel.egg
  no prebuilt extension found in home directory
  error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>

  ----------------------------------------
  Failed building wheel for frida
  Running setup.py clean for frida
Failed to build frida
Installing collected packages: frida, pygments, wcwidth, prompt-toolkit, frida-tools
  Running setup.py install for frida ... error
    Complete output from command /Users/user/py2virtualenv/py2android/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0f/v781tmf53yb24d4mmf0rwh4w0000gp/T/pip-install-C_ne2l/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/0f/v781tmf53yb24d4mmf0rwh4w0000gp/T/pip-record-iZUWw3/install-record.txt --single-version-externally-managed --compile --install-headers /Users/user/py2virtualenv/py2android/bin/../include/site/python2.7/frida:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/frida
    copying frida/__init__.py -> build/lib.macosx-10.6-intel-2.7/frida
    copying frida/core.py -> build/lib.macosx-10.6-intel-2.7/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/user/frida-12.2.27-py2.7-macosx-10.9-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>

    ----------------------------------------
Command "/Users/user/py2virtualenv/py2android/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0f/v781tmf53yb24d4mmf0rwh4w0000gp/T/pip-install-C_ne2l/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/0f/v781tmf53yb24d4mmf0rwh4w0000gp/T/pip-record-iZUWw3/install-record.txt --single-version-externally-managed --compile --install-headers /Users/user/py2virtualenv/py2android/bin/../include/site/python2.7/frida" failed with error code 1 in /private/var/folders/0f/v781tmf53yb24d4mmf0rwh4w0000gp/T/pip-install-C_ne2l/frida/

**Comment by thejunkjon** [comment]
@19oos , this seems to be very similar to your issue.

https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version

The solution stated in the link above was to update/install openssl and python3.  You might want to give that a try and see if the issue goes away.
