### ISSUE TITLE
Spawn not working on iOS 11.1.2 with Frida 11.0.1

### ISSUE THREAD

**Issue by manuumanuu** [frida/frida#498]
The spawn feature is not working in the newest Frida version. I use Frida 11.0.1 on the PC and on the phone (iOS 11.1.2 with Electra  1.0.4)

I always get the message "Failed to spawn: unexpectedly timed out while waiting for process to suspend" when calling " frida-trace -R -f ch.asdf.asdf"

The app opens on the phone but frida is not attached.

**Comment by mhsjlw** [comment]
On Android, it just crashes when using 11.0.1

**Comment by oleavr** [comment]
No issues here on Electra 1.0.4 w/tweaks enabled. Either you have a different setup, or a tweak is causing issues.

**Comment by minhtt159** [comment]
I'm having the same trouble as well
1. macOS 10.13.4
2. python3 & python2 installed and updated with Homebrew
3. frida 11.0.3 on both host/slave
4. iOS version 11.0.3 w Electra 1.0.4 w/tweaks enabled
frida can not spawn process, but attach seems ok.

**Comment by kov4l3nko** [comment]
Frida 11.0.3 on iPhone 5s iOS 11.0.1 Electra JB 1.0.4 with Tweaks. 

The same issue: spawn doesn't work (I got "Failed to spawn: unexpectedly timed out while waiting for process to suspend"). Attach is ok.

**Comment by lasting-yang** [comment]
frida -U --no-pause -f "com.facebook.Facebook" -l ios_hook.js

I can spawn the facebook process.

**Comment by kov4l3nko** [comment]
> frida -U --no-pause -f "com.facebook.Facebook" -l ios_hook.js
> 
> I can spawn the facebook process.

The issue I mentoided is a history now. It was fixed several version ago, so please just ignore my previous comment.

**Comment by masbog** [comment]
pardon me comment on closed issues, i got "Failed to spawn: argument 1 must be string, not list" did i missing the argument?

![image](https://user-images.githubusercontent.com/663374/56912763-379d9600-6ada-11e9-95d1-d4965fa6e22c.png)


thanks...
