### ISSUE TITLE
pass null to constructor in android

### ISSUE THREAD

**Issue by leonbotros** [frida/frida#512]
So, I'm dealing with some obfuscated constructor code that looks like this:

``   public C5227a(String str, String str2, Integer num, List<String> list) {
            this.f15335a = str;
            this.f15336b = str2;
            this.f15337c = num;
            this.f15338d = list;
        }
``
When I watch the init function and log the arguments, I always get a "null" value for the list.
However when I try to call this constructor with 2 strings, 1 int and a null, I get an error:

Error: <init>(): argument types do not match any of:
	.overload('java.lang.String', 'java.lang.String', 'java.lang.Integer', 'java.util.List')

Is there way to pass a null value to this constructor? If so, how?

Code:
```
queryClass.$init.implementation = function (str, str2, num, list) {
console.log("got called ");
        console.log(str, str2, num , list); // prints str1 str2 1 null
        return this.$init(str, str2, num, list);
    }
var query = queryClass.$init("str1", "str2", 1, null); // gives the error
```

**Comment by thanhvd-metric** [comment]
how did you solve this?

**Comment by thinhbuzz** [comment]
> how did you solve this?

Use NULL
