### ISSUE TITLE
Frida connect to remote frida-server seems not working

### ISSUE THREAD

**Issue by minhtt159** [frida/frida#517]
I know people usually attach their devices over USB, but my girlfriend just borrow my cable and I don't know what to do. I thought Frida has function "-H HOST" to connect to remote frida-server. But I failed to connect.

```
$ frida-ps -Ha 192.168.0.102
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/frida/application.py", line 415, in _run
    work()
  File "/usr/local/lib/python2.7/site-packages/frida/application.py", line 270, in _try_start
    self._start()
  File "/usr/local/lib/python2.7/site-packages/frida/ps.py", line 58, in _start
    self._update_status("Failed to enumerate processes: %s" % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16: ordinal not in range(128)
```
```
frida-trace -H 192.168.0.102 Safari -i "*open*"
Failed to attach: unable to connect to remote frida-server 
```

**Comment by jglimmers** [comment]
Same with my situation. Did you solve that?

**Comment by minhtt159** [comment]
Seems not. I hope the author will fix it some day

**Comment by droidresearch** [comment]
This is related to UTF encoding issue. The quick way to solve this is to use python3 at the client side.
pip3 install frida-tools

should solve the issue.

**Comment by minhtt159** [comment]
@droidresearch 
```
$ ssh root@192.168.137.194
The authenticity of host '192.168.137.194 (192.168.137.194)' can't be established.
RSA key fingerprint is SHA256:------------------------------------
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.137.194' (RSA) to the list of known hosts.
root@192.168.137.194's password: 
Johns-iPhone:~ root# exit
logout
Connection to 192.168.137.194 closed.
$ frida-ps -H 192.168.137.194
Failed to enumerate processes: unable to connect to remote frida-server 
```
It failed, in my case.

**Comment by oleavr** [comment]
@minhtt159 Did you tell `frida-server` to listen on that interface? (By default it only listens on loopback.)

**Comment by oleavr** [comment]
Anyway, this is not a bug as I've been using this feature myself a lot. The unicode issue, however, should be filed in the [frida-tools](https://github.com/frida/frida-tools) repo. And if you feel like opening a PR to fix it that would be even better! :-)

**Comment by Mr-suspicious** [comment]
Hello,

I am trying to run frida-server on my non-rooted device (Samsung S7). Whenever I try to run the command adb shell "**/data/local/tmp/frida-server &**" it outputs nothing; however, when i try to run by getting inside the adb shell and then run command, it outputs **[1] 20884**  (some random number). While when i type frida-ps -U command on separate command prompt it throws this error: **Failed to enumerate processes: unable to connect to remote frida-server: Unexpected lack of content trying to read a line**

Please anyone can guide in this? Complete details are as follows:

Device: Samsung S7 - arm64 - v8a (Non-rooted)
Frida Server version: frida-gadget-12.8.11-android-arm64.so.xz
Frida installed using pip:  Frida 12.8.11
System OS: Windows 10

Error caused : 

1.  Failed to enumerate processes: unable to connect to remote frida-server: Unexpected lack of content trying to read a line.
2.  Failed to spawn: unable to connect to remote frida-server: Unexpected lack of content trying to read a line

**Comment by Mr-suspicious** [comment]
> Hello,
> 
> I am trying to run frida-server on my non-rooted device (Samsung S7). Whenever I try to run the command adb shell "**/data/local/tmp/frida-server &**" it outputs nothing; however, when i try to run by getting inside the adb shell and then run command, it outputs **[1] 20884** (some random number). While when i type frida-ps -U command on separate command prompt it throws this error: **Failed to enumerate processes: unable to connect to remote frida-server: Unexpected lack of content trying to read a line**
> 
> Please anyone can guide in this? Complete details are as follows:
> 
> Device: Samsung S7 - arm64 - v8a (Non-rooted)
> Frida Server version: frida-gadget-12.8.11-android-arm64.so.xz
> Frida installed using pip: Frida 12.8.11
> System OS: Windows 10
> 
> Error caused :
> 
> 1. Failed to enumerate processes: unable to connect to remote frida-server: Unexpected lack of content trying to read a line.
> 2. Failed to spawn: unable to connect to remote frida-server: Unexpected lack of content trying to read a line

@oleavr appreciate your valuable input in said matter :)

**Comment by Aiswarya** [comment]
I am also getting the same error. Could some one let me know what is the solution for this?

**Comment by sg552** [comment]
I met the same problem.  My root cause is :  The current user in adb shell just LOOKS LIKE root, but it actually not root .

My solution:  switch to root user before running 'frida-server'. e.g.:

```
in pc         > $ adb shell
in android > $ su root
in android > $ frida-server -d 

```

> Hello,
> 
> I am trying to run frida-server on my non-rooted device (Samsung S7). Whenever I try to run the command adb shell "**/data/local/tmp/frida-server &**" it outputs nothing; however, when i try to run by getting inside the adb shell and then run command, it outputs **[1] 20884** (some random number). While when i type frida-ps -U command on separate command prompt it throws this error: **Failed to enumerate processes: unable to connect to remote frida-server: Unexpected lack of content trying to read a line**
> 
> Please anyone can guide in this? Complete details are as follows:
> 
> Device: Samsung S7 - arm64 - v8a (Non-rooted)
> Frida Server version: frida-gadget-12.8.11-android-arm64.so.xz
> Frida installed using pip: Frida 12.8.11
> System OS: Windows 10
> 
> Error caused :
> 
> 1. Failed to enumerate processes: unable to connect to remote frida-server: Unexpected lack of content trying to read a line.
> 2. Failed to spawn: unable to connect to remote frida-server: Unexpected lack of content trying to read a line

**Comment by lesleyxyz** [comment]
For me, updating Magisk to the latest version + updating frida and frida-server worked

**Comment by agentanonymus** [comment]
How to use Frida via Wi-Fi purification:

There is a simple way to use remote access via Wi-Fi purification.

First, activate the Wi-Fi purification:

Clique at the top and bottom or IP and at the door of access.
No terminal or CMD from your PC, execute or command:
Copy
adb connect <endereço_IP_do_seu_disposizione>:45844
Please note: Your PC and mobile phone must be connected via Wi-Fi.

After executing the command in terminal or CMD on your PC, you will see a connection message.

Below, connect to Frida's servant in the following way:

Copy
./frida-server -l <endereço_IP_do_seu_device>
