### ISSUE TITLE
Frida hooking onClick function

### ISSUE THREAD

**Issue by localacct** [frida/frida#522]
Hi all

I am currently testing Frida and using online tutorials for it (https://www.notsosecure.com/pentesting-android-apps-using-frida/).

In one of the apks (Insecure bank application v2), there is an onClick event which I want to hook

```
import android.view.View;
import android.view.View.OnClickListener;

public class dClass
extends Activity
{
    //....code....
    protected void onCreate(Bundle dBundle)
    {
        //....code....
        this.dButton.setOnClickListener(new View.onClickListener()
        {
                public void onClick(View dView)
                {
                    //....code....
                }
        }       
       );
    }
}
```

I tried the following code, there were no errors when running the python script but clicking on buttons did not trigger the hook. Below is the code snippet

```
Java.perform(function(){
    //....code....

    var hook_click=Java.use("android.view.View$OnClickListener");
    hook_click.onClick.implementation=function(z){
                console.log("onClick hook");
        };
    //....code....
});
```

If I tried using only "android.view.View", there is no OnClickListener for me to hook so I appended "....$OnClickListener" at the end. I also tried to use "android.view.View.OnClickListener" but an error indiciated that no such class is found.

Am I doing it the right way?

**Comment by agrawalsmart7** [comment]
Did you find the way? I am also stuck at that.

**Comment by Rich2020** [comment]
Your javascript should look something like this:

```
jscode = """
Java.perform(function () {
  // Function to hook is defined here
  var MainActivity = Java.use('com.example.androiddemo.MainActivity');

  // Whenever button is clicked
  var onClick = MainActivity.onClick;
  onClick.implementation = function (v) {
    // Show a message to know that the function got called
    send('Intercepted before button click event. Running onClick code...');

    // Call the original onClick handler
    onClick.call(this, v);

    // Log to the console that it's done, and we should have the flag!
    console.log('Done:' + JSON.stringify(this));
  };
});
"""
```

Note the **MainActivity**.
You also need to modify the attach command:

`process = frida.get_usb_device().attach('com.example.androiddemo')`


**com.example.androiddemo** is your app name - this can be found by loading up your app on your device, then in terminal run the `frida-ps -U` command to see a list of running processes (one of which will be your application).

**Comment by localacct** [comment]
@Rich2020 Thanks for the explanation. Will give it a try.
