### ISSUE TITLE
How to hook apk library class?Java.use can not found class

### ISSUE THREAD

**Issue by koangel** [frida/frida#533]
I have a game apk package.
It's have a function in sub apk library,
How to hook other apk or dex library? this game package include apk library.
It's path like : assests/modules/com.abcd.com.apk.

Java.enumerateLoadedClasses can print target class name.
Lcn/game/center/lib/network/SDKHttpRequest

but Java.use show error: java.lang.ClassNotFoundException: Didn't find class "cn.game,center.lib.network.SDKHttpRequest".

print class code:

 send('start enumerateLoadedClasses...')
        Java.enumerateLoadedClasses({
            onMatch: function(classname){
                if (classname.indexOf('cn/game/center/lib/network/SDKHttpRequest') != -1) {
                    send(classname);
                }
            },
    
            onComplete: function (){
            }
        });

and hook code:

 try
        {
            var reqClass = Java.use("cn.game,center.lib.network.SDKHttpRequest")
            send("setTimeout() -> go hook");
            reqClass.a.overload('java.lang.String','java.lang.String','java.lang.String','boolean').implementation = function (url,body,service,canTry) {
                send("request()");
                var log = "body:" + body + ",url:" + url+ ",service:"+service
                send(log)
                console.log(log)
                    
                this.a(url,body,service,canTry);
            };  
        }catch(ex) {
            console.log(ex)
        }

**Comment by koangel** [comment]
Android 4.4
ABI:"x86"

**Comment by ChiChou** [comment]
Can't you see the comma instead of dot in your class name?

**Comment by koangel** [comment]
已修复

**Comment by Gunkkk** [comment]
> 已修复

请问怎么修复的

**Comment by moovida-me** [comment]
哈哈哈哈哈哈~~~放大都找不到问题的.建议去看眼科~~

**Comment by koangel** [comment]
> 哈哈哈哈哈哈~~~放大都找不到问题的.建议去看眼科~~

傻逼？

**Comment by koangel** [comment]
> Can't you see the comma instead of dot in your class name?
> 
> 把这个字符串，放大字号了看："cn.game,center.lib.network.SDKHttpRequest"

老子不是这个傻逼，我是因为这个CLASS混淆了，脑残

**Comment by koangel** [comment]
> 哈哈哈哈哈哈~~~放大都找不到问题的.建议去看眼科~~

你个傻逼，我TM是因为CLASS被混淆了，所以没有这个类，我解决是把他反混淆了，脑子有病就去看病，傻逼
