### ISSUE TITLE
Frida Server Installation Error in Genymotion

### ISSUE THREAD

**Issue by manish199014** [frida/frida#534]
I am trying to install Frida 11.0.12 version server on Genymotion Android Emulator. I have successfully pushed the file but unable to start the server. I am getting following error.
./frida-server-11.0.12-android-x86.xz[1]: syntax error: ')' unexpected

To set up this I m using a Macbook and I have also tried the same on Ubuntu 18.04 VM machine but the error was same. Can anyone help me in a right direction?

**Comment by enovella** [comment]
Did you unpack the file `xz`?
