### ISSUE TITLE
OpenSSL fails to build when trying to build linux-arm SDK

### ISSUE THREAD

**Issue by stevielavern** [frida/frida#535]
Hi,
Since the linux-arm binaries are no longer released, I am trying to build them myself. However, it requires to first build the linux-arm SDK first, and this fails because of OpenSSL:
```
$ make -f Makefile.sdk.mk FRIDA_HOST=linux-arm
[...]
cp -a openssl build/fs-tmp-linux-arm/openssl
. build/fs-env-linux-arm.rc \
	&& . $CONFIG_SITE \
	&& export CC CFLAGS \
	&& cd build/fs-tmp-linux-arm/openssl \
	&& perl Configure \
		--prefix=$frida_prefix \
		--openssldir=/etc/ssl \
		no-comp \
		no-ssl2 \
		no-ssl3 \
		no-zlib \
		no-shared \
		enable-cms \
		 \                      # <== issue there: empty target name  
	&& make depend \
	&& make \
	&& make install_sw
Configuring OpenSSL version 1.1.0h (0x1010008fL)
[...]
Configuring for
Warning! target  doesn't exist!
Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-dso] [no-egd] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--config=FILE] os/compiler[:flags]
[...]
NOTE: If in doubt, on Unix-ish systems use './config'.
Makefile.sdk.mk:374: recipe for target 'build/fs-linux-arm/lib/pkgconfig/openssl.pc' failed
make: *** [build/fs-linux-arm/lib/pkgconfig/openssl.pc] Error 1
```
This is because no target was selected for OpenSSL. To solve the issue, you need to add `linux-armv4` to the OpenSSL compile line:

```
$ . build/fs-env-linux-arm.rc && . $CONFIG_SITE && export CC CFLAGS && cd build/fs-tmp-linux-arm/openssl && perl Configure --prefix=$frida_prefix --openssldir=/etc/ssl no-comp no-ssl2 no-ssl3 no-zlib no-shared enable-cms linux-armv4
$ make 
$ make install_sw
```

Then, re-run `make -f Makefile.sdk.mk FRIDA_HOST=linux-arm` and it should continue.

The next fail will be here:

```
/usr/bin/env: ‘/opt/python27-64/bin/python’: No such file or directory
[11/67] Generating path.test with a custom command.
ninja: build stopped: subcommand failed.
Makefile.sdk.mk:396: recipe for target 'build/fs-linux-arm/lib/pkgconfig/json-glib-1.0.pc' failed
make: *** [build/fs-linux-arm/lib/pkgconfig/json-glib-1.0.pc] Error 1
```

This is because of a hardcoded path in an a script and can be easily fixed, see https://github.com/frida/frida-core/issues/179.

Once fixed, the linux-arm SDK should build.

**Comment by oleavr** [comment]
Would you be interested in opening PRs for these issues? Would love to get these things fixed.

**Comment by r0ck3tAKATrashPanda** [comment]
@oleavr Can you provide some details on how your build/fs-toolchain and build/toolchain are auto-generated. This seems to appear in multiple files, and it would be a better fix to change how they are being generated than to patch them post generation. I haven't had luck tracking down the generation of these files though.

**Comment by oleavr** [comment]
@r0ck3tAKATrashPanda They're generated by `Makefile.toolchain.mk`.
