### ISSUE TITLE
Delay in script execution does not work

### ISSUE THREAD

**Issue by vellrya** [frida/frida#537]
Hello again, thanks for the quick previous answer, thanks to your hint, I was able to run the necessary activity.

I need to do this in a certain period of time. For example, at 10:00:00. For this I wrote the following code:

```
Java.perform(function () {


//initialize context, packagemanager, etc here


        var now = new Date();
        var needTime = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 10, 0, 0, 0);
        console.log(now);
        console.log(needTime);
        var millisTill10 = needTime - now;
        console.log(millisTill10);
        setTimeout(function () {
            console.log('Hello');
            var launchIntent = packageManager.getLaunchIntentForPackage("com.sample1.sample2");
            launchIntent.setClassName("com.sample1.sample2", "com.sample1.sample2.SampleActivity3");
            launchIntent.putExtra("123", "321");
            launchIntent.putExtra("abc", "def");
            context.startActivity(launchIntent);

        }, millisTill10);
});
```
If I run this code without a timer, I see the "hello" in the console and the SampleActivity3 actually opens, but it happens at 10:00:02 (this delay of two seconds is very important for my application, it's probably not relevant to the problem, but the time in Frida does not coincide with the time set on the computer)

If I execute the code above, I'll see the "hello" in the console, but the activity does not start. I tried to make this code into a separate function, which was started by timer, but it did not bring any result.

My question: Is it possible to use timers in a script and how to implement them correctly?

Thanks again for the previous answer, I hope for your advice)

**Comment by oleavr** [comment]
You need to wrap your timer code in a `Java.perform()`. Also, `Date.now()` is more idiomatic than doing arithmetic with `Date` instance that you got from `new Date()`.
