### ISSUE TITLE
frida makes target app crash on android

### ISSUE THREAD

**Issue by pandaiolo** [frida/frida#54]
I could find another device to test frida-server on android : galaxy tab pro 10.1 wifi, rooted with kitkat 4.4.2

I managed to make the tutorial work with the camera app, but not google chrome or other apps like snap chat : they crash instantly when I try to attach to the process. 

Process listing is working fine. 

Same bug when trying with locally built frida-server binary

**Comment by oleavr** [comment]
Ouch. I'm currently deep down in iOS land, but I'll try to find some time to investigate this Android issue sometime this weekend.

**Comment by StefaanSeys** [comment]
Same problem for me. I created a tiny HelloWorld Android App and when I attach to it, the app instantly crashes, the same for a couple of other Apps from the store.

The server does not output anything and keeps running...

This is the output of the python script:
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> session = frida.get_remote_device().attach("org.proxydroid")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/frida-4.2.6-py2.7-linux-x86_64.egg/frida/core.py", line 73, in attach
frida.TransportError: unexpectedly timed out while waiting for FIFO to establish
```

Software versions:
frida-server 4.2.6 (binary from build.frida.re)
host: cyanogenmod 10.2.1 (Android 4.3.1) on Galaxy S4

**Comment by vtky** [comment]
Hey,

I'm also getting the same issue. "Failed to attach: unexpectedly timed out while waiting for FIFO to establish"

I'm attaching to com.android.chrome. Application crashes if I try to run frida-trace or frida-discover.

Frida Server 4.3.6
Nexus 5 Android v5.0.1

**Comment by oleavr** [comment]
Fixed in latest git. We now support devices with SELinux in enforcing mode, there's ART support, and 64-bit ARM devices work too (verified on a Samsung Galaxy S6 Edge). Enjoy!
