### ISSUE TITLE
Windows-10: Unable to run Frida command

### ISSUE THREAD

**Issue by manish199014** [frida/frida#550]
Hello,

I am getting the following error while running the command. is there anything I am missing here? also what is the default location of Frida binaries on windows.

![image](https://user-images.githubusercontent.com/14213944/42590106-80eb16ee-8560-11e8-93e3-e8a5e98bdf36.png)

Please help me to get rid from this error.

Thanks

**Comment by oleavr** [comment]
As of Frida 12.0 the CLI tools have been moved to `frida-tools`, so do: `pip install frida-tools`
