### ISSUE TITLE
iOS server is outdated

### ISSUE THREAD

**Issue by AeonLucid** [frida/frida#551]
Hi,

With 12.0.1 being out and the only option available for "frida-tools" (pip install `frida-tools`), could there also be an update for the cydia repository? The latest version available is 11.0.13.

It also seems like the `frida-server` binary for iOS got skipped entirely. 
See https://build.frida.re/frida/ios/bin/, last update `16-May-2017 22:20`.

**Comment by oleavr** [comment]
Thanks! Currently publishing Frida 12.0.2, which should hopefully make it all the way through the release script.

**Comment by oleavr** [comment]
Fixed in 12.0.3. Cheers!

**Comment by AeonLucid** [comment]
Can confirm, thank you.

Would like to point out that the binary on https://build.frida.re/frida/ios/bin/ is still outdated.
