### ISSUE TITLE
Error: MemoryAccessMonitor is not yet available in the Duktape runtime

### ISSUE THREAD

**Issue by Palacee-hun** [frida/frida#553]
Maybe worth fixing this most probably accidental omission in the 12.x release iteration of Frida as its main focus is API stabilisation and correction.

**Comment by oleavr** [comment]
Totally agree. PR welcome!

**Comment by michalfapso** [comment]
If you just need to use the MemoryAccessMonitor, try to run Frida with `--enable-jit`, it worked for me.

**Comment by alvarofe** [comment]
This can be closed - it has been implemented

**Comment by oleavr** [comment]
Yes, this is now available in 12.7.10 thanks to @alvarofe 🙌
