### ISSUE TITLE
how to trace function without class 

### ISSUE THREAD

**Issue by gaplan** [frida/frida#555]
; XREF=imp___picsymbolstub4__CFUUIDCreate

void CFUUIDCreate() {
    r0 = CFUUIDCreate(r0);
    return;
}

**Comment by gaplan** [comment]
i found this;

Interceptor.attach(Module.findExportByName(null, 'CFUUIDCreateString'), {
    onEnter: function (args) {
        console.log('Context information:');
        console.log('Context  : ' + JSON.stringify(this.context));
        console.log('Return   : ' + this.returnAddress);
        console.log('ThreadId : ' + this.threadId);
        console.log('Depth    : ' + this.depth);
        console.log('Errornr  : ' + this.err);


**Context information:
Context  : {"pc":"0x25eab9f4","sp":"0x8415bc","r0":"0x0","r1":"0x175b6dd0","r2":"0x0","r3":"0x0","r4":"0x5e2028","r5":"0x0","r6":"0x175b6dd0","r7":"0x8415e0","r8":"0x5e14f8","r9":"0x3c787908","r10":"0x0","r11":"0x6b31ac","r12":"0x25eab9f5","lr":"0x7d2ed"}**

how can i read each of them ?

**Comment by gaplan** [comment]
is there anyone ?

**Comment by oleavr** [comment]
Like this: `this.context.r0`

**Comment by gaplan** [comment]
sorry for disturb, but i want to read what's in it.
this.context.r0
Thanks for help @oleavr

**Comment by oleavr** [comment]
`Memory.readByteArray(this.context.r0, 16)` to read the first 16 bytes, assuming `r0` is a valid pointer. You can also do `console.log(hexdump(this.context.r0.add(0x42), { length: 32, ansi: true }))` to hexdump the first 32 bytes of memory at `r0` plus `0x42`.

**Comment by oleavr** [comment]
Check out the [Memory](https://frida.re/docs/javascript-api/#memory) docs for the full story.

**Comment by gaplan** [comment]
Thank you so much @oleavr
