### ISSUE TITLE
problems with macOS install frida - version 12.0.5

### ISSUE THREAD

**Issue by pharazone** [frida/frida#562]
hello.

I installed frida according to the "pip install frida".

and it succeed.

but when I type "frida" in my console,it showed "command not found".

the "exec" bin has been removed?
![image](https://user-images.githubusercontent.com/11215634/42986868-cc6dc682-8c29-11e8-905a-7e78c34fe8c6.png)

**Comment by minhtt159** [comment]
pip install frida-tools
