### ISSUE TITLE
Accessing outer class fields from inner class hook

### ISSUE THREAD

**Issue by muhzii** [frida/frida#565]
How do I access outer class variable when hooking a function, if for example I have a set-up like this:

```
class A{
    private int val;
    class B{
        public void fun(){
            // do stuff
        }
    }
}
```

Here's a hook code for example:

```
var B = Java.use("package.name.A$B");
B.fun.implementation = function () {
send(this.val);
};
```
However; this doesn't work, so is there any way in frida-java to get to the outer class object from the inner class object?

**Comment by muhzii** [comment]
OK, I resolved it and actually `this.this$0` is a reference to the outer class object which was used to create an object from the inner class.

**Comment by viva777** [comment]
> this.this$0
== undefined
Why doesn't it work for me?

**Comment by lyf-is-coding** [comment]
same, my this$0 is undefined

> > this.this$0
> 
> == undefined Why doesn't it work for me?
