### ISSUE TITLE
Modify NSTaggedString in JS API iOS

### ISSUE THREAD

**Issue by ddzobov** [frida/frida#568]
I have method that returns memory pointer:

> Value Class[- targetMethod] - 0xa000000000055522

I got object with this:
`var object = new ObjC.Object(pointer);
      
      console.log('Kind', object.$kind);
      console.log('ClassName', object.$className);
      console.log('Value', object.toString());`

Output:

> Kind instance
      ClassName NSTaggedPointerString
      Value RU

I want to modify this value to US. How can i do this?

I tried to create NSString and return it, but i think that is bad idea, because i need to return a pointer of type NSTaggedPointerString

`return ObjC.classes.NSString.stringWithString_("US");`

**Comment by mrmacete** [comment]
Well, to my understanding `NSTaggedPointerString` is a subclass of `NSString` which, for very short strings, encodes its characters directly in the underlying pointer instead of pointing to an actual array of chars.

Your solution to return a new instance of `NSString` looks good to me.

**Comment by ddzobov** [comment]
For me solution was:
```
var strObj = return ObjC.classes.NSString.stringWithString_("US");

return ptr(strObj);
```
