### ISSUE TITLE
building frida 4.2.8 on Windows

### ISSUE THREAD

**Issue by progopis** [frida/frida#58]
Hi oleavr!

I tried to build your tools for Windows 7 x64 and get the following errors:

```20>z:\dev\frida\frida\frida-clr\src\Script.hpp(5): fatal error C1083: Cannot open include file: 'frida-core.h': No such file or directory```
And some others:
```5>------ Build started: Project: frida-agent-64, Configuration: Release x64 ------
2>  resource-compiler.c
4>  agent-glue.c
3>  backtracer.cpp
5>  agent-glue.c
4>z:\dev\frida\frida\frida-core\lib\agent\frida-agent.h(9): fatal error C1083: Cannot open include file: 'frida-interfaces.h': No such file or directory
3>  interceptor.cpp
5>z:\dev\frida\frida\frida-core\lib\agent\frida-agent.h(9): fatal error C1083: Cannot open include file: 'frida-interfaces.h': No such file or directory```
```17>------ Build started: Project: frida-core, Configuration: Release x64 ------
17>  Serializing Agent resources
17>  Error opening file: No such file or directory
17>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1.```

Finally, I got 15 projects succeed and 8 failed.

**Comment by progopis** [comment]
I fixed one of the issues with adding include path $(SolutionDir)frida-core\lib\interfaces to the frida-agen-32/64 projects.

**Comment by Maktm** [comment]
I can't find the header file even in the repo ('frida-core.h').

**Comment by oleavr** [comment]
Hi,

(Sorry about the late follow-up here.) This is because you need Python 2.7 installed, as this is required by a build step that generates frida-core.h.

Cheers!

**Comment by Maktm** [comment]
I installed every version of Python and followed the guide exactly. I'll try again.

**Comment by progopis** [comment]
I removed all git repo and reupload it again from github with version 4.2.9. And building was completed successfully:
```========== Build: 8 succeeded, 0 failed, 15 up-to-date, 0 skipped ==========```

**Comment by oleavr** [comment]
Thanks for confirming! :+1:
