### ISSUE TITLE
Build scripts broken on linux-x86_64

### ISSUE THREAD

**Issue by ion86** [frida/frida#592]
My system runs debian stretch:

- The docs at https://www.frida.re/docs/building/ are still referring to `frida-ci`, which is deprecated according to https://github.com/frida/frida-ci/issues/1
- The makefile to build the toolchain is still trying to download a pre-built toolchain, which is 404 (it reports this as `is not a bzip2 file` since `-f` is not passed to curl, therefore the 404 is ignored). I worked around this by downloading an old build of the toolchain manually from `https://build.frida.re/toolchain-20180411-linux-x86_64.tar.bz2`
- The libdwarf build step (`build/fs-%/libdwarf/Makefile`) tries to execute `../../../libdwarf/libdwarf/configure` which doesn't exist, changed this to `../../../libdwarf/configure`
- There is no libdwarf.a target, you can run `make` in `libdwarf` witout a target, but you also need to change paths in the install(1) step since they are wrong for `libdwarf.a` and `libdwarf.h`, the first is located in (`build/fs-tmp-$*/libdwarf/libdwarf/.libs/libdwarf.a`, the other one is in `build/fs-tmp-$*/libdwarf/libdwarf/libdwarf.h`)
- glib doesn't build unless you install `libmount-dev`, `libselinux1-dev` and add `/usr/lib/x86_64-linux-gnu/pkgconfig` to `build/fs-linux-x86_64-pkg-config`

I would recommend to setup a travis build to automatically execute the build weekly to ensure it's working correctly.

**Comment by mvastola** [comment]
Just ran into this too. (Ubuntu Bionic)

**Comment by oleavr** [comment]
Frida does actually have a CI set up, though not yet exposed, and it's been flashing red for weeks now. This is intentional as I've been working on upgrading all of Frida's dependencies, including moving to building everything with Meson (where available). First two targets that came back to life were `macos-x86_64` and `ios-arm64`. Earlier this week I moved to Windows, where I've replaced how dependencies are built, using Meson there as well. Once that's done I will move back to Linux. I'm hoping to have all platforms back up in the next few days.

Feel free to hit me up on [our Telegram channel](https://t.me/fridadotre) if any of you want to pitch in smoothing out the rough edges on the other platforms before I eventually get to them.

**Comment by mvastola** [comment]
@ion86 btw, your instructions are super helpful.
The only thing I'd add (for anyone else running into this issue) is that the third issue (re: libdwarf) is also present in [Makefile.sdk.mk](https://github.com/frida/frida/blob/0224906a1965547006d5ec51989e89864b07d122/Makefile.sdk.mk#L223) for anyone needing to build the SDK.

@oleavr is there any way this could be reopened? It would be helpful to be updated when this is fixed.

**Comment by mvastola** [comment]
Also, with compiling glib, for some reason I was also getting the following:
```
In file included from ../../../glib/glib/garcbox.c:24:0:
../../../glib/glib/garcbox.c: In function ‘g_atomic_rc_box_acquire’:
../../../glib/glib/grefcount.h:101:13: error: implicit declaration of function ‘g_atomic_int_get’; did you mean ‘__atomic_store’? [-Werror=implicit-function-declaration]
     (void) (g_atomic_int_get (rc) == G_MAXINT ? 0 : g_atomic_int_inc ((rc))); \
```

I solved this by modifying `glib/glib/grefcount.h` to have `#include <glib/gatomic.h>` right after `#include <glib/gtypes.h>`.

**Comment by oleavr** [comment]
@mvastola Good idea! I'll keep you posted.

**Comment by oleavr** [comment]
Done with Windows. Spent the last couple of hours struggling with getting the toolchain built on Linux. Currently trying to figure out why Meson puts `-l` flags in the wrong order when building the Vala compiler.

**Comment by oleavr** [comment]
Linux x86 and x86_64 are now back. Aiming to finish the remaining platforms tomorrow: macOS, iOS and Android.
