### ISSUE TITLE
Unable to load SELinux policy from the kernel: Failed to open file “/sys/fs/selinux/policy”: Permission denied

### ISSUE THREAD

**Issue by hdjsjyl** [frida/frida#597]
when I execute"adb shell "/data/local/tmp/frida-server &"", it shows the following error: "Unable to load SELinux policy from the kernel: Failed to open file “/sys/fs/selinux/policy”: Permission denied";
And when I execute"adb root", it shows the following error"adbd cannot run as root in production builds"; Must my android phone have been rooted? thanks.

**Comment by mincadev** [comment]
I'm too

**Comment by JonLittleIT** [comment]
same issue here.

**Comment by mincadev** [comment]
I solved this problem with the following statement

adb shell "su - setenforce 0"

Perfect!

**Comment by rawcoolpad** [comment]
if i execute "adb shell "su - setenforce 0" 
it shows "sush: 0: No such file or directory"

**Comment by cuiqingandroid** [comment]
`adb root`  then run server.
good luck

**Comment by kiranAndr** [comment]
In my case, i've downloaded the frida server for Google Nexus 5X API 24 (Genymotion) and trying to executing the command `/data/local/tmp/mailSugg/frida-server &` on another device (Studio's emulator)

**Comment by hiepxuan2008** [comment]
I'm using Magisk to root my Pixel device. I met the same issue, and now I can fix it.
`
adb shell
su
/data/local/tmp/frida-server &
`

If you want to kill the current frida-server
`
ps -e | grep frida-server
kill -9 your_process_id
`

**Comment by zaidnz** [comment]
> if i execute "adb shell "su - setenforce 0"
> it shows "sush: 0: No such file or directory"

I think "c" is missing .. try:
$ adb shell "su -c setenforce 0"
then 
$ adb shell "su -c /data/local/tmp/frida-server-xx.xx.xx-android-xxx &"

**Comment by czyllqhome** [comment]
You may need to change to rooted Android deveice with no google play services. If use android studio, choose the device without google play logo in the device description (e.g. Pixel 3 XL with X86 Android 8.0 oreo API 26).  This fixed the root problem for me.
1. win+r  cmd
2. adb root (output : adbd restart as root)
3. adb shell
4. Now u will see generic_X86:/**#** intead of generic_X86:/**$**  (or use whoami command with output “root” instead of "shell")
5. Good luck!

**Comment by iamsharan** [comment]
Go to magisk Superuser section:
Here you can find something like "com.android.shell" grant the superuser rights.

now go back to the terminal and restart the ADB.

**Comment by sakthi-238** [comment]
> Go to magisk Superuser section: Here you can find something like "com.android.shell" grant the superuser rights.
> 
> now go back to the terminal and restart the ADB.

thanks friend worked

**Comment by qusyairin** [comment]
> You may need to change to rooted Android deveice with no google play services. If use android studio, choose the device without google play logo in the device description (e.g. Pixel 3 XL with X86 Android 8.0 oreo API 26). This fixed the root problem for me.
> 
> 1. win+r  cmd
> 2. adb root (output : adbd restart as root)
> 3. adb shell
> 4. Now u will see generic_X86:/**#** intead of generic_X86:/**$**  (or use whoami command with output “root” instead of "shell")
> 5. Good luck!

Worked!

**Comment by saifurrdev-io** [comment]
<
libsepol.avtab_read: table is empty
Unable to load SELinux policy from the kernel: unsupported policy database format


Karnelisu next not support
