### ISSUE TITLE
frida-server: not found

### ISSUE THREAD

**Issue by Laura055** [frida/frida#604]
When starting the frida server it returns this

```
root@SM-G925F:/data/local/tmp # su
root@SM-G925F:/data/local/tmp # frida-server &
[1] 4232
sh: frida-server: not found
```
it says "not found" and im also not able to connect to the frida server. I tried both, x86 and x64 version.

My details:
Emulator: MEmu Emulator with Android 5.1
OS: Windows 10 Home
Frida version: 12.0.8

The emulator device is rooted.

Thank you for help in advance!

Regards, Mert

**Comment by Laura055** [comment]
I fixed it myself, thanks :)

**Comment by Abderaoufbhc** [comment]
How you fix it ?

**Comment by tom4ke** [comment]
> I fixed it myself, thanks :)

how?
