### ISSUE TITLE
build frida Error

### ISSUE THREAD

**Issue by joydo** [frida/frida#605]
I want to build android-server by myself,but when i run the command "make server-android",there is always the following error:

`FRIDA_HOST=macos-x86_64 \

 FRIDA_OPTIMIZATION_FLAGS="-Os" \

FRIDA_DEBUG_FLAGS="-g3" \

FRIDA_ASAN=no \

./releng/setup-env.sh

Downloading and deploying toolchain...

tar: Unrecognized archive format

tar: Error exit delayed from previous errors.

make[1]: *** [build/frida-env-macos-x86_64.rc] Error 1

make: *** [server-android] Error 2`

What's Wrong ?

**Comment by oleavr** [comment]
The build system has been undergoing maintenance as part of upgrading all of Frida's dependencies. This is now finally done, so please grab a fresh git clone and build away. :-)
