### ISSUE TITLE
Frida crashes (segmentation fault) every process on ubuntu 14.04 and 12.10 64bit

### ISSUE THREAD

**Issue by 0-duke** [frida/frida#61]
First of all: Thanks guys for your time and work, this project is amazing!

I've tried frida on a fresh new installed debian 32bit (virtual machine) and all worked smootlhy, super cool.
I've also tried to use frida on two other machines, with Ubuntu 12.10 LTS and Ubuntu 14.04 LTS, both fresh installed and 64bit but frida crashes every process while attaching to it. 
I did the same process as with debian (easy_install and enabled ptracing non-child processes).

I have create a core dump of the crashed application (/bin/cat) so if you need information just ask.

**Comment by oleavr** [comment]
Thanks for your kind words!  Very interesting. I've heard about similar issues from others, so I think it's time to have a look at this soon. I'll keep you posted.

**Comment by sha0coder** [comment]
I Have tried frida on ubuntu 64bits and also segfaulted, hope this helps:

[ 7806.247173] telnet[15805]: segfault at 388 ip 00007faeb96c1912 sp 00007faeb8082bd0 error 4 in ld-2.19.so[7faeb96b7000+23000]
[ 9146.240484] ptrace of pid 28007 was attempted by: frida-helper-64 (pid 28014)
[ 9154.844689] nc[28057]: segfault at 388 ip 00007f44eb706912 sp 00007f44ea6d8c10 error 4 in ld-2.19.so[7f44eb6fc000+23000]

**Comment by oleavr** [comment]
This should be fixed in the newly released 4.5.1 release.
