### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by mvastola** [frida/frida#615]
So I know a bit of work was done on Frida's build system lately, but it was supposedly fixed for Linux and I'm still running into issues on the latest master.

I'm happy to assist in troubleshooting if need be, although I must admit I need some guidance here -- I'm not sure how to trace down this error any further, specifically because I seemed to be getting less-than helpful traces due to async function calls.

Any help is greatly appreciated.

https://gist.github.com/f1c2baf5a238d95e26dd54a33eed005d

**Comment by oleavr** [comment]
Which version of Node.js do you have on your `PATH`?

**Comment by mvastola** [comment]
```
mvastola@vastdesk:~$ node -v
v10.9.0
```

**Comment by mvastola** [comment]
Ok. This was absolutely insane to figure out, but I finally managed. The issue was that I had the npm config option `globalstyle` set to `true` in my `npmrc`. This resulted in dependencies of the dependencies of `frida-gumjs` not being directly in `frida-gum/bindings/gumjs/node_modules`.

After doing `rm -Rf node_modules package-lock.json` and `npm i` everything worked. 

I really wish `babelify` had at least given a warning about this, but it's not a `frida` issue.
