### ISSUE TITLE
frida crash when hook on windows

### ISSUE THREAD

**Issue by d3862658** [frida/frida#629]
fixed

**Comment by riverar** [comment]
Win32 `ULONG` is actually an unsigned 32-bit integer regardless of platform. So RtlFreeHeap should be represented with `new NativeFunction(RtlFreeHeapAddr, 'uint', ['pointer', 'uint', 'pointer'])`. If you're on Windows 7 or older, however, the return type is Win32 `BOOLEAN` (uint8).

It's not clear what architecture you're targeting, but if this is targeting a 32-bit process, your calling convention is implicitly set wrong. (The default calling convention is __cdecl.) Add `_stdcall` to your definition and that should fix things up. (e.g. `new NativeFunction(RtlFreeHeapAddr, 'uint', ['pointer', 'uint', 'pointer'], 'stdcall')`)

Let us know if that works out for you!
