### ISSUE TITLE
Cannot install with Python 3.7, but Python 2.7 is ok

### ISSUE THREAD

**Issue by AlexGeeksoft** [frida/frida#643]
sudo pip install frida-tools --proxy 127.0.0.1:1087
The directory '/Users/alex/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/alex/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting frida-tools
  Downloading https://files.pythonhosted.org/packages/32/34/f6ce58434dd01996f55aae1b74a9d2ff8dc8ed93e655916e19707cd627c1/frida-tools-1.2.1.tar.gz
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from frida-tools) (0.3.9)
Collecting frida<13.0.0,>=12.1.0 (from frida-tools)
  Downloading https://files.pythonhosted.org/packages/48/62/1137bf0d1e42b72c72758190c36c04099d2ddee63e76898291b579de2ade/frida-12.2.5.tar.gz
Collecting prompt-toolkit<2.0.0,>=0.57 (from frida-tools)
  Downloading https://files.pythonhosted.org/packages/04/d1/c6616dd03701e7e2073f06d5c3b41b012256e42b72561f16a7bd86dd7b43/prompt_toolkit-1.0.15-py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 563kB/s
Collecting pygments<3.0.0,>=2.0.2 (from frida-tools)
  Downloading https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 27.6MB/s
Collecting wcwidth (from prompt-toolkit<2.0.0,>=0.57->frida-tools)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting six>=1.9.0 (from prompt-toolkit<2.0.0,>=0.57->frida-tools)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: frida, wcwidth, six, prompt-toolkit, pygments, frida-tools
  Running setup.py install for frida ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-8iuuz62d/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-8v02imom/install-record.txt --single-version-externally-managed --compile:
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/alex/frida-12.2.5-py3.7-macosx-10.6-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-8iuuz62d/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-8v02imom/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-8iuuz62d/frida/

**Comment by marcelocecin** [comment]
same error here
`running install`
`running build`
`running build_py`
`creating build`
`creating build/lib.macosx-10.6-intel-3.6`
`creating build/lib.macosx-10.6-intel-3.6/frida`
`copying frida/__init__.py -> build/lib.macosx-10.6-intel-3.6/frida`
`copying frida/core.py -> build/lib.macosx-10.6-intel-3.6/frida`
`running build_ext`
`querying pypi for available prebuilds`
`network query failed`
`looking for prebuilt extension in home directory, i.e. /Users/cecin/frida-12.2.6-py3.6-macosx-10.6-intel.egg`
`no prebuilt extension found in home directory`
`error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>`

**Comment by s2339956** [comment]
➜  ~ sudo -H pip install frida
Collecting frida
  Downloading https://files.pythonhosted.org/packages/4e/a3/ccfaa42bf09a8d59a1e1d835c09c80149c58350f4ade2e23f0c5a45635a7/frida-12.2.8.tar.gz
Installing collected packages: frida
  Running setup.py install for frida ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-hez2ivfk/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-6u5f415c/install-record.txt --single-version-externally-managed --compile:
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /var/root/frida-12.2.8-py3.7-macosx-10.6-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-hez2ivfk/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-6u5f415c/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-hez2ivfk/frida/

Such an error, how can I solve it?

**Comment by manjunathscp** [comment]
Same error with Python 3.7 in MACOS MOJAVE

Collecting frida-tools
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from frida-tools) (0.4.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=0.57 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from frida-tools) (1.0.15)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from frida-tools) (2.3.0)
Collecting frida<13.0.0,>=12.1.0 (from frida-tools)
  Using cached https://files.pythonhosted.org/packages/9b/19/c5f9206e87a214fbcb8d0934256d9b769a6c925711f502a5cee172236e0a/frida-12.2.26.tar.gz
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from prompt-toolkit<2.0.0,>=0.57->frida-tools) (0.1.7)
Requirement already satisfied: six>=1.9.0 in ./Library/Python/3.7/lib/python/site-packages (from prompt-toolkit<2.0.0,>=0.57->frida-tools) (1.11.0)
Building wheels for collected packages: frida
  Running setup.py bdist_wheel for frida ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/m2/nn2d03jx7cv8t3byfy6ytckr0000gn/T/pip-install-irni6ph2/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/m2/nn2d03jx7cv8t3byfy6ytckr0000gn/T/pip-wheel-v7c33bu0 --python-tag cp37:
  /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/frida
  copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/frida
  copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.7/frida
  running build_ext
  querying pypi for available prebuilds
  network query failed
  looking for prebuilt extension in home directory, i.e. /Users/manjunathscp/frida-12.2.26-py3.7-macosx-10.6-intel.egg
  no prebuilt extension found in home directory
  error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
  
  ----------------------------------------
  Failed building wheel for frida
  Running setup.py clean for frida
Failed to build frida

**Comment by oleavr** [comment]
This is a Python installation issue. Please read:
https://stackoverflow.com/a/42107877
