### ISSUE TITLE
[Android native] Replace a new path when hook function open file  in libc.so 

### ISSUE THREAD

**Issue by henrytom1703** [frida/frida#658]
Hello guys.
I want replace path  "/data/local/tmp/a" to  "/data/local/tmp/path_data_large_size" when hook an open function. But I tried execute a source code below then app crashed.
Cause error maybe come from these  two  line code:
```
        Memory.protect(pathPtr, 4,'rwx');
        Memory.writeUtf8String(pathPtr, "/data/local/tmp/path_data_large_size");
```
source code hook:
```
var openPtr = Module.findExportByName("libc.so", "open");
var open = new NativeFunction(openPtr, 'int', ['pointer', 'int']);
Interceptor.replace(openPtr, new NativeCallback(function (pathPtr, flags) {
    var path = Memory.readUtf8String(pathPtr);
    if (path == "/data/local/tmp/a") {
        Memory.protect(pathPtr, 4,'rwx');
        Memory.writeUtf8String(pathPtr, "/data/local/tmp/path_data_large_size");
    }
    return open(pathPtr, flags);
}, 'int', ['pointer', 'int']));
```
Could you help me fix it?
Thanks,

**Comment by henrytom1703** [comment]
@mohe2015 
How to replace the new path longer than the old path?
Thanks

**Comment by mohe2015** [comment]
@henrytom1703 First check if that's the issue by replacing the path with one with the same length. If that's really the issue I think you could use Memory.allocAnsiString(str). Check out the documentation at https://www.frida.re/docs/javascript-api/

**Comment by henrytom1703** [comment]
@mohe2015 
Could you help me the this new issue?
https://github.com/frida/frida/issues/660
