### ISSUE TITLE
spawn()  with android apps?

### ISSUE THREAD

**Issue by dreamx2** [frida/frida#66]
Are spawn() and resume() supported in the Android implementation? If so, what is the correct usage?

I have tried:
device.spawn(["com.skype.raider"]) which gives:  frida.ExecutableNotFoundError
and
device.spawn(["/data/app/com.skype.raider-1.apk"]) which gives: frida.ExecutableNotSupportedError

Thanks.

**Comment by oleavr** [comment]
The `spawn()` functionality in the latest released version of Frida is limited to spawning executables. Support for spawning apps is currently being implemented (I'm working on it), and once it lands it'll be like what you tried: `device.spawn(["com.skype.raider"])`.

**Comment by dreamx2** [comment]
Thanks man.

**Comment by dreamx2** [comment]
This works now. Thanks.
