### ISSUE TITLE
Frida shell waiting forever when executing "altering" functions

### ISSUE THREAD

**Issue by mfpp** [frida/frida#664]
Hi guys,

I have a problem with Frida 12.2.9 on iOS 11.1.x and 11.2.x with Electra jailbreak, hope someone can help me.

Every single time I try to alter a textfield's value, for example, Frida is able to change the value but the function called does not return... this way, my Frida shell remains waiting forever...

Expected behavior (works on iOS 9.x with Pangu jailbreak):
```
-> textFields[1].setText_("1234")
undefined
```

Behavior on iOS 11.1.x and 11.2.x with Electra jailbreak:
```
-> textFields[1].setText_("1234")
[NEVER RETURNS...]
```

Does anyone have any clue about it? Is it a bug?

**Comment by oleavr** [comment]
No, you are making UIKit calls from a background thread, which is not allowed. Use `ObjC.schedule(ObjC.mainQueue, function () { /* Call it here. */ })` to do it from the correct thread.
