### ISSUE TITLE
Correct way to use Interceptor

### ISSUE THREAD

**Issue by localacct** [frida/frida#681]
Hi,

I am using Interceptor to hook native C functions and running Frida in interactive command line mode.

````
frida -U -l script.js -f com.xyz.application --no-pause
````

My script was able to locate the memory addresses of the functions using Module.findExportByName and I used Interceptor to attach to those addresses. However, the Interceptor code never gets triggered even though there was no error.

I have tried enclosing the Javascript code inside setImmediate, setTimeout etc but still the Interceptor code does not get triggered.

What are the proper ways to use Interceptor? Is there a specific timing in terms of the process execution, library loading etc that I should take note of?

My code snippet as follows

````
setImmediate(function(){
    Java.perform(function(){
        var addr2=Module.findExportByName("libxyz.so","certain_function");
        console.log(addr2); //the code displays a valid address
        Interceptor.attach(addr2, {
                onEnter: function(args){
                    console.log("inside native function");
                },
                onLeave: function(retvalue){
                    console.log("leaving native function");
                }
        });
});
````

**Comment by stevepoland85** [comment]
Try adding 1 to addr2

**Comment by localacct** [comment]
Hi steve

Do you mean

````
addr2 +=1?
````

What is the purpose of this?

**Comment by stevepoland85** [comment]
Yes I mean that. But addr2.add(1) seems to be the Frida idiom. I'm guessing you're on ARM and trying to hook a thumb address.

**Comment by oleavr** [comment]
If you're dealing with an address where you're not sure if the Thumb bit is already set, use `.or(1)`. Never perform arithmetic on `NativePointer` values in Frida – such code is not portable to 64-bit processes, where JavaScript Number values are not able to represent all possible pointer values.
