### ISSUE TITLE
Wrong NDK folder name

### ISSUE THREAD

**Issue by neoz** [frida/frida#682]
Seem the NDK version folder name is hardcode and not correct with the supported version.

> make[1]: Entering directory '/mnt/d/Working/Android/frida'
> FRIDA_HOST=android-x86 \
>         FRIDA_OPTIMIZATION_FLAGS="-Os" \
>         FRIDA_DEBUG_FLAGS="-g3" \
>         FRIDA_ASAN=no \
>         ./releng/setup-env.sh
> cut: /mnt/d/Working/Android/frida/**android-ndk-r15c**/RELEASE.TXT: No such file or directory
> 
> Unsupported NDK version . Please install **NDK r17b** (17.1.4828580).
>

**Comment by stevepoland85** [comment]
Your ANDROID_NDK_ROOT env variable isn't set to a supported NDK. Download 17b (17c worked for me too) and set ANDROID_NDK_ROOT to point to it.

Not a bug with frida.
