### ISSUE TITLE
Method hooking problems on Android 7 and above.

### ISSUE THREAD

**Issue by xiphiasilver** [frida/frida#688]
Hi @oleavr .

In case when specific method - java.io.BufferedReader.readline() - is hooked on Android 7 and above, following errors are came across :

```
Error: can't decode byte 0xc0 in position 17
    at frida/node_modules/frida-java/lib/env.js:923
    at frida/node_modules/frida-java/lib/class-factory.js:2505
    at input:1
    at [anon] (/script1.js:169)
    at input:1
```

This is the Frida script I'm using :

```
var Buffer = Java.use("java.io.BufferedReader");
Buffer.readLine.overload().implementation = function(){
     var tmpResult = this.readLine();
          if (tmpResult != null){    
               send("        [!] read is requested : " + tmpResult.toString());
          }
     return tmpResult;
}
```

Another method to return unicode string work properly. 
I'm using on the latest Frida 12.2.18 and I tested on some other versions, but the results were the same...

On Android 6.0.1 with same code, I could output the string without any problems...

Do you have any idea how to fix this?

Thank you for your help in advance.

**Comment by nadavshtern** [comment]
Could it be that the string we are trying to print has Unicode chars in it ?

**Comment by xiphiasilver** [comment]
@hi, @nadavshtern.

Thanks for your consideration.

After google play and related library has been updated, it works well currently on Android 7...

The target application's code related google play seems not to implement properly.

**Comment by pich4ya** [comment]
up
