### ISSUE TITLE
Connect to frida-server from another machine over TCP

### ISSUE THREAD

**Issue by 0xABD** [frida/frida#70]
Kindly clarify how to connect frida clients to a `frida-server` on another machine over TCP. 

After a quick look at the sources it seems to be possible, both server and `tcp-host-session` have a default connection string of "tcp:host=127.0.0.1,port=27042", but an arbitrary one can be supplied.

How I see the steps now:
1. Make the frida-server listen on arbitrary address and port (undocumented, derived from source, tested, works):
`./frida-server tcp:host=ADDRESS,port=PORT`
2. Make the frida client connect to the arbitrary address and port 
??? Tried a couple of parameters without any luck.

Also, forwarding the remote port 27042 on the target (frida-server) machine to port 27042 on the client machine does not seem to help.

**Comment by oleavr** [comment]
There isn't yet an API to specify the host/port to connect to, only `frida-server` supports specifying it. I implemented support for the first part of this in the backends, but didn't expose this to the API yet. Basically this is a matter of wiring up in src/frida.vala, which serves as the facade API to shield users from the lower level HostSessionService API (which due to the nature of DBus, which we use p2p over a platform-specific transport, is somewhat clunky to use). If you see a nice way to represent it let me know, I put it on the backburner temporarily while thinking about the best way to expose it. Perhaps `DeviceManager.add_remote_device(ip, port)` which returns a `Device` and this device magically appears in the list of devices?

The official way to accomplish this currently is to set up a local SSH tunnel to from localhost:27042 locally to localhost:27042 remotely, and use the `-R` switch with the CLI tools, and `frida.get_remote_device()` from Python, and `frida.getRemoteDevice()` from Node.js.

**Comment by 0xABD** [comment]
Thank you!
Tried with port forwarding a couple of times, it actually works, so there is a workaround (regardless of the type of device -- x86/Android).

I believe something like "add_remote_device" will surely work, as it is easily accessible from scripts and can also be called from existing frida-* cmdline tools if a new parameter with a remote server connection string is specified.

**Comment by oleavr** [comment]
Cool! I'll look into adding that soon.

**Comment by oleavr** [comment]
Well, not quite “soon”, but this is now finally implemented. :-)

```sh
# listen on 127.0.0.1:27042 (the default)
$ frida-server

# listen on all interfaces
$ frida-server -l 0.0.0.0

# listen on a specific interface
$ frida-server -l 192.168.1.3

# listen on a specific interface and port
$ frida-server -l 192.168.1.3:1337

# connect to specific IP
$ frida-trace -H 192.168.1.3 -i "open*"

# connect to specific IP/port
$ frida-trace -H 192.168.1.3:1337 -i "open*"
```

Available in Frida 6.2.6.

**Comment by GHXST01** [comment]
@0xABD Can you tell me how you setup the local connection? I have troubles connecting to frida when using a SOCKS5 proxy in ProxyDroid and I have a feeling this might help my situation.

**Comment by zjcnew** [comment]
@oleavr  Can the client configure the connection specified ip in the python code?

**Comment by 3xp10it** [comment]
@oleavr Can the client configure the connection specified ip in the python code? like "frida.get_remote_device()" or other methods?

**Comment by leonjza** [comment]
You can set the target IP/port in python yes. 

```python
frida.get_device_manager().add_remote_device('host:port')
```

An example implementation is [here](https://github.com/sensepost/objection/blob/master/objection/utils/agent.py#L122).

**Comment by gMan1990** [comment]
@leonjza if the connect is lost, how to reconnect. retry `add_remote_device`?

**Comment by Dd-ouni** [comment]
> 好吧，不是“很快”，但现在终于实现了。:-)
> 
> ```shell
> #监听 127.0.0.1:27042（默认）
> $ frida 服务器
> 
> #监听所有接口
> $ frida-server -l 0.0.0.0
> 
> #监听特定接口
> $ frida-server -l 192.168.1.3
> 
> #监听特定的接口和端口
> $ frida-server -l 192.168.1.3:1337
> 
> #连接特定IP 
> $ frida-trace -H 192.168.1.3 -i " open* "
> 
> #连接到特定的 IP/端口
> $ frida-trace -H 192.168.1.3:1337 -i " open* "
> ```
> 
> 在 Frida 6.2.6 中可用。

@oleavr  Where can I find this information, thank you

**Comment by oleavr** [comment]
@gMan1990 Just try another API call, and it will attempt to reconnect. No need to re-add the device.

**Comment by oleavr** [comment]
@Dd-ouni Which information? Perhaps it's from https://frida.re/docs/frida-trace/

**Comment by specters312** [comment]
Not sure if I can ask here but just need an example on the client side when querying the device 

I tried 
`frida-ps -H 192.168.1.9`
Which works fine but when trying 
`frida-ps -Uai -H 192.168.1.9` or similar it wont allow it

If anyone has an example usage of this on the from client to server let me know :D

**Comment by bilabar** [comment]
@specters312 option `-U` is to connect to USB device. Using `-U` with `-H` may confuse `frida-ps`. You may want to use option `-Hai`

**Comment by specters312** [comment]
> @specters312 option `-U` is to connect to USB device. Using `-U` with `-H` may confuse `frida-ps`. You may want to use option `-ai -H 192.168.1.9`

You are awesome thank you

**Comment by mriamnobody** [comment]
I tried all the above-mentioned steps but still got the error "Failed to spawn: unable to connect to remote frida-server". Please guide. I'm on Frida 16.0.8 and on-device I have crDroid ROM (Android 10)

**Comment by mriamnobody** [comment]
#2360 I have also filed for an issue.
