### ISSUE TITLE
Java detection (Java.available) not working on Windows?

### ISSUE THREAD

**Issue by CodyMcCodeface** [frida/frida#704]
While trying to figure out how to hook SSL connections (that is, access unencrypted data for SSL connections) in Java applications on Windows (no one in the entire Google search index ever seems to have even contemplated this, wtf?!), I noticed that the Java detection (i.e. the "Java.available" boolean) does not detect that my example application is running Java (Java.available == False).

The target is a "packaged" Java application, that is, it is started as an ".exe" file in Windows, but frida-trace still readily detects jvm.dll being loaded in it and can hook the functions of jvm.dll.

Is this expected, and in that case, why? Would it work if the same Java application was executed as an explicit jar file through java.exe, or doesn't the Java detection of "Java.available" work on Windows at all?

The example application is Burp (freeware version available here: https://portswigger.net/burp/communitydownload), in case someone would like to reproduce.

PS.
If anyone has ANY clues whatsoever on how to hook SSL connection data in Java programs running on Windows, that would be SUPER appreciated too.

**Comment by oleavr** [comment]
Only the Dalvik and ART runtimes are currently supported. Support for other VMs is planned, but for now hasn't been a priority. PRs welcome!

**Comment by pinkLagoon** [comment]
@oleavr Is this still the case?

> Only the Dalvik and ART runtimes are currently supported. Support for other VMs is planned, but for now hasn't been a priority. PRs welcome!

Is this still the case? Until this becomes a feature, it would not be possible to instrument desktop based Java applications, correct?

**Comment by oleavr** [comment]
@pinkLagoon We also support HotSpot these days, but for now we depend on JVM symbols being available, i.e. that our `DebugSymbol` APIs are able to resolve symbols inside the JVM.
