### ISSUE TITLE
[android] Memory.readByteArray(addr, length) fails, but Memory.readCString(addr, length) works

### ISSUE THREAD

**Issue by 0xABD** [frida/frida#71]
On Android 4.4.4 (stock image KTU84P for Nexus 5), with dalvik runtime, when using `frida-trace` on any Java-only application (e.g. stock Gmail client), while tracing native calls from system libraries (e.g. libssl.so, ssl3_read and ssl3_write), `Memory.readByteArray(addr, length)` silently fails (returns null, the rest of the handler after readByteArray call is not executed), but, surprizingly, `Memory.readCString(addr, length)` works, when called with the same parameters. 

By the way, looks like readCString can read arbitrary number of null-bytes if the size parameter is specified, which is a nice feature, so it can be used instead of readByteArray indeed.

The only difference in their implementation that I can infer from the sources is that the `readCString` is the only one exposed as `GUM_EXPORT_MEMORY_READ`, the others `Memory.read***String` functions are all `GUM_DEFINE_MEMORY_READ_WRITE`. However, this should make no difference as in my case as `readUtf8String` also works fine, while `readByteArray` does not.

**Comment by oleavr** [comment]
Hmm, that's odd. Could you paste the code you're trying with? Is this with Frida 5.0.5 (from last night)?

**Comment by 0xABD** [comment]
That was from frida 5.0.2, code is
```
// frida-trace called as:
// # frida-trace -R -f com.google.android.gm -i ssl3_read -i ssl3_write

// handler for ssl3_read is:
{
    onEnter(log, args, state) {
        this.buf = args[1];
        this.len = parseInt(args[2]);
    },

    onLeave(log, retval, state) {
        log("ssl3_read(" + this.buf.toString() + ", " + this.len.toString() + ") = " + retval.toString() + "");
	retcnt = parseInt(retval);
        if (retcnt != 0xFFFFFFFF) {
		var bbuf = Memory.readByteArray(this.buf, retcnt);
	        log("Read bytes: " + bbuf.length.toString());
	}
    }
}

// handler for ssl3_write is:
{
    onEnter(log, args, state) {
        this.buf = args[1];
        this.len = parseInt(args[2]);
        log("ssl3_write(" + this.buf.toString() + ", " + this.len.toString() + ")");
        var bbuf = Memory.readByteArray(this.buf, this.len);
        log("Written bytes: " + bbuf.length.toString());
    },                     

    onLeave(log, retval, state) {
    }
}
```

**Comment by 0xABD** [comment]
With the provided script I do not see "Read bytes" or "Written bytes" messages at all.

**Comment by oleavr** [comment]
Instead of:
`this.len = parseInt(args[2]);`
I would recommend:
`this.len = args[2].toInt32();`

But here's one problem; Memory.readByteArray() returns an `ArrayBuffer` in Frida >= 5.x (it used to return an array-like object in Frida <= 4.x). That means you need to use the `byteLength` property, like so:
`log("Written bytes: " + bbuf.byteLength);`

**Comment by 0xABD** [comment]
Thank you so much, that works! 

(My bad, missed the ArrayBuffer in the new version of the docs.)

**Comment by oleavr** [comment]
Sweet! :+1:

**Comment by abarbaro** [comment]
Hi all,
I have exactly the same problem while I intercept send on Windows... Any idea? My code is:

onEnter: function onEnter(log, args, state) {
        log("send()");
		
		this.buf = args[1];
        this.len = args[2].toInt32();
		
		log(this.buf);
		log(this.len);
		var bbuf = Memory.readByteArray(this.buf, this.len);
        log("Read bytes: " + bbuf.length.toString());
		
    },

bbuf is empty...

**Comment by oleavr** [comment]
@abarbaro Did you try `log(hexdump(Memory.readByteArray(this.buf, this.len)));`?

**Comment by oleavr** [comment]
@abarbaro Btw, ArrayBuffer does not have a `length` property, only `byteLength`. Anyway, if you want to access individual bytes on it you should use an `Uint8Array` view, or pass it as the second argument to `send()` in order to process it on the host-side (depending on what you're doing).

**Comment by abarbaro** [comment]
@oleavr : Yes using your instruction it works. For sure my last line was incorrect but i still have a question: why if i use:

this.buf = args[1];
this.len = args[2].toInt32();
		
log(this.buf);
log(this.len);
buf = Memory.readByteArray(this.buf, this.len);
log(buf);

I can only see "()" in the output rather then the actual bytes?

Thanks

**Comment by abarbaro** [comment]
@oleavr OK I read your email on the ML. All clear now.

Thanks
