### ISSUE TITLE
Frida-trace/get_device multiple iphones

### ISSUE THREAD

**Issue by stevepoland85** [frida/frida#718]
I'm trying to keep multiple iphones, and Android devices plugged into my computer and do analysis on them. Specifying the device in `frida-trace`/`get_device` is nice for multiple Android devices, and the ID is whatever `adb` returns. But what is the equivalent for iPhone? Is there anything?

What is an 'ID' for an iPhone?

frida-trace help:
```
  -D ID, --device=ID    connect to device with the given ID
```

**Comment by oleavr** [comment]
Use `frida-ls-devices` to list available device IDs.

**Comment by stevepoland85** [comment]
Awesome! Thank you.
