### ISSUE TITLE
Building QNX Port

### ISSUE THREAD

**Issue by distributed** [frida/frida#72]
I would like to use Frida to instrument processes running on x86 QNX. I use Windows as a Development and I have access to a QNX toolchain.

Can you kindly instruct me how to build Frida for QNX?

**Comment by oleavr** [comment]
Hi,

The current QNX build system hasn't been ported to Windows. Would you be interested in helping out porting it?

Cheers!

**Comment by distributed** [comment]
Does this mean that you compile Frida for QNX on QNX?

Unfortunately I wouldn't even know where to start and I don't have the free time to do it :(

**Comment by oleavr** [comment]
No we cross-compile it from Linux (OS X might work too, didn't check). If you're low on time I would suggest setting up a VM with Ubuntu 15.04, and use that for building.

/cc @s1341

**Comment by distributed** [comment]
Thanks for the clarification. I will try the build on Ubuntu. That should for me :)

**Comment by s1341** [comment]
Note that the qnx port is arm only

**Comment by distributed** [comment]
Oh, I didn't realize that. Of course I'm one of the few x86 QNX still out there ;)

**Comment by oleavr** [comment]
Good point @s1341; to run it on x86 you will have to add some x86 code generation here:
https://github.com/frida/frida-core/blob/f27e79681fc2a80f77596818bae7fb90dfe73d76/src/qnx/qinjector-glue.c#L241
The easiest is probably having a look at the Linux backend and doing a mental three-way diff to port it. :-)

**Comment by oleavr** [comment]
By that I mean compare how the QNX/ARM code differs from Linux/ARM (it was based on it), then copy-paste Linux/X86 code and apply the corresponding changes to it.
