### ISSUE TITLE
Failed to attach: remote_call PTRACE_POKEDATA failed: 5 

### ISSUE THREAD

**Issue by 7763sea** [frida/frida#727]
Failed to attach: remote_call PTRACE_POKEDATA failed: 5

Deives：huawei XDD 259 

OS:EMUI 8.0.0
android os 8.0.0
kernel：4.4.23

CPU:hisilicon kirin 659

**Comment by 7763sea** [comment]
Thanks，I found error，because 华为XDD 259  is Android 8.0 os ，need Magisk module to open ro.debuggable to 1。
commond：

magisk resetprop ro.debuggable 1

**Comment by qssq** [comment]
are you solution problem?

**Comment by qssq** [comment]
.There's still a problem. @7763sea

**Comment by SergeyAppDroid** [comment]
@7763sea , Same problem. Can I somehow solve this problem without lowering the version of the android?
