### ISSUE TITLE
NSError problem.

### ISSUE THREAD

**Issue by xiaomiwang** [frida/frida#729]
Hi, guy.
I have a iOS argument problem. For example, I have a method like
 "+ (bool)_iMessage_canSendComposition:(id)arg1 error:(id*)arg2;". And the second argument looks like NSError. 
In Objective-C, we define it and use it like this,
"
  NSError *error = nil;
  [class iMessage_canSendComposition:arg1 error: &error];
"
So how can I define it and pass it when I use this method via JavaScript?

**Comment by xiaomiwang** [comment]
Thanks~

**Comment by BigCatGit** [comment]
thanks
