### ISSUE TITLE
Cannot build frida because valac segfaults

### ISSUE THREAD

**Issue by raymontag** [frida/frida#733]
Buiilding from scratch is not possible for me because valac cannot execute:

    $ make -f Makefile.sdk.mk
    ...
    meson.build:1:0: ERROR:  Unknown compiler(s): [['/home/grayfox/reversing/frida/build/fs-linux-x86_64-valac']]

    A full log can be found at /home/grayfox/reversing/frida/build/fs-tmp-linux-x86_64/libgee/meson-logs/meson-log.txt
    make: *** [Makefile.sdk.mk:287: build/fs-tmp-linux-x86_64/libgee/build.ninja] Error 1
    [grayfox@shadow-moses ~/reversing/frida frida-linux-x86_64]
    $ /home/grayfox/reversing/frida/build/fs-linux-x86_64-valac
    Segmentation fault (core dumped)

Seems to be a duplicate of #706  (which is closed without comment)

OS: Ubuntu 18.10

**Comment by omarroth** [comment]
Creating symbolic links to the system `valac` works for me.

```
$ which valac
/usr/bin/valac
$ ll *-valac
lrwxrwxrwx 1 omar omar 14 Dec 12 13:57 frida-linux-mipsel-valac -> /usr/bin/valac
lrwxrwxrwx 1 omar omar 14 Dec 12 13:57 frida-linux-mips-valac -> /usr/bin/valac
lrwxrwxrwx 1 omar omar 14 Dec 12 13:53 frida-linux-x86_64-valac -> /usr/bin/valac
lrwxrwxrwx 1 omar omar 14 Dec 12 13:53 frida-linux-x86-valac -> /usr/bin/valac
```

Although obviously not ideal.

**Comment by oleavr** [comment]
@raymontag Would be great if you could figure out why the prebuilt vala compiler segfaults on your system.

@omarroth Using the upstream Vala compiler will result in a broken or buggy build of Frida. Make sure you use our tweaked version available [here](https://github.com/frida/vala). The main issue is that our patched GLib, improved to support static linking and dynamic unloading, requires calling `glib_init()`, and our Vala compiler inserts that call.

**Comment by omarroth** [comment]
Gotcha, thanks @oleavr. The prebuilt Vala segfaults on my system as well, will investigate.

**Comment by raymontag** [comment]
@oleavr I'll try.

**Comment by raymontag** [comment]
@oleavr It has something to do with setlocale.c which belongs to locale from glibc:

    $ gdb -q valac-0.42-impl 
    
    warning: ~/Projects/tools/peda/peda.py: No such file or directory
    Reading symbols from valac-0.42-impl...(no debugging symbols found)...done.
    (gdb) run hello.vala
    Starting program: /home/grayfox/reversing/frida/build/frida_thin-toolchain-linux-x86_64/bin/valac-0.42-impl hello.vala
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff7dbb5ba in __GI_setlocale (category=<optimized out>, locale=<optimized out>) at setlocale.c:392
    392	setlocale.c: No such file or directory.

Interesting enough, it builds in Ubuntu 18.04. So maybe it doesn't work with the current glibc from 18.10.

**Comment by oleavr** [comment]
@raymontag Interesting, thanks. Could you grab the backtrace of that? (Using the `bt` command.)

**Comment by raymontag** [comment]
@oleavr Of course:

    (gdb) bt
    #0  0x00007ffff7dbb5ba in __GI_setlocale (category=<optimized out>, locale=<optimized out>) at setlocale.c:392
    #1  0x000000000044a8b5 in main ()

**Comment by thejunkjon** [comment]
I can also confirm that when I built with glibc-2.27 it worked fine.  I recently upgraded to glibc-2.28 and I am encountering this segfault issue.

**Comment by oleavr** [comment]
Thanks guys. The Docker image we use for building runs glibc-2.11.3 so that the generated binaries run on reasonably old glibc versions. I reckon the most probable explanation here is a bug in Frida's GLib that resulted in undefined behavior, and that behavior just happened to change in 2.28. If any of you get a chance to dig deeper, that would be awesome.

**Comment by thejunkjon** [comment]
@raymontag, one thing I noticed was that if I specify LC_ALL, then valac no longer crashes.  I haven't had time to dig into this but just thought I'd put that piece of info in case this helps someone. So, the command I used was:

`LC_ALL="en_US" /frida/build/fs-linux-x86_64-valac`

**Comment by raymontag** [comment]
@thejunkjon That's it! I thought I've already tried it because I read something similar in the Debian bugtracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=59802

I will create a PR.

**Comment by AsenOsen** [comment]
> @thejunkjon That's it! I thought I've already tried it because I read something similar in the Debian bugtracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=59802
> 
> I will create a PR.

![valac-fuckup](https://user-images.githubusercontent.com/2146615/53361493-f1488100-3948-11e9-98f8-2cafbf0c1bbc.png)

Got this SIGSEGV even having locale configured

**Comment by oleavr** [comment]
Got bitten by this issue on Ubuntu 19.04 today, so I finally took a closer look and fixed it properly. Updated toolchains coming soon.
