### ISSUE TITLE
Building Error on Ubuntu 64bit

### ISSUE THREAD

**Issue by june5079** [frida/frida#74]
Hi, Thx for making good tools for hackers.
I think I've followed all instruction from "frida.re" and github.com
But it comes error below. Please check this out.

Envirionment : Ubuntu 14.04 64bit

###################### Error Log #######################

make[2]: Leaving directory `/home/june/frida/build/tmp-android-arm/frida-core/lib/pipe'
. build/frida-env-android-arm.rc && make -C build/tmp-android-arm/frida-core/lib/agent
make[2]: Entering directory `/home/june/frida/build/tmp-android-arm/frida-core/lib/agent'
  VALAC    ../../../../../frida-core/lib/agent/libfrida_agent_la_vala.stamp
  CC       libfrida_agent_la-agent.lo
  CC       libfrida_agent_la-script-engine.lo
  CXX      dummy.lo
  CC       agent-glue.lo
  CCLD     libfrida-agent-glue.la
  CXXLD    libfrida-agent.la
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::ios_base::getloc() const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::locale::use_facet(std::__1::locale::id&) const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::locale::~locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::ios_base::getloc() const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::locale::use_facet(std::__1::locale::id&) const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::locale::~locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::ios_base::clear(unsigned int)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::num_put<char, std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > >::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*): error: undefined reference to 'std::__1::ctype<char>::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry(): error: undefined reference to 'std::uncaught_exception()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry(): error: undefined reference to 'std::__1::ios_base::clear(unsigned int)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush(): error: undefined reference to 'std::__1::ios_base::clear(unsigned int)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__1::ios_base::getloc() const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__1::locale::use_facet(std::__1::locale::id&) const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__1::locale::~locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__1::ios_base::clear(unsigned int)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(assembler.o):../src/assembler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__1::ctype<char>::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function v8::internal::CodeStub::RecordCodeGeneration(v8::internal::Handle<v8::internal::Code>): error: undefined reference to 'std::__1::ios_base::init(void*)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function v8::internal::CodeStub::RecordCodeGeneration(v8::internal::Handle<v8::internal::Code>): error: undefined reference to 'std::__1::locale::locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function v8::internal::CodeStub::RecordCodeGeneration(v8::internal::Handle<v8::internal::Code>): error: undefined reference to 'std::__1::locale::~locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function v8::internal::CodeStub::RecordCodeGeneration(v8::internal::Handle<v8::internal::Code>): error: undefined reference to 'std::__1::ios_base::~ios_base()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream(): error: undefined reference to 'std::__1::ios_base::~ios_base()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function void v8::internal::HydrogenCodeStub::TraceTransition<v8::internal::CompareNilICStub::State>(v8::internal::CompareNilICStub::State, v8::internal::CompareNilICStub::State): error: undefined reference to 'std::__1::ios_base::getloc() const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function void v8::internal::HydrogenCodeStub::TraceTransition<v8::internal::CompareNilICStub::State>(v8::internal::CompareNilICStub::State, v8::internal::CompareNilICStub::State): error: undefined reference to 'std::__1::locale::use_facet(std::__1::locale::id&) const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function void v8::internal::HydrogenCodeStub::TraceTransition<v8::internal::CompareNilICStub::State>(v8::internal::CompareNilICStub::State, v8::internal::CompareNilICStub::State): error: undefined reference to 'std::__1::ctype<char>::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int): error: undefined reference to 'std::__1::num_put<char, std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > >::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int): error: undefined reference to 'std::__1::ctype<char>::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream(): error: undefined reference to 'std::__1::ios_base::~ios_base()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs.o):../src/code-stubs.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream(): error: undefined reference to 'std::__1::ios_base::~ios_base()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(code-stubs-hydrogen.o):../src/code-stubs-hydrogen.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(double): error: undefined reference to 'std::__1::num_put<char, std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > >::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(compiler.o):../src/compiler.cc:function std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned int): error: undefined reference to 'std::__1::num_put<char, std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > >::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(flags.o):../src/flags.cc:function v8::internal::ComputeFlagListHash(): error: undefined reference to 'std::__1::ios_base::init(void*)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(flags.o):../src/flags.cc:function v8::internal::ComputeFlagListHash(): error: undefined reference to 'std::__1::locale::locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(frames.o):../src/frames.cc:function v8::internal::(anonymous namespace)::PrintFunctionSource(v8::internal::StringStream*, v8::internal::SharedFunctionInfo*, v8::internal::Code*): error: undefined reference to 'std::__1::ios_base::init(void*)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(frames.o):../src/frames.cc:function v8::internal::(anonymous namespace)::PrintFunctionSource(v8::internal::StringStream*, v8::internal::SharedFunctionInfo*, v8::internal::Code*): error: undefined reference to 'std::__1::locale::locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(hydrogen.o):../src/hydrogen.cc:function v8::internal::HTracer::Trace(char const*, v8::internal::HGraph*, v8::internal::LChunk*): error: undefined reference to 'std::__1::ios_base::init(void*)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(hydrogen.o):../src/hydrogen.cc:function v8::internal::HTracer::Trace(char const*, v8::internal::HGraph*, v8::internal::LChunk*): error: undefined reference to 'std::__1::locale::locale()'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(isolate.o):../src/isolate.cc:function std::__1::basic_filebuf<char, std::__1::char_traits<char> >::basic_filebuf(): error: undefined reference to 'std::__1::locale::locale(std::__1::locale const&)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(isolate.o):../src/isolate.cc:function std::__1::basic_filebuf<char, std::__1::char_traits<char> >::basic_filebuf(): error: undefined reference to 'std::__1::locale::has_facet(std::__1::locale::id&) const'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(isolate.o):../src/isolate.cc:function std::__1::basic_filebuf<char, std::__1::char_traits<char> >::basic_filebuf(): error: undefined reference to 'std::__1::locale::locale(std::__1::locale const&)'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(isolate.o):../src/isolate.cc:function std::__1::basic_filebuf<char, std::__1::char_traits<char> >::basic_filebuf(): error: undefined reference to 'std::__1::codecvt<char, char, mbstate_t>::id'
/home/june/frida/build/sdk-android-arm/lib/libv8_base.a(isolate.o):../src/isolate.cc:function std::__1::basic_filebuf<char, std::__1::char_traits<char> >::imbue(std::__1::locale const&): error: undefined reference to 'std::__1::codecvt<char, char, mbstate_t>::id'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libfrida-agent.la] Error 1
make[2]: Leaving directory `/home/june/frida/build/tmp-android-arm/frida-core/lib/agent'
make[1]: *** [build/tmp-android-arm/frida-core/lib/agent/libfrida-agent.la] Error 2
make[1]: Leaving directory `/home/june/frida'
make: *** [server-android] Error 2

**Comment by oleavr** [comment]
Hi,

Thanks for reporting. This is a known issue with the prebuilt dependencies on Linux. I built them with GCC 4.9.x, and it turns out that trying to link to those binaries with older versions (like GCC 4.8) is not going to work due to ABI breakage. Possible workarounds are:
- Upgrade to Ubuntu 15.04
- Recompile the dependencies

To recompile the dependencies, do:

```
$ git clean -xffd # start from a clean slate
$ make -f Makefile.sdk.mk FRIDA_HOST=linux-i386
$ make -f Makefile.sdk.mk FRIDA_HOST=linux-x86_64
```

Then once both of those SDKs have been built there will two tarballs in build/, which you can copy aside for safe-keeping (for future builds), and then proceed to build Frida as normal:

```
$ make
```

Cheers!

**Comment by june5079** [comment]
Thx for the quick replying~!!!.
I took your advice so that I upgraded my ubuntu from 14.04 to 15.10 and clean up git stuff...
But still same error occurred.

The reason I'm trying to compile (not using built binary you've uploaded on frida.re) is that,
I had issus about SELinux on Samsung Galaxy Note2

Yes, I also read github issue post that you replied before.
From that coment you said SELinux issue is now clear and works fine on your Galaxy S6 Device.
But I think It doesn't seem working on mine.

This is environment that I had.

Device : Galaxy Note2 (ARM32)
Rooted : Rooted firmware (Android 4.4.2)

When I try to connect to frieda-server and attach to package, it stops with "permission denied" error msg.
I think "add shell" privilege just have "shell" permission and can't fork process that I want to play.

This is what I wanted to test.
http://rotlogix.com/2015/09/13/defeating-ssl-pinning-in-coin-for-android/
If you don't mind, I hope you test above on your Samsung Galaxy S6 device.

Thx for your support~!! I really appreciate.

**Comment by oleavr** [comment]
Ooh sorry, I missed the part about your cross-compiling for Android. Which Android NDK version are you trying this with?

**Comment by june5079** [comment]
I'm using NDK-10re version now.

**Comment by oleavr** [comment]
Haven't been able to reproduce this. Please reopen if you're still seeing this issue with the latest code in git.
