### ISSUE TITLE
How to read local file in frida

### ISSUE THREAD

**Issue by o0xmuhe** [frida/frida#748]
OS : Windows 7
Frida info : `frida          12.2.14`, `frida-tools    1.2.2`

Hi, I 'd like to read local file and replace data in the memory, I tried `frida-fs` and `new File(filepath,'rb')`, they all failed :( 

so, how can I read local file in frida? My script is based on [this code](https://www.frida.re/docs/examples/windows/).

**Comment by eugenekolo** [comment]
Unfortunately it doesn't look like frida-fs supports Windows. You're going
to have to do extend it yourself.

All the library basically does is create NativeFunctions for the basic file
methods in libc. The equivalent has to be done for Windows. I'm not
familiar with Windows, but I imagine it's something like MSVCRT.dll!open
and others.

**Comment by o0xmuhe** [comment]
@eugenekolo  Thank you very much!!  I will try it in other ways.

**Comment by indexofrefraction** [comment]
if you execute require with frida-gadget you get
`"ReferenceError: 'require' is not defined"`
is there any way to include/require/open/load/read a file with frida-gadget?

**Comment by nobbes** [comment]
> if you execute require with frida-gadget you get `"ReferenceError: 'require' is not defined"` is there any way to include/require/open/load/read a file with frida-gadget?

Use import statements instead of require.

**Comment by indexofrefraction** [comment]
> Use import statements instead of require.

really tried that in all possible ways, to no avail...
issue report: https://github.com/frida/frida/issues/2602

if possible, it would it be really nice to get a small example code for this
(goal not to have all js code in one file)

**Comment by indexofrefraction** [comment]
@nobbes 
please, couldn't you give an example on how to import with frida gadget?
the issue above is unanswered for months :/

**Comment by pwnedDesal** [comment]
how about grep search?

**Comment by indexofrefraction** [comment]
> how about grep search?

i need working example code. 
from my experience frida-gadget cant include a js file
