### ISSUE TITLE
frida -f on 64bit iOS fails

### ISSUE THREAD

**Issue by titze** [frida/frida#749]
I try to spawn a process (app) with frida on iOS but fail to do so.

In ~80% of the cases, I get the error: _FBSOpenApplicationErrorDomain error 1_

I am running iOS 10.2 on a (jailbroken) Iphone 7, frida-server 12.2.27-ios-arm64

Any idea what this is and how I can get this more reliable?

Thanks!

**Comment by oleavr** [comment]
Try moving the `frida-server` binary to `/usr/sbin`. If that doesn't solve the issue, it means this is a jailbreak-specific issue.

**Comment by titze** [comment]
Moving the binaries to /usr/sbin did not resolve the issue.

Any way I can debug/fix this?
