### ISSUE TITLE
frida.TransportError: timeout was reached

### ISSUE THREAD

**Issue by thetana** [frida/frida#752]
Hi
I want get IOS App's Classes and Methods.
but my code make Errior that "frida.TransportError: timeout was reached"

It is my javascript code.
```
"""
if (ObjC.available) {
    for (var className in ObjC.classes) {
    	if (ObjC.classes.hasOwnProperty(className)) {
    		var methods = ObjC.classes[className].$ownMethods;
    		for (var i = 0; i < methods.length; i++) {
    	            var _className = "" + className;
    	            var _methodName = "" + methods[i];
                    send(_className + _methodName);
                }
    	}
    }
} else {
    console.log("Objective-C Runtime is not available!");
}
"""
```
Please help me

**Comment by OldTiger** [comment]
@oleavr  Can we manually set timeout value?

**Comment by nikswap** [comment]
I get the same error on android. My script is reading something from memory and base64 encoding it. It is a process that takes a long time, so it would be nice if the timeout could be set manually

**Comment by oleavr** [comment]
Scripts should never do anything long-running at load-time. Defer such work using e.g. `setImmediate()` instead. Also, for performance reasons I wouldn't recommend calling `send()` with every single method name – implement some batching logic instead.
