### ISSUE TITLE
hook shared library constructor

### ISSUE THREAD

**Issue by henrayluo** [frida/frida#757]
i am working on android platform. is there some example code for hooking shared library constructors? i can not get the best opportunity to hook.

**Comment by oleavr** [comment]
For now you'll have to parse the PE/Mach-O/ELF headers yourself, or use a static analysis tool like r2, to determine where the constructors are. You can also use the `DebugSymbol` API if symbols are available. PRs welcome to add API to `Module` to enumerate constructors. We already have implementation code for this for Mach-O and partially for ELF. Only PE would be some work to fill in the missing bits. Cheers!

**Comment by henrayluo** [comment]
I am sorry for my poor english. I did find the address of the method i want to hook,  but it was called too early to hook. When the shared lib was be dlopened, it was called from the constructor. If i spawn the app then attach it, i can not get the base address of the load lib.

**Comment by henrayluo** [comment]
> I am sorry for my poor english. I did find the address of the method i want to hook, but it was called too early to hook. When the shared lib was be dlopened, it was called from the constructor. If i spawn the app then attach it, i can not get the base address of the load lib.

finally i got it worked. i hook into linker's call_constructor and get the soinfo's 'this' pointer which by adding some offset to get the base address of the shared lib.

and i found a post [http://www.giovanni-rocca.com/giving-yourself-a-window-to-debug-a-shared-library-before-dt_init-with-frida-on-android/](url) that also solved my problem.

**Comment by oleavr** [comment]
Yeah the best solution is to hook the dynamic linker's internals. I'm hoping somebody will publish a Frida-specific module to [npm](https://www.npmjs.com/search?q=frida) that solves this problem across different OSes. (That module would then be consumed through `frida-compile`. [Here](https://github.com/oleavr/frida-agent-example) is an example showing how to use `frida-compile`.)

**Comment by henrayluo** [comment]
thank u very much. i will learn about that.
