### ISSUE TITLE
Cross compiling frida's python bindings

### ISSUE THREAD

**Issue by muhzii** [frida/frida#775]
Are there any instructions on how to cross-compile this? I'm using a x86_64 Linux and would like to build the python bindings for android arm.

**Comment by muhzii** [comment]
Closing the issue.. This would actually be possible by changing the Python include directory in the build script [https://github.com/frida/frida-python/blob/master/meson.build#L60-L65](meson.build) to point to the architecture specific Python headers.
@oleavr , do you consider this a valid use case/ should be supported?

**Comment by oleavr** [comment]
@muhzii Yes it would be good to support this. Will we be able to upload cross-compiled `.egg` builds though?

**Comment by muhzii** [comment]
@oleavr No, They'd have to be manually built or installed.

**Comment by interference-security** [comment]
@muhzii Hi. I would like to take take this forward and see if we can create EGG files for frida-python.
You referred to a change in meson.build file. Please share what changes did you make then tried cross-compiled for Android ARM. Your support here will be highly appreciated.
