### ISSUE TITLE
iOS: Connection refused

### ISSUE THREAD

**Issue by JohnCoates** [frida/frida#78]
Running El Capitan and iOS 9 on an iPhone 5s, I get `Failed to enumerate processes: unable to connect to remote frida-server: Unable to connect (connection refused)` when running `frida-ps -U`

**Comment by JohnCoates** [comment]
Took a look at the Android instructions, and it mentioned running "frida-server" so I ran that command over SSH and now it works

**Comment by oleavr** [comment]
This is a known issue that I should have mentioned in the release notes - sorry about that: `frida-server` gets launched by launchd but gets instantly killed by Jetsam on iOS 9 (works on iOS 8). We need to figure out a way to override the resource limit that Jetsam catches us exceeding.

**Comment by JohnCoates** [comment]
Ah, tricky. The iOS 9 jailbreak now enforces some entitlements that were optional in the past jailbreaks

**Comment by Cianjoo** [comment]
hi, now I tried using frida in iphone5 (ios9) with Mac..
but I met.... is it still not fixed? or I have env problem? 
Failed to enumerate processes: unable to connect to remote frida-server: Unable to connect (connection refused)

**Comment by oleavr** [comment]
@Cianjoo Does it work if you ssh to your device and manually start frida-server as root?

**Comment by fingerco** [comment]
frida-server does seem to be working upon manually running it via SSH.

**Comment by oleavr** [comment]
@JohnCoates Did you figure out which entitlements are needed? I didn't yet dig into this, but I noticed that putting Jetsam properties in the plist didn't have any effect, and I hope we won't have to use a post-install step where we modify the device-specific plist with Jetsam properties for all system services.

**Comment by oleavr** [comment]
This issue has finally been fixed in the latest release (6.0.6).
