### ISSUE TITLE
unexpected error while preparing pipe endpoints

### ISSUE THREAD

**Issue by schirrmacher** [frida/frida#783]
I have jailbroken an iPhone 7 with iOS 12.1.1 Beta 3 and unc0ver. When I try to trace a process with frida 12.3.6 I get the following error:

`Failed to attach: unexpected error while preparing pipe endpoints for process with pid 986 (mach_port_allocate remote_rx returned '(os/kern) invalid task')`

**Comment by schirrmacher** [comment]
I have seen that unc0ver is not supported yet.

**Comment by luoyanbei** [comment]
My iPhone is iOS13.1 , jailbreak by unc0ver。When I using frida-trace , I get the same error .
I uninstall frida and reinstall frida, it works for me.
