### ISSUE TITLE
NativeFunction not run

### ISSUE THREAD

**Issue by c0rpse** [frida/frida#786]
**The native funciton declaration like this:** 
        public static native String nativeGetSign(String paramString);

**IDA reverses .so file  and related function likes this:**
        int __fastcall Java_com_xxx_AntiSpam_nativeGetSign(JNIEnv *a1, int a2, int a3)

**I use code below to create a native function:**

         var signPointer = Module.findExportByName("libanti_spam.so", 
        "Java_com_xxx_AntiSpam_nativeGetSign");
        var i = new NativeFunction(signPointer, 'pointer', ['pointer']);

**When i want to call this native function in javascript code like this:**
        var s0 = Memory.allocUtf8String("YmR1c3M9ZC1ZM2RYTmtRem");
        var ret = i(s0); 
        send("get new string: " + ret);
**An error occured. "Error: access violation accessing 0x31526ffd".
Is there any wrong thing？**

**Comment by duolaaa** [comment]
meet the same problem

**Comment by duolaaa** [comment]
did u solved it ? @c0rpse

**Comment by c0rpse** [comment]
> did u solved it ? @c0rpse
yeap！
Code likes below：
`var sign_func = new NativeFunction(signPointer, 'pointer', ['pointer', 'pointer', 'pointer']);
    send("create new native function at:" + signPointer);
    send("create new native function at:" + sign_func);

    // 获取 JNIEnv*
    var env = Java.vm.getEnv();
    var handle0Pointer = env.handle;
    send("JNIEnv *: " + handle0Pointer);

    //调用JNIEnv的newStringUtf函数生成String实例，返回实例指针
    var t0 = env.newStringUtf("fuck001");
    send("new p2: "  + t0);

    var String_java = Java.use('java.lang.String');
    var ret = sign_func(handle0Pointer, ptr("0x0"), t0);

    send("get new string: " + ret);
    var ret_str = Java.cast(ret, String_java);
    send("sign: " + ret_str);`

**Comment by c0rpse** [comment]
@duolaaa Wait for your replay.

**Comment by duolaaa** [comment]
@c0rpse   邮件联系一下，感谢。

imelon@foxmail.com

**Comment by c0rpse** [comment]
# #
