### ISSUE TITLE
Connection is closed. Phone reboot. IDK why

### ISSUE THREAD

**Issue by minhtt159** [frida/frida#788]
I don't know if this is a trivial problem or not. Anyway, this is my situation.
I recently back to frida after long time not using. I updated frida-tools on my mac and frida server on my phone to 12.4. I'm using Unc0ver 2.2.6 for my iPhone 6s 11.0.3.
I tried to run
> frida-ps -U
> Failed to enumerate processes: the connection is closed   

And my phone reboot. I tried ssh to the phone and the frida-server process is still on 

> ps ax | grep frida
>   610   ??  Ss     0:00.03 /usr/sbin/frida-server
>   635 s000  R+     0:00.01 grep frida

Is there any reason why it happens?

**Comment by MuchiMuchiPink** [comment]
Did you update frida on your mac as well? Not just frida-tools.

**Comment by minhtt159** [comment]
> Did you update frida on your mac as well? Not just frida-tools.

Yes. It's not saying that frida is not compatible. It reboots the phone instantly

**Comment by mrchisel14** [comment]
This worked for me: https://github.com/frida/frida/issues/792#issuecomment-470029154

**Comment by yzytmac** [comment]
问题怎么解决的?我也遇到这个问题
