### ISSUE TITLE
Failure creating NsMutableArray

### ISSUE THREAD

**Issue by priyankn** [frida/frida#794]
This Seems straightforward, but getting the following error when trying to create a simple NSMutableArray:

-> var string = ObjC.classes.NSString.stringWithString_('dd')
undefined
-> var arr = ObjC.classes.NSMutableArray.arrayWithObjects_(string)
Error: access violation accessing 0x1

iOS 11.1.2 Electra JB. 

Let me know if anyone has any ideas.

**Comment by oleavr** [comment]
You are `arrayWithObjects:` expects a `nil`-terminated argument list. You should however use `arrayWithObject:` given that you have a single object.

**Comment by priyankn** [comment]
Thanks for your reply! I can successfully create an object with ```arrayWithObject:```

For ```arrayWithObjects:```,  I was aware of the nil terminated arg, but doesnt seem to work as expected.

```
[iPhone::]-> var arr = ObjC.classes.NSMutableArray.arrayWithObjects_(string, 'nil')
Error: access violation accessing 0x1
[iPhone::]-> var arr = ObjC.classes.NSMutableArray.arrayWithObjects_(string, nil)
ReferenceError: identifier 'nil' undefined
```
