### ISSUE TITLE
`frida-server` doesn't work with unc0ver jailbreak

### ISSUE THREAD

**Issue by evandrix** [frida/frida#799]
**error**
```
# ./frida-server-12.4.0-ios-arm64
Killed: 9
```

**attempted failed resolution**
- tried https://build.frida.re + install `Frida` according to https://www.frida.re/docs/ios, but that screws up jailbreak, i.e. Cydia wouldn't launch anymore

**system information**
- iPhone 5s running iOS v12.1.1 (16C5050a)
- [unc0ver jailbreak](https://github.com/pwn20wndstuff/Undecimus)
```
# uname -a
Darwin <redacted> 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 21:07:35 PST 2018; root:xnu-4903.232.2~2/RELEASE_ARM64_S5L8960X iPhone6,2 arm64 N53AP Darwin
```

**Comment by oleavr** [comment]
For now you'll have to build Frida from git yourself – unc0ver is only supported in latest git. Will push a new release as soon as early instrumentation is also working. (Everything else should work, though.)

**Comment by evandrix** [comment]
oh ok :+1:

**Comment by varenc** [comment]
@oleavr These recent changes to support unc0ver are now released, right? I've installed frida 12.6.11 on my mac and on a jailbroken iPhone X (iOS 11.3) and still having trouble getting it to work.

`frida-ps -U` works fine, but when I attempt to trace I get a permissions error:
```
➜  / frida-ps -U | grep Signal
3764  Signal
➜  / frida-trace -U Signal -m "-[NSURL* *HTTP*]"
Failed to start tracing: [Errno 13] Permission denied: '/__handlers__'
```

Any tips for getting this working?

**Comment by eugenekolo** [comment]
Looks like you're running at root? Frida cli creates a dir and you don't
have permission to create the dir in your current working directory. Move
to /tmp and try there.

- Sent from my Macbook Wheel

**Comment by varenc** [comment]
DOH! Wow, thanks for catching that.  Should have realized `/__handlers__` wasn't referring to a path on my iOS device...

That said, I'm now being blocked by this error:
```
➜  /tmp frida-trace -U Signal -m "-[NSURL* *HTTP*]"
Failed to attach: unable to mmap ((os/kern) no space available)
```

@792 mentions the same problem, but there it looks like the fix was just using the lastest code. Any chance if I downgrade to version 12.4.1 on mac and iOS that would fix the issue? Also looks like @931 had the same problem on a recent release but switched to the electra jailbreak to fix this.

**Comment by varenc** [comment]
Nevermind, fixed! I think [ssl kill switch](https://github.com/nabla-c0d3/ssl-kill-switch2) was interfering with Frida. I uninstalled that and re-installed frida-server on my iOS device, and things are working!  Or maybe just re-installed was all I needed, not sure.

```
➜  /tmp frida-trace -U Facebook -m "-[NSURL* *HTTP*]"


Instrumenting functions...
-[NSURLSession can_delegate_task_willPerformHTTPRedirection]: Loaded handler at "/private/tmp/__handlers__/__NSURLSession_can_delegate_task_8af1388e.js"
-[NSURLSession delegate_task:willPerformHTTPRedirection:newRequest:completionHandler:]: Loaded handler at "/private/tmp/__handlers__/__NSURLSession_delegate_task_wil_61cd27d8.js"
-[NSURLSession dataTaskWithHTTPGetRequest:completionHandler:]: Loaded handler at "/private/tmp/__handlers__/__NSURLSession_dataTaskWithHTTPG_4912dd37.js"
...
```

Thanks for your help.
