### ISSUE TITLE
Cannot attach to process on Ubuntu 14.04 segfault

### ISSUE THREAD

**Issue by hackvertor** [frida/frida#80]
Hi thanks for the cool project

I've been trying the sample code from the website, the hello.c app and hook.py I've changed the flag in /etc/sysctl.d/10-ptrace.conf to kernel.yama.ptrace_scope = 0 and I'm able to attach to Firefox using a normal ptrace command but whenever I use frida I get a seg fault. If I use gdb the process doesn't segfault and I get the following message:

Traceback (most recent call last):
  File "hook.py", line 4, in <module>
    session = frida.attach("hello")
  File "build/bdist.linux-x86_64/egg/frida/__init__.py", line 55, in attach
  File "build/bdist.linux-x86_64/egg/frida/core.py", line 87, in attach
frida.PermissionDeniedError: unable to access process with pid 7961 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root

But I'm 100% I've changed ptrace_scope.
cat /proc/sys/kernel/yama/ptrace_scope 
0

Cheers

**Comment by oleavr** [comment]
Hi,

Thanks for reporting! Which user are you running python as? If the target crashes when attaching it most likely means that the code we inject fails to load our `frida-agent.so`. The `dlopen()` call returns NULL, and we crash. The python process should write `frida-agent.so` to a temporary directory, and if this file isn't readable by the target process it will crash when trying to attach to it. Could you check your tempdir to see if you can figure out what the permissions are?

Cheers!

**Comment by hackvertor** [comment]
I've tried with a normal user and using sudo. The files seem to be written to the tmp directory.

**Comment by vladsolov** [comment]
same issue; all the test are resulting in segFault at the attach line;
tried both node.js and python frida code both on cat process and hello process (counting numbers with f func);

my config:
Frida:root@:/$ uname -a
Linux LpTwist 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Frida:root@:/$ cat /etc/issue
Ubuntu 14.04 LTS \n \l
Frida:root@:/$ python -V
Python 2.7.6
Frida:root@:/$ frida --version
6.0.3
Frida:root@:/$ node -v
v5.1.0
Frida:root@:/$ npm  -v
3.5.0

**Comment by upfall** [comment]
the same!
I am using 2.6.32-220.23.2.el6.x86_64 #1 SMP Mon Jan 28 17:12:52 CST 2013 x86_64 x86_64 x86_64 GNU/Linux, Frida 6.0.6.
And find the /tmp/frida-xxxxxxxxx is  empty

**Comment by oleavr** [comment]
Sorry about the delay. This is now finally [fixed](https://github.com/frida/frida/commit/aef24365643bdd303f527e69f6fa97baac3e9d83) and released in 6.0.8.
