### ISSUE TITLE
Help with frida injection

### ISSUE THREAD

**Issue by shadowzoom** [frida/frida#800]
Hi there! I'm trying to bypass ssl pinning in snарchat and intercept traffic, but none of the current frida scripts is not working :( Can you please help me with this? Thanks in advance

**Comment by oleavr** [comment]
Try hooking [SSLRead](https://developer.apple.com/documentation/security/1394324-sslread?language=objc) and [SSLWrite](https://developer.apple.com/documentation/security/1400864-sslwrite?language=objc) to get the protocol data after decryption and before encryption, respectively.

**Comment by oleavr** [comment]
You're in luck since I've actually covered this in some of my Frida talks, demoing the following on Snapchat:

```sh
$ frida-trace -U -f com.toyopagroup.picaboo -i SSLRead -i SSLWrite
```

Then replace the contents of `SSLRead.js` with:

```js
{
  onEnter: function (log, args, state) {
    log("SSLRead(" + "" + ")");
    this.data = args[1];
    this.processed = args[3];
  },

  onLeave: function (log, retval, state) {
    var status = retval.toInt32();
    if (status === 0) {
      var data = Memory.readByteArray(this.data, Memory.readPointer(this.processed).toInt32());
      log(hexdump(data, { ansi: true }));
    }
  }
}
```

And the contents of `SSLWrite.js` with:

```js
{
  onEnter: function (log, args, state) {
    log("SSLWrite(" + "" + ")");
    this.data = args[1];
    this.processed = args[3];
  },

  onLeave: function (log, retval, state) {
    var status = retval.toInt32();
    if (status === 0 && !this.processed.isNull()) {
      var data = Memory.readByteArray(this.data, Memory.readPointer(this.processed).toInt32());
      log(hexdump(data, { ansi: true }));
    }
  }
}
```
