### ISSUE TITLE
Question about emulator

### ISSUE THREAD

**Issue by Nightshades1** [frida/frida#801]
Hello, i know that it is currently not supported by frida so i'm wondering what is the issue with it ?
Does the way they execute the opcodes are problematic or something, or is it just a problem of paths, as i usually get local lib == remote lib (don't remember the assertion), if a day this is supported then it would work in all emulator and that would be a great thing, my pc sux i can't use AVD while Nox and others emu works very well.

It's also because my tablet isn't rooted as it's a nice huawei tablet with bootloader locked, i do use frida-gadget and it works perfect but repacked apk is now detected (until i crack this as well) and this make me waste time instead of RE'ing the game :dagger:

Beside this, i've seen that GameGuardian can attach to game runing in Parallel Space, i was wondering if it isn't possible to do the same ? like frida-server would see those runing process as they are virtualized.

if frida-gadget works without root, then there should be a way to attach it to a virtualized process or those that really require root (im a bit confused on how GameGuardian can attach). 

Thanks for this great RE framework :1st_place_medal:

**Comment by oleavr** [comment]
It's possible to support, and I'm hopeful somebody will contribute support for it someday (I don't have the time).

All it takes is embedding both `x86` and `arm` versions of `frida-agent.so`, just like we embed `x86` and `x86_64` in the `x86_64` build. The injector would then have to detect that the target process is using emulation, and in the native x86 code that it generates that calls `dlopen()` it would instead call the emulator so it emulates some code that does `dlopen()`.

**Comment by oleavr** [comment]
The code generated to call `dlopen()` is [here](https://github.com/frida/frida-core/blob/ffe2c7fb16f34a8fddc46d25e1903ddae54d300b/src/linux/frida-helper-service-glue.c#L1274-L1290) btw.
