### ISSUE TITLE
win10+模拟器 ./frida-server Clone is not a function\n    at cloneArtMethod

### ISSUE THREAD

**Issue by yilingsj** [frida/frida#811]
电脑是win10 64位，
frida --version 12.4.2 
电脑上装的逍遥模拟器，如图：
![逍遥模拟器版本信息](https://img.alicdn.com/imgextra/i2/759415648/O1CN01p0q0uU1rapUFlqMys_!!759415648.png)
我在cmd上执行：
adb kill-server
adb start-server
adb connect 127.0.0.1:21503
adb devices
adb root
adb push E:\soft\burpsuite\frida-server-12.4.3-android-x86\frida-server /data/local/tmp/
adb shell "chmod 755 /data/local/tmp/frida-server"
adb shell
cd /data/local/tmp
./frida-server
后就报错了，如图：
![frida-server error](https://img.alicdn.com/imgextra/i4/759415648/O1CN01EABkma1rapUDbhwci_!!759415648.png)
{"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java/lib/android.js:859:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1655:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1568:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1395:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:196:31)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2105:1), <anonymous>:1:285)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":859,"columnNumber":1}
{"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java/lib/android.js:859:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1655:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1568:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1395:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:196:31)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2105:1), <anonymous>:1:285)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":859,"columnNumber":1}

我不想在真机上安装xposed和root手机，因为我怕刷成了板砖......

**Comment by Nightshades1** [comment]
Emulator(s) are not supported as Frida isn't yet  X86-Arm, you are clearly using Memu :rofl:

**Comment by yilingsj** [comment]
> Emulator(s) are not supported as Frida isn't yet X86-Arm, you are clearly using MEmu 🤣

你好，我今天把手机刷机了，oppo a33，刷机后执行./frida-server提示：
Unable to save SELinux policy to the kernel: Permission denied
Segmentation fault
可我已经把文件权限设置为777最高权限了。如图：
![Unable to save SELinux policy to the kernel: Permission denied](https://img.alicdn.com/imgextra/i4/759415648/O1CN01Xdz8d01rapUHJod01_!!759415648.png)
![777权限](https://img.alicdn.com/imgextra/i1/759415648/O1CN01WB7MaT1rapUJtlobq_!!759415648.png)

**Comment by huhuang03** [comment]
I have a android  phone which vendor is lenovo. And I have xposed install on my phone.
I use version 12.4.7. And the error log is:

```
{"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java/lib/android.js:859:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1655:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1568:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1395:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:196:31)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2105:1), <anonymous>:1:285)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":859,"columnNumber":1}
```
The error is same, I doesn't know.

**Comment by luoyesiqiu** [comment]
可以尝试Google官方模拟器，这种支持Arm又支持X86的第三方模拟器不适合拿来调试

**Comment by ilanyu** [comment]
nexus 5 Google Official ROM lmy48m, frida-server-12.4.7-android-arm

    {"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java/lib/android.js:859:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1655:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1568:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1395:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:196:31)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2105:1), <anonymous>:1:285)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":859,"columnNumber":1}

The error is same, I doesn't know why.

**Comment by jiangfeng0103** [comment]
华为 ，海信 手机也出现这样的问题
{"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java/lib/android.js:859:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1655:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1568:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1395:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:196:31)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2105:1), <anonymous>:1:285)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":859,"columnNumber":1}

**Comment by Yufengs** [comment]
努比亚也出现

**Comment by zhaoyongping** [comment]
别用国产手机，国人把安卓乱改一通，frida要用原生系统，谷歌亲儿子试试

**Comment by oleavr** [comment]
Yes, unsupported ROM. PRs welcome though!
