### ISSUE TITLE
how to use frida to invoke a method by reflect

### ISSUE THREAD

**Issue by zxhubo** [frida/frida#815]
I have a question about how to how to use frida to invoke  a method by reflect。
For example，there is a method "public byte[] aesEncrypt(String plaintext)" in class "com.example.cryptutils.util.CryptoUtils", I want to invoke aesEncrypt by reflect, so the frida script is

```
var class_name1 = "com.example.cryptutils.util.CryptoUtils";
    var clz = Java.use("java.lang.Class");
    var Platform1  = Java.use(class_name1);
    var string=Java.use("java.lang.String");
    var method_aes = Platform1.class.getDeclaredMethod("aesEncrypt",Java.array('java.lang.Class', [string.class]) );
    method_aes.invoke(param1,param2);
```
but I do not know how to input the invoke of two param in the last code "method_aes.invoke(param1,param2);"
if I write "method_aes.invoke(Platform1.class,Java.array("java.lang.Object",[string.$new("hahaha")]));" ,frida throw Excepion,
do you know how to input the two param of invoke(param1,param2)?

**Comment by zxhubo** [comment]
@oleavr

**Comment by zxhubo** [comment]
@oleavr ,do you know how to input the two param of invoke(param1,param2)

**Comment by zxhubo** [comment]
I got it ！！！

**Comment by ilovechocolate** [comment]
hi @zxhubo, could you please tell me how to input the args of invoke???
I came up with the same problem and I can't fix it

**Comment by xiaoxiongwang** [comment]
hi @zxhubo , could you please tell me how to input the args of invoke???
I came up with the same problem and I can't fix it
