### ISSUE TITLE
Crash in frida-trace when log tries to print Unicode Text.

### ISSUE THREAD

**Issue by anirudhrata** [frida/frida#82]
Hi, 

While using frida-trace, I modified the handler to print one of the arguments `log(Memory.readUtf16String(args[1])` . It works well for ascii characters but crashes when Unicode occurs. 

      File "C:\Python27\lib\encodings\cp437.py", line 12, in encode return codecs.charmap_encode(input,errors,encoding_map)
    UnicodeEncodeError: 'charmap' codec can't encode character u'\xa9' in position 16: character maps to <undefined>

I am using it on Windows 7 with python 2.7

Thanks.

**Comment by oleavr** [comment]
Ooh, nice catch. I have only tested `frida-trace` in unicode-capable terminals so far. I'll set up a VM and try to reproduce this.

**Comment by oleavr** [comment]
Fixed: https://github.com/frida/frida-python/commit/a0405e3f4ac86634cb649b0e0a928db2645ce916

**Comment by anirudhrata** [comment]
Thanks. Works like a charm!
