### ISSUE TITLE
how to create int.class & boolean.class and other basic type variable by js

### ISSUE THREAD

**Issue by zxhubo** [frida/frida#835]
we can use getMethod by frida ,for exmaple:
var method_aes = Platform1.class.getDeclaredMethod("aesEncrypt",Java.array('java.lang.Class', [string.class]) );
but if the parameter is int  or boolean  or float and other basic type ,how to use js to construct int.class,float.class ,boolean and so on ?

**Comment by zxhubo** [comment]
I got it！

**Comment by poipoipoi000** [comment]
@zxhubo 请问，您是怎么解决这个问题的？

**Comment by poipoipoi000** [comment]
@zxhubo Excuse me, how do you solve this problem?
