### ISSUE TITLE
App hangs in java.lang.Runtime.exec with invalid command

### ISSUE THREAD

**Issue by gebing** [frida/frida#836]
1、I wrote an app with following code, and exec can return without frida:

```
Log.i(TAG, "before call exec");
Runtime.getRuntime().exec("fake.cmd");
Log.i(TAG, "after call exec");
```

2、If i start frida and attach app, the app is hanged and exec will never return, only output 'before call exec':

`frida -U -f com.package.name --no-pause`

I am using:
frida-server-12.4.7-android-arm64
frida           12.4.7
Android 6.0

**Comment by gebing** [comment]
I also change the 'fake.cmd' to 'fakecmd', it is the same and exec hangs without return.

**Comment by oleavr** [comment]
You need to `.enable_child_gating()` and handle the `child-added` signal on `Device`. The REPL does not currently do this (PRs welcome).

**Comment by gebing** [comment]
I try `.enable_child_gating()` and handle the `child-added` signal by just resume the thread, but it still get stuck on invalid command. below is my python code for handle `child-added`:

```
self._device.on("child-added", lambda child: self._reactor.schedule(lambda: self._on_child_added(child)))
self._device.on("child-removed", lambda child: self._reactor.schedule(lambda: self._on_child_removed(child)))
self._session.enable_child_gating()
```

```
def _on_child_added(self, child):
    self._print("Child added: {}".format(child))
    session = self._device.attach(child.pid)
    session.on("detached", lambda reason: self._reactor.schedule(lambda: self._on_child_detached(child.pid, session, reason)))
    # session.enable_child_gating()
    self._device.resume(child.pid)

def _on_child_removed(self, child):
    self._print("Child removed: {}".format(child))

def _on_child_detached(self, pid, session, reason):
    self._print("Child detached: pid={}, reason='{}'".format(pid, reason))
```

And below is the console output:
```
Child added: Child(pid=29521, parent_pid=29481, origin=fork)
Child removed: Child(pid=29521, parent_pid=29481, origin=fork)
Child added: Child(pid=29577, parent_pid=29481, origin=fork)
Child removed: Child(pid=29577, parent_pid=29481, origin=fork)
Child detached: pid=29521, reason='process-terminated'
Child added: Child(pid=29616, parent_pid=29481, origin=fork)
Child removed: Child(pid=29616, parent_pid=29481, origin=fork)
Child added: Child(pid=29632, parent_pid=29481, origin=fork)
Child removed: Child(pid=29632, parent_pid=29481, origin=fork)
Child detached: pid=29577, reason='process-terminated'
Child detached: pid=29616, reason='process-terminated'
```

Child process `29632` only get `child-added` and `child-removed` signal, but no `detached` signal. And on device shell, i execute `ps |grep com.target.app` and output is:
```
u0_a102   29481 602   1564384 137608 SyS_epoll_ 00f747cc84 S com.target.app
u0_a102   29632 29481 1437320 52704 futex_wait 00e1aaf7f4 S com.target.app
```

You can see the process `29632` is in futex_wait state, and application is hanged waiting for process end. And i try kill the process `29632` manually, the application can resume run.

**Comment by gebing** [comment]
By the way, in callback `_on_child_added`, i comment the invoke of `enable_child_gating`, becuase `session = self._device.attach(child.pid)` will failed with error `NotSupportedError: unable to inject library into process without libc` when exec a shell command without libc.so.
