### ISSUE TITLE
[ios-mac]frieda-server is not working

### ISSUE THREAD

**Issue by Cianjoo** [frida/frida#85]
Hi, I tried using frida iPhone 5(ios9) with mac.
when I put command 'frida-ps -U', I got below,
Failed to enumerate processes: unable to connect to remote frida-server: Unable to connect (connection refused)

hm... I want use your tool...would you help me? 
actually my iphone5 is already on jailbreak ...

**Comment by oleavr** [comment]
Hi,

This is because of a known issue where `frida-server` fails to launch properly with launchd due to Jetsam resource limits. For now you will have to ssh to your device and manually run `frida-server &` as root.

Cheers!

**Comment by Cianjoo** [comment]
hi, thanks for your replay..
I tried sudo frida-ps -U but it still fail by same reason...
do you have any idea?

**Comment by Cianjoo** [comment]
hi, 
mac : I just success for 'sudo easy_install frida'.
iphone5 : with jailbreak then install frida by your guide.

then I connected device to mac > tried frida-ps -U.... would you tell me it need to more?

**Comment by oleavr** [comment]
Yes, if your iPhone is running iOS 9 you will also need to:

```
$ ssh root@your-iphone
$ frida-server &
```

**Comment by oleavr** [comment]
Fixed in the latest release (6.0.6).
