### ISSUE TITLE
Why frida-ps: not found

### ISSUE THREAD

**Issue by b03201003** [frida/frida#852]
Hi. I'm trying to build frida on my HTC 10. I pushed frida-server by adb 
I tried the steps in some teaching website such as https://bbs.pediy.com/thread-248293.htm and  
https://blog.zzzmode.com/2017/09/12/frida-android-hook/?fbclid=IwAR04MhkGmTloPK0_st7f32CfxQGzuBHGFy4n3mnhxvcIz2jsTXaY7C0Qc-g.

However, when I executed "frida-ps -U", I got "sh: frida-ps: not found"
Is there anyone know what I should do?? Thanks!!!

**Comment by eugenekolo** [comment]
frida-ps is on your computer, not the phone.
it must be installed using `pip install frida-tools`

**Comment by b03201003** [comment]
Thanks!
