### ISSUE TITLE
May I ask for an example of using Javascript SocketListener?

### ISSUE THREAD

**Issue by SheilaLundin** [frida/frida#853]
I tried sereral days to write it by myself, unfortunately, I failed.
Could some smart guys give me an example?
Thank you very much.

**Comment by gorelics** [comment]
You mean using sockets in your frida script or to hook sockets calls?

**Comment by gorelics** [comment]
You can look to gists how it's work [Java.choose gists](https://gist.github.com/search?utf8=%E2%9C%93&q=frida+java.choose)

**Comment by SheilaLundin** [comment]
using sockets in frida script, and keep reading from inputstream, writing to outputstream. just like a normal socket server.

**Comment by SheilaLundin** [comment]
> You mean using sockets in your frida script or to hook sockets calls?

using sockets in frida script, and keep reading from inputstream, writing to outputstream. just like a normal socket server.

**Comment by gorelics** [comment]
In this example used Java sockets to communicate [Frida Java Socket](https://gist.github.com/malacupa/edd1fcb23121785f3e5f3ac02c69d8ca)

**Comment by gorelics** [comment]
I don't understand why you need that, there is already implemented messaging. If you want to connect through TCP not USB you can run frida-server with opts
```bash
# listen on 127.0.0.1:27042 (the default)
$ frida-server

# listen on all interfaces
$ frida-server -l 0.0.0.0

# listen on a specific interface
$ frida-server -l 192.168.1.3

# listen on a specific interface and port
$ frida-server -l 192.168.1.3:1337

# connect to specific IP
$ frida-trace -H 192.168.1.3 -i "open*"

# connect to specific IP/port
$ frida-trace -H 192.168.1.3:1337 -i "open*"```

**Comment by SheilaLundin** [comment]
Thank you very much for response. I try to inject an app, and send instructions to server to do specific work 
 automatically.

**Comment by eugenekolo** [comment]
Typing on phone so may contain typos. The API is promises based so if
you're inexperienced in js it can be challenging.

```
Socket.listen({SPEC})
.then(function (listener) {
  listener.accept()
  .then(function(Conn) {
   Conn.input.read()
  }.catch( ...)
}).catch(function (err) {
  Log err
}
```

Should get you started.

- Sent from my iPhone 12SR.

**Comment by SheilaLundin** [comment]
I know how to receive packet once, but my target is keeping receiving packets, like a c/c++ socket server.

**Comment by eugenekolo** [comment]
You can put the read() into a function that calls itself.

- Sent from my iPhone 12SR.

**Comment by gorelics** [comment]
Check this example, it's clear enough how to use send recv loop [Frida Node.js example](https://gist.github.com/oleavr/6ecae99945ccba47427a)

```js
function onMessage(message) {
        send({ name: "pong", payload: message }); 
        recv(onMessage);
}
recv(onMessage);
```

**Comment by SheilaLundin** [comment]
This is my code
```
function onMessage(message) {
    if (message['buff'] && message['buff'].byteLength != 0) {
        var arr = new Uint8Array(message['buff']);
        var s = typedArrayToUnicodeString(arr);
        console.warn('recv: ' + s);
        message['conn'].output.writeAll(message['buff']);
    }

    message['conn'].input.read(100)
        .then(function (buff) {
            onMessage({'conn': message['conn'], 'buff': buff})
        });
}

function onConnect(connection) {
    connection.input.read(100)
        .then(function (buff) {
            onMessage({'conn': connection, 'buff': buff})
        });
}

function interaction() {
    const listenerPromise = Socket.listen({"family": 'ipv4', 'host': '127.0.0.1', 'port': 23946});
    listenerPromise
        .then(function (listener) {
            return listener.accept();
        })
        .then(function (connection) {
            onConnect(connection);
        })
        .catch(function (err) {
            console.error('!!!!!!!!!: ' + err.message);
        });
}
```
and the output
```
     recv: {"type": 0}
     Unhandled promise rejection URIError: invalid input
```

**Comment by SheilaLundin** [comment]
It's a bug in function typedArrayToUnicodeString.
Thank you guys!

**Comment by gorelics** [comment]
You don't need to create socket yourself, send and recv are globals that frida provides to communicate with the frida remote control script.

For example if your device have an IP in local area 192.168.0.2, you need to launch  frida-server with opt
`frida-server -l 192.168.0.2:23946`

in your `inject.js` script

```js
function onMessage(message) {
        if(message.type == "task"){
            // do something with message.payload
            // you can return response with send({"type": "response", "payoad":"some data"})
            send({"type": "response", "payload": message.payload});
        }
        // listen for other message non-blocking, 
        recv(onMessage);
}
recv(onMessage);
```

in your `control.py` script 

```python
import frida
import codecs
import sys

def on_message(message, data):
    if message['type'] == 'response':
        print("[*] {0}".format(message['payload']))
    else:
        print(message)

processname = "some.app"
scriptpath = "./inject.js"

manager = frida.get_device_manager()
device  = manager.add_remote_device("192.168.0.2:23946")
pid     = device.spawn([processname])
session = device.attach(pid)

with codecs.open(scriptpath, "r", "utf-8") as f:
    jscode = f.read();

script = session.create_script(jscode)
script.on('message', on_message)
script.load()
device.resume(pid)

# sending message to inject.js script
script.post_message({
    'type': 'task', 
    'payload': "some serializable data"
})
sys.stdin.read()
```

Or maybe I don't understand what you want to achieve, please describe the task you have

**Comment by SheilaLundin** [comment]
Thanks for your tips, but the control is writen in lua by another guy.

**Comment by gorelics** [comment]
Ok, it's clear now ;)

**Comment by gorelics** [comment]
In this case you don't need `send` and `recv` at all unless you communicate with your spawn script if you don't use `frida` directly.

**Comment by 1215clf** [comment]
@SheilaLundin 
hi,
I have same question but ti is about client ，my client just received data once from server 
this is my client code：
```
function interaction(host,port)
{
  console.log('connection host:',host + ':' + port);
  Socket.connect({"family": 'ipv4', 'host': host, 'port': port})
        .then(connected)
        .catch(failure);
}

function connected(connection)
{
  console.log('recived:',connection);
  connection.output.write(str2ab('tsm'));

  const timerObj = setInterval(function () {
    connection.output.write(str2ab('tsm'));
    console.log('发送心跳包');
  },50000);

  console.log('str:',str2ab('tsm'));

  connection.input.read(1024)
            .then(function (buff) {
            onMessage({'conn': connection, 'buff': buff})
            });

}
function onMessage(message) {
    if (message['buff'] && message['buff'].byteLength != 0) {
        var s = ab2str(message['buff']);
        console.warn('recv: ' + s);
    }
}
interaction();
```
I am very confuse what’s wrong about it?

**Comment by brownmouse10** [comment]
I'm trying to get a socket server setup on frida gadget iOS so my client can connect to it and I can send messages to it. Could anyone provide an example?
