### ISSUE TITLE
Frida-Tools Install on Android

### ISSUE THREAD

**Issue by zimmerma379** [frida/frida#860]
Can frida / frida-tools be installed on Android?  I'm using pip3 in QPython3 but get an error:

/data/user/0/org.qpython.qpy3/files/bin/qpython3-android5-root.sh  /data/user/0/org.qpython.qpy3/files/bin/qpypi.py  && exit
ython.qpy3/files/bin/qpypi.py  && exit  <
Input pip3 commands, ie: pip3 install {module} OR pip3 help
-->pip3 install frida
Collecting frida
  Using cached https://files.pythonhosted.org/packages/be/96/ece591b8a19c1a0b57689f00aa1ebcfae544e58773877f0b8ee9ad159f91/frida-12.4.8.tar.gz
Installing collected packages: frida
  Running setup.py install for frida ...error
    Complete output from command /data/user/0/org.qpython.qpy3/files/bin/python3-android5 -u -c "import setuptools, tokenize;__file__='/storage/emulated/0/qpython/cache/pip-build-l_2dzww3/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-6glonkc1-record/install-record.txt --single-version-externally-managed --compile:
    /data/user/0/org.qpython.qpy3/files/lib/python36.zip/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv8l-3.6
    creating build/lib.linux-armv8l-3.6/frida
    copying frida/__init__.py -> build/lib.linux-armv8l-3.6/frida
    copying frida/core.py -> build/lib.linux-armv8l-3.6/frida
    warning: build_py: byte-compiling is disabled, skipping.

    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /frida-12.4.8-py3.6-linux-i686.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>

    ----------------------------------------
Command "/data/user/0/org.qpython.qpy3/files/bin/python3-android5 -u -c "import setuptools, tokenize;__file__='/storage/emulated/0/qpython/cache/pip-build-l_2dzww3/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-6glonkc1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build-l_2dzww3/frida/
-->

**Comment by eugenekolo** [comment]
It's possible... but not sure why. I don't believe this configuration is
supported or a priority.


- Sent from my iPhone 12SR.

**Comment by zimmerma379** [comment]
This issue was not addressed/resolved, but I found [another (better) way](https://github.com/frida/frida/issues/861) to do things so I will CLOSE this issue for now.

**Comment by mintesnot123** [comment]
I have also faced this problem while i try to install numpy using pip

/data/user/0/org.qpython.qpy3/files/bin/qpython3-android5.sh  /data/user/0/org.qpython.qpy3/files/bin/qpypi.py  && exit
n.qpy3/files/bin/qpypi.py  && exit               <
Input pip3 commands, ie: pip3 install {module} OR pip3 help
-->pip3 install numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/2c/2f/7b4d0b639a42636362827e611cfeba67975ec875ae036dd846d459d52652/numpy-1.19.1.zip
Installing collected packages: numpy
  Running setup.py install for numpy ... error
    Complete output from command /data/user/0/org.qpython.qpy3/files/bin/python3-android5 -u -c "import setuptools, tokenize;__file__='/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-3zhlyfxg-record/install-record.txt --single-version-externally-managed --compile:
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)


    Cythonizing sources
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_generator.pyx
    Traceback (most recent call last):
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/tools/cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/tools/cythonize.py", line 235, in <module>
        main()
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/tools/cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/setup.py", line 499, in <module>
        setup_package()
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/setup.py", line 479, in setup_package
        generate_cython()
      File "/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/setup.py", line 274, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!

    ----------------------------------------
Command "/data/user/0/org.qpython.qpy3/files/bin/python3-android5 -u -c "import setuptools, tokenize;__file__='/storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-3zhlyfxg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build-o800idl1/numpy/
-->
