### ISSUE TITLE
Frida not supporting Varargs or anonymous object Java array seeing it as Owners class instead

### ISSUE THREAD

**Issue by ydaniels** [frida/frida#864]
A code like 
```

public class JNICallLibrary {
   
 public static native Object runCommand(int i, Object... objArr);

}

```
runCommand in the native code is seen as 
```

runCommand([Ljava/lang/Object;)Ljava/lang/Object;

```
which is correct but on intercepting this method

```
Interceptor.attach(new NativePointer('0xaddress'), {

 onEnter: function(args) {

this.data = args[0]

...
 
```

this.data or args[0] is coming out as a JNICallLibrary class in frida instead of the actual values

another issue i think its about the topic https://github.com/frida/frida/issues/518

**Comment by ydaniels** [comment]
Sorry my bad

**Comment by WithHades** [comment]
I face a difficult like this.
I want to know the value of object[].
my issue is #1053 
how do you handle?
thx

**Comment by ydaniels** [comment]
@WithHades You can use reflection  to get values 

`
 onEnter: function(args) {
var object_java = Java.use('[Ljava.lang.Object;');
var Ref_arr  = Java.use('java.lang.reflect.Array')
data = args[3]
var data_obj = Java.cast(data, object_java);
var  data_length = Ref_arr.getLength(data_obj)
for (var i = 0; i < data_lenght; i++) {
 var value =   Ref_arr.get(data_obj,i);
   console.log(value);
}

`

**Comment by liaolingfen4** [comment]
thank you so much , fix my issue !!!!
