### ISSUE TITLE
nexus5x android 6.0.1  Process terminated

### ISSUE THREAD

**Issue by tongzhipeng** [frida/frida#865]
**frida version**: 12.4.7
**PC OS version**: win10 1809 (17763.437)
**device**: nexus5x with android 6.0.1, rooted with magisk
**cmd**： frida -U --no-pause -l script.js -f com.android.chrome  （chrome is just for example, it could be any other apps, like calculator and son on）
script.js is very simple, i just copy it from somewhere: 
`Java.perform(function(){Java.enumerateLoadedClasses({"onMatch":function(className){ console.log(className) },"onComplete":function(){}})})`
**exceptation**:  script.js inject succeed and then output some console log.
**result**:  
`Spawned 'com.android.chrome'. Resuming main thread!
[LGE Nexus 5X::com.android.chrome]-> Process terminated`

It works fine on nexus5x with android 8.1.0,  but i run into another problem, hook 'dlopen' cause crash when I hook Unity3D app （but works fine with non Unity3D app）I searched on the github, and found that it related with namespace issue after Android 7.0, that's why switch to android 6.0.1, then I got "ProcessTerminated",  
if there are log files could help, tell me and i will add it. any help would be grateful, thank you!

**Comment by tongzhipeng** [comment]
I have tried older version firda 10.6.29.  it won't show "Process terminated", but the "script.js" is not running.
by the way, both 12.4.7 and 10.6.29 work fine in "attach mode", but I want use hook under "spawn mode", so I can hook something just in the beginning. I will try some other versions and see what will happen.

**Comment by oleavr** [comment]
Could you try Frida from git?

**Comment by tongzhipeng** [comment]
yes, the frida-server versions I have tried are all downloaded from github releases.
the PC frida tools were installed with` pip install frida and   pip install frida-tools.`
Am i doing the right way?
by the way,  I have tried 11.0.13 and 12.2.17. both on Win10 and Ubuntu18.04 in the morning,  they are just like other versions,  work fine in "attach mode" but don't work in "spawn mode".  what can I do to find the reason or solve it?

**Comment by tongzhipeng** [comment]
I get some progress today,  I found that, It may be related with java VM load status, my test script.js start with Java.perform,  but Java VM may not be available when script is injected in to app during it's boot.（spawn mode） 
If my script doesn't start with Java.perform,  like just one line  `console.log("script injected!");`,  It works like a charm.
I was inspired by this issue:  #288 
@oleavr ,  so I think that would be the reason,  you saied " If you inject Frida before the Java VM has been loaded you should instead hook a function called early",  what would be the proper function to hook just after VM load succeed?  sorry for the poor question , I am a c++ developer  and totally new to android and JAVA.  
looking forward to your reply....

**Comment by xiguayizu** [comment]
frida -U -f com.test.apk

while(!Java.available)   // https://github.com/frida/frida/issues/288
// your code start
Java.perform(function(){Java.enumerateLoadedClasses({"onMatch":function(className){ console.log(className) },"onComplete":function(){}})})
// your code end

%resume



can run !!!

**Comment by 157charles** [comment]
I have the same problem. Have you solved it?

**Comment by ishdemon** [comment]
> 
> 
> I get some progress today, I found that, It may be related with java VM load status, my test script.js start with Java.perform, but Java VM may not be available when script is injected in to app during it's boot.（spawn mode）
> If my script doesn't start with Java.perform, like just one line `console.log("script injected!");`, It works like a charm.
> I was inspired by this issue: #288
> @oleavr , so I think that would be the reason, you saied " If you inject Frida before the Java VM has been loaded you should instead hook a function called early", what would be the proper function to hook just after VM load succeed? sorry for the poor question , I am a c++ developer and totally new to android and JAVA.
> looking forward to your reply....

just set the timeout to 100, its probably set to 0 in that script. setTimeout(function(),TIME) Look for the last line.

**Comment by liukuo362573** [comment]
set timeout to 1000 to solve my issue on Android 6.0.1,thanks.

**Comment by khalilklf** [comment]
Solved for me 
after one month of searching and debugging, this was my scenario
The App Lunch with root checking (Bypassed)
When I click on "Go To Login" Process Terminated.

the solution was too easy, just open your "apps" on android and grant the app the required and needed permissions.

Hope this will help you

**Comment by oleavr** [comment]
Let's assume this is fixed 🙂

**Comment by Puvipavan** [comment]
Thanks @liukuo362573  set timeout solved the issue. 
```
setTimeout(function(){ 
    //Your code here
}, 1000);
```

**Comment by yurenchen000** [comment]
some app work, but other direct crash, even without script:

```
frida -U  -f xxxx
```

**Comment by Nord-1** [comment]
I found the cause! Some applications (like in my case) check for frida strings in memory such as re.frida*, frida-agent*.so, frida-server, fridda...etc

The simple salutation is to rename all these strings, change the default frida port and extract the libraries in the CWD:
- mv frida-server-15.1.1-android-x86   fserver
- chmod 777 fserver
-  mv frida-agent-32.so fagent-32.so (or arm .so library if your phone is on ARM Arch)
- ./fserver -d . -l 192.168.0.5:28011 -D
-  ps |  grep fserver
-   frida -H 192.168.0.5:28011 -f  com.example.apk --no-pause

The above worked on Android 7.1 and defeated the frida anti-hocking detections implemented in my apk after a whole month of investigation!
