### ISSUE TITLE
Frida Output - change from overwrite to append

### ISSUE THREAD

**Issue by JoeBlackSecurity** [frida/frida#874]
Currently when outputting console logs to file (-o LOGFILE, --output=LOGFILE), Frida overwrites the file of the same name.
If you output console logs to log.txt and the server crashes, when you restart and start logging again, the previous log file it overwritten unless you remember every time to increment the log file number.
This makes it very difficult when debugging to keep an accurate record of older console data.

Honestly I don't see any reason you would want to overwrite instead of append.
Is it possible to change the behavior to append new console data?

**Comment by oleavr** [comment]
Definitely. Feel free to open a PR in frida-tools. Thanks!
