### ISSUE TITLE
The app quits after hooked in

### ISSUE THREAD

**Issue by butchild** [frida/frida#878]
Some apps will be quit after hooked in  , maybe 2-5 minutes later.
I got the error msg from logcat  :

        Fatal: g_variant_new_string: assertion `g_utf8_validate (string, -1, NULL)' failed
        Pid quit by signal 

I searched the problem and found it has been already fixed in the glib News:
[https://github.com/frida/glib/blob/master/NEWS](https://github.com/frida/glib/blob/master/NEWS)
* Bugs fixed:
 632631 GLib-CRITICAL **: g_variant_new_string: assertion `g_utf8_validate (string, -1, NULL)' failed

So that's wired.  Is the frida using newest version of glib ? Or how can I update the glib for my frida?

The evironment is below:
frida 12.4.7
python 3.7.2
windows 7 
android Mi-5  arm64 rooted

**Comment by thejunkjon** [comment]
@butchild , the instructions to build frida are located here.

https://www.frida.re/docs/building/

You'll need the instructions for building the SDK which is located towards the middle of the page.  IIRC, the glib version used by frida is not the mainstream branch but a self-maintained one.

https://github.com/frida/glib

**Comment by oleavr** [comment]
That error means the Frida agent (written by the user) constructs a JavaScript string from invalid UTF-8 and tries to `send()` it. So this is not a bug in Frida, but a usability issue we probably should address at some point.
