### ISSUE TITLE
Failed to enumerate processes: no such interface 're.frida.HostSession1' on object at path /re/frida/HostSession1

### ISSUE THREAD

**Issue by tosbaha** [frida/frida#88]
OS: OSX El Capitan
iOS: 9.0.2
Jailbroken: YES
I installed with ```sudo easy_install frida``` I installed Frida package from Cydia. During installation it gave me storage is Full message. When I do ```frida-ps -U``` I get
```Failed to enumerate processes: no such interface 're.frida.HostSession1' on object at path /re/frida/HostSession1```

I also tried to run ```frida-server &``` by SSH but this time it complained that

     [1] 647
     Unable to start server: Error binding to address: Address already in use

**Comment by oleavr** [comment]
Hi,

Does this also happen if you reinstall after freeing up storage on your iOS device?

Cheers!

**Comment by oleavr** [comment]
Oh wait, I see the problem. Frida on your host side is outdated. Try: `sudo easy_install -U frida`

**Comment by tosbaha** [comment]
Yay! It is working. Thanks very much. Frida is absolutely fantastic tool :+1:

**Comment by oleavr** [comment]
Glad to hear! 👍 Thanks for the patience!

**Comment by qingfengwolf** [comment]
> Oh wait, I see the problem. Frida on your host side is outdated. Try: `sudo easy_install -U frida`

when i did`sudo easy_install -U frida`， do start dump -> no such interface “re.frida.HostSession14” on object at path /re/frida/HostSession，

**Comment by oleavr** [comment]
@qingfengwolf It means that the other side, or potentially a local gadget (e.g. in ~/.local/frida/), is outdated and not at major version 14.
