### ISSUE TITLE
I get some error

### ISSUE THREAD

**Issue by ehsanpc9999** [frida/frida#880]
i get some error when run this command:

frida -U -f com.app.android -l ANYTHING.js --no-paus

============================================================== https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/

i put this script insted of ANYTHING.js but dose not work for me.

===============================================================

Error:

ReferenceError: identifier 'cf' undefined at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:81174) at /repl1.js:25 at frida/node_modules/frida-java/lib/vm.js:42 at E (frida/node_modules/frida-java/index.js:348) at frida/node_modules/frida-java/index.js:300 at frida/node_modules/frida-java/lib/vm.js:42 at frida/node_modules/frida-java/index.js:280 at /repl1.js:63 at frida/runtime/core.js:55

**Comment by oleavr** [comment]
This is not a bug in Frida, but in this particular script by @pcipolloni. The script is using a variable without declaring it first, which used to be allowed in older versions of Frida as we accidentally didn't enable strict mode.

**Comment by ehsanpc9999** [comment]
> This is not a bug in Frida, but in this particular script by @pcipolloni. The script is using a variable without declaring it first, which used to be allowed in older versions of Frida as we accidentally didn't enable strict mode.


How to fix this problem?

**Comment by oleavr** [comment]
@ehsanpc9999 Add `var ` to the beginning of line 25 of @pcipolloni's script. Ideally he sees this and can fix it, or you can post your own tweaked version with proper attribution.

**Comment by pcipolloni** [comment]
My bad! Thanks guys for pointing it out. I'm adding the fix right now.

**Comment by mrzhang638993** [comment]
{'type': 'error', 'description': "ReferenceError: identifier 'Exception' undefined", 'stack': "ReferenceError: identifier 'Exception' undefined\n    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:81019)\n    at stackTraceHere (/script1.js:22)\n    at /script1.js:7\n    at input:1", 'fileName': '/script1.js', 'lineNumber': 22, 'columnNumber': 1}

**Comment by bugit01** [comment]
@pcipolloni @oleavr @ehsanpc9999 

i too getting the same error on running cmd
i.e frida -U -F com.application.zomato -l frida-android-repinning.js --no-pause

![new](https://user-images.githubusercontent.com/97558344/154865416-fd61d621-58e8-446c-ac93-f6055944e064.png)


If i need to add a word/line where
↓
frida -U -F com.application.zomato -l frida-android-repinning.js --no-pause

Thanks in advance

**Comment by osousa** [comment]
> @pcipolloni @oleavr @ehsanpc9999
> 
> i too getting the same error on running cmd i.e frida -U -F com.application.zomato -l frida-android-repinning.js --no-pause
> 
> ![new](https://user-images.githubusercontent.com/97558344/154865416-fd61d621-58e8-446c-ac93-f6055944e064.png)
> 
> If i need to add a word/line where ↓ frida -U -F com.application.zomato -l frida-android-repinning.js --no-pause
> 
> Thanks in advance

You took the script from elsewhere other than the official repo, open the js file, and add "var " behind the "cf" variable. 

It will solve your issue guaranteed.
