### ISSUE TITLE
Installing a fixed version of frida-tools does not install a fixed version of frida

### ISSUE THREAD

**Issue by segura2010** [frida/frida#881]
Hi!

Sorry if it is not a bug and is the intended of doing the install..

We have configured a system that installs a fixed version of frida-tools (pip install frida-tools==1.2.2), but frida-tools installs the most recent version of frida instead of the frida version related to the fixed version of frida-tools.

We have fixed our building system by installing the fixed version of frida-tools and then reinstalling the fixed version of frida, but it is not very beautiful...

Our installation commands:
pip install frida-tools==1.2.2
pip install frida==12.2.27

Thank you! :)

**Comment by oleavr** [comment]
The reason is that `frida-tools` depends on features only available in newer versions of Frida. Why are you not using the latest version of Frida? 12.5.3 was released last night with a slew of fixes.

**Comment by segura2010** [comment]
Hi! Thank you for your reply :) 

We are using frida to instrument android malware (extract configs, etc.), we have multiple VMs with frida-server and it is included in the snapshot.. It is hard to update frida since we should update all the VMs and the version we use works fine :)
