### ISSUE TITLE
segmentation fault after execute on android

### ISSUE THREAD

**Issue by mustafairan** [frida/frida#882]
device: galaxy s8 oreo(8) and I am using  frida-server-12.5.4-android-arm64
Could you help?

![image](https://user-images.githubusercontent.com/4804603/57811998-67080000-7774-11e9-8c86-812d8f1c55d7.png)

**Comment by enovella** [comment]
Can you provide the output of `adb logcat` after the crash?

**Comment by mustafairan** [comment]
adn shell logcat *:E

[Uploading androidlogs2.txt…]()

**Comment by mustafairan** [comment]
adb shell logcat *:E

[androidlogs2.txt](https://github.com/frida/frida/files/3185923/androidlogs2.txt)

**Comment by mustafairan** [comment]
I have just tried newest version and saw that issue resolved.
