### ISSUE TITLE
Jailbroken iOS A12/A13 not yet supported

### ISSUE THREAD

**Issue by piaoyunsoft** [frida/frida#885]
$ frida -U -f com.xxxx.xxxx
     ____
    / _  |   Frida 12.5.6 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to spawn: unexpected error while starting thread (act_set_state returned '(os/kern) protection failure')

PiaoPiao-iPhone-XS-Max:~ root# frida-server --version
12.5.6
PiaoPiao-iPhone-XS-Max:~ root# uname -a
Darwin PiaoPiao-iPhone-XS-Max 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:32:01 PST 2018; root:xnu-4903.232.2~1/RELEASE_ARM64_T8020 iPhone11,6 arm64 D331pAP Darwin

iOS12.1.2

**Comment by gokberkince** [comment]
can you fix the problem?

**Comment by rockqj** [comment]
Same issue.

- Frida server version: 12.8.11
- iPhone XR
- iOS 13.3
- Unc0ver V4.0.3

**Comment by capacitor0** [comment]
Same issue, same config but 11 Pro Max

**Comment by oleavr** [comment]
Frida only supports A12/A13 devices in jailed mode for now. Support for jailbroken should be addressed in one of the next releases.

**Comment by nVisium-Alex-Useche** [comment]
I am testing on an A12 device, it appears this only occurs when trying to spawn the process/ using `-f`

**Comment by Squidkingdom** [comment]
@oleavr is this fixed in 12.8.12?

**Comment by oleavr** [comment]
@Squidkingdom No, 12.8.12 was focused on Android-related improvements. Stay tuned.

**Comment by oleavr** [comment]
@nVisium-Alex-Useche Yes, that relies on attaching to `launchd` in order to intercept the `posix_spawn()` call that it makes when launching an app; and `launchd` is a process where PAC is used. The reason you can attach to App Store apps is because it's not yet used for those.

**Comment by oleavr** [comment]
Great news: Frida 12.8.15 is out w/ iOS/arm64e support, both for jailbroken and jailed devices 🎉
