### ISSUE TITLE
Failed to attach: remote_write PTRACE_POKEDATA head failed: 5

### ISSUE THREAD

**Issue by Goldtulip** [frida/frida#889]
Failed to attach: remote_write PTRACE_POKEDATA head failed: 5

Deives：Honor 6X

OS:EMUI 8.0.0
android os 8.0.0
kernel：4.4.23

CPU:hisilicon kirin 655

I have tried to use "magisk resetprop ro.debuggable 1"，and make sure that, AndroidManifest.xml android:debuggable="true". still wrong, Help me~

**Comment by Goldtulip** [comment]
Downgrade to android 7.0, set selinux permissive，solved.

**Comment by yangw1990** [comment]
Hello, can you help me,  I am a novice，I have the same problem, I use the Android simulator, I don’t know what to do next.

**Comment by Goldtulip** [comment]
> Hello, can you help me, I am a novice，I have the same problem, I use the Android simulator, I don’t know what to do next.

Try true device, make sure your device is root, and the app is debuggable and not anti-debug.

**Comment by SergeyAppDroid** [comment]
@Goldtulip Same problem. Can I somehow solve this problem without lowering the version of the android?

**Comment by yangw1990** [comment]
@SergeyAppDroid ，I tried to use real device and already worked

**Comment by SergeyAppDroid** [comment]
@yangw1990 I am using a real device. Huawei 7a pro, Android 8.0.0. But does not work. I use the module for Magisk: MagiskHideProps Config v.2.4.1 and for Xposed: BuildProp Enhancer. Maybe I missed something?

**Comment by Goldtulip** [comment]
> @yangw1990 I am using a real device. Huawei 7a pro, Android 8.0.0. But does not work. I use the module for Magisk: MagiskHideProps Config v.2.4.1 and for Xposed: BuildProp Enhancer. Maybe I missed something?

I feel that huawei is not friendly to developer, try another device or lowering the version.

**Comment by yangw1990** [comment]
> > @yangw1990 I am using a real device. Huawei 7a pro, Android 8.0.0. But does not work. I use the module for Magisk: MagiskHideProps Config v.2.4.1 and for Xposed: BuildProp Enhancer. Maybe I missed something?
> 
> I feel that huawei is not friendly to developer, try another device or lowering the version.

Make the frida and frida-server versions the same and match cpuinfo

**Comment by SergeyAppDroid** [comment]
@yangw1990 Unfortunately, the conditions can not be changed. I read that it is possible to change something with "SELinux permissive". Do you know something about this?

**Comment by yangw1990** [comment]
> @yangw1990 Unfortunately, the conditions can not be changed. I read that it is possible to change something with "SELinux permissive". Do you know something about this?

When I tried the real device, I didn't care about selinux.

**Comment by SergeyAppDroid** [comment]
@yangw1990 

> Make the frida and frida-server versions the same and match cpuinfo

I use the same version of Frida and Frida server: 12.2.30

**Comment by yangw1990** [comment]
> @yangw1990
> 
> > Make the frida and frida-server versions the same and match cpuinfo
> 
> I use the same version of Frida and Frida server: 12.2.30

cat /proc/cpuinfo

**Comment by SergeyAppDroid** [comment]
@yangw1990 
`HWAUM-Q:/ # cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 38.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 38.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 38.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
BogoMIPS	: 38.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 5
BogoMIPS	: 38.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 6
BogoMIPS	: 38.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 7
BogoMIPS	: 38.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
`

**Comment by yangw1990** [comment]
@SergeyAppDroid ,I don't know why your device doesn't see the key information, for example: Processor : AArch64 Processor rev 4 (aarch64)，Then choose x64 or x86

**Comment by SergeyAppDroid** [comment]
@yangw1990 
```
adb shell getprop ro.product.cpu.abi
arm64-v8a
```

**Comment by yangw1990** [comment]
> @yangw1990
> 
> ```
> adb shell getprop ro.product.cpu.abi
> arm64-v8a
> ```

I didn't find “frida-server-12.3.0-Android-arm64.xz”, you should use the new version

**Comment by SergeyAppDroid** [comment]
@yangw1990 

> I didn't find “frida-server-12.3.0-Android-arm64.xz”, you should use the new version

I use the same version of Frida and Frida server: [12.2.30](https://github.com/frida/frida/releases/tag/12.2.30)

**Comment by yangw1990** [comment]
> @yangw1990
> 
> > I didn't find “frida-server-12.3.0-Android-arm64.xz”, you should use the new version
> 
> I use the same version of Frida and Frida server: [12.2.30](https://github.com/frida/frida/releases/tag/12.2.30)

not find “frida-server-12.3.0-Android-arm64”

**Comment by SergeyAppDroid** [comment]
@yangw1990 why 12.3.0?
12.2.30

**Comment by yangw1990** [comment]
> @yangw1990 why 12.3.0?
> 12.2.30

My fault, if so, I am also confused

**Comment by RussiaVk** [comment]
Hi buddys,I tooks 2 day,fix many error to success build kernel for honor 6x(emui8) .You can email huanxiangxr21@gmail.com to get if you need
