### ISSUE TITLE
Android: Error binding to address: Address already in use

### ISSUE THREAD

**Issue by zhangdingding** [frida/frida#89]
Hi, `frida` is really an amazing project :)

But one more thing :( 
When I run `frida-server` in android, it always says:
> Unable to start server: Error binding to address: Address already in use

PS:
* I have installed the latest `frida` on Mac(OS X 10.11) / PC(Ubuntu 15.04)
* I have pushed the latest `frida-server` to Android 4.3 / Android 4.4
* I have run `frida-server` as root user
* I have tried it several times

**Comment by zhangdingding** [comment]
Sorry, I'm afraid the problem due to another frida instance is running.
May I ask you to close this issue? Sorry again :(

**Comment by oleavr** [comment]
No worries at all. Glad to head that! :) Feel free to join #frida on FreeNode by the way.

**Comment by zhangdingding** [comment]
:)
