### ISSUE TITLE
获取构造函数列表(how to get an class of  constructor list by frida)

### ISSUE THREAD

**Issue by zxhubo** [frida/frida#890]
frida中使用如下js： var clz=Java.use("com.example.Test"); var constructor=clz.class.getConstructors(); console.log(constructor.length); var methods=clz.class.getDeclaredMethods(); console.log(methods.length); 为何这里通过getConstructors获取构造函数数组的长度就是undefined，但是通过getDeclaredMethods获取函数，就可以得到正常的长度的呢。 ps:我现在有一个需求就是把所有的构造函数全部得到，所以开始的想法就是通过getConstructors获取，但是发现获取到的constructor并不是一个数组。请问有什么解决办法的吗。
I want to get the constructor list of an class by frida，the code is:
```
var clz=Java.use("com.example.Test");
var constructor=clz.class.getConstructors(); 
console.log(constructor.length); 
var methods=clz.class.getDeclaredMethods(); 
console.log(methods.length);
```
the result, constructor.length is undefined，methods.length is 3. it's said that the result of constructor.length isn't a array,why? or if I want to get the constructor list,how to do ?

**Comment by haidragon** [comment]
how to do ?

**Comment by zxhubo** [comment]
I got it!!!
