### ISSUE TITLE
Atomic spawn-attach-load

### ISSUE THREAD

**Issue by louisabraham** [frida/frida#892]
Hi, I would like to use frida to prevent any non-hooked function call in an app.
Currently, I use the 3 functions spawn, attach and load but there is no guarantee that frida will attach and load the script before any function call is executed.

Is there a better way? And if not, could this be addressed?

**Comment by oleavr** [comment]
This is already supported. `spawn()` spawns the process suspended, and although `attach()` may move execution forward just enough for the libc to be ready (so `frida-agent` can be loaded), it will stay suspended until you `resume()`. Just make sure you `load()` your script before calling `resume()`. However if you need to do something asynchronous, like a `Socket.connect()`, you should expose a `Promise`-returning method through [rpc](https://frida.re/docs/javascript-api/#rpc).

**Comment by oleavr** [comment]
Would recommend writing your agent in TypeScript btw, in which case you can use an `async` function even when using the Duktape runtime (V8 supports it, though, which you can enable through `session.create_script(source, runtime='v8')`). Here's a boilerplate project to get you started:
https://github.com/oleavr/frida-agent-example

Or if you need something a bit more complete:
https://github.com/oleavr/frida-tool-example

Cheers!

**Comment by louisabraham** [comment]
Oh thanks, that explains why I couldn't spawn :)

Is there a doc of the Python API somewhere?
