### ISSUE TITLE
TypeError: cannot read property 'readU8' of null

### ISSUE THREAD

**Issue by erev0s** [frida/frida#893]
Attempting to hook in Android 7 a function in a native `C` library with architecture `x86` and name `myLib.so`. 
Frida version : 12.5.7
**Full error**
~~~~
TypeError: cannot read property 'readU8' of null
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56648)
    at frida/runtime/core.js:386
    at /repl1.js:7
~~~~
The following script in its simplest form.
**script.js**
~~~~
Interceptor.attach(Module.findExportByName('mylib.so', 'decrypt'), {
  onEnter: function (args) {
    console.log("hello")
  },
  onLeave: function () {
  }
});
~~~~
Have also seen [this](https://github.com/frida/frida/issues/830) and [this](https://github.com/frida/frida/issues/818) issues that have a similar issue.  

Additionally attempted to use 
the `findExportByName` but hit the exact same error.
**script.js**
~~~~
    var moduleName = "myLib.so"; 
    var targetFuncAddr = 0x00000f40;
        
    Interceptor.attach (Module.findExportByName (moduleName, "decrypt"), {
	onEnter: function (args) {
		console.log("decrypt called with: ");
            }
	}
    });
~~~~

any idea why this comes up?

**Comment by oleavr** [comment]
It means `Module.findExportByName()` returns `null` because it cannot find the export. Use `Module.getExportByName()` which will throw in that case, giving you a more helpful error to debug.
