### ISSUE TITLE
Unable to hook native C function in android

### ISSUE THREAD

**Issue by erev0s** [frida/frida#894]
Inside the unzipped folder `lib` of the apk i have these
~~~~
├── arm64-v8a
│   └── myLib.so
├── armeabi-v7a
│   └── myLib.so
├── x86
│   └── myLib.so
└── x86_64
    └── myLib.so
~~~~

Currently I am using in an emulator of `genymotion` where I test frida, with architecture x86.  
running `nm --demangle --dynamic myLib.so ` gives amongst other lines the following which is to my interest : `00000f40 T Java_com_example_bigclass_decrypt`  

The code I am using for frida is:
~~~~
Interceptor.attach(Module.getExportByName('myLib.so', 'Java_com_example_bigclass_decrypt'), {
  onEnter: function (args) {
    console.log("hello")
  },
  onLeave: function () {
  }
});
~~~~

result is
~~~~
Error: libj2c.so: unable to find export 'Java_com_example_bigclass_decrypt'
    at frida/runtime/core.js:231
    at /repl1.js:1
~~~~
or if i try only `decrypt` instead of 'Java_com_example_bigclass_decrypt' I have
~~~~
Error: libj2c.so: unable to find export 'decrypt'
    at frida/runtime/core.js:231
    at /repl3.js:1
~~~~

Also I noticed that if i change completely the name of the .so file. For example if my code is the following
~~~~
Interceptor.attach(Module.getExportByName('asdfasdfaasdf.so', 'asdfasdf'), {
  onEnter: function (args) {
    console.log("hello")
  },
  onLeave: function () {
  }
});
~~~~

I get a similar error
~~~~
Error: asdfasdfaasdf.so: unable to find export 'asdfasdf'
    at frida/runtime/core.js:231
    at /repl3.js:1
~~~~

So i guess this means that it does not even find the `.so` file to begin with. What am i doing wrong here or what have i missed?

**Comment by oleavr** [comment]
Is the device-side Frida up-to-date? I.e. 12.5.8 currently.

**Comment by erev0s** [comment]
> Is the device-side Frida up-to-date? I.e. 12.5.8 currently.

I have just updated, and tried again. Results remain the same

**Comment by oleavr** [comment]
Which version of Android is this on?

**Comment by erev0s** [comment]
> Which version of Android is this on?

7.0, API 24

**Comment by oleavr** [comment]
Is the behavior the same with 12.5.7? (In case the change I made yesterday fixed it on Android 9 but broke it on Android 7...)

**Comment by erev0s** [comment]
Yes it is, I have tested so far with `12.5.6`, `12.5.7` and `12.5.8`

**Comment by oleavr** [comment]
Ok, thanks. Could you try building Frida yourself like this:
`make core-android-x86`
(Then transfer `build/frida-android-x86/bin/frida-server` to your device.)

And before doing that, add some temporary logging to [this code](https://github.com/frida/frida-gum/blob/2bdcb9a1bc12cbb64898d066e50268579347be9f/gum/backend-linux/gumandroid.c#L769-L809). You can use `g_info ()` to log, e.g.: `g_info ("trying dlopen() path=\"%s\"", details->path);`. These messages end up in logcat, and should make it clearer what's happening.

**Comment by erev0s** [comment]
ok will do that and report back!

**Comment by erev0s** [comment]
Need to have ndk build `r17b` which is no longer available [here](https://developer.android.com/ndk/downloads/older_releases). Made another dummy app to try a simple printing `hello world` using JNI. This time it finds the function properly but it does not do anything else after that. I put a `console.log("hello")`  in the `onEnter` but it does not even print that.  
  
Could it be that it is an issue on my side (installation/system etc) ?

**Comment by oleavr** [comment]
@erev0s Copy the URL of the latest version, and just change the version part. Old versions are still available.

Btw, did you check that the function is indeed exported? Did you try with `Module.enumerateExports()` to see if it somehow finds the export?

**Comment by erev0s** [comment]
> Btw, did you check that the function is indeed exported? Did you try with `Module.enumerateExports()` to see if it somehow finds the export?

ok so based on that I tried the code below
~~~~
 Module.enumerateExports("myLib.so", {                
      onMatch: function(e) {                            
          if(e.type == 'function') {
		console.log("name of function = " + e.name);

              if(e.name == "Java_com_example_bigclass_decrypt") {
		console.log("Function Decrypt recognized by name");
		Interceptor.attach(e.address, {       
		onEnter: function(args) {         
			console.log("Interceptor attached onEnter...");
			},                                
		onLeave: function(retval){        
			console.log("Interceptor onLeave");
			}                                 
		});                                                                   
              }                   
          }   
      },                                                
      onComplete: function() {}                         
  });  
~~~~

to my surprise it **works** properly and all the `console.log()` are appearing. Maybe the issue lies with `Module.getExportByName`.  I still have not tried to build Frida myself to get some more info.
  
Additionally is there a way to print a variable that is within the `decrypt` function? The `decrypt` function reads a string and does some adjustments to it and then uses that. Is it possible to print this string just before leaving the function, so i would know i have the string after the adjustments?

**Comment by Goldtulip** [comment]
I have the same question On Android 7.0, Frida version:12.6.0.     Module.enumerateExports works well, I use it find the address of the export function, then call Interceptor.attach,:
Interceptor.attach(0x79e962480c, {
        onEnter:function(args){
            console.log('This is OnEnter');
        }
    });
but still have problem:
TypeError: undefined not callable (property 'readU8' of 523606575116)
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:65042)
    at frida/runtime/core.js:386
    at /script1.js:14
    at frida/node_modules/frida-java/lib/vm.js:42
    at E (frida/node_modules/frida-java/index.js:348)
    at frida/node_modules/frida-java/index.js:300
    at frida/node_modules/frida-java/lib/vm.js:42
    at frida/node_modules/frida-java/index.js:280
    at /script1.js:15

**Comment by Goldtulip** [comment]
> I have the same question On Android 7.0, Frida version:12.6.0. Module.enumerateExports works well, I use it find the address of the export function, then call Interceptor.attach,:
> Interceptor.attach(0x79e962480c, {
> onEnter:function(args){
> console.log('This is OnEnter');
> }
> });
> but still have problem:
> TypeError: undefined not callable (property 'readU8' of 523606575116)
> at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:65042)
> at frida/runtime/core.js:386
> at /script1.js:14
> at frida/node_modules/frida-java/lib/vm.js:42
> at E (frida/node_modules/frida-java/index.js:348)
> at frida/node_modules/frida-java/index.js:300
> at frida/node_modules/frida-java/lib/vm.js:42
> at frida/node_modules/frida-java/index.js:280
> at /script1.js:15


I reboot my device ,and push the 12.6.0 frida-server file to my device(ps: I used to use the old server file), now, It works well.

**Comment by erev0s** [comment]
> Ok, thanks. Could you try building Frida yourself like this:
> `make core-android-x86`
> (Then transfer `build/frida-android-x86/bin/frida-server` to your device.)
> 
> And before doing that, add some temporary logging to [this code](https://github.com/frida/frida-gum/blob/2bdcb9a1bc12cbb64898d066e50268579347be9f/gum/backend-linux/gumandroid.c#L769-L809). You can use `g_info ()` to log, e.g.: `g_info ("Trying dlopen() path=\"%s\"", details->path);`. These messages end up in logcat, and should make it clearer what's happening.

ok i did build it and used that instead. It works properly and now and the logs are as they should. I have literally no clue what has changed. So my next test was to try again the already built version and yes it now works. I have not changed anything to the code or anything else in regard to frida. The only thing i changed is i deployed a new device in genymotion and have made updates to my system. I do not know how relevant these could be but it is weird. Now everything works.

I have one more question if there is a way to print a variable that is within the decrypt function? The decrypt function reads a string and does some adjustments to it and then uses that. Is it possible to print this string just before leaving the function, so i would know i have the string after the adjustments?
