### ISSUE TITLE
No Javascript Set?

### ISSUE THREAD

**Issue by bannsec** [frida/frida#895]
I'm attempting to create a `Set` object, but i can't seem to do so. Frida keeps telling me it has no idea what a set is.

On a similar note, I also have tried to use `Array.includes` but that is similarly not present.

**Comment by oleavr** [comment]
You either need to use our V8-based runtime – i.e. `session.create_script(source, runtime='v8')` – or use [frida-compile](https://github.com/oleavr/frida-agent-example) configured to use Babel (the default) to compile the code to ES5.
