### ISSUE TITLE
frida brida 'ascii' codec can't encode characters in position 109-112

### ISSUE THREAD

**Issue by mr-m0nst3r** [frida/frida#899]
@oleavr Hey there,

I met a problem using `brida`, and posted an issue there, https://github.com/federicodotta/Brida/issues/34,

After looking into the problem, it seems to be frida's problem.

Would you like to take a look?

Thank you.

**Comment by oleavr** [comment]
Hi. No I'm already overloaded with work, but PRs welcome.
