### ISSUE TITLE
Unable to find executable

### ISSUE THREAD

**Issue by Reversive** [frida/frida#903]
If I try to spawn a process with frida (`frida -f com.xxx.xxxx`), i'm getting this error as stated in the title `Failed to spawn: unable to find executable at 'com.xxx.xxxx'`.

My guess is that it might be related to permissions? If i use dwarf i can spawn process with no trouble at all.

**Comment by oleavr** [comment]
Try adding `-U`. The command-line you mentioned tries to spawn an app on your local system, where spawning apps is probably not supported. (Unless you're running `frida` on an Android or iOS device.)

**Comment by anvarkh** [comment]
Run frida -U -f package_name

**Comment by fellipgomes** [comment]
> Run frida -U -f package_name

thank you!

**Comment by danishaziz-8** [comment]
if i am running with any JavaScript it did not spawning still persists.
