### ISSUE TITLE
FREEZING AND CRASHING ON ONEPLUS7 PRO OOS

### ISSUE THREAD

**Issue by Juxstin** [frida/frida#908]
FREEZING AND CRASHING ON ONEPLUS7 PRO OOS ON LATEST FRIDA SERVER ARM64

**Comment by iGio90** [comment]
Thanks! super helpful!

**Comment by Juxstin** [comment]
> Thanks! super helpful!

Explain how i'm spost to post logs when insta freezes and crashes

**Comment by iGio90** [comment]
logcat? gdb?

**Comment by Juxstin** [comment]
> logcat? gdb?

Did mention makes my device extremely hot not risking man i can't burn a 800$ phone
