### ISSUE TITLE
repl python import issue with prompt-toolkit

### ISSUE THREAD

**Issue by superkhung** [frida/frida#91]
with current version (0.57) of prompt-toolkit, there's no create_default_application() and create_default_output(), import should be change from
```python
from prompt_toolkit.shortcuts import create_default_application, create_default_output, create_eventloop
```
to
```python
from prompt_toolkit.shortcuts import create_prompt_application, create_output, create_eventloop
```

**Comment by oleavr** [comment]
Thanks! Is this the only issue on the newer prompt-toolkit? (I didn't have time to investigate this so I ended up just locking the version to 0.38.)

**Comment by superkhung** [comment]
i think it's all, still using repl without any error after import fixed

**Comment by oleavr** [comment]
Sweet! Feel like submitting a PR with this change and bumping the version requirement in setup.py?
