### ISSUE TITLE
Problems with Passionfruit when starting Frida manually

### ISSUE THREAD

**Issue by sushi2k** [frida/frida#911]
Please see the issue in Passionfruit https://github.com/chaitin/passionfruit/issues/49

TLDR:

When adding the Frida repo to Cydia and installing and using Frida like this, instead of copying the Frida binary manually via SSH an executing it on the iOS device passionfruit works. 

What is the difference when installing Frida via Cydia compared to starting the binary manually?

**Comment by oleavr** [comment]
The difference is that the .deb uses launchd to manage the daemon's lifetime. The [package-server.sh](https://github.com/frida/frida-core/blob/a37515462d792dcade5c7b567c2e70633a400107/tools/package-server.sh) script explains the details.
