### ISSUE TITLE
remote_write PTRACE_POKEDATA head failed

### ISSUE THREAD

**Issue by xiaofengtongxue** [frida/frida#914]
Hi
<img width="816" alt="屏幕快照 2019-06-06 下午5 40 23" src="https://user-images.githubusercontent.com/17273994/59023402-51bd5780-8882-11e9-8cab-0662a733a089.png">
<img width="539" alt="屏幕快照 2019-06-06 下午5 38 21" src="https://user-images.githubusercontent.com/17273994/59023518-91843f00-8882-11e9-8d02-566c0cc6962e.png">
<img width="828" alt="屏幕快照 2019-06-06 下午5 41 08" src="https://user-images.githubusercontent.com/17273994/59023553-a2cd4b80-8882-11e9-9257-f6814c4312ac.png">

error：remote_write PTRACE_POKEDATA head failed: 5

**Comment by sheldoncoupeheure** [comment]
There are two possibilities:
1. Another software is already debugging your app
2. SELinux is messing with Frida

In a root shell on your device, try executing `setenforce 0` (not persistent accross reboots)
Try killing your app manually with `am force-stop <your.package.name>`

**Comment by sheldoncoupeheure** [comment]
There are two possibilities:
1. Another software is already debugging your app
2. SELinux is messing with Frida

In a root shell on your device, try executing `setenforce 0` (not persistent accross reboots)
Try killing your app manually with `am force-stop <your.package.name>`

**Comment by oleavr** [comment]
Also make sure you try Frida 12.6.7, released last night. One of the issues it fixes has this exact symptom.
