### ISSUE TITLE
readS64() is str??

### ISSUE THREAD

**Issue by bannsec** [frida/frida#916]
Looks like there's an inconsistency in information returned from `Pointer.read<x>`. Specifically see the following:

```
[Local::notepad.exe]-> var p = ptr(0x35dddfcd40)
undefined
[Local::notepad.exe]-> p.readS8()
0
[Local::notepad.exe]-> p.readS16()
0
[Local::notepad.exe]-> p.readS64()
"0"
[Local::notepad.exe]-> p.readS32()
0
```

Both `readS64` and `readU64` return a string value, where the rest of the reads return int. This causes processing confusion since now we have to handle the special case of if the value returned is an int or str.

**Comment by oleavr** [comment]
It's not a string, it's a `Int64` or `UInt64` instance. Similar API as `NativePointer`. You can call `.valueOf()` to turn it into a `number` regardless of whether it's already a `number` or a boxed value. However, you should then be sure there's no risk of losing data, as `number` is backed by a `double`. V8 supports bigint however, but Duktape does not, so we cannot use that just yet.
