### ISSUE TITLE
64-bit write->read test fails

### ISSUE THREAD

**Issue by bannsec** [frida/frida#917]
Seeing a write->read test failing for me. Here's an example:

```
[Local::notepad.exe]-> p.writeS64(-9141729569757443772)
"0x7ffd00762000"
[Local::notepad.exe]-> p.readS64()
"-9141729569757444096"
```

This was first discovered via some python things i'm working on. I tried setting `runtime='v8'` in my script creation, but it didn't seem to affect this behavior.

**Comment by bannsec** [comment]
It's also inaccurate with unsigned 64-bit

```
[Local::notepad.exe]-> p.writeU64(6853490166805307081)
"0x7ffd00762000"
[Local::notepad.exe]-> p.readU64()
"6853490166805307392"
```

In both cases, the numbers differ by a bit over 300...

**Comment by oleavr** [comment]
You are passing a JavaScript `number` instead of a `Int64` or `UInt64`. This is exactly why those exist. Use the `int64()` and `uint64()` short-hands to create such values, passing a string with the value.

**Comment by oleavr** [comment]
To clarify:

```
p.writeS64(int64('-9141729569757443772'));
```

Same story with pointers: never use JavaScript number values, use the `ptr()` short-hand passing it a string with the pointer value.

**Comment by bannsec** [comment]
ahh ok, that makes sense. Thanks!
