### ISSUE TITLE
Failed to enumerate applications: unable to connect to remote frida-server: closed

### ISSUE THREAD

**Issue by xteraflopx** [frida/frida#92]
Following this tutorial: http://www.frida.re/docs/android/

I get the error from running the command frida-ps -U

I have a rooted Droid 4 running 4.1.2

I don't even know what the heck frida-server is, because I pushed it to my phone but it doesn't look like an APK or anything.

**Comment by oleavr** [comment]
It's a daemon that you need to start manually. Is `frida-server` running as root?

**Comment by xteraflopx** [comment]
I don't even know how to run frida-server whatsoever. I was following the instructions

$ curl -O https://build.frida.re/frida/android/arm/bin/frida-server
$ adb push frida-server /data/local/tmp/
$ adb shell "chmod 755 /data/local/tmp/frida-server"
$ adb shell "/data/local/tmp/frida-server &"

Is the last command running frida-server? I do have a rooted phone, but I don't know how to start frida-server as root.

Sorry for my ignorance

**Comment by oleavr** [comment]
No worries. That example will work great with an emulator, but for a rooted device you probably want to copy the binary to the device just like in those instructions, and then do something like:

```
$ adb shell
# su
# /data/local/tmp/frida-server &
```

**Comment by xteraflopx** [comment]
Thank you!

Running "frida-ps -U -i open com.android.chrome" gave me an error that permission was denied, or something similar, and after running "sudo sysctl kernel.yama.ptrace_scope=0" now Chrome just closes every time I try to attach to it.

**Comment by oleavr** [comment]
Is this still reproducible with Frida 6.2.1?

**Comment by xteraflopx** [comment]
@oleavr I'll download the new version and try out the tutorial to see if I can get it working.

**Comment by xteraflopx** [comment]
@oleavr With your most recent version of Frida, running on my rooted DROID 4 (Android 4.1.2), when trying to run:

frida-trace -U -i open com.android.chrome

I get the output:

Failed to start tracing: the connection is closed                       
Stopping...

It causes the app to close on my phone. This happens for nearly every app I attempt to attach to, except a few boring looking system apps like "zygote"

**Comment by youdy3000** [comment]
Hi @oleavr @xteraflopx 

I hit the same thing on Android.  I got the Process IDs listing perfectly on iOS but not on Android.  I was using 6.2.4 version of Frida.

I manually adb shelled into my device. Elevated myself to root. Went into the same directory you mentioned; /data/local/tmp/  I made sure the Frida Server was chmod 755.  

I can see the Frida server is running.  But it is the only process that is being listed.  I have multiple apps open.

Thoughts?

PS (I can attach to a PID on iOS, without issue).

**Comment by samitanwer** [comment]
Hi, 

I am facing the same issue. I am successfully able to run frida-server on my rooted android device (6.0.1, arm), however, when I try to run: "frida-ps -U", I get only one process listed, viz the frida-server process itself and when I run: "frida-ps -R, I get the message - "unable to connect to remote frida-server"

Frida version on my host is 7.1.0 and frida-server version on my phone is 7.0.11

Any solution to this, yet?

**Comment by samitanwer** [comment]
Also running "frida-ps -Uai open com.android.chrome" gives an error stating "java API not available"

**Comment by filipesam** [comment]
Hello, 
I'm having the same issue, i have a rooted phone, cydia and struff installed, upgraded to the last version of frida (/usr/sbin/frida-server --version shows: 7.2.15)

Everytime i try to connect to the device via USB i get the message: 
"Failed to enumerate applications: unable to connect to remote frida-server"

I've checked the apple systemd logs, and found that the frida-server is crashing everytime i try a connection.
I've attached a crashreport for you guys to check.

Thanks, and great work on frida
(crashreport from /Library/Logs/CrashReporter/frida-server_2016-07-27-104012_Flips-iPhone.ips)

[frida-crash.txt](https://github.com/frida/frida/files/385770/frida-crash.txt)

**Comment by olifozzy** [comment]
Same error here :/

**Comment by oleavr** [comment]
@filipesam Please try 7.2.24. This issue should be resolved.

**Comment by filipesam** [comment]
Thanks, for the update, it's working now in the iphone
Thanks, and keep up the great work!

**Comment by tecolee99** [comment]
I tired the frida-server (v8.2.2) on my Acer S500 phone. The Apps crash while i tried to attached it by frida-trace -R ..com.supercell.clashroyale., the crash message is shown in below.

[crash.txt](https://github.com/frida/frida/files/638658/crash.txt)

**Comment by anka-213** [comment]
I have the same problem with frida 8.2.3 on a rooted android phone (). :/
I can start the server just fine and it keeps running, but I cannot connect to it 

Model: GT-I9100
Android-version: 4.1.2
Kernel version: 3.0.31-Siyah-s2-v6.0b4+

**Comment by baptx** [comment]
I got this error when trying to list processes of Android x86 running in VirtualBox (bridged adapter network) on a Linux host. The solution was to give the IP address of Android to frida-server with -l parameter so it will listen on it. But it looks like a bug since the server should know its own IP address.

**Comment by imran209** [comment]
Hi,
@oleavr I was setting up Frida-server on the android rooted device and do all these steps
$ adb push frida-server /data/local/tmp/
$ adb shell "chmod 755 /data/local/tmp/frida-server"
$ adb shell "/data/local/tmp/frida-server &"

tools>adb shell /data/local/tmp/frida-server &
/system/bin/sh: /data/local/tmp/frida-server: can't execute: Is a directory

and also the following
$ adb shell
# su
# /data/local/tmp/frida-server & but it is showing this error
"root@kenzo:/ # /data/local/tmp/frida-server &
[2] 7962
[1] - Done (126)           /data/local/tmp/frida-server
sush: /data/local/tmp/frida-server: can't execute: Is a directory"

Please let me know how to solve this.

Regards,
Imran

**Comment by baptx** [comment]
@imran209 here is the command I used to start frida-server: `adb shell "su 0 /data/local/tmp/frida-server -l 0.0.0.0" &`.
Maybe you also need to do `chmod +x frida-server` before executing it.

**Comment by imran209** [comment]
> @imran209 here is the command I used to start frida-server: `adb shell "su 0 /data/local/tmp/frida-server -l 0.0.0.0" &`.
> Maybe you also need to do `chmod +x frida-server` before executing it.
> Link to your issue for reference: #1269

@baptx I tried the command which you shared but now worked, same above error msg.

**Comment by BinhMinhptit** [comment]
when i run frida-ps -U it returns: 
`# frida-ps -U 
Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually`
i started fridaserver using root@vbox86p:/data/local/tmp # ./frida-server-32 &                             
[1] 2547

any help?

**Comment by Cyberlock420** [comment]
some one please help me I am getting this issue unable to resolve:
Failed to attach: unable to connect to remote frida-server: closed

**Comment by crifan** [comment]
* Environment
  * PC: Mac M2 Max, macOS 13.2.1
    * installed: `frida v16.1.3`
  * Device: Android phone: `Google Pixel 3`
    * installed `frida-server v16.1.3`
* Error 
  * Mac: 
```bash
➜  frida frida-ps -U
Failed to enumerate processes: connection closed
➜  frida frida-ls -U
Failed to retrieve listing: unable to connect to remote frida-server: closed
```
* Solution
  * use [magisk-frida](https://github.com/ViRb3/magisk-frida)
    * instead of official frida-server (frida-server-16.1.3-android-arm64)
    * Steps: 
      * download [MagiskFrida-16.1.3-1.zip](https://github.com/ViRb3/magisk-frida/releases/download/16.1.3-1/MagiskFrida-16.1.3-1.zip) to Android phone ( Download folder)
      * Magisk->Module->Install from local disk -> choose and click MagiskFrida-16.1.3-1.zip -> install done -> reboot
