### ISSUE TITLE
Failed to attach:unable to inject library into process without libc.

### ISSUE THREAD

**Issue by summary-GodBlessYou** [frida/frida#936]
Python:3.7.3
frida-12.6.8
When the program is run, the following exception occurs:
Failed to attach: unable to inject library into process without libc.
Does anybody know what to do with it?

**Comment by guapier** [comment]
me too

**Comment by hongjian812** [comment]
me too, unable to inject library into process without libc.

**Comment by guapier** [comment]
Maybe the version is not right or you use the phone simulator, I use the nexus 6p  and  the frida version is 12.4.8 solve this problem

**Comment by srcdes** [comment]
You should use ABI-matched `frida-server`.

**Comment by GouveaHeitor** [comment]
Any update here?

**Comment by GouveaHeitor** [comment]
@oleavr can you help us?

**Comment by dilbertford** [comment]
@GouveaHeitor I was also experiencing the same problem, which seems to not be related to the mobile application I am testing. If you urgently need to get `frida-server` working, you can try a previous version. For me, I went back to version `12.7.4`, with a nexus 6p (although it is likely the device and version of Android do not matter) and the issue went away. For me, I tried both `12.7.8` and `12.7.9` and kept experiencing issues with both `x86` and `x86_64` where I'd receive an 

> unable to inject library into process without libc.

 Hope this [workaround](https://github.com/frida/frida/releases/tag/12.7.4), of going back a few versions helps you until a fix or resolution can be provided.

**Comment by twelveand0** [comment]
> @GouveaHeitor I was also experiencing the same problem, which seems to not be related to the mobile application I am testing. If you urgently need to get `frida-server` working, you can try a previous version. For me, I went back to version `12.7.4`, with a nexus 6p (although it is likely the device and version of Android do not matter) and the issue went away. For me, I tried both `12.7.8` and `12.7.9` and kept experiencing issues with both `x86` and `x86_64` where I'd receive an
> 
> > unable to inject library into process without libc.
> 
> Hope this [workaround](https://github.com/frida/frida/releases/tag/12.7.4), of going back a few versions helps you until a fix or resolution can be provided.

@dilbertford This works for me. Thanks!

**Comment by PhoneTester** [comment]
@dilbertford Thank you very much, I've spent 10 hours trying to figure out what have I done wrong. It helped.

**Comment by GouveaHeitor** [comment]
Thx @dilbertford!! This works for me!

**Comment by dilbertford** [comment]
@GouveaHeitor @PhoneTester @twelveand0 awesome guys! Nothing makes me feel better than being able to help alleviate some frustration. Have a good one!

**Comment by oleavr** [comment]
Fixed in 12.7.11, released earlier today. A recent change turned out to be a can of worms. Sorry for the trouble!

**Comment by AntonKukoba1** [comment]
Having the same issue on frida-server-12.8.6-android-arm

**Comment by danilobasanta** [comment]
Same problem on frida 12.8.9

**Comment by ravifogat** [comment]
Same here


frida -U -f com.xxxxxx -l ssl-pin.js --no-pause
     ____
    / _  |   Frida 12.8.10 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to spawn: unable to inject library into process without libc

**@oleavr please help**

**Comment by ErwanLegrand** [comment]
This can happen if libc was updated on the filesystem after the target process was started. In that case, the version of libc mapped by the process is not the same as the one found in the file hierarchy.

**Comment by dillonfranke** [comment]
I agree with @ErwanLegrand! Restarted my webserver and was able to attach to the process without the `libc` error.

**Comment by benquike** [comment]
Hi, 

I am trying to use frida-server 15.1.17 on Pixel 6 Pro (running Android 12), and  trace a system service (pid 13) 
using the following command:

```
frida -D 21191FDEE002BE -p 13 -e "Process.enumerateModules();"
     ____
    / _  |   Frida 15.1.17 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Pixel 6 Pro (id=21191FDEE002BE)
Failed to attach: unable to inject library into process without libc    
```
Any hint on how to solve it?

**Comment by YSaxon** [comment]
This is pretty niche I'm sure, but I'll just note that it can also happen if you start the frida-server from a different chroot than the process itself is in.

**Comment by YSaxon** [comment]
More precisely, it seems to depend on which `libc.so.6` is imported by the target process. You can use `ldd` to see which one Frida and the target are using respectively, and then make a softlink or adjust LD_LIBRARY_PATH to ensure they are using the same one.
