### ISSUE TITLE
Hook functions obfuscated with non-printable unicodes

### ISSUE THREAD

**Issue by xVERSUSx** [frida/frida#945]
Hi,
I want to hook a Java function that is named using non-printable unicodes. This function is also inside of a class called using the same technique.

I tried to use scaped unicodes like below:
```
Java.perform(function () { 
   const clazz = Java.use("\u086b.\u0863\u0865"); 
   clazz.\u1ace\u1ad3\u1ac2.implementation = function(a) { 
      //Do something
   }
});
```
I face two errors when I try t execute this code: 
- The class cannot be found, and therefore the variable `clazz` is undefined.
- The identifier of the hooked function is not valid. I receive the syntax error "invalid escape".

What is the proper way to hook this type of classes and functions?

Thank you.

**Comment by enovella** [comment]
Can I see the APK? This is possible and you seem to do it in the right way. Maybe you class definition is wrong.

**Comment by xVERSUSx** [comment]
Hi @enovella,

Unfortunately, I cannot disclose the APK since it is part of a project. However, I have an script to convert packages and Smali files names to escaped unicodes, and they match with the names given by tools such as JADX or BytecodeViewer when I decompile the classes.dex file with them, so I think that the package and class names are correctly escaped.

I have also tried to list the loaded classes using Frida, and then use a variable to name the class in the `Java.use` statement, but I still have the same problem.

**Comment by Nightbringer21** [comment]
I have a similar issue that I don't seem to find the solution.

I am using directly the REPL and loading the .js script. I have tried all other solutions that I could find on open issues but don't seem to work (including using a Unicode value or loading it through Python and using codecs to convert the script to UTF8). The code is below:

```
Java.perform(function () {
   var TestActivity = Java.use("com.test.TestActivity");
      TestActivity.כ⠋כ.implementation = function ()
      {\n
        console.log("[*] Entered TestActivity.כ⠋כ");
      };
});
```

Error:

```
Failed to load script: gDBus.Error:re.frida.Error.InvalidArgument: Script(line 16): SyntaxError: invalid token 
```
Using the Unicode escaped line as below, leads to a different error:
```
...
TestActivity.\u05DB\u280B\u05DB.implementation = function ()
...
```
Error:
```
Failed to load script: gDBus.Error:re.frida.Error.InvalidArgument: Script(line 13): SyntaxError: invalid escape
```

Any suggestions highly appreciated.

**Comment by oleavr** [comment]
Instead of `clazz.foo`, do `clazz['foo']` – strings may contain any unicode character.

**Comment by Nightbringer21** [comment]
Thanks for the response @oleavr. This works for hooking the implementation, I keep forgetting that you can treat the method as an array to pass the method.

To return the original value of the method, usually I would call this.foo(a,b). I have tried to call directly this.class['foo'](a,b), which I would expect to be working, however I am getting undefined instead. 

Any suggestions if this is correct and I have some other issue in my implementation or if I am missing something?

**Comment by oleavr** [comment]
@Nightbringer21 You have to use `.call()` or `.apply()` to specify the correct `this`. The recommended way is:

```
const foo = klass['foo'];
foo.implementation = function (a, b, c) {
  return foo.call(this, a, b, c);
};
```

**Comment by Rackme** [comment]
> Hi @enovella,
> 
> Unfortunately, I cannot disclose the APK since it is part of a project. However, I have an script to convert packages and Smali files names to escaped unicodes, and they match with the names given by tools such as JADX or BytecodeViewer when I decompile the classes.dex file with them, so I think that the package and class names are correctly escaped.
> 
> I have also tried to list the loaded classes using Frida, and then use a variable to name the class in the `Java.use` statement, but I still have the same problem.

@xVERSUSx hooking on methods with unicode character (even printable #806 ) didn't work for me nether, such script could help, is there any chance you'd share it?
