### ISSUE TITLE
Issue for iOS without Jailbreak

### ISSUE THREAD

**Issue by sendwave** [frida/frida#95]
I had downloaded the latest FridaGadget.dylib and added into my demo Xcode app, build and deployed to my iPhone, but it crashed when launching the dylib:

dyld`dyld_fatal_error:
->  0x1fef508c <+0>: trap   
    0x1fef5090 <+4>: nop  

dyld: Library not loaded: @executable_path/Frameworks/FridaGadget.dylib
  Referenced from: /var/mobile/Containers/Bundle/Application/D836EAFA-97E8-416E-A55B-58FD5536AFA2/testLoginView.app/testLoginView
  Reason: no suitable image found.  Did find:
	/var/mobile/Containers/Bundle/Application/D836EAFA-97E8-416E-A55B-58FD5536AFA2/testLoginView.app/Frameworks/FridaGadget.dylib: mmap() errno=1 validating first page of '/var/mobile/Containers/Bundle/Application/D836EAFA-97E8-416E-A55B-58FD5536AFA2/testLoginView.app/Frameworks/FridaGadget.dylib'
	/private/var/mobile/Containers/Bundle/Application/D836EAFA-97E8-416E-A55B-58FD5536AFA2/testLoginView.app/Frameworks/FridaGadget.dylib: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/D836EAFA-97E8-416E-A55B-58FD5536AFA2/testLoginView.app/Frameworks/FridaGadget.dylib'

Could you please help me?
Thanks a lot!

**Comment by ballballsun** [comment]
Should be problem on project setting, try to see:
http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta
