### ISSUE TITLE
crash on OnePlus 7 when attaching

### ISSUE THREAD

**Issue by epiciskandar** [frida/frida#952]
android version 9(Hydrogen OS 9.5.6.GM57)
frida crashes on any app when attaching with frida -U.
as logcat says:
E *** denied {map} for path='path/to/frida_server' ***
with tombstone file, could found such string near r3 register:
dlsym failed: library handle is null.ida server/frida-agent-32.so" phdr mmap failed: Permission denied

tombstone file is attached
[tombstone_09.txt](https://github.com/frida/frida/files/3377406/tombstone_09.txt)

**Comment by Juxstin** [comment]
setenforce 0 should fix temporarily

**Comment by epiciskandar** [comment]
setenforce 0 works, thanks!
