### ISSUE TITLE
Failed to attach to a game process (Android)

### ISSUE THREAD

**Issue by ballballsun** [frida/frida#96]
Hi, I am trying frida to look into an android game.
I have written a simple code in file named "f_test.py":
```
import frida
session = frida.get_usb_device().attach("com.games.game")
print([x.name for x in session.enumerate_modules()])
```
but get this result:
```
Traceback (most recent call last):
  File "f_test.py", line 3, in <module>
    session = frida.get_usb_device().attach("com.games.game")
  File "/Library/Python/2.7/site-packages/frida-6.0.5-py2.7-macosx-10.9-intel.egg/frida/core.py", line 87, in attach
frida.TransportError: unable to access process with pid 2790 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root
```
if I change ```attach("com.games.game")``` to ```attach("com.facebook.katana")```, then I am able to see the result. 
```
[u'libz.so', ...., u'libfb_filesystem.so', u'frida-agent-32.so']
```

I tried to run the suggested command ```sudo sysctl kernel.yama.ptrace_scope=0``` on Mac & android. But get the following result:
Mac: ```sysctl: unknown oid 'kernel.yama.ptrace_scope'```
android: ```tmp-mksh: sudo: not found```

I have no idea why, can anyone help me?

Device info:
Nexus7 2012 Android 4.4.4
Mac OSX EI Capitan 10.11.2

**Comment by oleavr** [comment]
Hi,

Is your frida-server on Android running as root?

**Comment by ballballsun** [comment]
Yes it is should be running as root. I followed your instruction in https://github.com/frida/frida/issues/92
```
$ adb shell
# su
# /data/local/tmp/frida-server &
```
It is strange that I can attach to other game process, but only Line Ranger cannot.
Maybe the game is protected?

The game i am trying is Line Ranger, you can try it.
https://play.google.com/store/apps/details?id=com.linecorp.LGRGS

**Comment by oleavr** [comment]
Ahh yes, that must be the reason then. It's currently very easy to block us on Android/Linux because we rely on `ptrace()` for the short moment where the injection happens. But, you can use Frida to spawn their app, and easily sabotage any anti-debug tricks they may have from the inside.

**Comment by ballballsun** [comment]
Oh ic, thanks a lot!!! I will try it.
By the way, is there are any command to restart/shutdown frida server on android?

**Comment by oleavr** [comment]
Np! No, you have to kill it yourself.

**Comment by ChaplinLi** [comment]
May I ask how to use Frida to spawn theri app?I don't konw what's that mean.

**Comment by henrymark92** [comment]
@oleavr  I have same this problem
I did  step by step of android example (https://www.frida.re/docs/examples/android/) and got a error.
```
Traceback (most recent call last):
  File "D:/source/App/test.py", line 58, in <module>
    session = frida.get_usb_device().attach("com.example.seccon2015.rock_paper_scissors")
  File "C:\python32\python-2.7.10\lib\site-packages\frida\core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: timeout was reached

Process finished with exit code 1

```
+ When I use debug then I saw a process of example app

![capture](https://user-images.githubusercontent.com/4132665/35195744-8f6aa456-fefa-11e7-8c18-685b8de0ffc4.PNG)

Device Info:
+Bluestack
 +Android version 4.4
+Win 10

**Comment by oleavr** [comment]
@henrymark92 Your issue has been fixed in Frida 10.6.39, currently being released. Cheers!

**Comment by henrymark92** [comment]
@oleavr . Please check example again(https://www.frida.re/docs/examples/android/)). I had tested with genymotion emulator and got crash when click button R
Thanks

**Comment by henrymark92** [comment]
Hi all.
I have same issue on this emulator
http://www.mediafire.com/file/chzx2cymbvyj5l6/BlueStacks+App+Player+0.9.24.5311+Superuser+BSEasy+-+bo+2.msi

**Comment by oleavr** [comment]
@henrymark92 Emulators like BlueStacks App Player are not supported – they run the JNI code in an ARM emulator, and our hooking logic isn't compatible with that. It's a non-trivial fix, so this won't be fixed unless somebody contributes support for it at some point.

**Comment by henrymark92** [comment]
hi @oleavr Do you know which emulator working well with frida?
Thanks

**Comment by mr-m0nst3r** [comment]
Hey guys,

I met this problem because I installed `Magisk`, which is similar like `SuperSU`, but `Magisk` made `adb root` not possible, and got error like `adbd can't run in production mode`.

Just reflash your boot.img, and install SuperSU instead, and before using frida, do `adb root` so the you're root by default when entering shell, no need to issue `su` command to get root.

Hope this helps.

**Comment by summary-GodBlessYou** [comment]
run frida:
`Failed to attach: unable to inject library into process without libc.`
I don't know why

**Comment by srcdes** [comment]
@summary-GodBlessYou You should use appropriate `frida-server`(x86 or arm, etc) binary for your device.

**Comment by RoyalFlushever** [comment]
Downgrade your frida-server version on your android devices.
For example, if you have frida-version 10.6.32 on your PC, you can install frida-server 10.0.X.
Note: only master version should match between frida-server and frida.
