### ISSUE TITLE
How to access this object?

### ISSUE THREAD

**Issue by JonaHunt** [frida/frida#968]
I have the following hook

```
Java.perform(function() {
     var test = Java.use('hello.world');
     test.test2.overload('int').implementation = function(arg0) {
          console.log(this);
     return this.test(arg0);
}
```

this yields

> {$handle: '0x2345', '$weakRef': 283}

I know there are data in the object that I'm looking for.

How do I access it?

**Comment by MY201314MY** [comment]
I have the same problem, have you solved it now ?
