### ISSUE TITLE
Multiple issues with build

### ISSUE THREAD

**Issue by alxchk** [frida/frida#97]
```
make[2]: Entering directory '/tmp/frida/build/tmp-linux-x86_64/frida-core/src'
  GEN      frida-data-agent.c
  CC       frida-data-agent.lo
  CPPAS    frida-data-agent-blob.lo
  CCLD     libfrida-data-agent.la
  GEN      frida-data-helper-process.c
  CC       frida-data-helper-process.lo
  CPPAS    frida-data-helper-process-blob.lo
  CCLD     libfrida-data-helper-process.la
  CC       linux/libfrida_core_la-linux-host-session.lo
../../../../frida-core/src/linux/linux-host-session.c:16:31: fatal error: frida-data-loader.h: No such file or directory
 #include <frida-data-loader.h>
```

Same problem with frida-data-android.h

Also pkg-config wasn't used to detect json-glib/json-glib.h location:
```
  CC       linux/libfrida_core_la-linux-host-session.lo
../../../../frida-core/src/linux/linux-host-session.c:19:33: fatal error: json-glib/json-glib.h: No such file or directory
 #include <json-glib/json-glib.h>
```
```
# pkg-config --cflags json-glib-1.0 
-pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
```
Same behaviour on Debian Jessie and Gentoo

**Comment by alxchk** [comment]
Also:

make[5]: Entering directory '/tmp/frida/build/tmp-linux-x86_64/frida-python2.7/src'
  CC       _frida.lo
  CCLD     _frida.la
/tmp/frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-linux-host-session.o): In function `frida_robo_launcher_construct':
/tmp/frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linux-host-session.c:4621: undefined reference to `frida_data_loader_get_frida_loader_32_so_blob'
/tmp/frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linux-host-session.c:4623: undefined reference to `frida_data_loader_get_frida_loader_64_so_blob'
/tmp/frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-linux-host-session.o): In function `frida_robo_agent_construct':
/tmp/frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linux-host-session.c:7415: undefined reference to `frida_data_android_get_robo_agent_js_blob'
/tmp/frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-frida-helper-process.o): In function `frida_resource_store_construct':
/tmp/frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/frida-helper-process.c:3693: undefined reference to `setfilecon'
/tmp/frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-linjector.o): In function `frida_agent_resource_get_path_template':
/tmp/frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linjector.c:1031: undefined reference to `setfilecon'
/tmp/frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linjector.c:1116: undefined reference to `setfilecon'

**Comment by oleavr** [comment]
Hi,

Are you using the toplevel Makefile.<build-os>.mk or are you trying to invoke configure/make/etc. directly in the different submodules?

**Comment by alxchk** [comment]
Toplevel, default one.
```
# make ANDROID_NDK_ROOT=/opt/android-ndk NODE=/usr/bin/node NPM=/usr/bin/npm server-android python-64 server-64 server-32
```
Something like that.

**Comment by oleavr** [comment]
Ahh! We currently have an issue where the build system's generation of Vala code only happens once, so the preprocessor defines there will be processed only once. This is something I've been wanting to fix, but haven't found the time to do it yet. So for now you will have to `make clean` between building for Linux (typically your host) and building for Android, or clone the repo twice.
