### ISSUE TITLE
Hooking method from list of strings

### ISSUE THREAD

**Issue by brian-leidos** [frida/frida#973]
Javascript API, I can do this: 
var classToHook = "java.lang.String"; 
var classDef = Java.use(classToHook); 
var overload = classDef.toString.overload(); 
overload.implementation = function() { ... } 

How could I hook the toString method, if it was specified as a  string, so, instead of hard-coding the toString method above, I had a  more generic function: 
var classToHook = "java.lang.String"; 
var methodToHook = "toString";     // <<==== for simplicity 
var classDef = Jave.use(classToHook); 
var overload = classDef.***** how can i use "methodToHook" here *****
overload.implementation = function() { ... }

**Comment by Rackme** [comment]
Have you tried 
var overload = classDef[methodToHook] ?

**Comment by brian-leidos** [comment]
obe, took a different approach
