### ISSUE TITLE
Chat about Frida?

### ISSUE THREAD

**Issue by gilamran** [frida/frida#979]
Hi,
I started working with Frida not long ago, and I've been struggling with the documentation.
I will surely contribute to the docs, once I firmly understand what I'm doing...
So, in order to get better at "Friding" I need someone who knows Frida internals, someone who can answer my questions... 
Is there any place that people chat about Frida? Gitter? IRC channel? Slack? 

Thanks

**Comment by dweinstein** [comment]
@gilamran there's a telegram (https://telegram.me/fridadotre), but I can also invite you to a nowsecure-oss slack server.
