### ISSUE TITLE
how to use JSONObjectWithData in frida's js code?

### ISSUE THREAD

**Issue by 3xp10it** [frida/frida#985]
I want to get dict/json type from string type in frida js code,below is my code:
```
var param_string="{'a':1,'b':2}"
var param_dict_nsstring=ObjC.classes.NSString.stringWithString_(param_string)
var jsonData=param_dict_nsstring.dataUsingEncoding_(4)
var err=ptr(ObjC.classes.NSError.alloc())
var dic=ObjC.classes.NSJSONSerialization.JSONObjectWithData_options_error_(jsonData,0,err)
console.log(dic)
```

but it didn't succeed,the last line `console.log(dic)` print `null`,that's to say `dic=ObjC.classes.NSJSONSerialization.JSONObjectWithData_options_error_(jsonData,0,err)`  didn't succeed,I think the wrong place is the third parameter `err` ,how can I call `ObjC.classes.NSJSONSerialization.JSONObjectWithData_options_error_` with the right way?
May be `var err=ptr(ObjC.classes.NSError.alloc())` is wrong?

Refer:
https://stackoverflow.com/questions/8356842/how-to-use-nsjsonserialization
https://developer.apple.com/documentation/kernel/1645411-anonymous/kniloptions?language=objc
https://developer.apple.com/search/?q=NSJSONSerialization
https://developer.apple.com/documentation/foundation/nsstring/1416696-datausingencoding?language=objc
https://developer.apple.com/documentation/foundation/1497293-anonymous/nsutf8stringencoding?language=objc

**Comment by lijiaxing1997** [comment]
Hello, have you solved this problem? I would like to ask how you did it?

**Comment by 3xp10it** [comment]
Solution:`https://stackoverflow.com/questions/57458375/how-to-pass-a-dict-parameter-from-python-to-frida-rpc-javascript-function`

**Comment by renzyang** [comment]
I got a similar problem, and I have to use the method `JSONObjectWithData_options_error_`.
Then I find a solution: [NSError problem. #729](https://github.com/frida/frida/issues/729).
It just works for me!

**Comment by lich4** [comment]
your code have two errors here.   
1. wrong json format:  not `"{'a':1,'b':2}"` but `'{"a":1,"b":2}'`
2. wrong usage NSError** for frida,  not alloc but Memory.alloc(8)

I paste right code here

```
NSString=ObjC.classes["NSString"];
NSJSONSerialization=ObjC.classes["NSJSONSerialization"];
ns=NSString.stringWithString_('{"a":1,"b":2}')
data=ns.dataUsingEncoding_(4)
dic=NSJSONSerialization.JSONObjectWithData_options_error_(data, 0, ptr(0))

```
