### ISSUE TITLE
How to hook a class function in side a module?

### ISSUE THREAD

**Issue by ballballsun** [frida/frida#99]
This is a .so opened by IDA
https://drive.google.com/file/d/0BwGeHEbQWswtZWszam5fWnBvNlU/view?usp=sharing

The module contain functions:
- function_5511
- Tosafe::function_5621(char *)

I use this code to hook function:
```Module.findExportByName("abc.so", "function_5511");```
I am able to hook function ```function_5511```

But
```Module.findExportByName("abc.so", "function_5621");```
Cannot hook the class function ```Tosafe::function_5621(char *)```

any way to do this?

**Comment by ballballsun** [comment]
solved by using Module.enumerateExports

**Comment by oleavr** [comment]
:+1:
