### ISSUE TITLE
Failed install frida-tools with pip on ubuntu 18.10

### ISSUE THREAD

**Issue by abrakadobr** [frida/frida#991]
Running pip installation works without any errors, but after no any frida commands exists:
![Screenshot_2019-08-19_13-52-34](https://user-images.githubusercontent.com/1707439/63244840-afa9ea80-c288-11e9-915e-693fa25deaf2.png)
no matter of pip/pip3 or sudo/"--user" option
pip install packets to ~/.local/lib/python3.6/site-packages, but /usr/local/bin/ not contains any frida scripts

**Comment by oleavr** [comment]
You need to add `~/.local/bin` to your `PATH`, or install it as `root`.

**Comment by abrakadobr** [comment]
@oleavr "moment you feel yourself unbelievably stupid" =) thanks a lot! exactly! =)
