### ISSUE TITLE
Can use frida for any address register read and write  ?

### ISSUE THREAD

**Issue by yehosjhwd** [frida/frida#997]
frida can help me any address register read and write ？
like this  
```
  .text:000228C6 64 44                       ADD             R4, R12
  .text:000228C8 0B D0                       BEQ             loc_228E2
  .text:000228CA 06 2D                       CMP             R5, #6
  .text:000228CC 09 D0                       BEQ             loc_228E2
  .text:000228CE 03 2D                       CMP             R5, #3
  .text:000228D0 02 D1                       BNE             loc_228D8
  .text:000228D2 A1 42                       CMP             R1, R4
  .text:000228D4 0E D3                       BCC             loc_228F4
  .text:000228D6 09 E0                       B                  loc_228EC
```
i want change R5 

it is very like [hookzz](https://github.com/jmpews/HookZz/tree/master) 
**ZzDynamicBinaryInstrumentation**
sorry, my english is poor, u know my mean? thanks

**Comment by yufengzjj** [comment]
use Interceptor.attach on the address and then access the regs by this.context in the onEnter function.

access x5 reg: console.log(this.context.x5)

im not sure whether it can write to the regs. I use it for monitoring values mostly,not change it

**Comment by yehosjhwd** [comment]
thanks
